### ISSUE TITLE
[Mac OS 11 Big Sur] Keepassxc Menu Icons Either Too Big or Stretched Horizontally

### ISSUE THREAD

**Issue by ecbrodie** [keepassxreboot/keepassxc#6139] opened 2021-02-18 00:38 UTC
_My apologies if this issue was already reported. I tried searching for a potential duplicate in advance but could not find one._

## Overview

Ever since I upgraded my Macbook to Mac OS 11.2.1 (Big Sur), I have noticed issues with the app icon on the top menu bar. When an app in my current display is focussed, the app appears abnormally larger than other icons. See this screenshot to illustrate (other icons to the right appear as comparison):

<img width="163" alt="icon_too_large" src="https://user-images.githubusercontent.com/1844664/108286563-4f368a80-7157-11eb-8ae6-626c846f2ae1.png">

If I am on a multi-display setup, the icon instead appears stretched horizontally. Here is a screenshot of that issue with the same set of icons:

![icon_stretched](https://user-images.githubusercontent.com/1844664/108286640-71300d00-7157-11eb-88bf-9b2df1e8883d.png)

## Steps to Reproduce

Nothing further to add, besides having the latest version of Keepassxc (2.6.4) installed on Mac OS Big Sur.

## Expected Behavior

App icon for Keepassxc appear at normal size.

## Actual Behavior

See above screenshots.

## Context

Debug Info from app:

```
KeePassXC - Version 2.6.4
Revision: 34a78f0

Qt 5.15.2
Debugging mode is disabled.

Operating system: macOS 11.2
CPU architecture: x86_64
Kernel: darwin 20.3.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
- libgcrypt 1.9.1
```

**Comment by droidmonkey** [comment] 2021-02-18 01:40
#6074 is duplicate of this

**Closed** 2021-02-18 01:42 UTC
Labels: bug

**Comment by ecbrodie** [comment] 2021-02-18 01:47
My bad. I'll follow that one. Thanks.
