### ISSUE TITLE
Make search shortcut work even if search bar is not visible

### ISSUE THREAD

**Issue by MarkKoz** [keepassxreboot/keepassxc#3650] opened 2019-10-22 01:02 UTC
## Summary
The search shortcut CTRL + F will not work if the search bar is not visible in the toolbar. This could be the case with a small window, especially if the button style is configured to show text.

## Desired Behavior
The search bar would be brought into focus when the shortcut is pressed and the user could begin typing their query.

## Possible Solution
Display the "extended" toolbar when the shortcut is pressed so that the search bar becomes visible.

Alternatives:

* Allow the extended toolbar to remain visible when the arrow button is pressed instead of retracting when the mouse moves away from it.
* Make the toolbar items re-arrangeable so that one could arrange the search bar to be visible.

## Context
The search feature is important to the efficient use of the program for users which have more than 5-10 entries in their database. Because of this situation, it means user have to choose between having text in the toolbar and being able to easily search; they cannot realistically have both unless the window is resized to be quite large (which is inconvenient and it some cases the search bar still wouldn't fit).

**Comment by droidmonkey** [comment] 2019-10-22 01:20
Duplicate of #550

**Closed** 2019-10-22 01:21 UTC
Labels: new feature
