### ISSUE TITLE
Minimizing/Opening the running instance from the executable, in pursuit of more i3 integration.

### ISSUE THREAD

**Issue by tkapias** [keepassxreboot/keepassxc#6760] opened 2021-07-22 14:09 UTC
## Summary
I would love to see a **new executable option (or core mechanism) to toggle between minimizing and opening KPXC** for the current KPXC instance. The purpose would be to bind the executable with a window manager like i3.

## Examples
1. Install KPXC with any configuration.
2. Launch KPXC with the --drop-down option : `# keepassxc --drop-down`
3. Run the same command a second time would act on the running instance and minimize it to tray if it is opened, or open it if it is minimized.

> Now you could bind KPXC to the TAB key in i3 : `bindsym $mod+Tab exec --no-startup-id keepassxc --drop-down`

## Context

- Many Linux users rely on **i3** for window management.
- When using the additional attributes, or editing a lot of information in KPXC, it is frequently necessary to minimize KPXC and then reopen it later by clicking on the icon in the notification area.
- With i3, this manipulation could be automated by calling the executable, with an option if needed, into a key binding.
- I use the same context with my terminal : `xfce4-terminal --drop-down`.
- Currently, the executable do not provide such options and it would launch a new instance, or if "Start only a single instance of KeePassXC" is checked, you will have an error message : 

```
# keepassxc
Another instance of KeePassXC is already running.
```

**Comment by droidmonkey** [comment] 2021-07-22 14:58
The xfce4-terminal option is different from what you think it is. That option is not toggling between minimized and visible, it is a special state window: https://docs.xfce.org/apps/xfce4-terminal/dropdown

We offer two shortcuts when KeePassXC is visible and focused:
* Ctrl + M - Minimize Window
* Ctrl + Shift + M - Hide window to system tray, if enabled

Doesn't i3 offer a native way to signal to minimize/maximize windows? This is technically a window manager function so it should offer that capability natively.

**Comment by tkapias** [comment] 2021-07-22 15:10
- For xfce4-terminal, it's true, I didn't look too much into it, but I use it for the toggle because it locks the executable call to the same instance.

- I know the shortcuts, but it means that I have to use 2 different shortcuts, with a different structure to call back the KPXC window and hide it.

- With i3 there is a way to hide/minimize the focused window to a scratchpad, then with the same key you can call it back. But there is only one scratchpad, and all the window that you send here share it. I use it more like a dirty quick hide and don't want to save it for a main app that I use all the time like KPXC.

**Comment by droidmonkey** [comment] 2021-07-22 15:15
This is a duplicate of #4507

**Closed as completed by droidmonkey** 2021-07-22 15:15 UTC
Labels: duplicate

**Comment by michaelk83** [comment] 2021-07-22 15:19
I think this is more about having single-instance mode switch to the already running instance instead of complaining with "Another instance of KeePassXC is already running.". Anyway, still a duplicate.

**Comment by droidmonkey** [comment] 2021-07-22 15:24
> I think this is more about having single-instance mode switch to the already running instance instead of complaining with "Another instance of KeePassXC is already running."

It does switch to the running instance. That is not a complaint just an info message

**Comment by tkapias** [comment] 2021-09-08 11:41
An internal solution to this issue is still opened in #4507 as a new feature request. 

I'm just editing this issue to add a specific solution for the i3wm users.

I wrote a small script to toggle between 3 states for any identified window :

1. If the window is active the script will close it, for a configured KeepassXC it will just minimize.
2. If the window is opened but not active, it will bring it to the current workspace and focus on it.
3. Else it launch the executable with the same name.

You need 3 dependencies : i3wm, xdotool, wmctrl

The script : 

```shell
#!/usr/bin/env sh
WinLookupName=$1
ActiveWinId=$(printf 0x0%x $(xdotool getactivewindow))
LookupWinId=$(wmctrl -lx | grep -i $WinLookupName\.$WinLookupName | awk '{print $1}')

if [ $LookupWinId = $ActiveWinId ]; then wmctrl -x -c $WinLookupName; else wmctrl -x -R $WinLookupName || $WinLookupName; fi
```

The command lines for i3wm (~/.i3/config) : 

```
for_window [class="KeePassXC"] floating enable, resize set width 80 ppt, resize set height 80 ppt, move position center, sticky enable
bindsym $mod+x exec --no-startup-id sh -c "/script_path/script_name.sh keepassxc"
```
