### ISSUE TITLE
Latest firefox update (firefox-71.0-8.npgo) appears to disable key KeePassXC functions

### ISSUE THREAD

**Issue by barkeratGitHub** [keepassxreboot/keepassxc#3996] opened 2019-12-09 14:22 UTC
I applied the latest Firefox update (firefox-71.0-8.npgo) on F30 this morning (2019-12-09). I know KeePassXC 2.5.1 was working yesterday morning because I used it successfully to populate login fields; also, I noted that the Firefox update was available yesterday but I did NOT apply it until this morning.

This morning, after applying the Firefox update, I've noted on several login attempts on multiple websites that KeePassXC won't/can't populate the login fields. The icon is still in the toolbar, I can still use it to open the KeePass database so I can log in, but it doesn't detect login fields--automatically or manually--and it doesn't populate them. However, I also use Blur (for generating random email addresses, not for password management), and the password fields still show with the Blur icon, but not the KeePassXC icon.

Because of the new NPGO edition of Firefox, I'm suspicious that something in the API (due to NPGO?) has changed that has partially neutered KeePassXC, as it can only connect to and open the database, but not apply login credentials.

**Comment by droidmonkey** [comment] 2019-12-09 14:46
Duplicate of issues over on the browser issue board.

**Closed by droidmonkey** 2019-12-09 14:46 UTC
