### ISSUE TITLE
Unlocking database with plugged-in Yubikey NEO freezes it until re-plug

### ISSUE THREAD

**Issue by sleeksorrow** [keepassxreboot/keepassxc#4464] opened 2020-03-23 15:38 UTC
## Initial situation

My database does not have a Yubikey configured, and I do not want to use KeepassXC with my Yubikey. But I need my Yubikey NEO to access the destination systems, and KeepassXC only needs to give the password for the systems.

## Expected Behavior
When unlocking the database I expect that it's unimportant if my Yubikey NEO is plugged in or not, because my database does not need it.

## Current Behavior
When I unlock my database without Yubikey NEO plugged in, all is fine. But when the Yubikey NEO is already plugged in when I see the unlock screen, KeepassXC tries to communicate with it. Obviously it fails to do that. But afterwards my Yubikey is not usable anymore. When I then paste the password into the login mask and press the button on my yubikey it does not paste the OTP. This stays this way until I re-plug it.

## Possible Solution
I would be satisfied when I just could configure KeepassXC to disable Yubikey usage completely. If it does not communicate with the key it cannot crash it. But of course it would be best if KeepassXC would not crash the key at all.

## Steps to Reproduce
1. Plug in a Yubikey NEO
2. Open KeepassXC until you see the unlock screen
3. Notice that there is a moving dotted line below "Challenge-Response" presumably visualizing communication to the Yubikey
4. Open a text editor and press the button on the Yubikey.
5. Notice that no OTP is printed, the light of the Yubikey stays off and you cannot use it anymore
6. Re-plug the Yubikey and press the button again
7. Notice that the OTP is printed again.

## Context
This bug causes me to create failed logins all the time because I don't realize quickly enough that my Yubikey is not working. Re-plugging it at every failed login is cumbersome

## Debug Info
KeePassXC - Version 2.4.3
Revision: 5d6ef0c

Libraries:
Qt 5.12.5
libgcrypt 1.8.5

Operating system: Ubuntu Focal Fossa (development branch)
CPU architecture: x86_64
Kernel: linux 5.4.0-18-generic

Enabled extensions:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare (only unsigned sharing)
- YubiKey

**Comment by droidmonkey** [comment] 2020-03-23 15:53
Upgrade to 2.5.3 please

**Comment by sleeksorrow** [comment] 2020-03-23 15:57
Ubuntu Focal is too old? Ouch... anyway, thanks.

**Comment by droidmonkey** [comment] 2020-03-23 16:42
You can use the AppImage as well... Check our releases.

**Comment by sleeksorrow** [comment] 2020-03-24 08:46
That was kind of helpful... in the way that I can now confirm that 2.5.3 is also affected. Same reproduction, plug in key, open keepassxc, key is frozen.

**Comment by droidmonkey** [comment] 2020-03-24 13:22
Good to know, I believe this is a repeat of another issue about locking Yubikey from use elsewhere.

**Comment by droidmonkey** [comment] 2020-03-28 18:29
Duplicate of #1215

**Closed by droidmonkey** 2020-03-28 18:29 UTC
Labels: more info needed
