### ISSUE TITLE
The "Open" button on an attachment fails to actually open the file

### ISSUE THREAD

**Issue by facundobatista** [keepassxreboot/keepassxc#9896] opened 2023-10-04 19:58 UTC
**NOTE 1**: this is very similar to a recent post but I'm not using Snap anymore and the problem is different

**NOTE 2**: names may vary, I see the interface in Spanish, don't know how to put it in English.

## Overview

I have an entry with attachments in the "advanced" tab.

 I select a file (jpeg, pdf, etc), click on the "Open" button, and it does NOT open the file, but produces an obscure error shown in a pop up windows (attached here).

## Steps to Reproduce
1.  Create an entry
2. Go to "advanced"
3. in the lower half, "attachments", click on "Add"
4. select a file from your disk, click in OK, the name and size of the file will appear in the attachment list
5. "select" the file (click on it, the row will highlight)
6. click on the "Open button"

## Expected Behavior

It should start an external program passing the selected file, probably `xdg-open` so the file is opened with whatever is configured in the system.

## Actual Behavior

A pop up window appears (attached here) saying "Error - KIO client" and with a path as the text in the window. Note that this path is actually valid (if I open manually that path with `xdg-open` it's ok).

## Context
```
KeePassXC - Versión 2.7.6
Revisión: dd21def
Distribución: AppImage

Qt 5.15.2
Modo de depurado deshabilitado.

Sistema operativo: Ubuntu 22.04.3 LTS
Arquitectura de CPU: x86_64
Núcleo: linux 5.15.0-84-generic

Extensiones habilitadas:
- Autoescritura
- Integración con navegadores
- Agente SSH
- KeeShare
- YubiKey
- Integración con servicio de secretos

Librerías criptográficas:
- Botan 2.19.1
```

**Comment by droidmonkey** [comment] 2023-10-04 21:35
Duplicate of #8721

**Closed as not planned by droidmonkey** 2023-10-04 21:35 UTC
