### ISSUE TITLE
request: Sort entries manually

### ISSUE THREAD

**Issue by maowm** [keepassxreboot/keepassxc#543] opened 2017-05-04 14:38 UTC
I am expecting, if you will, sort entries manually feature being added as a another way of sorting the Entries Table. Or a way of sorting by date added to the group or by topics inside the group.
Have a great time.

**Comment by krejvl** [comment] 2017-11-27 08:35
Hello guys, I would like to vote for this feature too - I used Windows Keepass (over mono) which has this feature and I miss it quite a lot in KeePassXc. Or at least sorting by the date added to the group.

**Comment by stdedos** [comment] 2019-03-28 10:52
Duplicate of https://github.com/keepassxreboot/keepassxc/issues/2295

**Closed** 2019-03-28 12:15 UTC
Labels: new feature
