### ISSUE TITLE
Corrupted database after 'save on exit' of locked db

### ISSUE THREAD

**Issue by Sparlie** [keepassxreboot/keepassxc#3828] opened 2019-11-09 19:52 UTC
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Able to open a pre-locked database after reopening KeePassXC.
No re-save of already locked/saved database, or no corruption if re-saving anyhow.

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
KeePassXC exits and all seems well, but trying to log in to the database next time you open KeePassXC, it fails with this error banner:
Error while reading the database: Invalid credentials were provided, please try again.
If this reoccurs, then your database file may be corrupt. (HMAC mismatch)

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )
Not really a solution, but when trying to resolve this problem, I found #639, which looks very similar.  Perhaps the underlying issue is the same, just in another location?

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. Create a new database in KeePassXC
2. Lock the database
3. Exit KeePassXC
4. Open KeePassXC
5. Try to unlock the database from step 1

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )
I just installed KeePassXC for the first time, and was testing how it worked.  The 'save on exit' setting sounded good, but unchecking that setting is the only way I have found to work around the issue.  This is obviously not ideal, since the only way to uncheck it is to also not auto-save anything else.

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.5.0
Revision: 1ab8a9f

Qt 5.5.1
Debugging mode is disabled.

Operating system: Ubuntu 16.04.6 LTS
CPU architecture: x86_64
Kernel: linux 4.4.0-166-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.1

![Settings](https://user-images.githubusercontent.com/57572712/68534252-327a9880-0300-11ea-9b1b-3b1fc68a4ccd.png)

**Comment by phoerious** [comment] 2019-11-09 20:56
Do you have a key file or did you enter the KDBX file name in the key file field?

**Comment by Sparlie** [comment] 2019-11-09 21:08
I didn't use either of the additional credentials options at all, when creating it or when trying to re-open it, just a basic database to test.

**Comment by droidmonkey** [comment] 2019-11-09 21:19
Likely mistyping password

**Comment by Sparlie** [comment] 2019-11-09 21:39
I reproduced it on three separate new databases, with the password visible to make sure it was right.

**Comment by droidmonkey** [comment] 2019-11-09 22:21
Do you have a Ryzen 3000 processor that requires updated firmware?

**Comment by wiscor** [comment] 2019-11-10 12:05
I'm having this exact issue. I've found is that it only happens with a database I'm trying to open from my google drive. If I try opening the exact same database that I've save locally it works fine. Is it a cloud stored database issue?

**Comment by droidmonkey** [comment] 2019-11-10 13:10
You both need to provide far more information about how you are storing the database file, the programs you are using to do that, etc etc.

**Comment by wiscor** [comment] 2019-11-10 14:09
I don't know what else to add. My laptop in Kubuntu and my desktop is Windows 10. Keepass settings are all default. I could not even open the google drive database after the 2.5 upgrade. I copied the database file locally to the Kubuntu laptop and the Windows 10 desktop. Both then open fine. I made a copy of the database and renamed it and opened locally, it worked fine. I uploaded it to my drive and get the error when trying to open.

**Comment by dxdc** [comment] 2019-11-10 14:27
> I've found is that it only happens with a database I'm trying to open from my google drive

I've experienced similar corruption issues with Google Drive (in general) and unrelated to this post. I find it generally unreliable for Cloud storage and syncing. Here's just one example: https://www.scss.tcd.ie/joeran.beel/blog/2019/04/02/google-file-stream-a-horror-story-with-corrupted-files-and-more/

I think at least part of the problem can be what happens if Google Drive (or Insync in your case) starts syncing at the moment the database is also trying to write the file. I think this happens, at least in part, because it detects a change to the file although the final write is still incomplete when the sync starts.

One idea, though (@droidmonkey not sure if it's already implemented?) is to add a lock when writing files. There's no guarantee it would solve this problem, but generally it could be helpful in these kind of scenarios. The other thing that could be helpful is to perform a CRC check before writing the file, then, separately read in the database and perform another CRC check after it's finished. If the two don't match, provide the user with an error that the database could not be written.

**Comment by Sparlie** [comment] 2019-11-10 16:03
I have an Intel Core i5, and was only saving locally.  Really very basic, and it seemed crazy that it was causing a problem.

That said, I'm not sure what to say right now.  Initially, I installed KeePassXC, created a database, and played around with it a little.  The next day, I went to open it, and got the error.  Created a new database, locked, exited, tried to reopen, error.  Did that another two times.  Unchecked the save on exit option, created a new database, locked, exited, reopened fine, posted this bug.  Later in the day, rechecked the save on exit option and tried the steps again to make sure I didn't mix something up...  Couldn't reproduce the error.  Tried a few more variations today, including fully uninstalling and reinstalling fresh, in case that had something to do with it, and still can't seem to reproduce it.  So I have no idea what happened.  But it sounds like there might be issues with sync-based saving, so hopefully this helps resolve them, at least!

Just for reference, if I wind up with a corrupt database issue again, is there a way to repair it?  I have found instructions for the original KeePass, but not for XC.  This time, I had nothing saved in it, so just restarting doesn't matter, but that shouldn't always be the case!

**Comment by droidmonkey** [comment] 2019-11-10 16:35
If the database file is truly "corrupt" there is absolutely nothing you can do, unfortunately, besides loading a backup.

**Comment by wiscor** [comment] 2019-11-10 16:58
I would like to add that I'm running KeePass2Android on my Google Pixel 2 and it will open the cloud stored database fine.

**Comment by droidmonkey** [comment] 2019-11-10 19:11
Well that is good to know. Have you tried manually copying the kdbx file from your mobile to your desktop/laptop? Maybe try a different sync service like dropbox.

**Comment by hifi** [comment] 2019-11-12 06:09
If it's a sync issue you can also use [Google Drive in your browser](https://drive.google.com/) to download a "clean" copy to verify it.

**Comment by peron** [comment] 2020-01-06 19:30
I have the same problem.
It's an old password file I've been using for about a year, manually coping between different devices; home computer, private cell phone (Android), and my company laptop. It's been working flawlessly on all devices, continually updating the file.
Over X-Mas I updated my home computer to Ubuntu 19.10. Updated KeePassXC to 2.5.1, AppImage installed with AppImageLauncher.
The same file, that has been working for a year, suddenly becomes corrupt when closed (no changes done), and can't be opened again. File attributes also show no changes, only access time has been updated. Very annoying, since I now can't update the file on my home computer (which is the master for this file. I have another file for which the work computer is the master)!

**Comment by droidmonkey** [comment] 2020-01-06 20:20
There were no writes at all to the file?

**Comment by peron** [comment] 2020-01-06 20:34
Alright, so I've been playing around a little bit, and I can now easily reproduce it.
It also occurred to me, that I had forgotten one thing I did. Since the Android app associates other URLs with my entries, I merged two files (phone + home) into a NEW password file, ie create new, merge first, then merge second.

So, to reproduce, create a new file, selecting **KDBX 4.0 (Recommended)** as the database format. Create an entry, save, close, and try to re-open. Not working!

Doing the same thing, but selecting **KDBX 3.1** as the database format, does not show the same problem, and seems to be working so far.

My old, one-year-old file, was created with KDBX 3.1. My newly created merge had KDBX 4.0.

If I merge my two files by merging one INTO the other, ie. keeping the KDBX 3.1 format, it works. Selecting KDBX 3.1 for the new file would work as well.

Conclusion: There's something fishy with the KDBX 4.0 database format, or how KeePassXC (2.5.1) handles it! (Maybe only write is implemented and not read, or vice versa! :rofl: )

**Comment by peron** [comment] 2020-01-06 20:44
> There were no writes at all to the file? What do you mean by "the master" file?

The home computer is "the master" for that file. I don't edit it anywhere else. Until recently, at least, when I figured out how to add Android URLs to the entries on my phone. But I've always lost them, since the home computer was the master, and I've only copied in one direction **home computer** -> **phone** -> **work computer**. Until my _NextCloud_ is up and running, I've now tried merging files for the first time.

**Comment by droidmonkey** [comment] 2020-01-06 20:56
There is nothing fishy with the kdbx 4.0 implemention. If so there would be thousands of people with this issue, myself included. Additionally this code is tested very thoroughly with our unit tests and gui tests. The simple matter of `new -> save -> lock -> corrupt` is troubling, but totally unreproducible. Any additional amplifying details you may have?

**Comment by peron** [comment] 2020-01-06 21:27
> There is nothing fishy with the kdbx 4.0 implemention. If so there would be thousands of people with this issue, myself included. Additionally this code is tested very thoroughly with our unit tests and gui tests. The simple matter of `new -> save -> lock -> corrupt` is troubling, but totally unreproducible. Any additional amplifying details you may have?

Not really. I'm on Ubuntu 19.10 Desktop, just fresh installed, and with all updates applied. I did go for the new install on ZFS, though. But I had the same problem when the password file was on my external HDD. External HDD is formatted with NTFS. I run the AppImage, version 2.5.1. With earlier versions, especially installed using Snap, I had problems when the file was on my external HDD. Then the file couldn't be found.

I'm not 100% sure how AppImages work, but shouldn't all dependencies be in there? So there shouldn't be a conflict with locally installed libraries, right?

**Comment by droidmonkey** [comment] 2020-01-11 01:00
This may be fixed by #4147

**Comment by phoerious** [comment] 2020-01-11 10:22
This issue is about KDBX 4 though. Unless there is another edge case where that is also affected and in a way where no in-between key change is required, this fix shouldn't apply.

**Comment by droidmonkey** [comment] 2020-01-11 13:36
> Later in the day, rechecked the save on exit option and tried the steps again to make sure I didn't mix something up... Couldn't reproduce the error. Tried a few more variations today, including fully uninstalling and reinstalling fresh, in case that had something to do with it, and still can't seem to reproduce it. 

This part of @Sparlie response points me to a hardware issue, most likely RAM. Whenever we see random corruption (without changing a password) or inability to properly transform a key it is a hardware issue. Especially with harder algorithms like Argon2 that use more of the resources and can trigger the fault.

I am closing this issue unless a bonified replication can be made using "demo" databases.

**Closed by droidmonkey** 2020-01-11 13:36 UTC
Labels: not reproducible

**Comment by Dakhaasje** [comment] 2023-09-15 12:22
Closed? godver. what is the use of a password database when it becomes unusable when it locks up !?
