### ISSUE TITLE
Bad font for revealed passwords and notes

### ISSUE THREAD

**Issue by jmbreuer** [keepassxreboot/keepassxc#10277] opened 2024-02-07 08:24 UTC
## Overview

KeePassXC does not use the system preference fixed pitch font to display its fixed pitch password and notes fields.

## Steps to Reproduce
1. navigate to an entry (with password and notes)
2. reveal its password

## Expected Behavior
Password and notes should be easily readable - my use case is copying down some of that information into an authentication device.
Ideally, there should be a setting or at least config file entry to choose a specific font, for those fields only. In lieu of that, at least the system fixed font preference should be honored.

## Actual Behavior
Both the revealed password and the notes field are rendered in a font that I find particularly small and hard to read. Changing the system wide fixed font does not affect this:

![Selection_134](https://github.com/keepassxreboot/keepassxc/assets/1792037/125f438f-a853-45d5-8db4-d7d5227b10d7)

(I've quit and restarted KeePassXC right before taking this screenshot.)

## Context

KeePassXC - 2.7.6
Revision: dd21def

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux (gentoo 17.1 current amd64)
Desktop Env: KDE (Plasma 5.27.10, Qt 5.15.12)
Windowing System: X11 (X.org 21.1.11)

**Comment by jmbreuer** [comment] 2024-02-07 08:52
Launching KeePassXC with `QT_SCALE_FACTOR=1.2 keepassxc` somewhat works around that issue, which immediately brings up another question: How would I get that setting to apply to KeePassXC as it is auto-started with my KDE session? (Without turning all my other applications into Teletubbyland.)

Also, I'd say this is an accessibility issue, but I guess I can't add that label as the reporter.

**Comment by droidmonkey** [comment] 2024-02-07 12:41
Hello, the font size is based on your overall system font size (the first box in your font screenshot). Using QT_SCALE_FACTOR is rather easy for startup, you will have to edit the `~/.config/autostart/org.keepassxc.KeePassXC.desktop`.

This report is a duplicate of a couple other issues, please watch those as we are going to make improvements to this experience in 2.8.0.

#6822 
#2741

**Closed as completed by droidmonkey** 2024-02-07 12:41 UTC
Labels: duplicate

**Comment by jmbreuer** [comment] 2024-02-07 14:00
Ooph, what's keeping KeePassXC from using the system fixed/mono setting for its fixed/mono fields? I still consider this a bug, and would prefer the issue to remain open.

Changing the 'General' font setting does work - insofar, thank you for your suggestion!

It does, however, also scale up _all other_ Text in the application, turning it into Teletubbyland something fierce. And the particular choice of fixed font for the password and note fields is still 'bad' and not what I have in system defaults at all. It looks like an old school X11 mono font, that's not used anywhere else in my desktop environment. With really bad antialiasing on top.

To (at least) only apply the font size setting to KeePassXC as a workaround, I found adding the following lines in `~/.config/keepassxcrc` work:

```ini
[General]
font=Noto Sans,12,-1,5,50,0,0,0,0,0,Regular
```

**Comment by droidmonkey** [comment] 2024-02-07 14:06
Refer to the issues I linked that are duplicates of your report. Add your comments there if there is some context missing, but this one is now back-linked to those as well.

How do you have KeePassXC installed? Flatpak? Snap? Native?

**Comment by jmbreuer** [comment] 2024-02-07 14:17
It's a native distribution package (ebuild) on gentoo.
