### ISSUE TITLE
Search should include KP2A_URL* by default

### ISSUE THREAD

**Issue by koelle25** [keepassxreboot/keepassxc#10027] opened 2023-11-16 08:33 UTC
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
If I use the "Browser integration" entry tab for additional URLS (e.g. when a login is valid for multiple sites) I want to be able to find those entries in my database by searching for (parts of) the URL.

Currently when using the Search field inside the application (the one at the top right) it seems that only the normal URL field is included in the search. Additional URLs added via "Browser integration" entry tab (which end up as KP2A_URL* attributes) do not get found.

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )
Here is an Example database with an entry for some of the different sites of the Stackexchange network:
![Bildschirmfoto vom 2023-11-16 09-20-58](https://github.com/keepassxreboot/keepassxc/assets/915514/02aa7d8b-40dd-44c8-98de-fbd4a1b921de)

If I now search for "_serverfault_" I would expect this entry to be found. Instead I get "No Results":
![Bildschirmfoto vom 2023-11-16 09-22-01](https://github.com/keepassxreboot/keepassxc/assets/915514/69777e1f-73b7-4287-a546-412e78f3d42b)

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
There are different use cases for this. One example is mentioned above. Another one would be company and school credentials, which most of the time are valid for multiple of the services they provide for their employees/students.

For the user it's not feasible to always remember the "main" URL of a saved login to find it. Changing the search term to "_attr:serverfault_" works, but is also not really viable in everyday use. IMO you would expect KeepassXC to find entries by any URL term, be it in the main URL or additional URLs.

This could be doable relatively easy, as a connected Browser already find's these entries without a problem - which of course is the whole point of these "Browser integration" additional URLs/KP2A_URL* attributes.

**Comment by droidmonkey** [comment] 2023-11-16 11:26
Duplicate of #5066

**Closed as not planned** 2023-11-16 11:26 UTC
Labels: duplicate, feature: Search

**Comment by koelle25** [comment] 2023-11-16 11:28
Ah thanks. I was looking for an existing issue but didn't find this one.

**Comment by droidmonkey** [comment] 2023-11-16 11:35
It was missing the search label 😃 fixed that
