### ISSUE TITLE
Global Auto-Type deactivated on Windows 10

### ISSUE THREAD

**Issue by ivostoykov** [keepassxreboot/keepassxc#6252] opened 2021-03-09 11:08 UTC
## Overview
After some time the Global Auto-Type shortcut key is deactivated under Windows 10.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Setup a Global Auto-Type in Settings
2. Use it for a while (I didn't find any time pattern in this, It might happen in the next few hours or days)
3. Shortcut is disabled.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Once set, to remain persistent

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Auto-Type is disabled after a while.

## Context
[NOTE]: # ( Give us any additional information you may have. )
This behaviour was noticed only under Windows 10. Works fine under Ubuntu 20.04

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.4
Revision: 34a78f0

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10

## Debug Info
KeePassXC - Version 2.6.4
Revision: 34a78f0

Qt 5.15.2
Debugging mode is disabled.

Operating system: Windows 10 Version 2004
CPU architecture: x86_64
Kernel: winnt 10.0.19041

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
- libgcrypt 1.9.1-unknown

**Comment by droidmonkey** [comment] 2021-03-09 11:26
You most likely set the key combo to something that conflicts with another program. Choose a different key combo. Closing since this is not reproducible with the current information provided.

**Closed by droidmonkey** 2021-03-09 11:26 UTC
Labels: bug
