### ISSUE TITLE
Auto-Type: Password only [Ctrl]+[Alt]+[Shift]+[A]

### ISSUE THREAD

**Issue by ccoenen** [keepassxreboot/keepassxc#3108] opened 2019-05-02 05:48 UTC
[KeePass 2.42 introduces](https://keepass.info/news/n190501_2.42.html) (see "New Features" bullet point 2) a Global Auto-Type variation that only types the password. This is useful for occasions where you just need to verify you're yourself. Some admin interfaces do this when you're already logged in but attempt a security critical action.

(edit: this also comes with a matching command line parameter `-auto-type-password` that does the same, so this feature request also extends to this)

**Comment by droidmonkey** [comment] 2019-05-02 12:27
Duplicate of #2093

**Closed by droidmonkey** 2019-05-02 12:27 UTC
Labels: new feature
