### ISSUE TITLE
No connect between KeePassXC-Browser and KeePassXC Portable

### ISSUE THREAD

**Issue by GeoChallenger** [keepassxreboot/keepassxc#1817] opened 2018-04-06 06:41 UTC
## Expected Behavior
KeePassXC-Browser should connect to KeePassXC Portable Edition using new browser integration

## Current Behavior
KeePassXC-Browser says: "Timeout or not connected to KeePassXC"
It works with installed KeePassXC but does not work using the Portable Edition of KeePassXC.
Switching off the proxy feature, a new KeePassXC window pops up for a few seconds and closes again.

Legacy Browser Integration works with both KeePassXC editions.
Tested using Firefox 59.0.2 and Chrome 65.0.3325.181

Using the proxy feature I can see the keepassxc-proxy.exe process is triggered. But the expected window to allow the connection to KeePassXC does not come up.
I have checked the points of @varjolintu  in #1559 - all is fine but no connect...

## Debug Info
KeePassXC - Version 2.3.1
Revision: 2fcaeea

Bibliotheken:
- Qt 5.10.1
- libgcrypt 1.8.2

Betriebssystem: Windows 7 SP 1 (6.1)
CPU-Architektur: x86_64
Kernel: winnt 6.1.7601

Aktivierte Erweiterungen:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by GeoChallenger** [comment] 2018-04-06 07:42
Registry entry points to the native messaging json script file in the folder of the portable version.
KeePassXC.exe, native messaging json script and keepassxc-proxy.exe are in this folder.
Path in the native messaging json script file points to this folder and keepassxc-proxy.exe

Checking the Windows task manager I can see the keepassxc-proxy.exe starting when the browser addon wants to connect but nothing happens to KeePassXC...

All requirements seem to be correct but no connect.

**Comment by varjolintu** [comment] 2018-04-06 07:59
What does the browser debug console say?

**Comment by varjolintu** [comment] 2018-04-08 08:02
Just tested this today and I cannot reproduce the problem. Does it help if you disable your browser support from the settings and enable it again?

**Comment by GeoChallenger** [comment] 2018-04-09 05:49
No, it does not help. I've meanwhile tried it on different computers... always same result.
BTW, I'm using KeePassXC Portable and Browser Portable (I never install an application if a portable version is available).

**Comment by varjolintu** [comment] 2018-04-09 06:09
Well, using portable Firefox can change things. I need to test it myself.

**Comment by QuibblingAsh42** [comment] 2018-04-11 17:42
Just dropping by as searching for my similar issue lead me here. I've also just started trying out using the portable versions of both apps and having the same problem.  Looking through the wiki, I think the main issue is figuring out where the json file goes since Portable FF doesn't read the registry for that location and there is no native-messaging-hosts directory to place the json into.  

BTW, I've confirmed that Portable FF isn't reading the registry.  I'm using this on my work computer where I also have Firefox installed natively.  The registry entry is there, but connecting the two applications still isn't working.

**Comment by droidmonkey** [comment] 2018-04-11 18:34
You can create the native messaging directory where the portable app is reading your profile data. That should be sufficient.

**Comment by QuibblingAsh42** [comment] 2018-04-11 21:08
I tried creating a native-messaging-hosts folder in:

FirefoxPortable\Data\profile
FirefoxPortable\App\Firefox

Same results.  Am I in the wrong directory?

**Comment by droidmonkey** [comment] 2018-04-12 03:39
Possibly, in a typical Linux install it is located in ```~/.mozilla/native-messaging-hosts``` and on Windows it is in the registry.

**Comment by varjolintu** [comment] 2018-04-12 13:46
I'm pretty sure a solution depends on tweaking things like this:
[https://portableapps.com/manuals/PortableApps.comLauncher/topics/registry.html](https://portableapps.com/manuals/PortableApps.comLauncher/topics/registry.html)

**Comment by djibux** [comment] 2018-09-24 11:19
I was experiencing the issue on Windows 10.
Switching off the proxy works for me.

The registry keys are listed [here](https://wiki.mozilla.org/WebExtensions/Native_Messaging).  On my computer KeepassXC creates the following key: `HKEY_CURRENT_USER\Software\Mozilla\NativeMessagingHosts\org.keepassxc.keepassxc_browser`.

**Comment by varjolintu** [comment] 2018-12-21 15:19
I finally had some time to check on this issue.

With KeePassXC portable I added the following entries to `[RegistryKeys]` in `KeePassXCPortable.ini`:
```
[RegistryKeys]
-=HKCU\Software\QtProject\OrganizationDefaults\FileDialog
chrome=HKCU\Software\Google\Chrome\NativeMessagingHosts
chromium=HKCU\Software\Chromium\NativeMessagingHosts
firefox=HKCU\Software\Mozilla\NativeMessagingHosts
vivaldi=HKCU\Software\Vivaldi\NativeMessagingHosts
```

With this the browsers enabled in the Browser Integration settings are written correctly in the registry, which means the portable Firefox can also find them (FYI, portable Firefox works with normal KeePassXC). After this the Native Messaging script files are also saved in the portable KeePassXC directory.

The only thing that doesn't work is the Named Pipe keepassxc-proxy uses to communicate with KeePassXC. When inspecting what pipes were open, normal KeePassXC opens a listener to pipe in location `C:\Users\<user>\AppData\Local\Temp\kpxc_server`. And portable KeePassXC opens the pipe in ``C:\Users\<user>\AppData\Local\Temp\KeePassXCPortableTemp\kpxc_server`. Currently I haven't found a way to "map" this location to the other, and keepassxc-proxy doesn't handle any custom locations to temp directory.

**Comment by djibux** [comment] 2018-12-27 12:18
Thank you for looking into that.
As I mentioned earlier, I think it also makes sense to cleanup those registry keys using `[RegistryCleanupIfEmpty]`.

**Comment by HyperMac** [comment] 2019-03-06 07:45
@djibux  
I just registered to say thank you for the tip with registry.
In my case for chrome it was under
`HKEY_CURRENT_USER\Software\Google\Chrome\NativeMessagingHosts\org.keepassxc.keepassxc_browser`
And it was pointing to the wrong location.

**Comment by justPoppingIn** [comment] 2019-03-06 18:47
Hello,
I have a setup of two computers, both Windows 10. One is 32-bit, the other is 64-bit. Both run Firefox Portable and KeePassXC Portable.
I had no issues during setup on the 64-bit Windows, the proxy configuration worked out of the box.
Under 32-bit Windows, I have the same issue as described above. Switching off the proxy works.
Is there any chance this will be fixed? I'm willing to help, if more debug information is needed for any configuration.
Kind regards,

**Comment by varjolintu** [comment] 2019-03-07 11:14
@justPoppingIn Can you check if the NativeMessagingHosts folder location differ under your 32-bit system?

**Comment by justPoppingIn** [comment] 2019-03-07 18:33
I just checked on both systems and there is no NativeMessagingHosts folder.
I searched the subtree of 'FirefoxPortable' and 'KeePassXCPortable' on 64-bit and 32-bit Windows for the phrase 'native'. Got no results...
Cross-checked with search phrase 'extensions' and found file and folder in 'FirefoxPortable'...

**Comment by pigsflew** [comment] 2019-10-04 13:42
Why doesn't KeepassXC simply double-check and potentially rewrite these registry keys to be its own installation's location?

**Comment by varjolintu** [comment] 2019-10-04 14:08
@pigsflew Because no one hasn't done the fix yet. I'm quite sure the fix isn't hard to do, but needs some testing.

For the devs: It might be enough to remove the check from https://github.com/keepassxreboot/keepassxc/blob/develop/src/browser/HostInstaller.cpp#L112, but I'm unable to test that at this moment.

**Comment by droidmonkey** [comment] 2019-10-04 17:37
concur with removal of the check. Also the one below it for the removal of settings is not necessary.

**Closed** 2019-10-05 17:59 UTC
Labels: bug, platform: Windows, plugin: Browser integration
