### ISSUE TITLE
KeePassXC 2.2.4 - Cannot open downloaded disk image on mac.

### ISSUE THREAD

**Issue by JulianSchoenbaechler** [keepassxreboot/keepassxc#1476] opened 2018-02-12 13:36 UTC
## Expected Behavior
I should be able to install KeePassXC on my Mac (Yosemite). The disk image (.dmg) downloaded from the 'Download' page of the website or from the release tab here on GitHub can not be opened.

## Current Behavior
The DiskImageMounter throws an `corrupt image` error. Opening the image through the Disk Utility from terminal is also not possible.
![screen shot 2018-02-12 at 14 20 48](https://user-images.githubusercontent.com/10711264/36099198-08990f58-1002-11e8-8030-6e7240f9cf9a.png)

## Possible Solution
Maybe this is a not compatible image file for my OS.

## Steps to Reproduce (for bugs)
1. Download KeePassXC 2.2.4 for MacOS 10 or newer on Yosemite.
2. Try to open the .dmg

## Context
Id'l like to update from the currently installed version (2.2.2) to the latest.

## Debug Info
**(my current version of KeePassXC)**
KeePassXC - Version 2.2.2
Revision: 6d46717

Libraries:
- Qt 5.9.1
- libgcrypt 1.8.1

Operating system: OS X Yosemite (10.10)
CPU architecture: x86_64
Kernel: darwin 14.5.0

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

**Comment by TheZ3ro** [comment] 2018-02-12 14:06
Duplicate of #1344, next time please use the search function also on closed issues

**Comment by TheZ3ro** [comment] 2018-02-12 14:07
@phoerious @droidmonkey we should edit the website explicitly saying this

**Closed by TheZ3ro** 2018-02-12 14:06 UTC
