### ISSUE TITLE
Search Results Disappear, but preview remains on screen

### ISSUE THREAD

**Issue by vraravam** [keepassxreboot/keepassxc#2691] opened 2019-02-11 02:24 UTC
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
I am testing out the 2.4.0-beta1, and (I dont know when/why), but the search results seem to disappear after some time. This is good (from a privacy perspective), but, the preview pane still shows the selected search result details.

## Current Behavior
Preview pane still shows the details of the entry that was selected after searching.

## Possible Solution
If the disappearance of the search results is intentional ie a feature, it should also clear out the preview pane on the bottom of the screen.

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. Perform a search
2. click on one of the search results
3. you can notice that the preview pane shows the details of the entry that was selected in step 2
4. (This trigger is what I dont know) - either you have to wait for sometime, or the autotype is performed
5. Notice that the preview pane still shows the details - whereas the search results are now empty.

## Context
Just an inconsistent UX - if it was intended for privacy/security.

## Debug Info
KeePassXC - Version 2.4.0-beta1
Build Type: PreRelease
Revision: 42cfe01

Libraries:
- Qt 5.12.0
- libgcrypt 1.8.4

Operating system: macOS 10.14
CPU architecture: x86_64
Kernel: darwin 18.2.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey
- TouchID

**Comment by droidmonkey** [comment] 2019-02-11 02:35
Good finding! The search results disappearing is by design and a change since 2.3.4.

**Comment by droidmonkey** [comment] 2019-03-18 00:43
This has been fixed in beta2 or beyond.

**Closed by droidmonkey** 2019-03-18 00:43 UTC
Labels: PRE-RELEASE BUG, bug
