### ISSUE TITLE
Feature: SSH-Agent: Context menu entries to add/remove keys

### ISSUE THREAD

**Issue by Skycoder42** [keepassxreboot/keepassxc#1958] opened 2018-05-15 14:19 UTC
It would be really useful if the "add to agent" and "remove from agent" actions of the SSH-Agent section could be provided as context menu actions when right-clicking an entry that has a SSH-Key associated.

## Context
Since I typically actiavte and deactivate some of my keys independently of the lock-state of keepassxc (i.e. unlock when starting to work with it and lock again once i'm done) it takes a little longer to always open the entry, go to ssh and de/activate it. Having context actions would really improve my workflow.

**Comment by hifi** [comment] 2018-05-15 15:15
Duplicate of #1815. Please comment on that issue as it also has some WIP information.

**Closed by hifi** 2018-05-15 15:15 UTC
Labels: duplicate, new feature, plugin: SSH agent
