### ISSUE TITLE
Cannot save database after reconnecting Yubikey

### ISSUE THREAD

**Issue by cjustin88** [keepassxreboot/keepassxc#864] opened 2017-08-13 01:21 UTC
If I unplug my Yubikey, replug it, then attempt to save my KeepassXC database, KeepassXC reports "Writing the database failed. Unable to issue challenge-response".

## Expected Behavior
KeepassXC should re-detect the Yubikey, perform a challenge-response against the Yubikey, and save the database.

## Current Behavior
KeepassXC does not re-detect the Yubikey when attempting to save the password database and hence returns "unable to issue challenge-response".

## Possible Solution
If the opened database was unlocked using a Yubikey challenge-response, attempt to "refresh"/re-detect the Yubikey before attempting to save the database.

## Steps to Reproduce (for bugs)
1. Unlock the database with the Yubikey inserted.
2. Unplug the Yubikey from the computer.
3. Replug the Yubieky back into the computer.
4. Database->Save database.

## Context
Being unable to save the database after making changes to it is a severe problem!

## Debug Info

**Note: I am using a fork of keepassxc from https://github.com/varjolintu/keepassxc that has support for the new keepassxc-browser extension. This fork adds support for Native Messaging interfacing with the keepassxc-browser extension.

I built this from source.**

KeePassXC - Version 2.2.0
Revision: bcc00018785824bf267c6ca54ae94049b1a85379

Libraries:
- Qt 5.7.1
- libgcrypt 1.7.8

Operating system: Fedora 26 (Workstation Edition)
CPU architecture: x86_64
Kernel: linux 4.11.8-300.fc26.x86_64

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey
- Native Messaging browser extension

Libraries:
Relevant Yubikey libraries that were required for compiling KeepassXC from source:
Installed Packages
Name         : libyubikey
Version      : 1.13
Release      : 3.fc26
Arch         : x86_64
Size         : 73 k
Source       : libyubikey-1.13-3.fc26.src.rpm
Repo         : @System
From repo    : fedora
Summary      : C library for decrypting and parsing Yubikey One-time passwords
URL          : http://opensource.yubico.com/yubico-c
License      : BSD
Description  : This package holds a low-level C software development kit for the
             : Yubico authentication device, the Yubikey.

Name         : libyubikey-devel
Version      : 1.13
Release      : 3.fc26
Arch         : x86_64
Size         : 4.6 k
Source       : libyubikey-1.13-3.fc26.src.rpm
Repo         : @System
From repo    : fedora
Summary      : Development files for libyubikey
URL          : http://opensource.yubico.com/yubico-c
License      : BSD
Description  : This package contains the header file needed to develop applications
             : that use libyubikey.

Name         : ykpers
Version      : 1.18.0
Release      : 2.fc26
Arch         : x86_64
Size         : 316 k
Source       : ykpers-1.18.0-2.fc26.src.rpm
Repo         : @System
From repo    : fedora
Summary      : Yubikey personalization program
URL          : http://opensource.yubico.com/yubikey-personalization/
License      : BSD
Description  : Yubico's YubiKey can be re-programmed with a new AES key. This is a
             : library that makes this an easy task.

Operating system: Fedora 26
CPU architecture: x86_64
Kernel: 4.11.8-300.fc26.x86_64

Enabled extensions:
keepassxc-browser installed in Firefox 55.

**Comment by sainaen** [comment] 2017-08-13 11:09
This looks like a duplicate of #712.

**Comment by droidmonkey** [comment] 2017-08-13 13:44
It is

**Closed by droidmonkey** 2017-08-13 13:44 UTC
