### ISSUE TITLE
Issue in setting up SSH key agent integration

### ISSUE THREAD

**Issue by GTP95** [keepassxreboot/keepassxc#8777] opened 2022-11-09 18:11 UTC
## Overview
I'm trying to set up the SSH agent integration on Arch Linux. Inside the settings, KeepassXC says that there's no SSH link and that the value of the SSH_AUTH_SOCK environment variable is empty, even if I set it. Indeed, if I try to echo its value in a terminal I get the following output:
```BASH
$ echo $SSH_AUTH_SOCK
/run/user/1000/ssh-agent.socket
```
Here is a screenshot of KeepassXC's settings.
![keepassxc](https://user-images.githubusercontent.com/9197945/200907036-658b53e2-1320-4b21-85ad-9047d8b4231f.png)

Restarting KeepassXC or rebooting my PC doesn't solve the issue.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Add "export SSH_AUTH_SOCK="$XDG_RUNTIME_DIR/ssh-agent.socket"" to the bashrc file.
2. Source the bashrc file or reboot the system.
3. Open KeepassXC settings.

## Expected Behavior
KeepassXC should be able to read the environment variable and tell that it isn't empty.

## Actual Behavior
KeepassXC thinks that the environment variable is empty.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.4
Revision: 63b2394

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: LXDE
Windowing System: X11

**Comment by droidmonkey** [comment] 2022-11-09 20:24
Are you running in snap or flatpak?

**Comment by GTP95** [comment] 2022-11-10 10:44
Neither, is this [package](https://archlinux.org/packages/community/x86_64/keepassxc/).

**Comment by droidmonkey** [comment] 2022-11-10 11:20
What happens when you do this in a terminal:

`SSH_AUTH_SOCK="$XDG_RUNTIME_DIR/ssh-agent.socket" keepassxc`

**Comment by GTP95** [comment] 2022-11-10 12:42
It opened KeepassXC. I then went to the settings and now I see the right value for SSH_AUTH_SOCK, but I have an error message saying that there is no running agent and it can't list identities, despite the fact that I have ssh-agent running (did this inside another terminal):
```BASH
$ pidof ssh-agent
5088
```
This is the screenshot of what I saw in the settings now:
![KeepassXC](https://user-images.githubusercontent.com/9197945/201094300-fc92e51f-9434-4d71-92c2-9618e020378e.png)

**Comment by droidmonkey** [comment] 2022-11-10 15:12
You need to either remove a firejail restriction or figure out why your bashrc is setting env vars in a different launch environment. Your ssh agent seems inaccessible.

**Comment by Ouack23** [comment] 2022-11-26 12:22
I have the exact same problem on Archlinux.
The socket access rights seem to be correct and "should" be accessible by kpxc. I'll post some details soon. Maybe the problem is on the distro's side, and I may open a bug there.

**Comment by Ouack23** [comment] 2022-11-30 18:31
I found a solution to my problem.

I used pam's `~/.pam_environment` to set my environment variables. This file has been deprecated in PAM 1.5.0 (see [changelog](https://github.com/linux-pam/linux-pam/releases/tag/v1.5.0)) which was released on 22/11/10 and put in ArchLinux core repository on 22/11/16.

A related ArchLinux bug is opened [here](https://bugs.archlinux.org/task/68945).

To use `$XDG_RUNTIME_DIR` value in the `SSH_AUTH_SOCK` variable value, I had to find another **user related** system-wide environment variable management mechanism.
FYI you cannot use `$XDG_RUNTIME_DIR` in a _fully_ system-wide way, as `$XDG_RUNTIME_DIR` may not exist at the time those variables are read, hence causing `$XDG_RUNTIME_DIR` to be interpreted as text or empty value in the `$SSH_AUTH_SOCK` variable, instead of a variable name that should be expanded. This is the case if you declare `SSH_AUTH_SOCK` in `/etc/environment`, for example.

Well, I chose to use Systemd user variables which are documented [here](https://wiki.archlinux.org/title/Systemd/User#Environment_variables).

What I did : 
```bash
mkdir -p ~/.config/environment.d/
echo 'SSH_AUTH_SOCK=$XDG_RUNTIME_DIR/ssh-agent.socket' >> ~/.config/environment.d/ssh-agent.conf
```

Then reboot _just to be sure_ (maybe a dynamic env var import is possible, but, you know, rebooting was faster than searching so I did that ...).

My KPXC ssh-agent was OK after this.

@GTP95 do you still have some issues on your side ?

**Comment by GTP95** [comment] 2022-11-30 23:04
Thank you very much for posting your solution, I'll try it in the coming days and report back here.

**Comment by GTP95** [comment] 2023-01-08 21:38
Sorry for the long delay, I nearly forgot about this. I tried @Ouack23 solution, but it still doesn't work for me. Setting a systemd user variable seems to have been successful, as after creating the file `~/.config/environment.d/ssh-agent.conf` and writing there the given value (and rebooting), by executing `systemctl --user show-environment` I get the following output:
```
HOME=/home/giacomo
LANG=it_IT.UTF-8
LOGNAME=giacomo
MAIL=/var/spool/mail/giacomo
PATH=/usr/local/sbin:/usr/local/bin:/usr/bin:/var/lib/flatpak/exports/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
SHELL=/bin/bash
SYSTEMD_EXEC_PID=1914
USER=giacomo
XDG_DATA_DIRS=/home/giacomo/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share/:/usr/share/
XDG_RUNTIME_DIR=/run/user/1000
XTABLES_LIBDIR=/usr/lib/iptables
SSH_AUTH_SOCK=/run/user/1000/ssh-agent.socket
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
DEBUGINFOD_URLS=$'https://debuginfod.archlinux.org '
DESKTOP_SESSION=/usr/bin/startlxde
DISPLAY=:0
GTK_MODULES=canberra-gtk-module
LANGUAGE=it_IT.UTF-8
LC_MESSAGES=it_IT.UTF-8
MOTD_SHOWN=pam
PWD=/home/giacomo
SAL_USE_VCLPLUGIN=gtk
SHLVL=1
XAUTHORITY=/home/giacomo/.Xauthority
XDG_CONFIG_HOME=/home/giacomo/.config
XDG_DATA_HOME=/home/giacomo/.local/share
XDG_SEAT=seat0
XDG_SESSION_CLASS=user
XDG_SESSION_ID=1
XDG_SESSION_TYPE=x11
XDG_VTNR=1
_=/usr/bin/dbus-update-activation-environment
```

But when I open KeepassXC I still get the same error:
![keepass error](https://user-images.githubusercontent.com/9197945/211220403-9072ad90-c627-41f9-ba44-3a1174390bac.png)
Any Idea?

**Comment by droidmonkey** [comment] 2023-08-20 21:41
This isn't a KeePassXC issue so closing

**Closed as not planned by droidmonkey** 2023-08-20 21:41 UTC
Labels: more info needed, platform: Linux, feature: SSH agent
