### ISSUE TITLE
Mount attachments to ram disk

### ISSUE THREAD

**Issue by b-fett** [keepassxreboot/keepassxc#4798] opened 2020-05-31 10:59 UTC
Typical application for attachments feature is to store some private keys or any other small files that must to be private.
The problem is that before use attachment you should store it on real drive to load it somewhere.
And it's very annoying because you might just want read this file on the same machine, but you forced to save it.
It is a few additional operations and it may affect security because it's easy to forget properly wipe your keys from drive.
On the other hand, if attachments will be stored in ram disk it would be easy to have access to them and they are completely gone once program is locked/closed.

How it could be implemented? I think it might be an option in main menu like "Mount attachments" which will create ram disk containing attachments which organized in tree structure like it is in keepassxc records.

**Comment by droidmonkey** [comment] 2020-05-31 12:03
Duplicate of #2400

**Closed by droidmonkey** 2020-05-31 12:03 UTC
Labels: new feature
