### ISSUE TITLE
Cancelling a Group edit should trigger confirmation prompt if there are unsaved changes

### ISSUE THREAD

**Issue by kneitinger** [keepassxreboot/keepassxc#2377] opened 2018-10-09 02:59 UTC
## Expected Behavior

If a group is  modified and "Cancel" is pressed, a confirmation prompt "Group has unsaved changes" with buttons "Save", "Discard", and "Cancel" should be presented to the user, just as how it is with editing entries:
![2018-10-08_19-48-26](https://user-images.githubusercontent.com/5200550/46644094-c98c8400-cb33-11e8-89bd-ad44f52d3195.png)

## Current Behavior

If a group is modified and "Cancel" is pressed, the edit widget closes and all unsaved changes are lost.

## Possible Solution

The `EditEntryWidget` class has a flag that marks if a modification is made.  This is checked when "Cancel" is pressed and the prompt is shown if needed.  Using this as a guide, modify `EditGroupWidget` to act similarly.

## Context

Fixing this can prevent accidentally discarding edits,  and lead to an overall more cohesive feel of the edit widgets.

## Debug Info
KeePassXC - Version 2.4.0-snapshot
Build Type: Snapshot
Revision: fd099cf

Libraries:
- Qt 5.11.2
- libgcrypt 1.8.3

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 4.14.74-1-lts

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- YubiKey

**Comment by ckieschnick** [comment] 2019-04-15 15:13
I think the issue is fixed in 2.4.1 with 4b1258f5851c12e2fbe7991fff794a8e78237656.

**Comment by droidmonkey** [comment] 2019-04-15 15:26
It certainly is.

**Closed** 2019-07-10 02:25 UTC
