### ISSUE TITLE
OS' keychain integration

### ISSUE THREAD

**Issue by rugk** [keepassxreboot/keepassxc#753] opened 2017-07-06 09:30 UTC
## Expected Behavior

Allow to save the master password in the OS keychain.

## Current Behavior

none

## Possible Solution

Add a checkbox/button at database creation and in database settings later, which allow one to save the password in the OS keychain and use it to automatically unlock the database, i.e. fill in the password into the unlock screen automatically, so maybe only a yubikey is still needed.

## Context

This would allow one to save passwords in a keepass database in order to e.g. use them in a browser that has no support for the OS keychain.
And it is done in a secure way, as the OS keychain is encrypted with the user's login password (or maybe even some hardware keys, whatever…). In some creative uses it could create a nice "trust chain" from users login password up to any application, where you can use KeePass auto-type or HTTP or STDOUT or… feature to pass passwords to.

**Comment by phoerious** [comment] 2017-07-06 11:36
Duplicate of #440

**Closed by phoerious** 2017-07-06 11:36 UTC
