### ISSUE TITLE
Cannot move entry from one group to another

### ISSUE THREAD

**Issue by henryliang21** [keepassxreboot/keepassxc#5828] opened 2020-12-13 20:16 UTC
## Cannot move an entry from one group to another
I am no longer able to move an entry from one group to another

## Steps to Reproduce
1. Create two groups
2. Create a entry of user account
3. Try to drag & drop it from one group to another

## Expected Behavior
Expect the entry to be moved from original group to the destination group, as what KeepassXC does before

## Actual Behavior
Nothing happened

## Context
I clear remember that I can move entries from one group to another, so I can easily manage the new entries in "KeepassXC - Browser password" group to other groups.

KeePassXC - Version 2.6.2
Revision: e9b9582

Operating System: macOS 11.0.1 (20B29)

**Comment by varjolintu** [comment] 2020-12-13 21:07
Duplicate of https://github.com/keepassxreboot/keepassxc/issues/5636.

**Closed by varjolintu** 2020-12-13 21:07 UTC
Labels: bug
