### ISSUE TITLE
macOS 10.15: MinimizeOnStartup causes window to not appear

### ISSUE THREAD

**Issue by SteffenGerdes** [keepassxreboot/keepassxc#3615] opened 2019-10-10 16:22 UTC
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
Window shows up when selecting app icon.

## Current Behavior
When trying to open the Window for the first time after app start, the opening animation appears, but the Window does not show up.

## Possible Solution
Workaround: Edit keepassxc.ini and set MinimizeOnStartup back to false.

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. Set MinimizeOnStartup to true
2. Close KeePassXC completly
3. Restart KeePassXC

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )
This settings were my default on macOS Mojave (10.14). After upgrading to Catalina the issue appeared.

## Debug Info
Testet on macOS Catalina 10.15 and macOS Mojave 10.14.6.
On macOS Mojave 10.14.6 the app works as expected.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.4.3
Revision: 5d6ef0c

Qt 5.12.3
Debugging mode is disabled.

Operating system: macOS 10.15
CPU architecture: x86_64
Kernel: darwin 19.0.0

Enabled extensions:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.4

**Comment by ConstantinRuhdorfer** [comment] 2019-10-10 16:24
Can confirm that this bug does not appear on MacOS 10.14.6 with KeepassXC 2.4.3 and the debug info:

KeePassXC - Version 2.4.3
Revision: 5d6ef0c

Qt 5.12.3
Debugging mode is disabled.

Operating system: macOS Mojave (10.14)
CPU architecture: x86_64
Kernel: darwin 18.7.0

Enabled extensions:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.4

**Comment by droidmonkey** [comment] 2019-10-11 20:13
Is the application opened? Based on your report it would appear that the setting is working perfectly.

**Comment by SteffenGerdes** [comment] 2019-10-12 11:00
Yes, the app starts up, but I‘m not able to open the window of KeePassXC then. If I understand correctly, then I should be able to manually open the window when the app is running and this is not possible. When the feature is enabled the window just never shows up.

**Comment by droidmonkey** [comment] 2019-10-12 11:07
Gotcha!

**Comment by droidmonkey** [comment] 2019-10-14 00:49
I can't replicate this on Catalina.

**Comment by droidmonkey** [comment] 2019-10-14 01:57
This is also a duplicate of #2280

**Closed by droidmonkey** 2019-10-14 01:57 UTC
Labels: bug, not reproducible
