### ISSUE TITLE
KeePassXC Hangs: "keepassxc has stopped responding"

### ISSUE THREAD

**Issue by HUGHUSR** [keepassxreboot/keepassxc#4039] opened 2019-12-19 01:50 UTC
Three times now, coming out of macOS sleep, keepassxc has stopped responding. It does not respond to a gentle "Quit" in ActivityMonitor, and you have to "Force Quit" it.  

While it is "not responding," keeypassxc's cpu utilization is >100%. You can let is sit "forever" and it will never start responding (I have let it sit for >15 minutes). When this behavior occurs, KeePassXC shows all the open databases are locked. (I would expect it to lock all open databases on sleep, so I am just stating what the UI shows.)

To assist in debugging, I have tried running a spindump of the process -- and this is where it gets weird: Running spindump "fixes" keepassxc and it begins responding as though nothing happened. I am attaching the dump to see if you have any clue what is going on.

This problem is not trivially reproducible. Well, at least I haven't found a pattern where I can force it to always happen. However, it only seems to happen if multiple databases are unlocked when the laptop is put to sleep (lid closed) -- but not every time.

Please let me know if you need any additional information.

[KeePassXC-Spindump.txt](https://github.com/keepassxreboot/keepassxc/files/3981328/KeePassXC-Spindump.txt)

## Expected Behavior
Not hang on awake from sleep.

## Current Behavior
Randomly hangs on awake from sleep. Spindump unhangs it.

## Steps to Reproduce
1. Open multiple databases. 
2. Close laptop with databases unlocked.
3. Leave laptop closed for ?? time (not even sure this is a factor).
4. Resume from sleep.

## Context
One DB is password protected and the other requires both a password and a key file. 

Both KeePassXC, and all its databases and keys, are on an encrypted flash drive [mounted as a macOS CoreStorage Logical Volume • Mac OS Extended (Journaled, Encrypted) file system], which remains mounted through the sleep (no need to reenter flash drive's encrypted passphrase upon awake from sleep).

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )

***FOR MAC, THE ABOVE NOTE SHOULD READ: About KeePassXC-->Debug Info

KeePassXC - Version 2.5.1
Revision: 0fd8836

Qt 5.13.1
Debugging mode is disabled.

Operating system: macOS Mojave (10.14)
CPU architecture: x86_64
Kernel: darwin 18.7.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by HUGHUSR** [comment] 2020-01-13 03:25
Having the same issue on the latest KeePassXC.

There was a single database open for the user where KeePassXC stopped responding when returning from sleep. Other users may have had the same database open.

I am attaching a spindump taken while the process was not responding and consuming 100% CPU.

Please let me know if I can provide additional information the next time this occurs.

Thanks!
[KeePassXChang.txt](https://github.com/keepassxreboot/keepassxc/files/4052001/KeePassXChang.txt)


KeePassXC - Version 2.5.2
Revision: 62cda9d

Qt 5.14.0
Debugging mode is disabled.

Operating system: macOS Mojave (10.14)
CPU architecture: x86_64
Kernel: darwin 18.7.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by droidmonkey** [comment] 2020-01-13 03:35
Can you run a snapshot build (https://snapshot.keepassxc.org) and recapture the spindump when this issue occurs. Unfortunately with release builds we lose function names.

**Comment by HUGHUSR** [comment] 2020-01-13 03:38
Sure. Glad to!

However, it will be later in the week before I can download it and
then wait for it to happen again.
Thanks!
On 1/12/2020 at 10:35 PM, "Jonathan White"  wrote:

	Can you run a snapshot build (https://snapshot.keepassxc.org) and
recapture the spindump when this issue occurs. Unfortunately with
release builds we lose function names.

**Comment by HUGHUSR** [comment] 2020-01-18 23:23
Okay. Here's a hang with a spindump captured against a snapshot version of KeePass.

HOWEVER, after having been hung for several minutes and pegging at 102.2% CPU, in the middle of the spindump, KeePassXC started responding and the CPU utilization dropped to 2.7%. So, I have no idea if this spindump is useful or not.

I will keep running the snapshot and capture a fully-hung event if this spindump is not useful.
[Spindump-KeePassXC.txt](https://github.com/keepassxreboot/keepassxc/files/4082036/Spindump-KeePassXC.txt)


KeePassXC - Version 2.5.1-snapshot
Build Type: Snapshot
Revision: 2fab4d5

Qt 5.14.0
Debugging mode is disabled.

Operating system: macOS Mojave (10.14)
CPU architecture: x86_64
Kernel: darwin 18.7.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by HUGHUSR** [comment] 2020-01-28 01:44
Finally have a snapshot spindump from a hang where it did not recover -- even after 20 minutes.
[KeePassXC-Spingump.txt](https://github.com/keepassxreboot/keepassxc/files/4120246/KeePassXC-Spingump.txt)


KeePassXC - Version 2.5.2-snapshot
Build Type: Snapshot
Revision: 8ded3bd

Qt 5.14.0
Debugging mode is disabled.

Operating system: macOS Mojave (10.14)
CPU architecture: x86_64
Kernel: darwin 18.7.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by droidmonkey** [comment] 2020-01-28 02:18
Here is the relevant section. This looks like it could be a Qt bug since no KeePassXC code is called in the stall.

```
Process:         KeePassXC [36775]
UUID:            A7AACAB3-4324-33CF-87C3-F921D5B1DFED
Path:            /Volumes/Keys/Applications/KeePassXC.app/Contents/MacOS/KeePassXC
Architecture:    x86_64
Parent:          launchd [1]
UID:             516
Footprint:       1494.48 MB
Start time:      2020-01-27 20:36:49 -0500
End time:        2020-01-27 20:36:59 -0500
Num samples:     1000 (1-1000)
CPU Time:        9.968s (36.6G cycles, 4.3G instructions, 8.44c/i)
Note:            Unresponsive for 262 seconds before sampling
Note:            2 idle work queue threads omitted

  Thread 0x159d0e           DispatchQueue 1           1000 samples (1-1000)     priority 46 (base 46)     cpu time 9.968s (36.6G cycles, 4.3G instructions, 8.44c/i)
  1000  start + 1 (libdyld.dylib + 91093) [0x7fff57fa43d5]
    1000  ??? (KeePassXC + 39056) [0x10ce13890]
      1000  QCoreApplication::exec() + 130 (QtCore + 2026562) [0x10e319c42]
        1000  QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 431 (QtCore + 2008943) [0x10e31576f]
          1000  ??? (libqcocoa.dylib + 218808) [0x1104586b8]
            1000  -[NSApplication run] + 699 (AppKit + 79240) [0x7fff2960b588]
              1000  -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 4043 (AppKit + 106213) [0x7fff29611ee5]
                999  (anonymous namespace)::AutoreleasePoolPage::pop(void*) + 710 (libobjc.A.dylib + 38012) [0x7fff567ca47c]
                  997  -[NSBitmapGraphicsContext dealloc] + 66 (AppKit + 1324490) [0x7fff2973b5ca]
                    997  -[NSCGSContext dealloc] + 25 (AppKit + 1324522) [0x7fff2973b5ea]
                      997  -[NSCGSContext _invalidate] + 79 (AppKit + 1324638) [0x7fff2973b65e]
                        997  _CFRelease + 192 (CoreFoundation + 1295743) [0x7fff2c11e57f]
                          997  context_reclaim + 37 (CoreGraphics + 171761) [0x7fff2c452ef1]
                            997  _CFRelease + 192 (CoreFoundation + 1295743) [0x7fff2c11e57f]
                              997  CGContextDelegateFinalize + 59 (CoreGraphics + 171912) [0x7fff2c452f88]
                                997  ripc_Finalize + 237 (CoreGraphics + 172293) [0x7fff2c453105]
                                  997  RIPRemoveContextFromContextList + 40 (CoreGraphics + 173894) [0x7fff2c453746]
                                    966  x_list_remove + 32 (CoreGraphics + 173278) [0x7fff2c4534de] (running)
                                    15   x_list_remove + 56 (CoreGraphics + 173302) [0x7fff2c4534f6] (running)
                                    7    x_list_remove + 32 (CoreGraphics + 173278) [0x7fff2c4534de]
                                     *4    ??? (kernel + 1738736) [0xffffff80003a87f0] (runnable)
                                     *3    call_continuation + 35 (kernel + 1429699) [0xffffff800035d0c3]
                                       *3    ml_set_interrupts_enabled + 25 (kernel + 2976393) [0xffffff80004d6a89] (running)
                                    5    x_list_remove + 27 (CoreGraphics + 173273) [0x7fff2c4534d9] (running)
                                    3    x_list_remove + 36 (CoreGraphics + 173282) [0x7fff2c4534e2] (running)
                                    1    x_list_remove + 30 (CoreGraphics + 173276) [0x7fff2c4534dc] (running)
                  1    objc_release + 32 (libobjc.A.dylib + 34384) [0x7fff567c9650] (running)
                  1    objc_msgSend + 33 (libobjc.A.dylib + 26273) [0x7fff567c76a1] (running)
                1    (anonymous namespace)::AutoreleasePoolPage::pop(void*) + 659 (libobjc.A.dylib + 37961) [0x7fff567ca449]
                  1    (anonymous namespace)::AutoreleasePoolPage::fastcheck(bool) + 17 (libobjc.A.dylib + 138149) [0x7fff567e2ba5]
                   *1    hndl_alltraps + 223 (kernel + 1431775) [0xffffff800035d8df]
                     *1    user_trap + 410 (kernel + 3005850) [0xffffff80004ddd9a]
                       *1    ??? (kernel + 2348313) [0xffffff800043d519]
                         *1    vm_map_lookup_locked + 295 (kernel + 2407543) [0xffffff800044bc77] (running)

  Thread 0x159d23           Thread name "com.apple.CFSocket.private"            1000 samples (1-1000)     priority 46 (base 46)
  1000  <truncated backtrace>
    1000  __select + 10 (libsystem_kernel.dylib + 34326) [0x7fff580e0616]
     *1000  ??? (kernel + 7175680) [0xffffff80008d7e00]

  Thread 0x159d2b           Thread name "com.apple.NSEventThread"               1000 samples (1-1000)     priority 46 (base 46)
  1000  thread_start + 13 (libsystem_pthread.dylib + 9229) [0x7fff5819740d]
    1000  _pthread_start + 66 (libsystem_pthread.dylib + 25161) [0x7fff5819b249]
      1000  _pthread_body + 126 (libsystem_pthread.dylib + 13035) [0x7fff581982eb]
        1000  _NSEventThread + 175 (AppKit + 140450) [0x7fff2961a4a2]
          1000  CFRunLoopRunSpecific + 455 (CoreFoundation + 239214) [0x7fff2c01c66e]
            1000  __CFRunLoopRun + 1612 (CoreFoundation + 241420) [0x7fff2c01cf0c]
              1000  __CFRunLoopServiceMachPort + 328 (CoreFoundation + 244126) [0x7fff2c01d99e]
                1000  mach_msg_trap + 10 (libsystem_kernel.dylib + 4634) [0x7fff580d921a]
                 *1000  ipc_mqueue_receive_continue + 0 (kernel + 1659696) [0xffffff8000395330]

  Binary Images:
           0x10ce0a000 -        0x10d1bffff  org.keepassx.keepassxc 2.5.2-snapshot () <A7AACAB3-4324-33CF-87C3-F921D5B1DFED>  /Volumes/Keys/Applications/KeePassXC.app/Contents/MacOS/KeePassXC
           0x10e12b000 -        0x10e66ffff  org.qt-project.QtCore 5.14 (5.14.0)      <C77C37D7-0ACE-3683-84D2-D19169C5C965>  /Volumes/Keys/Applications/KeePassXC.app/Contents/Frameworks/QtCore.framework/Versions/5/QtCore
           0x110423000 -        0x110586fff  libqcocoa.dylib (0)                      <C1BF0736-4570-3882-8F0E-DC2EDF1657CC>  /Volumes/Keys/Applications/KeePassXC.app/Contents/PlugIns/platforms/libqcocoa.dylib
        0x7fff295f8000 -     0x7fff2a3adfff  com.apple.AppKit 6.9 (1671.60.109)       <E23B2968-32EA-340D-9E5E-12F5370DC55D>  /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
        0x7fff2bfe2000 -     0x7fff2c427fff  com.apple.CoreFoundation 6.9 (1575.23)   <596DBC2A-60E3-3A73-AA5F-7A1806CF3204>  /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
        0x7fff2c429000 -     0x7fff2cab9fff  com.apple.CoreGraphics 2.0 (1265.10)     <06B191F9-039C-3C54-A4C6-2FB0C5C3105F>  /System/Library/Frameworks/CoreGraphics.framework/Versions/A/CoreGraphics
        0x7fff567c1000 -     0x7fff56f46fff  libobjc.A.dylib (756.2)                  <7C312627-43CB-3234-9324-4DEA92D59F50>  /usr/lib/libobjc.A.dylib
        0x7fff57f8e000 -     0x7fff57fbafff  libdyld.dylib (655.1.1)                  <002418CC-AD11-3D10-865B-015591D24E6C>  /usr/lib/system/libdyld.dylib
        0x7fff580d8000 -     0x7fff58100fff  libsystem_kernel.dylib (4903.278.19)     <2C2536E7-EA3B-32B5-AFC6-B1139A5046FD>  /usr/lib/system/libsystem_kernel.dylib
        0x7fff58195000 -     0x7fff5819ffff  libsystem_pthread.dylib (330.250.2)      <2D5C08FF-484F-3D59-9132-CE1DCB3F76D7>  /usr/lib/system/libsystem_pthread.dylib
   *0xffffff8000200000 - 0xffffff8000bfffff  kernel (4903.278.19)                     <BC166F11-DD33-32AF-AF67-DE0B2C985AA8>  /System/Library/Kernels/kernel
```

**Comment by HUGHUSR** [comment] 2020-01-28 12:56
Could it be something in how KeePassXC uses Qt? I have _multiple_
other apps running (across multiple different users) that use Qt and
_none_ of them ever exhibit this behavior. However, it is a fairly
consistent problem with KeePassXC, occurring at least 2 to 3 times a
week, if not daily or more often. I have yet to identify a 100%
reproducible pattern.
Or, if it really is a Qt bug, can you file a bug report on it?
Or, look into both?
THANKS!!
On 1/27/2020 at 9:18 PM, "Jonathan White"  wrote:

	Here is the relevant section. This looks like it could be a Qt bug
since no KeePassXC code is called in the stall. 

	Process:         KeePassXC [36775] UUID:           
A7AACAB3-4324-33CF-87C3-F921D5B1DFED Path:           
/Volumes/Keys/Applications/KeePassXC.app/Contents/MacOS/KeePassXC
Architecture:    x86_64 Parent:          launchd [1] UID:            
516 Footprint:       1494.48 MB Start time:      2020-01-27 20:36:49
-0500 End time:        2020-01-27 20:36:59 -0500 Num samples:     1000
(1-1000) CPU Time:        9.968s (36.6G cycles, 4.3G instructions,
8.44c/i) Note:            Unresponsive for 262 seconds before sampling
Note:            2 idle work queue threads omitted   Thread 0x159d0e  
        DispatchQueue 1           1000 samples (1-1000)     priority
46 (base 46)     cpu time 9.968s (36.6G cycles, 4.3G instructions,
8.44c/i)   1000  start + 1 (libdyld.dylib + 91093) [0x7fff57fa43d5]   
 1000  ??? (KeePassXC + 39056) [0x10ce13890]       1000 
QCoreApplication::exec() + 130 (QtCore + 2026562) [0x10e319c42]       
 1000  QEventLoop::exec(QFlags) + 431 (QtCore + 2008943) [0x10e31576f]
          1000  ??? (libqcocoa.dylib + 218808) [0x1104586b8]          
  1000  -[NSApplication run] + 699 (AppKit + 79240) [0x7fff2960b588]  
            1000  -[NSApplication(NSEvent)
_nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 4043 (AppKit
+ 106213) [0x7fff29611ee5]                 999  (anonymous
namespace)::AutoreleasePoolPage::pop(void*) + 710 (libobjc.A.dylib +
38012) [0x7fff567ca47c]                   997 
-[NSBitmapGraphicsContext dealloc] + 66 (AppKit + 1324490)
[0x7fff2973b5ca]                     997  -[NSCGSContext dealloc] + 25
(AppKit + 1324522) [0x7fff2973b5ea]                       997 
-[NSCGSContext _invalidate] + 79 (AppKit + 1324638) [0x7fff2973b65e]  
                      997  _CFRelease + 192 (CoreFoundation + 1295743)
[0x7fff2c11e57f]                           997  context_reclaim + 37
(CoreGraphics + 171761) [0x7fff2c452ef1]                            
997  _CFRelease + 192 (CoreFoundation + 1295743) [0x7fff2c11e57f]     
                         997  CGContextDelegateFinalize + 59
(CoreGraphics + 171912) [0x7fff2c452f88]                              
  997  ripc_Finalize + 237 (CoreGraphics + 172293) [0x7fff2c453105]   
                               997  RIPRemoveContextFromContextList +
40 (CoreGraphics + 173894) [0x7fff2c453746]                           
         966  x_list_remove + 32 (CoreGraphics + 173278)
[0x7fff2c4534de] (running)                                     15  
x_list_remove + 56 (CoreGraphics + 173302) [0x7fff2c4534f6] (running) 
                                   7    x_list_remove + 32
(CoreGraphics + 173278) [0x7fff2c4534de]                              
       *4    ??? (kernel + 1738736) [0xffffff80003a87f0] (runnable)   
                                  *3    call_continuation + 35 (kernel
+ 1429699) [0xffffff800035d0c3]                                       
*3    ml_set_interrupts_enabled + 25 (kernel + 2976393)
[0xffffff80004d6a89] (running)                                     5  
 x_list_remove + 27 (CoreGraphics + 173273) [0x7fff2c4534d9] (running)
                                    3    x_list_remove + 36
(CoreGraphics + 173282) [0x7fff2c4534e2] (running)                    
                1    x_list_remove + 30 (CoreGraphics + 173276)
[0x7fff2c4534dc] (running)                   1    objc_release + 32
(libobjc.A.dylib + 34384) [0x7fff567c9650] (running)                  
1    objc_msgSend + 33 (libobjc.A.dylib + 26273) [0x7fff567c76a1]
(running)                 1    (anonymous
namespace)::AutoreleasePoolPage::pop(void*) + 659 (libobjc.A.dylib +
37961) [0x7fff567ca449]                   1    (anonymous
namespace)::AutoreleasePoolPage::fastcheck(bool) + 17 (libobjc.A.dylib
+ 138149) [0x7fff567e2ba5]                    *1    hndl_alltraps +
223 (kernel + 1431775) [0xffffff800035d8df]                      *1   
user_trap + 410 (kernel + 3005850) [0xffffff80004ddd9a]               
        *1    ??? (kernel + 2348313) [0xffffff800043d519]             
            *1    vm_map_lookup_locked + 295 (kernel + 2407543)
[0xffffff800044bc77] (running)   Thread 0x159d23           Thread name
"com.apple.CFSocket.private"            1000 samples (1-1000)    
priority 46 (base 46)   1000       1000  __select + 10
(libsystem_kernel.dylib + 34326) [0x7fff580e0616]      *1000  ???
(kernel + 7175680) [0xffffff80008d7e00]   Thread 0x159d2b          
Thread name "com.apple.NSEventThread"               1000 samples
(1-1000)     priority 46 (base 46)   1000  thread_start + 13
(libsystem_pthread.dylib + 9229) [0x7fff5819740d]     1000 
_pthread_start + 66 (libsystem_pthread.dylib + 25161) [0x7fff5819b249]
      1000  _pthread_body + 126 (libsystem_pthread.dylib + 13035)
[0x7fff581982eb]         1000  _NSEventThread + 175 (AppKit + 140450)
[0x7fff2961a4a2]           1000  CFRunLoopRunSpecific + 455
(CoreFoundation + 239214) [0x7fff2c01c66e]             1000 
__CFRunLoopRun + 1612 (CoreFoundation + 241420) [0x7fff2c01cf0c]      
        1000  __CFRunLoopServiceMachPort + 328 (CoreFoundation +
244126) [0x7fff2c01d99e]                 1000  mach_msg_trap + 10
(libsystem_kernel.dylib + 4634) [0x7fff580d921a]                 
*1000  ipc_mqueue_receive_continue + 0 (kernel + 1659696)
[0xffffff8000395330]   Binary Images:            0x10ce0a000 -       
0x10d1bffff  org.keepassx.keepassxc 2.5.2-snapshot ()  
/Volumes/Keys/Applications/KeePassXC.app/Contents/MacOS/KeePassXC     
      0x10e12b000 -        0x10e66ffff  org.qt-project.QtCore 5.14
(5.14.0)       
/Volumes/Keys/Applications/KeePassXC.app/Contents/Frameworks/QtCore.framework/Versions/5/QtCore
           0x110423000 -        0x110586fff  libqcocoa.dylib (0)      
                
/Volumes/Keys/Applications/KeePassXC.app/Contents/PlugIns/platforms/libqcocoa.dylib
        0x7fff295f8000 -     0x7fff2a3adfff  com.apple.AppKit 6.9
(1671.60.109)        
/System/Library/Frameworks/AppKit.framework/Versions/C/AppKit        
0x7fff2bfe2000 -     0x7fff2c427fff  com.apple.CoreFoundation 6.9
(1575.23)    
/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
        0x7fff2c429000 -     0x7fff2cab9fff  com.apple.CoreGraphics
2.0 (1265.10)      
/System/Library/Frameworks/CoreGraphics.framework/Versions/A/CoreGraphics
        0x7fff567c1000 -     0x7fff56f46fff  libobjc.A.dylib (756.2)  
                 /usr/lib/libobjc.A.dylib         0x7fff57f8e000 -    
0x7fff57fbafff  libdyld.dylib (655.1.1)                   
/usr/lib/system/libdyld.dylib         0x7fff580d8000 -    
0x7fff58100fff  libsystem_kernel.dylib (4903.278.19)      
/usr/lib/system/libsystem_kernel.dylib         0x7fff58195000 -    
0x7fff5819ffff  libsystem_pthread.dylib (330.250.2)       
/usr/lib/system/libsystem_pthread.dylib    *0xffffff8000200000 -
0xffffff8000bfffff  kernel (4903.278.19)                      
/System/Library/Kernels/kernel

**Comment by droidmonkey** [comment] 2020-04-18 23:44
Closing this as its not readily reproducible.

**Closed by droidmonkey** 2020-04-18 23:44 UTC
Labels: bug, in triage, platform: macOS
