### ISSUE TITLE
Space added to end of line in notes preview

### ISSUE THREAD

**Issue by thejvmshid** [keepassxreboot/keepassxc#7825] opened 2022-04-08 05:01 UTC
If you select a record, select a line in Notes, then there is a space at the end of the selected line, but if you open the record and select the same line inside the record, there is no longer a space.

If Notes specifies a file name, this is a problem because after copying the string ("/a/b/c ") without opening the file from the Notes field and creating file creation ("/a/b/c "), the file is created with space character at the end

KeePassXC version: 2.7.0
OS: macOS Monterey 12.3.1

**Comment by michaelk83** [comment] 2022-04-08 12:00
This is included in #7826 :
>  firstly a space is left at the end of each file, and secondly, ...

Suggest to combine them as "Notes preview not displayed as typed".

**Comment by thyxNY** [comment] 2022-04-19 16:06
@droidmonkey Could copy/paste be fixed in the next version 2.7.2?

**Comment by droidmonkey** [comment] 2022-04-20 00:18
It is not a space but a new line or line break. This only happens if you double/triple click the line to select it. I am not sure we can do anything about it because that is native behavior of the Qt text edit. If you do the same thing while editing an entry you will experience the same behavior.

**Comment by michaelk83** [comment] 2022-04-20 04:53
> If you do the same thing while editing an entry you will experience the same behavior.

@droidmonkey , according to #7882 , the behavior from the actual edit is different. If the preview is a copyable label, that may be the cause. It can be an actual edit, but disabled and read-only.

Together with #7826, it looks like the preview is rendered as HTML instead of plain text. More importantly, it's copied as if it's HTML.

**Comment by droidmonkey** [comment] 2022-04-20 10:09
I'm am very specifically only talking about space added to end when copying here. That space is really a new line character and happens in both edit and preview.

**Comment by droidmonkey** [comment] 2023-06-03 13:43
I cannot reproduce this any more.

**Closed as completed by droidmonkey** 2023-06-03 13:43 UTC
