### ISSUE TITLE
KeepassXC looks really ugly on Ubuntu / eOS

### ISSUE THREAD

**Issue by yhnavein** [keepassxreboot/keepassxc#979] opened 2017-09-22 17:06 UTC
This is how app looks like:
![screenshot from 2017-09-22 18 56 50](https://user-images.githubusercontent.com/516709/30755683-e51946a6-9fc7-11e7-9d80-1822bc5827b8.png)

## Expected Behavior
It should look like in the Screenshot section here: https://keepassxc.org/screenshots

## Current Behavior
As above. Looks like Win 98 app -.-'

## Possible Solution
Sorry

## Steps to Reproduce (for bugs)
1. Have an `elementaryOS 0.4.1 Loki` system installed
2. Install `snapd` (`v. 2.27.5`) by apt
3. `sudo snap install keepassxc`

## Context
Well, there is absolutely no fun using app looking like this. It may be because of some missing Qt stuff, but as it was not part of the installation by snap package, then it may be beneficial to fix that either way or at least add info to the installation page about some requirements prior to installation.

As a side note - KeepassXC looks fine when installed via AppImage

## Debug Info
KeePassXC - Version 2.2.0
Revision: 9a7e6850d6b79c47c2d46d99fdaf433c2ff13716

Libraries:
- Qt 5.7.1
- libgcrypt 1.7.6-beta

Operating system: Ubuntu Core 16
CPU architecture: x86_64
Kernel: linux 4.10.0-35-generic

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

**Comment by weslly** [comment] 2017-09-23 05:09
Duplicate of #431 

Please see https://github.com/keepassxreboot/keepassxc/issues/431#issuecomment-292797327 and https://github.com/keepassxreboot/keepassxc/issues/949#issuecomment-329535675 .

**Closed by weslly** 2017-09-23 05:09 UTC
