### ISSUE TITLE
Launching new instance should toggle running instance

### ISSUE THREAD

**Issue by RealOrangeOne** [keepassxreboot/keepassxc#308] opened 2017-02-14 19:03 UTC
When starting a new instance, it should toggle the currently open application rather than launching a new one.

## Expected Behavior
When I click the shortcut icon, it toggles the running window.

## Current Behavior
It launches a new instance as if the other wasnt running.

## Possible Solution
Check for running applications before hand.

Chances are this wont be a liked feature by many, so maybe making this a setting is the best solution.

## Steps to Reproduce (for bugs)
1. Start KeepassXC
2. Start KeepassXC Again

## Your Environment
* KeePassXC version/commit used: (can be found under Help -> About) 2.1.0
* Qt version (e.g. Qt 5.3): N/A 
* Compiler (e.g. Clang++3.6.0): N/A
* Operating System and version: Arch Linux + Gnome

**Comment by phoerious** [comment] 2017-02-14 19:06
Basically a duplicate of #99 which suggests a --raise command line option further down in the thread.

**Comment by mihaiile** [comment] 2017-02-14 22:21
I also 'vote' for and find the solution described in the #99 about the `--raise` command line option very elegant and provide great flexibility in using the application. Plus should also help solve this issue.

**Comment by phoerious** [comment] 2017-02-14 22:38
Great. I guess I can close this here.

**Closed by phoerious** 2017-02-14 22:38 UTC
