### ISSUE TITLE
Delay when KeePassXC window is brought forward using Dock on Mac

### ISSUE THREAD

**Issue by garuffalo** [keepassxreboot/keepassxc#575] opened 2017-05-15 23:32 UTC
This problem only occurs when the KeePassXC window is completely obscured by another window on a Mac, and the KeePassXC Dock icon is used to bring it forward.

**Expected Behavior**

When KeePassXC is running, and its window is completely behind another window, clicking the KeePassXC icon in the Dock should bring it forward and action should be able to be taken immediately.

**Current Behavior**

If the KeepassXC window is completely obscured by another window (e.g., browser window) and its Dock icon is clicked to bring it forward, there is a 15-second (approximate) delay, during which the beachball spins, before allowing any action.

In other methods of revealing the KeePassXC window, such as dragging (or minimizing) the browser window out of the way, or clicking on a minimized KeePassXC window in the Dock, there is no delay.

If the KeepassXC window is partially showing from in back of the browser window, and the visible portion is clicked to bring it forward, there is no delay. In this scenario there is also no delay if the Dock icon is used to bring it forward.

**Possible Solution**
???

**Steps to Reproduce (for bugs)**

1. Open KeePassXC
2. Position the window so that when the browser window is brought forward, KeePassXC is complete obscured.
3. Click on the KeePassXC Dock icon.
4. Click anywhere on the KeePassXC window and beachballing will commence, stopping after about 15 seconds.

**Context**
There are plenty of workarounds, as described above, including simply waiting for 15 seconds, but it would be nice if actions were available immediately.

**Your Environment**

KeePassXC version 2.14
accessing .kdbx database file from USB flash drive
Mac OS X 10.9.5

**Comment by phoerious** [comment] 2017-05-16 00:10
I tested the described behavior on OS X Sierra and I can't reproduce it. I'm quite sure this is not a KeePassXC bug, but rather a bug in your operating system. There is no reason why KeePassXC should take that long to come to the foreground.

**Comment by garuffalo** [comment] 2017-05-16 00:29
I am planning a clean install of a newer Mac OS sometime soon. Perhaps that will solve my issue. Just to be clear (as perhaps I was not) the delay is not for the KeePassXC window to actually come forward. The delay is from the time the window pops into view and the point when I can take any action in KeePassXC. Thanks for your quick response, and for working on a great project!

**Comment by weslly** [comment] 2017-05-24 00:29
I can't reproduce it either, a clean install should probably fix it as there has been already 3 major updates to OSX since 10.9.5.

**Comment by weslly** [comment] 2017-06-07 23:54
@garuffalo Can I close this?

**Comment by garuffalo** [comment] 2017-06-08 01:37
Yes, and thank you.

**Closed** 2017-06-08 01:52 UTC
Labels: not reproducible, OS X
