### ISSUE TITLE
Advanced attributes list should be resizable by width

### ISSUE THREAD

**Issue by KekcuHa** [keepassxreboot/keepassxc#300] opened 2017-02-13 07:53 UTC
Then editing advanced attributes  in "edit entry" dialog, it's names  does not  fit into list and the list is not resizeable.

## Possible Solution
Make divider between advanced movable to have possibility extend list of  advanced attributes names.

## Steps to Reproduce (for bugs)
1. Open new entry dialog (or edit existing entry)
2. Add new advanced attribute (e.g. with default name 'New attribute')
3. Add new advanced attribute (e.g. with default name 'New attribute 1')
3. Attribute name are particularly hidden now   

## Your Environment

* KeePassXC version/commit used: 2.1.0 rev 26fdb193441bc313830b36463a6253809f9a6dc9
* Qt version (e.g. Qt 5.3): 5.8.0
* Operating System and version:  Arch linux
![image](https://cloud.githubusercontent.com/assets/16463182/22875060/97f14f86-f1da-11e6-9891-c86a24d0f4ab.png)

**Comment by TheZ3ro** [comment] 2017-02-13 09:19
Duplicate of #111, there is a PR pending #220, can you test it? Thanks

**Closed by TheZ3ro** 2017-02-13 09:19 UTC
