### ISSUE TITLE
Add a Command-Line Option to select a hardware key to use when launching the GUI

### ISSUE THREAD

**Issue by Jolly5** [keepassxreboot/keepassxc#11553] opened 2024-12-11 14:51 UTC
## Summary
KeePassXC can be launched with command-line options to provide the password via stdin and the path to a key file. However, there seems to be no way to specify at launch time that a hardware key shall be used.

## Examples
Just like with the keepassxc-cli, there should be the possibility to specify a hardware key upon launch, e.g. like this:
```
keepassxc --pw-stdin --yubikey 1:7370001 /home/me/Database.kdbx
```
Which would launch the KeePassXC GUI and attempt to open the database using a password from stdin and the given hardware key.

Another example:
```
echo 'highlysecure' | keepassxc --pw-stdin --keyfile /home/me/secrets/KeePassKey.keyx --yubikey 1:7370001 /home/me/Database.kdbx
```
Which would attempt to open the database using the password *highlysecure*, the key file from the given path and the specified hardware key. If required, the GUI shall request for the hardware key to be touched, just like it does when entering the values through the GUI.

## Context
I use a database which relies on a combination of a password, a key file and a yubi key to be unlocked. With this feature, I could avoid having to retype the password on a trusted device where I am logged in, by keeping the password in an encrypted user storage and supplying it via stdin when opening KeePassXC. The way it is right now, attempting to do so causes the database failing to open, as it attempts to unlock the database without the yubi key. I have to watch this failure every time and then manually check that the hardware key is to be used before I can unlock the database.

**Comment by droidmonkey** [comment] 2024-12-11 15:13
Duplicate of https://github.com/keepassxreboot/keepassxc/issues/6018

**Closed as completed by droidmonkey** 2024-12-11 15:13 UTC
Labels: duplicate, feature: Hardware Keys
