### ISSUE TITLE
KeepassXC 2.4 does not open existing database file

### ISSUE THREAD

**Issue by peerwal** [keepassxreboot/keepassxc#2873] opened 2019-03-25 14:23 UTC
Using KeepassXC 2.4 flatpak with Kubuntu 18.10 I cannot open a database file that was generated with Keepass 2 and which still works fine with KeepassXC 2.3.4 even with the original key file.

Expected Behavior:
After entering the master password and the pass for the kpxc.key file the database should open.

Current Behavior:
Instead of opening the database, I get en error message saying "... Wrong key or database is corrupted." (translated from German). However, using KeepassXC 2.3.4 the database opens perfectly.

Possible Solution:
None. Using KeepassXC 2.3.4 from Kubuntu repositories as a workaround.

Steps to Reproduce:
See top of page

Operating system: Kubuntu 18.10
CPU architecture: Intel Xeon X5650

Kernel: 
4.18.0

Enabled extensions:
None

**Comment by phoerious** [comment] 2019-03-25 14:38
Duplicate of #2863, fixed in #2872.

**Closed by phoerious** 2019-03-25 14:38 UTC
Labels: bug
