### ISSUE TITLE
open/save attachments broken in Snap 2.7.1

### ISSUE THREAD

**Issue by SCBuergel** [keepassxreboot/keepassxc#8251] opened 2022-07-07 06:26 UTC
## Overview
I cannot open or save attachments In the 2.7.1 release, Snap distribution.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. create entry with an attachments (via the `advanced` tab)
2. select the attachment
3. click `Open` button -> no response
4. click `Save` button -> does not allow me to select a folder

## Expected Behavior
With the `Open` button I expect to see the file.

With the `Save` button I expect to be able to store the file in a selected folder.

## Actual Behavior
`Open` button -> no response
`Save` button -> does not allow me to select a folder 

## Context
I am using the Snap release 2.7.1. The issue does NOT appear on the AppImage version.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.1
Revision: 5916a8f
Distribution: Snap

[NOTE]: # ( Pick choices based on your environment )
Operating System: Ubuntu
Desktop Env: Gnome

**Comment by droidmonkey** [comment] 2022-07-07 10:08
This was fixed with a newer snap release... but if it's still broken for you then you'll have to switch to flatpak or appimage.  It wasn't technically our bug, it's a bug in the way xdg desktop portal works in snaps.

**Closed as completed by droidmonkey** 2022-07-07 10:08 UTC

**Comment by SCBuergel** [comment] 2022-07-15 20:20
> This was fixed with a newer snap release...

According to GitHub 2.7.1 is the latest release and that's the one I'm using, so I guess this remains an open issue or is there some other (unreleased?) version that you mean?

I am using the appimage for that purpose but would be good to be able to just use snap.

**Comment by droidmonkey** [comment] 2022-07-15 20:41
We released a repackaged version of 2.7.1 that corrected the problem which was caused by Ubuntu themselves.

**Comment by ibasaw** [comment] 2022-08-24 19:18
same here, Ubuntu 20.04.4 LTS,  KeePassXC - Version 2.7.1
Revision: 5916a8f
Distribution: Snap 

can't open or save attachments

**Comment by michaelk83** [comment] 2022-08-25 07:56
@ibasaw you have the unpatched version (probably..). Run `snap refresh`.
https://github.com/keepassxreboot/keepassxc/issues/7607#issuecomment-1110646224

**Comment by ibasaw** [comment] 2022-08-25 20:30
@michaelk83 thanks for advise
but:
All snaps up to date.

**Comment by michaelk83** [comment] 2022-08-25 21:51
> All snaps up to date.

Are you sure? The revision you noted is from Apr 6, the fix was pushed to the snap store [on Apr 26](https://github.com/keepassxreboot/keepassxc/issues/7607#issuecomment-1109215569). They both show as "2.7.1".

Also try one of the commands in https://github.com/keepassxreboot/keepassxc/issues/7607#issuecomment-1227778563 . And generally, go over that other thread, as there may be other things to try.
