### ISSUE TITLE
Mac OS X 10.15.4 bug

### ISSUE THREAD

**Issue by xiehaisen1986** [keepassxreboot/keepassxc#4483] opened 2020-03-25 12:02 UTC
Process:               KeePassXC [1360]
Path:                  /Applications/KeePassXC.app/Contents/MacOS/KeePassXC
Identifier:            org.keepassx.keepassxc
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           KeePassXC [1360]
User ID:               501

Date/Time:             2020-03-25 20:02:39.801 +0800
OS Version:            Mac OS X 10.15.4 (19E266)
Report Version:        12
Bridge OS Version:     4.4 (17P4263)
Anonymous UUID:        9EC1606D-2353-761E-1540-834EC0966A3E

Sleep/Wake UUID:       4AFA8626-61CF-4662-81D3-924E1F0ABE44

Time Awake Since Boot: 3700 seconds
Time Since Wake:       2600 seconds

System Integrity Protection: disabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (Code Signature Invalid)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace CODESIGNING, Code 0x1

kernel messages:

VM Regions Near 0 (cr2):
--> 
    __TEXT                 0000000108f67000-00000001092f9000 [ 3656K] r-x/r-x SM=COW  

Thread 0 Crashed:
0   ???                           	0x0000000113e1d000 _dyld_start + 0

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x0000000000000000  rcx: 0x0000000000000000  rdx: 0x0000000000000000
  rdi: 0x0000000000000000  rsi: 0x0000000000000000  rbp: 0x0000000000000000  rsp: 0x00007ffee6c98c10
   r8: 0x0000000000000000   r9: 0x0000000000000000  r10: 0x0000000000000000  r11: 0x0000000000000000
  r12: 0x0000000000000000  r13: 0x0000000000000000  r14: 0x0000000000000000  r15: 0x0000000000000000
  rip: 0x0000000113e1d000  rfl: 0x0000000000000200  cr2: 0x0000000000000000
  
Logical CPU:     0
Error Code:      0x00000000
Trap Number:     0

Binary Images:
       0x108f67000 -        0x1092f8fff +??? (0) <16AE8CED-0E4C-3291-AE43-913B0D7192FF> (null)
       0x113e1c000 -        0x113eadeff +??? (750.5) <1F893B81-89A5-3502-8510-95B97B9F730D> (null)

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 2623
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=4776K resident=0K(0%) swapped_out_or_unallocated=4776K(100%)
Writable regions: Total=8408K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=8408K(100%)
 
                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
STACK GUARD                       56.0M        1 
Stack                             8192K        1 
__DATA                             360K        4 
__DATA_CONST                        20K        1 
__LINKEDIT                         536K        2 
__TEXT                            4240K        2 
shared memory                        8K        2 
===========                     =======  ======= 
TOTAL                             69.0M       13

**Comment by phoerious** [comment] 2020-03-25 12:05
Duplicate of #4398.

**Closed by phoerious** 2020-03-25 12:05 UTC
Labels: duplicate
