### ISSUE TITLE
Auto-type hotkey stops working after restart of KeePassXC

### ISSUE THREAD

**Issue by GlebYavorski** [keepassxreboot/keepassxc#9463] opened 2023-05-22 08:31 UTC
## Overview
When I set my desired key combination in settings for Auto-type, everything works. But After I completely close the KeePassXC and start again or restart my computer the hotkey doesn't work anymore although it is still in the settings.
![image](https://github.com/keepassxreboot/keepassxc/assets/390857/5df86639-dcfa-4bd0-a7c8-902460472d02)
If I go to the settings and set the same key combination again the shortcut starts working until next app restart.

## Steps to Reproduce
1. Set custom Global Auto-Type shortcut;
2. Check if it is working;
3. Completely exit KeePassXC;
4. Start KeePassXC again;
5. Unlock the DB;
6. Focus some window and hit your Global Auto-Type shortcut;

## Expected Behavior
Auto-Type window pops up.

## Actual Behavior
Nothing happens. No reaction from the app.

## Context
KeePassXC - 2.7.5
Revision: 9d0537b

Operating System: Windows 11

**Comment by droidmonkey** [comment] 2023-05-22 10:13
This has been reported before but cannot be replicated by the developers. The other report found that keepassxc was actually still running in the background for some reason. Make sure that isn't happening here.

**Comment by GlebYavorski** [comment] 2023-05-22 14:30
@droidmonkey Thank you for your reply. I just checked: the issue persist on my other laptop with Windows 10.
The issue also persist even after PC reboot, so I doubt there could another instance of the KeePassXC be running. What can be the name of the process? I don't see in task manager anything connected with KP.

After I close the window with KPXC and then start it again I notice, the field with shortcut becomes red. What does it mean?
![image](https://github.com/keepassxreboot/keepassxc/assets/390857/927bd508-3dbd-4907-bfe6-41df369b4d5c)
.
I am ready to provide more information or do some tests if needed.

**Comment by ThatIcyPolarBear** [comment] 2023-05-22 15:15
Might be related, auto-type broke for me when updating to v.2.7.5. Before that it worked fine.
My hotkey used to be: Ctrl+Alt+A, now that hotkey doesn't work anymore. I can't even enter it in the settings anymore. Any letter other then A does seem to work. It's not a n-key rollover issue because I am using the same keyboard and a day ago it worked fine. As far as I am aware the only thing changed was the version by updating it through winget, nothing else (no windows updates etc.). Not sure if I can supply any other info.

**Comment by GlebYavorski** [comment] 2023-05-22 16:04
@ThatIcyPolarBear please, make sure, that you haven't set the hotkey Ctrl+Alt+A in some other app on your computer.

I had the issue with not working shortcuts also on the previous version of KeePassXC.

**Comment by lagerimsi-ds** [comment] 2023-06-19 07:10
same problem on debian12 with snap package; I found related issues here:  
- https://github.com/keepassxreboot/keepassxc/issues/7567 -> snap package
- https://github.com/keepassxreboot/keepassxc/issues/364 -> missing libraries while packaging keepassxc which generate no cmake errors: libxi libxtst (these libraries are installed on my freshly installed system, but might have been missing packaging?)

auto-type submenu doesn't appear at all; auto-type settings for the entries in DB are still there, but no option in context menu

**Comment by droidmonkey** [comment] 2023-06-19 10:39
Has nothing to do with this. You are running wayland on Linux and cannot use autotype. You need to run x11 to use it.

**Comment by droidmonkey** [comment] 2024-08-10 12:16
Closing this since it is not reproducible and most likely due to conflict with other programs.

**Closed as completed by droidmonkey** 2024-08-10 12:16 UTC
Labels: not reproducible, platform: Windows, feature: Auto-Type
