### ISSUE TITLE
Fatal: "Error while reading the database: Duplicate custom attribute found"

### ISSUE THREAD

**Issue by GlenCoakley** [keepassxreboot/keepassxc#5176] opened 2020-07-26 14:22 UTC
## Overview
1. Red banner: "Error while reading the database: Duplicate custom attribute found". Does not open database.
2. Error message disappears on its own. 
3. When the error message is subsequently re-displayed it disappears almost immediately--without time to read it.

## Steps to Reproduce
I don't know how to reproduced this. This has been caused, occasionally, when opening a database saved by MiniKeePass on IOS.

While this is not easy to reproduce. A developer can easily find in the code where this message is displayed and change the logic. I will keep a copy of the errant database and would be happy to test out a new build against it. 

## Expected Behavior
1. It is good that KeePassXC is verifying the data but, it should continue to open the database and report entries with issues to the user so that the user correct them. 

2. Fatal/hard error messages should never just disappear as this one does (after 5 second). Such messages should always require user confirmation--staying on the screen to ensure the user has time to read the message.

3. This issue should be remove when #2 above is removed.

## Actual Behavior
KeePassXC, seems to be able to read the database but, when it finds a duplicate attribute, it refuses to open the database, rendering the data useless.

## Context
I exported the same database to KeePassium saved from it and see the same issue. After making a change to content and saving it again I was able to load the database in KeePassXC. 
There is an inconsistency in how MiniKeePass and possibly KeePassium save the database but, each of them read that same database without issue.  

[NOTE]: # ( Paste debug info from Help → About here )
NOTE to about bug report template: The line above is incorrect for the Mac version of the software. Further, you might want to mention that "Help -> About" (or "KeePassXC -> About" on the Mac) are menu items and "Debug Info" is a tab on the resulting dialog.

KeePassXC - Version 2.6.0
Revision: 0765954

Qt 5.15.0
Debugging mode is disabled.

Operating system: macOS High Sierra (10.13)
CPU architecture: x86_64
Kernel: darwin 17.7.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.5

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows/Linux/macOS
Desktop Env: Gnome/KDE/XFCE/Mate/Cinnamon
Windowing System: X11/Wayland

**Comment by droidmonkey** [comment] 2020-07-26 14:25
I can't speak for the other apps you used, but the bug is definitely with them.

**Comment by GlenCoakley** [comment] 2020-07-26 14:39
Thanks for the prompt response of a workaround. I can try that if needed. 

In my case the duplicate attribute always contains the same value also--the email address used for the account so, I must disagree. It will *not* cause a lost of data (full stop :-) A Brit.! Hi, ya!).

Yes, I agree they have an issue. But, there are UI issues here. Given the nature of the data stored KeePassXC, it should do everything it possibly can to show any/all that data it can read to the user. That may mean that data is loaded but, the saving of the entries with issues is disabled or even saving of the whole database is disabled.

**Comment by droidmonkey** [comment] 2020-07-26 17:07
In your case, sure no data loss, but that does not apply in the general case. We have overcome other issues like this in the past by forcing a rename of keys to make them unique.

**Comment by droidmonkey** [comment] 2022-03-21 15:55
Duplicate of #4540

**Closed by droidmonkey** 2022-03-21 15:55 UTC
Labels: bug, file format, ux

**Comment by gomgopcode** [comment] 2024-01-19 05:45
May be you have been created a new file on another device with custom fields duplicate, and used it's on another device.
Reason: During the entry creation process, two fields were the same.
Solution 1: Go to the previous device and delete the duplicate field and save it.
Solution 2: Install app "KeePass touch" IOS and import this files (error). But you want open on device other, you should find and remove custom fields duplicate.
Good luck!
