### ISSUE TITLE
Auto-type not working

### ISSUE THREAD

**Issue by oogiedoogie** [keepassxreboot/keepassxc#7675] opened 2022-03-26 15:45 UTC
Since the update to 2.7.0, when I click on the Auto-Type button, a window pops up:

![auto-type](https://user-images.githubusercontent.com/14121272/160246861-ba2c3bc5-d126-4dab-adcf-258f588e779d.jpg)

There are two buggy issues: 
1 - The "cancel" option is set by default (which seems strange)
2 - When I click "yes", KeePassXC minimizes, the browser is selected, but no forms are filled. 

Details:
KeePassXC - Version 2.7.0
Revision: 20c9ac1
Distribution: Snap

Qt 5.15.3
Debugging mode is disabled.

Operating system: Ubuntu Core 20
CPU architecture: x86_64
Kernel: linux 5.4.0-104-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.12.1

**Comment by hifi** [comment] 2022-03-26 16:01
Duplicate of #7584

**Closed as completed by hifi** 2022-03-26 16:01 UTC
