### ISSUE TITLE
Using "Online accounts" - Google Drive in Ubuntu 22.04 LTS (Gnome) opening a database or keyfile hangs Keepassxc

### ISSUE THREAD

**Issue by ai792** [keepassxreboot/keepassxc#8876] opened 2022-12-09 09:11 UTC
## Overview
After having linked my Google account in Ubuntu 22.04LTS, trying to use a keyfile and / or database from Google Drive using "Files v42.2" makes KeepassXC hang and fully unresponsive.

## Steps to Reproduce
1. Install Ubuntu 22.04 LTS and update (my system was updated to dec-9th-2022)
2. Install KeepassXC from Snap store (version 2.7.4)
3. From Ubuntu settings, go to "online accounts" --> Google and login to your Google account. Authorize all options.
4. Open KeepassXC and try to open a database using Files --> Other Locations --> Networks --> your Google account --> My Drive --> etc.

## Expected Behavior
The database opens and the application responses...

## Actual Behavior
The application hangs and gets unresponsive. Need a sigkill to close it.

## Context
Is there any more context to add...?

## Debug info
KeePassXC - Version 2.7.4
Revision: 7729648
Distribution: Snap

Qt 5.15.5
Debugging mode is disabled.

Operating system: Ubuntu Core 20
CPU architecture: x86_64
Kernel: linux 5.15.0-56-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.12.1

## OS version and other details
Operating System: Ubuntu 22.04 LTS updated to dec-9th-2022
Desktop Env: Gnome
Windowing System: X11

**Comment by varjolintu** [comment] 2022-12-09 09:39
You should give Snap a proper rights for remote locations. We recommend using Flatpak or AppImage instead.

**Comment by droidmonkey** [comment] 2022-12-09 12:05
Does this also happen with the appimage?

**Comment by ai792** [comment] 2022-12-12 08:21
> You should give Snap a proper rights for remote locations. We recommend using Flatpak or AppImage instead.

> Does this also happen with the appimage?

Tried the Appimage and technically this kind of works. From a user perspective it is not. To access Google Drive from the app I need to navigate to /run/user/1000/gvfs/google-drive\:host\=gmail.com\,user\=xxxxxxxxxx which is not really user friendly because of 2 reasons:

1. In "Files v42" a shortcut is available to "Google Drive". Can you make this accessible from the app?
2. Navigating to /run/user/1000/gvfs/google-drive\:host\=gmail.com\,user\=xxxxxxxxxx doesn't result in the proper files -and directory names [but all names are hashed](https://askubuntu.com/questions/1355619/why-are-my-file-names-hashed-when-i-access-them-from-my-google-drive-files-on-te)

From a user perspective it would be great if you could use the functionality you have in "Files V42". Install Keepassxc from the snap store. Open Keepass file from Google Drive as mounted in Files showing the proper directory- and file names.

NB: [gio has an implementation](https://gitlab.gnome.org/GNOME/glib/-/merge_requests/1291) to get the proper file- and directory names. Example navigating to /run/user/1000/gvfs/google-drive\:host\=gmail.com\,user\=xxxxxxxxxx and using ```gio -ld``` gives the proper names.

Thanks

**Comment by droidmonkey** [comment] 2022-12-12 10:45
What is Files v42?

**Comment by ai792** [comment] 2022-12-12 15:32
> What is Files v42?

![files_v42](https://user-images.githubusercontent.com/119161650/207085757-a7fd1f6a-1776-4670-b2be-870acc681ee6.png)

https://wiki.gnome.org/action/show/Apps/Files

**Comment by night199uk** [comment] 2023-01-10 17:59
Seeing this also on the official Flatpak with Fedora Silverblue 37.

This works:
```
flatpak run --command=/bin/bash org.keepassxc.KeePassXC
cp "/run/user/10003/gvfs/google-drive:host=x.x.x.x,user=yyyyyyy/hash/hash" ~user/test.kdbx
```
So the kdbx file is accessible inside the KeePassXC container.

- Opening the newly copied file from ~user/test.kdbx in KeePassXC works fine; so the file is not corrupt.
- Accessing the file through Other Locations/My Drive/ etc hangs KeePassXC.
- Accessing the file through /run/user/10003/gvfs/..... hangs KeePassXC.

**Comment by shanecbauman** [comment] 2023-02-04 03:10
Experiencing the same thing on Fedora 37 also. Also using flatpak, version 2.74

**Comment by georgiy-ermakov** [comment] 2023-02-20 16:07
same problem on Ubuntu

**Comment by jpges** [comment] 2023-02-23 23:34
The same for me

**Comment by georgiy-ermakov** [comment] 2023-02-24 08:29
remove it and install with apt install.

**Comment by jpges** [comment] 2023-02-24 11:01
Thank you very much, it's fine now.

**Comment by piorkov** [comment] 2023-02-26 23:30
I have the same problem with KeepassXC from deb package (2.7.4)

**Comment by thermoweb** [comment] 2023-02-28 10:06
> remove it and install with apt install.

this solve the issue for me but with the 2.6.6 version.

**Comment by Sazu-bit** [comment] 2023-03-02 12:23
I'm seeing this on Manjaro. With a slight twist. Version 2.7.4 63b2394 from the repository.

I host my password directory in an RClone Crypt on GDrive. When I go to save or to open a library it hangs and I can't get it to do anything. Often I have to force it to quit.

I also use a VPN. (Several things that are not very helpful I admit).

Unfortunately there are no real alternative to KeepassXC (offline, open source).

**Comment by droidmonkey** [comment] 2023-03-02 12:37
You may not want to hear this, but the rclone crypt is completely unnecessary. All data written to disk is encrypted. We never write unencrypted database data to disk. So you are double encrypting and adding unnecessary complexity.

**Comment by Sazu-bit** [comment] 2023-03-02 12:57
The crypt storage area is used for various files and documents, the keepassxc database has been thrown in there because otherwise I'd have to set up a second rclone just for that one file.

**Comment by bkerler** [comment] 2023-08-01 16:05
Hangs with snapd based install, but works fine after uninstalling snapd keepassxc version, instead installing keepassxc 2.7.4 via apt/deb. `sudo snap remove keepassxc && sudo apt install keepassxc -y`.

**Comment by droidmonkey** [comment] 2023-08-01 16:09
This would likely be a snapd problem (or snap packaging problem) and not a KeePassXC specific problem. We recommend using Flatpak instead of snap. Closing as we won't be making changes for this.

**Closed as not planned** 2023-08-01 16:09 UTC
Labels: platform: Linux, distribution: Snap

**Comment by ai792** [comment] 2023-08-09 10:36
From a developer perspective this a logical decision, from a non-technical end-user perspective this is a very disappointing decision. Don't distribute Keepassxc via SNAP if it breaks important use cases, would be my take.

**Comment by droidmonkey** [comment] 2023-08-09 15:14
You are coming at us with hypotheticals, but thanks. Distros distribute ancient versions of keepassxc and refuse to update it. The whole Linux ecosystem is incredibly broken.

**Comment by MadladV** [comment] 2023-08-13 11:30
I am experiencing the same issue with Flatpak distribution of KeePassXC (ver. 2.7.5):

Attempting to open a kdbx file on a mounted Google Drive results in the application becoming unresponsive as reported before (cursor at the Enter Password field will flicker, the window can be moved around the screen but that's about it; the instance has to be terminated via terminal).
Opening the same database copied onto a local partition doesn't reproduce the issue.

Running KeePassXC through the terminal doesn't seem to produce any errors (am I missing a verbose logging flag maybe?) beyond

> qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
> QCommandLineParser: option not defined: "allow-screncapture"
> ** (keepassxc:2): WARNNG **: 13:19:50.247: atk-bridge: get_device_events_reply: unknown signature

However launching it as `flatpak run org.keepassxc.KeePassXC --keyfile <google-drive://...[path-to-keyfile]>` seems to allow for the file to be opened without issues.

Using Fedora 38 (Gnome spin), file is present on a mounted Google Drive partition (set up via Online Accounts).

Kindest regards

**Comment by droidmonkey** [comment] 2023-08-13 12:44
This is _almost certainly_ a bug with Flatpak's file portals and NOT KeePassXC. This could also possibly be a Qt bug, but I doubt it.

**Comment by greyhillman** [comment] 2023-08-30 00:49
~~Killing the process while it hung resulted in the file getting permanently deleted in Google Drive. Since I didn't keep backups, I've lost all my passwords.~~
Edit: File got renamed to some long gibberish name with no extension. So if someone else finds this, check if some weird file was created around the same time your password database file got permanently deleted. Rest of my comment stands.

Leaving this here as a reminder for folks to even backup Google Drive, cause apparently deleting a file from a network drive doesn't send it to trash in Google Drive.

Never using snap again. Might even be a good idea to just remove snap support entirely, but it's just a suggestion.

**Comment by ferenczy** [comment] 2023-11-12 17:47
I would say it's more an issue of the GNOME's gvfs. Use rather the [google-drive-ocamlfuse](https://github.com/astrada/google-drive-ocamlfuse/). Gvfs has so many issues, for me, it was working satisfactory only in the Nautilus (Files), otherwise it was a huge pain or rather practically impossible to use (hashed file names, the root directory in `/run/user/1000/gvfs/google-drive:host=gmail.com,user=xxxxxxxxxx`, etc.).

With the `google-drive-ocamlfuse`, I don't have any issues. After it's mounted, you'll simply have a directory with your "My Drive" contents anywhere you like with proper file names and short paths (depending on the mount point you choose) in any application including the shell and all snaps without any special permissions, etc. You won't have to search your Drive data in obscure directories under hashed file names anymore!

I would say it's easy to install and use, the only a bit tricky part is to set it up to auto-mount during the system start (there are [several options](https://github.com/astrada/google-drive-ocamlfuse/wiki/Automounting), I liked the most the method of [creating a systemd user unit](https://github.com/astrada/google-drive-ocamlfuse/wiki/Automounting#mount-using-systemd)).
