### ISSUE TITLE
KeePassXc-2.71.3 Does not open browser

### ISSUE THREAD

**Issue by Ron000777** [keepassxreboot/keepassxc#8645] opened 2022-10-25 04:34 UTC
The most recent update does not open URL and does not integrate with Browsers. I had to downgrade the version in order program to work. I hope it can be fixed. Thanks

**Comment by varjolintu** [comment] 2022-10-25 07:35
Duplicate of #8636.

**Closed as not planned by varjolintu** 2022-10-25 07:35 UTC
