### ISSUE TITLE
Issue compiling KeePass2XMLReader

### ISSUE THREAD

**Issue by RealOrangeOne** [keepassxreboot/keepassxc#245] opened 2017-01-29 18:08 UTC
Issue compiling KeepassXC on 2 different Arch Linux machines. 

## Expected Behavior
It compiles

## Current Behavior
```
[ 29%] Building CXX object src/CMakeFiles/keepassx_core.dir/format/KeePass2XmlReader.cpp.o
/tmp/yaourt-tmp-jake/aur-keepassxc-git/src/keepassxc/src/format/KeePass2XmlReader.cpp: In member function ‘void KeePass2XmlReader::parseBinaries()’:
/tmp/yaourt-tmp-jake/aur-keepassxc-git/src/keepassxc/src/format/KeePass2XmlReader.cpp:391:77: error: call of overloaded ‘compare(const char [5], Qt::CaseSensitivity)’ is ambiguous
             if (attr.value("Compressed").compare("True", Qt::CaseInsensitive) == 0) {
                                                                             ^
In file included from /usr/include/qt/QtCore/qregexp.h:47:0,
                 from /usr/include/qt/QtCore/qstringlist.h:47,
                 from /usr/include/qt/QtCore/qlist.h:1093,
                 from /usr/include/qt/QtCore/qstringlist.h:41,
                 from /usr/include/qt/QtGui/qcolor.h:46,
                 from /usr/include/qt/QtGui/QColor:1,
                 from /tmp/yaourt-tmp-jake/aur-keepassxc-git/src/keepassxc/src/format/KeePass2XmlReader.h:21,
                 from /tmp/yaourt-tmp-jake/aur-keepassxc-git/src/keepassxc/src/format/KeePass2XmlReader.cpp:18:
/usr/include/qt/QtCore/qstring.h:1584:12: note: candidate: int QStringRef::compare(const QString&, Qt::CaseSensitivity) const
 inline int QStringRef::compare(const QString &s, Qt::CaseSensitivity cs) const Q_DECL_NOTHROW
            ^~~~~~~~~~
/usr/include/qt/QtCore/qstring.h:1515:9: note: candidate: int QStringRef::compare(const QByteArray&, Qt::CaseSensitivity) const
     int compare(const QByteArray &s, Qt::CaseSensitivity cs = Qt::CaseSensitive) const
         ^~~~~~~
make[2]: *** [src/CMakeFiles/keepassx_core.dir/build.make:903: src/CMakeFiles/keepassx_core.dir/format/KeePass2XmlReader.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:257: src/CMakeFiles/keepassx_core.dir/all] Error 2
make: *** [Makefile:139: all] Error 2
```

## Possible Solution
No idea. I did get an update for a large number of QT packages from 5.7.1 to 5.8 just before installing, looking at the error this may be related?

## Steps to Reproduce (for bugs)
1. `yaourt -S keepassxc-git`

__Note__: This also happens with `keepassxc` and `keepassxc-keepasshttp` packages too  

## Context
Can't install application at all

## Your Environment
* KeePassXC version/commit used: (can be found under Help -> About) Current master: `0091cb3`
* Qt version (e.g. Qt 5.3): 5.8
* Compiler (e.g. Clang++3.6.0): 3 6 1 
* Operating System and version: Arch Linux 64-Bit

**Comment by TheZ3ro** [comment] 2017-01-29 18:39
Duplicate of https://github.com/keepassxreboot/keepassxc/issues/195

Fixed in #211 merged in `release/2.1.1` branch. Checkout and compile from that branch if you don't want to wait for the 2.1.1 release

**Closed by TheZ3ro** 2017-01-29 18:39 UTC
