### ISSUE TITLE
On Fedora with Firefox service does not go really any more

### ISSUE THREAD

**Issue by xzj8b3** [keepassxreboot/keepassxc#3995] opened 2019-12-09 10:55 UTC
On Fedora with Firefox service does not go really any more

Since Firefox has already declared in the future will make several updates, it would be interesting to understand if this service will be able to keep up with it or maybe better to opt for something else!!!!

**Comment by varjolintu** [comment] 2019-12-09 11:31
Duplicate of https://github.com/keepassxreboot/keepassxc-browser/issues/704.

**Closed by varjolintu** 2019-12-09 11:31 UTC
Labels: bug
