### ISSUE TITLE
Do not store group fold / unfold state

### ISSUE THREAD

**Issue by lubko** [keepassxreboot/keepassxc#535] opened 2017-04-28 13:56 UTC
Hello,
i found KeePassXC when searching for alternatives to KeePassX.

## Current Behavior
One thing the i have problem with in both, is that whenever i look for certain key, i am bound to fold and unfold several groups. This marks the db as modified, even though no data has been modified.

For me, it is much more important, to be sure i did not accidentally made changes to the DB while navigating it, than remembering that last fold/unfold group state.

It also creates unnecessary conflicts when syncing the DB over machines with unison at the end of the day.

## Possible Solution
I guess, in the best case, i would like to see a setting : "group tree on startup all_folded/all_unfolded/last_state"
Or maybe some additional logic, if i unfold a group (dirty flag will be shown as it is now) and when i fold it back the dirty flag disappears, and i can close the DB without seeing save_modified dialog.

**Comment by TheZ3ro** [comment] 2017-04-28 14:37
Duplicate of #446. This is already in develop and will be in 2.2.0 release

**Closed by TheZ3ro** 2017-04-28 14:37 UTC
