### ISSUE TITLE
Checkboxes are tiny on Linux

### ISSUE THREAD

**Issue by marcbone** [keepassxreboot/keepassxc#1384] opened 2018-01-14 17:00 UTC
Simmilar to #1381 the checkboxes(not just the checkmarks) dont scale with the font in ubuntu with 2880x1620 display and scaling set to 200%
## Expected Behavior

Checkboxes should be as big as the text
## Current Behavior

![bildschirmfoto vom 2018-01-14 17-39-30](https://user-images.githubusercontent.com/16033059/34918448-cc5f0e36-f952-11e7-9399-f8ed6b4cb7e5.png)

(Also icons on the left dont scale as already mentioned in #548 and #475)

## Debug Info

KeePassXC - Version 2.2.4
Revision: 4723f66

Libraries:
- Qt 5.5.1
- libgcrypt 1.6.5

OS: Ubuntu 16.04.3 LTS

Kernel: linux 4.13.0-26-generic

extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

**Comment by phoerious** [comment] 2018-01-15 16:23
I'm closing this as a duplicate of #1384 so we don't need to maintain two issues.
We've had several HiDPI problems in the past. Qt appears to be quite unpredictable in this regard.

**Closed by phoerious** 2018-01-15 16:23 UTC
