### ISSUE TITLE
Window still visible on KDE Plasma after credential access confirmation

### ISSUE THREAD

**Issue by zeidspex** [keepassxreboot/keepassxc#6348] opened 2021-03-27 02:05 UTC
## Overview
While browsing, if I click on the KeePassXC icon to request filling a username and password, an access confirmation dialog is shown with choices "Allow Selected" or "Deny All". If I choose "Allow Selected", then the KeePassXC window will come to the foreground.

## Steps to Reproduce
1. Unlock database
2. Navigate using browser to website with stored credentials
3. A dialog with "Allow Selected" or "Deny All" should show up
4. Select "Allow Selected"
5. KeePassXC window is on the foreground

## Expected Behavior
The browser window should remain at the foreground.

## Actual Behavior
The KeePassXC comes to the foreground forcing the user to minimize it, or otherwise click on browser to regain focus.

## Context
KeePassXC - 2.6.4

Operating System: Linux - OpenSUSE Leap 15.2
Desktop Env: KDE Plasma
Windowing System: X11

**Comment by pwseo** [comment] 2021-08-22 17:32
Also confirmed using openSUSE Tumbleweed, on KDE Plasma with X11.

**Comment by kotoko** [comment] 2022-01-09 11:46
Probably duplicate of #5270 .

**Closed** 2022-01-09 12:36 UTC
Labels: bug, feature: Browser, platform: KDE
