### ISSUE TITLE
Add the ability to increase the font in the program settings

### ISSUE THREAD

**Issue by steinvard** [keepassxreboot/keepassxc#9619] opened 2023-07-09 18:55 UTC
The font used by the program is quite small, and therefore it is not very comfortable to read it. For example, the font used here on GitHub is slightly larger and therefore easier to read. Please add a function to the program settings that allows you to select an increased font size, at least for user data. I'm talking about text information, which is located in the fields, starting with the Title field and ending with the Notes field.

My review is about KeePassXC 2.7.5 on Windows 10.

I know about the ability to choose an increased font size in the operating system settings up to 175% (Settings > System > Display > Scale and layouts). But this change affects all other programs, so it is not a solution for me. I would like to increase the font only in KeePassXC, since the font in it is the smallest compared to everything else that I use on a daily basis.

**Comment by droidmonkey** [comment] 2023-07-09 19:07
Duplicate of #6822

**Closed as completed by droidmonkey** 2023-07-09 19:07 UTC
