### ISSUE TITLE
Accidently copying passwords when note field is selected

### ISSUE THREAD

**Issue by pellaeon** [keepassxreboot/keepassxc#2038] opened 2018-06-08 04:12 UTC
## Expected Behavior
1. select an item in keepassxc
2. select the Note tab (or Comment, I'm not sure what the wording is since I'm using Chinese version)
3. select text within the Comment
4. press Command+C (to copy)
5. go to some other text field (for example a notepad)
6. press Command+V (to paste)
7. the selected text from Comment in step 3 is pasted

## Current Behavior
In step 7, the password is pasted instead

## Context
I was trying to quickly paste my notes to a person messaging with me, so I quickly selected the note, hit Command+C, selected the messaging app text box, hit Command+V and immediately Enter, this sent my password to that person.

## Debug Info
KeePassXC - 版本 2.3.3
修訂：0a155d8

函式庫：
- Qt 5.9.3
- libgcrypt 1.8.2

作業系統：macOS High Sierra (10.13)
處裡器架構：x86_64
核心：darwin 17.5.0

已啟用的擴充元件：
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

## Screenshot
This is the screenshot before I hit Command+C in step 4:
![2018-06-08 12 13 42](https://user-images.githubusercontent.com/916913/41138689-8dedb0c8-6b15-11e8-9326-5257f710a4b9.png)

**Comment by droidmonkey** [comment] 2018-06-10 01:59
This is a duplicate

**Comment by redm123** [comment] 2018-09-03 23:00
I agree, annoying behavior. Just updated to 2.3.4, but still copies the password. So the ticket is still open for a reason, I guess...

**Comment by droidmonkey** [comment] 2018-09-03 23:14
Whoops, I forgot to tag this 2.3.4 and it fell through.

**Comment by droidmonkey** [comment] 2018-10-24 19:50
Duplicate of #1653

**Closed by droidmonkey** 2018-10-24 19:50 UTC
Labels: high priority, user interface

**Comment by madbird1304** [comment] 2024-02-21 02:24
Folks, really? 

You had a bug with "Copy" (just copy) feature always copyig a password when something were selected in Note field, so you made it to always copy a note, despite I'm actually clicking a "Copy <a god damn> Password" button?

https://github.com/keepassxreboot/keepassxc/assets/18216480/845b7dc6-2b22-4b0b-84ad-cfaa05164e12

Just... What the hell? 

May I ask you why you didn't just make it this way:
- Copy **\<something\>** (Keyboard \<Control\>-C, \<Command\>-C, Context Menu Entry \<copy\>,  etc) -- copy a **current selection** or **nothing if nothing selected**.
- Copy **Login** button -- copy a god damn **login**
- Copy **Password** button -- copy a god damn **password**
- Copy **URL** button -- copy a god damn **URL**

Because this is the way how it's *supposed to* work from user's perspective.

I am sorry for my complain being so emotional, but the way the "Copy" feature implemented is really driving me crazy. As if nobody cares at all. How can I trust devs in cryptography field, if even the "Copy" function is implemented so carelessly?

**Comment by redm123** [comment] 2024-02-21 20:38
Never noticed that, but I agree, that's an awkward behavior... a bug actually. Of course a dedicated password copy button should always copy the password...

I think Ctrl/Cmd-C could still copy the password as default behavior, if there is no selection in notes. But the button should always copy what it's labeled to do.

Also just noticed: if there is no username or URL the respective copy buttons are disabled. Good. But if there is no password, the password copy button is still enabled...
