### ISSUE TITLE
Crash when unlocking a DB, and switch to another tab while it's unlocking

### ISSUE THREAD

**Issue by fritschy** [keepassxreboot/keepassxc#4187] opened 2020-01-15 07:14 UTC
I have a DB that takes a rather long time to unlock, so while it unlocked I switched to another DB. When the first one unlocked, it crashed right away. I was able to easily reproduce this.

## Expected Behavior
Do not crash, open the first DB in the "background" tab.

## Current Behavior
Crash.

## Steps to Reproduce
Prerequisites: have two locked DBs in two tabs open, one of them (the one to unlock first should take a rather long time to unlock, enough time to switch tabs after PW entry).
1. Unlock the first DB (happens only when unlock is (would be?) successful).
2. while it is computing, switch to the other tab.
2. Crash.
3.

## Context
I have 2 Databases, at least one of them takes a long time to unlock.

## Debug Info
KeePassXC - Version 2.5.2
Revision: 62cda9d

Qt 5.13.2
Debugging mode is disabled.

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.18362

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by droidmonkey** [comment] 2020-01-15 11:07
Ugh, I thought this was fixed (at least I couldn't replicate it before).

**Comment by GithubGY** [comment] 2020-01-18 01:44
During a 10-15 minutes period I saved the db 5 times. Last time I saved it a pop-up window showed up telling that the db was modified outside (or something very similar) and asked for a reload. I accepted the reload, although there was no reason to do so (the db is stored only locally in a VeraCrypt container and the saved process finished a fraction of a second before the pop-up appeared). After accepting the reload the app just crashed. It just disappeared completely from the memory without cleaning it up.
I don't know if this is related to the crash described above, but looks similar: KeePassXC 2.5.2 crashed while a db was loading (after an unnecessary request).

**Comment by droidmonkey** [comment] 2020-01-18 12:11
That is unrelated to this crash. Although I am surprised you are experiencing a save/merge crash in 2.5.2 since we fixed that issue.

**Comment by droidmonkey** [comment] 2020-01-20 14:19
Confirmed this is still occuring.

**Comment by droidmonkey** [comment] 2020-04-02 22:11
This was fixed with #4309

**Closed by droidmonkey** 2020-04-02 22:11 UTC
Labels: bug, crash :boom:
