### ISSUE TITLE
Copying plaintext from quickview notes copies the password

### ISSUE THREAD

**Issue by r4ptor** [keepassxreboot/keepassxc#1860] opened 2018-04-18 19:22 UTC
When the user copys a note entry from the notes field, which was accessed over quickview (highlight the entry and just move to notes), the highlighted text isn't copied, but the standard password field is. If opening the entry with double click and then copy the text entry, the content will be copied correctly. 

This also only happens with Strg + c. If the highlighted text is copied with rightclick everything works as it should.

## Expected Behavior

The hightlighted text should be copied, not the actual password. 

## Current Behavior

Password is always copied into the clipboard, no matter what is selected in the quick view notes 

## Steps to Reproduce (for bugs)

1. Unlock KeepassXC
2. Navigate to an entry with notes
3. Navigate to notes on the bottom(quick view)
4. Select text and copy it with strg +c 
5. Password from the password field of this entry is copied to the clipboard instead

## Debug Info

KeePassXC - Version 2.3.1
Revision: 2fcaeea

Libraries:
- Qt 5.10.1
- libgcrypt 1.8.2

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.15063

&

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 4.15.15-1-ARCH

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by droidmonkey** [comment] 2018-04-19 01:06
Duplicate of #1653

**Closed** 2018-04-19 01:06 UTC
Labels: duplicate
