### ISSUE TITLE
Feature request : Add animation when a user double click on a field to copy it

### ISSUE THREAD

**Issue by F3000** [keepassxreboot/keepassxc#4501] opened 2020-03-27 20:51 UTC
Example : 

when I double click on the Passwort field the password is copied but I didn’t see it . 

Would be nice when there is a small notifications that display “ Field XXX copied successfull” etccf

**Comment by droidmonkey** [comment] 2020-03-28 01:28
Duplicate of #1843

**Closed by droidmonkey** 2020-03-28 01:28 UTC
