### ISSUE TITLE
KeePassXC installed as snap, prevent laptop from going to sleep, when you close the lid

### ISSUE THREAD

**Issue by user240** [keepassxreboot/keepassxc#1309] opened 2017-12-20 10:51 UTC
## Expected Behavior

laptop will go to sleep when you close the lid

## Current Behavior

doesn't go to sleep

## Steps to Reproduce (for bugs)

1. Install KeePassXC as snap on laptop
2. run KeePassXC
3. close the lid

**Comment by phoerious** [comment] 2017-12-21 21:48
Duplicate of #856 (most likely).

**Closed** 2018-03-02 23:02 UTC
Labels: duplicate
