### ISSUE TITLE
macOS 10.15 Catalina: Yubikey slots not populating

### ISSUE THREAD

**Issue by doits** [keepassxreboot/keepassxc#3329] opened 2019-06-27 12:16 UTC
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

Since upgrading to 10.15 catalina beta I cannot unlock my database which is secured with yubikey challenge response: the yubikey is not detected.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

Unlock database with yubikey

## Current Behavior
[NOTE]: # ( Tell us what actually happens )

Yubikey is not detected:

![Jun-27-2019 14-14-37](https://user-images.githubusercontent.com/148003/60265403-f2cd8a00-98e5-11e9-9d80-c1b5537fec94.gif)

I tried restarting everything, no change :-(

Otherwise yubikey works as expected (eg. with gpg), so currently only keepassxc cannot access it.

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.4.3
Revision: 5d6ef0c

Qt 5.12.3
Debugging mode is disabled.

Operating system: macOS 10.15
CPU architecture: x86_64
Kernel: darwin 19.0.0

Enabled extensions:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.4

**Comment by droidmonkey** [comment] 2019-06-27 13:37
Does it work with the Yubikey Personalization tool?

**Comment by doits** [comment] 2019-06-27 14:43
good catch, no, it doesn't. It says "unkown error" when I attach the yubikey.

<img width="231" alt="Bildschirmfoto 2019-06-27 um 16 42 54" src="https://user-images.githubusercontent.com/148003/60275728-a6d91000-98fa-11e9-9df5-ebdd5d3efa01.png">

**Comment by droidmonkey** [comment] 2019-06-27 14:46
Then this would be an error at the OS level or an incompatibility with yubikey itself. Recommend reporting the bug over on their repository: https://github.com/Yubico/yubikey-personalization-gui

**Comment by doits** [comment] 2019-06-27 14:50
:+1: reported at https://github.com/Yubico/yubikey-personalization-gui/issues/87

**Comment by doits** [comment] 2019-06-27 15:05
One more hint though: Using it in browsers for 2fa authentication or as a gpg smartcard for signing/encrypting e-mails still works though, so it is not completely broken. But looks like the functionality used in keepassxc and personalization tool is.

**Comment by doits** [comment] 2019-07-01 11:19
I made it working again by going to system settings --> security --> privacy --> input monitoring and manually adding keepassxc.app there. Looks like this permission should be requested by keepassxc when launching and/or trying to access yubikeys.

**Comment by doits** [comment] 2019-07-01 11:23
... although there is one minor flaw: The only yubikey is displayed three times now:

<img width="1218" alt="Bildschirmfoto 2019-07-01 um 13 20 25" src="https://user-images.githubusercontent.com/148003/60432692-31738500-9c03-11e9-92d4-e00c224f15b5.png">

It is three times the exactly same entry and selecting any of them works.

**Comment by droidmonkey** [comment] 2019-07-01 12:45
Yes looks like Catalina is introducing new privacy features that require additional approvals. Unfortunately they don't seem to be documented yet or it is non-intuitive when I read the apple developer documentation.

**Comment by Vertux** [comment] 2019-08-30 20:48
I can confirm this issue, it persists with the current Dev Beta 10.15 (19A546d) - I have reported Apple this issue already. As workaround you can start KeePassXC (v2.4.3) from the comand line, then it works as exspected and the YubiKey is recognized correctly.

**Comment by thobryan** [comment] 2019-09-10 08:49
That's quite annoying issue from mac. I am facing this intermittent issue everyday, when I restart my computer everything works but after few minutes (sometimes hours) it stop to work, if I try to type any command in terminal (like: ykinfo -s)  I receive this message: "USB error: kIOReturnSuccess". This look likes a permission issue to read the USB port, since if I am with a root user it works pretty fine (ykinfo and also keepassxc). 

@doits , what version of MacOS are you using? I didn't find  "input monitoring" option inside privacy. I tried to add the keepassxc inside "Accessibility" but it didn't solve.

**Comment by doits** [comment] 2019-09-10 09:14
@thobryan using Beta 10.15 (19A546d) and it works like this for me:

<img width="751" alt="Bildschirmfoto 2019-09-10 um 11 13 56" src="https://user-images.githubusercontent.com/148003/64600842-1cae2d00-d3bc-11e9-881a-46d2a8682693.png">

**Comment by thobryan** [comment] 2019-09-10 09:18
Weird, I dont have this option :-( I am on 10.14.6. 

<img width="665" alt="Screenshot 2019-09-10 at 11 17 26" src="https://user-images.githubusercontent.com/1568887/64601133-abbb4500-d3bc-11e9-9e98-fe2746dd02b1.png">

**Comment by doits** [comment] 2019-09-10 10:05
afaik this is new on 10.15, so it makes sense you don't have it on 10.14.6 :-) Looks like your issue is a different one then.

**Comment by james56b** [comment] 2019-09-20 12:07
On the latest 10.15 (19A558d) and I don't have the option to add an application....

![Screenshot 2019-09-20 at 14 05 49](https://user-images.githubusercontent.com/10844794/65325660-c0af8980-dbaf-11e9-9548-3f0cb00ead26.png)

**Comment by Vertux** [comment] 2019-09-20 17:59
> Weird, I dont have this option :-( I am on 10.14.6.
> 
> <img alt="Screenshot 2019-09-10 at 11 17 26" width="665" src="https://user-images.githubusercontent.com/1568887/64601133-abbb4500-d3bc-11e9-9e98-fe2746dd02b1.png">

@thobryan  You should not have any issues with MacOS 10.14.6 because it is the regular MacOS version (I run it on my second Mac too and there I have no problems with KeePassXC), we are talking about the **10.15 Beta**, this version has intoduced many new security features, which lead into problems with some old applications.

**Comment by thobryan** [comment] 2019-09-20 18:39
Hi @Vertux , but unfortunately it's happening with me... I tried 3 different keys (Yubikey 5 NFC with adaptor and Yubikey 5C) all failed after few minutes/hours. As a root it works. The same keys works in an old macbook that I have also in 10.14.6 (18G95).

**Comment by Vertux** [comment] 2019-09-21 11:32
@thobryan Weird, I got two ideas.

Sometimes it happens, that an application is not correctly recognized by macos when you install it, which means no window pops up where you have to give the app the required rights to opperate correctly. It can help if you reinstall the app and then start it for the first time from the comandline/terminal, then you should get the mentioned window - afterwards you can it start it normally. It can always help to investigate issues by starting an app from the commandline, because you can see possible errors.
Maybe you are running additional security software or a software/driver which exclusivly blocks the USB/Lightning port on your (new) macbook.

**Comment by thobryan** [comment] 2019-09-23 10:52
Hi @Vertux . Thanks a lot for the information, in fact I am using Norton Security antivirus. But I am going to do what you suggested and see If can I catch some new information to share.

**Comment by thobryan** [comment] 2019-09-23 15:03
Just got the error (after 5 or 6 hours):  

```
[12:53:53][thomas][~]: /Applications/KeePassXC.app/Contents/MacOS/KeePassXC
QObject::startTimer: Timers cannot have negative intervals
Failed to issue challenge
```

Have some verbose parameter that I can run to have more information?

**Comment by droidmonkey** [comment] 2019-09-23 15:35
The last message is what matters. That means KeePassXC cannot communicate with the Yubikey to perform the Challenge-Response.

**Comment by thobryan** [comment] 2019-10-01 09:48
Yesterday my mac was updated to 10.14.6 (18G103), maybe it's too early to celebrate, but seems that the issue was fixed.

**Comment by Vertux** [comment] 2019-10-01 19:11
Bad news I just have updated to **MacOS 10.15 Beta (19A578c)** and KeePassXC again does not work anymore - till now I cannot get it working again. If I start it from the command line I get the the following error:

`QObject::startTimer: Timers cannot have negative intervals`

![Bildschirmfoto 2019-10-01 um 21 08 14](https://user-images.githubusercontent.com/10457918/65992498-a15a0b80-e48f-11e9-9806-391db76ea31f.png)

**Comment by droidmonkey** [comment] 2019-10-01 19:51
The original issue (read the first post) clearly states that was a problem.

**Comment by Vertux** [comment] 2019-10-02 06:53
> The original issue (read the first post) clearly states that was a problem.

@droidmonkey you did not understand what I mean. For the last MacOS 10.15 Beta there was an easy workaround see @doits post, but with the current Beta (19A578c) this does not work anymore

**Comment by doits** [comment] 2019-10-02 08:34
Still using it with 19A578c and it works. Did you add it to [input monitoring](https://github.com/keepassxreboot/keepassxc/issues/3329#issuecomment-529847992)?

**Comment by Vertux** [comment] 2019-10-02 12:03
> Still using it with 19A578c and it works. Did you add it to [input monitoring](https://github.com/keepassxreboot/keepassxc/issues/3329#issuecomment-529847992)?

@doits It is very weird, I had already added it to input monitoring and I have tried it a couple of times yesterday and it did not work. Today I have removed it and then I have added it to input monitoring again and I have restarted the MBA - the miracle happens - now it works again.

**Comment by droidmonkey** [comment] 2019-10-02 13:43
macOS likes to "forget" permissions you gave an app but still show that you gave them. I've run into this with AutoType as well.

For this issue, is there a new entitlement we should be asking for?

**Comment by DanJohnsonCERN** [comment] 2019-10-14 12:10
This issue is preventing me from using my KeePass. Is there any news since 12 days ago? (yes, I already gave input monitoring permission, but this seems to work *possibly* once per reboot (or per re-install of keepassx), which is a real pain. Is KeePass now incompatible with YubiKey for OS 10.15 users?

**Comment by droidmonkey** [comment] 2019-10-14 13:22
@DanJohnsonCERN This is an issue that may be outside our ability to correct. You probably have to follow the instructions above and ensure input monitoring setting is granted.

**Comment by DanJohnsonCERN** [comment] 2019-10-14 13:31
Thanks @droidmonkey . I have already followed the instructions above, and keepassxc only detects the yubikey slots at most once (per reboot or re-install). To re-iterate, the yubikey works fine (enters text etc) but is not consistently detected by keepassxc.

**Comment by droidmonkey** [comment] 2019-10-14 13:39
Please try our 2.5.0 snapshot: https://snapshot.keepassxc.org/latest

I improved Yubikey handling recently.

**Comment by DanJohnsonCERN** [comment] 2019-10-14 13:55
Aha, nice, that works perfectly first time (after input monitoring permission, obv). I'll get back to you here if it stops later. Thank you for your time/work @droidmonkey !

**Comment by kanutope** [comment] 2019-10-31 18:36
Upgraded from 10.14.6 today to 10.15.1 - created manually 'input monitoring' entries for both KeePassXC and YubiKey Personalization Tool - it works smoothly. Thanks @droidmonkey

**Comment by droidmonkey** [comment] 2019-10-31 19:00
I need to figure out how to trigger the permission request for input monitoring

**Comment by 499602D2** [comment] 2019-11-20 12:55
I'm on a machine stuck on High Sierra and I've had this issue ever since I got my YubiKey, so around version 2.3.4, and I was unable to fix the issue with the privacy settings mentioned above, as High Sierra lacks all of it.

However, I did some Googling around, and it seems that this issue is somehow triggered if  "Secure Keyboard Entry" is enabled in Terminal's settings – I disabled it, and my key started to immediately work in KeepassXC, alongside with `ykinfo -a` producing actual output instead of `USB error: kIOReturnSuccess`, even when not run as sudo.

This thread is relevant: https://github.com/Yubico/yubikey-personalization/issues/34

**Comment by FaMux** [comment] 2019-11-23 00:02
I'am on a machine stuck with High Sierra (10.13.6) and have same problem as well. Disabling the "Secure Keyboard Entry" in the Terminal settings works for me fine (KeePassXC 2.5.1).
Citation from Apple support [page](https://support.apple.com/lv-lv/guide/terminal/trml109/2.8/mac/10.13) says:
> Before you turn on secure keyboard entry, make sure other apps don’t require keystrokes from Terminal.

Thanks for the hint @499602D2 ! This does not solve the real problem, but for now a good workaround.
![DisableSecureKeyboard](https://user-images.githubusercontent.com/32147448/69468187-88811e80-0d8b-11ea-85c8-ccc486a19b79.png)

**Comment by onlykey** [comment] 2020-01-07 17:37
I can verify that adding to security -> privacy -> input monitoring also works for OnlyKey. Is it possible for future release to automatically request adding KeePassXC to input monitoring? I think it already requests to automatically be added to accessibility.

**Comment by droidmonkey** [comment] 2020-01-07 17:52
I'll need a link to the documentation to do that

**Comment by onlykey** [comment] 2020-01-08 14:07
@droidmonkey Did a little digging into it and I am thinking that Mac released 10.15 without a way yet for apps to request this, or at least its not documented yet:
https://forums.developer.apple.com/thread/124368
https://developer.apple.com/documentation/bundleresources/information_property_list/protected_resources

**Comment by MarSalfer** [comment] 2020-08-08 06:31
Workaround Generally: Add ("+" or drag and drop) KeePassXC.app into "System Settings --> Security --> Privacy --> Input Monitoring".

Workaround when the above won't work as no list appears: **Populate _Input Monitoring_ with another app first.**

1. Start an app that requests _Input Monitoring_ permissions, e.g. [CheatSheet](https://mediaatelier.com/CheatSheet/). The _Input Monitoring_ window will be opened and populated with this one app plus a "+" and a drag-drop functionality.
1. Add or drag-drop KeePassXC into the _Input Monitoring_ list.
1. (optionally) remove the other app again.

**Comment by tswestendorp** [comment] 2020-08-20 07:11
I've tried all the possible workarounds to get my OnlyKey working. KeePassXC is added to input monitoring and version 2.6.1, re-added is a couple of times as well, but still slots aren't populated.

Just a minute ago I found errors some errors caused by KeePassXC in my Console:
```
error	09:10:05.384303+0200	KeePassXC	IOConnectCallMethod(kIOHIDLibUserClientOpen):e00002c5
error	09:10:06.407640+0200	KeePassXC	IOConnectCallMethod(kIOHIDLibUserClientOpen):e00002c5
error	09:10:07.318337+0200	KeePassXC	IOConnectCallMethod(kIOHIDLibUserClientOpen):e00002c5
error	09:10:07.983491+0200	KeePassXC	IOConnectCallMethod(kIOHIDLibUserClientOpen):e00002c5
```

These errors occur when hitting 'Refresh' next to the slots. Anybody got an idea what might be happening here? 

cc @onlykey

**Comment by droidmonkey** [comment] 2020-08-20 10:54
@phoerious what version of ykpers are you deploying with the macos build?

**Comment by phoerious** [comment] 2020-08-20 12:56
Can't check right now, but it should be the latest one from homebrew.

**Comment by onlykey** [comment] 2020-08-20 13:53
@tswestendorp Mac OS requires restart of app to have the privacy change take effect. I think in some cases it may require a reboot though, any luck after reboot?

**Comment by tswestendorp** [comment] 2020-08-21 06:33
> @tswestendorp Mac OS requires restart of app to have the privacy change take effect. I think in some cases it may require a reboot though, any luck after reboot?

Unfortunately not 😕

**Comment by repetitioestmaterstudiorum** [comment] 2020-12-27 10:39
> I'am on a machine stuck with High Sierra (10.13.6) and have same problem as well. Disabling the "Secure Keyboard Entry" in the Terminal settings works for me fine (KeePassXC 2.5.1).
> Citation from Apple support [page](https://support.apple.com/lv-lv/guide/terminal/trml109/2.8/mac/10.13) says:
> 
> > Before you turn on secure keyboard entry, make sure other apps don’t require keystrokes from Terminal.
> 
> Thanks for the hint @499602D2 ! This does not solve the real problem, but for now a good workaround.
> ![DisableSecureKeyboard](https://user-images.githubusercontent.com/32147448/69468187-88811e80-0d8b-11ea-85c8-ccc486a19b79.png)

This was the solution for me too!

**Comment by droidmonkey** [comment] 2020-12-27 12:41
I am closing this issue since it's not on us.

**Closed by droidmonkey** 2020-12-27 12:41 UTC
Labels: platform: macOS, plugin: YubiKey, upstream
