### ISSUE TITLE
Show password: password is unreadable, because of scrollbar, if too long

### ISSUE THREAD

**Issue by MorsMortium** [keepassxreboot/keepassxc#9233] opened 2023-03-12 12:19 UTC
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
In the default page (not in edit mode), the eye icon, that shows the password, also displays a scrollbar, if the password is too long, hiding half the password.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Create a password, with 99 chars length
2. Open KeePassXC's main window
3. Click on eye icon, to show password

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
The scrollbar appears outside the field, or not at all, or any way, that doesn't hide the password.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
The scrollbar hides half the password, as it is in the same field.

## Context
[NOTE]: # ( Give us any additional information you may have. )
Use case: quick compare of possibly duplicate entries.

![Screenshot_20230312_131822](https://user-images.githubusercontent.com/44305161/224544098-96c28757-1cb5-4d8e-973e-4aa347f90c9b.png)

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.4
Revision: 63b2394

Qt 5.15.8
Debugging mode is disabled.

Operating system: Manjaro Linux
CPU architecture: x86_64
Kernel: linux 6.2.2-1-MANJARO

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.19.3

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux (Manjaro)
Desktop Env: KDE
Windowing System: X11

**Comment by droidmonkey** [comment] 2023-03-12 12:34
Looks like you are in classic theme mode. Does it do this in dark theme?

Also duplicate of #9190

**Closed as not planned** 2023-03-12 12:35 UTC
Labels: duplicate
