### ISSUE TITLE
Reopening database with KeePassXC-Browser triggers Yubikey udev rule

### ISSUE THREAD

**Issue by jeremyj** [keepassxreboot/keepassxc#3194] opened 2019-05-30 08:54 UTC
## Expected Behavior
I expect KeePassXC-Browser not to trigger the udev rule

## Current Behavior
I have a udev rule that locks my screen when my Yubikey is removed

`ACTION=="remove", ATTRS{idProduct}=="0407", ATTRS{idVendor}=="1050", RUN+="/bin/loginctl lock-sessions"`

Whenever I click on the KeePassXC-Browser button in my browser to unlock the database this triggers the udev rule and my screen gets locked.
Furthurmore after this the udev rule stops working until I unplug and plug the Yubikey again.

I have tested this with:
KeePassXC-Browser 1.4.5
Brave Browser 0.64.77
Firefox 67

This is the output of `udevadm monitor`:
https://pastebin.com/gcHTwXiW

## Possible Solution
Unlock the database directly from the the app

## Steps to Reproduce
1. configure yubikey/lockscreen udev rule
2. plug in yubikey
3. click on KeePassXC-Browser then "Reopen database"

## Debug Info
KeePassXC - Version 2.4.1
Revision: 7bafe65

Qt 5.9.5
Debugging mode is disabled.

Operating system: Ubuntu 18.04.2 LTS
CPU architecture: x86_64
Kernel: linux 4.18.0-20-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.1

**Comment by jeremyj** [comment] 2019-05-30 08:59
Sorry, just realized there's a keepassxc-browser repo.
I'm guessing this issue belongs there....

**Comment by droidmonkey** [comment] 2019-05-30 10:38
This isn't in the browser extension. Although it is quite possibly a duplicate of our other Yubikey bugs.

**Comment by droidmonkey** [comment] 2019-05-30 12:20
I'm starting to wonder if the bugs we see with Yubikey are actually with the firmware on the Yubikey (or it's driver software). We don't tell the Yubikey to "remove" itself. You can inspect the code here, all we do is grab an instance, query it, and release.

https://github.com/keepassxreboot/keepassxc/blob/develop/src/keys/drivers/YubiKey.cpp#L60

**Comment by droidmonkey** [comment] 2019-05-30 12:24
Now when we call ```yk_closekey(yk)``` that triggers this function:

https://github.com/Yubico/yubikey-personalization/blob/master/ykcore/ykcore_libusb-1.0.c#L225

Which does call ```libusb_close((libusb_device_handle *) yk);```

I would expect ```libusb_reset_device``` to cause the behavior you see:
http://libusb.sourceforge.net/api-1.0/group__dev.html#ga7321bd8dc28e9a20b411bf18e6d0e9aa

**Comment by jeremyj** [comment] 2019-05-30 12:25
But why do you say this isn't related to the browser extension?
If I unlock the database from the app this problem doesn't occur.

**Comment by droidmonkey** [comment] 2019-05-30 12:28
The extension has nothing to do with this, the error would be in the KeePassXC application.

**Comment by droidmonkey** [comment] 2019-05-30 12:30
Do you use your Yubikey with your browser as well as KeePassXC? Perhaps it is doing a handoff between the two apps that appears as a disconnect/reconnect

**Comment by jeremyj** [comment] 2019-05-30 12:35
I'm not sure I understand the question.
If you mean do I use the Yubikey as an U2F device with some website that is open at the moment this happens, I do. But I've had this happen also when there are no websites that use the Yubikey

**Comment by droidmonkey** [comment] 2019-05-30 12:37
Ahh ok, well that makes a big difference. Even if you are not using it, the browser can still retain control of the device.

**Comment by jeremyj** [comment] 2019-05-30 13:38
So opening the Yubikey Personalization Tool has the same effect, even with the browser closed. I open it and my screen locks. Furthurmore it keeps locking until I close the tool (it doesn't require me to unplug and plug the Yubikey for the udev rule to work). So now I'm confused. It seems that this issue has noting to do with KeePassXC?

**Comment by droidmonkey** [comment] 2019-05-30 14:12
Bingo! It's most certainly a bug (or feature) of Yubikey itself.

**Closed** 2019-05-30 14:13 UTC
Labels: bug, plugin: YubiKey
