### ISSUE TITLE
Add a Search Box when Auto-Type key pressed but no matches found

### ISSUE THREAD

**Issue by xKeiro** [keepassxreboot/keepassxc#788] opened 2017-07-17 23:52 UTC
**Current behaviour:**
Currently KeepassXC displays and error message when it couldn't find a matching entry after pressing the Auto-Type key. 

**Requested feature:**
---
In addition to informing the user about not finding a matching entry it would be nice to have a search box where you could input a custom string (fore example: "github" -> return the github entry) and find matching entry that way

**Additional comment:**
If this feature gets implemented it should search for a string not only in the Entries names but in the comments as well.

**Example KeePass plugin:**
 AutoTypeSearch : [Download/Info](https://sourceforge.net/projects/autotypesearch/)
![Screenshot](https://user-images.githubusercontent.com/7066695/28294505-fcdca36a-6b5a-11e7-8cea-52eea907a8c3.png)

**Comment by DJCrashdummy** [comment] 2017-07-23 21:23
@Kusaha i guess this is a duplicate of #429.

**Closed** 2019-07-10 02:33 UTC
Labels: wishlist
