### ISSUE TITLE
Allow copying/pasting of *entries* (entire records)

### ISSUE THREAD

**Issue by macau23** [keepassxreboot/keepassxc#1764] opened 2018-03-21 09:08 UTC
It would help if I could copy/paste and even drag and drop entire entries/records between different keepassxc datafiles.

## Expected Behavior
I'd like to do this using drag and drop or copy/paste.

## Current Behavior
I can't (or I can't find it).

Edit: there is a merge option under Database> Merge...

**Comment by droidmonkey** [comment] 2018-03-21 10:46
Duplicate of #172

**Closed by droidmonkey** 2018-03-21 10:46 UTC
