### ISSUE TITLE
Quit unexpectedly - macOS

### ISSUE THREAD

**Issue by msman0** [keepassxreboot/keepassxc#9733] opened 2023-08-12 13:39 UTC
## Overview
every time I close I get the system message
KeePassXC quit unexpectedly
...
reopen
report
ignore

with the previous version I had no problems.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. open KeespassXC
2. close KeepassXC (via menu quit)

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.5
Revision: 9d0537b

Qt 5.15.8
Debugging mode is disabled.

Operating system: macOS 13.5
CPU architecture: x86_64
Kernel: darwin 22.6.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.19.3

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS 13.5

**Comment by varjolintu** [comment] 2023-08-12 14:06
Duplicate of: https://github.com/keepassxreboot/keepassxc/issues/9423

**Closed as not planned by varjolintu** 2023-08-12 14:06 UTC
Labels: duplicate
