### ISSUE TITLE
Synchronization by Triggers (like KeePass)

### ISSUE THREAD

**Issue by firepainting** [keepassxreboot/keepassxc#3768] opened 2019-11-02 08:48 UTC
[TIP]:  # ( Provide a general summary of the feature in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

Quick intro:

I think this is related to #90, but I felt that a thread specifically for this--synchronization by triggers--was needed. If this is redundant, I apologize. (Merging and bidirectional sync, as I understand, have different purposes.)

(Note: A self-proclaimed non-techie here but I hope I'm getting the discussions right.)

## Summary
[NOTE]: # ( Provide a brief overview of what the new feature is all about )

After updating and saving a "main" database, 1 or 2 or more separate database "backups" (which are basically copies/clones) automatically sync with it. This can be done with KeePass, an example is found [here](https://keepass.info/help/kb/trigger_examples.html#dbsync).

## Desired Behavior
[NOTE]: # ( Tell us how the new feature should work, be specific )

Before setting up the triggers, multiple copies/clones of the main database should be reproduced (depending on how many backups you wish to have). These copies are then placed into folders of cloud servers, etc. (I explain this in the context of my circumstances, below.)

Then as stated in the Summary above, upon updating and saving the main database, i.e., the *one* database you mainly use on your PC, all database-backups automatically gets updated.

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )

I have 2 PCs, both on Linux Mint 19.2.

I can not manage to use something like Syncthing (or self-hosted solutions), so I need to use Dropbox.

Dropbox is my daily folder. Therefore, it must always be up to date. Before shutting down any PC, I make sure everything is fully synced.

But I'm not happy with only one cloud server for my online backups--I want two. So there's another cloud server I use, I'll just call it Cloud 2. 

To make my life more simple, the only steps I want to do with my *one* main database (which is in Dropbox) is to update it, hit save, and wait for it to tell me that all other databases I told it to sync have already synced. (KeePass does this.)

I do not want to always be replacing my main database, or *manually* making copies of it and then saving it in multiple folders.

So my backup solution goes like this:

All in all, I have 3 KDBX databases in each of my PC: in Dropbox, in Cloud 2, and in a local folder.

When I update and save the one in Dropbox, the ones in Cloud 2 and in the local folder sync with it. The one in the local folder goes to my external backup devices.

Recently, KeePass has been crashing whenever I write long entries in the "Notes" field. (KeePass is being developed mainly for Windows, I was on Windows before Linux.)

I considered moving to KeePassXC before, but the inability to set Triggers has been holding me back. 

Triggers are the *only* "special" feature I use. I try to make things as simple as possible. I only open my database on my PCs. I refuse to allow my phone to "see" my database because I'm a bit privacy-paranoid.

Thank you.

**Comment by droidmonkey** [comment] 2019-11-03 13:49
Duplicate of #1016

**Closed by droidmonkey** 2019-11-03 13:49 UTC
Labels: new feature
