### ISSUE TITLE
"Lock databases after inactivity" should use wall clock time

### ISSUE THREAD

**Issue by nlevitt** [keepassxreboot/keepassxc#4372] opened 2020-02-24 18:57 UTC
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior

I have "Lock databases after inactivity of" set to 7200 sec (2 hours). When I open my laptop in the morning, I expect the keepassxc database to be locked, because ~12 hours have passed since I last used it.

## Current Behavior

Keepassxc database is not locked. I surmise this must be because it doesn't count time when the machine is sleeping.

## Possible Solution

Imho the inactivity calculation should use wall clock time.

## Steps to Reproduce

Described above.

## Debug Info
KeePassXC - Version 2.5.3
Revision: f8c962b

Qt 5.14.0
Debugging mode is disabled.

Operating system: macOS 10.15
CPU architecture: x86_64
Kernel: darwin 19.3.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by droidmonkey** [comment] 2020-02-25 00:46
Duplicate of #2014

**Closed by droidmonkey** 2020-02-25 00:46 UTC
Labels: bug
