### ISSUE TITLE
Database file gets deleted on 'Save database as..'

### ISSUE THREAD

**Issue by openscript** [keepassxreboot/keepassxc#2957] opened 2019-04-07 08:26 UTC
I have a database file on a smb share (`/run/user/1000/gvfs/..`), which I open in KeePassXC 2.4.0 on my ArchLinux system. When I want to replace the database with a new version I use `Save database as..`. I get asked if I want to replace the file. The file is being deleted and **NO** new file is written. The database is basically gone.

## Expected Behavior
The destination database will be replaced.

## Current Behavior
The destination database is being deleted. No new file is being written.

## Possible Solution
Enable `Safely save database files` in the settings.

## Steps to Reproduce
1. Mount an SMB share
2. Open a database on this SMB share
3. Use `Save database as..` to replace it.

## Context
Linux hostname 5.0.6-arch1-1-ARCH #1 SMP PREEMPT Wed Apr 3 09:35:20 UTC 2019 x86_64 GNU/Linux

## Debug Info
KeePassXC - Version 2.4.0
Revision: c51752d

Libraries:
- Qt 5.12.2
- libgcrypt 1.8.4

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 5.0.6-arch1-1-ARCH

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey

**Comment by droidmonkey** [comment] 2019-04-07 10:59
Do you get an error message? Do you have save safes enabled? Does the SMB share have weird permissions?

**Comment by hifi** [comment] 2019-04-07 12:42
This is a gvfs mounted share so it's closely related to issues described in #803.

**Comment by openscript** [comment] 2019-04-07 16:48
> Do you get an error message? Do you have save safes enabled? Does the SMB share have weird permissions?

No, there is no error message at all. "Safely save database files" is not active. The SMB share has usual permissions. I've full read and write permissions on that share.

Interestingly is, that it worked fine with 2.3.4. I always used `Save database as..` because of #803.

**Comment by droidmonkey** [comment] 2019-04-07 17:07
Enable save safes and retry

**Comment by openscript** [comment] 2019-04-07 17:28
With `Safely save database files` it works fine.

**Comment by droidmonkey** [comment] 2019-04-07 18:13
Then this is a duplicate of the issue that is being fixed.

**Closed by droidmonkey** 2019-04-07 18:13 UTC
Labels: bug
