### ISSUE TITLE
Global autotype shotcut depends on layout

### ISSUE THREAD

**Issue by Raphi111** [keepassxreboot/keepassxc#367] opened 2017-03-02 17:52 UTC
## Expected Behavior
When Ctrl+Alt+A is set as global autotype shortcut, pressing it should trigger autotype, whatever the keyboard layout is.

## Current Behavior
When (for example) Ctrl+Alt+a is set as global autotype shorcut and the keyboard layout is set to 'be', the key triggering autotype is Ctrl+Alt+q (on be azerty keyboard, 'q' is where the 'a' is on a qwerty keyboard) and not Ctrl+Alt+a, although the correct key is detected and displayed in the settings dialog.

## Steps to Reproduce (for bugs)

1. Set your keyboard layout to azerty (setxkbmap fr or be, ...)
2. Set Ctrl+Alt+a as global autotype shortcut
3. Pressing Ctrl+Alt+a doesn't trigger autotype.
4. Pressing Ctrl+Alt+q triggers autotype.

## Your Environment
I'm using a minimal window manager with no particular desktop environment
* KeePassXC version/commit used: (can be found under Help -> About)
* Qt version (e.g. Qt 5.3): Qt 5.8.0
* Operating System and version: Parabola GNU/Linux, keepassxc version 2.1.0

**Comment by phoerious** [comment] 2017-03-02 17:54
Duplicate of #324.

**Closed by phoerious** 2017-03-02 17:54 UTC
