### ISSUE TITLE
v2.3.1 SIGSEGV on QByteArray::operator=() from EditEntryWidget::commitEntry()

### ISSUE THREAD

**Issue by dossy** [keepassxreboot/keepassxc#1780] opened 2018-03-24 20:42 UTC
```
KeePassXC - Version 2.3.1
Revision: 2fcaeea

Libraries:
- Qt 5.9.3
- libgcrypt 1.8.2

Operating system: OS X El Capitan (10.11)
CPU architecture: x86_64
Kernel: darwin 15.6.0

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey
```

```
Process:               KeePassXC [91433]
Path:                  /Applications/KeePassXC.app/Contents/MacOS/KeePassXC
Identifier:            org.keepassx.keepassxc
Version:               2.3.1 (???)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           KeePassXC [91433]
User ID:               501

Date/Time:             2018-03-24 16:40:06.556 -0400
OS Version:            Mac OS X 10.11.6 (15G1611)
Report Version:        11
Anonymous UUID:        7A895E1A-537A-D03A-CFB4-B6F160B849E8

Sleep/Wake UUID:       593E03F4-CC86-4BDD-AB18-A8EA98827DC4

Time Awake Since Boot: 750000 seconds
Time Since Wake:       6300 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       EXC_I386_GPFLT
Exception Note:        EXC_CORPSE_NOTIFY

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   org.qt-project.QtCore         	0x000000010d33c8a0 QByteArray::operator=(QByteArray const&) + 16
1   org.keepassx.keepassxc        	0x000000010c1461de Uuid::operator=(Uuid const&) + 14
2   org.keepassx.keepassxc        	0x000000010c122c6d Entry::beginUpdate() + 61
3   org.keepassx.keepassxc        	0x000000010c1eeebd EditEntryWidget::commitEntry() + 1021
4   org.keepassx.keepassxc        	0x000000010c1efc2e EditEntryWidget::acceptEntry() + 14
5   org.qt-project.QtCore         	0x000000010d5274bb QMetaObject::activate(QObject*, int, int, void**) + 2923

--- DROIDMONKEY SNIP ---
```

</details>

**Comment by woj-tek** [comment] 2018-12-24 23:13
About "not reproducible" tag added by @weslly - it crashes quite consistently for me (to a point where I kinda stopped using KeePassXC because it stopped being convenient constantly re-entering master password).

I'd love to help tackling this issue in any way I can (which would mostly be logs/testing I guess).

**Comment by droidmonkey** [comment] 2018-12-25 00:47
Let me package the latest 2.4 snapshot for macOS and you can try that. No sense in trying to fix something that may already be fixed.

**Comment by droidmonkey** [comment] 2018-12-25 13:52
Please try to reproduce using 2.4.0 snapshot: https://s3.amazonaws.com/droidmonkey-keepassxc/snapshots/KeePassXC-2.4.0-snapshot.dmg

**Comment by woj-tek** [comment] 2018-12-25 18:54
Unfortunately I can't start it - it crashes immediately:

<details>
```
Process:               KeePassXC [35434]
Path:                  /Applications/KeePassXC_dev.app/Contents/MacOS/KeePassXC
Identifier:            org.keepassx.keepassxc
Version:               2.4.0-snapshot (???)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           KeePassXC [35434]
User ID:               501

Date/Time:             2018-12-25 15:52:30.835 -0300
OS Version:            Mac OS X 10.14.2 (18C54)
Report Version:        12
Anonymous UUID:        7FD9A845-160C-741D-70E6-287E69F204BA

Sleep/Wake UUID:       10BFC9BB-6EFB-499C-B230-FA1F51B7959A

Time Awake Since Boot: 490000 seconds
Time Since Wake:       2800 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x3] Wrong version

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @executable_path/../Frameworks/QtSvg.framework/Versions/5/QtSvg
  Referenced from: /Applications/KeePassXC_dev.app/Contents/MacOS/KeePassXC
  Reason: Incompatible library version: KeePassXC requires version 5.12.0 or later, but QtSvg provides version 5.11.0

Binary Images:
       0x10cd4f000 -        0x10d0c8ff3 +org.keepassx.keepassxc (2.4.0-snapshot - ???) <BFE5E899-4CB3-39D2-8384-B09311213107> /Applications/KeePassXC_dev.app/Contents/MacOS/KeePassXC
       0x10d1ba000 -        0x10d1f5fe7 +libsodium.23.dylib (0) <815738CE-419B-3AC5-A63E-35AC0CBEA4FA> /Applications/KeePassXC_dev.app/Contents/Frameworks/libsodium.23.dylib
       0x11bcd2000 -        0x11bd50a67  dyld (640.2) <289AB27E-F09F-3384-A14A-100431139559> /usr/lib/dyld

Model: MacBookPro10,1, BootROM 251.0.0.0.0, 4 processors, Intel Core i7, 2,4 GHz, 16 GB, SMC 2.3f36
Graphics: Intel HD Graphics 4000, Intel HD Graphics 4000, Built-In
Graphics: NVIDIA GeForce GT 650M, NVIDIA GeForce GT 650M, PCIe
Memory Module: BANK 0/DIMM0, 8 GB, DDR3, 1600 MHz, 0x80AD, 0x484D5434314753364D465238432D50422020
Memory Module: BANK 1/DIMM0, 8 GB, DDR3, 1600 MHz, 0x80AD, 0x484D5434314753364D465238432D50422020
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0xEF), Broadcom BCM43xx 1.0 (7.21.190.32 AirPortDriverBrcm4360-1315.1)
Bluetooth: Version 6.0.9f2, 3 services, 18 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
Serial ATA Device: APPLE SSD SD256E, 251 GB
USB Device: USB 2.0 Bus
USB Device: Hub
USB Device: FaceTime HD Camera (Built-in)
USB Device: USB 2.0 Bus
USB Device: Hub
USB Device: Hub
USB Device: Apple Internal Keyboard / Trackpad
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
USB Device: USB 3.0 Bus
USB Device: Yubikey 4 OTP+U2F+CCID
Thunderbolt Bus: MacBook Pro, Apple Inc., 23.4
```
</details>

**Comment by droidmonkey** [comment] 2018-12-25 20:00
Oh well that's interesting. The update to Qt 5.12 left QtSvg behind. That's also what I get for not testing.

**Comment by woj-tek** [comment] 2018-12-27 01:41
Can't get the file - seems to be some problem with access to S3:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>80641DC2C88A4B2A</RequestId><HostId>…</HostId></Error>
```

**Comment by droidmonkey** [comment] 2018-12-27 03:08
Ugh I'm failing big time lately. Forgot that s3 resets permissions on upload. Fixed now!

**Comment by woj-tek** [comment] 2018-12-27 15:02
No worries - I appreciate all the effort.

I tested this version and it looks it's not crashing - I'll test some more and let it run for a couple of days and report back if something shows up. Thank you!

**Closed** 2019-07-10 03:12 UTC
Labels: not reproducible, platform: macOS
