### ISSUE TITLE
Incorrect password when Auto-Type in another keyboard layout

### ISSUE THREAD

**Issue by ZiguDa** [keepassxreboot/keepassxc#1973] opened 2018-05-17 11:37 UTC
When entering the password through AutoType, the layout is forcibly switched to the RU and an incorrect password is entered

## Current Behavior
Localization of Linux is russian and 2 layouts: English (US) and Russian(RU).
The password consists of ASCII characters.
When entering the password, the layout is forcibly switched to the RU and an incorrect password is entered

## Steps to Reproduce (for bugs)
The password consists only of ASCII characters.
1. layout is English (US)
2. Ctrl+Alt+A
3. layout is forcibly switched to the RU
4. password is incorrect 

## Debug Info
KeePassXC - Version 2.3.3
Revision: 0a155d8

Libraries:
- Qt 5.10.1
- libgcrypt 1.8.2

Operating system: Manjaro Linux
CPU architecture: x86_64
Kernel: linux 4.14.39-1-MANJARO

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by phoerious** [comment] 2018-05-17 16:03
Duplicate of #324 and #474.

**Closed by phoerious** 2018-05-17 16:03 UTC
Labels: duplicate
