### ISSUE TITLE
Importing CSV with modified or created dates does not work as expected

### ISSUE THREAD

**Issue by idontusenumbers** [keepassxreboot/keepassxc#4557] opened 2020-04-06 23:09 UTC
## Expected Behavior
Modified date is either loaded properly or import is blocked until format is provided/fixed

## Current Behavior
Replaces field value with current date

## Possible Solution
* Indicate the required format (apparently unix time stamp)
* Try to parse ISO, other formats (keychain applescript exports as YYYYMMDDHHmmSS)

## Steps to Reproduce
Import CSV with created column

## Context
I'm trying to import keychain passwords from MacOSX exported using https://github.com/lifepillar/CSVKeychain

## Debug Info
KeePassXC - Version 2.5.3
Revision: f8c962b

Qt 5.14.1
Debugging mode is disabled.

Operating system: macOS High Sierra (10.13)
CPU architecture: x86_64
Kernel: darwin 17.7.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by Gatheringofravens** [comment] 2020-06-27 10:51
The date import function is definitely a bit off and doesn't work as I expected. But I can confirm it will work with unix time (has to be without milliseconds) if the rows are in the correct order and don't need re-ordering via the dropdowns in the importer. Strangely when I reordered them (modified row to created and vice versa because picked up wrong) it didn't import correctly but something else may have been off. 

Suggest either providing better info about expected format in importer (unix time without milliseconds) or making importer more tolerant to unix time with milliseconds as well as ideally YYYYMMDDHHMMSS formats. In either case better documentation or info on the window about tolerated time formats would be helpful and that's part of the reason I'm leaving this comment.

**Comment by droidmonkey** [comment] 2020-09-27 16:24
Fixed in #5346

**Closed by droidmonkey** 2020-09-27 16:24 UTC
Labels: bug, import: CSV
