### ISSUE TITLE
Add reference to Username or Password by selecting other entry

### ISSUE THREAD

**Issue by Simpler1** [keepassxreboot/keepassxc#3373] opened 2019-07-12 18:06 UTC
## Summary
When using [KeePass 2.42.1](https://keepass.info/), there is a button at the bottom of the _Edit Entry_ dialog to create a reference to Password, Username, and other fields of another entry by selecting the other entry.  This is very useful.  

![image](https://user-images.githubusercontent.com/5922273/61148456-d5371d80-a4ac-11e9-8090-4931a4eacfd0.png)

## Desired Behavior
When editing an entry, it would be very useful to add this functionality to KeePassXC.

## Possible Solution
The implementation in KeePass (shown above) is reasonable and works quite nicely.

## Context
I realize that I can create references by cloning an entry, but sometimes I already have an entry that I want to link to another entry.  I don't want to create a new entry.  One example of this is when I create an entry for an app through my Android phone using Keepass2Android, but I already have a master entry in my database that is used for the web.  The two have different URLs, but the Username and Password should be links.  It is much easier to create the entry from the Android device and then edit the Username and Password fields to be references, than to clone an existing entry and try to figure out what the URL should be for the Android app.

I also realize that I can manually create the references, but this is much more painful than just clicking the existing entry.

I have also seen similar requests, but they don't specifically request the UI to add this when editing an entry:
[Feature: Add support for basic references in autotype #75](https://github.com/keepassxreboot/keepassxc/issues/75)
[Use username and pasword link (reference) to other entry. #166](https://github.com/keepassxreboot/keepassxc/issues/166)

**Comment by droidmonkey** [comment] 2019-07-13 00:22
Duplicate of #433

**Closed** 2020-08-03 22:21 UTC
Labels: new feature
