### ISSUE TITLE
"Require user confirmation when this key is used" causes SSH Agent signing failed

### ISSUE THREAD

**Issue by 64b2b6d12b** [keepassxreboot/keepassxc#1627] opened 2018-03-04 22:05 UTC
## Expected Behavior
When using SSH Agent and "Require user confirmation when this key is used" checkbox is checked, SSH Agent login should work and I'm assuming there should be some sort of confirmation

## Current Behavior
When using SSH Agent, and "Require user confirmation when this key is used" checkbox is checked, the following error is seen on the terminal `sign_and_send_pubkey: signing failed: agent refused operation`

## Possible Solution
Un-check "Require user confirmation when this key is used"

## Steps to Reproduce (for bugs)
1.  Add a new entry with SSH Agent
2. Check "Require user confirmation when this key is used"
3. Login to a server that utilises the key

## Context
Trying to use the new SSH Agent feature

## Debug Info
KeePassXC - Version 2.3.0
Revision: 4c0ed74

Libraries:
- Qt 5.9.3
- libgcrypt 1.8.2

Operating system: macOS High Sierra (10.13)
CPU architecture: x86_64
Kernel: darwin 17.4.0

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by hifi** [comment] 2018-03-05 05:43
Does user confirmation work when you add the key manually with `ssh-add -c` outside KeePassXC? Is they key actually on the agent when you list the loaded keys with `ssh-add -l`?

It's likely the issue is with OpenSSH and confirmation on macOS meaning OpenSSH doesn't have any "askpass" binary that can be launched.

**Comment by mannp** [comment] 2018-03-05 10:07
I get the same error on my macos install and the key is loaded for me, but I will need to check your other questions when I boot back into macos.

**Comment by yan12125** [comment] 2018-03-05 12:27
> It's likely the issue is with OpenSSH and confirmation on macOS meaning OpenSSH doesn't have any "askpass" binary that can be launched.

Yes that's the cause. I use https://github.com/theseal/ssh-askpass to provide the ASKPASS program on macOS. It works for almost everything (git, ssh, filezilla, and possibly more). Only sshfs does not work with that.

**Comment by 64b2b6d12b** [comment] 2018-03-05 23:37
The same problem was happening for me even by manully adding the key with `ssh-add -c` so it was not a KeePassXC issue. The issue was resolved for me after installing [https://github.com/theseal/ssh-askpass](https://github.com/theseal/ssh-askpass) as per @yan12125, however, I had to follow the manual install process of;

```
$ sudo cp ssh-askpass /usr/local/bin/
$ cp ssh-askpass.plist ~/Library/LaunchAgents/
```
The homebrew method did not resolve the issue.

**Comment by sven-weber** [comment] 2018-08-13 18:38
Hi, 
I encountered the same issue and it took me quite some time to find the cause. 

Maybe we should add a check for the askpass installation or at least show some kind of information pop-up that askpass is required for this feature in order to work properly. 

This may prevent people in the future from taking hours to troubleshoot this issue. 

Thanks and regards

**Comment by thePanz** [comment] 2019-01-10 08:57
The same happens on my Linux (Arch+KDE) setup.
The key is correctly registered, and I can use it when the checkbox is empty. When enabling the `Require user confirmation when this key is used` looks like the key can not be used anymore

**Comment by cl0ne** [comment] 2019-01-25 17:15
Confirm the issue on Arch Linux with KDE with `SSH_ASKPASS` set to `/usr/bin/ksshaskpass`, but it works with `x11-ssh-askpass` or when `ksshaskpass` executable is symlinked to `/usr/lib/ssh/ssh-askpass`

**Comment by pablomenino** [comment] 2019-02-08 22:22
I Confirm the issue on Fedora 29 on Gnome with SSH_ASKPASS set to /usr/lib/ssh/ssh-askpass.

KeepassXC Version: 2.3.4

**Comment by thePanz** [comment] 2019-02-14 11:35
@cl0ne so the solution is to define `SSH_ASKPASS=/usr/bin/ksshaskpass` ?

**Comment by cl0ne** [comment] 2019-02-14 17:50
> @cl0ne so the solution is to define `SSH_ASKPASS=/usr/bin/ksshaskpass` ?

Confirmation with ksshaskpass works only when I symlink `ksshaskpass` executable to `/usr/lib/ssh/ssh-askpass`.

**Comment by cl0ne** [comment] 2019-02-14 17:53
> Also after checking/unchecking the checkbox we have to lock-unlock database (or restart keepassxc)

Actually, I overlooked buttons "Add to agent" and "Remove from agent" as a faster way to apply changes in key settings.

**Comment by TechupBusiness** [comment] 2019-11-08 14:28
This is still an issue on ubuntu. The solution on Ubuntu 18.04 was to disable the keyring and use the default ssh-agent.
Follow this instructions: https://bugs.launchpad.net/ubuntu/+source/openssh/+bug/1812247/comments/12
To get the linked solution to work, I needed to change one line in `~/.config/autostart/ssh-agent.desktop`:
```
Exec=/usr/bin/ssh-agent -a /run/user/1000/keyring/ssh
```
Now it's asking every time (when keepassxc is unlocked):
![image](https://user-images.githubusercontent.com/38460054/68483726-5bd1f080-023c-11ea-902e-ea11dc674f64.png)

**Comment by nycex** [comment] 2019-11-16 16:20
This issue still happens to me on Arch Linux, when I use sway.

**Comment by hifi** [comment] 2019-11-16 18:39
Ok, I'm going to close this as an upstream issue. If you keep having this on a stock distribution with their stock desktop environment, file a bug in their system to fix their implementation `SSH_ASKPASS`.

Thanks everyone.

**Closed by hifi** 2019-11-16 18:39 UTC
Labels: plugin: SSH agent, upstream

**Comment by WillyJL** [comment] 2025-07-06 04:13
Sharing here what I did to workaround the issue since it's all over the place. I am on Arch Linux, KDE, Wayland, using ksshaskpass.

The core issue is that `ssh-agent` is started without the `DISPLAY` and `SSH_ASKPASS` environment variables.

I installed this system around January 2025, so things may change later on, keep that in mind if following along.
In my case, KDE was spawning `ssh-agent` via `~/.config/plasma-workspace/env/ssh-agent.sh` (I did not create this, not sure if KDE did or Arch).
Still, even though this is the intended way to spawn processes in the desktop environment at startup and thus is supposed to have `DISPLAY` set, it does not (I believe it's the same issue as this [KDE bug report](https://bugs.kde.org/show_bug.cgi?id=469839)). Also, `SSH_ASKPASS` was not set anywhere either.
There is also the `ssh-agent.service` systemd service, since that is started with systemd and not related to the desktop environment that never had any chance of having `DISPLAY` set.

What fixed it for me:
- Disable the systemd service: `systemctl --user disable ssh-agent`
- Check what your usual desktop session's `DISPLAY` variable is: `echo $DISPLAY`, in my case `:1`
- Edit the `~/.config/plasma-workspace/env/ssh-agent.sh` script (adjust the `DISPLAY` variable):
  ```bash
  #!/bin/bash
  
  export SSH_ASKPASS=/usr/bin/ksshaskpass
  eval "$(DISPLAY=:1 ssh-agent -s)"
  ```

- Make sure there is nothing else starting `ssh-agent` or messing with the `SSH_AUTH_SOCK` environment variable, for example double check `~/.profile` (apparently this is not even executed anymore in recent versions?), `/etc/profile`, `/etc/profile.d`, `/etc/environment`
