### ISSUE TITLE
Clicking "abort" on the "Unsaved changes" Dialog causes dataloss

### ISSUE THREAD

**Issue by thomasfrobieter** [keepassxreboot/keepassxc#11000] opened 2024-06-28 19:13 UTC
## Overview
When KeepassXC is open with unsaved changes and the OS (Fedora) the screen is locked (or anything else triggers a Database close), a warning dialog appears (translated from German):
"You are editing an entry, do you really want to discard changes and lock?"
a) "Close without saving"
b) "cancel"

Clicking "cancel" immediatly locks the database. Affter unlocking, the changes are gone forever.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Open a database entry, change the password without saving
2. Lock the OS
3. Unlock the OS
4. See the warning message on Keepass
5. Click cancel
6. => Changes gone, old Password

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

## Context
[NOTE]: # ( Give us any additional information you may have. )

KeePassXC - Version 2.7.8
Revision: f6757d3

Qt 5.15.13
Diagnosemodus ist deaktiviert.

Betriebssystem: Fedora Linux 39 (Workstation Edition)
CPU-Architektur: x86_64
Kernel: linux 6.8.8-1.surface.fc39.x86_64

Aktivierte Erweiterungen:
- Auto-Type
- Browser-Integration
- Passkeys
- SSH-Agent
- KeeShare
- YubiKey
- Secret-Service-Integration

Kryptographische Bibliotheken:
- Botan 2.19.3

Operating System: Linux
Desktop Env: Gnome
Windowing System: Wayland

**Comment by droidmonkey** [comment] 2024-06-28 22:33
I cannot replicate this


https://github.com/keepassxreboot/keepassxc/assets/2809491/bea08a22-8dc2-4837-af11-a7afe2850369

**Comment by thomasfrobieter** [comment] 2024-06-29 06:35
Tried it multiple times with the same result. I will try to capture a video
later!

Jonathan White ***@***.***> schrieb am Sa., 29. Juni 2024,
00:34:

**Comment by fibsifan** [comment] 2024-07-03 12:31
I just experienced the same issue on Ubuntu 22.04 within a Virtualbox VM with a new entry which doesn't get saved when clicking cancel.

**Comment by droidmonkey** [comment] 2024-07-03 12:35
Hmmm, this must be a Linux thing then

**Comment by fibsifan** [comment] 2024-07-03 12:40
Here's a screen recording (version 2.7.9 from the phoerius/keepassxc launchpad repo):

[keepass.webm](https://github.com/keepassxreboot/keepassxc/assets/574988/a8601b06-62b3-4c5c-ac14-308fdc2bda52)

**Comment by hector-romero** [comment] 2024-07-19 22:06
I just experienced the same issue on MacOS Sonoma. It started happening after one of the latest updates. I'm currently on 2.7.9 and it happened a couple of times already, but I'm not sure when it started, although I know it used to work fine not long ago.

**Comment by vdng9338** [comment] 2024-09-21 07:00
I just experienced this issue as well on Ubuntu 24.04 with KeePassXC 2.7.9 from the phoerius/keepassxc Launchpad repo. I lost a backup passphrase because of that :/ (but did not lose anything too important, fortunately)

**Comment by fibsifan** [comment] 2024-09-28 09:41
@droidmonkey what is needed to get rid of the "not reproducible" label?

What else can be done to support analysis of the issue?

**Comment by fibsifan** [comment] 2024-09-28 10:08
I found out some strange behaviour while trying to reproduce this issue on Ubuntu 24.04 (wayland, ubuntu-session), KeePassXC 2.7.9 from the phoerius/keepassxc Launchpad repo. Keepass is set to lock the database when the session is locked or the laptop lid is closed.

**Working use cases**:
* Open KeepassXC, unlock database. Then lock the screen by entering win+l (thats lowercase L) and unlock the screen. -> DB is locked ✔️
* Open KeepassXC, unlock database. Then lock the screen by clicking lock the screen in the top right menu and unlock the screen. -> DB is locked ✔️
* Open KeepassXC, unlock database. Then close the laptop lid and wait for the pc to go into standby, open it again and unlock the screen. -> DB is locked ✔️

**Broken use cases**:
* Open KeePassXC, unlock database and open a (new or existing) entry for editing. Then lock the screen by entering win+l (thats lowercase L) and unlock the screen. -> DB is not locked and still shows the entry for edit (no data loss) ❌
    * Edit: on trying again I observed: in most cases the screen and DB actually properly lock and we have **data loss** ❌❌
* Open KeePassXC, unlock database and open a (new or existing) entry for editing. Then lock the screen by clicking lock the screen in the top right menu  and unlock the screen. -> DB is not locked and still shows the entry for edit (no data loss) ❌
    * Edit: on trying again I observed: in most cases the screen and DB actually properly lock and we have **data loss** ❌❌
* Open KeePassXC, unlock database and open a (new or existing) entry for editing. Then close the laptop lid and wait for the pc to go into standby, open it again and unlock the screen. -> DB is not locked and the dialogue from the original issue description appears. Only response options: cancel or close without saving = **data loss**  ❌❌

**Expected behaviour**:
I think this is tricky:
* If saving the open entry would be allowed, that would be allowing modification of the database while it is actually locked. I don't know about the technical perspective, but that sounds logically wrong.
* I personally would like the dialogue to not appear and the database simply being locked. when I unlock it again, I would like to be able to continue my _draft_ of modifying or creating the entry.

**Comment by droidmonkey** [comment] 2024-09-28 12:01
OK I reproduced the behavior, debugging

**Comment by droidmonkey** [comment] 2024-09-28 12:49
OK figured it out, this is going to take some thinking...

When the screen locks on gnome we receive multiple independent signals of that, namely the Gnome session manager and the gnome/freedesktop screensaver.

When this happens, this causes multiple "lock database" requests to be issued. The first one correctly shows the question to discard/cancel, but the second one _while the first is still asking_ goes and dismisses the question and then goes to ask it again. The result is it acts like you didn't answer correctly (ie, to cancel) and the database is locked.

Relevant code:

https://github.com/keepassxreboot/keepassxc/blob/c1a66a8be98d8f3a7ea1ba0ca6065c2d1a10e56b/src/gui/osutils/nixutils/ScreenLockListenerDBus.cpp#L105-L129

https://github.com/keepassxreboot/keepassxc/blob/c1a66a8be98d8f3a7ea1ba0ca6065c2d1a10e56b/src/gui/DatabaseWidget.cpp#L1957-L1967

https://github.com/keepassxreboot/keepassxc/blob/c1a66a8be98d8f3a7ea1ba0ca6065c2d1a10e56b/src/gui/DatabaseWidget.cpp#L1971-L1980

I think an easy fix for this is to "ignore" repeated lock attempts while one is already in process.

**Comment by droidmonkey** [comment] 2024-09-28 13:04
Fix posted for merge

**Closed as completed** 2024-10-07 03:22 UTC
Labels: high priority :rotating_light:, platform: Linux
