### ISSUE TITLE
merge to database (additional to the merge from database)

### ISSUE THREAD

**Issue by aisbergde** [keepassxreboot/keepassxc#4450] opened 2020-03-19 08:52 UTC
if you don't want / can implement a two-way-merge then please at least implement a "merge to database" additional to the existing "merge from database"

I use keepass / keepassxc on different devices. The suggested way to hope that the cloud syncing software can be used doesn't work, if changes are done in the same time on different devices. It is hard and complicated to solve conflicts.

The only solution, I found, is:
After doing some changes in an keepass_xc-database I open keepass with a second keepass-database and I use keepass to sync the tow databases. The keepass-database can be shared in the cloud and can be used on other devices.
 
But this is a little bit strange to use keepassXC as main program and to use keepass only for sync. Then I could also use only keepass at all instead of keepassXC.

If you will implement a "merge to database" I could avoid to open keepass for sync: I could do all what I need only with keepassXC

## Desired Behavior
it should be possible to merge changes from the existing database into a second database. And if the second database has the same security (master password, ...) no additional request should be done.

Much better of course would be if you implement a bi directional merge (= sync) like in keepass.

**Comment by droidmonkey** [comment] 2020-03-19 12:30
This is a duplicate of bidirectional sync request

**Closed** 2020-03-19 12:31 UTC
Labels: new feature
