### ISSUE TITLE
New ways to handle userdefined symbols & icons

### ISSUE THREAD

**Issue by RolandSM** [keepassxreboot/keepassxc#3806] opened 2019-11-06 05:41 UTC
During last years many many icons gets collected.
Sometimes also duplicate ones.

A new button which search icons not in use from an entry can be deleted.

Also a possibility if I get the Info, that this button is used from one or more entries, that I can go to the filtered view of these entries and I can set a single one.

**Comment by droidmonkey** [comment] 2019-11-06 11:31
Duplicate of #2110

**Closed by droidmonkey** 2019-11-06 11:31 UTC
Labels: new feature
