### ISSUE TITLE
Master Password getting reset suddenly while entering on unlock screen

### ISSUE THREAD

**Issue by RohitSurwase** [keepassxreboot/keepassxc#10702] opened 2024-05-08 04:06 UTC
## Overview
The password field gets reset/cleared while entering the master password using Virtual keyboard on macOS.

## Steps to Reproduce
Open KeepassXC app and start entering your master password to unlock your DB. I use Software keyboard available on MacOS to enter my password. After entering few characters (15 or more), the entered password gets reset automatically. And I have to start entering the password again from the start. Second time it works as expected.

## Expected Behavior
The password field should not reset/clear while entering the master password to unlock your DB on KeepassXC.

## Actual Behavior
The password field gets reset/cleared while entering the master password.

## Context
I use Software keyboard available on MacOS to enter my password. I have not tried physical keyboard.

[NOTE]: 
KeePassXC - Version 2.7.8
Revision: f6757d3

Qt 5.15.11
Debugging mode is disabled.

Operating system: macOS 14.3
CPU architecture: arm64
Kernel: darwin 23.3.0

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 3.1.1

[NOTE]: 
Operating System: macOS Apple M1 Pro with Sonoma 14.3.1

**Comment by phoerious** [comment] 2024-05-08 06:05
Duplicate of #10695.

**Closed as not planned** 2024-05-08 06:05 UTC
Labels: duplicate
