### ISSUE TITLE
Yubikey not detected if Slot 1 is empty / not configured 

### ISSUE THREAD

**Issue by hunterbr72** [keepassxreboot/keepassxc#5268] opened 2020-08-14 06:49 UTC
## Overview
KeepassXC doesn't detect a Yubikey if the first slot of the Yubikey is not configured on Windows 10.
I have only configured the 2nd slot for OTP/Challenge-response. It worked fine with Keepass 2.5.4.
Once the first slot is configure, the Yubi key and both slots are detected and working.

## Steps to Reproduce
Use YubiKey Manager to delete configuration on slot 1

## Expected Behavior
Detect Yubikey also if slot 1 is empty.

Operating System: Windows 10 Enterprise Built 2004
KeepassXC Ver. 2.6
Yubikey 5c Nano Firmware 5.1.2

**Comment by iwismer** [comment] 2020-08-14 07:42
I think this is a duplicate of #4987 which was fixed in #5004

**Comment by hunterbr72** [comment] 2020-08-14 09:13
yup, thx for the quick answer !

**Closed** 2020-08-14 10:35 UTC
Labels: bug
