### ISSUE TITLE
keepass does not start after update MacOS 10.5.4

### ISSUE THREAD

**Issue by matthias-zivim** [keepassxreboot/keepassxc#4469] opened 2020-03-24 18:21 UTC
After update from 10.5.3 -> 10.5.4 -> no function

## Debug Info
KeePassXC - 2.5.3

`Process:               KeePassXC [1079]
Path:                  /Applications/KeePassXC.app/Contents/MacOS/KeePassXC
Identifier:            org.keepassx.keepassxc
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           KeePassXC [1079]
User ID:               501

Date/Time:             2020-03-24 19:31:27.223 +0100
OS Version:            Mac OS X 10.15.4 (19E266)
Report Version:        12
Bridge OS Version:     4.4 (17P4263)

Time Awake Since Boot: 890 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (Code Signature Invalid)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace CODESIGNING, Code 0x1

kernel messages:

VM Regions Near 0 (cr2):
--> 
    __TEXT                 0000000109157000-00000001094e9000 [ 3656K] r-x/r-x SM=COW  

Thread 0 Crashed:
0                                	0x000000010b0d6000 _dyld_start + 0

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x0000000000000000  rcx: 0x0000000000000000  rdx: 0x0000000000000000
  rdi: 0x0000000000000000  rsi: 0x0000000000000000  rbp: 0x0000000000000000  rsp: 0x00007ffee6aa8c58
   r8: 0x0000000000000000   r9: 0x0000000000000000  r10: 0x0000000000000000  r11: 0x0000000000000000
  r12: 0x0000000000000000  r13: 0x0000000000000000  r14: 0x0000000000000000  r15: 0x0000000000000000
  rip: 0x000000010b0d6000  rfl: 0x0000000000000200  cr2: 0x0000000000000000
  
Logical CPU:     0
Error Code:      0x00000000
Trap Number:     0

Binary Images:
       0x109157000 -        0x1094e8fff + (0) <16AE8CED-0E4C-3291-AE43-913B0D7192FF> 
       0x10b0d5000 -        0x10b166eff + (750.5) <1F893B81-89A5-3502-8510-95B97B9F730D> 

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 807
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=4776K resident=0K(0%) swapped_out_or_unallocated=4776K(100%)
Writable regions: Total=8408K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=8408K(100%)
 
                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
STACK GUARD                       56.0M        1 
Stack                             8192K        1 
__DATA                             360K        4 
__DATA_CONST                        20K        1 
__LINKEDIT                         536K        2 
__TEXT                            4240K        2 
shared memory                        8K        2 
===========                     =======  ======= 
TOTAL                             69.0M       13 

Model: MacBookPro15,1, BootROM 1037.100.359.0.0 (iBridge: 17.16.14263.0.0,0), 8 processors, 8-Core Intel Core i9, 2,3 GHz, 16 GB, SMC 
`

**Comment by rogerclermont** [comment] 2020-03-24 18:54
Similar situation here.  Running KeepassXC v2.5.3.

===========================================================

Process:               KeePassXC [1827]
Path:                  /Applications/KeePassXC.app/Contents/MacOS/KeePassXC
Identifier:            org.keepassx.keepassxc
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           KeePassXC [1827]
User ID:               501

Date/Time:             2020-03-24 11:50:05.758 -0700
OS Version:            Mac OS X 10.15.4 (19E266)
Report Version:        12
Anonymous UUID:        5CDB969E-2287-074A-9C53-3A5199082935


Time Awake Since Boot: 1800 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (Code Signature Invalid)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace CODESIGNING, Code 0x1

kernel messages:

VM Regions Near 0 (cr2):
--> 
    __TEXT                 000000010cb13000-000000010cea5000 [ 3656K] r-x/r-x SM=COW  

Thread 0 Crashed:
0   ???                           	0x000000011a2f9000 _dyld_start + 0

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x0000000000000000  rcx: 0x0000000000000000  rdx: 0x0000000000000000
  rdi: 0x0000000000000000  rsi: 0x0000000000000000  rbp: 0x0000000000000000  rsp: 0x00007ffee30ecc48
   r8: 0x0000000000000000   r9: 0x0000000000000000  r10: 0x0000000000000000  r11: 0x0000000000000000
  r12: 0x0000000000000000  r13: 0x0000000000000000  r14: 0x0000000000000000  r15: 0x0000000000000000
  rip: 0x000000011a2f9000  rfl: 0x0000000000000200  cr2: 0x0000000000000000
  
Logical CPU:     0
Error Code:      0x00000000
Trap Number:     0


Binary Images:
       0x10cb13000 -        0x10cea4fff +??? (0) <16AE8CED-0E4C-3291-AE43-913B0D7192FF> (null)
       0x11a2f8000 -        0x11a389eff +??? (750.5) <1F893B81-89A5-3502-8510-95B97B9F730D> (null)

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 93458
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=4776K resident=0K(0%) swapped_out_or_unallocated=4776K(100%)
Writable regions: Total=8408K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=8408K(100%)
 
                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
STACK GUARD                       56.0M        1 
Stack                             8192K        1 
__DATA                             360K        4 
__DATA_CONST                        20K        1 
__LINKEDIT                         536K        2 
__TEXT                            4240K        2 
shared memory                        8K        2 
===========                     =======  ======= 
TOTAL                             69.0M       13 

Model: MacBookAir6,1, BootROM 120.0.0.0.0, 2 processors, Dual-Core Intel Core i7, 1.7 GHz, 8 GB, SMC 2.12f143

**Comment by jasonbeitler** [comment] 2020-03-24 19:12
Seems to be a duplicate of https://github.com/keepassxreboot/keepassxc/issues/4398

**Comment by jjdmon** [comment] 2020-03-24 19:54
Same problem on OS 10.14.6 after a security update.  It broke code signing for the app and apparently every framework and library with it.  I downloaded the latest snapshot build for 2.6.0 and that works.

**Comment by dpbaker57** [comment] 2020-03-24 20:02
I downloaded and was able to run the latest 2.6.0 snapshot. That's good but now I can't stop worrying that this pre-release version will trash my vault data. Any chance of a 2.5.4 using a correct code validation?

**Comment by droidmonkey** [comment] 2020-03-24 20:04
Ping @phoerious we need to figure this out.

**Comment by droidmonkey** [comment] 2020-03-24 20:23
This might be relevant: https://developer.apple.com/library/archive/qa/qa1884/_index.html#//apple_ref/doc/uid/DTS40015141

**Comment by andycu2015** [comment] 2020-03-24 20:30
I downloaded the latest 2.6.0.dmg from https://snapshot.keepassxc.org/latest/. Installed it and when I started it up, I got the below message 

“KeePassXC” cannot be opened because the developer cannot be verified. macOS cannot verify that this app is free from malware."

I got only two buttons, Move to Trash and Cancel so I can't open KeePassXC.  

What am I doing wrong please? I just updated macOS to 10.15.4 today

**Comment by dpbaker57** [comment] 2020-03-24 21:41
@andycu2015 You need to go into the systems preferences -> Security & Privacy -> General there you will be able to grant it the right to execute.

**Comment by andycu2015** [comment] 2020-03-24 21:52
> @andycu2015 You need to go into the systems preferences -> Security & Privacy -> General there you will be able to grant it the right to execute.

Thanks. I thought macOS kept setting. I googled and found out so it's working now.

**Comment by phoerious** [comment] 2020-03-24 22:08
Duplicate of #4398

**Closed by phoerious** 2020-03-24 22:08 UTC
Labels: duplicate
