### ISSUE TITLE
Non closable window of keepassxc when using firefox plugin

### ISSUE THREAD

**Issue by KlaR-o** [keepassxreboot/keepassxc#6406] opened 2021-04-14 09:12 UTC
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
when clicking to the add-on symbol the message appears that there is no connection to the database.
Measure: Add-on disabled

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. open firefox with activated plugin
2. unlock database
3. minimize or close

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
keepassxc windows should be minimized with respect to the settings

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
the windows keeps staying in foreground

## Context
[NOTE]: # ( Give us any additional information you may have. )
issue didn't appear yesterday, 13th April 2021 

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.4
Revision: 34a78f0
Distribution: Flatpak

Qt 5.15.3
Diagnosemodus ist deaktiviert.

Betriebssystem: KDE Flatpak runtime
CPU-Architektur: x86_64
Kernel: linux 4.19.0-16-amd64

Aktivierte Erweiterungen:
- Auto-Type
- Browser-Integration
- SSH-Agent 
- KeeShare (bestätigtes und unbestätigtes Teilen)
- YubiKey 

Kryptographische Bibliotheken:
- libgcrypt 1.8.7

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows/Linux/macOS
Desktop Env: Gnome/KDE/XFCE/Mate/Cinnamon
Windowing System: X11/Wayland

**Comment by droidmonkey** [comment] 2021-04-14 10:17
I am not clear what the problem is. Please rephrase it.

**Comment by KlaR-o** [comment] 2021-04-14 11:22
Normally when I first start Firefox the KeePassXC window opens and asked for a password. After this the window will be minimized and the Firefox add-on indicated a connection to the database. 
But since today (not sure it could be yesterday) the following happens:
After opening the database the window of KeePassXC will not close and the icon of the add-on in Firefox indicates a fault connection to the database. So it is not possible to perform any different action in Firefox, because the KeePassCX windows almost appears in front. (Okay, one can move it to the bottom of the screen... I prefered to disable the add-on and insert user and password manually.

This is first time I report to an issue. I apologize for circumstancial behaviour.

**Comment by droidmonkey** [comment] 2021-04-14 12:37
Can you try to use our AppImage instead of the FlatPak? We have heard of odd behavior with browsers and FlatPak before. We technically don't maintain the FlatPak distribution.

**Comment by KlaR-o** [comment] 2021-04-14 14:18
Sorry, for my distribution LMDE4 (Debian) there is only version 2.3.4. The avialibillty of 2.6.4 only as flatpak was the reason to perform this.
Actualy I'm not able to connect the database to the browser add-on. May be the problem is here. 
Will try later and report.

**Comment by droidmonkey** [comment] 2021-04-14 14:19
Download the appimage from our downloads page: https://keepassxc.org/download

**Comment by KlaR-o** [comment] 2021-04-14 14:33
First had to get familiar with appimages - simple. Done.
Not possible to connect add-on with database after I have removed the trusted ID. 
Will try in some hours again an report

**Comment by KlaR-o** [comment] 2021-04-14 15:47
Now it seems to work.
I've removed and reinstalled the add-on. After this the open database could be acknowledged and a new connection keys was generated. No idea, wheather the formerly installed flatpak would run also, but I intend to let it as is is.

**Comment by droidmonkey** [comment] 2021-04-14 16:01
Ok great, closing this then

**Closed by droidmonkey** 2021-04-14 16:01 UTC
Labels: distribution: flatpak, more info needed
