### ISSUE TITLE
CLI can't add entry with the same title

### ISSUE THREAD

**Issue by yur1xpp** [keepassxreboot/keepassxc#4790] opened 2020-05-29 07:55 UTC
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
keepassxc-cli couldn't create new entry when existing entries with the same title exist.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. `keepassxc-cli add D:/db.kdbx eMail/Gmail -u test -g`

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Entry titled "Gmail" is added into database.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Instead, error thrown: `Could not create entry with path eMail/Gmail.`

## Context
[NOTE]: # ( Give us any additional information you may have. )
I have many entries inside the "eMail" group that titled "Gmail", this caused the cli failed to add new entry. For diagnosing, try this for twice: `keepassxc-cli add D:/db.kbdx eMail/GmailTest -u test -g`. First try will successfully adds the entry, second try will fails.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.5.4
Revision: c023bf9

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10 1909

**Comment by droidmonkey** [comment] 2020-05-29 14:02
Duplicate of #3720

**Closed by droidmonkey** 2020-05-29 14:02 UTC
Labels: bug
