### ISSUE TITLE
Incessant nagging to destroy KeePassHttp rules

### ISSUE THREAD

**Issue by solikeumyeah** [keepassxreboot/keepassxc#3346] opened 2019-07-01 06:09 UTC
KeePassXC 2.4.3 displays this dialog each time the database is unlocked:
![image](https://user-images.githubusercontent.com/9821269/60413328-e31cb100-9c17-11e9-8ff0-d67c8b476373.png)
I have a mixed environment where I often use KeePass 2.x and other KeePass apps, and I don't want to destroy these settings. I am happy for each KeePass app to maintain its own browser ACLs.

## Expected Behavior
- I want to be able to say "No and don't ask me again".
- This message should warn you it will destroy KeePassHTTP settings, for users who share their database with other KeePass apps.

## Current Behavior
I am given the same prompt at every unlock.

## Possible Solution
Add a "Never" button to the dialog, or only ever ask once by storing a variable in the database which says the import has been done.

## Steps to Reproduce
1. Add a custom attribute to an entry: 
Name: `KeePassHttp Settings` 
Content:  `{"Allow":["example.com"],"Deny":[]}`
2. Lock then unlock the database.

## Context
Having to click _No_ at every unlock annoying. 
A couple of times I have clicked yes without fully understanding what this does, and had to rebuild my KeePassHttp ACLs from scratch for use with other KeePass apps.

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.4.3
Revision: 5d6ef0c

Qt 5.12.3
Debugging mode is disabled.

Operating system: macOS Mojave (10.14)
CPU architecture: x86_64
Kernel: darwin 18.5.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.4

**Comment by varjolintu** [comment] 2019-07-01 10:34
Duplicate of https://github.com/keepassxreboot/keepassxc/issues/3327.

**Closed by varjolintu** 2019-07-01 10:34 UTC
Labels: bug, duplicate

**Comment by droidmonkey** [comment] 2019-07-01 11:22
Actually I think your PR to fix 3327 should also include a checkbox in the conversion request to not ask again. The http settings can live side by side with custom data settings.

**Comment by solikeumyeah** [comment] 2019-07-02 05:09
> Actually I think your PR to fix 3327 should also include a checkbox in the conversion request to not ask again. The http settings can live side by side with custom data settings.

That would be useful. The fix for #3327 is "Prompt to migrate KeePassHTTP settings only if Browser Integration is enabled". My use case is different, as I do use KeePassXC's browser integration.

**Comment by varjolintu** [comment] 2019-07-02 05:22
I'll do the checkbox feature.

**Comment by phoerious** [comment] 2019-07-02 05:57
You do know that you can use KeePassXC in Windows as well, right? I cannot recommend using the old KeePassHTTP extensions. Besides the fact that they can be communicated with from every account on your system, they also lack some essential protections against in-browser password theft.

**Comment by mendhak** [comment] 2019-09-03 21:31
Please can this be reopened - the fix for #3327 didn't include a checkbox.

Like OP we're also in a mixed environment of KeePassXC and KeePass2 so it would be useful to allow the old `KeePassHttp Settings' to remain by user choice.
