### ISSUE TITLE
keepassxc-cli show gives reference string not value

### ISSUE THREAD

**Issue by cyphar** [keepassxreboot/keepassxc#1260] opened 2017-12-08 14:02 UTC
I use references quite heavily to handle the lack of multi-URL handling in KeePassXC, and I wanted to use `keepassxc-cli` in order to auto-fill my `mutt` configuration. But I found that if I try to use `keepassxc-cli show` on an entry that uses references, the referenced value isn't returned.

## Expected Behavior
```
% keepassxc-cli show database.kdbx Some/Value
hunter2
```

## Current Behavior
```
% keepassxc-cli show database.kdbx Some/Value
{REF:P@I:9C9CC754C5729833FA2322EF921EDD0D}
```

## Possible Solution
Resolve references recursively when fetching them with `keepassxc-cli`.

## Debug Info
KeePassXC - Version 2.2.2
Revision: 6d46717

Libraries:
- Qt 5.9.2
- libgcrypt 1.8.1

Operating system: openSUSE Tumbleweed
CPU architecture: x86_64
Kernel: linux 4.14.3-1-default

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

**Comment by Generator** [comment] 2017-12-09 16:00
The same happens with Auto-Type
![screenshot-2017-12-9 http basic auth demo](https://user-images.githubusercontent.com/44146/33797058-f2c88406-dcf8-11e7-9618-beb36890e6ab.png)

## Steps to reproduce 

- Create a new entry (e.g. [HTTP Basic Auth Demo](https://auth-demo.aerobatic.io/protected-custom/))
- Clone the new entry with "Replace username and password with references"
- Go to the entry website and perform Auto-Type

## Debug Info
KeePassXC - Version 2.2.2
Revision: feba525

Libraries:
- Qt 5.9.3
- libgcrypt 1.8.1

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 4.14.4-pf

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey
- SSH Agent

## Notes
Browser extension works without issue, only Auto-Type types the reference instead of username/password

**Comment by cyphar** [comment] 2017-12-09 19:47
I've also noticed that the KeePassHTTP integration similarly only provides the ID in the "confirmation prompt" rather than the real username (the actually auto-filled value is correct though).

**Comment by chuinul** [comment] 2017-12-14 12:50
@Generator I cannot reproduce using 2.2.4. Provided the original entry still exists, Auto-Type does auto-fill with the real username and password. Is there any other condition to reproduce?

For the same version, I confirm that `keepassxc-cli` does not resolve the reference.

**Comment by Generator** [comment] 2017-12-14 13:19
@chuinul Looks to be fixed in 4723f66 (2.2.4)

**Comment by chuinul** [comment] 2017-12-14 13:22
Ok, good news then. That leaves us with only one problem ;-)

**Comment by chuinul** [comment] 2017-12-14 21:40
Well, obviously it is not so easy. Bin compiled from https://github.com/keepassxreboot/keepassxc/commit/4723f66d23db95f8318f04ee3aeae448d2305c9c actually behaves as expected. But when I compile from `develop` (https://github.com/keepassxreboot/keepassxc/commit/57845851c01ce16198ac619bd0f0ff42fa2add1e), auto-type window shows only the original entry. I will look at that tomorrow.

Anyway, the two bugs mentioned seem unrelated. I will open a new issue for the auto-type one if it is really something that has to be fixed in `develop`.

**Comment by TheZ3ro** [comment] 2017-12-14 21:57
This https://github.com/keepassxreboot/keepassxc/commit/4723f66d23db95f8318f04ee3aeae448d2305c9c it backported in develop so there shouldn't be any difference

**Comment by chuinul** [comment] 2017-12-15 06:21
Well, I mean not those specific commits but the points from where I compiled the two branches. There are many things in `develop` that are not yet merged in `master`.

**Comment by chuinul** [comment] 2017-12-15 08:48
OK, let's forget that. https://github.com/keepassxreboot/keepassxc/pull/1280/commits/c12d8fbcddf75292511fdd9d02f19225612ac23a will solve the issue and both entries will be displayed again when autotyping.

**Closed** 2017-12-17 15:44 UTC
Labels: cli
