### ISSUE TITLE
KeePassXC 2.5.1 return all credentials for same domain instead of best matching credentials

### ISSUE THREAD

**Issue by HongmouZhang** [keepassxreboot/keepassxc#3903] opened 2019-11-20 12:39 UTC
I have updated to 2.5.1, however, keepassxc-browser lists all credentials for same domain even though the best matching one is there, and I have checked "Return only best-matching credentials" in KeepassXC application settings-> Browser integration-> general. But it doesn't help.

After that, I download 2.5.0 portable version again, and copy the file keepassxc.ini from 2.5.1 folder to 2.5.0 folder, I think that means the configuration for two versions is identical now. Then I run 2.5.0 without any further configuration, everything is fine for 2.5.0.

## Expected Behavior
If the best matching credentials are there, keepassxc-browser only lists the best matching results.

## Current Behavior
keepassxc-browser lists all credentials for the same domain.

## Debug Info
KeePassXC-Browser Version: 1.5.3

KeePassXC - Version 2.5.1
Revision: 0fd8836
Qt 5.13.1
Debugging mode is disabled.

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.17763

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by varjolintu** [comment] 2019-11-20 14:48
Duplicate of #3848.

**Closed by varjolintu** 2019-11-20 14:48 UTC
Labels: bug
