### ISSUE TITLE
KeepassXC crashes, when open with editor without focus on Mac

### ISSUE THREAD

**Issue by kschmid** [keepassxreboot/keepassxc#9228] opened 2023-03-11 14:20 UTC
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
I have the repeated behavior with KeePassXC that, if I create a new entry, fill it in, leave the editor open and switch to doing s.th. else in the foreground, KeePassXC crashes (loosing the info in the editor). 

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Open KeePassXC
2. click "+" button on KeePassXC window
3. fill in information for entry, but do not click "ok" or cancel
4. Continue working in the foreground, e.g., webbrowser.
5. After random time, KeePassXC crashes, loosing editor content. Mac wants to send a crash report.
    I happened several times, within a few minutes of open window, but apparently, behavior is not fully repeatable, will add more information, if I can identify this.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Nothing (the editor window should stay open until I get back to it.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
KeePassXC crashes, loosing content of the editor. 

## Context
[NOTE]: # ( Give us any additional information you may have. )
MacOS Monterey 12.6.3, MacBook Pro, intel
KeePassXC is installed and updated via brew in the application directory.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.4
Revision: 63b2394

Qt 5.15.6
Debugging mode is disabled.

Operating system: macOS 12.6
CPU architecture: x86_64
Kernel: darwin 21.6.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.19.2

[NOTE]: # ( Pick choices based on your environment )
Operating System:  macOS

**Comment by droidmonkey** [comment] 2023-03-11 14:54
Duplicate of #7660

**Closed as not planned by droidmonkey** 2023-03-11 14:55 UTC
Labels: duplicate
