### ISSUE TITLE
Auto-Type window does not appear on MacOS

### ISSUE THREAD

**Issue by cono** [keepassxreboot/keepassxc#10041] opened 2023-11-20 10:42 UTC
## Overview
It mostly 80% reproducible.

when I press key binding for auto-type, I see Keepass icon jumps on dock (sometime autotype even appears, but its not active).
When you try to click by mouse on window, it put it in front of you, but without focus and you need additional mouse click to make it active.

## Steps to Reproduce
1. I set my keybinding to ctrl+p, so when I press ctrl+p it happens that autotype window not appear or appear without focus.

## Expected Behavior
Auto-type window appear with focus on it.

## Actual Behavior
1. Sometimes just icon jumps on the dock
2. Sometimes auto type window appear, but first click bring second window (main window) on the background of the auto-type window, and second click finally puts focus on auto-type window.

## Context
Apple M2 Max
Sonoma 14.1.1

KeePassXC - Version 2.7.6
Revision: dd21def

Operating System: macOS

**Comment by droidmonkey** [comment] 2023-11-20 11:24
What state is the keepassxc window before you request Auto-Type? 

Minimized, in tray, full desktop?

**Comment by cono** [comment] 2023-11-20 11:28
When it happens, it could be either minimized or behind other windows. Not using tray or full desktop for keepass.

**Comment by cono** [comment] 2023-11-20 11:34
My dock is on the left and with auto hide.
And also I have "Alt-Tab" application installed.
Not sure if it helps...

**Comment by droidmonkey** [comment] 2023-11-20 13:43
That might be interfering, try disabling that application

**Comment by cono** [comment] 2023-11-21 14:14
Here it is how it looks:
https://www.youtube.com/watch?v=DKNkrsrx2nA

I was not able to spot this before I initiated auto-type, because whenever I put screen recorder I'm not able to reproduce, but I was able to screenrecord when I pressed ctrl+p and focus still left on terminal

**Comment by droidmonkey** [comment] 2023-11-21 14:42
Use View -> Allow screencapture

**Comment by cono** [comment] 2023-11-23 11:58
don't see a difference with or without `Allow screencapture` I still can reproduce issue.

**Comment by droidmonkey** [comment] 2023-11-23 12:33
I meant for your video recording.  Never mind, I read your sentence wrong

**Comment by cono** [comment] 2023-11-23 15:40
I recorded this video which I showed to you with this checkbox disabled. So doesn't matter much. screencapture works

**Comment by droidmonkey** [comment] 2023-11-23 15:49
Yah macOS doesn't properly respect the "don't allow other apps to see this window" flag. It only really applies to screenshare for teleconference software at this point.

**Comment by cono** [comment] 2023-11-23 17:07
anyway, doesn't relate to this issue. Issue still present :-(

**Comment by fudimangoeggi** [comment] 2023-12-30 11:08
Hi there
I face a similar if not the same issue. I will describe it later in more detail. I have a feeling it has to do with the state KeePassXC is in at the moment of pressing the "Global Auto-Type shortcut".


KeePassXC - Version 2.7.6
Revision: dd21def

Qt 5.15.10
Debugging mode is disabled.

Operating system: macOS 14.1
CPU architecture: arm64
Kernel: darwin 23.1.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.19.3

**Comment by fudimangoeggi** [comment] 2023-12-30 15:26
First of all, I expect the following behaviour to be correct:
_When pressing the "Global Auto-Type shortcut" then:_

- _the Auto-Type window should appear_
- _the focus should be in the search field at the bottom of that window such that any subsequent keystroke goes to the search field._

I don't care too much about the KeePassXC main window (whether it's visible or not).

Here's what I noticed so far:
- The "Global Auto-Type shortcut" does NOT work when the Auto-Type window is "open but hidden". You can reach the "open but hidden" state when the Auto-Type window is open (visible) and you click on the red x button of the KeePassXC main window, top left corner.
- Besides the above mentioned exception, the "Global Auto-Type shortcut" works well and brings the Auto-Type window to front. However, from time to time, the Auto-Type window appears but does NOT receive or keep the focus; instead, the focus is somewhere in the KeePassXC main window; when typing in this state the keystrokes go to the KeePassXC main window. When this happens (focus in the KeePassXC main window), most of the times the focus is in the search field in the top right corner, but this is not always the case. I also noticed that I can "provoke" this situation with about 80% probability like this:
  - bring KeePassXC main window to front
  - click into the search field in the top right corner
  - click on another window (take the focus from KeePassXC main window)
  - press the "Global Auto-Type shortcut" -> the Auto-Type window appears but oftentimes does NOT receive or keep the focus

I hope my findings help you to further improve KeePassXC. It's already a great tool, thank you!

**Comment by fudimangoeggi** [comment] 2023-12-30 15:29
just in case... here's my KeePassXC setup (enabled checkboxes mentioned below):

**Startup**
- Start only a single instance of KeePassXC
- Automatically launch KeePassXC at system startup
- Minimize window at application startup
- Minimize window after unlocking database
- Remember previously use databases (5)
  - Load previously open databases on startup
  - Remember database key files and security dongles
- Check for updates at application startup once per week

**File Management**
- Automatically save after every change
- Automatically save when locking database
- Automatically save non-data changes when locking database
- Automatically reload the database when modified externally

**Entry Management**
- Use group icon on entry creation
- Minimize when opening URL
- Hide window when copying to clipboard
  - Drop to background

**User Interface**
- Language: system default
- Toolbar button style: Icon only
- Show passwords in color
- Minimize instead of app exit
- Show a system tray icon
- Try icon type: monochrome

**Comment by droidmonkey** [comment] 2023-12-30 15:42
For your second bullet point, is your focus in the "other window" on a password field?

**Comment by fudimangoeggi** [comment] 2023-12-31 14:01
I‘m not sure which bullet point you refer to. This one?
  - click on another window (take the focus from KeePassXC main window)

If you mean this one, then: The focus in the „other window“ is most probably NOT in a password field. But it‘s something I did not explicitly pay attention to; I just clicked randomly on some other window. In many cases the other window was the Chrome browser showing this issue:-) and I clicked into the comment field.

**Comment by fudimangoeggi** [comment] 2024-01-22 15:53
Hi there
I noticed another situation where the Auto-Type window does NOT appear as expected:
- I have two screens: 1. built-in screen of my MBP; 2. an external monitor
- KeePassXC is on the built-in screen
- application X (where the user wants to insert the Auto-Type keystrokes) is on the external monitor in full-screen mode.
- the user presses the Global Auto-Type shortcut -> the Auto-Type window is opened on external monitor "behind" application X on another desktop (it's open but not visible to the user)

I see there is a LOT of complexity in this seemingly simple requirement...

**Comment by Nzalo** [comment] 2024-10-09 11:57
Hi everyone,

I found this thread while having the same issue in the past days. 
I guess my issue solved itself with some update.

As of today, I can say that the program´s autotype works without a problem on my machine: 
Whether the app  (keepassxc) is on top, hidden or minimized, it switches to the full screen app and enters the credentials correctly whenever I trigger the autotype keybindings. I do choose the entry and sequence to be typed.
My use case is that I cannot copy and paste credenctials since it is for a remote desktop that does not allow that.
Using MacOS 15.0.1 on apple sillicon and KeepassXC 2.7.9.

Thanks a lot to everyone behind KeepassXC!

**Comment by droidmonkey** [comment] 2024-10-09 15:34
I am going to close this because I cannot reproduce it and seems related to something outside our control.

**Closed as not planned by droidmonkey** 2024-10-09 15:34 UTC
Labels: more info needed, platform: macOS, feature: Auto-Type
