### ISSUE TITLE
database doesn't close after timeout if a keepassxc-browser confirmation dialog is open

### ISSUE THREAD

**Issue by dadosch** [keepassxreboot/keepassxc#2625] opened 2019-01-20 17:52 UTC
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( Do not include screenshots of your actual database! )

## Expected Behavior
[NOTE]: # ( If you're describing a bug, tell us what should happen )
[NOTE]: # ( If you're suggesting a change/improvement, tell us how it should work )
KeepassXC doesn't close the database if a KeepassXC-Browser confirmation dialog is open

## Current Behavior
[NOTE]: # ( If describing a bug, tell us what happens instead of the expected behavior )
[NOTE]: # ( If suggesting a change/improvement, explain the difference from the current behavior )
It should close it once the time limit of inactivity (from settings) is reached.

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug, )
[NOTE]: # ( or ideas how to implement the addition or change )

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. Unlock database
2. go to a webpage where you have logins in your database with a url
3. the confirmation dialog should open
4. don't close this dialog. (=don't click accept/deny/close button)
![screenshot_20190120_184100](https://user-images.githubusercontent.com/12801390/51443036-7782ff00-1cdb-11e9-838a-8c2c8c074308.png)
5. the database doesn't lock after the specified timeout in the settings

## Context
[NOTE]: # ( How has this issue affected you? What are you trying to accomplish? )
[NOTE]: # ( Providing context helps us come up with a solution that is most useful in the real world )

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.3.4
Revision: 6fe821c

Bibliotheken:
- Qt 5.12.0
- libgcrypt 1.8.4

Betriebssystem: Arch Linux
CPU-Architektur: x86_64
Kernel: linux 4.20.3-arch1-1-ARCH

Aktivierte Erweiterungen:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by droidmonkey** [comment] 2019-01-20 22:59
Duplicate of #721

**Closed by droidmonkey** 2019-01-20 22:59 UTC
