### ISSUE TITLE
KeePassHTTP server matches empty URLs on any website

### ISSUE THREAD

**Issue by syxolk** [keepassxreboot/keepassxc#1081] opened 2017-10-16 20:49 UTC
## Expected Behavior

Don't suggest entries with empty URLs on websites I don't have an account for.

## Current Behavior

I visit a random website with a login form and KeePassHTTP suggests a set of accounts without URL. 

## Possible Solution

I guess the URL matching functionality was changed.

## Steps to Reproduce (for bugs)

1. Enable KeePassHTTP, configure chromeIpass in your browser, etc
2. Create a new entry with username and password but without any URL
3. Go to any website with a login form where you don't have an account.
4. KeePassXC will suggest all entries with empty URLs

## Context
I'm pretty sure this issue was not there on version 2.2.0

## Debug Info
KeePassXC - Version 2.2.1
Revision: 2bce9c8add07226e9a05e9e0fd0e5e66b236d5b6

Libraries:
- Qt 5.9.1
- libgcrypt 1.8.1

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.15063

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

**Comment by TheZ3ro** [comment] 2017-10-16 21:40
Duplicate of #1080 

Please use the search function next time

**Closed** 2017-10-16 21:41 UTC

**Comment by syxolk** [comment] 2017-10-16 21:48
Sry, I only searched for open issues. I didn't expect this to be fixed already 👍
