### ISSUE TITLE
Automatic language setting doesn't seem to work

### ISSUE THREAD

**Issue by markusd112** [keepassxreboot/keepassxc#3375] opened 2019-07-13 11:56 UTC
## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
After installing KeepassXC, the language setting is set to "automatic" to use the system language of the OS. So KeepassXC should use the system language of the OS automatically without user interaction.

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
I have installed KeepassXC now on two Win10 machines which are set to german language and on both machines KeepassXC doesn't use german language after installing. It shows english dialogs and texts. You have to switch manually to german language...

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. Install KeepassXC on a Win10 machine with a different language than english
2. Start KeepassXC
3. KeepassXC doesn't use the system language, but english.

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.4.3
Revision: 5d6ef0c

Qt 5.12.3
Debugging mode is disabled.

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.17763

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.4

**Comment by droidmonkey** [comment] 2019-07-13 14:54
Please post a screenshot of your windows 10 language settings.

**Comment by markusd112** [comment] 2019-07-13 17:24
![screenshot_keepassXC4](https://user-images.githubusercontent.com/14372683/61174677-d5661480-a5a3-11e9-95f7-90c13db364aa.JPG)

**Comment by droidmonkey** [comment] 2019-07-13 20:45
I figured out the problem and this is a duplicate of #3202

**Closed by droidmonkey** 2019-07-13 20:45 UTC
Labels: more info needed
