### ISSUE TITLE
Keepass unresolved dependency libsodium23

### ISSUE THREAD

**Issue by marshsheep** [keepassxreboot/keepassxc#1603] opened 2018-03-02 20:00 UTC
When running installation of KeePassXC, it installs KeePassXC but fails to install the necessary dependency libsodium23
when the system next updates my software, it uninstalls KeePass due to the broken dependency

I get the following error message

dpkg: error processing archive /var/cache/apt/archives/libsodium23_1.0.16-0ppa3~xenial1_i386.deb (--unpack):
trying to overwrite '/usr/lib/i386-linux-gnu/libsodium.so.23.1.0', which is also in package libsodium18:i386 1.0.16-0ppa1~xenial1
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)

This error did not occur until I attempted the new KeePassXC Browser migration process to replace the old KeePassHTTP plugin 

KeePassXC - Version 2.3.0
Revision: 4c0ed74

Libraries:
- Qt 5.5.1
- libgcrypt 1.8.1

Operating system: Linux Mint 18.2
CPU architecture: i386
Kernel: linux 4.4.0-21-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by phoerious** [comment] 2018-03-02 23:06
Duplicate of #1545.

**Closed by phoerious** 2018-03-02 23:06 UTC
