### ISSUE TITLE
Cannot open any database /run/... appears

### ISSUE THREAD

**Issue by vonHousen** [keepassxreboot/keepassxc#7739] opened 2022-03-31 07:57 UTC
## Overview
Out of a sudden (maybe after some snap update) I cannot open any database (at least in home directory).
When I use [Open a database] button I can clearly see the database (in home directory), but after selecting it, the path of a database to be opened is completely different: /run/user/[...] and so on. Even if I try to type a password, there is a message: "File /run/user/[...] does not exist." and therefore I cannot open it.

## Steps to Reproduce
1. Create new database.
2. Save it somewhere in home directory.
3. Close it.
4. Try to open it.

## Expected Behavior
Path of the selected database should be correct AND no error "File [...] does not exist" should be raised.

## Actual Behavior
Path of selected database is different (/run/user/[...]) and error "File [...] does not exist" is raised.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.0
Revision: 20c9ac1
Distribution: Snap

Qt 5.15.3
Debugging mode is disabled.

Operating system: Ubuntu Core 20
CPU architecture: x86_64
Kernel: linux 5.4.0-105-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.12.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: Ubuntu 18
Desktop Env: Gnome/KDE/XFCE/Mate/Cinnamon
Windowing System: X11/Wayland

**Comment by droidmonkey** [comment] 2022-03-31 10:03
For now you'll have to use our appimage or ppa

**Comment by michaelk83** [comment] 2022-03-31 12:16
Duplicate of #7607 ? Or just related?

**Comment by droidmonkey** [comment] 2022-03-31 13:28
This is a different issue, probably related to using Ubuntu 18

**Comment by vicma75** [comment] 2022-04-03 10:42
I tried to do so but doesn't work at all. Please help. I cannot acces any valuable info on my computer. Following info about system and error.
[info system.txt](https://github.com/keepassxreboot/keepassxc/files/8404289/info.system.txt)
![Screenshot_2022-04-03_12:25:06](https://user-images.githubusercontent.com/102902713/161423695-ba944e06-e832-4583-92e9-aa0a02ed4102.png)
.

**Comment by vicma75** [comment] 2022-04-03 10:43
[info system.txt](https://github.com/keepassxreboot/keepassxc/files/8404295/info.system.txt)

**Comment by droidmonkey** [comment] 2022-04-03 10:53
Download the appimage and use that for now

**Comment by vicma75** [comment] 2022-04-03 12:24
Thank you very much.

Víctor Mary

**Comment by droidmonkey** [comment] 2022-07-11 20:17
That isn't a solution. Solution is to stop using snaps because they are terrible. Switch to our flatpak.

**Closed as not planned** 2022-07-11 20:18 UTC
Labels: distribution: Snap
