### ISSUE TITLE
On 2.2.1 & macOS, Global Auto-Type dialogue comes to front, but database password field not actually in focus

### ISSUE THREAD

**Issue by sts10** [keepassxreboot/keepassxc#1023] opened 2017-10-03 02:06 UTC
I recently upgraded to 2.2.1 on my Mac and wanted to investigate whether the PR #663 fix was working. While the pop-up dialogue does now come to the front, when you start typing you're still in the username field, not the KeePassXC database password field. 

## Expected Behavior
1. While on a browser login page, with KeePassXC database locked, invoke Global Auto-Type keyboard shortcut
2. Database unlock dialogue appears on top of browser window. 
3. User begins typing their database password into the dialogue box. 
4. Hit enter after entering database password and KeePassXC performs the Auto-Type. 

## Current Behavior
1. While on a browser page, with KeePassXC database locked, invoke Global Auto-Type keyboard shortcut
2. Database unlock dialogue appears on top of the browser window (awesome!). 
3. User begins typing, and while a cursor appears in the database password field, the entered text is actually typed into the username text field rather than the database password field (see GIF below). **Even when I attempt to click into the database password field, I often still can't enter characters into it.**

![keepassxc-2-2-1global-auto-type-bug](https://user-images.githubusercontent.com/4871664/31106870-877282fe-a7bc-11e7-8993-98594af11c1f.gif)

## Possible Solution
I'm worried this is a macOS issue?

## Steps to Reproduce (for bugs)
1. While on a browser page, with KeePassXC database locked, invoke Global Auto-Type keyboard shortcut
2. Database unlock dialogue appears on top of the browser window (awesome!). 
3. User begins typing, but the entered text is actually being typed into the username text field rather than the database password field (see GIF above)
4. Attempt to click into the database password field-- I couldn't enter characters into it. 

## Context
Not a huge deal to me as I learned to use KeePassXC's Global Auto-Type feature. But I feel like new KeePassXC users will be frustrated and potentially disclose their master database password to internet services inadvertently.

## Debug Info
KeePassXC - Version 2.2.1
Revision: 2bce9c8add07226e9a05e9e0fd0e5e66b236d5b6

Libraries:
- Qt 5.9.1
- libgcrypt 1.8.1

Operating system: OS X Yosemite (10.10)
CPU architecture: x86_64
Kernel: darwin 14.5.0

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

Browsers: I reproduced this with FireFox 57.0b4 (64-bit) and Google Chrome Version 61.0.3163.100 (Official Build) (64-bit) on the login pages of both ProtonMail and Reddit.

**Comment by quinncomendant** [comment] 2017-10-03 09:28
This is a nicely written issue. @sts10, how did you make your animated gif?

**Comment by sts10** [comment] 2017-10-03 11:58
Thanks! 

I made the GIF using [GIPHY Capture](https://giphy.com/apps/giphycapture), though that application doesn't capture the mouse cursor. If I need to show the mouse, I use QuickTime screen record to make an MP4 file, and then [GIF Brewery](http://gifbrewery.com/) (10.11+) to turn that into a GIF. I had a lot of recent practice making my (self-promotion alert) [KeePassXC user guide](https://sts10.github.io/2017/06/27/keepassxc-setup-guide.html).

**Comment by droidmonkey** [comment] 2017-10-03 17:00
Holy cow what a nice user guide! We should make that our official guide (minus the MacOS specific stuff).

**Comment by affinityv** [comment] 2017-10-03 17:07
I agree.  I was thinking about how the cool gifs could be done with perhaps scrot tool or other options with Linux (rather than macOS).

**Comment by sts10** [comment] 2017-10-03 18:22
Thanks y'all! I actually mentioned it in a comment on [an issue about documentation](https://github.com/keepassxreboot/keepassxc/issues/696#issuecomment-311547304) back in June, offering it as a starting point for a how-to/wiki. Offer still stands! (Though I'm still a little unsure about the procedure I outline in the appendix, [Verifying Your KeePassXC Download without Using the Command Line](https://sts10.github.io/2017/06/27/keepassxc-setup-guide.html#appendix-verifying-your-keepassxc-download-without-using-the-command-line).)

As for making GIFs with Linux, I've been meaning to check out [Peek](https://github.com/phw/peek) ([OMG Ubuntu article](http://www.omgubuntu.co.uk/2016/08/peek-desktop-gif-screen-recorder-linux)), but I've currently only got Linux running on a machine with 2 GB of RAM and doubt it will perform well enough to really use.

**Comment by hfr-hfr** [comment] 2017-10-08 10:58
Probably related: after unlocking the database this way (by manually setting focus on popped up password field), KeepassXC should use the prior window (where global Auto-Type keyboard shortcut was invoked) to check against auto-type rules. Instead it uses it's own window ("*database-name* KeepassXC") and consequently presents an error dialog "no entry found with that window title".

**Comment by TheZ3ro** [comment] 2017-10-08 12:33
Seems a bug in MacOS window flags

**Comment by hfr-hfr** [comment] 2017-10-08 15:07
…KeepassXC gets the window right when database is unlocked at time of hitting Auto-Type keyboard shortcut. It only fails when database has to be unlocked in the process of KeepassXC's Auto-Type routine.

**Comment by mihaiile** [comment] 2017-10-17 15:44
I also can confirm that the fix added to 2.2.1 has this window in front but no-focus problem on mac.
Also, why does the main window is also when the unlock window is presented (this was was in 2.2.0 already), could it be related to actual bug? (if main window is minimised or closed it appears together with the unlock window)

**Comment by droidmonkey** [comment] 2017-10-19 03:16
@weslly were you going to fix this for 2.2.2?

**Comment by weslly** [comment] 2017-10-19 13:40
@droidmonkey yes, I'll take a look at it today

**Comment by weslly** [comment] 2017-10-20 15:09
It looks like there's no way to actually steal the focus just with Qt window flags on macOS. I'll probably have to use [`ActivateIgnoringOtherApps`](https://developer.apple.com/documentation/appkit/nsapplication/1428468-activate) from AppKit.

**Comment by quinncomendant** [comment] 2017-10-20 16:45
I wonder what method the auto-type selector window uses now. That comes to the foreground correctly, whatever method it uses.

**Comment by phoerious** [comment] 2017-10-21 22:03
Postponing, since no immediate solution is in sight.

**Comment by zoresvit** [comment] 2017-10-26 20:05
[MacPass](https://github.com/mstarke/MacPass) works as expected in similar situation, maybe some ideas for implementation could be taken from there.

**Comment by hfr-hfr** [comment] 2017-10-26 20:55
Here's a link to a properly working KeepassX 0.4.3 autotype patch from kar: https://web.archive.org/web/20150908084351/https://www.keepassx.org/forum/download/file.php?id=122
via KeepassX's now dead forum: https://web.archive.org/web/20150908084351/https://www.keepassx.org/forum/viewtopic.php?f=5&t=1920&start=120

Maybe this can help.

**Comment by hfr-hfr** [comment] 2017-10-26 20:57
…this is also supposed to be working on OSX: https://github.com/keithbennett/keepassx

**Comment by TheZ3ro** [comment] 2017-10-26 21:17
The specific commit is https://github.com/keithbennett/keepassx/commit/b87097a7abbc676c46ff0a84c341e381506a9fcc

It's doing his thing using the keepassx processId and the function `SetFrontProcessWithOptions`

**Comment by anshulbajpai** [comment] 2017-11-09 14:45
When I type the database password, because of this issue I can type it in clear text on some other webpage and I can end up revealing my password sitting next to me. 
Can we stick security label to this bug?

**Closed** 2017-11-20 12:59 UTC
Labels: bug, macOS, user interface

**Comment by anshulbajpai** [comment] 2017-12-19 14:31
I could still face the issue on latest macOS.

**Comment by droidmonkey** [comment] 2017-12-19 21:28
This fix will be released in v2.3.0 in the future.

**Comment by anshulbajpai** [comment] 2017-12-19 22:31
Sorry, my bad. I read the release 2.2.4 as 2.4.2.

**Comment by MaximKraev** [comment] 2017-12-23 10:37
Hello

I've backported patch to 2.2.4 version with the fix and it looks like after focus it doesn't perform autotype as it is looking for an entry for "keepassxc window". is behaviour for 2.3.0 different?

<img width="430" alt="screen shot 2017-12-23 at 10 35 21" src="https://user-images.githubusercontent.com/575940/34318990-16ae2bbc-e7cd-11e7-81a6-5744c17396f6.png">

**Comment by droidmonkey** [comment] 2017-12-23 13:08
There is no way to tell, master and develop branches are wildly different at this point.

**Comment by weslly** [comment] 2017-12-23 13:10
@MaximKraev there's an open issue for this already: https://github.com/keepassxreboot/keepassxc/issues/1216

**Comment by darkgeek** [comment] 2018-03-01 16:59
Hi, I have upgraded KeepassXC to 2.3 im My MacOS High Sierra via `Homebrew Cask`, but this issue remains.

**Comment by hfr-hfr** [comment] 2018-03-01 19:18
I can confirm that with MacOS 10.11.6 via binary bundle. Focus is now set correctly on password field. But the other issue (using wrong window title for autotype) remains. Here's my summary of this bug from October last year:

> after unlocking the database this (…) KeepassXC should use the prior window (where global Auto-Type keyboard shortcut was invoked) to check against auto-type rules. Instead it uses its own window ("database-name KeepassXC") and consequently presents an error dialog "no entry found with that window title".

**Comment by anshulbajpai** [comment] 2018-03-01 23:34
Yes, the focus is fixed but the undesirable alert is still coming up.
