### ISSUE TITLE
Auto-type a specifc field on demand

### ISSUE THREAD

**Issue by mrahs** [keepassxreboot/keepassxc#5539] opened 2020-10-12 04:50 UTC
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
When auto-type dialogue is presented, allow the user to choose which field to auto-type instead of the default sequence. To preserve default behavior, this can be activated with a modifier such as Ctrl, such that hitting Enter activates the default sequence, but hitting Ctrl+Enter presents the user with another dialogue to choose the field to auto-type.

To enhance the experience even further, the standard fields can be selected sequentially using the default order, by maintaining
an auto-type session for small period of time.
For example, user requests an auto-type, filters for the desired entry and hits Ctrl+Enter to bring another dialogue to choose a field to auto-type. At the this point, the username field is selected by default and auto-type is activated by hitting Enter. The user now requests auto-type again, which brings the auto-type dialogue with the previous desired entry already selected so the user doesn't have to filter again. Upon hitting Ctrl+Enter, the field selection dialogue appears with the password field already selected this time and ready to activate. Same process for the third time, but the OTP is highlighted this time.

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )

Entry selection dialogue:
![auto-type-entry-selection](https://user-images.githubusercontent.com/53349900/95706289-766ad180-0c24-11eb-9e19-2f003614103f.png)

Field selection dialogue:
![auto-type-field-selection](https://user-images.githubusercontent.com/53349900/95706293-7965c200-0c24-11eb-847f-4d3597003918.png)

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
Coming from 1Password, I miss the simplicity of using the same hotkey to fill username, password and OTP, and the convenience of using drag-n-drop on individual fields to fill them without having to use the clipboard.

For example, to login to amazon.com, I would hit Alt+\ to fill the username and hit enter, then Alt+\ again to fill the password and hit enter, then Alt+\ again to fill the OTP and hit enter. Alternatively, I can bring a mini window showing the relevant entry and use drag-n-drop to fill all three fields without using the clipboard.

With KeePassXC, I would have to specify an auto-type sequence involving form submissions and delays which is not reliable. Alternatively, the browser extension can be used with two different shortcuts. However, the experience described above in the feature request works with any application, not just browsers.

**Comment by droidmonkey** [comment] 2020-10-12 11:10
We definitely recommend our browser extension. Auto-Type into the browser is challenging on multiple fronts. I do like your suggestion though!

**Comment by mrahs** [comment] 2020-10-12 16:38
The browser was just an example. The focus of this feature request is on the ease of getting data out of KeePassXC. The experience of manually specifying auto-type sequences is outmatched by the ease of manipulating the sequence on the fly imo. I think it's even better than drag-n-drop if it was implemented on individual fields, though mouse-first users would argue against that.

I may be able to create a PR for this if you are willing to accept it. It would be great if I can get pointers on which files or components I should look at to put this together.

**Comment by droidmonkey** [comment] 2020-10-12 18:30
I am already making major improvements to the autotype workforce at this time.

**Comment by Amerlander** [comment] 2020-10-27 13:02
For me its important to have autotype accessible, since I sometimes use Keepassxc portable on PCs of friends.
So I didn't install a browser extension there, neither I want to check if they have some syncing in the clipboard (like sync windows and android like swiftkey plans to do, or the clipboard history in windows).

So generally I would prefer to have "Copy Username/Password" replaced by "Use Entry/Password for next autotype" or something like that.

**Comment by droidmonkey** [comment] 2020-11-11 23:02
Duplicate of #3630

**Closed by droidmonkey** 2020-11-11 23:02 UTC
Labels: new feature
