### ISSUE TITLE
Windows hello crash when on remote desktop

### ISSUE THREAD

**Issue by Stonedestroyer** [keepassxreboot/keepassxc#7890] opened 2022-04-14 06:48 UTC
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Login to keepassXC 
2. Enter hello pin
3. Lock the database so unlock shows
4. Connect to device with remote desktop and press unlock 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
For it to either ask for a password again or say it's invalid. 

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Program just closing. 

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - v2.7.1
Revision: 5916a8f

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 11

**Comment by droidmonkey** [comment] 2022-04-14 10:09
> Connect to device with remote desktop

https://keepassxc.org/docs/KeePassXC_UserGuide.html#_screenshot_security

**Comment by Stonedestroyer** [comment] 2022-04-14 12:12
I think you misunderstood me, the application works with remote desktop without issues and I've been using it like this for a while, it's just on that specific edge case with new windows hello functionality added it just closes. Unless you say this will resolve the edge case?

**Comment by droidmonkey** [comment] 2022-04-14 13:37
Please provide a screencapture of what you experience. I have no idea what the problem actually is based on the description.

**Comment by Stonedestroyer** [comment] 2022-04-14 14:04
I will try explain how the behavior was before and after. 

1. Start KeepassXC on device.
2. Login, 
3. Connect to the device through remote desktop from another device
4. KeepassXC logged out asking for pw again
5. It asks for password
6. Enter and you are logged in.


---
Windows hello behavior

1. Start keepassXC on device
2. Login
3. Windows hello prompt asking for PIN
4. Enter and now you are logged in. 
5. Connect to the device through remote desktop from another device
6. There is a "unlock" button that says unlock and has a fingerprint icon.
7. Press it and application closes.

I assume cause this is cause windows hello is not supported over remote desktop. As when I try to login again over remote desktop I don't get the windows hello prompt. So not sure what best scenario here would be, as the application just closes I assume it errors at some point. 

I did not see a way to extract the logs, I can try see if I can capture a video but it may be hard to capture all the events. 

The bug in this case would be the application just abruptly closing after pressing unlock.

**Comment by droidmonkey** [comment] 2022-04-14 19:32
Closing as in it is no longer in task manager? You don't get a prompt saying it crashed?

**Comment by Stonedestroyer** [comment] 2022-04-14 22:44
It closes as the window closes, and I can start it again so i assume it goes away from the task manager but will double check. But yes no errors.

**Comment by yllekz** [comment] 2022-04-25 12:39
This is still happening for me. Is there any progress on this? It doesn't crash, it just quits...even if the correct PIN is entered. Win10 21H2

**Comment by droidmonkey** [comment] 2022-04-25 13:33
Can't reproduce it so no, there is nothing obvious to fix here.

**Comment by Stonedestroyer** [comment] 2022-04-27 22:09
Could you perhaps note down the steps you are following? 

I will try to summarize it in fewer steps as my initial explanation was confusing.

1. Start KeepassXC
2. Login (windows hello enabled)
3. Go to another device, connect remote desktop to the device KeepassXC is running on
4. Press unlock on KeepassXC as database quick unlock is enabled.
5. Program closes

**Comment by deluxghost** [comment] 2022-04-28 08:06
This issue is 100% reproducible. While first time opening KeePassXC, enable the windows hello by providing your fingerprint, And login from another PC through RDP protocol. The only problem is, we don't know how to get some log files for you

**Comment by ttimasdf** [comment] 2022-09-05 08:09
Same problem, also on Windows 11. KeepassXC crashed when unlocking database through RDP.

**Comment by michaelk83** [comment] 2022-09-05 20:35
If it's a crash, you'll need to reproduce it with the latest snapshot to get a stack trace. Need to run it through a debugger, I think.
edit: This might be related to #7977.

**Closed as completed** 2023-02-15 06:33 UTC
Labels: platform: Windows, crash :boom:, feature: QuickUnlock
