### ISSUE TITLE
Autofill for other details

### ISSUE THREAD

**Issue by Dave-Combinatrix** [keepassxreboot/keepassxc#6422] opened 2021-04-18 17:29 UTC
## Summary
Hi I was wondering if there is a chance that Autofill for bowsers could be added. For things like addresses, credit cards and all the other things we are continually asked for, but aren't usernames and passwords. 
I personally would rather keep all that sort of information in KeepassXC rather than Google storing it. Especially as I keep my database on my USB key so it isn't easily accessible.

## Examples
Address, county, country, DOB, Card number, card sort code.
For any other information that may be suggested whilst on other sites.
Standard fields would be good, but some custom ones that can be used for unspecified or unusual details would be nice as well.

## Context
This would make my life so much easier as I wouldn't have to keep finding the required details as I don't have a good memory and this would help many other users as well. It would allow KeepassXC to keep up with programs like 1Password and others.

Thank you for looking at this and I hope this is something that could be added soon.

**Comment by droidmonkey** [comment] 2021-04-18 18:42
Duplicate of #4171

**Closed by droidmonkey** 2021-04-18 18:42 UTC
Labels: new feature
