### ISSUE TITLE
KeePassXC Freezes On closing in Linux Mint 20.0

### ISSUE THREAD

**Issue by ineuw** [keepassxreboot/keepassxc#5199] opened 2020-07-30 05:16 UTC
## Overview
On each attempt to close KeepPassXC, the app hangs.

## Steps to Reproduce
1. Open KeePassXC App
2. Open a database
3, Leave open for a few minutes, minimized or not
3. Click to close

## Expected Behavior
Close the KeePassXC app without freezing.

## Actual Behavior
Just hangs on screen for 30 - 40 seconds.

## Context
This happens whether a browser is open or not.

KeePassXC - Version 2.6.0
Revision: 0765954

Qt 5.12.8
Debugging mode is disabled.

Operating system: Linux Mint 20
CPU architecture: x86_64
Kernel: linux 5.4.0-42-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.5

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Cinnamon
Windowing System: X11/Wayland

**Comment by invidian** [comment] 2020-08-16 17:02
I experience the same on fresh install on Arch Linux. From `gdb`, I got:
```
ASSERT: "baseGroup" in file /home/invidian/repos/keepassxc/src/core/EntrySearcher.cpp, line 41
```

When trying to execute the following command:
```sh
secret-tool lookup UserName invidian
```

**Comment by droidmonkey** [comment] 2020-08-16 19:07
Nice that shows perfectly where the crash is occurring

**Comment by 0xpr03** [comment] 2020-09-11 12:20
Kinda the same issue as OPs ?

Two independent systems both experience full desktop hangs when closing keepassxc after using it with 1 DB and firefox integration. (Browser can already be closed)
Didn't happen in older versions. Doesn't happen if I don't close the browser first.

So steps are:
- OpenKeepassXC and Firefox
- Let firefox plugin connect, login to some site
- Close firefox
- Close keepassxc, watch keepassxc hang (~1-2 seconds)

```
KeePassXC - Version 2.6.1
Revision: 9a35bba

Qt 5.9.5
Debugging mode is disabled.

Operating system: Ubuntu 18.04.5 LTS
CPU architecture: x86_64
Kernel: linux 4.15.0-117-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.1
```

**Comment by shmerl** [comment] 2022-01-07 21:34
I have the same experience. What's strange is that in KDE it freezes the whole plasmashell as well. It's around 5 seconds for me though.

**Comment by droidmonkey** [comment] 2022-01-07 21:47
That would imply that it is plasma itself that is freezing.

**Comment by shmerl** [comment] 2022-01-08 23:00
Yeah, but somehow it's caused by keepassxc only.

**Comment by WineBottles** [comment] 2022-01-15 14:40
> That would imply that it is plasma itself that is freezing.

This happens to me on a fresh Arch install using KDE Plasma. Sure it may be "Plasma itself that is freezing" but _no other app behaves like this this_. Only KeePassXC. I installed KeePassXC from the pacman repo: https://archlinux.org/packages/community/x86_64/keepassxc/

Computer details:
Operating System: Arch Linux
KDE Plasma Version: 5.23.5
KDE Frameworks Version: 5.90.0
Qt Version: 5.15.2
Kernel Version: 5.15.14-hardened1-1-hardened (64-bit)
Graphics Platform: X11

This also happens on the regular non-hardened Kernel.

Additional details/what happens.
1) Launch KeePassXC
2) Close KeePassXC by pressing the x in the top right
My entire computer is unusable for approximately 2 seconds. I can move the mouse around but cannot actually click on anything.

This issue is probably more widespread than everyone thinks but we just ignore or live with it. I saw a Reddit post a couple days ago where 2 replies said they all experienced it:
https://old.reddit.com/r/KeePass/comments/s2cwmh/keepassxc_causes_kde_plasma_to_hang_for_about_2/

This occurs whether you unencrypt or just close the app right away so I don't think it has anything to do with the "encryption delay" that was mentioned in a comment.

With Steam Deck using KDE Plasma, it is a good time to get new users/spread awareness of Linux and would make a bad impression for KDE/Linux if the entire handheld hangs for 2 seconds just to close a password manager.

**Comment by droidmonkey** [comment] 2022-01-15 19:24
I setup a VM with the following;

Operating System: Fedora Linux 35
KDE Plasma Version: 5.23.4
KDE Frameworks Version: 5.89.0
Qt Version: 5.15.2
Kernel Version: 5.15.14-200.fc35.x86_64 (64-bit)

At first I was able to replicate a freeze on exit, but when I did system updates and installed packages required for building keepassxc.... it totally went away.

I just built the develop branch and it ran and exited without any delay.

**Comment by shmerl** [comment] 2022-01-15 23:50
That freeze doesn't happen all the time in Plasma. It could be some race condition that causes it to happen only sometimes when you close keepassxc. So just try doing it a lot.

**Comment by shmerl** [comment] 2022-01-18 06:43
Not sure if related, but when keepassxc closes I see this in the X session errors log:

```
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 61938, resource id: 98566758, major code: 18 (ChangeProperty), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 67, resource id: 102760465, major code: 18 (ChangeProperty), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 99, resource id: 98566759, major code: 18 (ChangeProperty), minor code: 0
```

**Comment by droidmonkey** [comment] 2022-01-18 11:04
https://bugreports.qt.io/browse/QTBUG-56893

**Comment by WineBottles** [comment] 2022-01-28 19:37
> https://bugreports.qt.io/browse/QTBUG-56893

Are you suggesting when that ticket is fixed and released this should no longer be an issue?

**Comment by droidmonkey** [comment] 2022-01-28 20:04
I'm not saying anything at this point besides the fact that this does not _seem to be_ caused by KeePassXC. It very well may be a Qt problem.

**Closed** 2022-03-13 02:25 UTC
Labels: bug, platform: Linux, in triage, crash :boom:

**Comment by shmerl** [comment] 2022-03-13 02:27
This still happens, so IMHO better to keep it opened until it's actually working properly.

Or may be this can be investigated more like running a debugger on that situation.

If it's a bug in Qt, better to narrow it down and actually report it upstream, otherwise it might never be fixed. I.e. I'm not convinced the above bug is the same as causing this hang / delay on exit.

**Comment by droidmonkey** [comment] 2022-03-13 02:31
This issue is all over the place. Narrow the parameters with which it occurs, preferably with a fresh OS install to rule out other factors. I cannot reproduce it as noted above.

**Comment by shmerl** [comment] 2022-03-13 02:34
My current set-up:

Debian testing.

keepassxc: 2.6.6
Qt: 5.15.2
KDE Plasma: 5.24.3

Is it different from yours?

**Comment by shmerl** [comment] 2022-06-26 03:50
Can't reproduce it with newer Qt in Debian testing (5.15.4), so I think it was a Qt bug that's now fixed.
