### ISSUE TITLE
Crash on Windows after PC wakes up since 2.7.7

### ISSUE THREAD

**Issue by lazka** [keepassxreboot/keepassxc#10455] opened 2024-03-17 08:07 UTC
## Overview

Since the update from 2.7.6 to 2.7.7 I occasionally get crashes when the PC wakes up and I get this shown on the unlock screen.

![Screenshot 2024-03-12 082145](https://github.com/keepassxreboot/keepassxc/assets/991986/9867b2e1-4b78-45f6-af48-cd39d29f1164)

It happened four times this week and never before that in the last year.

## Steps to Reproduce

I haven't figured out a way to reproduce, I only know this:

1) Have KeepassXC running
2) Put the PC to sleep
3) Wake up the PC

## Expected Behavior

No crash

## Actual Behavior

Crash

## Context

KeePassXC - Version 2.7.7
Revision: 68e2dd8

Qt 5.15.11
Debugging mode is disabled.

Operating system: Windows 11 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.22631

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 3.1.1

**Comment by droidmonkey** [comment] 2024-03-17 10:19
Yes I have seen this as well but haven't been able to track it down yet

**Comment by lazka** [comment] 2024-03-17 12:35
I think I got a stacktrace (the above is from the official installer, the stacktrace from the MSYS2 build):

```
[New Thread 17112.0x3eac]
warning: qt.qpa.mime: Retrying to obtain clipboard.
warning: qt.qpa.mime: Retrying to obtain clipboard.
warning: qt.qpa.mime: Unable to obtain clipboard.
warning: qt.qpa.mime: Retrying to obtain clipboard.
warning: qt.qpa.mime: Retrying to obtain clipboard.
warning: qt.qpa.mime: Unable to obtain clipboard.
warning: qt.qpa.mime: Retrying to obtain clipboard.
warning: qt.qpa.mime: Retrying to obtain clipboard.
warning: qt.qpa.mime: Unable to obtain clipboard.
warning: com\ole32\ole232\clipbrd\clipapi.cpp(3731)\ole32.dll!00007FFCE47751D0: (caller: 00007FFCE4776A25) ReturnHr(1) tid(2770) 800401D0 OpenClipboard Failed
warning: com\ole32\ole232\clipbrd\clipapi.cpp(3731)\ole32.dll!00007FFCE47751D0: (caller: 00007FFCE4776A25) ReturnHr(2) tid(2770) 800401D0 OpenClipboard Failed
warning: com\ole32\ole232\clipbrd\clipapi.cpp(3731)\ole32.dll!00007FFCE47751D0: (caller: 00007FFCE4776A25) ReturnHr(3) tid( (The operation completed successfully.)
[Thread 17112.0x3eac exited with code 0]

Thread 1 received signal SIGSEGV, Segmentation fault.
0x00007ff6dab92b1c in Database::transformedDatabaseKey() const ()
(gdb) bt
#0  0x00007ff6dab92b1c in Database::transformedDatabaseKey() const ()
#1  0x00007ff6dadbe679 in Kdbx4Reader::readDatabaseImpl(QIODevice*, QByteArray const&, QSharedPointer<CompositeKey const>, Database*) ()
#2  0x00007ff6dadbc5da in KdbxReader::readDatabase(QIODevice*, QSharedPointer<CompositeKey const>, Database*) ()
#3  0x00007ff6dad17bf5 in KeePass2Reader::readDatabase(QIODevice*, QSharedPointer<CompositeKey const>, Database*) ()
#4  0x00007ff6dab8fe16 in Database::open(QString const&, QSharedPointer<CompositeKey const>, QString*) ()
#5  0x00007ff6dac346ea in DatabaseOpenWidget::clearForms() ()
#6  0x00007ff6dac3427b in DatabaseOpenWidget::load(QString const&) ()
#7  0x00007ff6dac082a3 in DatabaseWidget::lock() ()
#8  0x00007ff6dabd3b6e in DatabaseTabWidget::lockDatabases() ()
#9  0x00007ff6dab5e443 in MainWindow::handleScreenLock() ()
#10 0x00007ffc87d1fd8d in void doActivate<false>(QObject*, int, void**) () from C:\msys64\clang64\bin\Qt5Core.dll
#11 0x00007ffc87d1fd8d in void doActivate<false>(QObject*, int, void**) () from C:\msys64\clang64\bin\Qt5Core.dll
#12 0x00007ff6dacfbdc3 in ScreenLockListenerWin::nativeEventFilter(QByteArray const&, void*, long*) ()
#13 0x00007ffc87ce8b73 in QAbstractEventDispatcher::filterNativeEvent(QByteArray const&, void*, long*) ()
   from C:\msys64\clang64\bin\Qt5Core.dll
#14 0x00007ffc87d40621 in QEventDispatcherWin32::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from C:\msys64\clang64\bin\Qt5Core.dll
#15 0x00007ffcb299fef5 in QWindowsGuiEventDispatcher::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from C:\msys64\clang64\share\qt5\plugins\platforms\qwindows.dll
#16 0x00007ffc87ce9d35 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from C:\msys64\clang64\bin\Qt5Core.dll
#17 0x00007ffc87ced07d in QCoreApplication::exec() () from C:\msys64\clang64\bin\Qt5Core.dll
#18 0x00007ff6dab33761 in main ()
```

**Comment by droidmonkey** [comment] 2024-03-17 12:43
Yup that is what I was thinking, I found that code and changed it, couldn't reproduce the crash yet.

**Comment by SynapseScribe** [comment] 2024-03-31 12:11
i got similar error after resuming from sleep

![image](https://github.com/keepassxreboot/keepassxc/assets/7840350/112be9ff-8684-4b38-9f05-a5c47e861ca0)

on 2.7.7
only happens sometimes, not after each resume

**Comment by droidmonkey** [comment] 2024-03-31 12:15
It's all the same, thank you. Fixed in the linked PR.

**Closed as completed** 2024-04-13 11:54 UTC
Labels: platform: Windows, crash :boom:
