### ISSUE TITLE
Says all my entries are expiring in three days for a minute

### ISSUE THREAD

**Issue by josephj11** [keepassxreboot/keepassxc#7502] opened 2022-03-05 23:52 UTC
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Says all my entries are going to expire in three days.
Fixes itself in a minute or so
## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Install KeePassXC-2.7.0-beta1-x86_64.AppImage
2. Run it the first time
3. Open an exiting database
4. View entries in a folder

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Should only note actually expiring/expired entries

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Says they're all going to expire in three days, then fixes itself after a minute or so.

## Context
[NOTE]: # ( Give us any additional information you may have. )
Was using the Ubuntu standard version (PPA enabled) before installing this one.
That message had me scared that something bad was about to happen, but I have backups.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - KeePassXC-2.7.0-beta1-x86_64.AppImage
Revision: 046e508

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux kubuntu 18.04
Desktop Env: KDE
Windowing System: X11

KeePassXC - Version 2.7.0-beta1
Build Type: PreRelease
Revision: 046e508
Distribution: AppImage

Qt 5.15.2
Debugging mode is disabled.

Operating system: Ubuntu 18.04.6 LTS
CPU architecture: x86_64
Kernel: linux 4.15.0-169-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.12.1

**Comment by droidmonkey** [comment] 2022-03-06 01:36
It's a new feature, you can disable it. To be clear, do those entries actually have an expiration date set on them?

![image](https://user-images.githubusercontent.com/2809491/156905528-93b1c12f-f22f-495c-abf4-bcc1e8353dc7.png)

![image](https://user-images.githubusercontent.com/2809491/156905549-fec19f2e-03bd-451d-91c0-f4def4155f72.png)

**Comment by josephj11** [comment] 2022-03-06 07:32
Not sure. Most of them definitely do and most are not expired. They all had the horizontal line thing (strike through) through every entry, but once it got it together by itself, most of those went away and things were back to normal. It was like it had the wrong date for today - way in the future, so everything was expired and then it got around to updating the date to the correct value. Looks like an initialization error. (I have a story about that "happening" on a mainframe a long time ago. )  ;)

**Comment by droidmonkey** [comment] 2022-03-13 02:19
Still happening or narrow down a cause? Going to close this otherwise.

**Comment by josephj11** [comment] 2022-03-13 18:02
I think the software is working as intended. I just have a lot of expired passwords and seeing them all at once was a shock. :) I would mark this as a non-issue.

**Comment by droidmonkey** [comment] 2022-03-13 19:47
I guess the feature worked as intended haha

**Closed as completed** 2022-03-13 19:47 UTC
Labels: more info needed
