### ISSUE TITLE
keepassxc browser integration breaks after upodate to FF71

### ISSUE THREAD

**Issue by robbosch** [keepassxreboot/keepassxc#4003] opened 2019-12-10 14:41 UTC
This morning I had a browser update to FF71 on Fedora30
Since the browser update I have a problem with the browser intergration addon.
(translated) message by the Keepassxc-Browser addon:
An error has occurred in KeePassXC Browser: No connection with KeePassXC. Check in KeePassXC settings if browser integration is activated.

The browser integration is active for FF browser.

I am not 100% sure this is because of the browser update, but I noticed this behavior after the update. I already reinstalled both KeepassXC and the FF KeePassXC-Browser addon. Also reset the KeePassXC settings to default to rule out my own fckups.
Any investigations I can do to help getting around this problem?

**Comment by robbosch** [comment] 2019-12-10 14:52
Probably related to: https://github.com/keepassxreboot/keepassxc-browser/issues/711

**Comment by varjolintu** [comment] 2019-12-10 14:55
Duplicate of https://github.com/keepassxreboot/keepassxc-browser/issues/704

**Closed by varjolintu** 2019-12-10 14:55 UTC
