### ISSUE TITLE
Quick-merge/resolve cloud conflict

### ISSUE THREAD

**Issue by rigrig** [keepassxreboot/keepassxc#4192] opened 2020-01-16 19:28 UTC
[TIP]:  # ( Provide a general summary of the feature in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Summary
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
While using cloud sync, I often end up with conflict files because I made changes to my password file on different devices. It would be nice if there was a quick way to resolve these conflicts by merging.

## Desired Behavior
[NOTE]: # ( Tell us how the new feature should work, be specific )
A quick way to merge in conflicted versions of the currently opened database.

## Possible Solution
[NOTE]: # ( Not required, but suggest ideas on how to implement the addition or change )
A new "Quick-merge conflict file..." menu action, placed below the "Merge from database..." menu entry.

Example scenario: I've opened `database.kdbx`, and the sync software just created `database (conflicted copy 2020-01-02 123456).kdbx`

1. I select the (new) menu option "Quick-merge conflict file...":
2. File picker opens, I select the `database (conflicted copy 2020-01-02 123456).kdbx` file
3. *KeePassXC checks I really picked a different file*
4. *KeePassXC checks the file can be opened with the same secrets as the already opened one*
5. KeePassXC merges the file, using the same secrets as the (already open) `database.kdbx`
6. *Only if 3 succeeds*: KeePassXC deletes `database (conflicted copy 2020-01-02 123456).kdbx`

I think doing step 6 righ away would be safe enough, because a) the merge succeeded and b) opening the other file with the same secrets as the current one worked, so it is likely a different version of the already-opened file.
But even a dialog asking me if I want to delete the just merged file would be an improvement over having to look up and delete the conflict file manually.

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
Currently merging conflict files is a rather annoying process:
* I have to re-enter the secrets for the conflict file, which includes picking a keyfile from another directory (as I don't want the keyfile to end up on the cloud)
* After merging, I have to manually look up and delete the conflict file.

Right now my process is:
1. I select "Merge from database...":
2. File picker opens, I select `database (conflicted copy 2020-01-02 123456).kdbx`
3. I re-enter the secret to open the conflict file (which involves looking up the keyfile)
4. KeePassXC merges the selected file
5. I use my file explorer to look up and delete `database (conflicted copy 2020-01-02 123456).kdbx`

It would be nice if KeePassXC automatically handled steps 3 and 5 for me.

**Comment by droidmonkey** [comment] 2020-01-17 04:06
Duplicate of #2937

**Closed** 2020-01-17 04:07 UTC
Labels: new feature

**Comment by rigrig** [comment] 2020-01-17 14:00
Thanks for making that clear. (and I looked for existing issues but failed to realize merge=sync)
