### ISSUE TITLE
Font issue

### ISSUE THREAD

**Issue by pkail** [keepassxreboot/keepassxc#3072] opened 2019-04-23 19:59 UTC
Add the option to at least double the size of the menu and dialog fonts.  At present, they are extremely hard to see, even at 1920x1200.

Unfortunately, setting QT_AUTO_SCREEN_SCALE_FACTOR = 1 affects other applications, making them unusable.

Thanks for your help.

**Comment by droidmonkey** [comment] 2019-04-23 21:42
Duplicate of #621

**Closed by droidmonkey** 2019-04-23 21:42 UTC
Labels: new feature
