### ISSUE TITLE
Perform Auto-type will missing some words into Virtualbox Windows.

### ISSUE THREAD

**Issue by kmvan** [keepassxreboot/keepassxc#3320] opened 2019-06-25 11:18 UTC
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Testing password string: 
> ~!@#$%^&*()_+

Use auto-type in Host and let it type into vbox Windows (Tested XP/Win7/Win10). The password shall be `~!@#$%^&*()_+` in vbox.

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
The password `~!@#$%^&*_+` is `(` and `)` string is missing in vbox.

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )
Maybe some `shift + special symbol` words? Not sure.

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. Create a VirtualBox Windows and open Notepad. Make Notepad focus and ready for typing.
2. In host, create an entry, password is `!@#$%^&*()_+`. (Shift + 1,2,3...) and save.
3. Right mouse button and click `Perform Auto-Type`.
4. Now KeepassXc shall typing password to vbox and the password will missing some words.

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )
Not sure.

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.4.2
Revision: a775031

Qt 5.12.3
Debugging mode is disabled.

Operating system: Manjaro Linux
CPU architecture: x86_64
Kernel: linux 5.1.8-1-MANJARO

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.4

**Comment by droidmonkey** [comment] 2019-06-25 12:07
Duplicate of #1833

**Closed by droidmonkey** 2019-06-25 12:07 UTC
Labels: bug
