### ISSUE TITLE
Client certificate management

### ISSUE THREAD

**Issue by LecrisUT** [keepassxreboot/keepassxc#6085] opened 2021-02-09 05:07 UTC
This is a longshot FR, but it can really make a huge change. The main idea is for KeePassXC to save the private key and manage import/removal of client certificates from compatible companion, e.g. in Firefox and hopefully in the future Thunderbird as well. With that we can manage the login of compatible websites and email servers.

Creation and renewal of the certificates can be done manually and imported in the Keepass database.

I don't see any similar plugin for keepass, but in keepassxc should be closer to being achieved with the current browser extension.

**Comment by droidmonkey** [comment] 2021-02-09 11:42
Can you please rephrase your request? What exactly is your end goal? Are you using certificates to authenticate to websites and email, but NOT using hardware token?

**Comment by LecrisUT** [comment] 2021-02-09 12:19
It's feature request to automate to automate and secure authentication using client certification. Websites and email servers can use client certificates to authenticate users, and they can be stored in firefox or the os native system.

The implementation can work as follows:
- save the private key and certificate in keepass database
- connect keepassxc with firefox browser
- when database is unlocked the extension would add the certificate to firefox's client authorities
- the user can then access the websites (without providing passwords) as if the certificate is installed normally
- the difference would be when the database is locked, have the extension delete the certificate from firefox's list. Like that, it cannot be exported and reused by others.

Some certificates I have do not have hardware tokens, and could be exported out of firefox or the OS when these are unlocked. I use windows linux and mac, with firefox. Maybe with some reconfiguration the certificates can be secured better like keepassxc's locking features, but I would prefer to have them centralized, managed and more easily enabled. E.g. I have different databases and profiles for when I'm working or at home

**Comment by droidmonkey** [comment] 2021-02-28 14:48
This is a duplicate of #3111

**Closed by droidmonkey** 2021-02-28 14:48 UTC
Labels: more info needed, new feature
