### ISSUE TITLE
Option to export single folder

### ISSUE THREAD

**Issue by b4d** [keepassxreboot/keepassxc#5464] opened 2020-09-23 09:12 UTC
## Summary
Often I want to export a single subfolder to HTML/CSV instead the full database. An option to do that would benefit me greatly.

## Examples
Probably right clicking the subfolder could provide option to export it to selected format?

## Context
I have a database of different clients and I need to export the credentials to them.

**Comment by droidmonkey** [comment] 2020-09-23 11:14
Duplicate of #1940

**Closed by droidmonkey** 2020-09-23 11:14 UTC
Labels: new feature
