### ISSUE TITLE
Merging erases entry history

### ISSUE THREAD

**Issue by Beartis** [keepassxreboot/keepassxc#965] opened 2017-09-19 06:00 UTC
Upon merging databases the affected entries lose all history.

## Expected Behavior
Merged history or history of the current database including an record of the merged state.

## Current Behavior
Complete loss of all history for merged entries.

## Possible Solution
Preserve current history, restore it after merging the entry and record the merge.

## Steps to Reproduce (for bugs)
1. Duplicate database.
2. Edit entry in database A.
3. Edit entry in database B.
4. Merge B into A.
5. View the history of the merged entry.

## Context
Trying to resolve out of sync databases. The usefulness of the merge is severely reduced precluding any review of what may or may not have been merged and further offset by the resulting data loss.

### Originally encountered with the official snap package:

KeePassXC - Version 2.2.0
Revision: 9a7e6850d6b79c47c2d46d99fdaf433c2ff13716

Libraries:
- Qt 5.7.1
- libgcrypt 1.7.6-beta

Operating system: Ubuntu Core 16
CPU architecture: x86_64
Kernel: linux 4.10.0-33-generic

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

### Reproduced with the latest 'develop' revision:

KeePassXC - Version 2.2.0
Revision: 6e1fd0694f1013de83fa7cfcf62c527a128a39be

Libraries:
- Qt 5.5.1
- libgcrypt 1.6.5

Operating system: Ubuntu 16.04.2 LTS
CPU architecture: x86_64
Kernel: linux 4.10.0-33-generic

Enabled extensions:
- Auto-Type

**Comment by TheZ3ro** [comment] 2017-09-19 11:17
AFAIR this is already fixed in 2.2.1 by @louib, isn't it?

**Comment by louib** [comment] 2017-09-19 13:57
@TheZ3ro no, it's not. I created an issue for that about a week ago (#939).

Just to be clear, when creating a new entry during the merge, we do copy the history over. The problem is when the entries are synchronized.

@droidmonkey I also think this is high priority, especially if we are to support automatic synchronization at some point. That being said, if you do decide to fix this in `2.2.1`, please keep in mind that the code for the merge function already changed a lot in `develop`.

**Comment by droidmonkey** [comment] 2017-09-19 15:39
This should be a relatively minor fix, I'll make that determination when i crack open the code. Unless you want to take a look first.

**Comment by louib** [comment] 2017-09-19 18:12
@droidmonkey go ahead. It would be nice to have someone else look at the merge code, especially if we are to further improve it in the future.

**Comment by droidmonkey** [comment] 2017-09-19 21:40
I fixed it, very easy, clone function had the wrong flags on it. However, looks like we have an option to "Merge Keep Both" that never gets used. There is no way to say your merge strategy is to keep both entries in the case of conflicts. Right now we only use "Keep Newer".

**Comment by louib** [comment] 2017-09-19 21:54
@droidmonkey that is correct. The UI does not allow setting the merge strategy. It's weird because it was in the original keepassx PR, but never made it into keepassxc.

I think KeePass has a form to select the merge options before merging, and the options are applied globally, not on a per-group basis, as with the current implementation. I think this would be more appropriate.

**Comment by droidmonkey** [comment] 2017-09-19 22:03
Yah I agree, also a merge strategy to prompt for conflict resolution. I am not a fan of automatic choices...

**Comment by monomon** [comment] 2017-09-19 23:19
Just to chip in on this, in the original implementation in keepassx the "Keep both" option is intended to preserve a copy of the older entry, marked appropriately with a custom attribute (and renamed, don't remember).

Also, per group (cascading) merge strategy does provide more flexibility, though more complex to use.

**Closed** 2017-09-23 22:41 UTC
Labels: bug, high priority
