### ISSUE TITLE
Might work 1x, but does not autofill credentials afterwards, even after closing browser or logging out

### ISSUE THREAD

**Issue by wfrpdm** [keepassxreboot/keepassxc#8648] opened 2022-10-25 05:31 UTC
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
keepass icon appears on login website pages, but will not auto-fill user name or password even after re-detecting fields.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Open KeepassXC
2. Click entry and open URL via keepass, OR 
3. Open URL in browser and click on Keepass icon in username field
4. Have checked using Vivaldi, Firefox, and Chrome 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Before latest update, would autofill username and password consistently even after logging out of site then re connecting.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Mostly, nothing happens... no auto fill, drop down with options for multiple credentials... nothing. Re-detecting fields does not help; closing browser and relaunching might help (seems hit and miss); log out of site on occasion works more than 1x, as does full system reboot but obviously this is not a functional workflow.

## Context
[NOTE]: # ( Give us any additional information you may have. )
On occasion, will work 1x, but if I log out of website then reconnect, log in credentials do not appear, although keepass icon displays (but does nothing.)
Sometimes, will not auto fill even once... simply fails to do anything... have not found consistent behavior from site to site yet.

[NOTE]: # ( Paste debug info from Help → About here )

KeePassXC - Version 2.7.3
Revision: d8483d3

Qt 5.12.8
Debugging mode is disabled.

Operating system: Linux Mint 20.3
CPU architecture: x86_64
Kernel: linux 5.15.0-52-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.12.1

[NOTE]: # ( Pick choices based on your environment )
OS: Linux Mint 20.3 x86_64 
Host: XPS 8930 1.1.13 
Kernel: 5.15.0-52-generic 
DE: Xfce 
WM: Xfwm4 
WM Theme: Plano-Blue-Modern 
Theme: Adwaita [GTK2/3] 
Icons: Mint-Y-Purple [GTK2/3] 
Terminal: xfce4-terminal 
Terminal Font: Monospace 12 
CPU: Intel i7-9700 (8) @ 4.700GHz 
GPU: NVIDIA GeForce GTX 1650 
GPU: Intel UHD Graphics 630

First time ever reporting a bug (usually just do whatever manual work-around will work) but I'm trying to contribute something useful to the community so forgive my lack of experience here. Will be more than happy to add info based on whatever CLI commands you need, or if you need me to enable debugging mode just let me know... not a total noob with Linux but would rate myself as a toddler just for your reference.

I'm sure this is as frustrating for you as it is for the users, but accept my thanks in advance.... not a programmer but definitely understand the complexities of your work... let me know if I can add anything useful.

Should also mention I cleared all previous connections to database and created new browser connections just to see if that would help, but no love.

**Comment by varjolintu** [comment] 2022-10-25 07:34
This is probably because your entry URL's are incorrect? For pages like `https://www.example.com/randomPath/login?yes=no` just use `http://example.com` or `https://example.com/randomPath` as the URL.

**Comment by kipusoep** [comment] 2022-10-25 09:02
Same issue here, it stopped working today or yesterday.
Yesterday I've updated KeepassXC so maybe related to that?

**Comment by varjolintu** [comment] 2022-10-25 09:04
Closing this as a duplicate of: #8634.

**Closed as not planned by varjolintu** 2022-10-25 09:04 UTC
Labels: feature: Browser
