### ISSUE TITLE
KeepassXC as a service

### ISSUE THREAD

**Issue by thelehhman** [keepassxreboot/keepassxc#4785] opened 2020-05-27 17:50 UTC
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
Add an option to run the KeepassXC as a background service, i.e. something similar to macOS menubar application

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )
Docker runs in the background, as a service.

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
When using the KeepassXC-Browser extension, the database gets locked automatically after sometime. Also, the window is an extra clutter on the screen. 
I understand that having the auto-locking feature is important for security, but I think a user should be allowed to compromise it for a significant usability improvement.

**Comment by phoerious** [comment] 2020-05-27 18:15
Duplicate of #1334.

**Closed by phoerious** 2020-05-27 18:15 UTC
Labels: new feature
