### ISSUE TITLE
Save various highly customizable password profiles

### ISSUE THREAD

**Issue by BoltCitizen** [keepassxreboot/keepassxc#4724] opened 2020-05-11 08:44 UTC
## Summary
I would like to be able to create, save, use (and maybe share) highly customizable password profiles

## Examples
![image](https://user-images.githubusercontent.com/65156740/81541600-a2331400-9373-11ea-8cbc-6d7f85c896c1.png)

![image](https://user-images.githubusercontent.com/65156740/81541630-b0813000-9373-11ea-9583-43ffef335094.png)

![image](https://user-images.githubusercontent.com/65156740/81541651-bd9e1f00-9373-11ea-9c44-1232ba0c3d56.png)

## Context
I sometimes have to share passwords verbally, written on paper or type them manually into a device. Using a password profile is perfect for this. Passwords that consist of groups of four upper alphanumerical characters with no look-alikes, seperated by periods is quite easy to communicate and to enter manually into a device

Also, certain services and devices have very specific password format requirements

Currently I am still using the password manager of KeePass2 to create passwords in KeePassXC, which is a bit of a hassle

It would be greate to be able to import my password profiles that I created in KeePass2

Thank you very much for KeePassXC :-)

**Comment by droidmonkey** [comment] 2020-05-11 11:56
Duplicate of #2628

We are never going to make our generator like the KeePass2 one, it is too complex and defeats the entire purpose of a **randomized** password generator.

**Closed by droidmonkey** 2020-05-11 11:56 UTC
Labels: new feature

**Comment by BoltCitizen** [comment] 2020-05-11 12:15
I understand the point of communicating passwords verbally via passphrases.

However there are various use-cases for password profiles. For me it is a must have feature. Keepass 2 implemented it very well, albeit slightly clunky
