### ISSUE TITLE
Support HOTP within entries similar to TOTP

### ISSUE THREAD

**Issue by 0gcr** [keepassxreboot/keepassxc#4371] opened 2020-02-24 17:58 UTC
## Summary
Provide HOTP as a 2FA method along side the currently supported TOTP method.

## Desired Behavior
Allow for input of HOTP shared secrets and generation of HOTP codes.

## Context
Some 2FA implementations (e.g. [Duo](https://help.duo.com/s/article/1306?language=en_US)) are HOTP.

**Comment by droidmonkey** [comment] 2020-02-24 21:42
We are not going to do this. See previous discussion.

**Comment by 0gcr** [comment] 2020-03-05 06:27
I have not been able to find the discussion you referred to. Would you be so kind as to place a link to that discussion in this ticket? Thanks.

**Comment by droidmonkey** [comment] 2020-03-05 11:31
Sorry when I read this i was confused and thought you meant to unlock the database with.

**Comment by volodymyr-gz** [comment] 2020-04-01 13:20
@droidmonkey Can you also remove `wontfix` label?

**Comment by Dave-c-Ross** [comment] 2022-05-10 14:25
Hey guys, any news on this feature ? :)
I know it has been added for 2.8.0, which seems to contain a lot of features. I was wondering if the HOTP feature had any progress and when it can be expeted.

Kindly 
Dave

**Comment by fftmp** [comment] 2022-11-30 22:01
Seems duplicate of #1878. 
Will also happy to see this functionality.

**Comment by droidmonkey** [comment] 2022-11-30 22:55
Closing that other request

**Comment by akhiljalagam** [comment] 2023-01-18 14:08
+1

**Comment by fftmp** [comment] 2023-01-21 19:48
Some info:
* HOTP credentials constists of 2 parts - key (just long string) and counter (number, that incremented after each OTP usage). So the principal difference with all other entities in keepass - is that we need to save modified db after each HOTP usage. Seems this can lead to unexpected behaviour - when someone create temp record or edit existing record, then use HOTP code, then don't want to store modifications. Also need to remember about this if using synchronization.

* DUO [store credentials ](https://faui1-files.informatik.uni-erlangen.de/public/publications/Spreitzenbarth-Polleit-IMF-2018-Defeating_OTP.pdf) inside `/data/data/com.duosecurity.duomobile/files/duokit/accounts.json` (root access required)

* There is small linux app to work with HOTP+TOTP: [OTPClient](https://github.com/paolostivanin/OTPClient). Possibly can be useful for testing or as temporary solution until keepassxc have no HOTP support.
* [TOTP and HOTP support in keepassDX](https://github.com/Kunzisoft/KeePassDX/issues/70). Seems HOTP works in read-only manner - need to edit counter manually.
* [Task about support HOTP at keepass plugin](https://github.com/tiuub/KeeOtp2/issues/46) (not keepass**XC**)


I made initial/draft support for HOTP just as start point: https://github.com/fftmp/keepassxc/tree/hotp. 
It is compatible with keepassDX and uses TOTP menus/keybindings to minimize changes for easier apply to mainstream at any time.
Setup: specify key  and counter in TOTP setup menu. 
Usage:  TOTP context menu->'Copy TOTP' or ctrl+T for copy TOTP or HOTP code and **and update counter** in case of HOTP.
Can use 'show TOTP' to see HOTP without incrementing counter.

@droidmonkey, do you have any ideas, how HOTP support must looks like in interface?
Is it ok to rename 'TOTP->Set up TOTP' context menu to 'OTP->Set up OTP', and add HOTP settings there?
Can we assume, that nobody will have HOTP and TOTP simultaneously for one record?

**Comment by droidmonkey** [comment] 2023-01-21 20:19
I don't understand what service uses HOTP, this seems like a feature no one will use and it just clutters the ui.

**Comment by IntoTheBlackHole** [comment] 2023-01-22 04:40
> I don't understand what service uses HOTP, this seems like a feature no one will use and it just clutters the ui.

Unfortunately, https://app.deel.com uses it. And I am very frustrated.

**Comment by fftmp** [comment] 2023-01-22 04:46
I met HOTP 2 times and both times this was microsoft enterprise infrastructure with single sign on + DUO mobile for 2FA.
So users have no permissions to select between HOTP/TOTP/etc/.

**Comment by piramiday** [comment] 2023-04-29 14:04
any updates or plans?

> I don't understand what service uses HOTP, this seems like a feature no one will use and it just clutters the ui.

as noted by the OP, one of the main services using HOTP is Duo: https://duo.com
indeed, the OP linked this webpage on their website: https://help.duo.com/s/article/1306

as a metric, consider that [their mobile app on the Play Store](https://play.google.com/store/apps/details?id=com.duosecurity.duomobile) reports 10M downloads -- it's really not a niche software.

also, a web search led me to this repo, in case inspiration was needed: https://github.com/WillForan/duo-hotp

**Comment by droidmonkey** [comment] 2023-04-29 15:14
10M downloads, but how many use HOTP. Duo supports HOTP, but not just HOTP. I have no plans to implement this, to be honest.

> So the principal difference with all other entities in keepass - is that we need to save modified db after each HOTP usage

This is the primary reason for not implementing HOTP. Its frankly a terrible solution in general because of this implementation detail.

**Comment by piramiday** [comment] 2023-05-03 10:46
> 10M downloads, but how many use HOTP. Duo supports HOTP, but not just HOTP. I have no plans to implement this, to be honest.

I believe most of those are HOTP users, since Duo is not really one of the most-used tools for third-party 2FA.
In other words, people install it only when they need it, e.g. [many US educational institutions](https://duckduckgo.com/?q=duo+.edu).

> So the principal difference with all other entities in keepass - is that we need to save modified db after each HOTP usage
> 
> This is the primary reason for not implementing HOTP. Its frankly a terrible solution in general because of this implementation detail.

wow, I did not realize that that would have been the case!
yes, that is a terrible implementation indeed. :fearful: 
might as well close this issue with a wont-fix label.

do you have any idea why so many companies would choose to go this direction, rather than the much more reasonable TOTP standard?

**Comment by droidmonkey** [comment] 2023-05-03 11:54
I am convinced people only uses HOTP today because of Duo. Especially after your response which is true.

**Comment by volo-droid** [comment] 2023-05-05 23:27
> > So the principal difference with all other entities in keepass - is that we need to save modified db after each HOTP usage
> 
> This is the primary reason for not implementing HOTP. It's frankly a terrible solution in general because of this implementation detail.

Strictly speaking, there's no need to save the database **every time** the HOTP is used. The counter value can be kept in memory, marking the database as dirty, and users can be requested to save the database before they close it (probably explaining the reason, otherwise it might be confusing for the user). And to prevent counter loss after a sudden power off (or in case the process has been killed) a separate temporary file can be used which would hold only the counter value, and if present upon the app restart the db would be synced with the file data.
The only question is whether it's all worth the efforts. Back in the days at some huge German enterprise company I was using a software called PingID (probably just because their sales did a great job in selling it to the company with 300K employees), but even they added support for TOTP some time ago.

**Comment by droidmonkey** [comment] 2023-05-06 00:53
We are just not going to implement this. Thank you for the discussion.

**Closed** 2023-05-06 00:52 UTC
Labels: new feature

**Comment by kmarf** [comment] 2023-11-29 13:42
I completely agree that HmacOTP is a terrible (counter based) implementation and can be difficult to support without counter persistence but it does unfortunately seem to be used quite widely as yet another form of security through obscurity, regularly forcing end users to recreate or reset their secrets because their offline counters get out of sync. Anyhow, another common use case that I'm aware of is for Amazon Workspaces client logins, at least for a few thousand users in my org and probably tens maybe even hundreds of thousands of end users globally. Being able to support HmacOTP (like Keepass 2.x does in placeholders) is definitely a desirable feature for some folks. More on how they do that is documented [here](https://keepass.info/help/base/placeholders.html#otp)
