### ISSUE TITLE
Support hmac-secret capable hardware tokens

### ISSUE THREAD

**Issue by imp1sh** [keepassxreboot/keepassxc#4013] opened 2019-12-13 08:59 UTC
## Summary
It would be nice if any FIDO2 key would work with keepassxc to unlock the vault.

## Desired Behavior
Unlock keepassxc datatbase with FIDO2 key.

## Possible Solution
Challenge Response seems legit. More details here:
https://github.com/solokeys/solo/issues/348

## Context
I just switched from a yubikey which gave me a static key which Solo key doesn't. Still would like to have a working and secure method to unlock my fault with not only a static password.

**Comment by droidmonkey** [comment] 2019-12-13 14:17
FIDO2 has nothing to do with HMAC-SHA1 challenge response.

**Comment by Iolaum** [comment] 2020-03-28 23:27
This looks like a duplicate of #3560 
There's a POC commit posted there, d63e737 if anyone is able to work on it.

**Comment by droidmonkey** [comment] 2020-03-29 00:40
That is correct, this is a duplicate

**Closed by droidmonkey** 2020-03-29 00:40 UTC
Labels: new feature
