### ISSUE TITLE
KeepassXC 2.7.1 (win) randomly segmentation faults

### ISSUE THREAD

**Issue by dodancs** [keepassxreboot/keepassxc#8441] opened 2022-09-03 13:05 UTC
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Start KeeepassXC
2. Have KeepassXC running for some time, maybe even hibernate and bring your laptop back from sleep
3. Click on "Unlock Database" and use your Windows Hello
4. Wait for just a second for it to crash (maybe this is because I triggered Keepass from the Chrome browser plugin??)

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
KeepassXC should launch and open the database.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
KeepassXC fails and the application closes or sometimes some error with memory appears and when you click OK it closes the application. 

## Context
[NOTE]: # ( Give us any additional information you may have. )
I use Windows 10 21H2 x64 on a laptop, usually, I use KeepassXC from the browser so I also have the Chrome plugin v1.8.1. 

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.1
Revision: 5916a8f

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10 21H2

**Comment by droidmonkey** [comment] 2022-09-03 13:35
Can't do much without a crash dump. Please use our snapshot version to generate one.

**Comment by dodancs** [comment] 2022-09-06 06:29
> Can't do much without a crash dump. Please use our snapshot version to generate one.

@droidmonkey Can you please give me some instructions on how to generate a crash dump? I have downloaded the portable version of KeepassXC snapshot and it did the thing I described but I couldn't find any logs, nor in the directory of the portable executable, nor AppData, Local or Roaming, nor Temp.

```
KeePassXC - Version 2.7.1-snapshot
Build Type: Snapshot
Revision: 15b9e82
```

**Comment by droidmonkey** [comment] 2022-09-06 10:54
You need to enable them in the registry first: https://docs.microsoft.com/en-us/windows/win32/wer/collecting-user-mode-dumps

Or you can create one from the task manager, do this before you press ok on the application has crashed popup.

https://www.windowscentral.com/how-create-crash-dump-file-manually-windows-10

Be aware if you use your personal database that your information could be leaked in the dump. We recommend using a new or demo database when reproducing the crash.

**Comment by dlehammer** [comment] 2022-10-10 16:23
Hi @droidmonkey,

I suspect I've experienced a symptom similar to the original [description](https://github.com/keepassxreboot/keepassxc/issues/8441#issue-1360852949).

From Help -> About -> Debug Info
```
KeePassXC - Version 2.7.1
Revision: 5916a8f

Qt 5.15.3
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.19044

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.18.1
```

After entering my password, I'm presented with the below pin-prompt:
![image](https://user-images.githubusercontent.com/17439718/194908558-65257382-d049-4ce3-9966-534218f22e77.png)

If I enter my pin KeePassXC closes (crashes?), on the other hand if I press ESC the prompt disappears and I can use KeePassXC as usual 🤔 #Workaround
(I only discovered this right now by happy accident, when attempting to create a screen shot, and KeePassXC kept disappearing from the screen ~ so I escaped from the screen shot view)
Note: the pin support seemingly worked before as I've only recently experienced the symptom ~ I suspect perhaps a recent Windows upgrade has changed some behaviour, and the response from the pin-prompt triggers the unexpected KeePassXC behaviour.
 
I've also attempted to create a memory dump with a new DB as [suggested](https://github.com/keepassxreboot/keepassxc/issues/8441#issuecomment-1237990657), via the Task manager, just before pressing the final digit in the pin-prompt: 
https://www.dropbox.com/s/dvxseeuz9k550os/KeePassXC_8441.zip?dl=1

Hope this can help teasing out the root cause :)

**Comment by droidmonkey** [comment] 2022-10-10 16:26
Please download the latest snapshot build from https://snapshot.keepassxc.org. I am pretty sure this is fixed with proper exception handling that will be part of the 2.7.2 release.

**Comment by dlehammer** [comment] 2022-10-11 15:17
Hi @droidmonkey,

I've attempted to download "latest" portable zip from the provided link, but unfortunately I'm blocked by SmartScreen:
![image](https://user-images.githubusercontent.com/17439718/195130455-8b54cab1-103a-44f2-a6f2-d8a580218f3d.png)

As I usually utilize the portable version + only have limited access to the environment ~ so I don't know how to proceed from here :/
(Ie. the portable v2.7.1 must be signed since I'm able to execute it without issue)

**Comment by phoerious** [comment] 2022-10-11 15:20
There should be a small "more info" link somewhere where you can run it anyway. If not, you will have to change your app and browser control settings from "block" to "warn".

**Comment by dlehammer** [comment] 2022-10-15 18:42
Hi @phoerious,

Thanks for the suggestion, unfortunately the screenshot shows my options after clicking "More info" ~ revealing "App" & "Publisher".
![image](https://user-images.githubusercontent.com/17439718/195130455-8b54cab1-103a-44f2-a6f2-d8a580218f3d.png)

Unfortunately I'm unauthorized by the client to make changes to the environment, but I'll  be happy to test out a signed release :)

**Comment by dlehammer** [comment] 2022-10-24 12:04
Hi @droidmonkey,

I've verified I'm unable to reproduce the [symptom](https://github.com/keepassxreboot/keepassxc/issues/8441#issuecomment-1273555418) using [v2.7.3](https://github.com/keepassxreboot/keepassxc/releases/download/2.7.3/KeePassXC-2.7.3-Win64.zip).
Entering the pin when prompted results in access to the DB (or pressing Esc, also grants access).

**Comment by phoerious** [comment] 2022-10-24 12:17
Thanks for confirming. I will close this as resolved now.

**Closed as completed by phoerious** 2022-10-24 12:17 UTC
Labels: more info needed, platform: Windows, crash :boom:
