### ISSUE TITLE
Cannot enter special characters using English (US, international with dead keys) keyboard layout

### ISSUE THREAD

**Issue by aucuparia** [keepassxreboot/keepassxc#918] opened 2017-08-31 12:58 UTC
## Expected Behavior
Entering special characters like `~` or `^` works as it does in every other application.

## Current Behavior
Characters that require two keypresses cannot be entered. For example, the keypress `` ` `` followed by an `n` causes a `ǹ` to appear in other applications, but incorrectly causes a `n` to appear when entered in the Password field of KeepassXC (no accent grave).

## Possible Solution
I don't know.

## Steps to Reproduce (for bugs)
1. Install Ubuntu 16.04.3 (LTS)
2. Update packages and reboot
3. Install KeepassXC 2.2.0 using Snap (`sudo snap install keepassxc`)
4. Set keyboard layout to `English (US, international with dead keys)`
4. Open KeepassXC, create a database and save it to passwords.kdbx
5. Click the `Add new entry` button
6. Try to enter a special character that requires two keypresses into the Password field.

## Context
Cannot manually copy existing passwords with special characters into database entry.

## Debug Info
KeePassXC - Version 2.2.0
Revision: 9a7e6850d6b79c47c2d46d99fdaf433c2ff13716

Libraries:
- Qt 5.7.1
- libgcrypt 1.7.6-beta

Operating system: Ubuntu Core 16
CPU architecture: x86_64
Kernel: linux 4.10.0-33-generic

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

**Comment by ArchangeGabriel** [comment] 2017-08-31 13:33
I think this is related to https://bugreports.qt.io/browse/QTBUG-42181 and linked bugs.

**Comment by droidmonkey** [comment] 2017-09-04 12:29
So i assume this is not necessarily a keepassxc exclusive bug?

**Comment by ArchangeGabriel** [comment] 2017-09-04 15:16
No, it’s a Qt bug. If OP could confirm by trying to input into any other Qt5 app?

**Comment by aucuparia** [comment] 2017-09-05 13:13
@ArchangeGabriel Could you suggest one that is available from the Ubuntu package repositories?

**Comment by ArchangeGabriel** [comment] 2017-09-06 21:55
Sure, I suppose kate would be the easiest one to try.

**Comment by ArchangeGabriel** [comment] 2017-09-07 19:04
Hum maybe I misunderstood you, weren’t you saying that typing ``` followed by `n` was not issue `ǹ` but `n` in KeePassXC? Can you confirm that this exact test works in kate?

**Comment by GuilloOme** [comment] 2017-09-07 19:53
I tested it and I can confirm that on kate, the `ǹ` is rendered as expected while the same keystroke render a `n` on KeePassXC.

![screenshot from 2017-09-07 15-50-54](https://user-images.githubusercontent.com/247594/30182366-9fbdcf08-93e4-11e7-94f8-5b4d1aced042.png)
![screenshot from 2017-09-07 15-53-23](https://user-images.githubusercontent.com/247594/30182444-b1500da8-93e4-11e7-9204-ac986dafd470.png)

**Comment by ArchangeGabriel** [comment] 2017-09-07 19:57
That is strange. Can you confirm (from Help/About) that both apps are compiled with Qt 5.x?

**Comment by GuilloOme** [comment] 2017-09-07 20:00
for KeePassXC v2.2.0

```
Qt 5.9.0
```
and for kate v16.12.3: 

```
Qt 5.7.1 (built against 5.7.1)
```

**Comment by ArchangeGabriel** [comment] 2017-09-07 20:05
Hum, maybe that can explain the issue. I guess that Qt 5.7.1 is coming from Ubuntu repos, one would need to take a look at what patching they do.

**Comment by phoerious** [comment] 2017-09-15 09:24
Are you using the AppImage? That one comes with it's own Qt 5.9, while your KDE apps use another Qt version.

**Comment by kafran** [comment] 2017-10-04 20:13
I would like to confirm this bug with appimage version 2.2.1 running on Ubuntu 16.04.3. I'm on a brazilian keyboard (br-abnt2). I can't enter some characters like: `~^'`

If I press `~+space` (the expected to get ~), it doesn't work. But if I press `alt gr+~` I can get `~`. No way I can get ^.

Workaround: copy+paste special characters from another place.

**Comment by klenje** [comment] 2019-03-04 17:07
I have the same issue on the password field, but it works if I make visible the passwords (no asterisks)

Keepassxc 2.3.4
OSX 10.13

The related Qt bug seems fixed in 5.14...

**Comment by toxynoid** [comment] 2019-06-30 08:51
I can confirm this, no circumflex ^ in the password field but works in the keyfile field.

Keepassxc 2.3.4
Ubuntu 19.04

**Comment by droidmonkey** [comment] 2019-07-10 02:28
This was/is a Qt bug

**Closed by droidmonkey** 2019-07-10 02:28 UTC

**Comment by mfrade** [comment] 2023-01-08 20:09
I know this issue is closed, but I had a similar problem with inserting characters with dead keys, and I want to share my workaround here.

My system:

- Kubuntu 22.04.1
- KeepassXC 2.7.4 (installed from PPA)
- Qt 5.15.3

My problems started after installing `zoom` because it depends on the `ibus` package. The `ibus` changes the way dead keys work and no longer act as real "dead keys" because it shows a preview of the "dead key" before the second key is pressed. Removing the `ibus` package removes also `zoom`, but `ibus` is not needed on kde plasma. What I did was:

- uninstall `ibus` and `zoom`
- used [`equivs`](https://wiki.debian.org/Packaging/HackingDependencies) to install a fake `ibus` package:
```Console
sudo apt install equivs

echo """
Package: ibus
Version: 99:99
Maintainer: myself <mail@domain.com>
Architecture: all
Description: dummy ibus package for zoom
 A dummy package with a version number so high that the real package will never reach it.
""" > anti-ibus.equivs
  
equivs-build anti-ibus.equivs

sudo apt install ./ibus_99_all.deb
  ```
- reinstall `zoom`

Now the dead keys are working as expected, I can enter passwords with special characters (like `áâã...`) on keepassXC without showing the password field, and `zoom` also works.

I hope this is useful to someone.

**Comment by HoffmannP** [comment] 2023-01-10 12:35
The solution from @mfrade works like a charm, thank you!
