### ISSUE TITLE
Referenced password not working

### ISSUE THREAD

**Issue by metbril** [keepassxreboot/keepassxc#1352] opened 2018-01-05 12:39 UTC
[test.kdbx.zip](https://github.com/keepassxreboot/keepassxc/files/1606573/test.kdbx.zip)

When usings referenced fields, this does work for username, but not for password.
The reference to the user is replace by the username, but the reference to the password is used as the password itself (so the password is actually pasted as `{REF:P@I:xxx}`).

I have for example an Amazon and Audible login in the database, where audible is referenced to amazon. See **attachted database** `test.kdbx`, password `test`.

## Debug info

KeePassXC - Version 2.2.4
Revision: 4723f66

Libraries:
- Qt 5.9.1
- libgcrypt 1.8.1

Operating system: macOS High Sierra (10.13)
CPU architecture: x86_64
Kernel: darwin 17.3.0

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

**Comment by TheZ3ro** [comment] 2018-01-05 13:25
AFAIR we already fixed this in the `develop` branch and will be in 2.3.0 release

**Comment by phoerious** [comment] 2018-01-05 15:12
Duplicate of #1040

**Closed by phoerious** 2018-01-05 15:12 UTC
