### ISSUE TITLE
2.5.1 MacOS password field font is wrong

### ISSUE THREAD

**Issue by tomhundt** [keepassxreboot/keepassxc#3853] opened 2019-11-12 19:44 UTC
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )
Looks like something broke or regressed with the password field font.  Suddenly it's not using a monospaced one.  I'm assuming it's not deliberate.  (Maybe something to do with PR 3727?)

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Password fields displayed in fixed-width _Monaco_ font.  Here's a screen shot of 2.4.3 display:
<img width="800" alt="keepassxc-243-test" src="https://user-images.githubusercontent.com/12475662/68703645-e74ec880-053f-11ea-85f0-c2fdd80d84c0.png">

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
Password fields display in a small, proportional/variable-width, serif font (looks like _Times Regular_ 10pt)
<img width="1057" alt="keepassxc-251-test" src="https://user-images.githubusercontent.com/12475662/68703646-e74ec880-053f-11ea-9156-e0678311354a.png">

Another, longer pw to help in figuring out what it is
<img width="424" alt="keepassxc-251-longer-pw" src="https://user-images.githubusercontent.com/12475662/68703647-e74ec880-053f-11ea-9a03-8a5056bca4fc.png">

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )
Bring back Monaco or let us choose the font (I understand this under consideration?).

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
Opened the same file under version 2.5.1 on one computer, and 2.4.3 on another that hasn't been updated yet.  They should have all the same fonts (newer one was migrated from older one) and both are running latest Catalina.
1.
2.
3.

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )
Harder to read the password, now.

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.5.1
Revision: 0fd8836

Qt 5.13.1
Debugging mode is disabled.

Operating system: macOS 10.15
CPU architecture: x86_64
Kernel: darwin 19.0.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.5

Libraries:
- LIBS

**Comment by droidmonkey** [comment] 2019-11-12 20:32
I noticed this as well and firmly blame Qt on this.

**Comment by droidmonkey** [comment] 2019-12-31 14:41
Duplicate of #1917

**Closed** 2019-12-31 14:41 UTC
Labels: bug, duplicate, platform: macOS
