### ISSUE TITLE
KeePassXC-2.2.4-2.dmg doesn't open on macOS 10.10.5

### ISSUE THREAD

**Issue by jsoref** [keepassxreboot/keepassxc#1470] opened 2018-02-09 22:10 UTC
A colleague reports that he can't use https://github.com/keepassxreboot/keepassxc/releases/download/2.2.4/KeePassXC-2.2.4-2.dmg on macOS 10.10.5:
<img width="377" alt="keepass disk image issue" src="https://user-images.githubusercontent.com/2119212/36052519-09c5f028-0dbc-11e8-837c-997252b665c6.png">

He was able to use https://github.com/keepassxreboot/keepassxc/releases/download/2.2.2/KeePassXC-2.2.2.dmg

The download page claims that 2.2.4 supports 10.10 ...

**Comment by TheZ3ro** [comment] 2018-02-09 22:28
Duplicate of #1344

**Closed by TheZ3ro** 2018-02-09 22:28 UTC
