### ISSUE TITLE
KeeShare File Browse Dialogue closes after 20 seconds - macOS

### ISSUE THREAD

**Issue by islamadel** [keepassxreboot/keepassxc#4846] opened 2020-06-11 08:22 UTC
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
When selecting the keeshare File in the Browse Dialogue, the window closes after 20 seconds. This is not enough time to select the required file.

## Steps to Reproduce
1. right click a group > edit group 
2. KeeShare > click the Browse icon near Path
3. While choosing the file, the window will close after 20 seconds.

## Expected Behavior
Window should remain open, until selection is done

## Actual Behavior
window closes after 20 seconds

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.5.4 + 2.6.0-snapshot

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS Mojave 10.14.6

**Comment by droidmonkey** [comment] 2020-06-11 10:22
Fixed in 2.6.0

**Comment by islamadel** [comment] 2020-07-10 17:28
Bug Still exists in 2.6.0 stable release. As soon as I click on Browse.. the windows closes after few seconds.

**Comment by droidmonkey** [comment] 2020-07-10 20:29
Yah I noticed

**Comment by droidmonkey** [comment] 2020-09-27 16:20
Duplicate of #5295

**Closed by droidmonkey** 2020-09-27 16:20 UTC
Labels: bug
