### ISSUE TITLE
Autotype does not working properly. It adds extra " symbols to fields.

### ISSUE THREAD

**Issue by Auronius** [keepassxreboot/keepassxc#10206] opened 2024-01-16 17:13 UTC
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Good day!
I use KeePassXC 2.7.6 AppImage on Linux Q4OS 5 Aquarius, which is Debian 12 Bookworm based distro.
I live in Latvia, so I am using Latvian (apostrophe variant) keyboard layout.
![KeyboardLayout](https://github.com/keepassxreboot/keepassxc/assets/13540006/8bdfff9c-4f3f-4631-ad15-35d8641161c2)
**My problem is, when I perform auto-type using default settings, KeePassXC adds extra " symbols into Username and password fields, which results in failing login attempts.** This happens on all websites I have tested (more than 20).
Here are the examples from Q4OS Forum (https://www.q4os.org/forum/login.php).
![KeePassXCAutotype1](https://github.com/keepassxreboot/keepassxc/assets/13540006/222998b5-4469-4161-b68f-ba219d83dfa6)
![KeePassXCAutotype2](https://github.com/keepassxreboot/keepassxc/assets/13540006/8ae10306-6dde-40d0-aa0b-eef8362e91dd)
I do not have this issue, when I switch to US keyboard layout. But, I live in Latvia and I need Latvian keyboard layout.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Set Latvian (apostrophe variant) keyboard layout in your OS Keyboard layout settings
2. Open a database and try to perform an auto-type (without browser plugin).
3. Your login attempt fails, because KeePassXC will add extra" characters to fields.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Auto-type should fill the login fields correctly, without any extra characters.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
When I perform auto-type, KeePassXC adds extra " symbols into Username and password fields, which results in failing login attempts.

## Context
[NOTE]: # ( Give us any additional information you may have. )
I do not have this issue, when I switch to US keyboard layout. But, I live in Latvia and I need Latvian keyboard layout.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.6
Revision: dd21def
Distribution: AppImage (signature has been verified)

Qt 5.15.2
Debugging mode is disabled.

Operating system: Debian GNU/Linux 12 (bookworm)
CPU architecture: x86_64
Kernel: linux 6.1.0-17-amd64

[NOTE]: # ( Pick choices based on your environment )
**Operating System:** Linux Q4OS 5.4.1-n1, which is Debian 12 Bookworm based distro.
**Desktop Env:** TDE (Trinity)
**Windowing System:** X11

**Comment by droidmonkey** [comment] 2024-01-16 17:19
Duplicate of #7881

**Closed as not planned by droidmonkey** 2024-01-16 17:19 UTC
