### ISSUE TITLE
[macOS] Prompt for a master password, despite having quick unlock via Touch ID after opening the lid

### ISSUE THREAD

**Issue by KORraNpl** [keepassxreboot/keepassxc#8945] opened 2022-12-31 14:36 UTC
## Overview
I have quick unlock enabled. Whenever I try to unlock my database after it has been locked due to closing the lid), there is a prompt for a master password. There is no button for quick unlock. After typing anything in the field (bad / good password), only then prompt to use the Touch ID and the db gets unlocked (given I use the right finger, so this part works fine).

**Note:** This seems to work as expected if I manually lock the db / put the machine to sleep / lock it.

## Steps to Reproduce
1. Unlock a db with quick unlock enabled.
1. Close the lid (make sure in your settings that KeePassXC will lock the db in this case).
1. Open the lid and try to unlock the db.

## Expected Behavior
As the quick unlock is enabled, I can click "Unlock Database" button, use the Touch ID to have the db unlocked.

## Actual Behavior
I get a prompt for a password, then (regardless the password is valid or not), I get a prompt for using Touch ID.
<img width="912" alt="image1" src="https://user-images.githubusercontent.com/1622190/210140097-a084f951-bc66-4a84-ab7c-685283533462.png">
<img width="798" alt="image2" src="https://user-images.githubusercontent.com/1622190/210140099-0f7b6e75-3806-4e5f-ab78-a4bdfa514ed7.png">
<img width="912" alt="image3" src="https://user-images.githubusercontent.com/1622190/210140100-533abcac-5f33-4251-a888-b864d6627136.png">

## Context

KeePassXC - Version 2.7.4
Revision: 63b2394

Qt 5.15.6
Debugging mode is disabled.

Operating system: macOS 12.6
CPU architecture: arm64
Kernel: darwin 21.6.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.19.2

**Comment by droidmonkey** [comment] 2022-12-31 15:08
That is extremely odd. So the only real defect here is that the expected quick unlock view is not shown, but quick unlock still works.

**Comment by KORraNpl** [comment] 2022-12-31 18:05
Yeah, I agree that it's very odd. Initially, I thought that it requires both password AND Touch ID to unlock a db, so I suspected that it might be a desired behaviour, but after realizing that any password works, I was sure it's a defect.

Anyway, if you need anything in terms of reproduction, please let me know. I love KeePassXC and recent addition of quick unlock feature is a great idea!

**Comment by mikes625** [comment] 2023-01-10 23:59
I can confirm this issue on my intel macbook air, OS 13.1. No master password required, just hitting return brings up the quick unlock popup. Never noticed it because I normally lock the db manually before shutting the lid.

**Comment by joh-klein** [comment] 2023-04-04 15:09
I have this issue as well – I cant unlock the database anymore with the master password without touch-id. This is rather annoying, since I have an issue with my skin right now, were touch-id only sometimes works :(

**Comment by b0n0r** [comment] 2023-05-09 17:41
have seen this behaviour at coworker's mac too:
- unlock database while using the laptop without external monitor & keyboard, everything works
- close the lid of the laptop
- connect external monitor & power & bluetooth keyboard ("clamshell mode")
and you end up stuck, unable to unlock the database since it asks for fingerprint but that sensor is in the closed laptop :)

you have to close the db tab in the app and reopen (and unlock with master pw) the db to be able to use it.

UPDATE: actually my scenario is more like #9034 / #9032 which was just fixed in the fresh [release 2.7.5](https://github.com/keepassxreboot/keepassxc/releases/tag/2.7.5) 👍 😎

**Comment by KORraNpl** [comment] 2023-08-16 08:20
I know that this issue is assigned to 2.8.0, but I noticed there were some changes in 2.7.6 related to Quick Unlock, so I retested the issue and it's still there. Just my QA habit ;)

**Closed as completed** 2024-03-08 15:55 UTC
Labels: platform: macOS, feature: QuickUnlock
