### ISSUE TITLE
Global auto-type does not handle multiple databases well

### ISSUE THREAD

**Issue by dnel** [keepassxreboot/keepassxc#1893] opened 2018-05-02 10:10 UTC
I use two keepass databases for personal and work credentials, and I make regular use of the global auto-type key but I've found this provides poor handling of more than one database.

## Expected Behavior

If both databases are locked, provide a means to quickly select which database to unlock.

If any of the databases are locked, and credential search fails, provide an unlock dialogue instead of a flat failure message.

## Current Behavior

If both databases are locked the unlock database window appears allowing you to unlock one database, its choice of which database is random to me, maybe the last one used?

If the credentials required are in a locked database but other databases are unlocked, the just search fails after searching the wrong database.

## Possible Solution
Get rid of the separate unlock dialogue and just maximise+focus the main application window with a error message so you can get straight to unlocking the required database. 

Only when all databases are unlocked, display the search fail dialogue as a separate pop-up window.

## Steps to Reproduce (for bugs)
1. Open two databases
2. Unlock one of the databases
3. Go to a site using credentials in the locked database
4. Use global short-cut key

## Context
I have to close the dialogue, manually re-maximise the main application window and unlock the required database then try again. This process happens several times a day between locking and returning to my computer and the whole process could be streamlined.

## Debug Info
KeePassXC - Version 2.2.2
Revision: 6d46717

Libraries:
- Qt 5.9.1
- libgcrypt 1.8.1

Operating system: macOS High Sierra (10.13)
CPU architecture: x86_64
Kernel: darwin 17.5.0

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

**Comment by TheZ3ro** [comment] 2018-05-21 07:35
Duplicate of #476

**Closed by TheZ3ro** 2018-05-21 07:35 UTC
