### ISSUE TITLE
better icloud synchronization

### ISSUE THREAD

**Issue by psifertex** [keepassxreboot/keepassxc#8863] opened 2022-12-04 15:47 UTC
## Summary
icloud syncing is broken out of the box and requires [a setting](https://github.com/keepassxreboot/keepassxc/issues/6072) that is not very discoverable. It should at a minimum be set by default for databases saved to icloud, or should support better integration

## Examples
No UI needs to change. The backend merely needs to [detect](https://stackoverflow.com/questions/21094534/how-do-i-verify-a-files-existence-in-icloud) whether a database is saved in icloud and use the alternate saving method

The actual fix is probably to make better use of the cloud APIs to still keep a backup but properly re-create the databse .

## Context
This is a super important feature for _any_ new user who is using icloud as they won't otherwise be able to use keepasscsx to sync with any other compatible solution (I'm using keepassiumXC on mobile) as it will result in constant de-syncs and alternate files.

**Comment by droidmonkey** [comment] 2022-12-04 16:02
I'm not sure what the problem is here but I just tested saving with iCloud. I made a series of auto saved edits with the default saving method and nothing misbehaved. The issue you referenced is 2 years old...

**Comment by psifertex** [comment] 2022-12-05 07:14
The issue happened for me just this morning though the exact text is different in the settings now compared to the previous issue. Here's what I had to change.

Well, I tried to take a screenshot to show the setting but keepassxc blocks it. Cute but unhelpful. If no passwords are shown on screen maybe consider allowing them as it's annoying to show bugs.

```
Use alternative saving method (may solve problems with Dropbox, Google Drive, GVFS, etc.)

Changed to "Directly write to database file (dangerous)"
```

Did you test opening/changing with another tool that accessed the same file? I use Keepassium on mobile and KeePassXC on desktop. I wonder if making changes in both at the same time is required? Or maybe it's related to whether icloud is set to full sync or not? All I know is that I had to change this setting once before when I first converted to keepass, forgot about it, then when I needed to reinstall a few weeks ago I accidentally started having the same problem happen again.

**Comment by droidmonkey** [comment] 2022-12-05 12:13
iCloud works like other cloud sync services, there is a local copy of files managed by an agent. Some files are downloaded on-demand and the agent detects changes and downloads or uploads the file depending on what happens.

Keepassium might be strong binding to a specific file node instead of by name which can cause issues. I think that was a problem a while ago. Either way, keepassxc treats the file in icloud as any other file (which it ahould) and we default to safe saves which is the right thing to do.

**Comment by psifertex** [comment] 2022-12-05 16:59
Can't speak to the code just to my experience which has consistently been broken through two re-installs if I'm using stock settings and Keepassium on mobile and XC on desktop with icloud sync. It's this kind of rough edge that will make me head back to 1p as much as I dislike their business model. :-( 

I don't blame you if you feel the defaults are doing the right thing. I'm just trying to describe how as a user the current defaults could lead to what feels like a broken experience and would be difficult to resolve for a less technical user. Feel free to close as won't-fix if you do not believe that this situation is common enough to warrant any special-casing or think there's something else at play that's unique to my configuration (I'd disagree, but not be offended at all if you do).

**Comment by droidmonkey** [comment] 2022-12-05 17:28
I am willing to hear if anyone else has the same experience as you. I believe you are the first one on this forum to post about consistent failures with iCloud. We don't want to degrade the save setting based solely on "is in iCloud", so that part is a wontfix. However, we should be handling files better and providing better error messages if this is truly a problem. Already if the safe saves fail three times, you will be prompted to disable safe saves. To me it doesn't seem like the saves are failing but temporary files are being left behind in your iCloud.

**Comment by psifertex** [comment] 2022-12-05 17:38
That's correct. I've had the files renamed from underneath me without a warning on desktop. On mobile the database disappears and before I realized what happened I manually opened back up the new file since I assumed the higher number was better and accidentally began making changes to the two files separately. That's how I re-discovered after this reinstall that there was an issue again. Changes were no longer syncing as each application was changing a different file.

**Comment by droidmonkey** [comment] 2022-12-05 17:41
Let me parrot that back to make sure I understand:

You saved the file on desktop, then you saw the temp file on mobile and opened it, made changes, then saw the temp file on desktop again?

If the above is true then the easy fix is just to not open the temp file on mobile.

**Comment by psifertex** [comment] 2022-12-05 19:36
Unfortunately it's been several days and passwords being a strong part of my normal workflow mean it's hard to separate out what happened when, but here's what I recall:
- I have generally made some amount of changes to both mobile and desktop over the past few weeks
- At some point a new numbered copy was created and the original file link was broken on mobile where I had to select the database again. I assumed the highest numbered copy was the "correct" one and selected that. 
- This resulted in desktop and mobile mis-syncing

So, yes! If I ignored the new files being created and when asked to re-open always open the original file name I believe you're right and it would fix the issue. The problem is -- how does a new user know this is the correct behavior? Especially when the timestamps don't actually help there? I know this now, but I'm not filing this issue for me, I'm filing it for future users for whom it would be good to have a smoother workflow since they might not even realize they're creating changes in two different databases for some time.

**Comment by droidmonkey** [comment] 2022-12-05 23:00
Ahhhhh ok so you had a _conflict_ file get created in iCloud. The correct sequence would be to merge the numbered file into the main database file and delete the numbered file. We cannot protect against conflict files, even the unsafe saves will produce them if you don't allow your files to fully sync before editing them.

**Comment by psifertex** [comment] 2022-12-05 23:04
How do I know that will happen? Is this some part of the UI I've been not noticing?

**Comment by droidmonkey** [comment] 2022-12-05 23:13
It's part of the sync agent process, it has nothing to do with KeePassXC. If you edit the file before it has pulled down the latest version it will create a conflict file. The same applies to word documents and other binary files you use in iCloud.

**Comment by Christian-Nerd** [comment] 2022-12-10 04:00
You need to just look at settings, and this is a niche feature just disable safe settings! The solution to your problem is a blog on keepassxc.org okay!

**Closed as completed** 2023-05-02 20:13 UTC
Labels: not reproducible, platform: macOS

**Comment by tkafka** [comment] 2025-11-09 13:22
I just got bitten by this - KeepassXC deleted the passwords file, there was no conflicting version. 

I have tried setting "Use alternative saving method" to "Directly write to file (dangeours)" - is this how the option is called now?

**Comment by droidmonkey** [comment] 2025-11-09 13:26
Yes that is the option.

**Comment by tkafka** [comment] 2025-11-09 21:45
Thanks. Can we reopen the issue then? I would have just lost my data if I wasn't looking soon enough to still find them in iCloud recovery.

The issue is that with the default settings, KeePassXC will cause your password file to be deleted when using iCloud for syncing.

**Comment by droidmonkey** [comment] 2025-11-09 22:33
The default settings are there for a reason, almost all services behave correctly. We have this setting documented in our user guide and in the settings page itself. Using a cloud sync service has the main benefit of version history and recovery of deleted objects. You should always keep a deep copy backup as well periodically.

FWIW many many people use iCloud for syncing KDBX files without issue. I do not think there is actually a problem with iCloud syncing. Please verify or replicate the scenario to confirm your assertion.

I just tried saving KDBX to iCloud and it worked flawlessly over the course of 15+ saves without using direct-write saving.

**Comment by tkafka** [comment] 2025-11-10 12:48
One might read `almost all services behave correctly` as `we know some services will lose user's data with this setting, and we are okay with that`. No one reads the documentation. I am a developer and I didn't.

Do you think KeepassXC could detect such situation (iCloud as a storage) and warn about the situation (an maybe let the user turn this setting on directly from the warning dialog)?

It certainly tricky to reproduce, but since MacOS Tahoe, I have found the passwords.kdbx file deleted two times so far.
