### ISSUE TITLE
YubiKey doesn't work on Appimage version 2.2.1

### ISSUE THREAD

**Issue by cldebuhr** [keepassxreboot/keepassxc#1034] opened 2017-10-05 03:41 UTC
I had initially commented on this in the comments for issue #693 (YubiKey doesn't works on Snap version).  I probably should have opened a new issue instead at that time.  I was hoping the issues were related and similar enough that I could just wait for 2.2.1 ... The observed behaviour in the 2.2.1 appimage is identical to that documented in #693 for the 2.2.0 Snap version.

## Expected Behaviour
When unlocking a database or changing/creating a master key, the Yubikey should show up in the list of devices in the "Challenge-response" section.

## Current Behavior
The Yubikey is not visible in the list of devices (the device list is empty).  No amount of plugging/unplugging/ or pressing the "refresh" button will change this.  The Yubikey has been configured with a valid challenge response credential in slot #2.

## Steps to Reproduce (for bugs)
1. Start KeepassXC
2. Plug in Yubikey (steps 1 and 2 are interchangeable)
3. Create new DB, or open existing DB
4. Yubikey is not available for challenge response authentication

## Context
Challenge-response authentication is a major enhancement to KeepassXC, but at the moment seems to be unavailable to Appimage users.

## Debug Info
KeePassXC - Version 2.2.1
Libraries:
- Qt 5.9.0
- libgcrypt 1.6.1

Operating system: Linux Mint 18.2
CPU architecture: x86_64
Kernel: linux 4.10.0-35-generic

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

**Comment by jamm3r** [comment] 2017-10-07 05:57
Same problem here.
Tried installing libpam-yubico as for the snap thread, but no improvements.

## Debug Info
KeePassXC - Versione 2.2.1
Librerie:
- Qt 5.9.0
- libgcrypt 1.6.1

Sistema operativo: Linux Mint 18
Architettura CPU: x86_64
Kernel: linux 4.4.0-93-generic

Estensioni abilitate:
- KeePassHTTP
- Auto-Type
- YubiKey

**Comment by droidmonkey** [comment] 2017-10-08 01:29
Ping @phoerious

**Comment by phoerious** [comment] 2017-10-08 07:32
I will look into it.

**Comment by MyWay** [comment] 2017-10-11 08:58
Same on Ubuntu with snap and --devmode.

**Comment by droidmonkey** [comment] 2017-10-11 10:41
This was fixed in the snap. did you read the snap tips in wiki

**Comment by phoerious** [comment] 2017-10-12 12:02
Okay, this problem is becoming ugly. It's caused by the bundled libykpers-1.so.1 library. With it, the YubiKey isn't detected, without it, it works, but only if another version is installed on the host system. Otherwise KeePassXC won't start. Bundling more dependencies of libykpers doesn't make the problem go away. Bundling libusb has no effect, bundling libc or libpthread makes KeePassXC crash and is generally not a good idea.

**Comment by phoerious** [comment] 2017-10-21 22:01
Fixed in #1100

**Closed by phoerious** 2017-10-21 22:01 UTC
Labels: distribution, yubikey
