### ISSUE TITLE
firefox addon keeps saying keepassxc is out of date?

### ISSUE THREAD

**Issue by JackDinn** [keepassxreboot/keepassxc#1935] opened 2018-05-10 09:45 UTC
Im using Manjaro and wanted to try keepassXC, I use pacman -S keepassxc and then installed the firefox addon but the addon keeps saying keepassxc is out of date?

First i installed the
community/keepassxc 2.3.1-1

then built & installed with
aur/keepassxc-git 2.3.3.r48.gb02bd59e-2

then i went to https://www.archlinux.org/packages/community/x86_64/keepassxc/ and installed
❰greg❙~❱✘≻ yaourt -U Downloads/keepassxc-2.3.3-1-x86_64.pkg.tar.xz

But none of these will stop saying its out of date (wrong version) ?

![screenshot_20180510_015704](https://user-images.githubusercontent.com/5557560/39863564-ef9f33ac-543e-11e8-9b8b-271ebc4373af.png)

If i click the link in the warning message pop-up it takes me to the keepassxc site and for arch (it has no Manjaro) it just says sudo pacman -S keepassxc which installs the community/keepassxc 2.3.1-1 again, im just going round in circles :confused:

EDIT:- checking the addons settings it has a “check update” section where it states my keepassxc is up to date

![screenshot_20180510_021724](https://user-images.githubusercontent.com/5557560/39863593-0485f350-543f-11e8-8746-1d2f47e3b78c.png)

**Comment by phoerious** [comment] 2018-05-10 10:37
Duplicate of https://github.com/keepassxreboot/keepassxc-browser/issues/140

**Closed by phoerious** 2018-05-10 10:37 UTC
Labels: duplicate
