### ISSUE TITLE
KeePassXC not starting with last Database

### ISSUE THREAD

**Issue by salvelinus1** [keepassxreboot/keepassxc#2196] opened 2018-08-13 12:56 UTC
Using KeePassXC 64bit portable, with automatic start on Windows 8.1 x64 start, with KeePassXC minimized to tray icon.
KeePassXC Options are set to load last used database when starting KeePassXC.

## Expected Behavior
Clicking on the tray icon to open a database window should immediately open the window which asks for password input.

## Current Behavior
The above described behaviour is shown only from 2nd time when tray icon is clicked. 
1st time, KeePassXC never shows password input window, but the window prior to password input, where database(s) used in sessions before are shown. Clicking on the (or one of the) shown database(s) then starts the password input window.
Same problem if I try from KeePassXC-Browser icon (within Cyberfox): 
"Reopen database" command doesn't work (=doesn't do anything at all) if it is the 1st time KeePassXC is to be opened from its tray icon mode, but same command works from 2nd time on, then by correctly starting the KeePassXC password input window. 

## Debug Info
KeePassXC - Version 2.3.3
Revision: 0a155d8

Bibliotheken:
- Qt 5.10.1
- libgcrypt 1.8.2

Betriebssystem: Windows 8.1 (6.3)
CPU-Architektur: x86_64
Kernel: winnt 6.3.9600

Aktivierte Erweiterungen:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

Many thanks!

**Comment by droidmonkey** [comment] 2018-08-14 01:39
I had a hard time following your launch sequence. Is KeePassXC already running and you click the tray icon to open it? Are you closing the databases prior to closing KeePassXC (ie, closing the tabs)?

**Comment by salvelinus1** [comment] 2018-08-14 12:49
Many thanks for your prompt answer!

Yes, KeePassXC starts with Windows start and sits in the tray. I open it either by clicking the tray icon or the KeePassXC-Browser button in Cyberfox. Results are as described, i.e. irregular behaviour (to my mind) when doing this 1st time, regular reaction from 2nd time on, until new Windows start.

Closing is always done NOT by closing the database(s), but simply by closing the whole window, clicking on the X button in the upper right edge (or by Alt+F4).

Hope this helps to understand the issue.
Thanks again, best...

**Comment by droidmonkey** [comment] 2018-08-14 14:07
Ok, I will try to replicate. Just to be certain, you have "Start minimized" and "Minimize to tray" both enabled?

**Comment by salvelinus1** [comment] 2018-08-14 20:32
Thanks!

Yes, screenshot attached...
![keepassxc options](https://user-images.githubusercontent.com/42345342/44116831-dcb7ac0a-a011-11e8-8181-7d74520391f8.JPG)

**Comment by droidmonkey** [comment] 2018-10-24 19:48
I cannot reproduce this issue at all. If it is still a problem please comment here.

**Closed by droidmonkey** 2018-10-24 19:48 UTC
Labels: in triage
