### ISSUE TITLE
Libsecret integration not working with Nextcloud when not exposing root

### ISSUE THREAD

**Issue by virtualdxs** [keepassxreboot/keepassxc#4894] opened 2020-06-21 18:11 UTC
## Overview
When exposing only a subfolder rather than the root, each time Nextcloud starts, it adds two entries to the database (one plaintext and one base64). Normally, it should do this on first start, then fetch the stored ones on future starts.

## Steps to Reproduce
1. Configure KeepassXC to expose a subfolder in an open database to libsecret clients
2. Start nextcloud
3. Authenticate nextcloud
4. Stop nextcloud (make sure it's actually killed)
5. Start nextcloud again

## Expected Behavior
Nextcloud starts and synchronizes without asking for auth

## Actual Behavior
Nextcloud starts the authentication flow again

## Context
My guess is the subfolder name is being used in the path presented to clients somehow. I would expect that if I expose only a subfolder that subfolder is the root for all libsecret requests.

```
KeePassXC - Version 2.5.4
Revision: dcca5aa

Qt 5.15.0
Debugging mode is disabled.

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 5.4.47-1-lts

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.5
```

Operating System: Arch Linux
Desktop Env: dwm
Windowing System: X11

**Comment by klorax** [comment] 2020-10-23 13:44
This is mentioned on Nextcloud as well: https://github.com/nextcloud/desktop/issues/2303

@blacktemplar mentions a workaround (autostarting the following script):

```shell
#!/bin/bash

while ! $(secret-tool lookup Title Nextcloud &> /dev/null); do
	echo "wait"
	sleep 1s
done

/usr/bin/nextcloud --background
```

It can also be started manually and will correctly find the secrets even if not in the database root.

**Comment by droidmonkey** [comment] 2020-10-23 16:10
Closing as this is a next cloud issue

**Comment by virtualdxs** [comment] 2020-10-23 23:07
Wait, what? Pretty sure that's an unrelated issue. Once I get a chance, I'll test it again while making sure KeepassXC is started first and report back here

**Comment by droidmonkey** [comment] 2020-10-24 01:28
Reading the nextcloud issue leads me to believe it is directly related

**Comment by blacktemplar** [comment] 2020-10-24 10:47
I also think that this issue is different to the nextcloud one. I don't know if its a nextcloud problem or a keepassxc problem but the issues are different:

In this issue keepassxc is always unlocked and Nextcloud gets restarted.

In issue nextcloud/desktop#2303 Nextcloud gets started BEFORE keepassxc is unlocked, then keepassxc gets unlocked but nexcloud already asked for credentials and can't automatically access the credentials.

**Comment by klorax** [comment] 2020-10-24 11:02
Sorry, I think these are two different issues, but the workaround seems to work for both:
manually using `secret-tool lookup` handles the KeePassXC root issue and the `while/sleep` handles the Nextcloud issue.

**Comment by droidmonkey** [comment] 2020-10-24 11:09
It still seems like a next cloud issue, does any other software exhibit the same problem?

**Comment by Aetf** [comment] 2020-11-16 03:45
It will be really helpful to see what's really going on here. Could anyone run the following command before starting Nextcloud and keep it running and report the output?

```
dbus-monitor "destination=org.freedesktop.secrets" "sender=org.freedesktop.secrets"
```
This will record all dbus messages related to the secret service. So we can know for sure what happened.

Of course, the output needs to be edited to not leak your actual secret (It should suffice to remove the parameters from the open session call, because later messages are encrypted using the key negotiated in that call).

**Comment by phoerious** [comment] 2020-11-18 09:47
It's most certainly a Nextcloud issue. I had the same ages ago with KWallet. I left a comment under the Nextcloud issue and am closing this for now.

**Closed by phoerious** 2020-11-18 09:47 UTC
Labels: more info needed, plugin: Secret Service, upstream

**Comment by virtualdxs** [comment] 2020-11-19 16:40
I just verified that this still occurs with keepassxc pre-opened. In addition, I have discovered that I get the same behavior from `secret-tool lookup`. Reproduction steps:

1. Create a libsecret test entry in root (I have one with attribute test, value test, password open)
2. Expose root via libsecret
3. Run `secret-tool lookup test test` and observe that it prints `open`.
4. Move the libsecret test entry to a dedicated libsecret folder
5. Change the database to expose that folder
6. Run `secret-tool lookup test test` and observe that it returns 1.

Dbus traces for success and failure:

[dbus-secrettool.txt](https://github.com/keepassxreboot/keepassxc/files/5568333/dbus-secrettool.txt)
[dbus-secrettool-fail.txt](https://github.com/keepassxreboot/keepassxc/files/5568334/dbus-secrettool-fail.txt)

**Comment by Aetf** [comment] 2020-11-19 17:05
Can confirm there is indeed some bug about connecting to `nullptr` after the Item is moved and while changing the exposed folder of the database. The result is the database is actually no longer exposed at all, thus the `secret-tool lookup`failure. If you open keepassxc in the terminal, there should be lines similar to the following
```
QObject::connect(Group, Unknown): invalid nullptr parameter
QObject::connect(FdoSecrets::Item, FdoSecrets::Collection): invalid nullptr parameter
```
However, if you disable and reenable the the plugin, or restart keepassxc after step 5, `secret-tool lookup`should be able to find the entry.

@virtualdxs can you verify that if you restart keepassxc after step 5, `secret-tool lookup` can prints `open` as expected?

**Comment by virtualdxs** [comment] 2020-11-19 17:22
Unfortunately not. After stopping keepassxc, starting it, and re-unlocking the database, secret-tool still fails.

[dbus-secrettool-fail-2.txt](https://github.com/keepassxreboot/keepassxc/files/5568589/dbus-secrettool-fail-2.txt)

**Comment by Aetf** [comment] 2020-11-19 17:29
Hmm... then there must be something else going on. Did you see anything if you start keepassxc from the terminal? Also, could you share your database file if it's a test one. Or if not, could you reproduce it (and test the restart workaround) using a new database file?

Another way to diagnose is to see if the entry is actually exposed on DBus or not:
```
dbus-send --session           \
  --dest=org.freedesktop.secrets \
  --type=method_call          \
  --print-reply               \
  /org/freedesktop/secrets/collection/pw       \
  org.freedesktop.DBus.Introspectable.Introspect
```

**Comment by virtualdxs** [comment] 2020-11-20 05:30
Upon testing vigorously, I found that it works fine after deleting the libsecret folder I had and creating a new libsecret folder. Same name. Since I can no longer reproduce, we can leave this closed.
