### ISSUE TITLE
Feature request: support storage of secrets and generation of TOTP tokens

### ISSUE THREAD

**Issue by ChristopherSchultz** [keepassxreboot/keepassxc#563] opened 2017-05-11 13:46 UTC
TOTP is used as a second-factor in many services (e.g. Google, GitHub, etc.) and I tend to store my TOTP secrets in KeePass in case I need to re-load my secrets into e.g. Google Authenticator app on my phone.

When I'm on a real computer, I'd prefer to use KeePass as my TOTP token-generator instead of having to unlock my phone and run the app just to get a token.

The TOTP algorithm is trivial, and would be a nice feature to add, possibly as an optional plug-in to KeePass.

I'm not suggesting that it be stored/generated along with the password but perhaps could be used in conjunction with the auto-type feature when manually-configuring the auto-type text (e.g. "{USERNAME}{TAB}{TOTP_TOKEN}{PASSWORD}") because most TOTP-based 2FA schemes use different techniques to gather the password. For example, Google services ask for username/password on one form, and, once authenticated with that initial factor, the second factor is requested on a second form.

**Comment by TheZ3ro** [comment] 2017-05-11 14:01
This is a duplicate of #80. This feature is already available in develop and will be released in version 2.2.0 of KeePassXC

**Closed by TheZ3ro** 2017-05-11 14:01 UTC

**Comment by ChristopherSchultz** [comment] 2017-05-11 15:06
Apologies for the noise! Nice to see that (a) others want this feature, too and (b) it's been implemented. I'll check-out the dev version.
