### ISSUE TITLE
adding additional fields when importing

### ISSUE THREAD

**Issue by jeroen7s** [keepassxreboot/keepassxc#1831] opened 2018-04-10 08:53 UTC
I have a custom field in my CSV file from bitwarden which i would like to import, but there only seems to be an option to add aditional fields to keepass to import, only to map fields to the standard fields

## Expected Behavior
I should be able to add a field to import, in this case I have stored TOTP keys in my csv-file, but I'm unable to import them

## Current Behavior
you can only import fields that are:
- group - title - username - password - url - notes - lastmodified - created

## Possible Solution
add an option to add an additional field, 
which would be added to "Advanced" -> "Additional Attributes"

## Steps to Reproduce (for bugs)
1. import csv
2. map csv fields to correct keepass fields
3. find there's no option to import additional fields that are not standard keepass fields

**Comment by eleith** [comment] 2018-04-23 04:38
duplicate of https://github.com/keepassxreboot/keepassxc/issues/406

**Closed** 2018-04-23 15:54 UTC
Labels: duplicate
