### ISSUE TITLE
Strange behavior when open latest version

### ISSUE THREAD

**Issue by faizalsb** [keepassxreboot/keepassxc#8677] opened 2022-10-27 05:19 UTC
Strange behavior when open latest version
Automatically text "is:expired-3" in the search form.

## Expected Behavior
Normal window with preselect ROOT folder

## Actual Behavior
Search result window with text "is:expired-3" in the search form.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.3
Revision: d8483d3

[NOTE]: # ( Pick choices based on your environment )
Operating system: Windows 7 Version 6.1 (Build 7601: SP 1)
CPU architecture: x86_64
Kernel: winnt 6.1.7601

**Comment by traviss64** [comment] 2022-10-27 05:58
Yes same issue I am facing.

**Comment by varjolintu** [comment] 2022-10-27 06:48
Duplicate of #8626.

**Closed as not planned by varjolintu** 2022-10-27 06:48 UTC
