### ISSUE TITLE
Don't error out when duplicate attachments are found

### ISSUE THREAD

**Issue by beks6** [keepassxreboot/keepassxc#2493] opened 2018-11-20 10:57 UTC
## Expected Behavior

Database should open

## Current Behavior

Database won't open in KeePassXC on MacOS 10.14.1 with "Duplicate attachment found" error

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

We are using the Database over smb access on several macOS Computer. Opening the database in other programs like KeeWeb or MacPass is working fine. Only KeePassXC is causing this problem.
How can we solve this issue? We also exported the DB to .xml from KeeWeb but searching in a DB with over 100 pw is causing headaches :)

## Debug Info

KeePassXC - Version 2.3.4
Revision: 6fe821c

Libraries:
- Qt 5.9.3
- libgcrypt 1.8.2

Operating system: macOS 10.14
CPU architecture: x86_64
Kernel: darwin 18.2.0

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by droidmonkey** [comment] 2018-11-20 12:29
Here is the offending code block:

https://github.com/keepassxreboot/keepassxc/blob/82bf00de7389db3e52baf11c9295300ad943c643/src/format/KdbxXmlReader.cpp#L873-L881

In my opinion this should not raise an error, only a warning (or perhaps silently remove the duplicate attachment). If it is truly duplicate there won't be data loss.

**Comment by beks6** [comment] 2018-11-20 12:46
The point ist we get the warning, but Database won't open.
We investigated also a bit deeper into the problem. The DB is on our share and it seemed the *.kdbx file got corrupted. We even aren't able to configure permissions on the file. Luckily we have version control on our share and have been able to restore the last save. Will inform you if we find more to this problem, but it seems not to be a bug.

But still wondering why KeeWeb or MacPass have been able to open the DB.

Thanks for the fast response

**Comment by droidmonkey** [comment] 2018-11-20 13:37
Those other apps are either not doing format checks on open or they are not caring about duplicate attachments. To me its a bug because its an easily fixed error that cannot be fixed because we bail out.

**Comment by beks6** [comment] 2018-11-20 13:44
It could also be possible, that this bug is popping up falsely due to a unhandled exception?

We think so because we have no more access to the file, we can't even move it to another folder and we can't manipulate the security privileges. Even with our Admin Domainaccounts we are not able to manipulate the file permissions.

To be mentioned, the DB file is on a Windows share and we are accessing it from macOS through smb.

**Comment by phoerious** [comment] 2018-11-20 18:06
We don't use exceptions, but it's possible that the error message itself is misleading. Does it help when you save back the file in one of the other applications that allow you to open it? Perhaps try converting between kdbx3 and kdbx4 (and then back).

**Comment by beks6** [comment] 2018-11-20 20:17
Will give it a try tomorrow.

**Comment by beks6** [comment] 2018-11-21 14:03
OK guys, it's now getting a serious problem. Yesterday we exported the last working version to another location on the share. Today we made some new entries to the db and now we get again the duplicate warning and are not able to open the database in KeePassXC. I'm wondering what is causing this problem

**Comment by droidmonkey** [comment] 2018-11-21 15:16
Are you using all three apps to access this database? (KeeWeb, MacPass, and KeePassXC)

**Comment by beks6** [comment] 2018-11-21 15:35
Until last week we had no problems with this usecase. But since last week only KeePassXC is a bit offended and we struggle in finding to root of the problem.

@phoerious could give me a detailed example how to do this? I tried to check the xml exported from KeeWeb, but the exported xml is not formatted properly and we have more than 100 entries. You could imagine how long it takes to format it properly and check the entries.

Yesterday after restoring the database we already checked our entries for attachments and there are only two or tree entries with an attachment in the database and today nobody added an attachment, just normal pass entries.

**Comment by phoerious** [comment] 2018-11-21 18:14
You find build instructions here: https://github.com/keepassxreboot/keepassxc/wiki/Building-KeePassXC

**Comment by beks6** [comment] 2018-11-22 09:57
Another maybe important notice, the Windows Version KeePass2 v2.38 is also able to open the database. So it's only affecting KeePassXC, but I can't really say what we changed in our usecases. The last update installation is weeks ago.
Still struggling a bit getting the cli to run :)

**Comment by phoerious** [comment] 2018-11-22 10:36
Your database is most likely inconsistent, but the other programs are less strict about it.

**Comment by beks6** [comment] 2018-11-22 12:41
ok, I exported now the DB from the Windows client into xml. any hint where to start searching? xml has 57145 rows :)

**Comment by phoerious** [comment] 2018-11-22 12:49
Search for `<Binaries>` or `<Binary>`

**Comment by beks6** [comment] 2018-11-22 20:31
OK, I think I've found the bastard. The `<Binary>` IDs are unique but searching further led to two `<Binary>
	<Key>Mc_Shark_LIWEST_4061.pdf</Key>
	<Value Ref="0" />
</Binary>`

entries with identical Key and Value entries. What's best practice resolving this issue?

**Comment by droidmonkey** [comment] 2018-11-22 21:45
Ahhh, this may be a bug

**Comment by droidmonkey** [comment] 2018-11-22 22:47
So the IDs are unique, that is fine. What matters here is that the _BLOB_ sections must be unique as well. Is their duplicate of the actual attachment data?

**Comment by beks6** [comment] 2018-11-23 07:47
I assume, the _BLOB_ data is the hash between `<Binary ID="0" Compressed="True">_BLOB_</Binary>`

If so, I copied the 4 entries each in a separate file (over 300 000 chars), but they seem all to be different

**Comment by beks6** [comment] 2018-11-23 08:51
KeePassXC is now able to open the DB, but as I already mentioned. I think the warning/message is maybe misleading and caused by another bug.

I'll keep you informed

**Comment by rmiller-sgntr** [comment] 2018-12-05 14:57
Hi, I am having this issue as well, working on a shared DB, all my colleagues are using Mac and can use the file, but I am using Ubuntu 18.04 and cannot open it with the `duplicate attachment` error.

Any progress on this?

**Comment by droidmonkey** [comment] 2018-12-05 15:13
Are you ALL using KeePassXC or are some using another application?

**Comment by rmiller-sgntr** [comment] 2018-12-05 15:42
My colleagues use MacPass, I get the same error on both KeePassXC and KeePassX (kinda stating the obvious).

**Comment by droidmonkey** [comment] 2018-12-05 16:02
I think the root cause of this is MacPass, to be honest. That is the common thread (besides KeePassXC and a team environment) between you and beks6. Why can't everyone just use KeePassXC?

**Comment by rmiller-sgntr** [comment] 2018-12-05 17:10
So assuming this issue will resolve once macpass users update to the version with the fix?

**Comment by droidmonkey** [comment] 2018-12-05 17:17
You'll need to address that question to the MacPass owner

**Comment by droidmonkey** [comment] 2020-06-02 19:19
I fixed this issue, but fwiw this only impacts KDBX 3.x databases. Upgrading to KDBX 4.x will solve the problem.

**Closed** 2020-06-04 14:03 UTC
Labels: bug, ux
