### ISSUE TITLE
Show TOTP & lock screen & uplock screen -> KeePass unlocked

### ISSUE THREAD

**Issue by serebryakov-av** [keepassxreboot/keepassxc#2447] opened 2018-11-02 07:41 UTC
What to do:
1. Open keepass with TOTP.
2. Choose "Show TOTP" for entry -> timer will appear.
3. Lock screen for your computer.
4. Unlock screen.

Wrong behaviour:
- KeePass wouldn't be locked.

**Comment by weslly** [comment] 2018-11-02 13:30
Duplicate of #721

**Closed by weslly** 2018-11-02 13:30 UTC
