### ISSUE TITLE
Implement RFC 6238 Authenticator

### ISSUE THREAD

**Issue by MrDrMcCoy** [keepassxreboot/keepassxc#618] opened 2017-06-03 05:10 UTC
Feature request for an storing RFC 6238 authenticator secrets and generating codes in the UI. There is a distinct lack of open-source authenticators that can securely store and sync codes, and this would be a killer feature to have!

**Comment by TheZ3ro** [comment] 2017-06-03 09:43
This is a duplicate of #80. This feature is already available in develop and will be released in version 2.2.0 of KeePassXC

**Closed by TheZ3ro** 2017-06-03 09:43 UTC
