### ISSUE TITLE
Load ssh key into agent from entry contextual menu

### ISSUE THREAD

**Issue by francogu** [keepassxreboot/keepassxc#4007] opened 2019-12-11 07:30 UTC
## Summary
Add a new item in the contextual menu of an entry to load the ssh-key into the ssh agent.

## Desired Behavior
If an entry has a ssh-key associated, an additional entry in the contextual menu of the entry is available. When selected, it would load the associated ssh-key in the ssh-agent of Keepassxc.
Such functionality exist for KeeAgent plugin.

## Context
Due to load of ssh-key in the Keepassxc, we only use the auto-load feature for some of them.
When we want to load additional keys into the ssh-agent, we have to:
1. Edit the entry
2. Select the SSH-agent pane
3. Click on "Add to agent" button"
4. Then click "Ok" or "Cancel" button to finish the edition of the entry.
(Bonus, lots of mouse cursor distance or lots of key press)

In the contextual menu
1. Right click entry (or contextual menu key)
2. Select and click "load into ssh-agent"
(Short distance, few key pressed)

**Comment by hifi** [comment] 2019-12-20 04:29
Duplicate of #1815. This feature is in the pipeline for 2.6.0.

**Closed by hifi** 2019-12-20 04:29 UTC
Labels: new feature, plugin: SSH agent
