### ISSUE TITLE
Brackets in password break {TOTP}

### ISSUE THREAD

**Issue by tsohst** [keepassxreboot/keepassxc#11500] opened 2024-11-27 07:52 UTC
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
* I need to create an entry where the password is followed by an TOTP.
In the password field I've entered `myfancypassword{TOTP}` which should produce `myfancypassword1234`

**Unfortunately my password contains a `{` which breaks this concept.**

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
* Add a TOTP to your KeePassXC entry.
* Enter your password like this:
* `my{ancypassword{TOTP}` generates `my{ancypassword{TOTP}` (no numbers)
* `{my{ancypassword}{TOTP}` generates `{my{ancypassword}1234` (note the brackets)

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
* Generate `my{ancypassword1234`

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.9
Revision: 8f6dd13

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows

**Comment by droidmonkey** [comment] 2024-11-27 12:25
This is "by design" because you have a broken placeholder (the open curly bracket). For better or worse, keepass supported these placeholder options alongside regular text for any field, including password fields. I don't necessarily agree with it because of this issue you highlight, although it is rare to occur. 

The fix is simple as you mentioned, either close the open curly brace or replace the left curly with a right curly and be done with it.

Fixing this would have all sorts of potential issues due to the way placeholders are syntaxed and used in various ways. As a result, this is a "won't fix".

**Closed as not planned by droidmonkey** 2024-11-27 12:25 UTC

**Comment by tsohst** [comment] 2024-11-27 12:46
Just to post a workaround if anyone else will have this issue in the future:

* Create a entry with your password that contains the bracket
* Create a second entry with a refence in the password field `{REF:P@I:UUID of the first entry}{TOTP}`

**Comment by droidmonkey** [comment] 2024-11-27 12:54
You don't need two entries, you can use advanced attributes as well. Create an attribute in the same entry, name it "pw" for example, and set its value to your desired password. Then set your password to `{S:pw}{TOTP}`.

This is, of course, only if you absolutely need to have an open curly brace in your password in the first place.
