### ISSUE TITLE
app freezes when saving attachments

### ISSUE THREAD

**Issue by yeus** [keepassxreboot/keepassxc#5873] opened 2020-12-28 22:09 UTC
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
1. create new db
2. create new pw entry
3. add arbirary attachement to pw entry
4. save attachement back to disk

## Expected Behavior
should save the attachement

## Actual Behavior
app freezes while the savefile dialog is opened

## Context
- window can still be maximized/minimized
- but no other buttons work (e.g. can not close window, cancel, save etc...)

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.2
Revision: e9b9582
Distribution: Flatpak

Qt 5.15.2
Debugging mode is disabled.

Operating system: KDE Flatpak runtime
CPU architecture: x86_64
Kernel: linux 5.4.0-58-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.7

**Comment by yeus** [comment] 2020-12-28 22:15
ohh yeah, one interesting remark:  the "open" button works...  i can directly open the files on my system and also use that as a work around as the files get copied into `/run/user/<id>/app/org.keepassxc.KeePassXC/`

**Comment by phoerious** [comment] 2020-12-29 08:36
Doesn't sound like a "crash" to me.

**Comment by yeus** [comment] 2021-01-07 19:40
> Doesn't sound like a "crash" to me.

changed the title ;)

**Comment by phoerious** [comment] 2021-01-08 08:16
Does "while the savefile dialog is opened" mean you get back control after you close it or is the savefile dialogue also frozen?

**Comment by yeus** [comment] 2021-01-14 15:35
@phoerious: the savefile dialogue freezes as well, I can"t even close it. Only way is to forcefully kill the app process.

About NFS mounts: I dont have any..  so..  anything else that I could look out for :)?

I am using KDE, the savefile dialogue is the only one that looks different from the native dialogues (I guess a qt dialogue or something similar?). When opening  or saving a database I get the native file dialogues. The savefile dialogue also doesn"t seem to care about my KDE file-dialog settings (for example shortcuts) otherwisse I would have though that maybe that could be the reason...

and I was finally able to gather some error messges by startig the app form the commandline

these messages appear, as soon as I enter the savefile dialogue:

```
kf.solid.backends.udisks2: Failed enumerating UDisks2 objects: "org.freedesktop.DBus.Error.Disconnected" 
 "Not connected to D-Bus server"
```

The messages appears 20 times in a row. Any idea where to go from here?

**Comment by yeus** [comment] 2021-01-14 15:41
I found a bug which pretty much resembles my problem, it is apparently related to flatpak:

https://github.com/flathub/org.kde.kate/issues/1

if I understand it correctly they fixed this in the application itself (app: kate), so I wonder if we have the exact same problem here. This is how they fixed it:

https://invent.kde.org/utilities/kate/-/commit/5b5c32aa35ea16653421eb637eb407686696d2fd

**Comment by phoerious** [comment] 2021-01-14 15:55
This is not a bug on our side and we do not maintain the Flatpak at the moment. Please take your report to the Flatpak packages maintainer or use one of our official packages.

**Closed by phoerious** 2021-01-14 15:56 UTC
Labels: bug, distribution: flatpak

**Comment by yeus** [comment] 2021-01-14 16:00
@phoerious:  but apparently kate fixed that in the application itself, not in flatpak. The flatpak poeple say in that thread that it is not their problem. So in order to support flatpak, it should be possible to fix this in keepasssxc, right? Or I am missunderstanding something here.
