### ISSUE TITLE
Update error: "An error occurred in retrieving update information"

### ISSUE THREAD

**Issue by solt87** [keepassxreboot/keepassxc#5606] opened 2020-10-24 08:29 UTC
## Overview

When using KeepassXC Appimage (2.6.2, the newest as of this writing), checking for updates
fails with "Update error! An error occurred in retrieving update information. Please try again later."
This has been happening since the 2.6.1 Appimage version. Update detection worked with earlier
versions.

Incidentally, HIBP also fails (since 2.6.1, where it was introduced, I believe) with
"Online password validation failed: TLS initialization failed."

I keep re-checking, and my internet connection is fine.

## Steps to Reproduce

1. Open KeepassXC.
2. Open a database.
3. Select Help / Check for Updates

## Expected Behavior

KeepassXC should inform me whether there are any updates.

## Actual Behavior
I get an error message saying "Update error! An error occurred in
retrieving update information. Please try again later."

## Context
[NOTE]: # ( Give us any additional information you may have. )

KeePassXC - Version 2.6.2
Revision: e9b9582
Distribution: AppImage

Qt 5.14.2
Debugging mode is disabled.

Operating system: Linux Mint 20
CPU architecture: x86_64
Kernel: linux 5.4.0-52-generic
Desktop Env: XFCE
Windowing System: X11

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.1

**Comment by droidmonkey** [comment] 2020-10-24 11:19
I believe you need to install openssl

**Comment by droidmonkey** [comment] 2020-10-24 11:20
Duplicate of #4965

**Closed by droidmonkey** 2020-10-24 11:20 UTC
Labels: bug, distribution: AppImage

**Comment by solt87** [comment] 2020-10-24 11:51
I have the following SSL packages installed:

- libio-socket-ssl-perl
- libnet-smtp-ssl-perl
- libnet-ssleay-perl
- libssl-dev:amd64
- libssl1.1:amd64
- openssl
- perl-openssl-defaults:amd64
- python3-openssl
- ssl-cert

#4965 seems to be orignally reported against 2.5.4; I have been using KeePassXC for at least a year now, and update checking worked for me before 2.6.1. I wonder if the Mint 19 to 20 upgrade might have contributed to this, but KeePassXC 2.6.1 came more than a month after the Mint upgrade.

**Comment by n1n1n3sh4rk** [comment] 2021-04-03 09:22
I have the same error. I use appimage. KeePassXC 2.6.4. OpenSSL installed.
