### ISSUE TITLE
OTP not auto-closing / locking fatal crashing

### ISSUE THREAD

**Issue by t4777sd** [keepassxreboot/keepassxc#1664] opened 2018-03-07 03:41 UTC
When the OTP dialog is opened and the database auto-locks due to the timeout it does NOT close the OTP dialog. What you have left is a OTP dialog and a locked database. The OTP dialog no longer functions. Clicking any of its buttons causes keepass to crash.

## Expected Behavior
OTP dialog auto-closes when the database lcoks

## Current Behavior
OTP fails to auto-close when locking and instead crashes keepass

## Possible Solution
Close the OTP dialog when locking keepass

## Steps to Reproduce (for bugs)
1. Set a lock timeout for keepass such as 60 seconds
2. Open an entries OTP dialog
3. Wait 60 seconds for the database to lock
4. See the OTP dialog is still open. Click one of its buttons and keepass then crashes

## Context
The previous OTP dialog issue (not locking while OTP is open) was really annoying, so this is better and more secure. However, it is still annoying that the OTP dialog does not auto-close and that it instead crashes keepass eventually.

## Debug Info
KeePassXC - Version 2.3.1
Revision: 2fcaeea

Libraries:
- Qt 5.9.1
- libgcrypt 1.7.8

Operating system: Ubuntu 17.10
CPU architecture: x86_64
Kernel: linux 4.13.0-36-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by hifi** [comment] 2018-03-11 04:59
I can't reproduce the timeout lock but I can reproduce the issue if I set "lock on minimize" and minimize the window while the TOTP window is open. It doesn't crash but the modal TOTP dialog is still present but inanimate, it can still be closed.

**Comment by ya-isakov** [comment] 2018-03-17 22:14
Another issue - TOTP window prevents auto-locking the DB when screen is locked.

**Comment by droidmonkey** [comment] 2020-01-12 23:53
This is fixed in #4075

**Closed by droidmonkey** 2020-01-12 23:53 UTC
Labels: bug, user interface
