### ISSUE TITLE
A script in the extension "KeePassSC -Browser" is causing Firefox to slow down.

### ISSUE THREAD

**Issue by Aephir** [keepassxreboot/keepassxc#5171] opened 2020-07-25 08:41 UTC
## Overview
Recently (but I'm almost sure it started before upgrading to KeePass XC 2.6), Firefox has been throwing this error, and freezing. It will occasionally be a temporary fix to click "Temporarily disable" or "Stop it", but quite often the error banner just reappears within a second or two, and you cannot navigate further.

Screenshot of error message:
<img width="1572" alt="Screenshot 2020-07-24 at 15 08 18" src="https://user-images.githubusercontent.com/20152788/88452813-13a63d00-ce62-11ea-85dd-03f7da71edf2.png">

## Steps to Reproduce
1. With [KeePassXC firefox addon](https://addons.mozilla.org/en-US/firefox/addon/keepassxc-browser/?src=search) installed, navigate to website (not all, but e.g. this one: https://www.mdpi.com/journal/biomedicines/special_issues/Venoms).
2. You might need to scroll down, or just wait.
3. 

## Expected Behavior
That the KeePassXC Firefox extension does not crash Firefox.

## Actual Behavior
The KeePassXC Firefox extension does crash Firefox.

## Context
-

[NOTE]: # 
KeePassXC - Version 2.6.0
Revision: 0765954

Qt 5.15.0
Debugging mode is disabled.

Operating system: macOS 10.15
CPU architecture: x86_64
Kernel: darwin 19.5.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.5

Operating System: macOS 10.15.5
Firefox version: 78.0.2

**Comment by varjolintu** [comment] 2020-07-25 14:01
Duplicate of https://github.com/keepassxreboot/keepassxc-browser/issues/953.

**Closed by varjolintu** 2020-07-25 14:01 UTC
Labels: bug, duplicate

**Comment by Aephir** [comment] 2020-07-28 12:12
> Duplicate of [keepassxreboot/keepassxc-browser#953](https://github.com/keepassxreboot/keepassxc-browser/issues/953).

Oops, sorry!
