### ISSUE TITLE
Missing SettingsWidget qt header on develop branch

### ISSUE THREAD

**Issue by CPWeaver** [keepassxreboot/keepassxc#648] opened 2017-06-16 17:25 UTC
Hi,
   Just an FYI, I ran into an issue compiling from source on Debian. I can build the `2.1.4` tag just fine but `develop` branch gives me the following:

```
mkdir build; cd build; cmake ..; make -j 8



[ 60%] Building CXX object src/CMakeFiles/keepassx_core.dir/gui/KeePass1OpenWidget.cpp.o
[ 60%] Building CXX object src/CMakeFiles/keepassx_core.dir/gui/KMessageWidget.cpp.o
[ 61%] Building CXX object src/CMakeFiles/keepassx_core.dir/gui/LineEdit.cpp.o
[ 61%] Building CXX object src/CMakeFiles/keepassx_core.dir/gui/MainWindow.cpp.o
[ 61%] Building CXX object src/CMakeFiles/keepassx_core.dir/gui/MessageBox.cpp.o
[ 62%] Building CXX object src/CMakeFiles/keepassx_core.dir/gui/MessageWidget.cpp.o
[ 62%] Building CXX object src/CMakeFiles/keepassx_core.dir/gui/PasswordEdit.cpp.o
[ 63%] Building CXX object src/CMakeFiles/keepassx_core.dir/gui/PasswordGeneratorWidget.cpp.o
[ 63%] Building CXX object src/CMakeFiles/keepassx_core.dir/gui/SettingsWidget.cpp.o
/home/cweaver/dev/tools/keepassxc/src/gui/SettingsWidget.cpp:20:38: fatal error: ui_SettingsWidgetGeneral.h: No such file or directory
 #include "ui_SettingsWidgetGeneral.h"
                                      ^
compilation terminated.
[ 63%] Building CXX object src/CMakeFiles/keepassx_core.dir/gui/SearchWidget.cpp.o
[ 64%] Building CXX object src/CMakeFiles/keepassx_core.dir/gui/SortFilterHideProxyModel.cpp.o
src/CMakeFiles/keepassx_core.dir/build.make:1549: recipe for target 'src/CMakeFiles/keepassx_core.dir/gui/SettingsWidget.cpp.o' failed
make[2]: *** [src/CMakeFiles/keepassx_core.dir/gui/SettingsWidget.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:161: recipe for target 'src/CMakeFiles/keepassx_core.dir/all' failed
make[1]: *** [src/CMakeFiles/keepassx_core.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

Looks like the auto uic is missing that file for some reason? This is probably obvious to someone who's used to working in this tool chain but I'm not familiar.
 
## Expected Behavior
keepassxc should compile ok

## Your Environment
* KeePassXC version/commit used: `f817eaa`
* Qt version (e.g. Qt 5.3): 5.3.2
* cmake 3.0.2
* Operating System and version: debian jessie `3.16.0-4-amd64 #1 SMP Debian 3.16.43-2 (2017-04-30) x86_64 GNU/Linux`

**Comment by phoerious** [comment] 2017-06-16 18:24
Maybe a regression due to https://github.com/keepassxreboot/keepassxc/pull/549 ? @droidmonkey

**Comment by sainaen** [comment] 2017-06-16 20:07
I'm not very familiar with the cmake either, but I just tried building the same commit on Debian Testing/Sid and it completed without any errors.

Because I use Sid (unstable), my versions are is slightly more recent:
* Qt 5.7.1
* cmake 3.7.2
* uname: `Linux 4.9.0-3-amd64 #1 SMP Debian 4.9.30-1 (2017-06-04) x86_64 GNU/Linux`

I don't think the newer kernel or Qt itself have anything to do with this, so maybe something was fixed in cmake? It looks like 3.0.2 is 4 years old and was one of the first versions with AUTOUIC feature.

**Comment by phoerious** [comment] 2017-06-16 20:40
Quite possible. With the PR I referenced above we got rid of explicit CMake macros for compiling UI files in favor of AUTOUIC.

**Comment by CPWeaver** [comment] 2017-06-16 20:45
FWIW it seems to auto generate every other ui_name header file just fine... it's that particular one that is getting missed.

**Comment by droidmonkey** [comment] 2017-06-16 22:05
You need to clear out your build folders between 2.1.4 and develop. We are using the new cmake ui finder on develop.

**Comment by CPWeaver** [comment] 2017-06-16 22:06
I had this problem on a clean build.

**Comment by phoerious** [comment] 2017-06-17 09:41
Could you try a newer CMake version?

**Comment by droidmonkey** [comment] 2017-06-17 11:15
cmake 3.0.2 is documented to support the AUTOUIC feature. @CPWeaver can you please check in the build/src folder to see if there are ui_SettingsWidgetGeneral.h and ui_SettingsWidgetSecurity.h files?

**Comment by sainaen** [comment] 2017-06-17 14:13
@droidmonkey 
That's true, but I found [this bug](https://cmake.org/Bug/view.php?id=14981) filed against 3.0.2 and fixed in 3.1:
> *<...>* if one file has more than one #include "ui_*.h", only the last one is generated

I repeated the @CPWeaver's steps on Debain Jessie machine and got the same error.
Here's a part of the output that lists generated ui_*.h files (I checked, only those files actually present in build directory):
```
Generating ui_AboutDialog.h
Generating ui_CategoryListWidget.h
Generating ui_ChangeMasterKeyWidget.h
Generating ui_CloneDialog.h
Generating ui_DatabaseOpenWidget.h
Generating ui_DatabaseOpenWidget.h
Generating ui_DatabaseSettingsWidget.h
Generating ui_EditWidget.h
Generating ui_EditWidgetIcons.h
Generating ui_EditWidgetProperties.h
Generating ui_DatabaseOpenWidget.h
Generating ui_MainWindow.h
Generating ui_PasswordGeneratorWidget.h
Generating ui_SearchWidget.h
Generating ui_SettingsWidgetSecurity.h
Generating ui_SetupTotpDialog.h
Generating ui_TotpDialog.h
Generating ui_DatabaseOpenWidget.h
Generating ui_WelcomeWidget.h
Generating ui_CsvImportWidget.h
Generating ui_EditEntryWidgetMain.h
Generating ui_EditGroupWidgetMain.h
```
Here we can see that only the last import is considered by cmake: not only in `SettingsWidget.cpp` (`ui_SettingsWidgetSecurity.h` is imported after `ui_SettingsWidgetGeneral.h`), but also, for example, in `EditEntryWidget.cpp` (with 4 imports, only the last one `ui_EditEntryWidgetMain.h` is generated.)

@CPWeaver 
You can try to install cmake 3.6.2 from jessie-backports. With it I was able to build KeepassXC just fine.

**Comment by CPWeaver** [comment] 2017-06-17 18:28
I'd be willing to bet 3.0.2 is the issue. I will report back Monday morning.

**Comment by droidmonkey** [comment] 2017-06-17 19:59
geez its like no one ever tests these things 😜

**Comment by CPWeaver** [comment] 2017-06-19 18:53
Here is what was generated with cmake 3.0.2:
```
$ ls -1 src/ui_S*
src/ui_SearchWidget.h
src/ui_SettingsWidgetSecurity.h
src/ui_SetupTotpDialog.h
```

I pulled cmake 3.6.2 from jessie-backports and it generated properly.
```
$ ls -1 src/ui_S*
src/ui_SearchWidget.h
src/ui_SettingsWidgetGeneral.h
src/ui_SettingsWidgetSecurity.h
src/ui_SetupTotpDialog.h
```

So it seems the deps list on the wiki should specify cmake >= 3.1, plus 
`sudo apt-get -t jessie-backports install cmake` in the Linux guide.

I don't think I can PR the wiki (?) but I will say thank you for the help!!

**Comment by droidmonkey** [comment] 2017-06-19 23:50
I will change it right now!

**Closed by droidmonkey** 2017-06-19 23:50 UTC
Labels: build system
