### ISSUE TITLE
KeepassXC database locks despite timeout setting when actively using it with KeepassXC-browser

### ISSUE THREAD

**Issue by bluezclouds** [keepassxreboot/keepassxc#6374] opened 2021-04-06 17:23 UTC
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

KeepassXC database locks despite active use via KeepassXC-browser

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )

1. Set up KeepassXC and KeepassXC-Browser (I'm using Firefox)
2. Use actively via extension for the lock database timeout period set in KeepassXC.
3. 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
KeepassXC should keep the database open until the set timeout after the last use via KeepassXC-Browser.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
KeepassXC does not seem to recognize activity from the browser extension and locks even when in active use via extension. 

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.4
Revision: 34a78f0

Qt 5.12.8
Debugging mode is disabled.

Operating system: Linux Mint 20.1
CPU architecture: x86_64
Kernel: linux 5.4.0-70-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- libgcrypt 1.8.5

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows/Linux/macOS
Desktop Env: Gnome/KDE/XFCE/Mate/Cinnamon
Windowing System: X11/Wayland

**Comment by varjolintu** [comment] 2021-04-07 04:22
Duplicate of https://github.com/keepassxreboot/keepassxc/issues/310.

**Closed by varjolintu** 2021-04-07 04:22 UTC
Labels: bug
