### ISSUE TITLE
2.6.1: browser does not find entry

### ISSUE THREAD

**Issue by matthiasschroder** [keepassxreboot/keepassxc#5299] opened 2020-08-20 13:53 UTC
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
When using KeePassXC 2.6.1 the browser module in Firefox 79 claims it can not find an entry. 2.6.0 works fine on the same site.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Install 2.6.1
2. Visit website
3. Click on Browser modul

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Browser module recognizes website and pre-fills username and password field

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
I get a notification saying "Error! No login found" (text might be slightly different...) 

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.1
Revision: Not sure, I just went back to 2.6.0

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS

**Comment by varjolintu** [comment] 2020-08-20 15:21
Check your entry URL and if you have Best-matching credentials setting enabled. There's a small fix for handling subdomains and paths correctly.

**Comment by matthiasschroder** [comment] 2020-08-20 16:24
Thanks for your reply. Best matching credentials was enabled. I noticed I had 'https://fqdn' in the db, but the actual URL was 'https://fqdn/index.html'. Putting the full URL made KeePassXC find the entry. 

But this is a bit annoying, due to credential expiration I would need this to match any URL that starts with 'https://fqdn', how can I achieve that?

**Comment by varjolintu** [comment] 2020-08-20 16:26
If you use `https://example.com` it will work as a wildcard for `https://*.example.com/*` unless you have the _Best-matching credentials_ enabled. Then those wildcards won't work.

**Comment by matthiasschroder** [comment] 2020-08-20 16:34
I see. That is a strange side-effect of the Best-matching setting, and this is a change of behaviour with 2.6.1, isn't it?

**Comment by varjolintu** [comment] 2020-08-20 17:05
Your best bet is to disable the _Best-matching_ setting and use URL's without paths.

**Comment by MaxXor** [comment] 2020-08-20 17:36
Same here, after update to 2.6.1 all my browser autofill logins aren't working anymore, I tested several sites... this is the 2nd time now this year. Can we finally add unit tests to the autofill feature so it doesn't break every X releases? (I don't use URLs with paths)

**Comment by varjolintu** [comment] 2020-08-20 17:44
@MaxXor I guess the main reason why this happens is the _Best-matching credentials_ used with URL's with paths. Previously the option didn't actually handle subdomains and paths correctly. Now it does, and the bad part is that a lot of people have used the same URL's quite a long time and used the "wrong" handling without any problems. Considering that, I'm pretty certain this is actually not a bug.

**Comment by varjolintu** [comment] 2020-08-20 17:46
More details about the change here: https://github.com/keepassxreboot/keepassxc/pull/4832

**Comment by MaxXor** [comment] 2020-08-20 18:58
My URL is set to "https://discord.com/" and it doesn't find any logins for discord web (I don't use URLs with paths).

**Comment by varjolintu** [comment] 2020-08-20 19:28
@MaxXor Are you using the _Best-matching credentials_ setting?

**Comment by MaxXor** [comment] 2020-08-20 19:30
Yes

**Comment by varjolintu** [comment] 2020-08-20 19:31
@MaxXor Well, then you should use `https://discord.com/login` instead.

**Comment by jmichler** [comment] 2020-08-20 20:52
But this does not make sense. Then the name would need to be "exact matching URL only" instead of "best matching". It is quite widespread to have dynamic or at least frequently changing parts in the URL

**Comment by varjolintu** [comment] 2020-08-20 20:56
@jmichler Yeah it doesn't. It should still return the first credentials.

**Comment by hrez** [comment] 2020-08-21 07:11
So, how to make it work with https://discord.com in db now? - It doesn't work regardless of "best match" option.

**Comment by varjolintu** [comment] 2020-08-21 07:18
@hrez Using `https://discord.com/login` as said in my previous message.

**Comment by Renegade-Master** [comment] 2020-08-25 17:43
Same thing was happening to me with the new 2.6.1 release.  I thought I had broken something.

For example, my ProtonMail entry URL reads `https://protonmail.com/` as I am trying to make all of my entries aware only of the domain rather than the whole path.  I originally had "Best Matching Credentials" enabled, and in previous versions the browser extension would pick up my credentials, even when visiting `https://beta.protonmail.com/login`.
With the 2.6.1 update I was only being presented the "No Matching Credentials" popup.  I had to disable "Best Matching Credentials" in order to return to the functionality I was used to.

Works fine now that the option is disabled though 👍

**Comment by bennoonan92** [comment] 2020-08-27 00:39
I have attempted the above and nothing has worked. I am on a macbook pro using firefox browser integration. 
Changing https://fqdn -> https://fqdn/php/login.php didn't work and even tried adding a slash on the end of both configurations
Tried removing the "Return only best-matching credential" for all URL configurations no luck.

**Comment by varjolintu** [comment] 2020-08-27 04:14
@bennoonan92 You should roll back to 2.6.0 while waiting if nothing helps.

**Comment by veehexx** [comment] 2020-08-27 09:00
same issue. started happening with 2.6.1 x64 (win10). 2.6.0 worked fine:
![image](https://user-images.githubusercontent.com/1247183/91419438-508f9600-e84b-11ea-83c8-e76e073962db.png)

'return only best-matching credentials' is ticked with the above result. unticking this option allows the browser to find the correct creds.

keepass-xc browser is 1.6.6, browser firefox.

I havent updating my linux machines yet to see if it's OS specific.

**Comment by nniesen** [comment] 2020-08-27 19:48
@varjolintu Disabling the "best-matching" also fixed my problem with the Entries "Browser Integration> Additional URL's" not working. With best-matching enabled, it prompts if you want to allow access for the additional sites but then never shows the entry for the site. So currently, best-matching must be disable to use "Browser Integration> Additional URL's". It would be nice if there was a warning about that.

**Comment by varjolintu** [comment] 2020-08-27 20:05
@nniesen Best-Matching with Additional URL's is also already fixed for the next release.

**Comment by BullShark** [comment] 2020-09-01 16:21
This bug also affects me with Ungoogled Chromium and Icecat.

**Comment by bennoonan92** [comment] 2020-09-02 01:16
> @bennoonan92 You should roll back to 2.6.0 while waiting if nothing helps.
I did rollback but still having intermittent issues with it

**Comment by masi** [comment] 2020-09-04 16:18
I'm also in the the camp that has been affected by the "fix".
Oddly enough I have the disable best match even when the URL does match exactly. Looking forward to the new version.

**Comment by timodenissen** [comment] 2020-09-11 07:06
Regardless of setting the "best matching" option or using KeePassXC 2.6.0 or 2.6.1, Firefox fails to detect any credentials. When closing the database, the browser plugin detects this and gives me the correct message. When opening the database again I get no credentials, no "No credentials found" message... nothing.

Funnily, KeePassXC-Browser asks me to save new credentials (which are saved correctly!) and then fails to retrieve them but asks me again to save them, thus duplicating the exact entry. KeePassXC-Browser is set to save the whole URL, not just the domain.

KeePassXC - 2.6.1 (installed using the PPA)
KeePassXC-Browser - 1.7.0
Operating system: Linux x86_64 (Ubuntu 20.04)
Browser: Mozilla Firefox 80.0

Is there a simple way of testing a future version with the fix applied?

**Comment by varjolintu** [comment] 2020-09-11 12:24
@timodenissen The fix is not yet merged, so no. If even 2.6.0 doesn't work, then I would like to see an example of an entry with a URL that doesn't work, plus your Browser Integration settings.

**Comment by timodenissen** [comment] 2020-09-15 12:15
@varjolintu Annoyingly, the problem I had with github.com does not come up again :angry:...

I had the problem with https://github.com/login as URL entry. I'm currently using KeePassXC 2.6.1. Only problem(s) I now have are entries containing multiple URLs, but those are neglectable at the moment.

Because you asked for them, please find my browser settings attached.

[keepassxc-browser_settings.json.txt](https://github.com/keepassxreboot/keepassxc/files/5224721/keepassxc-browser_settings.json.txt)

**Comment by timodenissen** [comment] 2020-09-18 18:12
I found my culprit: I enabled "Match URL scheme" in the general browser integration settings, now everything works like a charm again, even the multi-URL entries (I just cross-checked the settings from my Ubuntu installation with my Arch installation).

**Comment by synergiator** [comment] 2020-09-22 08:57
For me, URL wildcard is not working so that this bug applies

**Comment by Winter84** [comment] 2020-09-27 16:44
I have also been having this problem (Firefox 80.0.1 on macOS 10.13.6 with KXC 2.6.1), though I guiltily confess I have not made a record of examples for you, but they include several sites that I use regularly. I do not have best-matching set, but I do have Match URL scheme set, if that is relevant.

One behaviour that I have noticed is that matching does not work when reopening KXC from the browser when already on the page where I want to fill in the credentials. If I hit login with no credentials, KXC will then recognize and fill the credentials properly.

**Comment by droidmonkey** [comment] 2020-09-27 17:20
This has been fixed for 2.6.2

**Closed by droidmonkey** 2020-09-27 17:20 UTC
Labels: bug, plugin: Browser integration

**Comment by pintjuk** [comment] 2023-08-12 12:05
sorry for a stupid question, but where do I find this best-matching setting?

**Comment by earentir** [comment] 2023-08-12 12:16
Tools -> Settings -> Browser Integration

**Comment by koppor** [comment] 2023-09-25 12:57
For the Googlers: The error message also appears if no databases have been setup for the connection. Please double check that there is a connected database.
