### ISSUE TITLE
Export a sub-group as a separate .kbdx file

### ISSUE THREAD

**Issue by peanutbutterandcrackers** [keepassxreboot/keepassxc#3063] opened 2019-04-23 04:26 UTC
## Summary
The ability to export a certain subgroup as a separate `.kbdx` file would allow users to take their `workplace` passwords and put it onto their workplace computer, without having to worry about `personal` passwords coming along with them.

## Desired Behavior
It would be nice if a sub-group could be clicked and there were an option to `export as a new .kbdx file`. Or something similar.

## Context
I have been in a situation where there was something similar to `work` subgroup and `personal` subgroup. It would have been preferable to get a copy of the workplace passwords on to a workplace computer. However, because of the presence of one's own personal passwords in the same file, it didn't seem like the best of ideas.

**Comment by droidmonkey** [comment] 2019-04-24 18:48
Duplicate of #642 and #1940

**Closed by droidmonkey** 2019-04-24 18:48 UTC
Labels: new feature
