### ISSUE TITLE
Keypass buggy with last versions of IOS

### ISSUE THREAD

**Issue by AlfaDelta** [keepassxreboot/keepassxc#4010] opened 2019-12-12 01:49 UTC
Since last updates of my macbook os KeypressXC is buggy, or is it the OS ;-)

While editing a field of finishing a entry, the change it crash is there :-( 

Process:               KeePassXC [13095]
Path:                  /Applications/KeePassXC.app/Contents/MacOS/KeePassXC
Identifier:            org.keepassx.keepassxc
Version:               2.5.1 (???)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           KeePassXC [13095]
User ID:               501

Date/Time:             2019-12-12 02:44:22.909 +0100
OS Version:            Mac OS X 10.15.1 (19B88)
Report Version:        12
Anonymous UUID:        639FC95A-EB87-C983-3EC1-DB9E3948437E

Sleep/Wake UUID:       D1DA72D1-7F55-4143-BD80-36255CAEA56D

Time Awake Since Boot: 200000 seconds
Time Since Wake:       20000 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000100
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [13095]

VM Regions Near 0x100:
--> 
    __TEXT                 000000010ebc3000-000000010ef4f000 [ 3632K] r-x/r-x SM=COW  /Applications/KeePassXC.app/Contents/MacOS/KeePassXC

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   org.keepassx.keepassxc        	0x000000010ebf803f 0x10ebc3000 + 217151
1   org.keepassx.keepassxc        	0x000000010ecdfd7a 0x10ebc3000 + 1166714
2   org.keepassx.keepassxc        	0x000000010ece087e 0x10ebc3000 + 1169534
3   org.qt-project.QtCore         	0x0000000110095833 QMetaObject::activate(QObject*, int, int, void**) + 1843
4   org.qt-project.QtCore         	0x0000000110095833 QMetaObject::activate(QObject*, int, int, void**) + 1843
5   org.qt-project.QtWidgets      	0x000000010f3f9962 0x10f258000 + 1710434
6   org.qt-project.QtCore         	0x0000000110095833 QMetaObject::activate(QObject*, int, int, void**) + 1843
7   org.qt-project.QtWidgets      	0x000000010f34f84f 0x10f258000 + 1013839
8   org.qt-project.QtWidgets      	0x000000010f34f6ec 0x10f258000 + 1013484
9   org.qt-project.QtWidgets      	0x000000010f35081c QAbstractButton::mouseReleaseEvent(QMouseEvent*) + 268
10  org.qt-project.QtWidgets      	0x000000010f2a2be7 QWidget::event(QEvent*) + 439
11  org.qt-project.QtWidgets      	0x000000010f268220 QApplicationPrivate::notify_helper(QObject*, QEvent*) + 272
12  org.qt-project.QtWidgets      	0x000000010f26b186 QApplication::notify(QObject*, QEvent*) + 7670
13  org.qt-project.QtCore         	0x0000000110065834 QCoreApplication::notifyInternal2(QObject*, QEvent*) + 212
14  org.qt-project.QtWidgets      	0x000000010f268b47 QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) + 903
15  org.qt-project.QtWidgets      	0x000000010f2c1dff 0x10f258000 + 433663
16  org.qt-project.QtWidgets      	0x000000010f2c0b4a 0x10f258000 + 428874
17  org.qt-project.QtWidgets      	0x000000010f268220 QApplicationPrivate::notify_helper(QObject*, QEvent*) + 272
18  org.qt-project.QtWidgets      	0x000000010f2695d5 QApplication::notify(QObject*, QEvent*) + 581
19  org.qt-project.QtCore         	0x0000000110065834 QCoreApplication::notifyInternal2(QObject*, QEvent*) + 212
20  org.qt-project.QtGui          	0x000000010f948ff1 QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) + 3441
21  org.qt-project.QtGui          	0x000000010f93064b QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) + 219
22  libqcocoa.dylib               	0x00000001120da828 0x1120a6000 + 215080
23  com.apple.CoreFoundation      	0x00007fff3c062b81 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
24  com.apple.CoreFoundation      	0x00007fff3c062b20 __CFRunLoopDoSource0 + 103
25  com.apple.CoreFoundation      	0x00007fff3c046154 __CFRunLoopDoSources0 + 209
26  com.apple.CoreFoundation      	0x00007fff3c045760 __CFRunLoopRun + 1272
27  com.apple.CoreFoundation      	0x00007fff3c044fe3 CFRunLoopRunSpecific + 499
28  com.apple.HIToolbox           	0x00007fff3abcc67d RunCurrentEventLoopInMode + 292
29  com.apple.HIToolbox           	0x00007fff3abcc2c9 ReceiveNextEventCommon + 356
30  com.apple.HIToolbox           	0x00007fff3abcc147 _BlockUntilNextEventMatchingListInModeWithFilter + 64
31  com.apple.AppKit              	0x00007fff39251864 _DPSNextEvent + 990
32  com.apple.AppKit              	0x00007fff392505d4 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1352
33  com.apple.AppKit              	0x00007fff3924ad76 -[NSApplication run] + 658
34  libqcocoa.dylib               	0x00000001120d9698 0x1120a6000 + 210584
35  org.qt-project.QtCore         	0x0000000110060ddf QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 431
36  org.qt-project.QtCore         	0x0000000110065e82 QCoreApplication::exec() + 130
37  org.keepassx.keepassxc        	0x000000010ebccdb0 0x10ebc3000 + 40368
38  libdyld.dylib                 	0x00007fff7351f2e5 start + 1

Thread 1:: com.apple.CFSocket.private
0   libsystem_kernel.dylib        	0x00007fff7366f7e6 __select + 10
1   com.apple.CoreFoundation      	0x00007fff3c073a8a __CFSocketManager + 632
2   libsystem_pthread.dylib       	0x00007fff7372bd36 _pthread_start + 125
3   libsystem_pthread.dylib       	0x00007fff7372858f thread_start + 15

Thread 2:: com.apple.NSEventThread
0   libsystem_kernel.dylib        	0x00007fff73668166 mach_msg_trap + 10
1   libsystem_kernel.dylib        	0x00007fff736686cc mach_msg + 60
2   com.apple.CoreFoundation      	0x00007fff3c04636b __CFRunLoopServiceMachPort + 322
3   com.apple.CoreFoundation      	0x00007fff3c045907 __CFRunLoopRun + 1695
4   com.apple.CoreFoundation      	0x00007fff3c044fe3 CFRunLoopRunSpecific + 499
5   com.apple.AppKit              	0x00007fff39258dba _NSEventThread + 132
6   libsystem_pthread.dylib       	0x00007fff7372bd36 _pthread_start + 125
7   libsystem_pthread.dylib       	0x00007fff7372858f thread_start + 15

Thread 3:: Thread (pooled)
0   libsystem_kernel.dylib        	0x00007fff7366b916 __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff7372c040 _pthread_cond_wait + 701
2   org.qt-project.QtCore         	0x000000010feaae80 0x10fe82000 + 167552
3   org.qt-project.QtCore         	0x000000010feaabde 0x10fe82000 + 166878
4   org.qt-project.QtCore         	0x000000010feaab54 QWaitCondition::wait(QMutex*, QDeadlineTimer) + 100
5   org.qt-project.QtCore         	0x000000010feaaabb QWaitCondition::wait(QMutex*, unsigned long) + 59
6   org.qt-project.QtCore         	0x000000010fea76a7 0x10fe82000 + 153255
7   org.qt-project.QtCore         	0x000000010fea28f3 0x10fe82000 + 133363
8   libsystem_pthread.dylib       	0x00007fff7372bd36 _pthread_start + 125
9   libsystem_pthread.dylib       	0x00007fff7372858f thread_start + 15

Thread 4:
0   libsystem_pthread.dylib       	0x00007fff7372856c start_wqthread + 0

Thread 5:
0   libsystem_pthread.dylib       	0x00007fff7372856c start_wqthread + 0

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0xa74cf72f246100be  rbx: 0x00007ffcaf562800  rcx: 0x0000000000000171  rdx: 0x00000000bea860ca
  rdi: 0x00007ffee103a3d8  rsi: 0x0000600000f79920  rbp: 0x00007ffee103a460  rsp: 0x00007ffee103a450
   r8: 0x00000000000001ff   r9: 0x00000000000007fb  r10: 0x0000000000001920  r11: 0x0000000000000020
  r12: 0x00007ffee103a490  r13: 0x0000600000156820  r14: 0x0000000000000000  r15: 0x00007ffee103a480
  rip: 0x000000010ebf803f  rfl: 0x0000000000010202  cr2: 0x0000000000000100
  
Logical CPU:     0
Error Code:      0x00000004 (no mapping for user data write)
Trap Number:     14

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 5
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 134072
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=597.9M resident=0K(0%) swapped_out_or_unallocated=597.9M(100%)
Writable regions: Total=632.2M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=632.2M(100%)
 
                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Accelerate framework               512K        4 
Activity Tracing                   256K        1 
CG backing stores                 1328K        4 
CG image                           368K       25 
CoreAnimation                      556K       18 
CoreGraphics                         8K        1 
CoreImage                           40K        6 
CoreUI image data                 3348K       28 
Foundation                          24K        2 
Kernel Alloc Once                    8K        1 
MALLOC                           233.8M      109 
MALLOC guard page                   32K        7 
MALLOC_NANO (reserved)           384.0M        1         reserved VM address space (unallocated)
Memory Tag 242                      12K        1 
STACK GUARD                       56.0M        6 
Stack                             10.5M        6 
VM_ALLOCATE                        736K       67 
__DATA                            31.1M      374 
__DATA_CONST                        48K        6 
__FONT_DATA                          4K        1 
__LINKEDIT                       358.5M       41 
__OBJC_RO                         32.0M        1 
__OBJC_RW                         1780K        2 
__TEXT                           239.4M      360 
__UNICODE                          564K        1 
mapped file                       95.6M       55 
shared memory                      656K       18 
===========                     =======  ======= 
TOTAL                              1.4G     1146 
TOTAL, minus reserved VM space     1.0G     1146 

Model: MacBookPro11,2, BootROM 157.0.0.0.0, 4 processors, Quad-Core Intel Core i7, 2,2 GHz, 16 GB, SMC 2.18f15
Graphics: kHW_IntelIrisProItem, Intel Iris Pro, spdisplays_builtin
Memory Module: BANK 0/DIMM0, 8 GB, DDR3, 1600 MHz, 0x80AD, 0x484D54343147533641465238412D50422020
Memory Module: BANK 1/DIMM0, 8 GB, DDR3, 1600 MHz, 0x80AD, 0x484D54343147533641465238412D50422020
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x134), Broadcom BCM43xx 1.0 (7.77.106.3 AirPortDriverBrcmNIC-1435.3)
Bluetooth: Version 7.0.1f1, 3 services, 27 devices, 1 incoming serial ports
Network Service: Thunderbolt Ethernet, Ethernet, en6
PCI Card: Apple 57762-A0, sppci_ethernet, Thunderbolt@195,0,0
Serial ATA Device: APPLE SSD SM0256F, 251 GB
USB Device: USB 3.0 Bus
USB Device: Apple Internal Keyboard / Trackpad
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
USB Device: USB Keyboard
Thunderbolt Bus: MacBook Pro, Apple Inc., 17.1
Thunderbolt Device: Thunderbolt to Gigabit Ethernet Adapter, Apple Inc., 3, 5.5

**Comment by droidmonkey** [comment] 2019-12-12 01:58
Duplicate of #3857

**Closed** 2019-12-12 01:58 UTC
Labels: duplicate
