### ISSUE TITLE
Masked fields when logging into the bank

### ISSUE THREAD

**Issue by sylwester92** [keepassxreboot/keepassxc#4273] opened 2020-02-01 15:10 UTC
## Summary
I would like to ask if there is posibility to fill masked fields on the second step in logging into bank (Alior). The problem is that fields and their quantity are random.

## Desired Behavior
Fill masked fields and press "Sign in" button (or press enter after fill last char).

## Possible Solution
Some script that skip non-fillable fields and check actual position when typing.

## Context
I often logs in to my bank.
![1](https://user-images.githubusercontent.com/23282657/73594300-57506780-450d-11ea-813a-7c5ca4dece05.jpg)
![2](https://user-images.githubusercontent.com/23282657/73594302-57506780-450d-11ea-83b1-b146f98e41e1.jpg)

**Comment by droidmonkey** [comment] 2020-02-01 15:22
Duplicate of #725

**Closed by droidmonkey** 2020-02-01 15:22 UTC
Labels: new feature
