### ISSUE TITLE
Attempting to add a file to an entry causes KeePassXC to become unresponsive.

### ISSUE THREAD

**Issue by akwala** [keepassxreboot/keepassxc#11383] opened 2024-10-20 02:11 UTC
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
KeePassXC becomes unresponsive indefinitely when attempting to add a file to an entry,

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Right-click an entry and select 'Edit entry...'.
2. Go to the 'Advanced' tab.
3. In 'Attachments' section, click the 'Add' button.
4. A file manager window (Dolphin) appears.
5. Try changing the folder in the file manager.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Be able to 
- navigate, in the file manager window, to the location of the file to be added; 
- select the file and add it to the entry in KeePassXC.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
The file manager window freezes and is unresponsive for an indefinite amount of time. Attempting to close the window causes a dialog window to appear, saying that KeePassXC is unresponsive and asking whether it should be terminated. 

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.9
Revision: 8f6dd13

Qt 5.15.3
Debugging mode is disabled.

Operating system: Ubuntu 22.04.5 LTS
CPU architecture: x86_64
Kernel: linux 5.15.0-124-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.19.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: KDE
Windowing System: X11

**Comment by droidmonkey** [comment] 2024-10-20 02:57
We don't control the file manager window, that is actually a system window (ie, there is no code on our end). You have something going on external to keepassxc. 

You'll have to run the program through gdb and provide a stack trace to determine what's going on.

**Comment by droidmonkey** [comment] 2024-10-20 12:52
Since this does not occur from within KeePassXC code going to close this one unless you can provide a stack trace showing otherwise. I do recommend updating your system if possible or switching to the Flatpak distribution.

**Closed as completed by droidmonkey** 2024-10-20 12:52 UTC
Labels: not reproducible, more info needed, platform: Linux - KDE

**Comment by Tinister** [comment] 2024-11-11 20:01
I'm seeing the same thing on Windows 10.  KeepassXC goes unresponsive and crashes as soon as the file picker opens.

Since this is Windows, I'm hesitant to think it's "something going on external".  Additionally, opening files in every other program I've tried so far works fine.

**Comment by droidmonkey** [comment] 2024-11-11 20:14
File picker is windows code. If it crashes when it's shown that is either windows or qt. If it crashes _after_ a file is chosen then maybe it could be us.

**Comment by mbrandis** [comment] 2025-12-27 16:51
I have the same issue with KeePassXC in KDE with Wayland. I tried using gdb, but apart from some "Thread" lines, nothing else appeared. I’m not an expert with gdb. Can I help reproduce the issue? I would really like this problem to be fixed.

**Comment by droidmonkey** [comment] 2025-12-27 17:41
Compile a debug build and run it directly, otherwise you can't

**Comment by mbrandis** [comment] 2025-12-27 19:00
Here is the output of gdb.

[keepassxc-gdb.log](https://github.com/user-attachments/files/24356297/keepassxc-gdb.log)

**Comment by droidmonkey** [comment] 2025-12-27 20:39
```
#12 0x00007ffff63b13e5 in QMimeDatabase::mimeTypeForFile(QFileInfo const&, QMimeDatabase::MatchMode) const () from /lib/x86_64-linux-gnu/libQt5Core.so.5
No symbol table info available.
#13 0x00007ffff25336ad in ?? () from /usr/lib/x86_64-linux-gnu/qt5/plugins/platformthemes/libqt5ct.so
No symbol table info available.
#14 0x00007ffff728e35c in QFileIconProvider::icon(QFileInfo const&) const () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
No symbol table info available.
#15 0x00007ffff71b7f4f in ?? () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
No symbol table info available.
#16 0x00007ffff71b1a78 in ?? () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
No symbol table info available.
#17 0x00007ffff6306343 in QObject::event(QEvent*) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
No symbol table info available.
#18 0x00007ffff6f6bd45 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
No symbol table info available.
#19 0x00007ffff62d8118 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
No symbol table info available.
#20 0x00007ffff62db94b in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
No symbol table info available.
#21 0x00007ffff6335c0f in ?? () from /lib/x86_64-linux-gnu/libQt5Core.so.5
No symbol table info available.
#22 0x00007ffff4f145c5 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#23 0x00007ffff4f73737 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#24 0x00007ffff4f13a63 in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#25 0x00007ffff6335279 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
No symbol table info available.
#26 0x00007ffff62d6a7b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
No symbol table info available.
#27 0x00007ffff718aebb in QDialog::exec() () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
No symbol table info available.
#28 0x00007ffff71a0c18 in QFileDialog::getOpenFileUrls(QWidget*, QString const&, QUrl const&, QString const&, QString*, QFlags<QFileDialog::Option>, QStringList const&) ()
   from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
No symbol table info available.
#29 0x00007ffff71a0d16 in QFileDialog::getOpenFileNames(QWidget*, QString const&, QString const&, QString const&, QString*, QFlags<QFileDialog::Option>) ()
   from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
```

The crash occurs in system code but starts with Qt trying to obtain mime type information. It has nothing to do with KeePassXC code.

**Comment by mbrandis** [comment] 2025-12-28 10:16
Okay. Thank you. 

I just tested it with another QT application (not KDE) and I see the same problem. Opening a file dialog -> choosing a new directory with files in it -> file dialog is no longer responding. 

Do you have a tip for me where to open this bug? KDE? QT?

Thank you for your time.

**Comment by droidmonkey** [comment] 2025-12-28 12:05
I would open it with kde
