### ISSUE TITLE
Release 2.6.3 keeps crashing - macOS 11.1

### ISSUE THREAD

**Issue by markster101** [keepassxreboot/keepassxc#5927] opened 2021-01-14 04:54 UTC
Issue 1. Using Firefox to download the file. After download completed macOS has given an error that Developer cannot be verified. After I approved that with Preferences/Security it shown an error "Application is damaged."

Repeated the same process using Safari and I was able to finally install the app, however I keep experiencing frequent app crushes when
1. Trying to close the app.
2. After computer wake-up with app opened.

I'd like to reinstall version 2.6.2 but cannot find the original. Can you provide the link?

mark

**Comment by phoerious** [comment] 2021-01-14 07:01
Can you provide a crash dump?

You will find older releases on the Github releases page.

**Comment by phoerious** [comment] 2021-01-14 07:07
Are you using the SSH agent feature? If yes, this may be a duplicate of #5820.

**Comment by kdwinnell** [comment] 2021-01-14 14:13
I encountered the same problem if I dragged KeePassXC 2.6.3 into the shortcut to the Applications folder that appeared during the DMG install. Dragging directly into the Applications folder in Finder allowed the install to complete properly. I also downloaded with Firefox 85.0b7, MacOS 11.1.

**Comment by tomhundt** [comment] 2021-01-15 00:15
Wow, @kdwinnell, same here (but MacOS 11.2 Beta (20D5029f) + Chrome 87), dragging directly to `/Applications` worked.  From what I can tell, that alias is okay, too (just an alias/symlink to `/Applications`).  I wouldn't have thought that mattered.  Thanks!

**Comment by kdwinnell** [comment] 2021-01-15 00:40
I'm on the M1 machine. Would that be part of it? Glad there's a workaround.

**Comment by SiGmAX666** [comment] 2021-01-15 01:27
Same issue for me, same workaround worked. Also on macOS11 and an M1 MBP.

**Comment by markster101** [comment] 2021-01-15 04:25
Using SSH agent feature, yes. That maybe why the app has been crushing but the install steps as other have mentioned is probably something different. Sorry that I cannot provide the app dump since I had to revert back to 2.6.2

**Comment by zapme** [comment] 2021-01-21 23:31
Same issue, macOS 11.1, KeepassXC 2.6.3.  Disable SSH agent fixed the problem for me.

Crash reports were sent to apple.  How can I send to here?

The option to remove is a per entry setting, tedious to trigger for all ssh keys.

**Comment by droidmonkey** [comment] 2021-01-22 01:22
We don't need them we know what the crash is and it's fixed.

**Closed** 2021-03-28 14:02 UTC
Labels: bug, platform: macOS
