### ISSUE TITLE
Discussion: The Future of KeePassX-Reboot

### ISSUE THREAD

**Issue by TheZ3ro** [keepassxreboot/keepassxc#40] opened 2016-10-10 12:55 UTC
Lot of users rely on KeePassX as main PasswordManager.
If this is a serious fork we need to consider:
- Opening a project on [Transifex for translations](https://github.com/keepassxreboot/keepassx/issues/35) 
- Opening an Official WebSite for the Reboot fork
- [Pushing binaries for upstream distro,](https://github.com/keepassxreboot/keepassx/issues/5) MacOs and Windows
- Update all the KeePassX reference to KeePassX Reboot
- Starting a "dev" mailing-list or another form of team communication between team member that actively develop the project

And more...

**Comment by Manko10** [comment] 2016-10-10 14:27
We should maybe also make this a standalone repository instead of an attached fork, so contributions are counted. See https://help.github.com/articles/why-are-my-contributions-not-showing-up-on-my-profile/

**Comment by droidmonkey** [comment] 2016-10-10 23:41
I was going to unfork us this week. We are significantly departing from the main code base with no intention of folding the changes back in.

I was thinking of using a different name for the binary application so as not to conflict with KeePassX in any manner. Any suggestions?

My ideas:

- KeePassXtra
- KeePass2X
- KeePassXL
- KeePassXtd   (Xtd for Extended)

**Comment by magkopian** [comment] 2016-10-11 05:25
What about keep it simple and just call it KeePassX2 so everyone will know what this is about? KeePass2X also looks ok to me, but it reminds me more of KeePass2 rather than KeePassX as X comes after 2, and might even confuse some people into thinking that it is a fork of KeePass2.

**Comment by magkopian** [comment] 2016-10-11 05:38
@TheZ3ro Regarding the `Opening an Official WebSite for the Reboot fork`, I'd like to let you know that I'm a PHP developer, so in case you need me I'd be glad to help with that part.

**Comment by TheZ3ro** [comment] 2016-10-11 10:09
I think se should stuck with `keepassx-reboot`
Anyway, what about the mailing-list/communication channel?

**Comment by LawGuy2000** [comment] 2016-10-11 14:42
I agree that it definitely needs a different name than the original keepass. That way distributions can easily include both and let the user decide (there is benefits to the old keepass code as this code base is changing rapidly so there may be bugs introduced).

I think "keepassx-rebooted" is good

**Comment by jonafato** [comment] 2016-10-11 14:57
(I'm not involved in either project, but I do use KeePassX and am considering switching over to the reboot.)

I like the idea of a separate name to disambiguate, and KeePassXtd seems to align nicely with the goals of the reboot (extending the functionality of the original application). Options like KeePass2X or X2 would likely be very confusing to users, as KeePassX is currently on version 2.0.2 (2.0.0 being a big release), and future version updates may result in names like "KeePassX2 version 3 (the second major version of KeePassX Reboot)".

**Comment by Manko10** [comment] 2016-10-11 16:40
I would prefer something pronounceable with at most one extra letter,
not three. KeePassXtd is too complicated and KeePass Extended is too
long. We could call it QKeePass, but that's a little trite.

I also don't think that this is really an "extended" Version of
KeePassX. It's just the normal KeePassX with all the stuff that should
have made it into the original project in the first place. We shouldn't
choose a name that will inevitably become cheesy or meaningless in a
couple of years. For that reason, I also think that "Reboot" should only
be a working title for now and not the real name we choose in the end.

**Comment by magkopian** [comment] 2016-10-11 16:49
@Manko10 I think that QKeePass looks very different than KeePassX and I don't quite like how it looks in the eye, I agree though with your thinking that Reboot should not be part of the name. We need something new, but yet not very far from the original. What about let's say KeePassZ or KeePassK? I think Z looks at least as cool as X and also K looks a bit like X if you think about it.

**Comment by TheZ3ro** [comment] 2016-10-11 17:33
KeePassX is named after KeePass and the X stand for "Cross-Platform".
If we need a name I prefer a name with an actual sense, not a name that just fit in 😅 

KeePassXR (CrossPlatform Reboot)

**Comment by magkopian** [comment] 2016-10-11 17:43
@TheZ3ro As long as we don't call it KeePassXP :stuck_out_tongue_winking_eye: this is fine by me.

**Comment by george-viaud** [comment] 2016-10-11 21:41
KeepassX-LTS ;)

**Comment by droidmonkey** [comment] 2016-10-11 22:17
I am taking a liking to KeePassXR, but its only really a reboot in the short term to gain momentum. Rebooting is not the main goal, as @Manko10 suggested. Tough decision...

**Comment by droidmonkey** [comment] 2016-10-12 00:30
I created a Discord channel for this project: https://discord.gg/q7Pda

Discord is like a mailing list and a chat tool rolled into one, good way to coordinate ideas or ask questions in a non-committal way. GitHub will obviously be the official means of communication though.

If someone wants to be the moderator/semi-admin of this channel let me know. You can create sub-channels for targeted discussions.

**Comment by LawGuy2000** [comment] 2016-10-12 06:41
What about KeePassOS where OS means "open source". The previous keepass was open source, but it did not really support open development (and neither does the original in actuality) and it seems this one intends to do that. I don't think the "X" needs to stay as nowadays all keepass versions are cross platform (keepass can be run with mono for example).

**Comment by george-viaud** [comment] 2016-10-12 06:48
I appreciate the sentiment but feel OS ubiquitously references "Operating System" and doesn't fit (just one person's humble opinion of course)

The fact that it will be openly developed and supported is really the major feature of this fork, or so it seems.

I'll reiterate my suggestion of "KeePassX-LTS" for that reason but fear it may be too long or perhaps just too obscure.  It's tough because there is a great desire to remain with the original naming as it brings with it the link/community...

**Comment by Manko10** [comment] 2016-10-12 08:09
If we want to stress the open source character, what about Open KeePass, LibreKeePass or KeePassFree?

**Comment by TheZ3ro** [comment] 2016-10-12 08:20
@droidmonkey the Discord invite is expired 

all: KeePass and KeePassX are both open source, so I don't see any sense to use "OS" or "Libre" in the name.
Maybe It should be good to maintain "Kee" in the name because this fork support KeePass database format.

Some new names:
"KiPass" -> pronounce like "KeePass" (we can also append an "X" if we want)
"XPass" ->pronounced as "cross-pass"

**Comment by TheZ3ro** [comment] 2016-10-12 19:15
Also, we will need a new icon I think

**Comment by Manko10** [comment] 2016-10-12 19:23
Yes, I was thinking about that. And when we're already in the progress,
we should also make some monochrome variants for use in desktop
environments such as KDE. I've always hated the green icon in my
otherwise monochrome systray.

**Comment by droidmonkey** [comment] 2016-10-12 20:42
Scratch Discord, I decided based on reading some Open Source guides that using Google Groups is a better alternative. I set it up as a Q&A format so that topics can be starred/categorized/and voted on.

https://groups.google.com/forum/#!forum/keepassx-reboot

Yes, a new icon is needed, issue #41

**Comment by fcore117** [comment] 2016-10-14 14:51
Finally a cross platform local file based password manager is coming, i wait for day when i could replace this C# based KeePass with this KeePassX2. My Chromium portable from chromium.woolyss.com is waiting  :)

**Comment by droidmonkey** [comment] 2016-10-14 19:37
You can use it today! It is rather stable due to the hard work of the original maintainers, I recommend compiling this tag: https://github.com/keepassxreboot/keepassx/tree/2.0.3-http

**Comment by TheZ3ro** [comment] 2016-10-18 07:57
People are using the KeePassX Reboot (`keepassx-reboot`) name already, We really want to change the name?

**Comment by droidmonkey** [comment] 2016-10-18 11:23
I think its ok to keep calling it reboot, the actual executable can be ```keepassxr``` with an alias of ```keepassx-reboot```?

**Comment by TheZ3ro** [comment] 2016-10-18 13:04
I'm ok with the names/alias `keepassxr` - `keepass-reboot`  👍

**Comment by magkopian** [comment] 2016-10-18 13:20
I think there should also be a `keepassx` symlink that points to the `keepassxr` binary, but only in the case that the original `keepassx` is not already installed as well. This is important for software packages that may depend on the original `keepassx` so they won't break if only `keepassxr` is installed.

**Comment by jonafato** [comment] 2016-10-18 14:46
@TheZ3ro Sorry if I've jumped the gun a little here. The pull request that referenced this issue was intended to address the reference to @droidmonkey's moved repository. If necessary, I'm happy to change the name listed there before it gets merged, and I'll keep up with any changes that happen here, as well.

**Comment by TheZ3ro** [comment] 2016-10-18 15:14
@jonafato no problem, the name it's an Issue we have to resolve some point in time

@droidmonkey @magkopian I like your idea about alias but I think that those things are platform-dipendent (package maintainer will address the alias problem)

What we really need instead is the name that we will use in the program UI (window title, about screen, etc) and the executable name (for Linux all lowercase, and for Windows and Mac with proper upper and lower case)

If we all agree on **KeePassXR** and **keepassxr** I think we can start to change all the label for KeePassX.

Also another Issue will be insert the "KeePassX-Reboot copyright" in every file header we change and in the COPYING file

**Comment by magkopian** [comment] 2016-10-18 16:13
@TheZ3ro KeePassXR and keepassxr are fine by me, personally I like KeePassX2 better, but I think KeePassXR is also fine.

**Comment by stmllr** [comment] 2016-10-18 21:40
suggestion: KeePassXL (KeePassX with LTS)

**Comment by WizardGed** [comment] 2016-10-18 21:48
Just a thought but can there be a better place (a poll maybe?) for
suggestions. All I'm going to say is that if you look at the post history
this and other issues have received a continuous stream of the same
suggestions repeatedly and getting others to vote instead of repeated email
will make everyone's email inbox/github notifications a lot less ...
repetitive.

**Comment by droidmonkey** [comment] 2016-10-20 00:35
Please continue this discussion in the following Google Group topic. I am locking this discussion but leaving the issue open until a resolution is reached.

https://groups.google.com/forum/#!topic/keepassx-reboot/tJhYaTt3rqc

**Comment by TheZ3ro** [comment] 2016-10-25 08:58
I have proposed a new Icon.
Everybody please take a look at this https://groups.google.com/d/msg/keepassx-reboot/tJhYaTt3rqc/MY-rtRnwAgAJ

**Closed** 2016-11-25 15:20 UTC
Labels: discussion

**Comment by TheZ3ro** [comment] 2016-11-25 20:59
Guys, every maintainer must read google groups. Please keep weekly notification on it.

**Comment by Manko10** [comment] 2016-11-26 09:10
I get mail notifications directly into my inbox.
