### ISSUE TITLE
No menu items in title bar

### ISSUE THREAD

**Issue by twdkeule** [keepassxreboot/keepassxc#763] opened 2017-07-11 07:42 UTC
## Expected Behavior
There should be dropdown menus in the title bar

## Current Behavior
There are no menus in the title bar. I cannot change any of the settings.

## Steps to Reproduce (for bugs)
1. Set KeepassXC to minimize to tray icon
2. Close
3. Open
4. ...

## Debug Info

KeePassXC - 2.2.0 
Revision: REVISION

Libraries:
- LIBS

Operating system: Ubuntu 17.04
CPU architecture: x64
Kernel: 4.10.0-26

Enabled extensions:
- Http

**Comment by phoerious** [comment] 2017-07-11 07:44
Duplicate of #691.

**Closed by phoerious** 2017-07-11 07:44 UTC
