### ISSUE TITLE
Autotype uses current keyboard language and layout

### ISSUE THREAD

**Issue by pankaryp** [keepassxreboot/keepassxc#2475] opened 2018-11-13 13:31 UTC
When you press the _Autotype Button_ it usually autocompletes the selected entry (username and password) , into the input form in your broswer (for example you facebook username and password) and it presses the _enter key_  automatically, logging in this way to your account.

Now, when your keyboard language is English, everything goes as intended. If you change your keyboard language (for example Greek) and you press the _autocomplete button_, it transforms the selected entry in Greek characters, it pastes the greek-like character into the form and it presses _enter_ again to submit the form, which is of course invalid.

## Expected Behavior

The Autotype button should copy your entry as it it , inside the form.

## Current Behavior

The Autotype button copies your entry inside the form but in different languages according to your keyboard language.

## Steps to Reproduce (for bugs)

1. Create an entry, **ex, username: panostest@gmail.com, password: testpass**
2. Then while having english(us) as the default keyboard language. try to use the Autotype button in a random form. It will paste _panostest@gmail.com,  testpass_ inside the form
3. Now with the samy entry, change your keyboard language to Greek (i think it might happen the same thing with other languages too , like russian etc), and use again the Autotype button. 
4. It will output  **username: πανοστεστ@γμαιλ.ψομ,  password: τεστπασσ**

## Context

This error basically messes up your form submitions every time you change your keyboard language.

## Debug Info

KeePassXC - 2.3.4
Revision: REVISION

Libraries:
- LIBS

Operating system: Linux Ubuntu 18.04 Bionic Beaver
CPU architecture: ARCH
Kernel: KERNEL

Enabled extensions:
- No extensions enabled

**Comment by varjolintu** [comment] 2018-11-14 06:41
I assume you are talking about Auto-Type?

**Comment by pankaryp** [comment] 2018-11-14 07:39
> I assume you are talking about Auto-Type?

Yes, i editted my post. Thanks.

**Comment by jicama** [comment] 2019-07-30 03:22
This also affects other layouts for the same language; when my keyboard is set to the Dvorak layout, auto-type turns "jason" into "haorb".

**Comment by droidmonkey** [comment] 2019-07-30 11:29
This is actually a duplicate issue

**Comment by droidmonkey** [comment] 2019-07-31 01:50
I'm not even sure how to fix this... we would have to temporarily switch your keyboard to english (probably some OS API calls there), perform the auto-type sequence, then switch your keyboard back to the original layout. Technically we are not doing anything "wrong" here because if you yourself would type in the login information using the Greek keyboard layout it would come out all wrong as well, correct?

**Comment by pankaryp** [comment] 2019-08-03 14:30
Not in Windows 10 tho. If i type in the login information using the Greek Keyboard layout, on Windows 10, it would come out all correct according the saved entry in the keepass database.

**Comment by Raigedas** [comment] 2020-03-01 15:10
Another acceptable workaround would be to configure a specific key combination (for ecample Ctrl+Shift+1) for enabling custom layout in Linux and then setup KeePaasXC to hit that key combination before typing a password but unfortunately KeePassXC does not have support for hitting any of Ctrl/Alt/Shift.

**Comment by Raigedas** [comment] 2020-03-01 15:12
Another acceptable workaround would be to configure a specific key combination (for ecample Ctrl+Shift+1) for enabling english layout in Linux and then setup KeePaasXC to hit that key combination before typing a password but unfortunately KeePassXC does not have support for hitting any of Ctrl/Alt/Shift.

**Comment by phoerious** [comment] 2020-06-01 08:49
This is pretty much the opposite of #324. Typing in Greek characters if Greek is enabled is the expected behaviour. Auto-Type simply emulates keystrokes. Your keyboard layout must have the desired characters, so I don't think we can fix that. Auto-Type in Windows works differently, so it's possible that don't see the issue there. I'm closing this as WONTFIX / CANTFIX.

**Closed by phoerious** 2020-06-01 08:49 UTC
Labels: bug, plugin: Auto-Type

**Comment by vetko** [comment] 2020-07-31 15:53
> Auto-Type simply emulates keystrokes.

_Disclaimer: I don't know much about how Linux / X programming works._

Is this the only possible implementation for Linux? Is Auto-type really bound to the active keyboard layout?
Why is it not possible to just send to the target window the actual character(s) saved in the DB, without not involving keyboard layouts in the game?

Additional info which might help: I am also using **KeeWeb** (https://github.com/keeweb/keeweb) which is working properly in every scenario, whatever keyboard layout I have active. As far as I know it uses `xdotool` to perform the Auto-type. Would that help here?

**Comment by HacKanCuBa** [comment] 2020-07-31 17:45
> Additional info which might help: I am also using **KeeWeb** (https://github.com/keeweb/keeweb) which is working properly in every scenario, whatever keyboard layout I have active. As far as I know it uses `xdotool` to perform the Auto-type. Would that help here?

I thought something like that, but now I must warn: `xdotool` [doesn't work in Wayland](https://github.com/bulletmark/libinput-gestures/issues/27#issuecomment-283506408) :( (damn!) whereas the current KeePassXC implementation (whatever is they are doing) does work fine.

So whichever solution is picked will have to be something else.

**Comment by sdragnev** [comment] 2020-10-20 15:52
> > Auto-Type simply emulates keystrokes.
>
> Why is it not possible to just send to the target window the actual character(s) saved in the DB, without not involving keyboard layouts in the game?

That does seem like a better solution. Especially assuming you can use any UTF-8 character as part of a password.

**Comment by droidmonkey** [comment] 2020-10-20 16:19
Thats not how interapplication communications work, unfortunately
