### ISSUE TITLE
--pw-stdin stopped working with KeePassXC 2.3

### ISSUE THREAD

**Issue by devkid** [keepassxreboot/keepassxc#1600] opened 2018-03-02 19:06 UTC
## Expected Behavior
Passing `--pw-stdin` on the command line (and passing the password to stdin) should open the database on startup.

## Current Behavior
KeePassXC starts with the welcome screen and doesn't open any databases.

## Context
Happens with my older database as well as with a newly created database. Adding `--keyfile` doesn't work either.

## Debug Info
KeePassXC - Version 2.3.0
Revision: 4c0ed74

Libraries:
- Qt 5.10.1
- libgcrypt 1.8.2

Operating system: Arch Linux
CPU-Architektur: x86_64
Kernel: linux 4.15.3-2-ARCH

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by TheChiefMeat** [comment] 2018-03-02 21:25
Yep, the code for launching the database via a terminal is now completely missing from the main.cpp:

 ```
   const bool pwstdin = parser.isSet(pwstdinOption);
    for (const QString& filename: fileNames) {
        if (!filename.isEmpty() && QFile::exists(filename) && !filename.endsWith(".json", Qt::CaseInsensitive)) {
            QString password;
            if (pwstdin) {
                static QTextStream in(stdin, QIODevice::ReadOnly);
                password = in.readLine();
            }
        }
    }

    int exitCode = app.exec();

```

**Comment by joanbm** [comment] 2018-03-02 21:51
Same issue here, I can confirm that @TheChiefMeat 's solution works.

**Comment by Generator** [comment] 2018-03-02 23:14
This is a duplicate of #1358

**Comment by phoerious** [comment] 2018-03-02 23:41
Probably even the same #1533

**Comment by phoerious** [comment] 2018-03-03 00:38
Indeed, it is.

**Closed by phoerious** 2018-03-03 00:38 UTC
Labels: duplicate
