### ISSUE TITLE
Differentiate The Same Entry from Different Databases in Global Auto-Type

### ISSUE THREAD

**Issue by tunaflsh** [keepassxreboot/keepassxc#10533] opened 2024-04-02 05:24 UTC
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )

Two databases. Same entry, but different passwords of course. There is no way to tell them apart in the auto-type window.

![image](https://github.com/keepassxreboot/keepassxc/assets/86954679/90a9a51b-98e5-437d-a96f-aa45198475f4)

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )

Have a column for Database name (and location, since the names can be the same too)

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )

My situation happened, because of auto-save and lack of undo functionality. So I had to open a second database from the version control system. This in itself could be solved by manually copying instead of auto-typing, but the ability to configure the auto-type window and to distinguish different entries just felt like a natural feature to have.

**Comment by droidmonkey** [comment] 2024-04-02 10:18
Duplicate of #1416

Although, in the scenario you describe, just change the title of one of the entries if it is indeed different and meant to be that way.

**Closed as not planned by droidmonkey** 2024-04-02 10:19 UTC
