### ISSUE TITLE
Can't input Japanese character

### ISSUE THREAD

**Issue by CleanDiesel** [keepassxreboot/keepassxc#6583] opened 2021-06-01 11:34 UTC
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
I can't input Japanese character (ex.こんにちは)

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Be able to input Japanese on your system
2. Input Japanese on KeepassXC

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Japanese character will be entered (ex. こんにちは)

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
English is entered (ex. konnnitiha)

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.4
Revision: 34a78f0

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux(Ubuntu)
Desktop Env: Gnome
Windowing System: Wayland

**Comment by droidmonkey** [comment] 2021-06-01 11:53
Need much more info, where does this happen in the program

**Comment by jessesung** [comment] 2021-06-04 08:06
I can reproduce the issue so let me fill in the info.  :)

Input method works w/o any problem with the keepassxc debian package. This issue can only happen with the keepassxc snap.

When using the debian packaged one, I can always use the shortcut key to launch the input method when I want to input something, like the name and the comment of an entry.

On the other hand, in the snap one the shortcut key doesn't seems to do anything.

According to [Compatibility with CJKV input method frameworks](https://forum.snapcraft.io/t/compatibility-with-cjkv-input-method-frameworks/7788), in order to make input method work one would need to 1. connect to the desktop-legacy interface and 2. incoporate one of the desktop-helpers remote part and launch the app using the desktop-launch launcher. But seems that both are already in the keepassxc snap so I'm not sure what is going wrong...

**Comment by droidmonkey** [comment] 2021-06-04 09:58
Ok this would be a snap big then. Snaps are a hot mess, you could try installing the snap in classic mode to remove the sandbox. 

`snap install keepassxc --classic`

**Comment by jessesung** [comment] 2021-06-04 10:15
Since input method works with my other snaps (telegram-desktop, thunderbird, chromium, ...), I would guess this can be fixed by modifying the snap/ directory.

**Comment by CleanDiesel** [comment] 2021-06-11 02:09
I use ubuntuPPA version.

**Comment by jessesung** [comment] 2021-06-16 05:28
@CleanDiesel  I tried the PPA one (version 2.6.6-1ppa1~hirsute1) and it works with my input framework (fcitx). For your reference I tested it with Ubuntu 21.04/Gnome/Wayland.

**Comment by jessesung** [comment] 2021-06-16 05:39
@droidmonkey

The `--classic` option doesn't seem to work. In `snap list` it isn't listed as a classic snap. Guess it only works when you explicitly set confinement to classic.

On the other hand, I tried `--devmode` and `snap list` confirms that keepassxc is in devmode. Unfortunately this issue can still be reproduced.

**Comment by et2010** [comment] 2021-10-23 21:41
I'm facing the same problem. I use fcitx and cannot input Chinese in the search box.

os: archlinux
keepassxc: 2.6.6 (community)

**Comment by luni3359** [comment] 2022-06-06 04:01
I can input characters just fine using fcitx+mozc, but when the database is locked you aren't able to switch between languages which is troublesome if you're using to typing your passwords in your specific language, because you'll be locked into that specific language layout.

It is really important to note that you can make the IME responsive again if you click the eye to reveal the password. It just doesn't work with obfuscated fields.

I'm using fcitx 4.2.9.7 with mozc 2.26.4220.100+dfsg-5.2ubuntu1~focal1. No wayland.

**Comment by Aikatsui** [comment] 2023-02-18 10:50
@CleanDiesel @droidmonkey you can modify the issue title.

Today i tested snap, flatpak and .deb versions (2.7.4) with multiple scripts.

.deb - chinese, korean, nepali, sinhala, thai (all works)
flatpak - all works
snap - nepali, thai (works) | chinese, korean, sinhala (not work)

i can't guess why

Ubuntu 22.04.01

**Comment by droidmonkey** [comment] 2023-02-18 13:06
We no longer support snap for these reasons, just use flatpak

**Closed** 2023-02-18 13:05 UTC
Labels: platform: Linux, platform: Linux - Wayland, distribution: Snap

**Comment by luni3359** [comment] 2023-02-19 00:00
Not being able to switch languages within the password input is still an issue with the normal binary/flatpak.

**Comment by droidmonkey** [comment] 2023-02-19 00:34
That is a qt bug

**Comment by Aikatsui** [comment] 2023-02-21 02:30
> We no longer support snap for these reasons, just use flatpak

@luni3359  But as you mentioned above, I don't see this problem in snaps like chromium, libreOffice, telegram, onlyoffice, firefox etc. If this is not a keepassxc issue, you can report the bug to the snap team (launchpad.net) with a link to this discussion.

> Not being able to switch languages within the password input is still an issue with the normal binary/flatpak.
>> That is a qt bug

I can switch between e.g. chinese, japanese, nepali, sinhalese etc and type but sometimes stop working and only print english characters. To solve the problem, i usually move to english keyboard and move back to required keyboard

**Comment by droidmonkey** [comment] 2023-02-21 03:13
I've already poured a ton of hours trying to fix snap issues and they usually are unfixable because you either need to develop a custom wrapper and some voodoo magic or you can't fix it at all because you are using Qt/KDE base. The simple fact is snaps do not work out of the box, we aren't doing anything exotic at all, and the flatpak works fine without ANY workarounds.

**Comment by luni3359** [comment] 2023-02-23 00:30
@Aikatsui Like I said I use the binary not the snap, but he said it's a qt bug so yeah I can understand that. If you say that switching languages on the password field works for you on the snap then the snap is probably doing something to intercept the input change.
