### ISSUE TITLE
gpg: Can't check signature: No public key

### ISSUE THREAD

**Issue by bartatgithub** [keepassxreboot/keepassxc#1918] opened 2018-05-07 14:34 UTC
During GPG check i get: `gpg: Can't check signature: No public key`

## Expected Behavior
Proper GPG check

## Current Behavior
During GPG check i get: `gpg: Can't check signature: No public key`

## Possible Solution
?

## Steps to Reproduce (for bugs)
1. open MacOS Terminal
2. `gpg --verify /Volumes/user/********/Downloads/KeePassXC-2.3.1.dmg.sig`
3. 
```
gpg: directory '/Volumes/user/********/.gnupg' created
gpg: keybox '/Volumes/user/********/.gnupg/pubring.kbx' created
gpg: assuming signed data in '/Volumes/user/********/Downloads/KeePassXC-2.3.1.dmg'
gpg: Signature made Tue Mar  6 23:17:55 2018 CET
gpg:                using RSA key C1E4CBA3AD78D3AFD894F9E0B7A66F03B59076A8
gpg: Can't check signature: No public key
```

## Context
I try to check the GPG signature before installing. 

## Debug Info
KeePassXC-2.3.1.dmg
KeePassXC-2.3.1.dmg.sig

Operating system: MacOS 10.10.5

Enabled extensions: NONE

**Comment by TheZ3ro** [comment] 2018-05-07 16:13
Please check out the Verifying Signatures guide: https://keepassxc.org/verifying-signatures/

**Comment by droidmonkey** [comment] 2018-05-07 16:18
Closing since this is user error

**Closed** 2018-05-07 16:17 UTC

**Comment by bartatgithub** [comment] 2018-05-07 18:41
That's exactly the page that i have followed up. I would never start a thread on a forum or github if i haven't searched all possible solution that i van find on the web. 


Tomorrow i am back on that computer, to test more.

**Comment by TheZ3ro** [comment] 2018-05-07 20:46
The step to reproduce only list the `--verify` command. 
You have to execute `gpg --import` or `gpg --fetch-keys` as well.

**Comment by bartatgithub** [comment] 2018-05-08 10:11
Then sorry to disturb.
Your help page about signaturen verification isn't too clear. 
Thanks


On 8 May 2018 00:22:17 CEST, Jonathan White <notifications@github.com> wrote:
>Your issue is you have not imported our public key into your keyring.
>You skipped a step.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/keepassxreboot/keepassxc/issues/1918#issuecomment-387224998

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
