### ISSUE TITLE
chromeIPass requests credentials that don't have a URL specified

### ISSUE THREAD

**Issue by derhagen** [keepassxreboot/keepassxc#1086] opened 2017-10-18 12:10 UTC
When visiting a website for which I don't have any credentials yet, chromeIPass requests credentials from my database which don't have a URL specified. I first noticed this a few days ago (possibly after updating to 2.2.1) on the login page at adobe.com, which requested my Uber credentials (that dont have a URL set in the database).

chromeIPass Version:2.8.1

KeePassXC - Version 2.2.1
Revision: 2bce9c8add07226e9a05e9e0fd0e5e66b236d5b6

Libraries:
- Qt 5.7.1
- libgcrypt 1.7.8

Operating system: Fedora 26 (Workstation Edition)
CPU architecture: x86_64
Kernel: linux 4.13.5-200.fc26.x86_64

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

**Comment by phoerious** [comment] 2017-10-18 14:57
Duplicate of #1080

**Closed by phoerious** 2017-10-18 14:57 UTC
