### ISSUE TITLE
Unable to Download Favicon

### ISSUE THREAD

**Issue by Nerdfest** [keepassxreboot/keepassxc#261] opened 2017-02-06 21:22 UTC
Selecting the "Download favicon" button results in "Unable to fetch favicon" being displayed in seemingly all cases. I have the URL of the site filled in, which I;''m making the assumption is the source that is used for the attempted retrieval. An example would be "https://www.nytimes.com/"

## Expected Behavior

I expect that the favicon would be downloaded and selected as the current icon. My apologies if I'm making an invalid assumption or have missed some instructions.

## Current Behavior

The download attempt results in an error message stating the icon can't be downloaded.

## Steps to Reproduce (for bugs)

1. Select an entry with a filled URl.
2. Select the Icon entry on the left attribute list
3. Select the "Download Favicon button."

## Your Environment

* KeePassXC version/commit used: 2.10/b6f754c29a7cf3a2365fea4487395a9f9741055c
* Qt version: 5.6.1
* Operating System and version: 
This occurs running under Kubuntu Linux 16.10. fully patched as of the current date, with KeePassXC installed via Snap.

**Comment by phoerious** [comment] 2017-02-06 22:02
Does it work when you save the entry first, then reopen it and try again?

**Comment by Nerdfest** [comment] 2017-02-06 22:40
It does not. I tried a few variations, including with and without http/https. It seems to always do the same thing.  I'm wondering if the version I have installed through Snap is fully featured, as thing like automatic reloading when the underlying file changes don't seem to be working either.

**Comment by phoerious** [comment] 2017-02-06 23:22
Can you try the AppImage or DEB instead and tell me if it works with them?

**Comment by Nerdfest** [comment] 2017-02-07 00:18
It works correctly.

**Comment by phoerious** [comment] 2017-02-07 00:19
Then I think this is a duplicate of #258

**Closed by phoerious** 2017-02-07 00:19 UTC

**Comment by Nerdfest** [comment] 2017-02-07 00:22
Cool. Same with not seeing file system changes perhaps?

**Comment by phoerious** [comment] 2017-02-07 00:28
I suppose.

**Comment by applesea2** [comment] 2017-08-17 04:02
I have the same problem, but on Windows. Any idea how to fix it?

**Comment by unai-ndz** [comment] 2017-09-08 10:14
Same error on windows. The app image on linux works well.

**Comment by vlenzer** [comment] 2017-11-07 13:44
Got same error on Windows 8.1 and Linux Mint. Both versions are 2.2.2..

**Comment by droidmonkey** [comment] 2017-11-07 14:44
This is being fixed in an existing PR that i am working on.

**Comment by LinusMoBo** [comment] 2018-07-02 13:35
I still have the Problem.. (Win8.1)

**Comment by gggomg** [comment] 2018-08-30 04:32
Good day, same problem exists for me on Windows 10 with x64 version of keepassxc. Thank you for your work and attention.
