### ISSUE TITLE
counter the number of records in the database

### ISSUE THREAD

**Issue by torerobo** [keepassxreboot/keepassxc#2269] opened 2018-09-06 09:30 UTC
Make the function "counter the number of records in the database."
The problem is that I'm working and synchronizing different databases, because of this I am making new entries to the old database.

The android counter implemented in the keepassdroid in keepass2 also has a counter, why is not there? Because of such little things, huge problems.

**Comment by droidmonkey** [comment] 2018-09-06 11:54
Duplicate of #2034

**Closed by droidmonkey** 2018-09-06 11:54 UTC
