### ISSUE TITLE
SSH Agent Add/Remove fast access

### ISSUE THREAD

**Issue by OlivierMary** [keepassxreboot/keepassxc#2200] opened 2018-08-14 09:45 UTC
Since KepassXC add SSH Agent feature I have many ssh keys (1 / server) 
All controled by keepassxc.
But With many keys and auto-add to agent feature it's impossible to connect to certains server cause "Too many Authentication Failures" cause by "MaxAuthTries limit " default value is 6.

So I added auto some keys and others I added them to agent manually.

It's for this case it's very long to access to the "Add to agent" button.
## Expected Behavior

Just one / two action to add or remove to agent a ssh key

## Current Behavior

Too many step to access to "add to agent" or "remove to agent"

## Possible Solution

Add a fast access to "add to agent" and "remove to agent" feature. 
With button in toolbar or with right click on an ssh entry

## Steps to Reproduce (for bugs)

N/A

## Context

Easier use of ssh agent features

## Debug Info

KeePassXC - Version 2.3.3
Revision: 0a155d8

Libraries:
- Qt 5.10.1
- libgcrypt 1.8.2

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.17134

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by hifi** [comment] 2018-08-15 16:00
Essentially a duplicate of #1815. Add more comments to that if you feel something is missing.

A tip to use all keys in the same agent: you can have the public keys exported into `.pub` files and then use that as the `IdentityFile` of a single `Host` in your `~/.ssh/config`. It prevent OpenSSH from sending any other keys to the host and you can then pretty much have any number of keys loaded into the agent. You can most likely also set a default key with `Host *`.

That might not be ideal in your use case but in case you didn't know.

**Closed by hifi** 2018-08-15 16:00 UTC

**Comment by OlivierMary** [comment] 2018-08-19 08:26
Ok @hifi  will try this, I thought it was necessary to have the private key in `.ssh/config`

**Comment by OlivierMary** [comment] 2018-08-20 18:05
@hifi this works perfectly
