### ISSUE TITLE
Bug on vers. 2.5 on macOS Catalina 10.15.1

### ISSUE THREAD

**Issue by Florxy** [keepassxreboot/keepassxc#3799] opened 2019-11-05 15:23 UTC
hi, just installed the update 2.5 on my Mac book pro 13. The installation was fine and at the point of starting the app it shows me the bug called: (from German translated by my own) 
„KeePassXC“ couldn't open, because apple can not see if there is any malware inside
more it says: 
The Software should be updated to function normally.. 
Please close this bug or bring an update that function on this machine. 

The German version: 
„KeePassXC“ kann nicht geöffnet werden, da Apple darin nicht nach Schadsoftware suchen kann.

Diese Software muss aktualisiert werden. Wende dich an den Entwickler, um weitere Informationen zu erhalten.
Safari hat diese Datei heute um 16:00 von github-production-release-asset-2e65be.s3.amazonaws.com geladen.

**Comment by phoerious** [comment] 2019-11-05 15:59
Duplicate of #3685.

**Closed by phoerious** 2019-11-05 15:59 UTC
Labels: duplicate
