### ISSUE TITLE
MacOS: no focus on Keepassxc window after pressing global auto-type shortcut

### ISSUE THREAD

**Issue by klara31** [keepassxreboot/keepassxc#1192] opened 2017-11-18 09:03 UTC
After pressing the global auto-type shortcut, KeepassXC opens, but does not get focus. Focus remains on the web browser. When typing the Keepass password, the password is visible in the website.

## Expected Behavior
Make KeepassXC getting focus, so that the password for the Keepass DB is entered in KeepassXC and not in the website

## Debug Info
KeePassXC - 2.22

Operating system: MacOS 10.13.1

**Comment by phoerious** [comment] 2017-11-18 10:08
Duplicate of #1023

**Closed by phoerious** 2017-11-18 10:09 UTC
