### ISSUE TITLE
Let global Auto-Type keyboard shortcut show search window

### ISSUE THREAD

**Issue by irgendsontyp** [keepassxreboot/keepassxc#2075] opened 2018-06-26 23:49 UTC
First of all: I know there's something similar already included in KeePassXC: You can right-click an entry and select "Perform Auto-Type". But I think there's a more comfortable way to achieve the same thing:

Sometimes there are situations in which the title of the window where the password shall be entered by global Auto-Type is not enough for automatically finding the correct password entry. So one ends up with KeePassXC showing a dialog box saying "Couldn't find an entry that matches the window title: ...". It would be really great if in this case the user got offered the "select entry" dialog with an input field for searching through all entries (of course this might be a configuration option which turns this on or off). The user can search for the desired password entry in this dialog by typing in a string which is contained in the entry's title (and maybe some additional fields?). Then, all matching entries are displayed (in most cases this would probably be only one entry), the user can navigate through the entries with the keyboard and press enter for the selected password to be Auto-Typed. 

What do you think?

**Comment by kneitinger** [comment] 2018-07-01 19:10
So while I do think this isn't strictly __necessary__ due to the `Entry->View/Edit Entry->Auto-Type->Window-Associations` settings, this is still a nice idea.

Something else to consider is if the proposed search dialog could then add an association to selected entry, so that it would just work next time.

**Comment by irgendsontyp** [comment] 2018-07-01 19:35
I thought of windows like this one:

![image](https://user-images.githubusercontent.com/7070216/42137954-7f8e65c8-7d75-11e8-86c1-9d075fcb4540.png)

Of couse one could use "Authenticate" as window association in KeePassXC's current state. If more than one application had that association, the user could still select the right entry. But wouldn't it be great if the user had the chance to type in a keyword in order to search for the right entry? This might make the workflow more convenient as you do not have to visually find the right entry but rather type in some words and press enter.

Another thing bringing me to this issue's idea was a website which had "Change password..." as the website title (that was the whole title - no name of the website or anything else). Users frequently changing their web accounts' passwords would certainly be happy if they had the ability to search for the entry which they want to change the password for.

**Comment by kneitinger** [comment] 2018-10-09 04:12
This is a duplicate of #429

**Closed** 2018-10-09 14:38 UTC
Labels: plugin: Auto-Type, user interface, wishlist
