### ISSUE TITLE
Screen is dimmed after Auto-Type

### ISSUE THREAD

**Issue by ghost** [keepassxreboot/keepassxc#8153] opened 2022-06-14 18:48 UTC
## Overview
If "ask always before Auto-Type" is activated, the screen is dimmed after performing Auto-Type.
![Screenshot from 2022-06-14 20-27-17](https://user-images.githubusercontent.com/76070679/173663010-3bfeffef-9fdc-49ce-a0d4-318a82402ae0.png)

## Info's
KeePassXC - Version 2.7.1
Revision: 5916a8f

Qt 5.15.4
Debugging mode is disabled.

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 5.18.3-arch1-1

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.19.2
---
Operating System: Linux
Desktop Env: Gnome
Windowing System: Wayland

**Comment by droidmonkey** [comment] 2022-06-14 20:05
What do you mean the screen is dimmed?

**Comment by phoerious** [comment] 2022-06-15 07:00
Looks like your window manager is doing something fancy. Is this what usually happens when a modal window opens in an app?

**Comment by ghost** [comment] 2022-06-15 09:51
> What do you mean the screen is dimmed?

Before Auto-Type:
![Screenshot from 2022-06-15 11-34-23](https://user-images.githubusercontent.com/76070679/173795907-54bbe5ed-54d6-4e91-aff2-61bf5731b7bf.png)

After Auto-Type:
![Screenshot from 2022-06-15 11-37-42](https://user-images.githubusercontent.com/76070679/173796186-4bd65111-ad37-4274-9df3-f4020fb57125.png)

> Looks like your window manager is doing something fancy. Is this what usually happens when a modal window opens in an app?

I tested a bit and it looks like you're right.
![Screenshot from 2022-06-15 11-37-25](https://user-images.githubusercontent.com/76070679/173796864-45d2dea5-c346-4a79-86dc-dff26a979f11.png)
![Screenshot from 2022-06-15 11-41-48](https://user-images.githubusercontent.com/76070679/173797073-6cb10a3b-3248-447f-98ee-68391bc341fd.png)
![Screenshot from 2022-06-15 11-50-39](https://user-images.githubusercontent.com/76070679/173798871-71f8d223-6ec5-4203-9483-b372a92aaf67.png)

But it should be still a bug in KeePass because in all other apps the shadow in the background is removed after closing the modal window.

**Comment by ghost** [comment] 2022-06-15 09:59
I looked if there are other modal windows in KeePass, I just found one but at this window the background shadow works as expected.
![Screenshot from 2022-06-15 11-52-29](https://user-images.githubusercontent.com/76070679/173800264-b2df2b16-d909-4c09-93bb-81b51446d9de.png)
![Screenshot from 2022-06-15 11-52-34](https://user-images.githubusercontent.com/76070679/173800274-631cd428-9f7d-4bf7-89e9-de194bbb2fbe.png)

**Comment by droidmonkey** [comment] 2022-06-15 10:06
This can't possibly be "our" bug for a couple reasons: we don't dim our own window, we don't ask for the window to be dimmed, this happens on no other platform. 

You are comparing two different types of modal window. Try editing an entry and press cancel. Then cancel that pop-up. Does it happen again?

This could be qwayland acting dumb. It could also be a bad interaction between gnome and Auto-Type specifically (hence the above test), but I doubt that.

**Comment by ghost** [comment] 2022-06-15 10:15
> This can't possibly be "our" bug for a couple reasons: we don't dim our own window, we don't ask for the window to be dimmed, this happens on no other platform.
> 
> You are comparing two different types of modal window. Try editing an entry and press cancel. Then cancel that pop-up. Does it happen again?
> 
> This could be qwayland acting dumb. It could also be a bad interaction between gnome and Auto-Type specifically (hence the above test), but I doubt that.

Confirmation window:
![Screenshot from 2022-06-15 12-09-51](https://user-images.githubusercontent.com/76070679/173803024-2a9fbc4f-b943-4f7c-bdb7-0d8bebfda003.png)

After clicking "Cancel":
![Screenshot from 2022-06-15 12-10-00](https://user-images.githubusercontent.com/76070679/173803427-80c647b2-0ae7-4f27-a8f7-c77ab97716ed.png)

After clicking "Close without Saving":
![Screenshot from 2022-06-15 12-10-10](https://user-images.githubusercontent.com/76070679/173803574-cb4bfff7-ff23-4118-95ca-b62170179ac5.png)

After clicking "Save":
![Screenshot from 2022-06-15 12-10-25](https://user-images.githubusercontent.com/76070679/173803696-53ea58d5-c567-45ed-a39d-df04eb4bb15e.png)

**Comment by droidmonkey** [comment] 2022-06-15 10:51
It could be because we send the window to the background when Auto-Type starts that the dimmed state never gets reset by gnome. This should be a bug report to them. 

Does it undim if you press cancel instead of ok on the autotype question?

**Comment by ghost** [comment] 2022-06-15 11:56
> It could be because we send the window to the background when Auto-Type starts that the dimmed state never gets reset by gnome. This should be a bug report to them.
> 
> Does it undim if you press cancel instead of ok on the autotype question?

Yes, when i cancel it it is normal.
I'll report it to gnome.

**Comment by phoerious** [comment] 2022-06-15 12:15
Closing this here then.

**Closed as not planned by phoerious** 2022-06-15 12:15 UTC
Labels: downstream

**Comment by jonas2515** [comment] 2022-06-29 16:20
There's https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/2473 to allow minimizing modals in mutter now.

That said, from the compositor side of things, given that the concept behind modals is essentially "this window should *always* be on top of other windows of the app", it doesn't make a lot of sense to allow minimizing modal dialogs. It might make more sense to just forbid that and print a warning in mutter instead.

Is there a reason why KeePassXC needs this exact behavior of minimizing a modal instead of just closing it?

**Comment by droidmonkey** [comment] 2022-06-29 16:58
We don't minimize modal dialogs.

**Comment by jonas2515** [comment] 2022-06-30 08:35
Ahh alright, turns out the reproducer we found on the gnome-shell [bugreport](https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/5581) was different from this issue. This issue is caused by gnome-shell not syncing dimmed state after the undimming animation got cancelled, see https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/2349.
