### ISSUE TITLE
AutoType not working since 2.6.0

### ISSUE THREAD

**Issue by sven-frotscher** [keepassxreboot/keepassxc#4985] opened 2020-07-08 19:25 UTC
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Since updating to 2.6.0, AutoType does not work correctly for me, the KeePassXC window fails to minimize.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
Activate AutoType from an entry of your choice.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
The KeePassXC window minimizes itself and the AutoType sequence is sent to the previously focused window. (That's how it worked before the update.)

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
The KeePassXC window tries to minimize itself but gets restored almost immediately. KPXC then autotypes into itself.

## Context
[NOTE]: # ( Give us any additional information you may have. )

### Diagnostic info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.0
Revision: 0765954

Qt 5.9.5
Diagnosemodus ist deaktiviert.

Betriebssystem: Ubuntu 18.04.4 LTS
CPU-Architektur: x86_64
Kernel: linux 4.15.0-109-generic

Aktivierte Erweiterungen:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare (bestätigtes und unbestätigtes Teilen)
- YubiKey
- Secret-Service-Integration

Kryptographische Bibliotheken:
 libgcrypt 1.8.1

### Environment
[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
KeePassXC installed using: [phoerious' PPA](https://launchpad.net/~phoerious/+archive/ubuntu/keepassxc)
Desktop Env: Budgie (like Gnome/based on Gnome 3.28.2)
Windowing System: X11

**Comment by doubleloop** [comment] 2020-07-08 21:44
Same issue here.

## Diagnostic info
KeePassXC - Version 2.6.0
Revision: 0765954

Qt 5.14.2
Debugging mode is disabled.

Operating system: Debian GNU/Linux bullseye/sid
CPU architecture: x86_64
Kernel: linux 5.7.0-1-amd64

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.5

## Environment
Operating System: Linux
Desktop Env: GNOME Shell 3.36.3 
Windowing System: X11

**Comment by sven-frotscher** [comment] 2020-07-09 12:57
Same here. The "failing to minimize" thing only happens when trying to "Hide when minimized".

**Comment by droidmonkey** [comment] 2020-07-10 01:03
Duplicate of #4962

**Closed by droidmonkey** 2020-07-10 01:03 UTC
Labels: bug
