### ISSUE TITLE
URL with ssh scheme  doesn't display in the details window

### ISSUE THREAD

**Issue by wesamly** [keepassxreboot/keepassxc#1763] opened 2018-03-21 08:23 UTC
## Expected Behavior

I have url like: ssh://root@example.com, I associate ssh with iTerm2 so that when I click the URL it opens directly in iTerm.

## Current Behavior

After version 2.3.0 the URL no longer shows in the Entries table, but when I click the URL

 placeholder it opens the iTerm window, it is hidden but working!

## Possible Solution

Please fix guys,
## Steps to Reproduce (for bugs)

1. Enter a URL with ssh://, e.g. ssh://root@example.com
2. Save and go to Entries table,
3. The URL should be hidden, but if you click it works.

## Debug Info

KeePassXC - Version 2.3.1
Revision: 2fcaeea

Libraries:
- Qt 5.9.3
- libgcrypt 1.8.2

Operating system: macOS Sierra (10.12)
CPU architecture: x86_64
Kernel: darwin 16.7.0

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

## Screenshot
![screen shot 2018-03-21 at 10 20 00 am](https://user-images.githubusercontent.com/389138/37699817-c902eb90-2cf1-11e8-84b4-dfe37936766e.png)

**Comment by TheZ3ro** [comment] 2018-03-21 13:45
Woops, duplicate of #1424. Closing

**Closed as completed by TheZ3ro** 2018-03-21 13:45 UTC
Labels: duplicate
