### ISSUE TITLE
KeepassXC does not open in foreground on MacOS

### ISSUE THREAD

**Issue by realrolfje** [keepassxreboot/keepassxc#8550] opened 2022-10-06 10:47 UTC
## Overview
When opening KeepassXC on MacOS, it opens the window in the background. After opening the user needs to first look for the window, click it to give focus, and then type the password to open the database.

## Steps to Reproduce
1. Install KeepassXC.app (version 2.7.1) in the /Application folder, open it and close it (to get rid of the "This app is downloaded from internet" warning).
2. Open other applications (have open windows on your screen)
3. Open KeepassXC by clicking on your password file.  

## Expected Behavior
KeepassXC opens in the foreground, with cursor focus in the password box.

## Actual Behavior
KeepassXC window opens burried behind all other application windows, has no focus.

## Context
"Minimize application at startup" is NOT set. (I was not able to create a screenshot of keepassxc)below.

KeePassXC - Version 2.7.1
Revision: 5916a8f

Qt 5.15.2
Debugging mode is disabled.

Operating system: macOS 12.6
CPU architecture: arm64
Kernel: darwin 21.6.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.19.1

Operating System: macOS

**Comment by varjolintu** [comment] 2022-10-07 04:39
Does it behave normally if you just open KeePassXC without clicking a database file?

**Comment by droidmonkey** [comment] 2022-10-07 10:21
I can't reproduce the described behavior. However I do notice when the window is hidden to tray opening a kdbx file does not unhide the window.

**Comment by pfiaux** [comment] 2022-10-09 09:18
Similar here, I'll add some details since it might be the same under laying issue. I can't say for sure about the initial open I feel it might have happened to me as well.
It also happens to me often when hidden to try I open it from tray using Alfred (haven't tested with spotlight) it behaves inconsistently:
* Sometimes it pops up to foreground as expected
* Other times the Keepass window will open (I can see it in the back) but behind the window the currently has the focus. (so it is unhiding, but not focusing)
    * Using Alfred again to "open" it will correctly bring it to the foreground.

Note: it only started happening after upgrade to macOS Monterey for me.

**Comment by varjolintu** [comment] 2022-10-09 09:57
The only time this has been happening to me is when I've been debugging KeePassXC or starting it directly from zsh (macOS still). And still it's quite random. I'd say it's either OS or Qt bug.

**Comment by phoerious** [comment] 2022-10-18 07:33
Since we are unable to reproduce this issue, I'm closing this. Please reopen if you find a way to reproduce it reliably.

**Comment by realrolfje** [comment] 2022-10-18 08:06
Closed issues disappear off radar, so I guess I need to find another solution, because the focus problem is really really annoying in my daily work. I'll look if I can find a workaround or else an alternative to KeepassXC. Tips are welcome, thanks!

**Comment by phoerious** [comment] 2022-10-18 08:08
Do you have "minimise window at application startup" enabled maybe?

**Comment by realrolfje** [comment] 2022-10-18 09:55
Definitely not, see my original bug report. Besides, the window is not minimized. It opens in the background (visible, but behind all other windows, without focus)

**Comment by maarten03** [comment] 2022-11-01 09:58
I experience the exact same behavior.

**Comment by henningn** [comment] 2023-11-29 13:31
I've just discovered that MacOS has this feature where a program opens in the background when a password field (e. g. <input type="password> in a browser) is selected. This avoids writing parts of a password into other programs.

So this is probably not an issue at all and it also explains why it was not reproducible.

**Comment by ddickstein** [comment] 2024-09-26 10:41
@henningn can you elaborate a bit on "avoids writing parts of a password into other programs"? I'm not sure I'm properly visualizing the scenario that's prevented by the current behavior. It seems to me that the danger would be inadvertently entering data intended for another application into the one that's focused - that is, I'd expect that if keepassxc were brought to the foreground with its password field focused, the danger would be that you might accidentally type something that isn't your password into the password field, not that you might accidentally type something that is your password into some other application.

Since I'm not clear on the scenario here I don't know if this is a viable suggestion, but it seems to me that it would be more convenient to not auto-select the password field for keepassxc, allowing it to be brought into the foreground, and then allow the password field to be selected with `Tab`.

**Comment by droidmonkey** [comment] 2024-09-26 11:01
> the danger would be that you might accidentally type something that isn't your password into the password field, not that you might accidentally type something that is your password into some other application.

You are backwards. The risk is absolutely that another application could steal focus from the password field and cause you to type it in a non password field.

The fix is simple, don't select the password field before invoking auto-type. KeePassXC doesn't automatically select fields for you.

**Comment by ddickstein** [comment] 2024-09-26 12:22
> The fix is simple, don't select the password field before invoking auto-type. KeePassXC doesn't automatically select fields for you.

Although I agree with your recommendation to not select password fields on a webpage before invoking auto-type, I'm confused by this response. I didn't think this issue was about password fields on webpages and auto-type -- I thought this was about the fact that the KeepassXC application window itself does not appear in the foreground when opened. Meaning after I launch it from Raycast/Spotlight/Alfred it appears behind the current application and I need to then manually change the focused window.

When @henningn wrote:
> I've just discovered that MacOS has this feature where a program opens in the background when a password field (e. g. <input type="password> in a browser) is selected.
I had read that as there being a tension between bringing keepassxc into the foreground and the fact that when keepassxc is opened the db password field is selected so you can just start typing. I was suggesting a way to resolve that tension.

As for applications stealing focus, I hadn't thought about that, and it makes sense that that could be an issue, but is that not also a concern when the db password is currently being typed? It seems to me that starting the application in the background is only safe until the application is brought into the foreground. But maybe I'm missing something about how focus stealing works.

**Comment by droidmonkey** [comment] 2024-09-26 18:10
I think I crossed issues, but the fact remains that macos applies unexpected, but potentially useful, behavior on focus stealing based on context. We already bring keepassxc to foreground on launch, not much else we can do if the platform ignores our request.

**Closed as completed** 2024-09-26 18:11 UTC
Labels: platform: macOS

**Comment by phoerious** [comment] 2024-10-09 08:12
I believe this issue is related to  the other window state problem we had on macOS. If you delete the window state setting from your keepassxc.ini, it should fix the problem.
