### ISSUE TITLE
Error installing version of KepassXC 2.3.0

### ISSUE THREAD

**Issue by Faust30000** [keepassxreboot/keepassxc#1552] opened 2018-02-28 10:46 UTC
When installing version 2.3.0, an error occurs with the installation of the library:
**libsodium23_1.0.16-0ppa3~xenial1_amd64.deb**
In the Package Manager Synaptic error can not be fixed.

KeePassXC - Версия 2.3.0
Ревизия: 4c0ed74

Библиотеки:
- Qt 5.5.1
- libgcrypt 1.8.1

Операционная система: Linux Mint 18.3
Архитектура CPU: x86_64
Ядро: linux 4.13.0-36-generic

Включенные расширения:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by RealOrangeOne** [comment] 2018-02-28 10:51
This sounds like it's related to, and possibly a duplicate of https://github.com/keepassxreboot/keepassxc/issues/1545

**Comment by phoerious** [comment] 2018-02-28 11:34
Yes, it is.

**Closed by phoerious** 2018-02-28 11:34 UTC
