### ISSUE TITLE
MacOS 2.4.0 cannot open database that Linux 2.4.0 can

### ISSUE THREAD

**Issue by aserrallerios** [keepassxreboot/keepassxc#2932] opened 2019-04-03 10:45 UTC
The error says:

```
Unable to open the database:
Error while reading the database: Wrong key or database file is corrupt. (HMAC mismatch)
```

The db file is the same in both systems (md5sum checked).

**Comment by phoerious** [comment] 2019-04-03 11:04
Duplicate of #2863.

**Closed by phoerious** 2019-04-03 11:04 UTC
Labels: bug
