### ISSUE TITLE
YubiKey 4 not detected on KeepassXC

### ISSUE THREAD

**Issue by MyWay** [keepassxreboot/keepassxc#754] opened 2017-07-06 12:54 UTC
I installed keepassxc with snap. I insert my YubiKey, but even when clicking on Refresh, the dropdown remains "light grey" as if there were no YubiKeys available and so I cannot set the Challenge-Response. The dropdown, instead, should show a list of connected YubiKeys and let me choose.

KeePassXC - Version 2.2.0
Revision: 9a7e6850d6b79c47c2d46d99fdaf433c2ff13716

Libraries:
- Qt 5.7.1
- libgcrypt 1.7.6-beta

Operating system: Ubuntu Core 16 (Ubuntu 17.04 x64)
CPU architecture: x86_64
Kernel: linux 4.10.0-26-generic

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

**Comment by weslly** [comment] 2017-07-06 13:15
Duplicate of #693

**Closed by weslly** 2017-07-06 13:15 UTC
