### ISSUE TITLE
GUI icons are blurry, looks zoomed

### ISSUE THREAD

**Issue by janhicken** [keepassxreboot/keepassxc#348] opened 2017-02-26 10:55 UTC
As you can see in this screen shot ![screenshot_1](https://cloud.githubusercontent.com/assets/2724840/23338994/d0c0c3f8-fc18-11e6-98f3-039b51754b80.png) my keepassxc instance looks weird. To the left, there is a window of keepassx2 working correctly but keepassxc has some blurry icons and looks zoomed in in a way.

## Expected Behavior
keepassxc on the right should look like keepassx2 on the left

## Current Behavior
keepassxc has blurry icons and looks zoomed in

## Steps to Reproduce (for bugs)

1. Open KeePassXC

## Context
This is occuring on my notebook with Intel i915 and Wayland, my desktop pc has the exact same setup except using nvidia and X and runs just fine. Another desktop pc of mine also runs i915 and Wayland and works fine. I've tried using a clean environment with no environment variables with `env -i HOME=$HOME DISPLAY=$DISPLAY keepassxc` which doesn't resolve my issue.

## Your Environment

* KeePassXC version/commit used: 2.1.2
* Qt version (e.g. Qt 5.3): 5.8.0
* Compiler (e.g. Clang++3.6.0): GCC 6.3.1
* Operating System and version: current Arch Linux
* Desktop Environment: GNOME 3.22
* GTK theme: Arc
* Icon theme: Numix-Circle

**Comment by phoerious** [comment] 2017-02-26 11:05
This is most likely a duplicate of #323. Can you try installing version 2.1.1 and see if the problem persists?

**Comment by janhicken** [comment] 2017-02-26 11:55
You're correct, downgrading to 2.1.1 fixes the issue. Please go ahead marking it as a duplicate and close this issue.

**Closed** 2017-02-26 11:55 UTC
