### ISSUE TITLE
App refuses to close after running for long period of time

### ISSUE THREAD

**Issue by pwilliamson19** [keepassxreboot/keepassxc#4249] opened 2020-01-27 14:06 UTC
Sometimes I am unable to close KeepassXC. Seems to be when I have Hibernated the PC then restarted it, Not unlocked after restart. Shutdown by right-click in tray icon and select Quit. Process hangs and has to be terminated via Task Manager. Problem appeared in 2.5.1 and all subsequent releases so I'm running 2.3.4. I'm running the Portable version - don't know if that makes any difference.
Doesn't always happen but it is very annoying when it does.
Windows 10 .
By the way - the 2.5.3 release says it's 2.5.1 on the 'About' pop-up.

**Comment by droidmonkey** [comment] 2020-01-27 14:35
If you are seeing 2.5.1 in about then you are running 2.5.1. Try completely uninstalling and reinstalling.

**Comment by pwilliamson19** [comment] 2020-01-27 15:25
Did as suggested - now definitely running 2.5.3. I will monitor over the next few days and update this issue.

**Comment by droidmonkey** [comment] 2020-01-27 16:08
This issue was likely fixed in 2.5.3 so hopefully it does not come back.

**Comment by pwilliamson19** [comment] 2020-01-27 17:23
It's just broken again. Not exactly sure what I did, but even when I right-click the tray icon I get no response. Icon shows d/b is locked (orange dot).

**Comment by droidmonkey** [comment] 2020-01-27 17:43
Are you running this on a thumb drive or network share?

**Comment by pwilliamson19** [comment] 2020-01-27 18:49
Running off a directory on my hard drive. Not C drive - a different partition.

**Comment by turkeyhandwoven** [comment] 2020-02-03 00:17
I'm having the same issue since a few updates ago. It doesn't always happen, so I'm not entirely sure about the steps that cause it. But here is some info, I

## Expected Behavior
Closing the database via the toolbar/tray icon/Ctrl+Q shortcut should close the application.

## Current Behavior
Closing freezes the program. The main window disappears. The tray icon takes the "locked" appearance, but right-clicking it doesn't do anything. Only way to close the program is via the Task Manager.

## Possible Solution
-

## Steps to Reproduce

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )


## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION
Revision: REVISION

Libraries:
- LIBS

Operating system: OS
CPU architecture: ARCH
Kernel: KERNEL

Enabled extensions:
- EXTENSIONS

**Comment by turkeyhandwoven** [comment] 2020-02-03 00:24
I'm having the same issue since a few updates ago. 
It doesn't always happen, so tracing the exact steps to reproduce it is a bit difficult. But here is some info, I'll add more if I find out anything else.

## Expected Behavior
Closing the database via the toolbar/tray icon/Ctrl+Q shortcut should close the application.

## Current Behavior
Closing freezes the program. The main window disappears. The tray icon takes the "locked" appearance, but right-clicking it doesn't do anything. Only way to close the program is via the Task Manager.

## Possible Solution
???

## Steps to Reproduce

1. Load Database.
2. ??? (not sure yet, will observe some more).
3. Close program.


## Debug Info
KeePassXC - Version 2.5.3
Revision: f8c962b

Qt 5.13.2
Debugging mode is disabled.

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.18363

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by turkeyhandwoven** [comment] 2020-02-06 11:38
Alright, so the last couple of days I tried to find steps to effectively reproduce this bug by doing just what I always did when it happened, but to no avail.
I believe it has something to do with the duration the database or program is open, because in all the instances I remember, the database was unlocked and the program was running for quite some time, around 8 hours plus.
Unlike the OP, my PC does not go into hibernation or anything.

Any idea what other time-based factor there could be?

For the time being, I just enabled the automatic locking of my databases after 30 minutes. That way I probably won't be running into that issue anymore.

**Comment by droidmonkey** [comment] 2020-02-06 12:36
Do you have the browser plugin enabled

**Comment by pwilliamson19** [comment] 2020-02-06 13:14
Do you recommend having the browser plug-in enabled? I don't have it. I couldn't see any obvious advantage - KeepassXC seems to work perfectly well without it. But I could enable it if it might help fix or diagnose this problem.

**Comment by droidmonkey** [comment] 2020-02-06 13:42
I do recommend our browser plugin, but that is not what I'm getting at. I'm trying to narrow down the configuration of the application that causes the crash after long periods of time.

**Comment by walkerbl** [comment] 2020-02-06 14:05
I'm having this problem as well. It first turned up in 2.51 and persists in 2.53 (my installed version, MSI installer, Windows 10). For me, the problem occurs when my PC goes to sleep when I am away. When I wake up my PC, it shows me the Unlock KeePassXC Database screen. I see the thin little animation bar under the greyed out Hardware Key: field, but instead of disappearing it persists. When I provide my password for my database, the app simply hangs. I am using the KeePassXC browser extension for FireFox. When I click to close the application I find the process remains open in the background and I must use the Task Manager to close the application. Further, if I try to close the app before leaving my PC, so that it doesn't hang on sleep, I find that the program doesn't fully close and must be closed using the Task Manager or I will be unable to re-open it to re-authenticate against my database.

**Comment by turkeyhandwoven** [comment] 2020-02-06 14:23
> Do you have the browser plugin enabled

The browser integration is disabled in my options.

And like I said in my previous post, unlike **pwilliamson19** and **walkerbl**, my PC does not go into hibernation or anything, merely my screen is turned off after 15 minutes of inactivity.

**Comment by walkerbl** [comment] 2020-02-06 14:26
I should note that my PC also does not go into hibernation. I do not know exactly what level of sleep the system achieves, but it is not hibernation. The problem is also slightly inconsistent. Usually the program hangs, but sometimes it does not.

**Comment by turkeyhandwoven** [comment] 2020-02-07 09:23
@walkerbl @pwilliamson19 
Can you please tell me for how long the program has been running whenever you encounter this problem? Like do you have it open for a long time, like 5 hours or more? Or did it also happen when you only had it open for a short period?
And was the program idle (meaning you didn't interact with it) in the background or minimized before the error happened? Or did you recently use it (edited entries, used auto-type, etc.)?

**Comment by pwilliamson19** [comment] 2020-02-07 09:30
Length of time running - variable. Usually much less than 5 hours. Say 1 or 2 hours typically. Not sure if it happened after a short period.
The program is usually (always?) minimised to the tray and idle when it happens. Usually the database is locked, y because I have restarted after hibernating and it automatically comes up locked (good feature).
Most times I have not used it since the restart (hence the db is still locked). If it has been used it is normally for autotype.

**Comment by droidmonkey** [comment] 2020-02-07 10:46
Do you all see the hardware key animation as well?

**Comment by turkeyhandwoven** [comment] 2020-02-07 12:06
I'm not using a hardware security key.

**Comment by pwilliamson19** [comment] 2020-02-07 12:29
What is the hardware key animation?

**Comment by walkerbl** [comment] 2020-02-07 13:47
@turkeyhandwoven Variable length of time open. I have it set to launch at startup in Windows because much of my work takes place in browser interfaces. So it's always open and unlocked in the background, until I have to step away from my computer. It is when I return and awaken my computer (the screen is set to turn off after 30 minutes). Rarely does my computer actually managed to go to sleep (current setting is 2 hours).

I'm not using a hardware key, but that little back-and-forth bar animation under the hardware key field just keeps going when the program is going to lock up. It never goes away until I close the window (and then force quit the app).

**Comment by walkerbl** [comment] 2020-02-07 13:49
KeePassXC - Version 2.5.3
Revision: f8c962b

Qt 5.13.2
Debugging mode is disabled.

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.14393

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by walkerbl** [comment] 2020-02-07 16:14
New twist on this: I enabled minimizing to the tray today, just for kicks. After an hour or two in the tray it locked the database and then hung as described above. No screen-off necessary, apparently. I have disabled tray functions to avoid having to deal with this even more often.

**Comment by droidmonkey** [comment] 2020-02-07 16:45
I'm thinking there is an infinite loop happening when checking the hardware key presence for some reason. For context, I run, develop, and test KeePassXC on Windows 10 (19.10) every single day. I have never experienced a lockup after a long period of time or when coming back from sleep/hibernation. I am trying to find the unique difference that all of you share that is triggering your experience.

**Comment by droidmonkey** [comment] 2020-02-10 01:49
I actually witnessed this issue today. I am going to dig into the changes in 2.5.1 to see where the error chain began.

**Closed** 2020-03-07 21:52 UTC
Labels: bug, platform: Windows
