### ISSUE TITLE
Secret service DBus error if launched with another database unlocked

### ISSUE THREAD

**Issue by HanabishiRecca** [keepassxreboot/keepassxc#10549] opened 2024-04-05 12:05 UTC
## Overview

Secret service produces a DBus error if KeePassXC was launched with another database unlocked via CLI.
It doesn't happen if KeePassXC is started regularly.

## Steps to Reproduce
1. Launch `keepassxc` via CLI with arguments to unlock some database automatically, which is **not** the one exposed for the secret service. E.g.

```
$ keepassxc '/some/other/database.kdbx' --keyfile '/some/keyfile.keyx'
```

2. Run some app which uses the secret service and unlock its database. Again, it should be a different database from specified in the CLI above. 

## Expected Behavior

It should just work without issues as always.

## Actual Behavior

DBus drops an error.

## Context

For example, I use the secret service to store some `git` credentials.

```
$ git fetch

** (process:10048): CRITICAL **: 11:37:48.187: store failed: No such object path '/org/freedesktop/secrets/aliases/default'
```

But credentials **does** work (the fetch is successful). So it's not clear why it errors out.

From DBus monitor:

```
method call time=1712318281.359531 sender=:1.510 -> destination=org.freedesktop.secrets serial=9 path=/org/freedesktop/secrets/aliases/default; interface=org.freedesktop.Secret.Collection; member=CreateItem
...
error time=1712318281.359578 sender=:1.479 -> destination=:1.510 error_name=org.freedesktop.DBus.Error.UnknownObject reply_serial=9
   string "No such object path '/org/freedesktop/secrets/aliases/default'"
```

KeePassXC - Version 2.7.7
Revision: 68e2dd8

Operating System: Linux
Desktop Env: KDE
Windowing System: Wayland

**Comment by droidmonkey** [comment] 2024-04-05 13:09
Duplicate of #8611

**Closed as not planned by droidmonkey** 2024-04-05 13:09 UTC
Labels: duplicate, feature: Secret Service
