### ISSUE TITLE
Error: "Writing in database failed cannot create for output"

### ISSUE THREAD

**Issue by NicWow** [keepassxreboot/keepassxc#2019] opened 2018-06-02 02:39 UTC
## Expected Behavior

 
I expected no error

## Current Behavior

Says "Writing in database failed
cannot create for output" in red box.

## Steps to Reproduce (for bugs)

1. Launch AppImage in AppVM
2. Import CSV
3. Fill out info like where the passwords, username, URL, e.c.t, are
4. Click ok
5. You did it! A red box appears inside of the manager.
6. It fades away

## Context

Whenever I try to edit it seems to work so I click "ok". Then it appears again.
Don't save.

## Debug Info

KeePassXC - VERSION
Revision: REVISION

Libraries:
- LIBS

Operating system: Qubes OS
CPU architecture: Idk how to check this tbh. I have "CORE i5" if this helps.
Kernel: Idk how to check this tbh. Dual booting on a Dell.

Enabled extensions:
- EXTENSIONS
Just downloaded it.

**Comment by hifi** [comment] 2018-06-02 05:04
Looks like a duplicate of #1995.

Please comment on that issue if you have more information. Thank you!

**Closed by hifi** 2018-06-02 05:04 UTC
