### ISSUE TITLE
Auto-type fails the first time after unlocking database

### ISSUE THREAD

**Issue by dnel** [keepassxreboot/keepassxc#1990] opened 2018-05-24 09:56 UTC
When using global auto-type and the database is locked the dialogue to unlock the database appears, when the database is unlocked through this dialogue the auto-type completes with an error after failing to locate credentials, with the database now unlocked I am able to re-attempt the global auto-type and the credentials are located successfully.

## Expected Behavior
1. Enter global auto-type key sequence
2. Enter database password in unlock dialogue
3. Auto-type search menu shows matching entries

## Current Behavior
1. Enter global auto-type key sequence
2. Enter database password in unlock dialogue
3. Auto-type presents error after failing to find matching entries
4. Re-enter global auto-type key sequence
5. Auto-type search menu shows matching entries

## Possible Solution
It's a bug

## Steps to Reproduce (for bugs)
1. Lock database
2. Enter global auto-type sequence on site known to work with auto-type
3. Unlock database from dialogue

## Context
Wastes time repeating steps

## Debug Info
KeePassXC - Version 2.2.2
Revision: 6d46717

Libraries:
- Qt 5.9.1
- libgcrypt 1.8.1

Operating system: macOS High Sierra (10.13)
CPU architecture: x86_64
Kernel: darwin 17.5.0

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

**Comment by hfr-hfr** [comment] 2018-06-05 08:46
I think this bug is addressed here: #1216 
It's following us for a pretty long time…

**Comment by TheZ3ro** [comment] 2018-06-10 19:29
Can anyone confirm this? @weslly maybe

**Comment by weslly** [comment] 2018-06-10 21:29
Duplicate of #1216

**Closed by weslly** 2018-06-10 21:29 UTC
Labels: platform: macOS
