### ISSUE TITLE
KeePassXC entries should allow multiple http addresses

### ISSUE THREAD

**Issue by haakobja** [keepassxreboot/keepassxc#3483] opened 2019-08-29 06:48 UTC
## Summary
It would be nice to have a KeePassXC entry to match several HTTP-addresses and domains. This way it is no need to maually manage all the different entries with the same logon for different sites.

## Desired Behavior
Multiple URLs for KeePassXC should allow a single username-password combination to be used for several sites.

## Possible Solution
The way I see it, there's several solutions. 
1. Allow entries to be linked, thus making a master entry with username and password and have the entries with specific URLs connected to the master entry. The way I see it, this could be managed as a tree with the leaf-nodes (with urls) connected to the master (with username and password). But this would probably be a solution that's difficult to maintain
![image](https://user-images.githubusercontent.com/1866620/63916995-de1e8700-ca39-11e9-96e9-bdd426941c18.png)

2. Allow an entry to have multiple URLs.

## Context
I use my KeePassXC both private and at work and we have sites where we use the internal AD user to log on. Those sites are not necessary at the local domain, even though they are connected to the AD.

**Comment by varjolintu** [comment] 2019-08-29 08:42
Duplicate of https://github.com/keepassxreboot/keepassxc/issues/398.

**Closed by varjolintu** 2019-08-29 08:42 UTC
Labels: duplicate, new feature
