### ISSUE TITLE
Search in all opened databases for matching credentials does not work

### ISSUE THREAD

**Issue by oceanBT** [keepassxreboot/keepassxc#7269] opened 2022-01-07 10:19 UTC
## Overview
The Option "Search in all opened databases for matching credentials" in the Browser-integration does not work. 

## Steps to Reproduce

1. Enable  "Search in all opened databases for matching credentials"
2. Open and unlock a database that is connected to the browser extension (A.kdbx)
3. Open and unlock a database that is not connected to the browser extension (B.kdbx) 
4. open a website in chrome where you have credentials in A.kdbx 

## Expected Behavior
The extension should provide credentials from A.kdbx

## Actual Behavior
The extension does not provide credentials from A.kdbx. I have to open keepassXC and switch tab to "A.kdbx", reload webpage then the auto completion in chrome works as expected. 

## Context
This is no new problem. I use keepassxc since about one year with multiple databases and it never worked as expected. 

KeePassXC - Version 2.6.6
Revision: 9c108b9

Qt 5.15.2
Debugging mode is disabled.

Operating system: Ubuntu 21.10
CPU architecture: x86_64
Kernel: linux 5.13.11-051311-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- libgcrypt 1.8.8

Desktop Env: Gnome
Windowing System: Wayland

**Comment by droidmonkey** [comment] 2022-01-07 12:20
I agree the focused tab condition is very confusing to users. Recommend an update to that @varjolintu

**Comment by varjolintu** [comment] 2022-01-07 12:31
Please check that your other database is not a copy of the first one. You can try resetting the Root Group UUID from Database Settings' Browser Integration page.

**Comment by varjolintu** [comment] 2022-01-07 12:31
@droidmonkey I'm working on it, but it needs a lot of changes.

**Comment by varjolintu** [comment] 2022-01-07 14:26
Instead of breaking the current protocol, I'm trying to add all connected databases to a separate array for some responses, so we can still detect them even if the active database is not connected to the extension.

**Comment by varjolintu** [comment] 2022-01-07 14:27
Related issue: https://github.com/keepassxreboot/keepassxc-browser/issues/1275

**Comment by droidmonkey** [comment] 2022-01-07 14:33
Yah I think we discussed this before that the database and the extension connection were too tightly bound. Need to add a shim in between to allow for the "search everywhere even if only one database is registered to extension".

**Comment by flyingflo** [comment] 2022-02-15 07:44
It seems to be the same issue with DBus secret service requests.
I have multiple databases with secret service enabled.
Lookup only finds entries in the database that is currently focused in the keepassxc window.

**Comment by fcana** [comment] 2024-02-25 18:15
any update about this? is there a way to work with two databases without entering every time in the one you need?

**Comment by varjolintu** [comment] 2024-02-25 18:22
@fcana It's already fixed for the next protocol update, but it's coming with KeePassXC 2.8.0 so it's gonna take a while.

**Comment by droidmonkey** [comment] 2024-08-18 18:17
Duplicate of #5238

**Closed as not planned** 2024-08-18 18:17 UTC
Labels: duplicate, feature: Browser, ux
