### ISSUE TITLE
[Linux] I don't see toolbar icons

### ISSUE THREAD

**Issue by kenlog** [keepassxreboot/keepassxc#4998] opened 2020-07-09 08:48 UTC
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
After the last update, the icons in the toolbar are not displayed correctly.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
I simply updated to version 2.6.0

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
I'd say it would be great to see these new icons! Thanks.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
![keepass](https://user-images.githubusercontent.com/11728231/87019382-d3448f00-c1d2-11ea-8926-62f3a4c999b3.png)

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.0
Revision: 0765954

Qt 5.9.5
Debugging mode is disabled.

Operating system: Linux Mint 19
CPU architecture: x86_64
Kernel: linux 4.15.0-109-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Cinnamon
Windowing System: X11

**Comment by phoerious** [comment] 2020-07-09 09:04
Duplicate of #4963

**Closed by phoerious** 2020-07-09 09:04 UTC
Labels: bug
