### ISSUE TITLE
All icons look ugly in high resolution MacOS screen

### ISSUE THREAD

**Issue by smimish** [keepassxreboot/keepassxc#2837] opened 2019-03-22 15:14 UTC
# Summary
All icons look ugly on the high res MacOS screen

<img width="863" alt="изображение" src="https://user-images.githubusercontent.com/4650168/54832874-16bd7600-4cce-11e9-881f-32eaa1cde6f6.png">

## Expected Behavior
Icons should look nice and polished, not like on the attached screenshot.

## Current Behavior
The screenshot speaks of itself:
<img width="863" alt="изображение" src="https://user-images.githubusercontent.com/4650168/54832903-263cbf00-4cce-11e9-9865-43f012ffc075.png">

## Steps to Reproduce
Just run KeepassXC on any high res MacOS system.

## Debug Info
KeePassXC - 2.4.0

Operating system: MacOS

**Comment by affinityv** [comment] 2019-03-22 15:49
Look at the links from the following comment (and two below), it might help with your problem.
https://github.com/keepassxreboot/keepassxc/issues/2815#issuecomment-475668798

**Comment by phoerious** [comment] 2019-03-26 13:13
The icons are not really HiDPI and we chose the apply nearest-neighbour scaling until we have higher-resolution icons.

**Comment by phoerious** [comment] 2019-03-26 13:16
Duplicate of #2468.

**Closed by phoerious** 2019-03-26 13:16 UTC
Labels: bug, platform: macOS
