### ISSUE TITLE
Linux Mint 18 File does not exist

### ISSUE THREAD

**Issue by topas-rec** [keepassxreboot/keepassxc#2847] opened 2019-03-23 17:14 UTC
KeePassXC somehow suddenly stopped to be able to open my definitely existing kdbx database. 

The error message says:

`Unable to open the database.  File [...].kdbx does not exist.`

I made a screenshot:
![Screenshot from 2019-03-23 18-05-48](https://user-images.githubusercontent.com/20391449/54869342-60be5e80-4d97-11e9-904b-23859c5c5ef1.png)

It might be related to other updates recently installed - but I'm not sure.
I did not change any preferences.

I have not idea what could be wrong and I don't know how to start this app through the terminal (Which command?)

Can someone help me with this issue?

**Comment by droidmonkey** [comment] 2019-03-23 18:33
That database is not stored in a proper location. That looks like the temp directory for a snap install. Did you actually store your database in your user directory?

**Comment by Tbaut** [comment] 2019-03-23 18:59
I can confirm this. Just to test I've copied a db on my `/home/user/Desktop`, it can be open by the v2.3.4 without problem (and this version shows the proper path). with v2.4.0 it show a weird path eg: `/run/user/<some hash>/` and complains that the file doesn't exist.

**Comment by droidmonkey** [comment] 2019-03-23 19:04
Are you both running the snap version?

**Comment by topas-rec** [comment] 2019-03-23 19:21
File is stored on an NTFS drive - since years and worked with KeePassXC for years. When I open that file from Desktop the path looks similar. So no matter where I store the file, I cannot get the showing the real path. But that was the same two weeks ago and the app worked. I noticed that the path looks wrong. Tested that with the file copied to the Desktop, too - without success.

PS: I've reinstalled the app. (Installed from the software manager in Linux Mint)

**Comment by topas-rec** [comment] 2019-03-23 19:25
> Are you both running the snap version?

How can I find out? I installed from the software manager (There it says it's a flatpak from flathub)

**Comment by droidmonkey** [comment] 2019-03-23 20:45
@topas-rec in that case you need to report your issue to the flatpak maintainer: https://github.com/flathub/org.keepassxc.KeePassXC/issues

**Comment by topas-rec** [comment] 2019-03-23 21:16
Thanks. Before I do that I'll test it witha downloaded version to verify it is only the flatpak version that has the issue. Can I use the appimage download for this test @droidmonkey? (I cannot distinguish between flatpak and appomage - I assume they are different and rust o can use the appimage to find out that the issue is only flatpak related)

@Tbaut what installation method do you use?

**Comment by droidmonkey** [comment] 2019-03-23 21:32
Yes you can use the appimage. AppImage, Snap, and Flatpak are all VERY different from each other.

**Comment by mat-m** [comment] 2019-03-23 23:28
Confirmed. AppImage version has no issue. I think it is related to gvfs, which does the conversion from /home/<user>/... to /run/user/...
It already did but worked with 2.3.4 and is now broken with 2.4.0

**Comment by Tbaut** [comment] 2019-03-23 23:41
>@Tbaut what installation method do you use?

Same as you, the one provided by the software manager.
I can also confirm that the AppImage works as expected.

**Comment by droidmonkey** [comment] 2019-03-24 00:00
Ok closing since this is a flatpak issue

**Closed by droidmonkey** 2019-03-24 00:00 UTC
Labels: bug

**Comment by topas-rec** [comment] 2019-03-24 05:49
Can confirm, that it works with the appimage.

**Comment by topas-rec** [comment] 2019-03-24 05:51
Issue is already present: https://github.com/flathub/org.keepassxc.KeePassXC/issues/34
