### ISSUE TITLE
Support conditionally auto-adding SSH keys

### ISSUE THREAD

**Issue by scruloose** [keepassxreboot/keepassxc#3571] opened 2019-09-23 14:21 UTC
### Summary
Add capability to automatically add particular keys to ssh-agent only when running on specified host and/or under specified user.
### Desired Behavior
* In the 'SSH Agent' pane, add text fields for hostname and username (possibly auto-populated by default if the key includes a comment in the user@host format?).
* Under "Add key to agent when database is opened/unlocked", add two additional checkboxes for "only if username matches" and "only if hostname matches".
### Possible Solution
I don't know whether KeepassXC already has the capability to query the OS to determine the hostname we're running on and the name of the user under whom we're running. If not, would it be feasible to add that capability via the C++ functions `gethostname()` and `getusername()` or similar?. With that in place, I assume it would be fairly straightforward to add conditionals to do the ssh-add only if the queried value matches what's stored in the database entry.
### Context
As someone who uses a number of SSH keys from different user accounts on various client machines for different purposes, and keeps all the private keys as attachments in my KeepassXC database, I have found the on/off toggle for "Add key to agent when database is opened/unlocked" to be a rather blunt implement. Automatically adding every key from every account on every machine as soon as I open KeepassXC would be counterproductive, so the automatic-adding feature is simply unusable for me. Having the option to automatically add the keys conditionally on matching hostname and/or username would save me having to pick through my "Key Management" group and manually add the appropriate key(s) every time I log in.

**Comment by droidmonkey** [comment] 2019-09-23 17:41
We can just use the username and url fields of the entry to do the matching.

**Comment by scruloose** [comment] 2019-09-23 19:31
Yes, if the feature can be implemented using the fields that are already included and displayed by default, that's even better!

(I'm embarrassed that I didn't think about the username field which was right in front of me.)

**Comment by hifi** [comment] 2020-03-15 11:03
Getting back to this: while the option would be rather simple to implement to match the host and user, OpenSSH has a "hidden" feature of pinning public keys to host entries in `~/.ssh/config` using `IdentityFile` and `IdentitiesOnly yes`.

I have that set up for every entry when I need over a dozen keys for different purposes and I have them all pinned to specific hosts so the ssh client won't even try to use other keys except the one listed even though it's using the public key as the reference.

Would that work for you?

**Comment by hifi** [comment] 2020-03-15 11:29
Also as for what @droidmonkey suggested, if we add support for matching user/host then it needs to be a global setting because changing the `KeeAgent.settings` XML structure would make us incompatible with KeeAgent or it would need to be a clever hack with the entry data without XML changes.

In addition this is a duplicate of #1721 but if this will have a scope of being compatible we can have both open for now.

**Comment by droidmonkey** [comment] 2021-01-29 02:57
Closing this as duplicate

**Closed** 2021-01-29 02:57 UTC
Labels: duplicate, plugin: SSH agent
