### ISSUE TITLE
Update 2018-02-28 has failed libsodium23 broken package

### ISSUE THREAD

**Issue by lonelylinux** [keepassxreboot/keepassxc#1562] opened 2018-02-28 18:08 UTC
Looks like this morning's update contains a broken package. This is from the command line:

```
Preparing to unpack .../libsodium23_1.0.16-0ppa3~xenial1_amd64.deb ...
Unpacking libsodium23:amd64 (1.0.16-0ppa3~xenial1) ...
dpkg: error processing archive /var/cache/apt/archives/libsodium23_1.0.16-0ppa3~xenial1_amd64.deb (--unpack):
 trying to overwrite '/usr/lib/x86_64-linux-gnu/libsodium.so.23.1.0', which is also in package libsodium18:amd64 1.0.16-0ppa1~xenial1
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
Processing triggers for libc-bin (2.23-0ubuntu10) ...
Errors were encountered while processing:
 /var/cache/apt/archives/libsodium23_1.0.16-0ppa3~xenial1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
---------------------------------------------------------------
```

I searched system logs for "keepass" and for "libsodium". Other than the records of my uninstall and reinstall commands, these are the only two lines:

```
(gnome-software:2090): As-WARNING **: failed to rescan: Failed to parse /usr/share/applications/org.keepassxc.KeePassXC.desktop.dpkg-new file: cannot process file of type text/plain

(gnome-software:2090): As-WARNING **: failed to rescan: Failed to parse /usr/share/applications/org.keepassxc.KeePassXC.desktop file: cannot process file of type application/x-desktop
```

## Expected Behavior
Of course, expected the package to install...

## Current Behavior
The software appears to function, though I haven't tested every feature.

## Possible Solution
I think there may be a package problem. Maybe sorting that?

## Steps to Reproduce (for bugs)
I've done complete uninstall with -purge, and reinstall: Same error.
Ubuntu suggests apt-get -f install: Same error.

## Context
Just getting the error, and worried the software won't work - or that if I add entries they'll corrupt.

## Debug Info
KeePassXC - Version 2.3.0
Revision: 4c0ed74

Libraries:
- Qt 5.5.1
- libgcrypt 1.8.1

Operating system: Ubuntu 16.04.4 LTS
CPU architecture: x86_64
Kernel: linux 4.13.0-36-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

Would appreciate any clues how to resolve this, though I suspect there's a tiny bug in the package?

Thanks for a really great software!

**Comment by gislikarl** [comment] 2018-02-28 18:09
Same here this has been bugging me since the update

**Comment by tailwheeldriver** [comment] 2018-02-28 18:31
I seem to have a similar problem, except keepassxc has disappeared from my menu on LinuxMint 18.3. It will not start, and is still broken on reinstall. Last report from apt-get while installing from the ppa is:

> dpkg: error processing archive /var/cache/apt/archives/libsodium23_1.0.16-0ppa3~xenial1_amd64.deb (--unpack):
 trying to overwrite '/usr/lib/x86_64-linux-gnu/libsodium.so.23.1.0', which is also in package libsodium18:amd64 1.0.16-0ppa1~xenial1
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
Selecting previously unselected package keepassxc.
Preparing to unpack .../keepassxc_2.3.0-0ppa1~xenial1_amd64.deb ...
Unpacking keepassxc (2.3.0-0ppa1~xenial1) ...
Processing triggers for libc-bin (2.23-0ubuntu10) ...
Processing triggers for hicolor-icon-theme (0.15-0ubuntu1) ...
Processing triggers for shared-mime-info (1.5-2ubuntu0.1) ...
Processing triggers for gnome-menus (3.13.3-6ubuntu3.1) ...
Processing triggers for desktop-file-utils (0.22+linuxmint1) ...
Processing triggers for mime-support (3.59ubuntu1) ...
Processing triggers for man-db (2.7.5-1) ...
Errors were encountered while processing:
 /var/cache/apt/archives/libsodium23_1.0.16-0ppa3~xenial1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by TheZ3ro** [comment] 2018-02-28 18:46
Duplicate of #1545, there you can find many solutions

Also some user on twitter proposed this solution for Linux Mint specifically: https://twitter.com/_notarobot_/status/968893051656724480

**Closed by TheZ3ro** 2018-02-28 18:46 UTC
