### ISSUE TITLE
Current macOS binary build of 2.1.1 has no Preferences menu.

### ISSUE THREAD

**Issue by UniK** [keepassxreboot/keepassxc#264] opened 2017-02-07 13:14 UTC
Current macOS binary build of version 2.1.1 has no "Preferences" menu entry.
- no menu entry under `KeePassXC/Preferences...`
- default keyboard shortcut `Cmd+,` doesn't open the preferences either

So... there is no way to make any setting upon the app.

## Environment

* KeePassXC version/commit used: 2.1.1
* Operating System and version: macOS 10.12.3

**Comment by TheZ3ro** [comment] 2017-02-07 19:06
Currently I'm using 10.12 and I can't reproduce this. I will test on 10.12.3
![virtualbox_macos sierra_07_02_2017_20_01_10](https://cloud.githubusercontent.com/assets/686894/22706759/c6c9061e-ed70-11e6-9592-e2bca176f8d2.png)

**Comment by UniK** [comment] 2017-02-07 20:46
Suddenly this issue has become resolved, after I cleaned up (deleted) all the app's supporting files, in following directories, e.g.:
```
~/Library/Application Support/...
~/Library/Preferences/...
~/Library/Saved Application State/...
```

Not sure wich one did the trick.
So I think we can close this issue, as long as no-one can reproduce this one.

**Comment by TheZ3ro** [comment] 2017-02-07 21:49
Closing for now

**Closed by TheZ3ro** 2017-02-07 21:49 UTC
