### ISSUE TITLE
Partial SEARCH MATCH for TAGS.

### ISSUE THREAD

**Issue by emomilk** [keepassxreboot/keepassxc#10366] opened 2024-03-10 00:58 UTC
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )

SEARCH only works with TAGS if the SEARCH term MATCHES the TAG exactly. No partial MATCHES.

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )

I have a STAR WARS password saved with TAGS "sw" and "swtor". If I SEARCH for "s", this ENTRY shows up in the RESULTS because there is partial MATCH on its TITLE. If I SEARCH for "sw", this ENTRY shows up in the RESULTS because there is partial MATCH on its TITLE and/or the TAG is EXACT MATCH for the SEARCH. However, if I SEARCH for "swt", this ENTRY does not show up in the RESULTS because there is no MATCH on the TITLE and there is no MATCH on TAGS either (since there is no partial MATCH on TAGS). Neither does the ENTRY show up in the RESULTS if I SEARCH for "swto". The ENTRY only shows up again in the RESULTS if I SEARCH for "swtor", the full TAG.

I think the ENTRY should show up in every scenario mentioned above. I.e. the SEARCH should have partial MATCH on TAGS the same way it has partial MATCH on TITLES.

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )

It is convenient and user friendly and sensible.

**Comment by droidmonkey** [comment] 2024-03-10 01:27
Search for `swt*`

Duplicate of #9809

**Closed as not planned** 2024-03-10 01:28 UTC
Labels: duplicate, feature: Tags

**Comment by emomilk** [comment] 2024-03-10 01:34
It's kinda baffling that this is not even considered. Instead of a simple change on the application side users have to add every partial tag to their entries as a workaround. Ridiculous.

**Comment by droidmonkey** [comment] 2024-03-10 01:52
Follow the other issue, it's open, read my last comment on it, thanks.

**Comment by emomilk** [comment] 2024-03-10 22:17
Will do. I saw "closed this as not planned" and did not think to check the other issue. My apologies.

**Comment by droidmonkey** [comment] 2024-03-11 02:41
That is just a dumb thing GitHub does, you can't close an issue as a duplicate for some reason.
