### ISSUE TITLE
Window resize failed while switching monitor off on multi monitor environment

### ISSUE THREAD

**Issue by seelenreiter** [keepassxreboot/keepassxc#8035] opened 2022-05-11 06:59 UTC
## Overview
Envirnment 2 Monitors. 
1. 32" UHD
2. 22" FHD

switching off the monitors will cause a failure inside the keypass windows. 
seems to be a resizing failure of the elements. see picture
The programm is reacting on keyboard input, but mouse does not grab any input. (broken layout)

![KeepassXCError1](https://user-images.githubusercontent.com/21043420/167787961-ff0b5587-1cfe-4f86-9575-da6bcb9556ba.jpg)

## Steps to Reproduce
- switch off the UHD monitor and than the 22", too
- switch on the 22" and then the UHD Monitor

it doesn't appear while 22" Monitor is disconnected

## Expected Behavior
seems to be a problem on resizing the windows because of "resolution change during switch off the monitor.

KeePassXC - 2.64, 2.6.6, 2.7.0 and 2.7.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: W10 enterprise 21H2
19044.1645
Windows Feature Experience Pack 120.2212.4170.0

**Comment by droidmonkey** [comment] 2022-05-11 10:05
This is a qt bug we cannot fix. You can try hiding the window to the system tray icon and bringing it back. Should reset things

**Comment by JohnLGalt** [comment] 2022-05-11 10:14
Ran into the same issue, with similar results, also using 1 UHD and 1 FHD. FWIW, DM also link me to this page https://doc.qt.io/qt-5/highdpi.html#high-dpi-support-in-qt which has three values that I added to my Environment variables (as system, not user).

See my post here https://github.com/keepassxreboot/keepassxc/issues/6262#issuecomment-1072743374 for the values. Those are exactly what I used when using UHD + FHD monitors and moving KPXC between them. I've since replaced the FHD with a QHD and have not had to use those values anymore as it autoscales much better now.

**Comment by enginpost** [comment] 2022-06-14 12:43
I think I have the same problem. It seems in Windows 11, when the computer falls to sleep and the browser extension needs to reconnect, when the app pops up out of the system tray, the scale of the app interface is confused and i cannot focus the app on fields in the interface. So, is the work-around minimizing and maximizing again to rescale the interface? I've been closing the app and re-opening, which is getting a little old, TBH.

**Comment by JohnLGalt** [comment] 2022-06-14 17:06
Since I have multiple monitors, I move it to the other monitor then back to the monitor I want it displayed on. Note, my monitors are of different resolutions, and also use different display scaling values (1005 vs 150%).

**Comment by sooonmitch** [comment] 2023-04-19 05:09
I have just started getting these issues lately, but instead, the display is super zoomed, in the window. This happens when my external usb monitor unplugs/plugs itself in on computer sleep/wake up. Fully quitting the service and starting it again fixes the issue. Thought I would add this detail here instead of creating a new ticket. Especially since it it still open.

**Comment by droidmonkey** [comment] 2023-08-20 21:36
Duplicate of #6262

**Closed as not planned by droidmonkey** 2023-08-20 21:36 UTC
Labels: Qt
