### ISSUE TITLE
First input box UI focus style issue with Classic theme on the Mac

### ISSUE THREAD

**Issue by solidcolour** [keepassxreboot/keepassxc#5618] opened 2020-10-26 16:04 UTC
<img width="470" alt="Screen Shot 2020-10-26 at 11 44 23 AM" src="https://user-images.githubusercontent.com/1742906/97195900-36f2c800-1782-11eb-871d-007d06ffaedd.png">

Two UI issues:

1. First input box (Title) loses focus style at the top with Classic theme on the Mac
2. Unwanted white space occurs right before Username input box since v2.6.2

**Comment by phoerious** [comment] 2020-10-26 16:06
Duplicate of #5601

**Closed by phoerious** 2020-10-26 16:07 UTC
