### ISSUE TITLE
after update doesn't open database in ubuntu

### ISSUE THREAD

**Issue by Th0masT** [keepassxreboot/keepassxc#3677] opened 2019-10-27 06:00 UTC
after i update 2.4.3 => 2.5.0 i can't open any database (i tried 2 different). My pc is ubuntu 18.04.3 LTS x64. i did purge uninstall and reinstall same result.

In virtual machine windows 7 x86 and keepassxc 2.5.0 working fine. i open same databases

## Expected Behavior
open the database

## Current Behavior
I get HMAC mismatch message.

**Comment by Th0masT** [comment] 2019-10-27 08:46
i figured out a workaround. i opened database in vm win7 with keepassxc 2.5.0, changed the password. after with the new password i can open under ubuntu.

**Comment by Ivan-Shestakov** [comment] 2019-10-27 09:52
Same here - can't open KeepassXC database using my password after  OS Ubuntu upgrade from 9.04 to 9.10

**Comment by phoerious** [comment] 2019-10-27 10:00
Duplicate of #3678

**Closed by phoerious** 2019-10-27 10:00 UTC
Labels: bug

**Comment by tmhpfnr** [comment] 2019-10-28 15:57
Removing the **keepassxc** directoy under **~/snap/keepassxc/current/.config** worked for me (corresponding to the comment by @ged42 at #3678).

**Comment by droidmonkey** [comment] 2019-10-28 16:36
For clarification, simply clicking the "clear field" button on the key file input would fix this immediately.

**Comment by phoerious** [comment] 2019-10-28 16:43
I suggest you repost these solutions to the linked report, since that one is pinned to the top of the issue list.
