### ISSUE TITLE
libsodium23 required but libsodium18 installed

### ISSUE THREAD

**Issue by achlys75** [keepassxreboot/keepassxc#1623] opened 2018-03-04 16:45 UTC
My Ubuntu16.04 has libsodium18 installed, keepassxc requires libsodium23

## Expected Behavior
"apt upgrade" to the newest keepascx file.

## Current Behavior
"apt upgrade" gets the following error:
``` Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.       
Statusinformationen werden eingelesen.... Fertig
Probieren Sie »apt-get -f install«, um dies zu korrigieren.
Die folgenden Pakete haben unerfüllte Abhängigkeiten:
 keepassxc : Hängt ab von: libsodium23 ist aber nicht installiert
E: Unerfüllte Abhängigkeiten. Versuchen Sie, -f zu benutzen.``` 



"apt-get -f install" gets the following error:
```  Entpacken von libsodium23:amd64 (1.0.16-0ppa3~xenial1) ...
   dpkg: Fehler beim Bearbeiten des Archivs /var/cache/apt/archives/libsodium23_1.0.16-0ppa3~xenial1_amd64.deb (--unpack):
 Versuch, »/usr/lib/x86_64-linux-gnu/libsodium.so.23.1.0« zu überschreiben, welches auch in Paket libsodium18:amd64 1.0.16-0ppa1~xenial1 ist
dpkg-deb: Fehler: Unterprozess einfügen wurde durch Signal (Datenübergabe unterbrochen (broken pipe)) getötet
Trigger für libc-bin (2.23-0ubuntu10) werden verarbeitet ...
Fehler traten auf beim Bearbeiten von:
 /var/cache/apt/archives/libsodium23_1.0.16-0ppa3~xenial1_amd64.deb```



## Possible Solution
I've got no idea.

## Steps to Reproduce (for bugs)


## Context


## Debug Info

KeePassXC - Version 2.3.0
Revision: 4c0ed74

Bibliotheken:
- Qt 5.5.1
- libgcrypt 1.8.1

Betriebssystem: Ubuntu 16.04.4 LTS
CPU-Architektur: x86_64
Kernel: linux 4.4.0-116-generic

Aktivierte Erweiterungen:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by phoerious** [comment] 2018-03-04 17:46
Duplicate of #1545

**Closed by phoerious** 2018-03-04 17:46 UTC
