### ISSUE TITLE
Side By Side UI Layout

### ISSUE THREAD

**Issue by homhom1416** [keepassxreboot/keepassxc#5272] opened 2020-08-15 07:58 UTC
## Summary &  Context
a wish ..

just like keepass ..

view > windows layout > side by side ..

## Examples

![1](https://user-images.githubusercontent.com/63208539/90308152-b55efe00-dee5-11ea-844a-22880b006804.png)

Thanks ..

**Comment by droidmonkey** [comment] 2020-08-15 11:19
Duplicate of #5236

**Closed by droidmonkey** 2020-08-15 11:19 UTC
Labels: new feature

**Comment by turmoggy** [comment] 2021-06-27 04:14
Yes it needs an option for side by side ui layout. I find it more functional than bottom view.

**Comment by michaelk83** [comment] 2021-06-27 08:38
FYI, the KDE direction seems to be towards movable panels, so users can arrange them however they like. But I can't find the reference atm.
