### ISSUE TITLE
Repeatedly pressing the favicon download button crashes the app

### ISSUE THREAD

**Issue by C0rn3j** [keepassxreboot/keepassxc#2893] opened 2019-03-27 14:41 UTC
## Expected Behavior
No crashes.

## Current Behavior
When repeatedly pressing the download favicon button (triggered it with minimum two presses) - there's a risk of crash.

It seems to be more reliably reproduced when trying a server that is not really responding but not killing the connection outright either (right now that's https://travianz.eu/ for example)

Trying to trigger it on responding servers ( https://aleksandra.rys.pw for example ) does work, but seems to require way more download-icon presses.

## Possible Solution
???

## Steps to Reproduce
1. Create a new entry with https://travianz.eu/ as the URL (or any other website that takes too long to load)
2. Press the download favicon button a few times
3. Repeat 2. if necessary
4. Crash

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.4.0
Revision: c51752d

Libraries:
- Qt 5.12.2
- libgcrypt 1.8.4

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 5.0.4-arch1-1-ARCH

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey

Seems like there was a similar issue, but that's 2 years old now so I opened this one.
https://github.com/keepassxreboot/keepassxc/issues/225

**Comment by droidmonkey** [comment] 2019-03-27 16:13
This is a Qt bug.

**Comment by droidmonkey** [comment] 2019-03-28 01:25
Duplicate of #2734

**Closed by droidmonkey** 2019-03-28 01:25 UTC
Labels: bug

**Comment by pkx166h** [comment] 2019-04-21 07:25
If you're going to close #2734 as duplicate of this but then just say this a 'QT bug', I think at the very least we should pots the link to the QT bug tracker issue so that others who are interested (like me) can find it quickly.

Looking at KeepassXC issue #2734  - is it this QT bug?

https://bugreports.qt.io/browse/QTBUG-47822

**Comment by C0rn3j** [comment] 2019-04-21 13:21
The linked thread has 5 comments, not 50, the second being the link to Qt's tracker.

That's quick enough.
