### ISSUE TITLE
Window preview shows database when app is locked

### ISSUE THREAD

**Issue by JekRock** [keepassxreboot/keepassxc#5529] opened 2020-10-09 11:19 UTC
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
When the app is locked on Windows, the app window preview shows the window state before locking.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Open Keepass XS on Windows with existing database
2. Unlock the database
3. Minimize the Keepass XS window and wait until the database is locked (do not focus the window)
4. Hover the Keepass XS on the taskbar
5. Hover the Keepass XS window preview without clicking on it. Here you will get the Keepass XS window preview before it was locked

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Window preview should not show the app window preview when a database is locked

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
The Keepass XS window preview shows the Keepass XS window state before it was locked when database is locked.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.5.4
Revision: c023bf9

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10

**Comment by droidmonkey** [comment] 2020-10-09 11:34
Duplicate of #3392. You should upgrade your version, we are ont 2.6.1 now.

**Closed by droidmonkey** 2020-10-09 11:34 UTC
Labels: bug
