### ISSUE TITLE
Auto-type stopped working in 2.7.0 on Gnome

### ISSUE THREAD

**Issue by ThomasA** [keepassxreboot/keepassxc#7631] opened 2022-03-24 07:41 UTC
## Overview
Until a few days ago, auto-type worked fine for me for entering my username and password into login forms in my browser. This has stopped working since a suspected automatic update by Ubuntu.

## Steps to Reproduce
1. I place the cursor in the username field of a login form in my browser.
2. I switch to KeePassXC, locate, and highlight the relevant password there.
3. I press CTRL + SHIFT + V

## Expected Behavior
I expect KeePassXC to switch back to the previous application (my browser) and enter username and then password into the login form.

## Actual Behavior
KeePassXC first displays this dialog:
![Autotype dialog](https://user-images.githubusercontent.com/971307/159865500-b8878047-c457-41d7-b3a1-2f09dc4ecb24.png)
This is new to me. I click "Yes". Then focus switches to my browser window where KeePassXC does *nothing*. I.e. nothing gets entered into the login form.

## Context
The browser I am using is Firefox 98.0.1. I do not expect Firefox to be the cause of the problem since I cannot paste my credentials into for example a text editor either.

KeePassXC - Version 2.7.0
Revision: 20c9ac1
Distribution: Snap

Qt 5.15.3
Debugging mode is disabled.

Operativsystem: Ubuntu Core 20
CPU-arkitektur: x86_64
Kerne: linux 5.13.0-37-generic

Aktiverede udvidelser:
- Autoskriv
- Browserintegritet
- SSH-agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.12.1

Operating System: Linux (Ubuntu)
Desktop Env: Gnome
Windowing System: X11

**Comment by hifi** [comment] 2022-03-24 07:58
Duplicate of #7584, fix has been merged and will be available in v2.7.1.

The suggested workaround is to use global Auto-Type hotkey as it's less prone to errors and does not inhibit this bug.

**Closed as completed by hifi** 2022-03-24 07:58 UTC
Labels: duplicate, platform: Linux, feature: Auto-Type

**Comment by ThomasA** [comment] 2022-03-24 08:02
Great to hear. I will wait for the fix then.

**Comment by HNieme** [comment] 2023-10-03 09:59
Note for anyone wondering why this is still not working for them:

On Wayland AutoType is disabled by default. You need to re-enable it ( See the documentation https://keepassxc.org/docs/KeePassXC_UserGuide#_auto_type )
