### ISSUE TITLE
Ability to unlock database by providing HMAC secret in the event a hardware key is lost

### ISSUE THREAD

**Issue by lauritzt** [keepassxreboot/keepassxc#4018] opened 2019-12-14 20:47 UTC
## Summary
If a user protects their database with a hardware key, and does not have a backup key, they will not be able to open the database if they lose that key. If this feature proposal is implemented, the user will be able to enter the HMAC secret of their hardware key to unlock the database in such a situation.

## Desired Behavior
The user should be able to open the database by entering the HMAC secret into KeePassXC.

## Possible Solution
Under the hardware key section of the unlock database screen, a recovery button could be present if no hardware key is inserted. When clicked, the user can enter the HMAC secret. The response is then generated (just as it is on a hardware key) and used to unlock the database.

## Context
The user has lost their hardware key, but has access to their HMAC secret.

**Comment by droidmonkey** [comment] 2019-12-14 22:47
Duplicate of #1734

**Closed by droidmonkey** 2019-12-14 22:47 UTC
Labels: new feature
