### ISSUE TITLE
AutoOpen with remote files

### ISSUE THREAD

**Issue by Guite** [keepassxreboot/keepassxc#2794] opened 2019-03-17 12:12 UTC
## Summary
The AutoExec plugin from KeePass allows to reference a second database using FTP. This would be an awesome feature because it simplifies having a shared database on a server.

## Desired Behavior
It would be sufficient if the scheme `ftp://user@password:somehost.com/path/to/file.kdbx` would be possible. If user and password would be stored in separate fields this would be even better.

## Context
Each person has a personal database and in addition we have a shared one. The latter one should automatically be synchronised on updates, so we store it on a server.

**Comment by droidmonkey** [comment] 2019-03-17 13:42
Duplicate of #1775.

**Closed by droidmonkey** 2019-03-17 13:42 UTC
Labels: new feature

**Comment by droidmonkey** [comment] 2019-03-17 13:43
I don't recommend ftp at all, it is insecure. If anything ftp over ssh (sftp) is preferred. Either way, recommend you use a proper cloud service with version control in this case. You are asking for trouble with "dumb" file protocols.
