### ISSUE TITLE
Tools: Delete icons which are not used

### ISSUE THREAD

**Issue by xopez** [keepassxreboot/keepassxc#2892] opened 2019-03-27 10:00 UTC
## Summary
A function among the tools to delete unused icons to save disk space.

## Desired Behavior
A button/Menu button which deletes custom icons which are not in any entry.

## Possible Solution
I think it would be the best if it's under Tools → `Delete unused icons`

## Context
It shrinks the db a bit and you don't have to manually delete not needed icons.

**Comment by droidmonkey** [comment] 2019-11-06 11:31
This is duplicate of #2110

**Closed by droidmonkey** 2019-11-06 11:31 UTC
Labels: new feature
