### ISSUE TITLE
KeeShare seems to keep a copy of the shared database and ignores the actual file contents

### ISSUE THREAD

**Issue by DDzwiedziu** [keepassxreboot/keepassxc#6901] opened 2021-09-06 20:03 UTC
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
I'm using my main database and a smaller DB for mobile devices and appropriate credentials. The smaller DB is attached via KeeShare for two-way sync. Files are synced trough Syncthing. Lately I've decided to sort the entries into categories where passwords entered into categories were wiped out. It's somewhere between KeePassDX and KeePassXC, so I that is not what I'm reporting here. In KeePassXC I've saw that the categories are present, but they are empty. Now I've tried to recover some of the situation from an earlier backup and merged a earlier file to the smaller DB (with additional copies). Now the smaller file essentially looks like the old backup, which is the state before making the categories and with unfortunately two passwords lost.

Now what's the problem. The main database synced category contains the entries as if the small database has not been merged (as in empty categories and entries that were in those categories lost). Also saving the main database just overwrites the merged file (in accordance to sync settings). I've tried repeating merging, watching if the big DB is open, if KeePassXC is open. Only when I had both the big and small backup DB's open in the same KPXC instance I could select all the entries in the small DB backup and drag them to the big DB, to the KeeShared category.

And now when I've tested the missing entries, moving an entry to a category on the mobile, the entry is missing in the big DB in KeeShare, but is present in the KeeShare'd file itself.

Second test, where I've moved the entry to a category inside KPXC, however produced a proper result. The entry is moved to a category both on the small DB and synced group inside the big DB. So while writing this issue I'm not so sure which KP this belongs too.

I can only add that it seems similar to #6477, but that maybe be only in the "KeeShare was simple, but it got too complex", because I've tripped over a edge case.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Have two DB's, let's call them "big" and "small".
2. Import the small DB using KeeShare to the big DB.
3. Add one entry to the small DB.
4. Close both.
5. Sync the small to a mobile device, where KeePassDX is installed.
6. Inside KPDX add a new category and move the entry to that category.
7. Close the small DB and sync it back to the computer.
8. Open the big DB. Inside the KeeShare the category should be present, but the entry will be missing.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Entry present in the category after syncing.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Entry missing from the small DB

## Context
[NOTE]: # ( Give us any additional information you may have. )
Not sure

[NOTE]: # ( Paste debug info from Help → About here )
KeePassDX 3.0.0_beta02
KeePassXC - Version 2.6.2
Revision: e9b9582

Qt 5.15.2
Debugging mode is disabled.

Operating system: Pop!_OS 21.04
CPU architecture: x86_64
Kernel: linux 5.11.0-7633-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.7

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux/Android
Desktop Env: KDE
Windowing System: X11

**Comment by droidmonkey** [comment] 2021-09-06 21:53
Keeshare doesn't handle groups (you call them categories?) well. This will be fixed in 2.7.0 and this is a duplicate of that issue. 

#3045

**Closed as completed by droidmonkey** 2021-09-06 21:53 UTC
Labels: duplicate, feature: KeeShare

**Comment by DDzwiedziu** [comment] 2021-09-08 12:37
> (you call them categories?)

Yes, maybe it's an issue of translating back and forth.

Anyways, good to know that's on track.
