### ISSUE TITLE
Permission being sought for unrelated sites since upgrade to KeepassXC 2.5.0

### ISSUE THREAD

**Issue by eddgrant** [keepassxreboot/keepassxc#3748] opened 2019-11-01 08:42 UTC
Hi folks,

Hope this contains useful information, give me a shout if I can provide any more detail to help get to the bottom of this.

Cheers,

Edd

## TL;DR

Access permission dialogue is referring to sites that don't have any relationship to the current URL.

## Expected Behavior
Access permission dialogue should only referring to sites that _do_ have a relationship to the current URL.

## Current Behavior
Since upgrading to KeepassXC 2.5.0 I have started getting frequent permission prompts for unrelated sites. To give an example I might navigate to the AWS signin console at which point a dialogue pops up asking permissions for access to what appear to be completely unrelated URLs in my password database. I have tried to demonstrate this in the screenshots below:

1: Navigate to AWS sign-in page, permission dialogue pops up and asks for permission for 2 totally unrelated sites (as far as I can see they are unrelated anyway).

![keepass-permission-being-sought-for-unrelated-sites](https://user-images.githubusercontent.com/604861/68012677-9c50cd80-fc82-11e9-9880-3ab03ac0a5a4.png)

2: I dismiss the dialogue, by clicking the cross in the top right corner, or the deny button. The page then behaves as normal and offers me any of the AWS logins that I have configured in KeepassXC to match this URL.

![keepass-permission-being-sought-for-unrelated-sites-2](https://user-images.githubusercontent.com/604861/68012725-c3a79a80-fc82-11e9-9c88-63f7dc721755.png)

## Possible Solution

In terms of code, no idea I'm afraid. My only thoughts are to downgrade as this only started happening when I upgraded to 2.5.0 this week.

## Steps to Reproduce
I can't provide any steps as I can't seem to find a deterministic link between the sites for which permission is sought and the URL I have navigated to.

## Context
The behaviour is confusing and an annoyance, but doesn't actually stop me from being able to do anything.

## Debug Info

KeePassXC - Version 2.5.0
Revision: 1ab8a9f
Distribution: Snap

Qt 5.9.5
Debugging mode is disabled.

Operating system: Ubuntu Core 18
CPU architecture: x86_64
Kernel: linux 5.3.0-19-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.1

Libraries:
- LIBS

Operating system: OS
CPU architecture: ARCH
Kernel: KERNEL

Enabled extensions:
- EXTENSIONS

**Comment by eddgrant** [comment] 2019-11-01 08:49
Just had another pass at this, and have noticed what _might_ be a pattern. In this case the 2 sites which permission was being sought for had issues in their URL definitions. One had too many colons in the URL e.g.

    https:://doo.com

And the other I had specified a wildcard to match any sub-domain e.g.

    https://*.parentdomain.com

Obviously the one with the duplicated colon is an invalid URL, however I thought that the `*` character _was_ a supported way of matching sub-domains in the URL? Even it if it's not, I suspect the behaviour of then asking permission for it when visiting an unrelated site is unintended?

**Comment by libklein** [comment] 2019-11-01 09:03
Possible duplicate of https://github.com/keepassxreboot/keepassxc-browser/issues/656

**Comment by droidmonkey** [comment] 2019-11-01 09:56
This is a duplicate

**Closed by droidmonkey** 2019-11-01 09:56 UTC
Labels: bug

**Comment by LeBaux** [comment] 2019-11-01 09:59
@droidmonkey could you please reference the issue so I can track it? I can't find it. Thanks.

**Comment by eddgrant** [comment] 2019-11-01 10:54
Thanks for the quick response and confirmation. Apologies for not having found the dupe issue myself first!

**Comment by droidmonkey** [comment] 2019-11-01 11:10
Yeah sorry the issue is over on the browser issue board, i didn't realize that. We will move it over.
