### ISSUE TITLE
ssh-agent: segfaults with gnome-keyring on removing a ssh key.

### ISSUE THREAD

**Issue by mannp** [keepassxreboot/keepassxc#1632] opened 2018-03-05 08:52 UTC
## Expected Behavior

To be able to remove and add ssh keys at will.

## Current Behavior

ssh-agent[11068]: segfaults.

## Steps to Reproduce (for bugs)

1. Testing key gets added and is listed in ssh-add -l

2.When I select 'remove from agent' I get the following dmesg log;

> ssh-agent[11068]: segfault at 0 ip 0000556c73f68923 sp 00007fd22b7fdb10 error 4 in gnome-keyring-daemon[556c73f21000+101000]

3. ....and ssh-add -l gives me;

> Error connecting to agent: Connection refused

## Debug Info
KeePassXC - Version 2.3.0-snapshot
Build Type: Snapshot
Revision: a06e85f

Libraries:
- Qt 5.10.1
- libgcrypt 1.8.2

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 4.15.6-1-ARCH

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by hifi** [comment] 2018-03-05 09:16
What type of key do you have, is it RSA and what is the bitness? Are you sure it's Gnome Keyring that KeePassXC is talking to because `ssh-agent` process is the OpenSSH one?

Could you paste the value of *SSH_AUTH_SOCK* environment variable from a terminal window you would launch KeePassXC from for testing purposes? You can check all SSH related environment variables with `env | grep SSH`.

**Comment by mannp** [comment] 2018-03-05 09:41
To be honest no I am not entirely clear with the ssh-agent thing, as I have just started trying to set it up.

Key is SHA256 converted using you command [here;](https://github.com/keepassxreboot/keepassxc/pull/1098)

> ssh-keygen -o -p -f id_rsa

It confused me that the keepassxc support is called ssh-agent support and not ssh-agent 'client' support as it appears to acting as a client rather than actually supplying ssh-agent functionaility? or have I misunderstood?

> SSH_AUTH_SOCK=/run/user/1000/keyring/ssh

This is a standard gnome install on arch linux.

**Comment by hifi** [comment] 2018-03-05 10:22
Thanks, that looks like GNOME Keyring indeed. I will try to reproduce the issue to see if there's something odd happening with it. There were crashing issues with `ssh-agent` process itself long before 2.3.0 was released but it was fixed but this may be related to the same thing.

You are correct that the agent feature is a client feature and not a server feature. It could be thought as "SSH Agent integration" rather than an agent itself.

**Comment by hifi** [comment] 2018-03-05 10:27
@mannp Is it possible for you to test building from release/2.3.1 branch? There are RSA related fixed that might help.

**Comment by mannp** [comment] 2018-03-05 13:14
@hifi just building the release/2.3.1 branch now, will report back shortly.

**Comment by hifi** [comment] 2018-03-05 17:37
Just type `./src/keepassxc` in the build directory to run it.

I tested this against GNOME Keyring 3.27.4 on ubuntu and it didn't crash even with KeePassXC 2.3.0.

**Comment by hifi** [comment] 2018-03-05 18:32
Master branch equals the 2.3.0 release, you'd need to do something along these lines to get the 2.3.1 WIP branch:

```
git fetch origin release/2.3.1
git checkout -b release/2.3.1 origin/release/2.3.1
```

I will try to install Antegros later this week/weekend to replicate the crash if no one figures what's going on by then.

**Comment by mannp** [comment] 2018-03-05 19:15
Thats what I have done and it built fine but the gui doesn't start and no errors appear.

I will delete and re-pull later this evening to see if the 2.3.1 branch sorts it out.

**Comment by hifi** [comment] 2018-03-06 17:18
Got some time and installed Antegros with Cinnamon and could not reproduce. I took these steps:

1. Generate encrypted RSA key with default options by doing just `ssh-keygen`
2. Create new empty database
3. Create an entry with said key
4. Try to add/remove the key multiple times with the buttons on agent page

The key was successfully added and removed from GNOME Keyring and no segfault was happening. Checked the socket was set to */run/user/1000/keyring/ssh* so it was definitely using the keyring agent. The version I have is 3.27.4+8+gff229abc-1 that was available from the repositories.

If you can reproduce this reliably, could you generate a key and configure a database in a way it definitely crashes your GNOME Keyring and share that database? I'm likely doing something wrong as I can't trigger it.

**Comment by mannp** [comment] 2018-03-07 10:03
With the release of 2.3.1 I tried it again this morning and keepassxc reports the following error when trying to remove the key. 

> 'Agent protocol error'

At this point the segfault occurs.

Also, I converted the key and didn't create a new one and have 12 or so keys that likely need converting to.

**Comment by hifi** [comment] 2018-03-07 11:21
FYI if you don't need GNOME Keyring for anything else you can always use ssh-agent directly to sort out this issue for yourself. Also you don't need to convert any keys to use this feature unless they are too old that are completely unsupported.

I still don't know how to reproduce this myself so if you could create a test case database that definitely triggers the issue for you that you can share it would help with testing as then I could be sure that there's nothing wrong (or right) with my keys or testing methods.

**Comment by hifi** [comment] 2018-03-18 05:53
@mannp @ToKaTpoHb I got this reproduced now with an empty comment. Does this occur if you set an username for the entry so that the comment is not empty when you do `ssh-add -l`?

That issue has been fixed in #1681 and it was only thought of affecting gpg-agent at the time. Can you guys please confirm having a non-empty comment fixes GNOME Keyring crashes?

Thanks!

**Comment by ToKaTpoHb** [comment] 2018-03-18 06:28
@hifi looks like keepassxc (snap) cant get comment from key. I've created key with `ssh-keygen -t rsa -b 4096 -C "MyComment"` and ...
![image](https://user-images.githubusercontent.com/11059471/37563303-63278636-2a86-11e8-89b3-69d71105ac85.png)

**Comment by hifi** [comment] 2018-03-18 07:46
@ToKaTpoHb The comment is only stored in the .pub file for RSA keys in the old (and default) format. If you want an embedded comment use `ssh-keygen -o -t rsa -b 4096 -C "MyComment"`.

As I said before you can set the username for the entry to override an empty comment in 2.3.1 where the fix for empty comments is not yet landed.

**Comment by ToKaTpoHb** [comment] 2018-03-18 20:21
@hifi Confirmed.
![image](https://user-images.githubusercontent.com/11059471/37570627-a200cff6-2afa-11e8-9817-219532e8fefb.png)

**Comment by hifi** [comment] 2018-03-19 03:52
@ToKaTpoHb Is that still the snap install? Does the snap have a separate issue of not being able to connect regardless?

Does having a comment fix GNOME Keyring from crashing with the PPA version?

**Comment by ToKaTpoHb** [comment] 2018-03-19 15:03
Yes, it is snap install. I have not found any related issues, even with "connect" as keyword. You can checkout it [here](https://bugs.launchpad.net/snapcraft)

IPPA version (KeePassXC - Version 2.3.1, Revision: 2fcaeea) not crashing right now, but...
![image](https://user-images.githubusercontent.com/11059471/37602995-4021b2fe-2b96-11e8-9ed3-ea817524e680.png)

**Comment by droidmonkey** [comment] 2018-09-24 14:17
@hifi is this still an issue?

**Comment by hifi** [comment] 2018-09-24 15:58
As far as I know, one issue was fixed and after GNOME Keyring replaced its internal agent with OpenSSH remaining issues should be OpenSSH related.

**Comment by droidmonkey** [comment] 2018-09-24 17:02
Ok I'm labeling this upstream then.

**Closed** 2018-09-24 17:04 UTC
Labels: plugin: SSH agent, upstream
