### ISSUE TITLE
DB does not lock if modified.

### ISSUE THREAD

**Issue by lordloh** [keepassxreboot/keepassxc#2277] opened 2018-09-10 18:35 UTC
KeepassXC does not lock if database is not saved.

## Expected Behavior
![capture](https://user-images.githubusercontent.com/2434923/45316693-62ac8880-b4fd-11e8-915b-2d335a18daf4.PNG)

Should lock the database on locking the windows session

## Current Behavior
If I make changes to the database > then lock the session > logging back in, I see...
![capture2](https://user-images.githubusercontent.com/2434923/45316797-b28b4f80-b4fd-11e8-8028-e124d188487c.PNG)

## Possible Solution
Save the database as `userdb.1.kdbx` and notify the user on next login

## Context
N/A

## Debug Info
KeePassXC - Version 2.3.3
Revision: 0a155d8

Libraries:
- Qt 5.10.1
- libgcrypt 1.8.2

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.17134

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by droidmonkey** [comment] 2018-09-11 02:07
Duplicate of #721

**Closed by droidmonkey** 2018-09-11 02:07 UTC
