### ISSUE TITLE
Provide a way to query a running KeepassXC instance/unlocked database from the command-line

### ISSUE THREAD

**Issue by nodiscc** [keepassxreboot/keepassxc#10238] opened 2024-01-28 14:57 UTC
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )

Currently, the only supported way to query a KeepassXC database from the command-line, is to use `keepassxc-cli`.

Unfortunately `keepassxc-cli` cannot communicate with a running KeepassXC instance, hence the password and/or keyfile must always be supplied to `keepassxc-cli`, even when KeepassXC is already running with a database already unlocked.

This is not ideal as:
- putting the database password in a script, configuration file, or using a keyfile requires storing the password on-disk in cleartext (which gives full r/w access to the database)
- asking for the password interactively prevents using this solution without any user input/fully unattended, even when the database is already unlocked in a running KeepassXC instance (see my use case below).

## Context

I am using [ansible](https://en.wikipedia.org/wiki/Ansible_(software)) (configuration management system) with secret/sensitive values stored in encrypted files managed by [ansible-vault](https://docs.ansible.com/ansible/latest/cli/ansible-vault.html). During execution, ansible is able to get the master ansible-vault decryption password from either:
- interactive input (`--ask-vault-pass`) - not fully unattended, must be entered every time ansible is ran
- a keyfile (`--vault-password-file /path/to/.ansible-vault-password` or `vault_password_file = /path/to/.ansible-vault-password` in `ansible.cfg`) - not ideal as the password is not encrypted at rest (my current solution)
- a script: just make `/path/to/.ansible-vault-password` executable and it will be used to fetch the vault decryption password

I have KeepassXC running all the time on my workstation, with my database unlocked most of the time when I'm logged in. I want to store the ansible-vault decryption password in KeepassXC, and have the `.ansible-vault-password` script fetch it from the already unlocked database (if the db is not unlocked, either error/abort and ask to unlock it manually in KeepassXC, or prompt for a password, not important).

This is not possible using `keepassxc-cli` for the reasons mentioned above.

## Examples

I suggest extending `keepassxc-cli` (or provide a separate tool) to allow querying databases from already running KeepassXC instances, using the `🌐 Browser Integration` feature or another mechanism (I have searched for ways to query KPXC using dbus, keeshare, etc, without success).

For example:

```bash
# --use-proxy is just an example, for lack of a better name
$ keepassxc-cli show --use-proxy --show-protected -a Password /path/to/my/database.kdbx 'my-vault-password'
MY_s3cr3t_pa55word
```

Advantages of using the browser integration mechanism:
- KeepassXC will show an allow/deny dialog when a new client request access to the database
- KeepassXC will show an allow/deny dialog when a specific item/db entry is requested (you can choose to remember the allow decision)
- The native messaging key will still have to be stored *somewhere* on the disk, but it only gives *read* access to a *single* item (unlike a keyfile). Locking the database makes the native messaging key alone useless.

--------------------

## Workaround

I have found the following workaround using https://github.com/hargoniX/keepassxc-proxy-client but would really like to see this integrated natively in KeepassXC/`keepassxc-cli`:
- unlock your KeepassXC database
- create an entry containing the ansible-vault password, and give it a unique URI, for example `ansible://myvault`
- setup the KeepassXC proxy client:
```bash
python3 -m venv .venv && source .venv/bin/activate
pip3 install git+https://github.com/hargoniX/keepassxc-proxy-client.git@0.1.7
```
- create a new client association - this will cause KeepassXC to raise a prompt to allow/deny access
```bash
keepassxc_proxy_client create > ~/.config/keepassxc/keepassxc_proxy_client.json
```
- make sure your `ansible.cfg` has `vault_password_file = .ansible-vault-password` set
- create (or modify) the `.ansible-vault-password` file with the following contents, and make it executable:
```bash
#!/bin/bash
source .venv/bin/activate
keepassxc_proxy_client get ~/.config/keepassxc/keepassxc_proxy_client.json ansible://myvault
```

The first time this is used, KeepassXC will raise a prompt allowing you to allow/deny access from the native messaging client registered in `~/.config/keepassxc/keepassxc_proxy_client.json` to **this particular URL**, and possibly remember this decision.

Thanks a lot for maintaining KeepassXC <3.

**Comment by droidmonkey** [comment] 2024-01-28 15:11
This is a duplicate of #5069

**Closed as not planned by droidmonkey** 2024-01-28 15:11 UTC
Labels: duplicate, feature: CLI
