### ISSUE TITLE
Adding HMAC auth using Yubikey

### ISSUE THREAD

**Issue by askuechler** [keepassxreboot/keepassxc#2945] opened 2019-04-05 06:53 UTC
Hi,
I am trying to add hmac auth to an existing database on my mac. Keepassxc version 2.4.0. As soon as I click ok on the add yubikey auth keepassxc crashes.

here are some details from the crash report:

Process:               KeePassXC [3249]
Path:                  /Applications/KeePassXC.app/Contents/MacOS/KeePassXC
Identifier:            org.keepassx.keepassxc
Version:               2.4.0 (???)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           KeePassXC [3249]
User ID:               501

Date/Time:             2019-04-05 08:51:50.391 +0200
OS Version:            Mac OS X 10.14.3 (18D109)

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000008
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [3249]

**Comment by phoerious** [comment] 2019-04-05 08:40
Duplicate of #2834.

**Closed by phoerious** 2019-04-05 08:40 UTC
