### ISSUE TITLE
upgraded to version 2.5.0 as prompted, password no longer works

### ISSUE THREAD

**Issue by fangio10** [keepassxreboot/keepassxc#3705] opened 2019-10-28 13:46 UTC
password to unlock database no longer works after upgrading to version 2.5.0, backup copy of database reports the same credential failure issue.

I have tried uninstalling and re-installing, can't unlock the database

## Expected Behavior
password expected to work to unlock database from one version of keepassxc to next

## Current Behavior
credential failure, HMAC mismatch

## Steps to Reproduce
1. Prompted to update to release 2.5.0
2. Install version 2.5.0
3. attempt to unlock database with password

## Context
none that i know of, windows 10 user

## Debug Info
KeePassXC - 2.5.0

Operating system: Windows 10
CPU architecture: 64

**Comment by phoerious** [comment] 2019-10-28 13:54
Duplicate of #3678.

**Closed by phoerious** 2019-10-28 13:54 UTC
Labels: bug

**Comment by fangio10** [comment] 2019-10-28 13:57
yes after lodging this ticket i attempted to uninstall again except this time i removed the keepassxc folder under appData and ran a registry cleaner as well

re-installed and decrypted fine

looks like something went amiss with the uninstallation of the older version.. at any rate happy to see this ticket closed before i got the chance.. keep up the good work :)
