### ISSUE TITLE
[Feature Request] Global Search window which directly inserts selected password in focused application

### ISSUE THREAD

**Issue by yennor** [keepassxreboot/keepassxc#630] opened 2017-06-08 15:08 UTC
It would be great if there would be a Global Shortcut, with which a search window would be opened. When choosing a password from the shown results, it should be entered directly in the application which had the focus before. It should be possible to use the search window by only using the keyboard.
When you need to enter passwords in the shell or programs which do not support keepassxc and also don't have any meaningfull window title (or don't change them at all), it's quite time consuming opening keepassxc first, copy it to clipboard and then paste it.

**Comment by TheZ3ro** [comment] 2017-06-08 18:13
This is a duplicate of #429. Closing

**Closed by TheZ3ro** 2017-06-08 18:13 UTC
