### ISSUE TITLE
Add an optional number to the passphrase (diceware) generator

### ISSUE THREAD

**Issue by shaneknysh** [keepassxreboot/keepassxc#4418] opened 2020-03-10 02:31 UTC
Add a random number to the passphrase generator. 

## Summary
The current passphrase generator only includes words selected from the word list but most sites still require a number for a password to be valid. 

## Desired Behavior
Add a random number into the generated passphrase 
rigidness 3419 throat abandoned sprout
OMNIVOROUS DIZZINESS NEFARIOUS 111498 NEFARIOUS
Cuticle Lantern 23237 Shelf Gadget

## Possible Solution
Add an option in the passphrase generator to include a random number. 

Adding the option should not be difficult. Adding the option and keeping the passphras dialog clean and usable will be the key. The option will need to have a check box to include the option and the ability to set the  minimum and maximum length. 

## Context
I would like this feature for my own use.

**Comment by droidmonkey** [comment] 2020-03-10 03:29
Duplicate of #4209

**Closed by droidmonkey** 2020-03-10 03:29 UTC
Labels: new feature
