### ISSUE TITLE
Quick unlock enabled - short hang / freeze after unlocking database on macOS Monteray (M1)

### ISSUE THREAD

**Issue by philBrown** [keepassxreboot/keepassxc#8767] opened 2022-11-07 23:30 UTC
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

If _Quick Unlock_ is **enabled**, after unlocking the database there's a brief pause complete with beachball before the app is usable.

I get a similar delay when closing the app.

Seems related to #8678

With _Quick Unlock_ **disabled**, there is no such delay and the app is usable near instantly.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Open KeepassXC
2. Enable _Quick Unlock_: Preferences -> Security
3. Unlock a database

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

The database opens near-instantly and is ready for use.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

There's a noticeable delay plus the macOS beachball icon.

## Context
[NOTE]: # ( Give us any additional information you may have. )

KeePassXC - Version 2.7.4
Revision: 63b2394

Qt 5.15.6
Debugging mode is disabled.

Operating system: macOS 12.6
CPU architecture: arm64
Kernel: darwin 21.6.0

**Comment by droidmonkey** [comment] 2022-11-08 00:28
There is always a delay when unlocking your database for the key transformation. Quick unlock still requires that. Reduce your encryption delay if you want it to be faster. 

Can you confirm that is what we are talking about here?

**Comment by philBrown** [comment] 2022-11-08 01:15
@droidmonkey sorry, I'm not following.

With quick unlock **enabled**, there's a noticeable _hang_ when unlocking the database.
With quick unlock **disabled**, there is no such delay.

> Reduce your encryption delay if you want it to be faster

I'm not aware of this. Is that a setting somewhere? If so, I cannot find it.

**Comment by droidmonkey** [comment] 2022-11-08 02:31
Are you sure the hang isn't on the apple side?

**Comment by philBrown** [comment] 2022-11-08 03:26
@droidmonkey What does that even mean? And no, I have no idea because KeepassXC doesn't provide logs.

Al I know is that I upgraded from 2.7.1 to 2.7.4 and found it started lagging after unlocking the DB. Disabling quick unlock seemed to _"fix"_ it but I thought it might be something you'd like to know about.

**Comment by droidmonkey** [comment] 2023-02-22 02:54
Closing since this isn't reproducible or reported by anyone else

**Closed as completed by droidmonkey** 2023-02-22 02:54 UTC
Labels: more info needed, platform: macOS, feature: QuickUnlock
