### ISSUE TITLE
Make backups more configurable

### ISSUE THREAD

**Issue by meersjo** [keepassxreboot/keepassxc#4603] opened 2020-04-15 08:59 UTC
## Summary
Currently, the automatic backup feature only keeps a single backup file, and overwrites it on every save. Combined with the default save-on-every-change option, this means that as soon as the user makes two consecutive changes (or multiple users make consecutive changes), the original database is lost.

## Desired Behavior
In order to prevent inadvertent data loss, considerably more complex backup behaviour would be desirable.

Possibilities:
 * Minimal age of backup file before overwriting
 * Use name of client host/active user/? in backup file (useful for files on shared storage)
 * timestamped backup files
   * Option for automated cleanup
   * Decremental cleanup (1 file per day for the last week, 1 per week for the last month etc) ?
 * Configurable location for backup files
   * Backup to specified removable storage if it is present
   * Backup to remote locations (dav/S3/?)

**Comment by droidmonkey** [comment] 2020-04-16 19:17
Duplicate of #3279, and see discussion in there specifically https://github.com/keepassxreboot/keepassxc/issues/3279#issuecomment-536190299

**Closed by droidmonkey** 2020-04-16 19:17 UTC
Labels: new feature
