### ISSUE TITLE
Global hide and show keyboard shortcut 

### ISSUE THREAD

**Issue by georgesnow** [keepassxreboot/keepassxc#3021] opened 2019-04-17 00:26 UTC
User defined global keyboard shortcut to show and hide keepassxc

1password has similar feature (cmd+\\) can be user defined and it’s intended to be used in conjunction with the menu bar icon
It launches the mini version however the the regular keepassxc window would work just as well

I wrote an applescript to mimic the behavior with Fastscripts but native solution would be preferable
It is very helpful for working in multiple types of apps 
That you are known to fail global Autotype (can’t get make a good match) so you end up having to 
Bring up the window anyway and manually copy the password
Ie 
iterm fetch finder(smb)

**Comment by georgesnow** [comment] 2019-04-17 00:44
Oh and the focus should be the search field for quick access to find a particular entry

**Comment by droidmonkey** [comment] 2019-04-17 00:46
Duplicate of #99

**Closed by droidmonkey** 2019-04-17 00:46 UTC
Labels: new feature
