### ISSUE TITLE
No Mac option for downloading 2.1.1

### ISSUE THREAD

**Issue by ligyxy** [keepassxreboot/keepassxc#262] opened 2017-02-07 02:13 UTC
Glad to see the 2.1.1 version, while I don't find the link for mac system.

Should I expect there would be dmg package for Mac in the short future? Or this version is not available for Mac?

**Comment by droidmonkey** [comment] 2017-02-07 02:28
It's coming, our apple builder is AFK tonight. Will close this once its posted.

**Comment by TheZ3ro** [comment] 2017-02-07 12:59
@rockihack 
I'm building KeePass.dmg on macOS 10.12 with `-DCMAKE_CXX_FLAGS="-mmacosx-version-min=10.7"`.
When I start it on 10.11 it tells me:
```
Dyld Error Message:
   Symbol not found: _clock_gettime
   Referenced from: /Applications/KeePassXC.app/Contents/MacOS/../Frameworks/libmicrohttpd.12.dylib (which was built for Mac OS X 10.12)
   Expected in: /usr/lib/libSystem.B.dylib
```

**Comment by rockihack** [comment] 2017-02-07 13:14
What is your question?
You probably need to build libmicrohttpd with `-DCMAKE_CXX_FLAGS="-mmacosx-version-min=10.7"` too.
However I never built keepassxc and keepassx doesn't depend on libmicrohttpd.

**Comment by TheZ3ro** [comment] 2017-02-07 13:34
I'm using libmicrohttpd from brew that is compiled for 10.12 I think.
I was asking if you know an alternative since you are better than me on MacOS :smile:

**Comment by rockihack** [comment] 2017-02-08 18:48
This issue is related to xcode 8 and weak imports.
Try adding `-no_weak_imports` to LDFLAGS and then build libmicrohttpd.

https://github.com/Homebrew/homebrew-core/issues/3727

**Comment by varjolintu** [comment] 2017-02-10 09:56
Here's a compiled version of 2.1.1 for macOS Sierra (Qt 5.8.0.1):
[https://dl.dropboxusercontent.com/u/55238633/software/KeePassXC-2.1.1.dmg](url)

**Comment by TheZ3ro** [comment] 2017-02-10 10:27
We already had a macOS Sierra dmg, the problem is that libmicrohttpd used for KeePassHTTP on brew is compiled for Sierra and building a dmg from Sierra will make it uncompatible with macOS < 10.12, See #265.

So I've removed the Sierra-only dmg until #265 isn't solved

**Comment by phoerious** [comment] 2017-02-11 16:56
I rebuilt the DMG, can you please test https://github.com/keepassxreboot/keepassxc/releases/download/2.1.1/KeePassXC-2.1.1.dmg ?

**Comment by phoerious** [comment] 2017-02-11 19:53
I wasn't able to build a binary that works on OS X <= 10.12 with libmicrohttpd enabled. I therefore built two versions now, one with and one without KeePassHTTP support. The one without should also work on 10.7 and newer.

In 2.1.2 we will get rid of libmicrohttpd and will therefore also be able to provide a single DMG which should work on all recent OS X versions.

**Closed by phoerious** 2017-02-11 19:53 UTC
Labels: task
