### ISSUE TITLE
Caret symbol in password is sometimes output as ampersand when using auto-type

### ISSUE THREAD

**Issue by jakob-dunning-agan** [keepassxreboot/keepassxc#10864] opened 2024-06-06 14:35 UTC
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
When including one or more caret symbols in passwords, sometimes auto-type outputs an ampersand instead of the first caret symbol. Right clicking in the app and selecting "Copy password" seems to always work as expected.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Create a password with one or more caret symbols ("^") in it
2. Use auto-type a few times to paste the password to a text document

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
I expect a caret symbol always to be output as a caret symbol

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Instead of the caret symbol, sometimes an ampersand appears in the output instead

## Context
[NOTE]: # ( Give us any additional information you may have. )
KeePassXC - Version 2.7.4
Revision: 63b2394

Qt 5.15.8
Debugging mode is disabled.

Operating system: Debian GNU/Linux 12 (bookworm)
CPU architecture: x86_64
Kernel: linux 6.6.13+bpo-amd64

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.19.3
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.4
Revision: 63b2394

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Gnome
Windowing System: X11

**Comment by droidmonkey** [comment] 2024-06-06 14:46
What keyboard layout are you using?

**Comment by jakob-dunning-agan** [comment] 2024-06-06 16:12
Standard German/Germany layout
https://en.wikipedia.org/wiki/German_keyboard_layout#/media/File:KB_Germany.svg

**Comment by c4rlo** [comment] 2024-06-16 21:52
This looks like a dupe of #7610.

**Comment by droidmonkey** [comment] 2024-06-16 22:27
Yup

**Closed as not planned by droidmonkey** 2024-06-16 22:27 UTC
Labels: duplicate, platform: Linux, feature: Auto-Type
