### ISSUE TITLE
Show TOTP in entry preview panel config

### ISSUE THREAD

**Issue by ghost** [keepassxreboot/keepassxc#5429] opened 2020-09-14 10:26 UTC
## Summary
Have an option in the convenience settings to 'Hide TOTP in the entry preview panel' just like there is for passwords.
If the checkbox is set you would have to manually click on the TOTP icon as you have to now.
If the checkbox is unset you would see the current TOTP automatically when viewing the entry preview panel.

For security reasons you can have this automatically enabled by default, so users will have to manually disable it.

## Context
It is really just a convenience suggestion.

**Comment by juk0de** [comment] 2023-02-18 07:48
I came here to suggest the same. Since TOTP is widely used nowadays, it should be more convenient to use. Especially users who are not so technically savvy often have problems finding the TOTP for an entry (they usually never try the context menu). I know there's this tiny little icon on the right where you can visualize the current TOTP for a few seconds, but it's really hard to find (and also doesn't support copy&paste). Having the TOTP in the same area as the password and other stuff totally makes sense and would significantly improve the UI, imo.

**Comment by droidmonkey** [comment] 2023-02-18 13:00
https://keepassxc.org/docs/KeePassXC_UserGuide.html#_adding_totp_to_an_entry

See the end. There are actually four ways to view and copy totp codes (not including Auto-Type and browser extension)

**Comment by juk0de** [comment] 2023-02-18 16:31
> There are actually four ways to view and copy totp codes 

I found three and all of them have flaws:
* the little clock to the in the leftmost column: can copy to clipboard, but not show the TOTP
* the little clock on the right side, above the preview pane: can show the TOTP, but not copy it to clipboard
* the context menu: inconvenient and hard to find, like all context menus (because they're hiding functionality from sight by design), but at least there's a keyboard shortcut

I don't know what the fourth one is. If you mean the QR code window: that can't show the current TOTP.

I've been using KeePassXC daily for over a year now, but didn't discover the first two possibilities until today (been using context menu / keyboard shortcut). It's almost like someone tried very hard to hide TOTPs from the user. For a less tech-savvy person (like my wife) it's almost impossible to discover. If it's not part of the (obvious and well visible) preview pane, it could as well be hidden in a safe on the moon. I really don't understand why it's not part of the preview pane, like all the other credentials. It just doesn't make sense...

Btw: the browser plugin is not an equivalent solution, unfortunately. In theory, it provides the best user experience, but in practice it works only for about 50% of the websites, without any tinkering. And even if you fix the login URLs and use custom login fields (which is already out of scope for many users) it will never work on 100% of websites.

**Comment by droidmonkey** [comment] 2023-02-18 16:36
Keyboard shortcut is the fourth. If you setup totp then you already found the context menu / top menu so you aren't making any sense. This is also clearly documented.

**Comment by juk0de** [comment] 2023-02-18 16:53
> If you setup totp then you already found the context menu / top menu so you aren't making any sense.

There's a big difference between setting sth. up once and using it regularly (try reading a book on UI design). There's no contradiction in what I wrote. I also don't have a problem to set this up for others **once** but I don't want to show them again and again where to find it, just because of a confusing UI. What actually doesn't make sense is the location of TOTPs.

> This is also clearly documented.

You know that you have a problem in the UI if you have to refer a user to the documentation for a simple task like showing (not configuring!) a TOTP...

**Closed** 2023-06-03 13:13 UTC
Labels: new feature, Hacktoberfest
