### ISSUE TITLE
Keyboard layout in .appimage

### ISSUE THREAD

**Issue by theonlydoo** [keepassxreboot/keepassxc#272] opened 2017-02-08 11:09 UTC
# Wrong keyboard layout in appimage
I was expecting to enjoy azerty layout, like the rest of my OS, but it seems that qwerty is the enforced .appimage keyboard layout.
* Fedora 25
* KeepassXC 2.1.1

## Expected Behavior
azerty keyboard layout

## Current Behavior
qwerty keyboard layout

## Steps to Reproduce (for bugs)

1. setup fedora
2. use layout fr
3. start appimage
4. try to type in azerty

**Comment by phoerious** [comment] 2017-02-08 17:28
We do not enforce any keyboard layout. Here on Arch I can use both QWERTY and QWERTZ without issues.
Could you maybe check if somehow your application-specific input settings are mixed up? I suppose this is rather an issue of your desktop environment than of the AppImage.

**Comment by theonlydoo** [comment] 2017-02-09 09:31
@phoerious I have a single keyboard layout on my distro, it's not enforced by the app either, I left out the default settings while trying out keepassXC (so much of a good job that I kept using it btw, congrats and thank you for the work!) I invite you to try to reproduce my issue in a VM, because I haven't seen anything that may enforce another keyboard layout in keepassXC or elsewhere.

**Comment by phoerious** [comment] 2017-02-09 09:51
I cannot reproduce this on either Arch or Ubuntu. I will try this in a Fedora VM. But even if I can reproduce it there, it's probably a Fedora bug.

**Comment by phoerious** [comment] 2017-02-09 12:04
I tried it in a Fedora Workstation 25 VM and still can't reproduce your problem. I added German (QWERTZ) and French (AZERTY) and they both work fine. If there is only one layout and I change it, I need to restart KeePassXC, though. With multiple configured layouts, I can switch on-the-fly.

**Comment by theonlydoo** [comment] 2017-02-09 12:16
This is weird, I can't manage to switch layout even after restart the app (I tried to configure two layouts and switch on the fly also) :
![wut](https://cloud.githubusercontent.com/assets/1903124/22782984/f6945042-eec9-11e6-9e04-64bdb53ca4c0.gif)

**Comment by phoerious** [comment] 2017-02-09 12:18
I switched from the taskbar, not with hotkeys.

**Comment by theonlydoo** [comment] 2017-02-09 12:19
I will try to build an rpm instead of the appimage and see if this is appimage+fedora related

**Comment by phoerious** [comment] 2017-02-09 12:24
I think, en-us doesn't really count as a custom layout for some reason. You need to configure two layouts of which none is QWERTY I think. With only QWERTY and AZERTY I needed to restart KeePassXC after a switch.

**Comment by theonlydoo** [comment] 2017-02-09 12:26
compiled version works fine, even tho I can't pin it to my dash2dock because it'll start a new instance instead of calling back the running one **BUT** it works fine and I love the app so I'll keep this version and wait for new releases!

**Comment by phoerious** [comment] 2017-02-09 12:28
So, can I close this?

**Comment by theonlydoo** [comment] 2017-02-09 12:29
done! Thx for the help :)

**Comment by phoerious** [comment] 2017-03-07 11:59
Since we have this issue also in #324 with a better description, I'll close this again.

**Closed by phoerious** 2017-03-07 11:59 UTC
Labels: duplicate
