### ISSUE TITLE
Loading a database via a windows google drive app folder fails to read

### ISSUE THREAD

**Issue by TheSmallBlue** [keepassxreboot/keepassxc#10045] opened 2023-11-22 03:16 UTC
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Trying to open a database from a drive or folder created via the Windows Google Drive app results in an error appearing at the top of the window in red: "Error while reading the database: Failed to read database file".

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Upload a database to google drive
2. Install and set up the official Google Drive windows app
3. Open KeepassXC, locate your database in the new drive the Google Drive app creates
4. Type in the password
5. Results

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
The database should open up fine

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
An error "Error while reading the database: Failed to read database file" pops up in red at the top and the database does not open

## Context
[NOTE]: # ( Give us any additional information you may have. )
I originally thought somehow Google Drive had corrupted my file, but if I download the file instead and I try to open it, there is no issue whatsoever, so it's not that.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.6
Revision: dd21def

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows
Desktop Env: N/A
Windowing System:  N/A

**Comment by droidmonkey** [comment] 2023-11-22 03:40
Does the Google drive client even download the kdbx file when it is accessed? This problem doesn't appear to be on our end at all.

**Comment by TheSmallBlue** [comment] 2023-11-22 04:01
Honestly I'm not very sure? I dont understand what the official google drive client even does but it doesn't look like its actually downloading the contents of your drive onto your hard drive. Though apparently making a file available offline (via right clicking it) does make it work as an actual physical downloaded file, but even after doing that it still doesnt work

**Comment by TheSmallBlue** [comment] 2023-11-22 04:05
Here's some more info about my specific drive configuration:
The specific app is: https://www.google.com/drive/download/

And my settings on the app look like this:
![image](https://github.com/keepassxreboot/keepassxc/assets/24967815/95d23906-8f53-478a-b3dd-5c9da0e3b19e)
![image](https://github.com/keepassxreboot/keepassxc/assets/24967815/2130d381-6012-44c0-95b1-c279d075d275)
![image](https://github.com/keepassxreboot/keepassxc/assets/24967815/44d7beee-ab5d-422e-9c3c-0b814c230fd2)
![image](https://github.com/keepassxreboot/keepassxc/assets/24967815/0352a84a-8e71-4ac5-95ca-ec61bf84d081)

**Comment by droidmonkey** [comment] 2023-11-22 04:12
Looks like you have the drive located outside your main hard drive and outside your user folder. Something similar to this came up before, but the error was very different.

**Comment by droidmonkey** [comment] 2023-11-22 04:14
This one: https://github.com/keepassxreboot/keepassxc/issues/9937

**Comment by TheSmallBlue** [comment] 2023-11-22 06:36
> This one: #9937

I did get that same error while trying to open the drive folder through the database file chooser once, but I restarted my computer and the error was gone so I assumed it was something on my side.

This worked up until now though, like that one folder with those exact settings worked up until out of seemingly nowhere it just didn't. I feel like it might be something on Google Drive's app's side, since I hadn't even updated keepassxc or changed any settings in it at all

**Comment by droidmonkey** [comment] 2023-11-22 11:50
It's definitely on the google drive side, we just open files, nothing fancy.

**Comment by JohnLGalt** [comment] 2023-11-22 16:20
FWIW - I use the drive letter instead of folder and have no issues with my database stored in Drive.

if it worked before and stopped working out of the blue, it's either an update to the Drive software changing something, or it could be an update to your OS. Are you using Windows 10/11? Have you recently enabled restricted access to the Special user folders (Documents, pictures, etc.)? Could a 3rd party AV solution also have enabled something like this?

**Comment by TheSmallBlue** [comment] 2023-11-22 16:36
> Are you using Windows 10/11? Have you recently enabled restricted access to the Special user folders (Documents, pictures, etc.)? Could a 3rd party AV solution also have enabled something like this?

I am using Windows 11, I havent changed anything about the special user folders ever since i originally set up my pc ages ago, and I didnt install any new software or AV solution at all in the recent days so I doubt they could've caused this. (I guess I bought an Xbox series controller adaptor and plugged it in for the first time yesterday but i really, really really doubt its related)

**Comment by TheSmallBlue** [comment] 2023-11-22 16:37
For clarification I straight up don't use a 3rd party AV, I only use Windows Defender

**Comment by JohnLGalt** [comment] 2023-11-22 17:59
Have you recently taken the Windows 23H2 update? 

Also verify that controlled folder access is **off**: Defender Security --> Virus & threat protection --> Manage settings --> Manage Controlled folder access 

Another thing - you've set the files to stream, can you set the database to always be available locally (offline)?

According to Drive instructions, you have to go to the file and enable this via right click:

<img width="290" alt="Screenshot 2023-11-22 125629" src="https://github.com/keepassxreboot/keepassxc/assets/7432512/bf676d4a-be9f-45ac-99d4-7464d21294b2">

With Win11, you have to right click, then click more options at the bottom, to get the following:

<img width="360" alt="Screenshot 2023-11-22 125701" src="https://github.com/keepassxreboot/keepassxc/assets/7432512/7b68f1b2-c4ad-40f6-8c2f-047d74642eb7">

If you change that to available offline, does KPXC start seeing the file?

**Comment by TheSmallBlue** [comment] 2023-11-22 23:39
> Have you recently taken the Windows 23H2 update?

Nope, I'm on 22H2 still, updated to it around May, so a while ago
![image](https://github.com/keepassxreboot/keepassxc/assets/24967815/afad7bde-32ad-43f2-9966-9ecbb0b2b778)

> Also verify that controlled folder access is **off**: Defender Security --> Virus & threat protection --> Manage settings --> Manage Controlled folder access

![image](https://github.com/keepassxreboot/keepassxc/assets/24967815/f81ffdff-c038-43e5-9119-8e0b08cbe412)
It is, yeah, didnt change anything here.

> Another thing - you've set the files to stream, can you set the database to always be available locally (offline)?
> If you change that to available offline, does KPXC start seeing the file?

![image](https://github.com/keepassxreboot/keepassxc/assets/24967815/e4eba147-20b7-4325-ad4b-6d122091e59e)

Did this, KPXC still can't open it. The problem isn't that it can't see it, the problem is that trying to open it and inputting my password results in the error I mentioned in the first post.

**Comment by droidmonkey** [comment] 2023-11-22 23:57
~~I believe that error (the latter half comes directly from Qt) is because some other process is holding a lock on the file. Try closing google drive client and try opening the database again.~~

**Comment by JohnLGalt** [comment] 2023-11-22 23:59
> Did this, KPXC still can't open it. The problem isn't that it can't see it, the problem is that trying to open it and inputting my password results in the error I mentioned in the first post.

I should have picked up on that - if it could not even see the file, it should say exactly that. Since you get to the password entry it means it is seeing the file, at first, but something after that is breaking.

> I believe that error (the latter half comes directly from Qt) is because some other process is holding a lock on the file. Try closing google drive client and try opening the database again.

That makes sense. Sorry I didn't realize this at first.

**Comment by droidmonkey** [comment] 2023-11-23 00:02
Oops I was wrong, the error shown is from us. It is only shown when the first two bytes of the file don't match what was expected:

https://github.com/keepassxreboot/keepassxc/blob/develop/src/format/KeePass2Reader.cpp#L69

Are you sure you are opening a valid database file? The error would indicate it is not actually a kdbx database.

**Comment by TheSmallBlue** [comment] 2023-11-23 00:17
> Oops I was wrong, the error shown is from us. It is only shown when the first two bytes of the file don't match what was expected:
> 
> https://github.com/keepassxreboot/keepassxc/blob/develop/src/format/KeePass2Reader.cpp#L69
> 
> Are you sure you are opening a valid database file? The error would indicate it is not actually a kdbx database.

There is something weird here... if I
- Go to my google drive through my web browser
- Download the file through it
- open it

It works perfectly, HOWEVER; if I INSTEAD 
- Copy the file from the Google drive folder the app creates
- Paste it somewhere else
- open it
It returns a DIFFERENT error from the usual "failed to read database file" one, instead saying "Not a KeePass database".

The file stored in my Google Drive is fine, since I can download it and open it with no problems, but the file google drive creates on its folder isn't fine.

Looking at thier properties side by side the only difference, everything looks the same except the small security warning on the bottom:
![image](https://github.com/keepassxreboot/keepassxc/assets/24967815/af440bca-891b-45de-b5da-cef5bb8d1bfd)
Left is the one copied from the drive folder, the one that errors.
Right is the one downloaded directly from the site, the one that works fine.

The one that works fine has the security notice, while the one that doesn't, doesn't.

Maybe new versions of the google drive app append some info to the start of the file? I hope that's not it, that would be an absurdly bad decision by them

**Comment by droidmonkey** [comment] 2023-11-23 00:19
Hmmm I'll have to see if I can replicate this, but I doubt I will be able to.

**Comment by TheSmallBlue** [comment] 2023-11-23 00:19
I opened up the copied file in a hex editor and yeah i see the issue: It's completely empty

![image](https://github.com/keepassxreboot/keepassxc/assets/24967815/1f326615-7c55-4e61-b267-a23feb345015)

**Comment by droidmonkey** [comment] 2023-11-23 00:46
Hah that'll do it! Clearly the Google drive app is just reserving the space for the file and not actually downloading it. Frankly I hate Google drive, the app itself was reason enough for me to switch to onedrive.

**Comment by JohnLGalt** [comment] 2023-11-23 05:32
But that should **not** be the case, since he has it set to make available _offline_.

Something is not right here.

If you first check the box to unblock it, _then_ check the file in the hex editor, is it still blank?

**Comment by TheSmallBlue** [comment] 2023-11-23 23:51
> If you first check the box to unblock it, _then_ check the file in the hex editor, is it still blank?

Yup, to be clear though I cant open the file directly from the drive using my hex editor (HxD), I have to copy it elsewhere first

**Comment by droidmonkey** [comment] 2023-11-24 00:28
>  I cant open the file directly from the drive using my hex editor

There is clearly something fundamentally wrong with the Google drive client. I am closing this issue because the problem isn't with KeePassXC. Although it would be nice to find a fix for others who have experienced this silliness as well.

**Closed as not planned by droidmonkey** 2023-11-24 00:28 UTC
Labels: platform: Windows, downstream

**Comment by JohnLGalt** [comment] 2023-11-28 21:13
One thing to note - the Google Drive client has also been deleting people's files starting with version 84.0.0.0 through the current 84.0.4.0. I seem to be one of the lucky ones that has not lost any files, but thus far the rumor mill is tying it directly to the Windows Drive client software. The issue seems to go back as far as April / May 2023, so it could very well be a alternate manifestation of whatever the actual issue(s) behind Drive losing people's files.

Either way, though, DM called it - Drive issue for sure.

**Comment by droidmonkey** [comment] 2023-11-29 02:06
https://arstechnica.com/gadgets/2023/11/google-drive-is-investigating-sync-issues-as-users-complain-of-lost-files/

This doesn't look good! Make sure you still have that working manual download.

**Comment by JohnLGalt** [comment] 2023-11-29 13:21
Yeah, I'm making sure I mirror my Google Drive repository locally, just to be safe. @TheSmallBlue should too, as should anyone else.

**Comment by Rots** [comment] 2024-09-16 10:52
As a reference, my workaround is to use [rclone](https://rclone.org/) to mount the google drive instead of the google drive app
