### ISSUE TITLE
Cant change keyboard layout after i accidently try to autotype greek

### ISSUE THREAD

**Issue by nbibzgvs** [keepassxreboot/keepassxc#596] opened 2017-05-26 16:37 UTC
## Expected Behavior
I expected that the keyboard shortcat for layout would work

## Current Behavior
Couldnt change layout using the keyboard shortcut after i used autotype shortcut 

## Possible Solution
Its really annoying not to be able to change layout.

## Steps to Reproduce (for bugs)
1.I open my computer. 
2.I tried to login using autotype to the website https://top.host/
3.I forgot that at the time i tried the autotype combination i had the greek layout
4.Keepassx enter the password and login with greek characters.
5.When i realized that i tried to change the layout but it didnt change.(using the keyboard shortcat)
6.It happens everytime i follow the upper sequence

## Your Environment

* KeePassXC 2.1.4
* Qt version (e.g. Qt 5.3): 5.7.1
* Compiler (e.g. Clang++3.6.0): gcc 6
* Operating System and version: debian  "stretch" testing

**Comment by Dia-m-onD** [comment] 2017-11-04 08:54
Having the same with Russian layout and latest Archlinux, keepassxc v2.2.2

**Comment by frostasm** [comment] 2017-11-16 11:39
Having the same with Ukrainian layout, Ubuntu 17.04 
Related issues #324 #474

**Comment by romanshevelev** [comment] 2018-01-24 11:53
With Russian layout too.
After autofill in russian layout keyboard doesn`t switch layout until Xorg restart

**Comment by droidmonkey** [comment] 2019-07-10 01:46
Duplicate of #2246

**Closed by droidmonkey** 2019-07-10 01:46 UTC
