### ISSUE TITLE
Doesn't open on Windows 10

### ISSUE THREAD

**Issue by Dr4c0s** [keepassxreboot/keepassxc#4772] opened 2020-05-21 14:23 UTC
## Overview

i updated keepassxc to the version 2.5.4 but if i try to open it, nothing opens. in the taskmanager i can see it only as a background process but not in the system tray.
I already try Portable Version and new installition but with no success
i have this problem on my desktop pc, i have it on my laptop and on a new created vm too
My Desktop Pc has Windows 10 Pro Build 1909.
My Laptop has Windows 10 Home Build 1909
VM has Windows 10 Education Build 1809

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.5.4

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10

**Comment by droidmonkey** [comment] 2020-05-21 16:13
Please try our snapshot to confirm this is no longer a problem: https://snapshot.keepassxc.org

Are you running anti-virus software? If so is it sending KeePassXC to quarantine?

**Comment by Dr4c0s** [comment] 2020-05-21 18:05
My VM hasn't an anti-virus software.
My Desktop and Laptop have an anti-virus software but it does nothing with keepassxc.

**Comment by Dr4c0s** [comment] 2020-05-21 18:09
i tried the latest snapshot but the i have the problem too

**Comment by droidmonkey** [comment] 2020-05-21 19:03
have you tried restarting your computer?

**Comment by Dr4c0s** [comment] 2020-05-21 20:23
yes i already tried that

**Comment by droidmonkey** [comment] 2020-05-21 20:33
I am at a loss on how this is possible.

**Comment by MLipfert1** [comment] 2020-05-21 21:28
Duplicate of #4583. Seems to be related to QT 5.14.2. The latest version of the Logitech G Hub software is showing a similar behavior on my machine. It comes with the same version of QT.

**Closed** 2020-05-22 00:43 UTC
Labels: bug
