### ISSUE TITLE
Huge icons

### ISSUE THREAD

**Issue by gerroon** [keepassxreboot/keepassxc#2923] opened 2019-03-31 17:40 UTC
Hi

I just downloaded the appimage for 2.4.0 and the inferface looks crazy. The icons are so huge that I can see anything, navigating becomes very hard.

This issue was not there in 2.3.4 just 5 mins ago before the upgrade.

Please see the image and compare the text size of the top menu with the icon sizes.

I am on Debian Buster, x64 using 2.4.0 appimage. I tried the snap version, that as the exact same issue.

Some apps provide dpi settings, please either resolve this if possible or provide dpi settings.

![Screenshot_2019-03-31_12-36-07](https://user-images.githubusercontent.com/8519469/55292584-30507300-53dc-11e9-83fb-5b09b7dc3648.png)

**Comment by phoerious** [comment] 2019-03-31 19:25
Duplicate of ##2815.

**Closed by phoerious** 2019-03-31 19:25 UTC
Labels: bug
