### ISSUE TITLE
"Additional URL's" is not search-able

### ISSUE THREAD

**Issue by Galliver7** [keepassxreboot/keepassxc#5374] opened 2020-09-02 15:57 UTC
## Summary
Additional URL's in Browser Integration is not search-able and it's seem any way to reach the URL. 😪

![screenshot_131](https://user-images.githubusercontent.com/8030470/92006386-a00c1f80-ed7f-11ea-80b3-f279c0339cc8.png)

## Examples
Include the Additional URL's field into the scope of search

## Context
When I want to edit website which is in Additional URL, I can not find it. then I have to guess which ID include the credential so.

PS,
Thank you for this great product 🐳

**Comment by schlimmchen** [comment] 2020-11-01 11:02
This should be closed as duplicate of #5066.

**Closed** 2020-11-01 11:59 UTC
Labels: new feature
