### ISSUE TITLE
Brower-plugin: Specific URL will matches everything in the database

### ISSUE THREAD

**Issue by priv** [keepassxreboot/keepassxc#3902] opened 2019-11-20 06:11 UTC
## Expected Behavior
Browser plugin should only matches correct urls.

## Current Behavior
`https://www.wunanbooks.com.tw/` matches everything in my database and request my access to them all.

## Possible Solution
N/A

## Steps to Reproduce
Normal Case:
1.  Under a working pair of KeePassXC and KeepPassXC-Browser(chrome)
2. Open `https://www.wunanbooks.com.tw/`
3. KeePassXC-Browser Confirm Access dialog will jump up with everything in the database.

Controlled Case:
1. Create a new single entry database in KeePassXC, connect it with KeePassXC-Browser chrome plugin.
2. The only entry could be anything, mine is Title:Test, Username: user, Password:12345, URL: https://github.com/
3. Open https://www.wunanbooks.com.tw/
4. KeePassXC-Browser Confirm Access dialog will jump up. (but it shouldn't since URL not matched.)

## Debug Info
KeePassXC - Version 2.5.1
Revision: 0fd8836
Distribution: AppImage

Qt 5.12.3
Debugging mode is disabled.

Operating system: Ubuntu 19.10
CPU architecture: x86_64
Kernel: linux 5.3.0-23-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.1

**Comment by varjolintu** [comment] 2019-11-20 07:56
Duplicate of https://github.com/keepassxreboot/keepassxc/issues/3848.

**Comment by varjolintu** [comment] 2019-11-20 07:57
The only workaround until we release a new version is to remove all invalid URL's from your database.

**Closed by varjolintu** 2019-11-20 07:56 UTC
Labels: bug
