### ISSUE TITLE
Scroll in the wrong place

### ISSUE THREAD

**Issue by Maciejozaman** [keepassxreboot/keepassxc#5582] opened 2020-10-21 15:05 UTC
## Overview
When adding a new entry, the scrollbar is displayed in the wrong place.

## Steps to Reproduce
1. Click "+" button to create new entry. 

## Expected Behavior
I expected the program to work properly.

## Actual Behavior
Scroll in the wrong place

## Context

[NOTE]:
KeePassXC - 2.6.1
Revision: 9a35bba

[NOTE]:
Operating System: Windows 10 x64 19.09 18363.900
![bug](https://user-images.githubusercontent.com/56502072/96738803-6474f580-13bf-11eb-8ec6-bbeab713a8f2.png)

**Comment by phoerious** [comment] 2020-10-21 15:11
Duplicate of #5300. Please use the search function.

**Closed by phoerious** 2020-10-21 15:11 UTC
Labels: bug
