### ISSUE TITLE
Auto-Type types wrong password on DE keyboard layouts

### ISSUE THREAD

**Issue by ej0815de** [keepassxreboot/keepassxc#10062] opened 2023-11-27 07:07 UTC
## Overview
I use KeepassXC 2.7.6
Global Auto-Type ist CTRL-SHIFT-K to autotype (on Win an Linux)
The german characters are transformed to US-characters, so the password is wrong.
The answer on Issue "Auto-Type types wrong password on different keyboard layouts #6358" is not working correct on this version.

## Steps to Reproduce
1. Create password with germann character 
2. Start RDP on Windows or Linux, start autotype, Username is correct because the character are almost the same
3. Password ist written with wrong characters

## Expected Behavior
insert the german characters like [(),.-, these are on different positions on DE and US keyboard

## Actual Behavior
same as expected

## Context
NONE

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION 2.7.6
Revision: REVISION dd21def

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows/Linux
Desktop Env: Gnome/KDE/XFCE/
Windowing System: X11

**Comment by xA8EYLgMSN43oEHC** [comment] 2023-11-27 09:37
swedish keyboard, using remmina on linux to connect to windows server over rdp
Auto-typing username:

- username: abcdefghijklmnopqrstuvxyz
- outcome: bcdefghijklmopqrstuvxyz

- username: !"#¤%&/()=?{[]}\
- outcome: !"#¤%/=?{[]}\

**Comment by Turecky** [comment] 2023-12-08 12:32
Same thing with LV layout

**Comment by nh3oh** [comment] 2024-04-29 10:12
I've the same issue on Debian 12 after upgrading from Debian 11
```
  $ keepassxc --version
  KeePassXC 2.7.4

  $ apt list --installed keepassxc
  keepassxc/stable,now 2.7.4+dfsg.1-2 amd64  [installed]

```
My session keyboard layout is french AZERTY latin-9  and `[Ctrl+Maj+V]` uses QWERTY layout.

I gave a try with `keepass2` debian package on the same DB that behaves correctly.

I've asked others Debian users, they don't suffer this using the same package.

So I think this coming from a wrong local config, but I haven't idea where to look for.

Maybe some previous posters here are in the same situation ?

Thanks for any int.

**Comment by Turecky** [comment] 2024-05-08 04:17
Problem still persist in latest version. Must manually switch to English keyboard layout before use Autotype. 
```shell
KeePassXC - Version 2.7.8
Revision: f6757d3

Qt 5.15.3
Debugging mode is disabled.

Operating system: Ubuntu 22.04.4 LTS
CPU architecture: x86_64
Kernel: linux 6.5.0-28-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.19.1
```

**Comment by nathan-odin** [comment] 2024-07-04 12:34
This issue still in latest version, Auto Type writes wrong characters when the keyboard is configured in AZERTY.

I am on Xubuntu 24.04 LTS .

Any progress on this issue ?

**Comment by droidmonkey** [comment] 2024-07-04 13:06
Duplicate of either #7881 or #8966

**Closed as completed by droidmonkey** 2024-07-04 13:06 UTC
Labels: duplicate, feature: Auto-Type
