### ISSUE TITLE
Bulk database merging

### ISSUE THREAD

**Issue by mfbehrens** [keepassxreboot/keepassxc#10765] opened 2024-05-15 18:26 UTC
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
It would be nice to be able to select multiple databases in the merge dialog. Then you can provide one password and all the databases get unlocked and sequentially merged.

A bonus feature would be to be able to enter multiple passwords and if the first fails the second gets tried and so on.

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )
My family always creates 20-30 sync conflicts that I have to merge manually into our shared password database. Being able to select all 

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )

**Comment by droidmonkey** [comment] 2024-05-15 21:28
This cannot be implemented because the _sequence_ that you merge in is incredibly important. Recommend that you turn on auto-sync for your family cause it seems like they aren't syncing their files correctly.

**Comment by droidmonkey** [comment] 2024-05-15 21:29
Duplicate of #5024

**Closed as completed by droidmonkey** 2024-05-15 21:29 UTC
