### ISSUE TITLE
UX: Make reference easier to use

### ISSUE THREAD

**Issue by pquerner** [keepassxreboot/keepassxc#2030] opened 2018-06-05 07:06 UTC
## Expected Behavior
Reference always needs (at least for me) a look into the official docs, on how to use them.
It would better if we allow it to use them in a more natural way.

## Current Behavior
Either you know how it must look like, or you need to look it up and then do it manually anyways.

## Possible Solution
Add Button next to field you CAN use as reference (if done right, the UI will change I think)
or
Add item to context menu when you right-click into that field. Currently available: Undo, Redo, ... all that standard stuff. A new item would be named like "Copy field as reference" (or something like that)
or
Add a shortcut for that.

## Context
Creating new entries where fields must be based on by reference (ie. different logins where the loginname is the same (ie. email address)) is difficult to do and time consuming.

## Debug Info
KeePassXC - Version 2.3.3
Revision: 0a155d8

Libraries:
- Qt 5.9.3
- libgcrypt 1.8.2

Operating system: macOS High Sierra (10.13)
CPU architecture: x86_64
Kernel: darwin 17.5.0

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by pquerner** [comment] 2018-06-05 07:16
I just realized you can *copy* the entry and it will ask you if you want to have the new entry to use username and password fields used as references. Duh!
Maybe this ticket is obsolete then if everyone thinks that it works ok now?

**Comment by phoerious** [comment] 2018-06-08 08:05
I'll leave it open for now. This whole references thing is something KeePass designed after the fact and it is inherently difficult to use. We need some sensible user interface for them.

**Comment by droidmonkey** [comment] 2018-10-11 12:40
Duplicate of #433

**Closed by droidmonkey** 2018-10-11 12:40 UTC
Labels: user interface
