### ISSUE TITLE
OSX 10.10.5: code signature invalid for libsodium.23.dylib

### ISSUE THREAD

**Issue by jobevers** [keepassxreboot/keepassxc#1748] opened 2018-03-17 22:12 UTC
I downloaded keepassxc, installed it, and when I tried to run it, it failed to start.

## Steps to Reproduce (for bugs)
Download OSX DMG; Install App, Open App

## Debug Info
```
Process:               KeePassXC [634]
Path:                  /Applications/KeePassXC.app/Contents/MacOS/KeePassXC
Identifier:            KeePassXC
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        bash [630]
Responsible:           Terminal [561]
User ID:               501

Date/Time:             2018-03-17 18:03:52.861 -0400
OS Version:            Mac OS X 10.10.5 (14F2511)
Report Version:        11
Anonymous UUID:        48D37E08-A191-F5A3-72C7-130BD8CB7CB2


Time Awake Since Boot: 320 seconds

Crashed Thread:        0

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000002, 0x0000000000000000

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @executable_path/../Frameworks/libsodium.23.dylib
  Referenced from: /Applications/KeePassXC.app/Contents/MacOS/KeePassXC
  Reason: no suitable image found.  Did find:
	/Applications/KeePassXC.app/Contents/MacOS/../Frameworks/libsodium.23.dylib: code signature invalid for '/Applications/KeePassXC.app/Contents/MacOS/../Frameworks/libsodium.23.dylib'

	/Applications/KeePassXC.app/Contents/MacOS/../Frameworks/libsodium.23.dylib: code signature invalid for '/Applications/KeePassXC.app/Contents/MacOS/../Frameworks/libsodium.23.dylib'
```

**Comment by phoerious** [comment] 2018-03-17 22:51
Duplicate of #1671

**Closed by phoerious** 2018-03-17 22:51 UTC
