### ISSUE TITLE
Password generator templates (pattern/character sets)

### ISSUE THREAD

**Issue by Bonez76** [keepassxreboot/keepassxc#10767] opened 2024-05-16 09:42 UTC
## Summary
Having the option to create user defined templates for the password generator where I can define how a password is generated and create a list of n versions of a password where n is a value I enter in the generator. And then save the template with a name which I can recall when I create a new password entry to auto-generate a password. Identical to the functionality in KeePass (Windows)

## Examples
Not sure if I am allowed to paste screenshots from their site, so I just refer to the website. Hope this is OK.
https://keepass.info/screenshots.html
https://keepass.info/help/base/pwgenerator.html

## Context
I like to define how my password looks like and save various templates for different use cases (e. g. length) and get a list with n variations of a generated password. In my opinion more convenient than having to define everything from scratch each time.

**Comment by droidmonkey** [comment] 2024-05-16 11:31
Duplicate of #2628

**Closed as not planned by droidmonkey** 2024-05-16 11:31 UTC
