### ISSUE TITLE
No Tray icon in Linux Mint 17.3 "Rosa" (Ubuntu 14.04 LTS "Trusty" based)

### ISSUE THREAD

**Issue by Chugajstyr** [keepassxreboot/keepassxc#467] opened 2017-04-04 19:13 UTC
Deb package builded from sources, because package v2.1.3, available from "Releases" page, required QT >= v5.3 for install (Ubuntu "Trusty" has only QT v5.2.1).

## Expected Behavior
If option "Show a system tray icon" is enabled, there should be appear tray icon of KeePassXC.

## Current Behavior
KeePassXC tray icon is invisible.

## Your Environment

* KeePassXC version/commit used: (can be found under Help -> About) v2.1.3
* Qt version (e.g. Qt 5.3): v5.2.1
* Compiler (e.g. Clang++3.6.0): gcc 4.8.4
* Operating System and version: Linux Mint 17.3 "Rosa"

**Comment by Keisial** [comment] 2017-04-04 22:51
Looks like a duplicate of #451 I would check if the fix for appmenu-qt5 was backported to Linux Mint, too.

**Comment by droidmonkey** [comment] 2017-04-08 21:52
Which desktop are you using (Cinnamon, XFCE, KDE, GNOME)?

**Comment by Chugajstyr** [comment] 2017-04-08 23:00
I use Mate desktop.
P.S.  Temporary helps copying KeePassXC icons to `~/.local/share/icons/hicolor/24x24/apps`, but only when passwords database opened or locked. When KeePassXC just started, but database not opened, than tray icon is invisible when application minimized.

**Comment by stucki** [comment] 2017-04-10 09:55
I have the same issue using Ubuntu 16.04 running Unity.

**Comment by phillip-white-sociomantic** [comment] 2017-04-24 12:30
Same issue on Ubuntu Mate 17.04

**Comment by ebisagli** [comment] 2017-05-27 16:47
If i install KeepassXC in Linux Mint 18.1 (Cinnamon or Mate) with the command "sudo snap install keepassxc", the tray icon of keepassxc is not show.
But if i download the "Official AppImage" of keepassxc, and i run it, the tray icon is show.

**Comment by droidmonkey** [comment] 2017-05-30 02:36
No tray icon with the snap is a known issue.

**Comment by droidmonkey** [comment] 2017-06-25 22:37
See if this is still an issue in the 2.2.0 release. I fixed the missing tray icon in the snap release.

**Comment by emkae** [comment] 2017-07-07 07:47
I have this on Arch Linux with Gnome aswell :(

```bash
[marco@l460 ~]$ uname -a
Linux l460 4.11.6-1-ARCH #1 SMP PREEMPT Sat Jun 17 08:19:42 CEST 2017 x86_64 GNU/Linux
[marco@l460 ~]$ gnome-shell --version
GNOME Shell 3.24.2
[marco@l460 ~]$ keepassxc-cli --version
2.2.0
```
Just to make sure, we are on the same boat; we are talking about this little thing here, right?
![screenshot from 2017-07-07 09-45-56](https://user-images.githubusercontent.com/1384938/27948180-19c62ab0-62f9-11e7-87da-440f0ae843ea.png)

I'm coming from KeePassX2 which doesn't appeal to me as KeePassXC does, but it's a real bummer to me, that I cannot minimize it to the tray as I was before (when using KeePassX2).

**Comment by phoerious** [comment] 2017-07-07 07:59
Are you using the Snap package?

**Comment by emkae** [comment] 2017-07-07 08:12
I'm using the latest from yesterday's repo, self compiled. I just used `keepassxc-cli` to show the version number as `keepassxc` seems to have no -v or --version flag

**Comment by phoerious** [comment] 2017-07-07 08:44
Did you try what I asked and unset the XDG_DATA_DIRS environment variable?

**Comment by emkae** [comment] 2017-07-07 08:51
Just unsetting them like so like in the code below?

```bash
unset XDG_DATA_DIRS && keepassxc
```
Doesn't help: https://vimeo.com/224616964/9543521ebc

**Comment by phoerious** [comment] 2017-07-07 08:54
Yes.

Do you have sni-qt installed?

**Comment by emkae** [comment] 2017-07-07 09:06
I had not, but I just installed it and it did not fix it. I tried it with unsetting the `XDG_DATA_DIRS`, too.

**Comment by emkae** [comment] 2017-07-07 09:07
This is the debug info from the about screen:

```
KeePassXC - Version 2.2.0
Revision: 7580c385da58329ef29e0d026b1ac0720cbcccf2

Libraries:
- Qt 5.9.0
- libgcrypt 1.7.7

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 4.11.6-1-ARCH

Enabled extensions:
- Auto-Type
```

**Comment by droidmonkey** [comment] 2017-07-07 10:15
System test icon is a setting that is not enabled by default. Did you enable it?

**Comment by emkae** [comment] 2017-07-07 10:24
@droidmonkey @phoerious you can add me to the hall-of-shame! :cry: 

> System test icon is a setting that is not enabled by default. Did you enable it?

I did not and I'm a stupid retard! Sorry, for causing all this mess/confusion :cry:

**Comment by phoerious** [comment] 2017-07-07 10:33
PEBKAC. 😏

**Comment by droidmonkey** [comment] 2017-07-07 20:06
Lol no problem, no one is retard on here!

**Comment by droidmonkey** [comment] 2017-08-31 20:36
I would like to close this issue unless we can confirm that the problem still exists for OP. ping @Chugajstyr

**Comment by Chugajstyr** [comment] 2017-09-01 11:50
> I would like to close this issue unless we can confirm that the problem still exists for OP.
Well, I updated my Mint to 18 release. It's appeared that Mint v.18.x is not undergo such issue.

**Comment by droidmonkey** [comment] 2017-09-02 00:53
Ok send like a mint issue than

**Closed by droidmonkey** 2017-09-02 00:53 UTC
Labels: in triage, not reproducible

**Comment by hoxnox** [comment] 2018-02-14 06:19
I have the same issue - no tray icon.

I've tried to clear XDG_DATA_DIRS - no effect.

I can't install sni-qt - it requires Qt4, but I'm using Qt5.

```
KeePassXC - Version 2.2.4
Revision: 4723f66

Libraries:
- Qt 5.7.1
- libgcrypt 1.8.1

Operating system: Gentoo/Linux
CPU architecture: x86_64
Kernel: linux 4.9.76-gentoo-r1

Enabled extensions: None
```

**Comment by phoerious** [comment] 2018-02-14 08:08
The package should be sni-qt5

**Comment by hoxnox** [comment] 2018-02-14 08:10
> The package should be sni-qt5

But according to https://github.com/bil-elmoussaoui/sni-qt

**Comment by hoxnox** [comment] 2018-02-14 08:12
> The package should be sni-qt5

But according to https://github.com/bil-elmoussaoui/sni-qt there is no such thing as sni-qt5. Am I wrong?

> This plugin only works when used together with the "qsystemtrayicon-plugin-system-4.7" Qt branch.

**Comment by phoerious** [comment] 2018-02-14 08:32
AFAIK, some distributions used to ship an sni-qt5 package. Of you don't have one, check that you have actually enabled the tray icon in the settings. If you have, it's likely a bug in your window manager.

**Comment by hoxnox** [comment] 2018-02-14 08:37
> some distributions used to ship an sni-qt5 package

How can they do it? Ships qt4? I don't see support for qt-5 for sni-qt at all. Is the repo https://github.com/bil-elmoussaoui/sni-qt official?

> bug in your window manager

There is no problems with other applications... though I have only one Qt-based... Is there method to check that the problem is in window manager?

**Comment by phoerious** [comment] 2018-02-14 13:05
The only check is to use a different desktop.
