### ISSUE TITLE
Additional attributes in ListView mode

### ISSUE THREAD

**Issue by foxfire881** [keepassxreboot/keepassxc#4364] opened 2020-02-23 14:03 UTC
Hi guys, I notice that KeePassXC only shows additional attributes/fields in TAB control by each entry, it's too indiscoverable.  but sometimes I want to check which of my entries have the additional attributes/fileds and their values in my database(such as binding email/mobile/card number...), so I think it's better to show the additional fields in ListView mode. I also notice that the original KeePass could configure columns(included additional fields) in ListView with KPEnhancedEntryView plugin,  I think KeePassXC could also have this feature. thank you.

**Comment by droidmonkey** [comment] 2020-02-23 16:02
duplicate of #1493

**Closed by droidmonkey** 2020-02-23 16:02 UTC
Labels: new feature
