### ISSUE TITLE
Auto-type doesn't insert @-symbol in spotify(linux)

### ISSUE THREAD

**Issue by Brn9hrd7** [keepassxreboot/keepassxc#2661] opened 2019-01-30 16:18 UTC
## Expected Behavior
Insert e-mail address at the spotify login screen correctly

## Current Behavior
Auto type doesn't insert the @-symbol in spotify, for example if the mail-address is myemail@gmail.com it inserts myemailgmail.com.

## Steps to Reproduce
1. start spotify
2. start keepass
3. right click on the spotify entry in keepass and select auto-type

## Debug Info
KeePassXC - Version 2.3.4
Revision: 6fe821c

Bibliotheken:
- Qt 5.12.0
- libgcrypt 1.8.4

Betriebssystem: Manjaro Linux
CPU-Architektur: x86_64
Kernel: linux 4.20.3-1-MANJARO

Aktivierte Erweiterungen:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by droidmonkey** [comment] 2019-01-31 00:44
Duplicate of #324

**Closed by droidmonkey** 2019-01-31 00:44 UTC
Labels: bug
