### ISSUE TITLE
Crash after merging of two databases

### ISSUE THREAD

**Issue by MaSven** [keepassxreboot/keepassxc#10203] opened 2024-01-15 22:07 UTC
## Overview
I have one database, that I save into my Nextcloud. There was a conflict detected by Nextcloud and for that reason, I have a conflict file. This is just a copy of the same database with a few changes.  I wanted to merge these two together but i keepassxc crashes while doing the merge.

## Steps to Reproduce
1. Create a Database
2. Save it into nextcloud
3. sync with nextcloud to a different client
4. edit the database on different client while being offline
5. edit the database on first client
6. go online on second client
7. try to merge the conflited file

## Expected Behavior
Normally it would happyli merge the databases and after that, i delete the conflict file.

## Actual Behavior
Keepassxc crashes and closes the main UI. 

## Context

The last lines I see
```
QObject::connect(Group, Unknown): invalid nullptr parameter
QObject::connect(FdoSecrets::Item, FdoSecrets::Collection): invalid nullptr parameter
QObject::connect(FdoSecrets::Item, FdoSecrets::Collection): invalid nullptr parameter
```

KeePassXC - Version 2.7.6
Revision: dd21def
Distribution: Flatpak

Qt 5.15.10
Diagnosemodus ist deaktiviert.

Betriebssystem: KDE Flatpak runtime
CPU-Architektur: x86_64
Kernel: linux 6.5.0-10013-tuxedo

Aktivierte Erweiterungen:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare
- YubiKey
- Secret-Service-Integration

Kryptographische Bibliotheken:
- Botan 3.2.0

Operating System: Linux
Desktop Env: KDE
Windowing System: X11

**Comment by droidmonkey** [comment] 2024-01-15 22:59
Duplicate of #9371

**Closed as not planned** 2024-01-15 23:00 UTC
