### ISSUE TITLE
Unable to write to the database with an access denied message.

### ISSUE THREAD

**Issue by advisorgee** [keepassxreboot/keepassxc#1422] opened 2018-01-24 22:02 UTC
When a save (or auto-save) is attempted; there will be a banner message saying "writing to the database failed. Access is denied"

This is happening on my work PC, using GoogleDrive. I share the database with my Macbook at home (which is currently off)

## Expected Behavior
Database should be able to be saved. 

## Current Behavior
The database cannot be saved to the current file. It must be saved to a new file name, and then merged back with the previous version.

## Steps to Reproduce (for bugs)

There aren't any specific steps to reproduce this.  It just occurs. The second time it happened today, i had merged two databases together. I went to merge into with another older one, and then the message appeared again. 

## Debug Info

KeePassXC - Version 2.2.4
Revision: 4723f66

Libraries:
- Qt 5.9.2
- libgcrypt 1.8.1

Operating system: Windows 8.1 (6.3)
CPU architecture: x86_64
Kernel: winnt 6.3.9600

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

**Comment by TheChiefMeat** [comment] 2018-01-25 18:22
I've had the same issue; Just stopped Google Drive Sync, wait a few seconds and then save the database, then restart Google Drive Sync.

**Comment by advisorgee** [comment] 2018-01-25 18:25
Thanks, that is way easier than saving/merging.

**Comment by droidmonkey** [comment] 2018-01-25 19:06
Duplicate of #197

**Closed by droidmonkey** 2018-01-25 19:06 UTC
Labels: duplicate
