### ISSUE TITLE
Bulk Download of favicons

### ISSUE THREAD

**Issue by aserrallerios** [keepassxreboot/keepassxc#3100] opened 2019-04-30 14:06 UTC
I think it'd be handy to have an option menu for `Download Favicon` that also works when you select multiple entries.

**Comment by droidmonkey** [comment] 2019-04-30 15:08
Duplicate of #735

**Closed by droidmonkey** 2019-04-30 15:08 UTC
Labels: new feature

**Comment by aserrallerios** [comment] 2019-04-30 15:30
I swear I'd looked for it! :P sorry!
