### ISSUE TITLE
Segfault when searching

### ISSUE THREAD

**Issue by damianrath** [keepassxreboot/keepassxc#2208] opened 2018-08-17 11:34 UTC
## Steps to Reproduce (for bugs)
1. Start application.
2. Search for whatever.
3. After 2-3 chars in the search field it segfaults.

kernel: [34894.052632] keepassxc[22074]: segfault at 565400000011 ip 00007f5221a15ae8 sp 00007ffe191d93d0 error 4 in libQt5Core.so.5.5.1[7f52217c5000+4c5000]

## Debug Info
KeePassXC - Version 2.3.3
Revision: 0a155d8

Libraries:
- Qt 5.5.1
- libgcrypt 1.8.1

Operating system: Linux Mint 18.3
CPU architecture: x86_64
Kernel: linux 4.15.0-32-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by phoerious** [comment] 2018-08-18 06:53
Duplicate of #1254

**Closed by phoerious** 2018-08-18 06:53 UTC
