### ISSUE TITLE
Unlock database with hardware key SECRET

### ISSUE THREAD

**Issue by Coernel82** [keepassxreboot/keepassxc#4194] opened 2020-01-17 08:41 UTC
<h1>Scenario: hardware key lost or broken</h1>
Losing your hardware key makes it impossible to unlock your database. Yes, you can get a new harware key and program it with your old secret but <strong>ordering it will take some days</strong> you don't necessarily have.
<h2>Solution: Password + Secret</h2>
For this worst case scenario the database should be unlockable by entering the secret of the hardware key which you have printed out (and probably stored in your physical safe).
<h1>Current workaround</h1>
Keepass2Android supports this - though I never tested it.

**Comment by droidmonkey** [comment] 2020-01-17 11:05
Duplicate of #1734

**Closed by droidmonkey** 2020-01-17 11:05 UTC
Labels: new feature
