### ISSUE TITLE
[Browser integration] Provide different URLs matches for a single entry

### ISSUE THREAD

**Issue by pedrom34** [keepassxreboot/keepassxc#3501] opened 2019-09-03 07:04 UTC
Would it be possible to add an option to use different URLs for a single entry (alternative URLs)?

I'm coming from KeePass 2.x with Kee for the browser integration. I'd like to use KeePassXC, but I miss this feature 😢 

Here's a screenshot of Kee with the feature I miss:
![Screenshot of minimum URL Match Accuracy dialog](https://github.com/luckyrat/KeeFox/wiki/images/minimumURLMatchAccuracy.png)
https://github.com/kee-org/KeeFox/wiki/en-%7C-Using-KeeFox-%7C-Alternative-URLs

**Comment by varjolintu** [comment] 2019-09-03 11:49
Duplicate of https://github.com/keepassxreboot/keepassxc/issues/398.

**Closed by varjolintu** 2019-09-03 11:49 UTC
Labels: duplicate, new feature
