### ISSUE TITLE
Feature request: "Semi-open" database state for usage only with browser extension

### ISSUE THREAD

**Issue by aeisi** [keepassxreboot/keepassxc#2223] opened 2018-08-22 13:38 UTC
This is an alternative to #2222:

When mainly working with the browser extension, it would be helpful to have a "semi-open" password database state. In this state only the browser extension can access the passwords for which it has been granted access.
The password database itself in the keepassxc application is locked and no content can be read until properly unlocked.

## Expected Behavior
The browser extension can read credentials for which it has been granted access.
The database in keepassxc application is locked and no content can be read by other applications/users until it is unlocked using the master password.

## Current Behavior
The database in keepassxc application is locked and needs to be unlocked when the browser extension wants to read credentials.

## Possible Solution
Please see above.

**Comment by droidmonkey** [comment] 2018-08-23 00:13
Duplicate of #1809

**Closed by droidmonkey** 2018-08-23 00:13 UTC
