### ISSUE TITLE
Nth letter of password

### ISSUE THREAD

**Issue by UtXtiQArZE** [keepassxreboot/keepassxc#1801] opened 2018-03-31 12:32 UTC
A lot of banks / places where you log in, have it so rather than typing in the whole password in you type in say the 2nd 5th 7th and 9th letters of the password. I was wondering if it was possible to add in a viewing window such that determining which letter of the password was in which position.

**Comment by droidmonkey** [comment] 2018-03-31 12:40
Duplicate of #72

**Closed by droidmonkey** 2018-03-31 12:40 UTC
