### ISSUE TITLE
Have I Been Pwned integration doesn't work on the 2.6.4 Linux AppImage

### ISSUE THREAD

**Issue by Davester47** [keepassxreboot/keepassxc#6584] opened 2021-06-01 23:40 UTC
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Have I Been Pwned doesn't work. It gives the following error message in the table that bad passwords normally show up in.
`Online password validation failed: protocol 'https' is unknown`

I do not believe this is a duplicate of #6544, because this gives a different error in the terminal than when I try to download a favicon. Downloading a favicon gives multiple `Maximum depth of replacement has been reached. Entry uuid: {0a38400a-0b83-4abb-8027-a439e0c80e73}` in the terminal. I also don't see any of the errors from #4219 in the terminal. 

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Start the AppImage version of KeepassXC
2. Load a password database
3. Click Database -> Database Reports -> HIBP -> Perform Online Analysis

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
I expect it to connect to Have I Been Pwned and tell me which of my passwords are bad.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
In the table that should say which passwords are bad and how many times they have been used, it shows an error message in red in the top left cell. It says `Online password validation failed: protocol 'https' is unknown`.
Here's a screenshot:
![image](https://user-images.githubusercontent.com/59511328/120402845-e9ca6c00-c2f7-11eb-9773-d724bcd2f535.png)

Here is what the terminal looks like when I try to use HIBP:
```
QObject::startTimer: Timers cannot have negative intervals
QNetworkReplyImplPrivate::error: Internal problem, this method must only be called once.
QNetworkReplyImplPrivate::error: Internal problem, this method must only be called once.
QNetworkReplyImplPrivate::error: Internal problem, this method must only be called once.
QNetworkReplyImplPrivate::error: Internal problem, this method must only be called once.
QNetworkReplyImplPrivate::error: Internal problem, this method must only be called once.
QNetworkReplyImplPrivate::error: Internal problem, this method must only be called once.
QNetworkReplyImplPrivate::error: Internal problem, this method must only be called once.
QNetworkReplyImplPrivate::error: Internal problem, this method must only be called once.
QNetworkReplyImplPrivate::error: Internal problem, this method must only be called once.
QNetworkReplyImplPrivate::error: Internal problem, this method must only be called once.
QNetworkReplyImplPrivate::error: Internal problem, this method must only be called once.
QNetworkReplyImplPrivate::error: Internal problem, this method must only be called once.
QNetworkReplyImplPrivate::error: Internal problem, this method must only be called once.
QNetworkReplyImplPrivate::error: Internal problem, this method must only be called once.
QNetworkReplyImplPrivate::error: Internal problem, this method must only be called once.
QNetworkReplyImplPrivate::error: Internal problem, this method must only be called once.
QNetworkReplyImplPrivate::error: Internal problem, this method must only be called once.
QNetworkReplyImplPrivate::error: Internal problem, this method must only be called once.
QNetworkReplyImplPrivate::error: Internal problem, this method must only be called once.
QNetworkReplyImplPrivate::error: Internal problem, this method must only be called once.
QNetworkReplyImplPrivate::error: Internal problem, this method must only be called once.
QNetworkReplyImplPrivate::error: Internal problem, this method must only be called once.
QNetworkReplyImplPrivate::error: Internal problem, this method must only be called once.
QNetworkReplyImplPrivate::error: Internal problem, this method must only be called once.
QNetworkReplyImplPrivate::error: Internal problem, this method must only be called once.
QNetworkReplyImplPrivate::error: Internal problem, this method must only be called once.
QNetworkReplyImplPrivate::error: Internal problem, this method must only be called once.
QNetworkReplyImplPrivate::error: Internal problem, this method must only be called once.
QNetworkReplyImplPrivate::error: Internal problem, this method must only be called once.
QNetworkReplyImplPrivate::error: Internal problem, this method must only be called once.
QNetworkReplyImplPrivate::error: Internal problem, this method must only be called once.
QNetworkReplyImplPrivate::error: Internal problem, this method must only be called once.
QNetworkReplyImplPrivate::error: Internal problem, this method must only be called once.
QNetworkReplyImplPrivate::error: Internal problem, this method must only be called once.
QNetworkReplyImplPrivate::error: Internal problem, this method must only be called once.
QNetworkReplyImplPrivate::error: Internal problem, this method must only be called once.
QNetworkReplyImplPrivate::error: Internal problem, this method must only be called once.
QNetworkReplyImplPrivate::error: Internal problem, this method must only be called once.
```
All those errors were after trying it once. I didn't keep trying that many times. The version in Debian's package system works fine, as does the github develop branch when I tried a couple days ago.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.4
Revision: 34a78f0
Distribution: AppImage

Qt 5.15.2
Debugging mode is disabled.

Operating system: Debian GNU/Linux 11 (bullseye)
CPU architecture: x86_64
Kernel: linux 5.10.0-6-amd64

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- libgcrypt 1.8.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: I've confirmed the problem on KDE and [Sway](https://swaywm.org/).
Windowing System: Both X11 and Wayland

Thanks for taking the time to look through this.

**Comment by droidmonkey** [comment] 2021-06-02 00:29
This is a known issue with ssl certs in appimage and is a duplicate of other issues here. You will have to use the snap package or ppa to use hibp feature at this time.

**Closed by droidmonkey** 2021-06-02 00:29 UTC
Labels: bug
