### ISSUE TITLE
Keepassxc window not (re)drawn correctly on Linux/i3

### ISSUE THREAD

**Issue by wknapik** [keepassxreboot/keepassxc#2242] opened 2018-08-27 16:53 UTC
When I start keepassxc it works fine, but after some time, when the database gets locked, after a period of inactivity, invoking keepassxc results in a window with no contents drawn. The titlebar still says "KeePassXC" and the window does accept keyboard input, so I can supply the password and unlock, but the window remains completely black. The only way to restore normal operation is to kill keepassxc and start it again.

Sometimes, the breakage is only partial and the menu bar on top doesn't work correctly (the menus don't "pop down") and right-click on items doesn't work, but usually it's just a completely blank window. 

## Expected Behavior

The window should be rendered correctly no matter what state keepassxc is in.

## Current Behavior

The window is not rendered correctly.

## Possible Solution

No idea.

## Steps to Reproduce (for bugs)

1. Start keepassxc.
2. Wait until the db gets locked (or maybe not, I don't know, but for me that's the only reason to call keepassxc, because I mostly rely on the browser plugin, but some time has to pass).
3. The window is rendered completely black when keepassxc is called.

## Context

While browser integration (and, presumably, the cli) still works, the gui becomes unusable.

## Debug Info

KeePassXC - Version 2.3.4
Revision: 6fe821c

Libraries:
- Qt 5.11.1
- libgcrypt 1.8.3

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 4.18.5-arch1-1-ARCH

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by wknapik** [comment] 2018-08-28 09:38
I don't know, I'm not seeing such issues with any other applications.
I'm waiting for it to happen again to maybe get some useful logs, but so far the gui is working fine.

**Comment by wknapik** [comment] 2018-08-29 12:04
So it happened again, but there was nothing in the logs.
I think I'm seeing a correlation here with switching between 2 monitors and 1. I'll keep an eye on that, since I switch daily.

@droidmonkey is there a way to increase the logging level ? Or anything that would allow me to give you more actionable info ? I couldn't find anything in the command-line help, or the man pages...

**Comment by droidmonkey** [comment] 2018-08-29 12:33
We do not log much of anything, mainly due to that's how we inherited the program. The best I can offer is to run it in a debugger. I still contend this is a negative interaction between i3 and Qt. Can you run any other Qt application and try to replicate the issue?

**Comment by wknapik** [comment] 2018-08-29 12:44
I don't use any other qt applications. Maybe I'll install one and keep it running to see what happens.

**Comment by L0rdBootysniffer** [comment] 2018-09-07 12:32
I use i3 on the exact same kernel and distribution as you and do not have this problem. Do you use a compositing manager of some sort?

**Comment by kneitinger** [comment] 2018-10-09 03:49
> Sometimes, the breakage is only partial and the menu bar on top doesn't work correctly (the menus don't "pop down") and right-click on items doesn't work

While I haven't experienced the blank window issue, I do also occasionally experience the missing menu issue.  Not using a compositor currently, and only experience this behavior with KeePassXC (but by no means ruling out that the actual root cause is in i3)

**Comment by phoerious** [comment] 2018-12-30 10:35
This is almost certainly a toolkit issue either in Qt5 or i3, your compositor or anything in between those.

**Comment by droidmonkey** [comment] 2018-12-30 13:10
@j6s please post replication steps here for all to see, thank you.

**Comment by j6s** [comment] 2018-12-30 16:58
I am currently trying to narrow down steps to reproduce the issue.
What I found out so far:

- I do not have the issue on a fresh ubuntu system (18.10)
- I only have the issue on my debian testing machine when keepassxc is configured to minimize to the system tray icon

---

I thought I could reproduce the issue on a ubuntu VM - currently setting up a fresh debian testing VM to test some theories.

---

Additional information about the debian testing environmen where keepassxc has issues:

- I use both, i3bar and xfce4-panel - both of which have the capabilities to display system tray icons. i3bar is configured not to though.

While I don't think that this is the source of the issue I just wanted to throw this piece of information out there in case it is relevant.

**Comment by j6s** [comment] 2018-12-30 17:18
Okay - I think I have nailed down the issue: It seems to be an issue with qt5 & the breeze theme:

- I can reproduce the issue when using XFCE - so it is not i3 specific
- I use `qt5ct` to control the styling of qt applications
- When setting "style" in qt5ct to "Breeze" the issue exists
- When setting "style" in qt5ct to "gtk2" then it does not
- Funny side note: I use the breeze gtk theme, so the actual application appearance does not change a lot.

---

**Environment**
- Install keepassxc & qt5ct
- Configure keepassxc to minimize to system tray
- Setup qt5ct correctly (see: https://wiki.archlinux.org/index.php/Qt#Configuration_of_Qt5_apps_under_environments_other_than_KDE_Plasma )

**Steps to reproduce**
- Ensure keepassxc is not running in system tray
- Select breeze theme in qt5ct
- Open keepassxc. Now the main window is displayed correctly
- Close keepassxc. Now no window is opened, but the application is running behind the system tray icon
- Open keepassxc again either by clicking on the system tray icon or by launching the application again regularly

**Expected behaviour**
- The main window of the already running keepassxc instance should be shown exactly the same as before

**Actual behaviour**
- An empty keepassxc window is visible

---

![screenshot_2018-12-30_18-16-45](https://user-images.githubusercontent.com/3374170/50549559-49237e00-0c5f-11e9-9496-a98b52fc5ce2.png)
![screenshot_2018-12-30_18-16-13](https://user-images.githubusercontent.com/3374170/50549560-49237e00-0c5f-11e9-879d-e71cddf0c65e.png)

**Comment by j6s** [comment] 2018-12-30 18:04
I cannot reproduce the issue on any AppImage (Tested the latest snapshot and the current stable 2.3.4) as they seem to completely ignore any style settings made by qt5ct.

Let me try to compile the current master myself and see if I can reproduce it there.

**Comment by j6s** [comment] 2018-12-30 19:48
Okay - I just built the current `develop` and `master` branches for testing purposes.

- Both were built with `-DWITH_XC_ALL=ON` and `-j 8`

---

- On `develop` everything works fine
- On `master` the issue still exists

It seems like the issue has been fixed already in develop and I would assume that the next release will fix it. I guess this ticket can be closed.

---

Looking at the output of launching these instances back-to-back I would assume that the following line in the log actually is related to the issue:

`qt.qpa.xcb: QXcbConnection: XCB error: 5 (BadAtom), sequence: 752, resource id: 0, major code: 19 (DeleteProperty), minor code: 0`

Full log of launching and reproducing the bugs for `develop`, `master` and 2.3.4 installed globally:
```
j@jo-tp ~/tmp/keepassxc $ ./build-develop/src/keepassxc
qt5ct: using qt5ct plugin
Couldn't load translations.
Invalid Context= "Apps" line for icon theme:  "/usr/share/icons/Arc-Icons/apps/symbolic/"
Invalid Context= "Mimetypes" line for icon theme:  "/usr/share/icons/Arc-Icons/mimetypes/symbolic/"
Icon theme "Moka" not found.
qt5ct: D-Bus global menu: no
qt5ct: D-Bus system tray: no
QObject::startTimer: Timers cannot have negative intervals
^C
j@jo-tp ~/tmp/keepassxc $ ./build-master/src/keepassxc
qt5ct: using qt5ct plugin
Couldn't load translations.
Invalid Context= "Apps" line for icon theme:  "/usr/share/icons/Arc-Icons/apps/symbolic/"
Invalid Context= "Mimetypes" line for icon theme:  "/usr/share/icons/Arc-Icons/mimetypes/symbolic/"
Icon theme "Moka" not found.
qt5ct: D-Bus global menu: no
qt5ct: D-Bus system tray: no
QObject::startTimer: Timers cannot have negative intervals
qt.qpa.xcb: QXcbConnection: XCB error: 5 (BadAtom), sequence: 714, resource id: 0, major code: 19 (DeleteProperty), minor code: 0
^C
j@jo-tp ~/tmp/keepassxc $ keepassxc
qt5ct: using qt5ct plugin
Invalid Context= "Apps" line for icon theme:  "/usr/share/icons/Arc-Icons/apps/symbolic/"
Invalid Context= "Mimetypes" line for icon theme:  "/usr/share/icons/Arc-Icons/mimetypes/symbolic/"
Icon theme "Moka" not found.
qt5ct: D-Bus global menu: no
qt5ct: D-Bus system tray: no
QObject::startTimer: Timers cannot have negative intervals
qt.qpa.xcb: QXcbConnection: XCB error: 5 (BadAtom), sequence: 752, resource id: 0, major code: 19 (DeleteProperty), minor code: 0
```

**Comment by droidmonkey** [comment] 2018-12-30 20:11
Awesome that's great to hear, closing!

**Closed by droidmonkey** 2018-12-30 20:11 UTC
Labels: more info needed

**Comment by phoerious** [comment] 2018-12-31 14:34
I still think that the bug is not really in KeePassXC, but we may have triggered it with something.

**Comment by languitar** [comment] 2019-02-08 09:52
Has something with a "fix" been released? I am seeing the same issue on i3 right now with 2.3.4

**Comment by droidmonkey** [comment] 2019-02-08 15:30
I recommend reading the issue thread........

**Comment by exapsy** [comment] 2021-12-08 16:30
> Has something with a "fix" been released? I am seeing the same issue on i3 right now with 2.3.4

Depending on if you're running GNOME or KDE, edit `/usr/share/applications/org.keepassxc.KeePassXC.desktop` (or wherever your keepassxc `.desktop` file is lying) and add `XDG_CURRENT_DESKTOP=GNOME` or `KDE` to your `TryExec` and `Exec`

```
Exec=XDG_CURRENT_DESKTOP=GNOME keepassxc %f
TryExec=XDG_CURRENT_DESKTOP=GNOME keepassxc
```
