### ISSUE TITLE
YubiKey doesn't register with KeePassXC.

### ISSUE THREAD

**Issue by rtevans01** [keepassxreboot/keepassxc#3054] opened 2019-04-22 03:59 UTC
## Expected Behavior

Static password should bet inputted into the password field when I touch the YubiKey button.

## Current Behavior

The static password doesn't get inputted into the password field when trying to unlock my database. I have to physically remove the YubiKey and reinsert it into my USB drive in order for it to work once. I have to repeat if I want it to work a second time.

## Possible Solution

I have none. Sorry.

## Steps to Reproduce

I'm using a YubiKey Neo and running Linux Mint 19.1 on a Dell XPS-15 L521X. SSH and browser integration are enabled.

EDIT: Only occurs in KeePassXC. Work as intended in KeePass2.

**Comment by droidmonkey** [comment] 2019-04-22 11:32
Do you have any slots configured for challenge response? I'd like to setup my key just like yours to debug this issue

**Comment by rtevans01** [comment] 2019-04-22 14:33
No both slots are configured for different static passwords.

**Comment by rtevans01** [comment] 2019-04-22 15:07
BTW, if it helps narrow the problem down this only happens in KeePassXC. KeePass2 works as intended.

**Comment by w-A-L-L-e** [comment] 2019-04-22 17:47
AnyKey works perfectly with KeePassXC. We've tested it today in Mac OS X Mojave and windows 10.
https://www.kickstarter.com/projects/715415099/anykey-the-usb-password-key/posts/2486815
Thanks for this great project that is a perfect companion for our AnyKey hardware!

**Comment by m451** [comment] 2019-04-25 21:34
Wait: you want to use the static password (aka a "string") yubikey produces as your master password?

**Comment by w-A-L-L-e** [comment] 2019-04-26 07:49
Nothing wrong with using a password I can remember and type easily and extend that with a long string typed by a hardware dongle like AnyKey or in this ticket a UbiKey. Additionally we want to also support a seperate Asymmetrical Encryption like the ssh handshake, but then used only for unlocking the keepassxc db file (basically like the already implemented fingerprint option right now, but fingerprints have other issues: https://hackaday.com/2015/11/10/your-unhashable-fingerprints-secure-nothing/). 

Yes this ticket is for someone using a yubikey to enter part of the master password with a hardware device and apparently has an issue with it not functioning properly. The AnyKey works fine here. And also by design, you don't leave that dangling on your pc: you insert it only during unlocking and immediately remove it after your password entry (or ssh-like handshake) is completed and put it back in your pocket. I get your concern with just leaving the key hanging on your pc unattended the whole time. It's on par with putting a post-it with part of the password on your monitor or never locking your pc or leaving your housekey on your door. 

Having a hardware hid making your master password more complex is a good thing. Not perfect, but it's way better than the alternatives: where someone takes a totally short password or even not putting a login password on their desktop because it's a hastle to type it multiple times per day. And that's the majority of people : https://it.slashdot.org/story/19/04/21/1742219/more-than-23-million-people-use-the-password-123456. Taking a short master password is prone to dictionary attacks and once your kdbx file is unlocked you've been owned. But by design you'll have to re-enter this master password many times (every time your pc is left or put to sleep actually) so yes it's a good idea to make that more user friendly but still have the kdbx file itself hard to unlock/hack by having a really long and complex master password that is a combination of 'your short password + a complex string added by a hardware device'.

**Comment by phoerious** [comment] 2019-04-27 09:34
I just want to add that using the key in CR mode is basically equivalent to letting the key complete your password, but with the added benefit that the actual value changes every time you save the database, giving you some sort of forward secrecy for your database.

**Comment by m451** [comment] 2019-04-27 10:27
...and a potential sync conflict.
I mean: everyone can decide on their own what they want to protect against.
I was just wondering why anyone would use static passwords that don't protect against many attacks (including very simple attacks such as keyloggers) when they have a Yubikey that's capable of PIV / PKCS11 or at least CR with HMAC-SHA1.

**Comment by w-A-L-L-e** [comment] 2019-04-27 10:55
Yes indeed it's always a matter of convenience vs protection. Having an added salt to your password gives you better protection and makes it easier in daily use (current AnyKey): you can then backup the db somewhere and only decrypt it with a long secure password. The keylogger attack will only work if you decide to unlock your db on a compromised system and this is also true for all current people not using an AnyKey. Basically without AnyKey you got the worst of everything : a shorter pass prone to dictionary&brute force attacks and one that can be keylogged. 

The HMAC-SHA1 method indeed changes the code every time but because the stored secret is not shared between keepassxc you have a seperate file that stores the state that you also need to backup on every save (meaning it becomes much harder to backup your password db somewhere if you want to be able to unlock it at a later date or on a different pc).  Having said that. It wouldn't be much extra work for us at all to support HMAC-SHA1 as an alternate firmware.

Same goes for PKCS11 the software you use it for will have to have support for it also (even keepassxc doesn't have it yet, correct me if I'm wrong https://github.com/keepassxreboot/keepassxc/issues/255)

**Comment by droidmonkey** [comment] 2019-04-27 11:04
@w-A-L-L-e I'm going to request that you stop plugging AnyKey in every response you make. This doesn't help the situation and clutters our issue board with irrelevant comments.

**Comment by w-A-L-L-e** [comment] 2019-04-27 11:13
Ow yes I see ,sorry for that, it was by force of habit. As far as pkcs11 support goes my guess is the botan library only provides part of the high level implementation. You need an added specific middleware that does the actual communication per device type you want to support right?

**Comment by m451** [comment] 2019-04-27 11:19
> Yes indeed it's always a matter of convenience vs protection. Having an added salt to your password gives you better protection and makes it easier in daily use (current AnyKey): you can then backup the db somewhere and only decrypt it with a long secure password. The keylogger attack will only work if you decide to unlock your db on a compromised system and this is also true for all current people not using an AnyKey. Basically without AnyKey you got the worst of everything : a shorter pass prone to dictionary&brute force attacks and one that can be keylogged.
> 
> The HMAC-SHA1 method indeed changes the code every time but because the stored secret is not shared between keepassxc you have a seperate file that stores the state that you also need to backup on every save (meaning it becomes much harder to backup your password db somewhere if you want to be able to unlock it at a later date or on a different pc). Having said that. It wouldn't be much extra work for us at all to support HMAC-SHA1 as an alternate firmware.
> 
> Same goes for PKCS11 the software you use it for will have to have support for it also (even keepassxc doesn't have it yet, correct me if I'm wrong #255)

There are plugins for KeePass that provide PKCS11 support. The only downside now is that the (second) key is only encrypted using 3DES, which is kinda outdated but should still be good for anything < NSA / KGB level.

**Comment by w-A-L-L-e** [comment] 2019-04-27 11:20
Thanks for the tip m451 we'll look into it.

**Comment by phoerious** [comment] 2019-04-27 11:27
CR does not require an extra file. Only the KeePass implementation does, which we do not support for exactly that reason.

CR also does not create sync conflicts. The challenge changing every time has no effect on whether you can open the database later with an identically-programmed YubiKey or not. The response is only bound to the master seed (which changes every time anyways) and the secret programmed into the YubiKey.

**Comment by droidmonkey** [comment] 2019-04-27 11:47
@w-A-L-L-e if you want to discuss integrating AnyKey with KeePassXC, please open a new issue. You can see an example of what we did with OnlyKey here: #2754

**Comment by w-A-L-L-e** [comment] 2019-04-27 14:01
@droidmonkey thanks for the info!

**Comment by psychotrome** [comment] 2019-04-29 23:54
Yeah, I'm a bit anxious to figure this issue out myself.

When I bring up the window to unlock KeepasXC, which is running in systray after coming back from sleep. My Yubikey lights up, there's something like a progress bar under "challenge response" which is grayed out because I'm not using it. Then the Yubikey is completely dead until re-plugged.

The most annoying thing is that there's absolute no feedback about what just happened. Nothing in the logs and nothing in Keepass's console output. Nothing in dmesg. Nothing about why the key's dead.

I'm running v. 2.4.0 on updated Manjaro Archlinux from it's standard repositories. Kernel 4.20.17

**Comment by rtevans01** [comment] 2019-05-01 16:04
I consider myself a layman at netsec but it seems to me like a Yubikey NFC ring would be very useful for the HMAC-SHA1 challenge response option. That way it would be easier to unlock the same KeePass database on multiple devices.

**Comment by psychotrome** [comment] 2019-05-26 20:09
It took a while but it's happened again. This time even after rebooting (without the key plugged in) it kept killing the key whenever I'd open Keepass's window.

**Comment by psychotrome** [comment] 2019-05-26 20:14
It took a while but it's happened again. This time even after rebooting (without the key plugged in) it kept killing the key whenever I'd open Keepass's window.

Restarting again with key plugged in and Keepass works fine.

**Comment by psychotrome** [comment] 2019-05-27 03:25
So, the problem definitely manifests itself when the key is unplugged and plugged back in at all during a session before attempting to unlock database regardless if Keepass is running in background or not.

I should have noticed it earlier but as before, I've been lazy and keeping the key plugged in from startup through sleep-wake.

What I'd like to know now is how to disable Yubi two factor completely because it apparently keeps enabling itself even though I don't have it enabled for my database or at all in settings.

**Comment by psychotrome** [comment] 2019-05-27 04:12
After searching around for how to debug / disable the key. Noticed my issue is a duplicate of issue 1215.

**Comment by onlykey** [comment] 2019-06-28 15:18
@droidmonkey @psychotrome I haven't tested this with OnlyKey but in troubleshooting other issues in regards to typing in apps here is what I would do. Yubikey is basically just a USB keyboard to the computer, when the problem manifests itself ( I press yubikey and nothing is typed ) first verify the touch was sensed by Yubikey ( The light turns off) if so plug in a USB keyboard and verify does it also type nothing? If so we know its not a problem with the device its something else like maybe another app is in the foreground and so the text is typed there. I.e. An RDP session or VM.

**Comment by rtevans01** [comment] 2019-07-02 23:47
UPDATE: I bought an OnlyKey and it works! I don't have to remove and plug it in all the time to unlock my database. Impressive device too.

**Closed** 2019-10-15 02:01 UTC
Labels: bug, plugin: YubiKey

**Comment by w-A-L-L-e** [comment] 2020-02-04 14:44
Status update we took a different route to integrate with keepassxc we allowed our anykey to type using a configurable shortcut and the configurator software running in taskbar picks this up for us (works in windows, linux, mac). We've got no issues here and it works like a charm to open up the keepass db with given password by our hardware. Basically we open the keepass db and when we need to type the pass we either insert our key or type apple-t if its already inserted earlier. 
<img width="499" alt="Screenshot 2020-02-04 at 15 39 19" src="https://user-images.githubusercontent.com/710803/73754716-1a7ead80-4765-11ea-8207-4b2f52b71a86.png">

**Comment by bytew0lf** [comment] 2020-10-06 08:22
On Windows 10 1909 x64 the YubiKey 4 (FW: 4.2.6) and YubiKey 5 NFC (FW:5.1.2) are not detected by KeepassXC 2.6.0 and 2.6.1 x64 but the work with 2.5.4 x64.
I also noticed that the Browser integration in Edge (chromium version) seems to be broken in 2.6.1 x64.
