### ISSUE TITLE
Keepass main window disappears [v2.5.4 - Windows 10]

### ISSUE THREAD

**Issue by kekukui** [keepassxreboot/keepassxc#4650] opened 2020-04-23 12:38 UTC
**The Keepass window randomly disappears but the application is still visible in Task Manager, and must be forcibly closed through Task Manager in order to relaunch it.  I cannot reproduce this issue on demand, but it happens often and may be associated with high system resource usage or low memory conditions.**

**Comment by droidmonkey** [comment] 2020-04-23 12:55
Give us more details about your computer. How are you out of resources for our tiny app?

**Comment by droidmonkey** [comment] 2020-04-23 12:55
This is a duplicate issue and will be closed unless you have new information

**Comment by kekukui** [comment] 2020-04-23 13:46
I dont know how to debug the random disappearance of a window, but it does not happen with any other app, so it may be related to the application framework.  If you can programmatically detect when the window has disappeared, maybe you can build a version of keepass that logs anything which might be important & relevant.

**Comment by kekukui** [comment] 2020-04-23 14:16
I am monitoring a list of active windows using this tool: https://www.nirsoft.net/utils/winlister.html
One thing I noticed here is that the window property `popup` = **yes** for keepass, but all other user mode applications have the property of "**no**".

**Comment by Xant1k** [comment] 2020-04-25 02:47
+1 same problems, 2.5.3/2.5.4, may be 2.5.2 i don't remember).
always latest stable windows 10 pro.

**Comment by droidmonkey** [comment] 2020-04-25 03:19
If you disable the browser integration does the problem go away?

**Comment by kekukui** [comment] 2020-04-25 10:24
Browser integration is not enabled when the problem occurs

**Comment by kekukui** [comment] 2020-04-28 01:30
**Possibly related - error when attempting to close the main window / exit application**

![image](https://user-images.githubusercontent.com/20834957/80436689-b6840500-88cd-11ea-8a10-155c28662239.png)

**(nothing logged in event viewer)**

**Comment by Farix1337** [comment] 2020-04-28 13:10
I use Windows 10 1909 18363.778 and i got a similar issue.
When i start KeepasXC 2.5.4 it does not appear at the taskbar at all, only in the taskmanager no matter how long i wait. I did a repair installation but the behavior didn't change. The process appears in the taskmanager but die UI does not open, no error appears, just nothing happens. If i try to open the keepassxc cli the console opens but nothing starts and the outpout stays empty too.
I am currently using the keepassxc portable edition of 2.5.3 and have no issues at all.

**Comment by kekukui** [comment] 2020-04-30 03:18
@Farix1337 - try the [WinLister](https://www.nirsoft.net/utils/winlister.html) program and determine if the window is hidden or does not exist.

![Capturee](https://user-images.githubusercontent.com/20834957/80667917-6e501880-8a6e-11ea-9021-4b3025198e32.PNG)
----------
**Interesting comparison of QT5 applications**

![Capture](https://user-images.githubusercontent.com/20834957/80667964-8d4eaa80-8a6e-11ea-8398-d0f64cbfa6d9.PNG)

![Capture2](https://user-images.githubusercontent.com/20834957/80667981-98a1d600-8a6e-11ea-805d-499a6b9b9b23.PNG)

**Comment by EricBright** [comment] 2020-06-12 00:26
Any news on what causes the issue? It happens, quite predictably, on my PC as well. It happens when the app is minimized (with the DB still open). Once minimized for a period of time, it cannot be opened again. It has to be killed by the task manager, and relaunched.

**Comment by droidmonkey** [comment] 2020-06-12 01:01
We have a beta of 2.6 available in the releases. Give it a try for a little while

**Comment by a-vrma** [comment] 2020-07-04 15:47
Here is what I needed to do to reproduce this on KeePassXC - Version 2.6.0-beta1 (with the browser extension enabled).

```
KeePassXC - Version 2.6.0-beta1
Build Type: PreRelease
Revision: e5b0219

Qt 5.15.0
Debugging mode is disabled.

Operating system: Windows 10 Version 2004
CPU architecture: x86_64
Kernel: winnt 10.0.19041

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5
```

1. Minimize window at night.
2. Lock account.
3. Go to sleep.
4. When I wake up the window has disappeared and I need to kill from Task Manager.

I think it has something to do with the amount of time the program is left alone. I can't reproduce the bug if I leave the PC alone for only 1 hour. The next time I get this problem I will use WinLister to determine if the window is hidden or does not exist.

**Comment by droidmonkey** [comment] 2020-07-04 17:35
When you say minimized, the taskbar icon was still visible? As in, you did not hide the window to the tray icon?

**Comment by a-vrma** [comment] 2020-07-04 17:46
> When you say minimized, the taskbar icon was still visible? As in, you did not hide the window to the tray icon? Were your databases locked or unlocked before you minimized the window? I need very explicit state information if I have any hope of replicating or narrowing this issue.

I did not hide it to a tray icon, it was still visible in the taskbar.  The database was not locked when I minimized the window.

I have attached my keepassxc.ini if that helps (hopefully there is no private info in there 😅).
[keepassxc.ini.txt](https://github.com/keepassxreboot/keepassxc/files/4873442/keepassxc.ini.txt)

**Comment by droidmonkey** [comment] 2020-07-04 18:14
I will need you config file in the roaming folder as well

**Comment by a-vrma** [comment] 2020-07-04 20:23
[local-keepassxc.ini.txt](https://github.com/keepassxreboot/keepassxc/files/4873799/local-keepassxc.ini.txt)

**Comment by a-vrma** [comment] 2020-07-06 01:49
KeePassXC shows up 3 times in my WinLister output with "Display Hidden Windows" enabled.

![image](https://user-images.githubusercontent.com/29077900/86548089-34394200-bf09-11ea-8b49-d8c387b6d161.png)

WinLister allows you to save the details about the windows so I attached that information [here](https://github.com/keepassxreboot/keepassxc/files/4876375/windows.txt).

**Comment by succeedmr123** [comment] 2021-01-19 10:14
Dear, I confirm this behavior is still present in the most recent 2.6.3 release, and that is why I write into this thread and not to QT ticket issue thread as it related to this behaviour exactly as described here.

Asof breaking my production machine workflow to send debug data etc  just for this simple observation - I can not do that, noticing is ienough, and full belief it is the truth.

Latest windows 20H2, 64 bit, KpXC 2.6.3 release etc blabla.. will stick to what is more relevant describing the behaviours, ant then it may be narrowed down to App or the QT framework config or a bug.

Workaround: try to start KeepassXC one more time from the taskbar.

Important for diagnosing further: When it appears, try to right click at the icon in the taskbar to check if taskbar functions like right-click menu options and jumplists work - it does not, fully borken. The icon next to it- totally works.

Therefore, defect is narrowed to [speculative hints]; app framework - QT, OR the app, regarding window definition - Might be flags that describe the underlying Windows OS that concern window dispay and definition, including jumplists displaying are defective

Seen similar but not the same ill behaviour in LibreOffice long time ago (for it is related to the position of the windows previews) - so it really might be QT in part)

Hope that helps, got to continue with my jobs,

Have a great day :-)

**Comment by phoerious** [comment] 2021-01-19 11:10
I am not sure exactly what your issue is. Please give a detailed and structured recipe for reproducing it.

**Comment by droidmonkey** [comment] 2021-01-19 11:15
Right clicking the Taskbar icon doesn't do anything, perhaps because the application is in deadlock or something.

**Comment by phoerious** [comment] 2021-01-19 12:39
I have never had that issue.

**Comment by droidmonkey** [comment] 2021-01-19 13:02
Neither have I

**Comment by succeedmr123** [comment] 2021-01-20 16:23
Dear, please allow me to point that this issue is exhibited on both of machines run here - one with sandy bridge, another with brasswell /Atom N5xxx on latest W10 64 bit 20H2. Therefore, the issue is fully existent on some W10x64 systems (I can vouch for V1903 / V20H2).

The purpose of feedback is to collect additional data via reporting the issues with KeepassXC on some Windows 10 x64 systems.


Best regards

**Comment by mitohund** [comment] 2021-01-29 12:20
Intere

> 
> 
> Here is what I needed to do to reproduce this on KeePassXC - Version 2.6.0-beta1 (with the browser extension enabled).
> 
> ```
> KeePassXC - Version 2.6.0-beta1
> Build Type: PreRelease
> Revision: e5b0219
> 
> Qt 5.15.0
> Debugging mode is disabled.
> 
> Operating system: Windows 10 Version 2004
> CPU architecture: x86_64
> Kernel: winnt 10.0.19041
> 
> Enabled extensions:
> - Auto-Type
> - Browser Integration
> - SSH Agent
> - KeeShare (signed and unsigned sharing)
> - YubiKey
> 
> Cryptographic libraries:
>  libgcrypt 1.8.5
> ```
> 
>     1. Minimize window at night.
> 
>     2. Lock account.
> 
>     3. Go to sleep.
> 
>     4. When I wake up the window has disappeared and I need to kill from Task Manager.
> 
> 
> I think it has something to do with the amount of time the program is left alone. I can't reproduce the bug if I leave the PC alone for only 1 hour. The next time I get this problem I will use WinLister to determine if the window is hidden or does not exist.

I am running KeePass 2.47 (not XC) and I have the exact same issue. Oftentimes, the main window is minimised to tray, not taskbar. But it also happens when it's minimised to taskbar.

**Comment by crogonint** [comment] 2021-04-07 01:26
Yeah.. you guys have like 10 issues on 'disappearing window', currently. You might want to look in to it. I'm not real sure which thread to post this on, but I hope it helps. I'm on OpenSUSE, Gnome desktop. I've set KeePassXC to automatically open on boot. After I login (or not) instead of hiding to the tray, the last couple of versions of KeePassXC don't correctly hide the window.. it just disappears entirely. If I open it from the menu, it opens the already existing window (instance) that was invisible. Then I go in to the KeePassXC settings, disable the 'Show a system tray icon' option, and THEN the window er.. indicicator(?) appears in the task bar where it belongs.

At that point I CAN re-enable 'Show a system tray icon' to minimize the window to the tray. It will still repeat the behavior on reboot though, so currently I'm just going to leave it in the task bar.. even though it's a bit annoying.

Good luck! updates are a bit slow to hit the linux distros, so I'll just cross my fingers that it gets repaired sooner than later. :)

**Comment by droidmonkey** [comment] 2021-04-07 02:09
There is honestly nothing we can do if we cannot reproduce it. Your issue is actually totally unrelated to this thread, you need to add a delay to your startup of keepassxc to start after the system tray is available. This is a Qt bug and was closed recently with 2.6.4 with a different startup definition.

I am closing this issue because there is nothing we are going to do to address this without actual debug logs or repeatable sequence.

**Closed by droidmonkey** 2021-04-07 02:09 UTC
Labels: in triage, platform: Windows, user interface

**Comment by crogonint** [comment] 2021-04-08 07:53
Thank you for the quick and clear response, Jonathan! It makes perfect
sense.. now.

One more question though, do I really need to go mucking about in there..
or can I just wait for you guys to roll out a build using QT 2.6.4?
 - James T. Long

------------
There are 10 kinds of people in the world - those who understand binary,
and those who don't.

**Comment by droidmonkey** [comment] 2021-04-08 10:20
2.6.4 is our version, Qt doesn't have a fixbfor this problem yet. The problem is that Qt doesn't keep trying to add a tray icon if the tray is unavailable. This leads to a missing tray icon if the app starts before the tray starts.

**Comment by crogonint** [comment] 2021-04-09 00:05
Got it. No worries then. If I miss the feature enough, I'll try to figure
out how to do a CRON job for it or some such nonsense. :)

Thanks so much!
 - James T. Long

------------
There are 10 kinds of people in the world - those who understand binary,
and those who don't.

**Comment by Mikesco3** [comment] 2024-03-25 16:16
for me the solution was here:
https://github.com/keepassxreboot/keepassxc/issues/7636#issuecomment-1078343152

It basically comes down to starting keepas with the following option:
 `--allow-screencapture`
