### ISSUE TITLE
Cannot change keyboard layout after using auto-type

### ISSUE THREAD

**Issue by xvitaly** [keepassxreboot/keepassxc#1988] opened 2018-05-23 14:25 UTC
## Current Behavior

I cannot change keyboard layout after using auto-type in KeePassXC. I use global `Alt+Shift` combination to switch between keyboard layouts. Switch policy set to `global`.

This bug related to #474.

## Steps to Reproduce (for bugs)

1. Launch KeePassXC.
2. Open password database.
3. Switch layout to non English (RU/DE/etc).
4. Select database entry with Latin login and password (login `sample`, password `example`).
5. Press Ctrl+V to run auto-type in browser.

## Debug Info

KeePassXC - 2.3.3
Revision: 0a155d8

Libs:
- Qt 5.10.1
- libgcrypt 1.8.2

Operating system: Fedora 28
CPU architecture: x86_64
Kernel: 4.16.9-300.fc28.x86_64
DE: KDE Plasma 5.12.5.
X11 version: 1.19.6

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by 2e3s** [comment] 2018-08-09 01:09
This happens in XFCE on Fedora too, and it has happened on Kubuntu 17.10 and 18.04. However, some time after session start the text is autotyped in cyrillic alright with no problems, so I can't reproduce it 100% times.

**Comment by droidmonkey** [comment] 2019-07-10 02:49
Duplicate of #2246

**Closed by droidmonkey** 2019-07-10 02:49 UTC
Labels: platform: KDE
