### ISSUE TITLE
Firefox dialog access not working

### ISSUE THREAD

**Issue by rredford** [keepassxreboot/keepassxc#3381] opened 2019-07-16 10:59 UTC
## Expected Behavior
I can set user and password from keepassxc in firefox dialog. 

## Current Behavior
It shows permission access? I selected yes. Dialog does not have anything related to keepassxc.

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )

## Steps to Reproduce
1. Open any site or router that has login that is NOT html page but are dialog window.
2. Accept access if needed.
3. Click username and it won't show anything.

## Context
Router I use has a website control that has login that uses dialog.

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 5.4.7

Operating system: xfce mint

**Comment by varjolintu** [comment] 2019-07-18 05:37
What do you mean by a dialog? A HTTP Basic Auth dialog? If so, that will ask for a permission to access your credentials. If you allow it, it will fill the HTTP Basic Auth credentials.

Btw. what is KeePassXC 5.4.7?

**Comment by rredford** [comment] 2019-07-20 04:42
Yes. And nope, it does show if I allow it or not, I clicked allow and remember it. It does NOT fill in those, hence my posting here. :)

The program this GIT is for. 5.4.7 is version.

**Comment by varjolintu** [comment] 2019-07-26 09:46
I don't quite understand what this problem is. Could you elaborate?

**Comment by rredford** [comment] 2019-07-26 23:42
Basically, nothing happens. Login and password does not show up.

**Comment by droidmonkey** [comment] 2019-07-27 03:49
This is a duplicate of the other http access dialog issue and the submitted PR's fix it.

**Closed by droidmonkey** 2019-07-27 03:49 UTC
Labels: bug
