### ISSUE TITLE
Single Instance prevents load when lock file remains behind

### ISSUE THREAD

**Issue by Aholiab** [keepassxreboot/keepassxc#993] opened 2017-09-24 19:50 UTC
## Expected Behavior
After I launch, KeePassXC should appear somewhere.

## Current Behavior
I can't find KeePassXC anywhere. I search in Process Explorer, and it's not there, even though I just launched it. This repeatedly happens.
This is a new laptop, but KeePassXC was working perfectly for a few day, until about an hour before. I have booted between failures--doesn't seem to matter.

## Possible Solution
NA
Poor solution that works: I'm running KeePassXC portable off the hard drive. That works.

## Steps to Reproduce (for bugs)
1. Start, click on KeePassXC
2. Look in hidden icons
3. Try to find in Process Explorer
4. It's disappeared.

## Context
NA

## Debug Info

Can't get to Help About.
KeePassXC - latest 64-bit version from today's website
Revision: ditto

Libraries:
- LIBS

Operating system: Windows 10 Home 64-bit
CPU architecture: ??
Kernel: ??

Enabled extensions:
- EXTENSIONS

**Comment by seatedscribe** [comment] 2017-09-24 20:01
This is a perfect user case for adding a CLI option to display
version/revision information. Maybe save this to the wishlist?

For your troubleshooting:
- invoke the command from a shell (e.g. bash) window. Does it solve the
problem?

- If not, can you post the output of the command 'strace keepassxc'
(without quotes)?

Hth,
Enrico

**Comment by droidmonkey** [comment] 2017-09-24 22:05
See fix in this comment: https://github.com/keepassxreboot/keepassxc/issues/890#issuecomment-325498877

This will be addressed in 2.2.1

**Comment by droidmonkey** [comment] 2017-09-26 03:35
Duplicate of #893

**Closed by droidmonkey** 2017-09-26 03:35 UTC
Labels: bug, high priority, Windows
