### ISSUE TITLE
Crash with MacOS 10.15.4

### ISSUE THREAD

**Issue by Guillaume99** [keepassxreboot/keepassxc#4486] opened 2020-03-25 15:22 UTC
After updating to MacOS 10.15.4,
when lauching, the following message is displayed : "KeePassXC quit unexpectedly", and application is immediatly killed.

## Steps to Reproduce
1. update MACOS to 10.15.4
2.launch KeepassXC  

Operating system: MacOS 10.15.4
CPU architecture: ARCH
Kernel: KERNEL

Enabled extensions:
- none

**Comment by bmendonca** [comment] 2020-03-25 15:27
I encountered this as well and came here to see if it was just me. I also tried reinstalling KeepassXC from scratch so that I could "reallow" the application from the security standpoint. Here's a snippet of the crash message I got that is probably similar to Guillaume99's: 

```
Exception Type:        EXC_CRASH (Code Signature Invalid)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace CODESIGNING, Code 0x1
```

**Comment by varjolintu** [comment] 2020-03-25 15:36
Duplicate of https://github.com/keepassxreboot/keepassxc/issues/4398.

**Closed by varjolintu** 2020-03-25 15:36 UTC
Labels: duplicate
