### ISSUE TITLE
keypassxc-cli: Usage instructions missing

### ISSUE THREAD

**Issue by fthommen** [keepassxreboot/keepassxc#840] opened 2017-08-01 08:08 UTC
Usage instructions for the keepassxc CLI are missing.  There is no manpage, no wikipage and `keypassxc-cli --help` doesn't print out enough information to use it

## Expected Behavior
There should be some kind of documentation on how to use `keypassxc-cli`.  E.g. on how to modify/add/search for entries or on how to use a key to authenticate to the KeePass database

## Current Behavior
There is (almost) no documentation

## Possible Solution
Write documentation :-)

## Debug Info
This refers to `keepassxc-cli` from an extracted KeePassXC-2.2.0-x86_64.AppImage

**Comment by TheZ3ro** [comment] 2017-08-01 18:33
This is essentially a duplicate of #681 (that covers the manpage)

Right now the cli interface is very basic. We are working on it.

**Comment by louib** [comment] 2017-08-09 19:25
Closing as we will be tracking documentation of the CLI in #681

**Closed** 2017-08-09 19:24 UTC
