### ISSUE TITLE
Crash upon quitting

### ISSUE THREAD

**Issue by TempSpas** [keepassxreboot/keepassxc#1622] opened 2018-03-04 15:32 UTC
Occasionally upon quitting the application, dialog will appear explaining that KeePassXC has unexpectedly quit. This has happened to me twice since the most recent update.

## Expected Behavior

Application should quit normally.

## Current Behavior

Sometimes, it crashes instead of quitting.

## Steps to Reproduce (for bugs)

1. Have KeePassXC open.
2. Press the shortcut Command-Q to quit.
3. Observe the program crashes instead of quitting.

## Debug Info

KeePassXC - Version 2.3.0
Revision: 4c0ed74

Libraries:
- Qt 5.9.3
- libgcrypt 1.8.2

Operating system: macOS High Sierra (10.13)
CPU architecture: x86_64
Kernel: darwin 17.4.0

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

Libraries:
- LIBS

Operating system: OS
CPU architecture: ARCH
Kernel: KERNEL

Attached is the crash log.

[kpxc_crash.txt](https://github.com/keepassxreboot/keepassxc/files/1778642/kpxc_crash.txt)

**Comment by phoerious** [comment] 2018-03-04 17:51
Duplicate of #1543

**Closed by phoerious** 2018-03-04 17:51 UTC
