### ISSUE TITLE
Password Generator includes special characters when only alphanumeric are selected

### ISSUE THREAD

**Issue by mcx808** [keepassxreboot/keepassxc#3161] opened 2019-05-20 16:24 UTC
My password generator default settings are for alphanumeric characters.

On new entries and when using the ad-hoc generator, special characters are being included in the password despite them not being selected:

![image](https://user-images.githubusercontent.com/30801293/58036789-376a4680-7b2c-11e9-8054-d22b664db6ba.png)

A workaround is to select and deselect special characters, which then generates a password conforming to my selection.

This appears to be a new issue in v2.4.1. I have not observed this behaviour in any version before.
KeePassXC - Version 2.4.1
Revision: 7bafe65

Qt 5.12.2
Debugging mode is disabled.

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.17763

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.4

**Comment by droidmonkey** [comment] 2019-05-20 21:33
Duplicate of #3064. The same root cause applies

**Closed by droidmonkey** 2019-05-20 21:33 UTC
Labels: bug
