### ISSUE TITLE
Auto-type doesn't work properly when I switch keyboard layouts

### ISSUE THREAD

**Issue by GUiHKX** [keepassxreboot/keepassxc#1433] opened 2018-01-27 15:28 UTC
I use KDE Plasma 5.11, and use two keyboard layouts: `en-US` and `pt-BR`. One of my passwords have `{` and `[` in it, but if my keyboard layout is set to `en-US` and I use auto-type, somehow `{` turns into `}`, and `[` turns into `]`. This does not happen when it's set to `pt-BR`.

## Expected Behavior
Auto-type should not behave differently when I have a different keyboard layout... (I guess?)

## Current Behavior
If I'm using the `en-US` layout and my username or password is `{ } [ ] < > ( ) / \`, when I use auto-type:

* `{` turns into `}`
* `}` turns into `|`
* `[` turns into `]`
* `]` turns into `\`

`<`, `>`, `(`, `)`, `/` and `\` are still the same in both layouts.

## Steps to Reproduce (for bugs)
1. You must have two different keyboard layouts, in my case they are: `English (US)` and `Portuguese (Brazil)`
2. Create a new entry, "Username" being: `User { } [ ] < > ( ) / \`, and "Password" being: `Pass { } [ ] < > ( ) / \`
3. Add a program to the Window Association option, to test the Auto-Type behavior. (I've used a text editor because it's easier)
4. Open your text editor, press `Ctrl + Alt + A` to issue Auto-Type
5. Switch your keyboard layout and try Auto-Type again
6. If the bug actually worked, the first auto-type shouldn't match the second, like so:

![screenshot_20180127_132453](https://user-images.githubusercontent.com/626206/35473324-d10d9976-0365-11e8-9d23-387c624df5c5.png)

## Context
I was trying to use auto-type in the Steam desktop client, which is buggy by itself, so in the beginning I thought it was a Steam issue. But I've tried auto-typing the same password in different programs and the behavior still was the same.

## Debug Info
```
KeePassXC - Version 2.2.4
Revision: 46c58b3

Libraries:
- Qt 5.10.0
- libgcrypt 1.8.2

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 4.14.15-1-ARCH

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey
```

**Comment by hifi** [comment] 2018-01-28 12:13
Are you using per-application keyboard layouts? I could see there being a problem if the KeePassXC window is using a different layout than the application auto-type is targeting.

**Comment by phoerious** [comment] 2018-01-28 12:36
Duplicate of #324.

**Closed by phoerious** 2018-01-28 12:36 UTC

**Comment by GUiHKX** [comment] 2018-01-28 13:05
@hifi Nope, I'm using it globally.
