### ISSUE TITLE
Snap does not use interface removable-media

### ISSUE THREAD

**Issue by usinggh** [keepassxreboot/keepassxc#497] opened 2017-04-12 20:36 UTC
Snap does not use the interface removable-media. Therefore access to database stored on memory stick is not possible.

![image](https://cloud.githubusercontent.com/assets/27376004/24978291/6d71499a-1fd0-11e7-866b-69e41521c44e.png)

**Comment by TheZ3ro** [comment] 2017-04-12 20:43
Ping @droidmonkey

**Comment by droidmonkey** [comment] 2017-04-12 21:50
This is a duplicate issue.

**Comment by TheZ3ro** [comment] 2017-04-12 22:50
You are right. Duplicate of #400

**Closed by TheZ3ro** 2017-04-12 22:50 UTC
