### ISSUE TITLE
Bring back password column + copy username / password on double-click 

### ISSUE THREAD

**Issue by fonic** [keepassxreboot/keepassxc#455] opened 2017-04-01 09:10 UTC
I always loved the possibility to copy username / password to clipboard by double-clicking the respective column. Currently, there is no password column at all and a double-click on the username opens the entries' details instead of copying the username to the clipboard.

The feature was present in KeePassX 0.4.x and got removed in 2.x. Its removal was the main reason why I switched to original KeePass, but I'd love to switch back to KeePassXC.

**Comment by TheZ3ro** [comment] 2017-04-01 09:31
We are aware of this, those feature weren't really removed in 2.x, since it is a complete rewrite they aren't implemented at all yet.

Duplicate of #17 (password column) and #360 (double-click to copy) so I will close this in favor of those

**Closed** 2017-04-01 09:31 UTC
Labels: duplicate
