### ISSUE TITLE
Website not accessible as of Fri 03 Sep 2021 02:56:54 AM UTC

### ISSUE THREAD

**Issue by obtusedev** [keepassxreboot/keepassxc#6886] opened 2021-09-03 02:57 UTC
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Website down as of Fri 03 Sep 2021 02:56:54 AM UTC

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Go to https://keepassxc.org/

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Able to visit website

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Hmm. We're having trouble finding that site.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Ubuntu & iOS
Desktop Env: Gnome/KDE/XFCE/Mate/Cinnamon
Windowing System: X11/Wayland

**Comment by droidmonkey** [comment] 2021-09-03 03:36
Google DNS and Open DNS are failing to resolve our address. The server is up and hosting the site just fine. This is likely an anomaly. We'll watch this into tomorrow to see if it resolves. 

Tested using https://www.dnstester.net/

**Comment by lifehome** [comment] 2021-09-03 07:12
Hi,

I am so sorry that I have kind of "intended" to test if the resolving issues is caused by DNS cache or not, so I cleared the A record of `keepassxc.org` at Cloudflare DNS cache. And immediately after that, the testing site provided by @droidmonkey failed to resolve with Cloudflare DNS.

Since the domain name `keepassxc.org` is signed with DNSSEC with GoDaddy, my guess is that GoDaddy has provided an invalid value for the DS record, thus all the compliant DNS resolvers that mandates/follows the DNSSEC will fail the resolve.

<img width="1186" alt="螢幕截圖 2021-09-03 15 10 04" src="https://user-images.githubusercontent.com/1886237/131965214-6920ea91-550f-42c8-b6ff-3b8838475a47.png">

With the above deduction, it is  the authoritative nameserver of `keepassxc.org` by GoDaddy can respond the designated value:
```
lifehome@localhost ~ % dig A @PDNS07.DOMAINCONTROL.COM keepassxc.org

; <<>> DiG 9.10.6 <<>> A @PDNS07.DOMAINCONTROL.COM keepassxc.org
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 65229
;; flags: qr aa rd; QUERY: 1, ANSWER: 1, AUTHORITY: 2, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1472
;; QUESTION SECTION:
;keepassxc.org.			IN	A

;; ANSWER SECTION:
keepassxc.org.		3600	IN	A	185.26.156.57

;; AUTHORITY SECTION:
keepassxc.org.		3600	IN	NS	pdns08.domaincontrol.com.
keepassxc.org.		3600	IN	NS	pdns07.domaincontrol.com.

;; Query time: 32 msec
;; SERVER: 97.74.111.53#53(97.74.111.53)
;; WHEN: Fri Sep 03 15:00:56 HKT 2021
;; MSG SIZE  rcvd: 117
```

With further "digging" using third party services also confirms the severity of this incident:  
https://www.digwebinterface.com/?hostnames=keepassxc.org&type=A&useresolver=8.8.4.4&ns=all&nameservers=  
```
keepassxc.org@8.8.4.4 (Default):


keepassxc.org@94.140.14.14 (AdGuard (CY)):
keepassxc.org.		3355	IN	A	185.26.156.57

keepassxc.org@165.87.13.129 (AT&T (US)):
keepassxc.org.		3600	IN	A	185.26.156.57

keepassxc.org@1.1.1.1 (CloudFlare):


keepassxc.org@8.26.56.26 (Comodo (US)):
keepassxc.org.		3600	IN	A	185.26.156.57
keepassxc.org.		3600	IN	NS	pdns08.domaincontrol.com.
keepassxc.org.		3600	IN	NS	pdns07.domaincontrol.com.

keepassxc.org@8.8.8.8 (Google):


keepassxc.org@168.95.1.1 (HiNet (TW)):
keepassxc.org.		3600	IN	A	185.26.156.57

keepassxc.org@208.67.222.222 (OpenDNS):


keepassxc.org@9.9.9.9 (Quad9):
keepassxc.org.		3600	IN	A	185.26.156.57

keepassxc.org@144.217.51.168 (Securolytics (CA)):
keepassxc.org.		3600	IN	A	185.26.156.57

keepassxc.org@195.129.12.122 (UUNET (CH)):


keepassxc.org@192.76.144.66 (UUNET (DE)):


keepassxc.org@158.43.240.3 (UUNET (UK)):


keepassxc.org@198.6.100.25 (UUNET (US)):
keepassxc.org.		3600	IN	A	185.26.156.57

keepassxc.org@64.6.64.6 (Verisign (US)):
keepassxc.org.		3600	IN	A	185.26.156.57

keepassxc.org@77.88.8.8 (Yandex (RU)):
keepassxc.org.		3600	IN	A	185.26.156.57
```

My suggestion is to move away from GoDaddy as they don't really provide quality service at all...  
I'm not affiliated in any way, but my current choices for domain names are with Porkbun, as they provide great services.

EDIT: [DNSSEC is not something to be fire and forget](https://dane.sys4.de/common_mistakes), Cloudflare have automated the process but with other providers, sysadmin or tech guys should keep an eye on their PKI and things to keep the website up and running.

EDIT again: To immediately rectify this situation, the webmaster can immediately change the authoritative nameserver to another one(e.g., Cloudflare) and let that nameserver to sign off the DNSSEC record, and republish the new one at GoDaddy. **But again, I recommend against using the services of GoDaddy.**

Regards,
Ivan

**Comment by droidmonkey** [comment] 2021-09-03 07:40
Thank you confirmed: https://dnsviz.net/d/keepassxc.org/dnssec/

@phoerious

**Comment by phoerious** [comment] 2021-09-03 07:43
Looks like GoDaddy fucked up the DNSSec key rotation. I turned it off and on again, should be working again once the new records are propagated.

**Comment by lifehome** [comment] 2021-09-03 07:45
@droidmonkey @phoerious

I have flushed a several public DNS resolver, and we can immediately see the site is up and running again now! :DD

**Comment by phoerious** [comment] 2021-09-03 07:46
GoDaddy's DNSSec is usually fire-and-forget. Not sure what happened here.

**Closed as completed** 2021-09-03 07:51 UTC
Labels: upstream
