### ISSUE TITLE
Settings toolbar labels are clipped with Light/Dark theme

### ISSUE THREAD

**Issue by cl0ne** [keepassxreboot/keepassxc#5164] opened 2020-07-24 13:50 UTC
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Labels of toolbar buttons for switching pages in Settings are clipped because they are positioned outside of the button's boundaries (too low)

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Choose Light or Dark theme
2. Open Application or Database Settings
3. Look at the vertical toolbar on the left that switches pages of Settings screen 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Labels should be visible as with Platform-native theme:
![native](https://user-images.githubusercontent.com/271097/88398115-8ca78500-cdcd-11ea-9b18-061507fe9f09.png)

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
![dark](https://user-images.githubusercontent.com/271097/88398077-80bbc300-cdcd-11ea-949b-9803bb99969b.png)
![light](https://user-images.githubusercontent.com/271097/88398092-83b6b380-cdcd-11ea-812e-ca16d5bc7cea.png)

## Context
[NOTE]: # ( Give us any additional information you may have. )
I've tried latest version (2.6.0) from Arch Linux repositories and separately built latest version from develop branch, result is the same.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.0-snapshot
Build Type: Snapshot
Revision: 71b05db

Qt 5.15.0
Debugging mode is disabled.

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 5.7.9-arch1-1

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.6

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: KDE
Windowing System: X11

**Comment by droidmonkey** [comment] 2020-07-24 14:17
Look at the pinned issues please.

**Comment by cl0ne** [comment] 2020-07-24 14:22
@droidmonkey I did that before opening the issue. Neither #4963 nor #5029 didn't mention this kind of problem. All other icons are completely fine looking.

**Comment by droidmonkey** [comment] 2020-07-24 14:34
You have scaling issues in general, you most likely need to apply the environment variable `QT_AUTO_SCREEN_SCALE_FACTOR=0` or `QT_SCALE_FACTOR_ROUNDING_POLICY=Round`

**Comment by cl0ne** [comment] 2020-07-24 14:47
I've already `QT_AUTO_SCREEN_SCALE_FACTOR` set to 0. BTW the only `QT_*` variables set are:
```QT_SCREEN_SCALE_FACTORS=eDP-1=1;HDMI-1=1;
QT_AUTO_SCREEN_SCALE_FACTOR=0
```
Setting `QT_SCALE_FACTOR_ROUNDING_POLICY=Round` does exactly nothing to this issue.

**Comment by droidmonkey** [comment] 2020-07-24 15:01
Sorry this was the key: https://github.com/keepassxreboot/keepassxc/issues/5015#issuecomment-657149061

**Comment by cl0ne** [comment] 2020-07-24 15:14
I've tried setting `QT_SCALE_FACTOR` in different combinations with other `QT_*` variables but that doesn't change the outcome: labels with Light/Dark theme are cropped while everything is fine with Classic.

**Comment by droidmonkey** [comment] 2020-07-24 15:33
The problem is you are overriding screen scaling explicitly. I recommend deleting the overrides of `QT_AUTO_SCREEN_SCALE_FACTOR` and `QT_SCREEN_SCALE_FACTORS` and `QT_SCALE_FACTOR`. ONLY set `QT_SCALE_FACTOR_ROUNDING_POLICY=Round`

**Comment by cl0ne** [comment] 2020-07-24 15:51
> The problem is you are overriding screen scaling explicitly. I recommend deleting the overrides of `QT_AUTO_SCREEN_SCALE_FACTOR` and `QT_SCREEN_SCALE_FACTORS` and `QT_SCALE_FACTOR`. ONLY set `QT_SCALE_FACTOR_ROUNDING_POLICY=Round`. There is a Qt bug with non-HIDPI displays with a scale factor of 1.0 and using the "PassThrough" policy.

Yes, I've tried that among other combinations I've mentioned above. And it didn't change anything.

**Comment by droidmonkey** [comment] 2020-07-24 15:53
Are you sure they are actually applying to the application. I am assuming you are restarting it between attempts and verifying that the environment variables are actually set.

**Comment by cl0ne** [comment] 2020-07-24 15:57
> Are you sure they are actually applying to the application. I am assuming you are restarting it between attempts and verifying that the environment variables are actually set.

Yes, I quit app before unsetting/exporting any variables in bash instance from which I start the app.

**Comment by droidmonkey** [comment] 2020-08-03 01:18
This is fixed by #5185

**Closed by droidmonkey** 2020-08-03 01:18 UTC
Labels: bug
