### ISSUE TITLE
Segmentation fault enabling browser integration

### ISSUE THREAD

**Issue by bitterjug** [keepassxreboot/keepassxc#1928] opened 2018-05-09 11:27 UTC
## Expected Behavior

Enable browser integration

## Current Behavior

Gui crashes, segfault reported on standard out.

## Steps to Reproduce (for bugs)

1. Open Keepassxc, unlock database
2. Tools/Settings/Browser Integration
3. Enable KeePassXC browser Integratrion
4. Apply

At this point the gui closes and, if I run it from the command line, I get the following messge:
```
1d [:~] $ keepassxc
QObject::startTimer: Timers cannot have negative intervals
Segmentation fault
```
I can get the seg fault without first unlocking the db in which case Std.Out doesn't include the message about timers:
```1d [:~] 139 $ keepassxc
Segmentation fault
```

## Context

Installed from ppa this morning. Op

## Debug Info

KeePassXC - Version 2.3.2
Revision: 2bb72eb

Libraries:
- Qt 5.5.1
- libgcrypt 1.8.1

Operating system: Ubuntu 16.04.4 LTS
CPU architecture: x86_64
Kernel: linux 4.13.0-39-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by phoerious** [comment] 2018-05-09 11:31
Duplicate of #1922

**Closed by phoerious** 2018-05-09 11:31 UTC
