### ISSUE TITLE
System pop-up dialogs for file manipulation are getting randomly closed on their own

### ISSUE THREAD

**Issue by pbukva** [keepassxreboot/keepassxc#5295] opened 2020-08-20 11:19 UTC
## Overview
All OS system pop-up dialogs like `Open Database...`, `Save Database As...`, `Save Database Backup...`, etc. ..., are getting closed on their own after short period of time, without user clicking/selecting appropriate button to close them.  

## Steps to Reproduce
1. Go to `Database -> Open Database...`
2. OS system pop-up dialog for file open pops up
3. Use mouse to click somewhere in to the dialog and WAIT
4. Dialog closes on it's own after a few seconds, usually in the frame of 10s

## Expected Behavior
Dialog shall stay open until user selects desired action, e.g. after clicking on cancel or open button. 

## Actual Behavior
Dialog disappearts on it's own after some time - usually in the frame of 10secs. It looks like that closing time is shortened when user interacts with pop-up dialog (e.g. clicking in to it).

## Context
KeePassXC - Version 2.6.1
Revision: 9a35bba

Operating System: macOS
Desktop Env: n.a.
Windowing System: n.a.

**Comment by droidmonkey** [comment] 2020-08-20 11:31
This is a Qt bug

**Comment by pbukva** [comment] 2020-08-20 11:46
I'm not so sure.

As it turns out the random closing time period seems to be shortend with increasing number of openned & UNLOCKED databases in the KeepassCX application.

**Comment by droidmonkey** [comment] 2020-08-20 21:13
I've debugged this for hours in the past. It is not something on our end

**Comment by pbukva** [comment] 2020-08-21 00:23
I have never observed such a behaviour in other Qt apps, on macOS or other OS-es (e.g. krusader, kdiff3, etc. ...).

Observed behaviour (= shortening of dialong closing time with increasing number of oppened&unlocked databases in the app) indicates that this is caused by implemnntation of this app.
For example something in threading model of the app, e.g. how mesage queues are used - how events are passed around in to or between queues, including handling of various timers/timeouts, etc. ... . In general it is really hard to find bugs in threading model, and using debugger is usually not the best approach in such situations.

To be frank, this is not crytical bug at all since it is gettin prevalent only whn you have olredy open 3 or more files.
I would not bark on the tree, but this really affects usability of the app - it basically disables openning new files, saving as, etc. ... . And it's ellusivenes makes it specially weird for users, since it chages behaviour with num. of opened files, and users have no clue what is going on.

**Comment by pbukva** [comment] 2020-08-21 00:36
This might be related: https://bugreports.qt.io/browse/QTBUG-56746
However it is quite old, was reported in 2016 for Qt 5.7.1, and I can't find how or whether the bug was resolved.

**Comment by droidmonkey** [comment] 2020-08-21 00:40
Lemme put it this way, it should be impossible to get the dialog in such a state that it does not behave like this. Being that it is possible, its either a Qt or macOS bug or both.

**Comment by templateK** [comment] 2020-09-26 15:30
Just for a data point.

The time window before dialog closing is about 20 seconds right after fresh launch, which is barely usable.
macOS mojave 10.14.5. manually compiled from source https://github.com/keepassxreboot/keepassxc/commit/ac5c1af829bd7da63295b60426d3001840a5f158

**Comment by templateK** [comment] 2020-09-26 17:21
I've bisected the code causing this issue. https://github.com/keepassxreboot/keepassxc/blob/ac5c1af829bd7da63295b60426d3001840a5f158/src/core/FileWatcher.cpp#L121

if I change that line to synchronous code, the dialogs won't close at least for my system.

```diff
modified   src/core/FileWatcher.cpp
@@ -118,7 +118,7 @@ void FileWatcher::checkFileChanged()
     // Prevent reentrance
     m_ignoreFileChange = true;
 
-    auto checksum = AsyncTask::runAndWaitForFuture([this]() -> QByteArray { return calculateChecksum(); });
+    auto checksum = calculateChecksum();
     if (checksum != m_fileChecksum) {
         m_fileChecksum = checksum;
         m_fileChangeDelayTimer.start(0);
```
I looked into the `runAndWaitForFuture` code and found that it uses `quit()` as receiving SIGNAL to a  `QEventLoop`
local variable and this somehow causes the dialog closed. 

Of course, that's totally unfounded my speculation as I don't know anything about Qt programming.

**Comment by droidmonkey** [comment] 2020-09-26 17:55
The way AsyncTask works is a new event loop is entered on the main thread so you get a situation like:

Main Event Loop > ... stack ... > AsyncTask Event Loop > ... stack ...

When the quit() slot is called, the AsyncTask Event Loop will end returning event processing back to the main event loop. This returns control back at the line that called the AsyncTask to begin with (ie delivering the result).

It is possible that quitting the AsyncTask event loop while a QFileDialog is visible on macOS causes that dialog to close. Keep testing your patch, if it never reoccurs I will investigate further.

**Comment by droidmonkey** [comment] 2020-09-27 03:03
@templateK confirmed! This is absolutely what is causing the dialog to close. I increased the rate of checksum checks and the dialog closes immediately every time. I then removed the AsyncTask and the dialog remained open. We will have to rethink how we implement AsyncTask in order to fix this... or accept a potential for a UI hiccup when a database checksum is calculated.

**Comment by phoerious** [comment] 2020-09-27 07:48
If an event loop closes dialogues which it hasn't spawned, then I'd say that's a bug in Qt. I don't really see an alternative to using event loops, though. We cannot let the UI freeze every 10 seconds. Or we need a different signalling method for the check thread.

**Comment by templateK** [comment] 2020-09-27 10:50
@droidmonkey Thank you for checking out and confirming this issue. 

@phoerious 
I cannot fix `runAndWaitForFuture` because I presume it's used many other places and doesn't know the whole picture.
But, I've tried make the `calculateChecksum` in `FileWatcher::checkFileChanged` asynchronous without `QEventLoop`
I had to introduce new private member variable `QFuture` and `QFutureWatcher` of `FileWatcher` class.  

it's at https://github.com/templateK/keepassxc/commit/2a7a10b9910c16554a25f41bccc5d5845f19fdcd

**Comment by droidmonkey** [comment] 2020-09-27 12:56
I have a plan on how to do this using lambda functions similar to what you proposed. Want to convert AsyncTask to still use a QFutureWatcher but instead of entering an event loop it just queues a call to a pre-defined lambda completer function.

**Closed** 2020-10-07 15:27 UTC
Labels: Qt Bug, platform: macOS
