### ISSUE TITLE
Low resolution application and notification icons, theme's off 

### ISSUE THREAD

**Issue by johnnydvc** [keepassxreboot/keepassxc#355] opened 2017-02-27 21:33 UTC
## Expected Behavior
keepassxc should stick to the general theme, maybe qt issue.

## Current Behavior

icons inside keepassxc and the indicator are very low resolution.

![screenshot-2017_02_01_221202-514x226](https://cloud.githubusercontent.com/assets/4787052/23380941/06b1f70a-fd3d-11e6-992d-b30be26a627f.png)

![screenshot-2017_02_01_221218-119x48](https://cloud.githubusercontent.com/assets/4787052/23380962/1fd9c96a-fd3d-11e6-9089-09f854bbb38f.png)

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* KeePassXC version 2.1.2 from aur
* Qt version Qt 5.8.0-5
* Compiler (e.g. Clang++3.6.0): 
* Operating System and version: 4.8.17-1-MANJARO

**Comment by phoerious** [comment] 2017-02-27 21:52
This is a duplicate of #323 and #348 and will be fixed in 2.1.3.

**Closed by phoerious** 2017-02-27 21:52 UTC
