### ISSUE TITLE
Attachments disappeared?

### ISSUE THREAD

**Issue by Bondarz** [keepassxreboot/keepassxc#6912] opened 2021-09-12 18:55 UTC
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

Hello everyone, originally I used KeePass and then at some point I switched to KeePassXC.  
When that was exactly I do not know, certainly over a year ago. I could now already observe in at least two of my entries that attachments from my entries are missing. Be it a .pgp file as well as .ppk file. 

Unfortunately I don't know how to repoduce it, nor do I know where the error is. Fact is that always write a note that I have an attachment in the entry. Twice this attachment has already been missing. 

Can something like this happen in combination with a opend database on Windows 10 and Android 11 with KeePassDX? I am really clueless how this can happen.

Thanks for your help and your work.

## Context
[NOTE]: # I use the database on two desktop computers (Windows 10) from a Nextcloud. Also I use the database via Android 11 with KeePassDX 3.0.0
I use a password as well as a key file to unlock.
Otherwise, my entries are always all there, including notes, date of entry and Co.

YubiKey I have only briefly tested, but then removed again and imported a backup without YubiKey.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.6
Revision: 9c108b9

Qt 5.15.2
Diagnosemodus ist deaktiviert.

Betriebssystem: Windows 10 Version 1909
CPU-Architektur: x86_64
Kernel: winnt 10.0.18363

Aktivierte Erweiterungen:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare (bestätigtes und unbestätigtes Teilen)
- YubiKey

Kryptographische Bibliotheken:
- libgcrypt 1.9.2-unknown

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10 and

**Comment by droidmonkey** [comment] 2021-09-12 19:28
There was a bug with one of the other keepass apps last year (I think it was keeweb) that caused attachments to be overwritten and then deleted from the database. This was decidedly NOT a bug in keepassxc. Unless you can reproduce it with keepassxc.

**Comment by droidmonkey** [comment] 2021-09-12 19:30
This issue describes the fail state I mentioned above: https://github.com/keepassxreboot/keepassxc/issues/3048#issuecomment-495807532

**Comment by Bondarz** [comment] 2021-09-15 18:05
> 
> 
> There was a bug with one of the other keepass apps last year (I think it was keeweb) that caused attachments to be overwritten and then deleted from the database. This was decidedly NOT a bug in keepassxc. Unless you can reproduce it with keepassxc.

Thanks, I have never used KeeWeb before. I used to have KeePass2Android, now KeePassDX and the Firefox extension 1.7.9.1

Phew, hard to tell how it deleted some of 
Duplicate of #my attachments. Also, my histories are empty (attachments)

![keepass](https://user-images.githubusercontent.com/19914015/133486195-7bd45425-2ad9-435d-be57-10d9639153f5.png)

**Comment by droidmonkey** [comment] 2021-09-15 18:27
Those two files on the left are databases that were saved but couldn't be renamed into place for some reason. You can rename those to .kdbx and open in keepassxc to see if they contain your attachments.

**Comment by fubar-coder** [comment] 2021-10-25 08:22
@Bondarz My solution was to open the password database in [KeePass](https://keepass.info) and save it again with the "Save as..." menu. The file size grew to twice its original size and the attachment was available in KeePassXC.

**Comment by droidmonkey** [comment] 2021-10-25 10:03
Gonna close this since it is likely not a keepassxc issue. Most likely a file sync confusion.

**Closed as completed by droidmonkey** 2021-10-25 10:04 UTC
Labels: not reproducible, more info needed
