### ISSUE TITLE
Support KDBX 4

### ISSUE THREAD

**Issue by curiosity-seeker** [keepassxreboot/keepassxc#305] opened 2017-02-14 11:47 UTC
KeePass 2.35 [introduced](http://keepass.info/news/n170109_2.35.html) the new KDBX 4 format which supports Argon2, ChaCha20 and improved header and data authentication.

## Expected Behavior
Support of the new KDBX file format and its integrated features.

## Current Behavior
KeePassXC doesn't load KDBX files with the new format. 

## Context
The [KDBX 4 format](http://keepass.info/help/kb/kdbx_4.html) offers various important improvements. For example, Argon2 offers a better resistance against GPU/ASIC attacks.

## Your Environment
* KeePassXC version/commit used: v. 2.1.1 I'm using the AppImage version
* Qt version (e.g. Qt 5.3): 5.8.0
* Compiler (e.g. Clang++3.6.0): 
* Operating System and version: Fedora 25 KDE

**Comment by phoerious** [comment] 2017-02-14 11:55
Duplicate of #148

**Closed by phoerious** 2017-02-14 11:55 UTC
