### ISSUE TITLE
Recognize password requirements on popular sites

### ISSUE THREAD

**Issue by rugk** [keepassxreboot/keepassxc#1454] opened 2018-02-04 20:06 UTC
As it seems, [Safari](https://twitter.com/_inside/status/959549503920660480) has a feature to recognize popular websites and their stupid password requirements, so it can automatically choose the right mode when generating them.

Maybe that is a good addition for KeePassXC, too?

**Comment by droidmonkey** [comment] 2018-02-04 22:06
Sounds like a nightmare to maintain. No chance that this will be implemented without a public api to pull from.

**Comment by rugk** [comment] 2018-02-04 22:14
Yeah, but on the other hand it sounds much better in a FLOSS project, where everyone can contribute, instead of such things in non-open-source browsers.
So maybe it indeed needs another project/GitHub repo/website, where people can add/contribute data and you would only be one user of that. Nevertheless it can be your initiative to create that…

**Comment by droidmonkey** [comment] 2018-02-05 03:57
I'd rather start the initiative to end ridiculous password requirements except for length and obvious repetitive characters.

**Comment by rugk** [comment] 2018-02-05 12:53
Well... in a perfect world you'd succeed, but I doubt you'll get far this way... 😆

**Comment by noMICROSOFTbuhtz** [comment] 2019-03-05 08:05
I agree with to much ressources for a FOSS project to maintaine.

Often the problem is the websites doesn't inform the user about the complete passwort restrictions. Even the admins didn't knew it themself!

Myself I contact the admins all the time. IMO this is more in the responsibility of the (FOSS) users to flood the admins with questions about that. If more users asking such questions they will think more about it.

In context of KeePassXC this Issue can IMO be closed or set to something like "nice to have - but will never implemented"

**Comment by droidmonkey** [comment] 2019-03-05 12:48
I'm closing it since the web credentials standard is now approved

**Closed by droidmonkey** 2019-03-05 12:48 UTC
Labels: wishlist

**Comment by rugk** [comment] 2019-03-05 20:37
> the web credentials standard

The _what_?

**Comment by droidmonkey** [comment] 2019-03-05 20:47
See #1870
