### ISSUE TITLE
Auto-Type into VMware Fusion not working

### ISSUE THREAD

**Issue by joergrenn** [keepassxreboot/keepassxc#4711] opened 2020-05-07 09:41 UTC
## Overview
Auto-Type into a VM running in VMware Fusion is not working correctly.
Instead of the actual text just the character "a" ist Auto-Typed  "aaaaa"

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. In VMware Fusion press the global Auto-Type shortcut
or
2. Switch from VMware Fusion window to Keepassxc windows 
3. Select Auto-Type for a database entry

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
The content of the mapped fields is Auto-Typed into the active window.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Just the character "a" is Auto-Typed into the active window.
The number of characters typed seems to be correct.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.5.4
Revision: dcca5aa

Qt 5.12.3
Diagnosemodus ist deaktiviert.

Betriebssystem: macOS 10.15
CPU-Architektur: x86_64
Kernel: darwin 19.4.0

Aktivierte Erweiterungen:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare (bestätigtes und unbestätigtes Teilen)
- YubiKey
- TouchID

Kryptographische Bibliotheken:
 libgcrypt 1.8.5

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows/Linux/macOS
Desktop Env: Gnome/KDE/XFCE/Mate/Cinnamon
Windowing System: X11/Wayland

**Comment by phoerious** [comment] 2020-05-07 09:46
Duplicate of #1833.

**Closed by phoerious** 2020-05-07 09:46 UTC
Labels: bug
