### ISSUE TITLE
FEATURE REQUEST: Drag-n-Dropp between open databases in tabs

### ISSUE THREAD

**Issue by cto741** [keepassxreboot/keepassxc#2363] opened 2018-10-06 18:46 UTC
It would be nice to Drag-n-drop groups between entries or groups of entries between ope databases. 

E.g.  If you start with a DB that has Windows, Networking, Linux, and storage and you'd like to break them in to separate databases it would be nice not to have to manually move each of them to the new database.   This is probably an infrequent usage feature but is sure handy in an enterprise when breaking things up in to security realms.

**Comment by droidmonkey** [comment] 2018-10-06 19:20
Duplicate of #172.

**Closed by droidmonkey** 2018-10-06 19:20 UTC
