### ISSUE TITLE
Change icon of all selected entries

### ISSUE THREAD

**Issue by reagle** [keepassxreboot/keepassxc#770] opened 2017-07-14 18:00 UTC
I'd like to select a few entries and change all their icons at once. I figure this must be an option, but I can't figure out how to do it?

## Debug Info
keepassxc: 2.2.0
/usr/local/Caskroom/keepassxc/2.2.0 (68B)
From: https://github.com/caskroom/homebrew-cask/blob/master/Casks/keepassxc.rb

(There is no "Help → About here" menubar option.)

**Comment by rominf** [comment] 2018-02-15 14:15
Related: #1314

**Comment by phoerious** [comment] 2018-02-15 15:10
Duplicate of #735

**Closed by phoerious** 2018-02-15 15:10 UTC

**Comment by therealmaxmoon** [comment] 2020-05-20 18:30
Is there a solution to this issue? Because the linked issues don't look like they are related to this one.

**Comment by droidmonkey** [comment] 2020-05-20 18:34
You can do this though editing the group icon. You can select to have that icon propogate to the entries under the group
