### ISSUE TITLE
upgrade fails libsodium23 dpkg

### ISSUE THREAD

**Issue by guiek** [keepassxreboot/keepassxc#1706] opened 2018-03-11 20:04 UTC
## Context
Install fails on Linux Mint 18.3

## Debug Info

KeePassXC - keepassxc 2.3.1
Revision: REVISION

Libraries:
- LIBS

Operating system: OS
CPU architecture: Linux Mint
Kernel: 4.13.0-36-generic #40~16.04.1-Ubuntu SMP Fri Feb 16 23:25:58 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

## Current Behavior
electing previously unselected package libgpg-error-127:amd64.
(Reading database ... 343308 files and directories currently installed.)
Preparing to unpack .../libgpg-error-127_1.27-0ppa2~xenial1_amd64.deb ...
Unpacking libgpg-error-127:amd64 (1.27-0ppa2~xenial1) ...
Selecting previously unselected package libgcrypt20-18:amd64.
Preparing to unpack .../libgcrypt20-18_1.8.1-0ppa2~xenial1_amd64.deb ...
Unpacking libgcrypt20-18:amd64 (1.8.1-0ppa2~xenial1) ...
Selecting previously unselected package libargon2-0:amd64.
Preparing to unpack .../libargon2-0_20171227-2+really20161029-0ppa1~xenial1_amd64.deb ...
Unpacking libargon2-0:amd64 (20171227-2+really20161029-0ppa1~xenial1) ...
Preparing to unpack .../libsodium23_1.0.16-0ppa3~xenial1_amd64.deb ...
Unpacking libsodium23:amd64 (1.0.16-0ppa3~xenial1) ...
dpkg: error processing archive /var/cache/apt/archives/libsodium23_1.0.16-0ppa3~xenial1_amd64.deb (--unpack):
 trying to overwrite '/usr/lib/x86_64-linux-gnu/libsodium.so.23.1.0', which is also in package libsodium18:amd64 1.0.16-0ppa1~xenial1
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
Selecting previously unselected package libyubikey0.
Preparing to unpack .../libyubikey0_1.13-1_amd64.deb ...
Unpacking libyubikey0 (1.13-1) ...
Selecting previously unselected package libykpers-1-1:amd64.
Preparing to unpack .../libykpers-1-1_1.17.2-1_amd64.deb ...
Unpacking libykpers-1-1:amd64 (1.17.2-1) ...
Selecting previously unselected package keepassxc.
Preparing to unpack .../keepassxc_2.3.1-0ppa1~xenial1_amd64.deb ...
Unpacking keepassxc (2.3.1-0ppa1~xenial1) ...
Processing triggers for libc-bin (2.23-0ubuntu10) ...
Processing triggers for hicolor-icon-theme (0.15-0ubuntu1) ...
Processing triggers for shared-mime-info (1.5-2ubuntu0.1) ...
Processing triggers for gnome-menus (3.13.3-6ubuntu3.1) ...
Processing triggers for desktop-file-utils (0.22+linuxmint1) ...
Processing triggers for mime-support (3.59ubuntu1) ...
Processing triggers for man-db (2.7.5-1) ...
Errors were encountered while processing:
 /var/cache/apt/archives/libsodium23_1.0.16-0ppa3~xenial1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by phoerious** [comment] 2018-03-11 21:36
Duplicate of #1545

**Closed by phoerious** 2018-03-11 21:36 UTC
