### ISSUE TITLE
RHEL 7.7 64b does not run KPXC 2.5.0 AppImage ( but does 2.4.3 )

### ISSUE THREAD

**Issue by poutnikl** [keepassxreboot/keepassxc#3783] opened 2019-11-04 08:27 UTC
RHEL 7.7 64b does not run KPXC 2.5.0 AppImage
SHA digest of 2.5.0 Appimage was OK, Excution flag was set.

## Expected Behavior
KPXC 2.5.0 AppImage was expected to run as  2.4.3 AppImage does run.

## Current Behavior
It does literally nothing, no error messege, no opening of any window.

Posibly related(wild guess) to 
RHEL 7.7 - /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' on version 2.5.0  #3728

**Comment by phoerious** [comment] 2019-11-04 08:48
Duplicate of #3728 .

**Closed by phoerious** 2019-11-04 08:48 UTC
Labels: bug
