### ISSUE TITLE
[Feature Request] Hotkey Search

### ISSUE THREAD

**Issue by sjaakvandenberg** [keepassxreboot/keepassxc#680] opened 2017-06-26 18:59 UTC
## Expected Behavior
Being able to search entry with hidden toolbar

The KeePassX interface has the ability to search with a hotkey (CTRL+F). Also, this could be done without having the menu bar visible, hitting the hotkey just pulls up the input field.

## Current Behavior
Right now, I have to have the toolbar visible and activate the search field manually in order to use it in KeePassXC.

Screenshot from KeePassX with toolbar hidden
![Screenshot](http://imgur.com/T8uIdOCl.png)

**Comment by TheZ3ro** [comment] 2017-06-26 21:29
I've edited the post so now it's clear.

**Comment by droidmonkey** [comment] 2017-06-26 23:15
I believe this is a duplicate

**Comment by gjost** [comment] 2017-07-20 18:12
This is a duplicate of https://github.com/keepassxreboot/keepassxc/issues/505

**Closed** 2017-07-20 19:44 UTC
Labels: wishlist
