### ISSUE TITLE
keepassxc crashes after downloading favicon

### ISSUE THREAD

**Issue by GentlyD** [keepassxreboot/keepassxc#5128] opened 2020-07-19 12:04 UTC
Hi,

keepassxc crashes after downloading favicon. Error message is as attached. Anything I can do to resolve this?

Thanks so much,
Dirk

![Screen089](https://user-images.githubusercontent.com/52222791/87874233-72823700-c9c8-11ea-91ea-a2a70a1da84e.jpg)

**Comment by droidmonkey** [comment] 2020-07-19 13:01
Probably a duplicate of #4966 or #2734

**Closed by droidmonkey** 2020-07-19 13:01 UTC
