### ISSUE TITLE
Auto-type fails to enter characters in password only, Ubuntu + Firefox

### ISSUE THREAD

**Issue by jimbudarz** [keepassxreboot/keepassxc#2169] opened 2018-07-31 01:13 UTC
## Expected Behavior

CTRL + V in app should enter username and password into most recently open window.

## Current Behavior

CTRL + V enters username correctly, moves to password field and enters something with fewer characters than the full password, and attempts to log into page.
Note: on the same system and Chrome browser the function works as expected.

## Possible Solution

Perhaps the delay between entering username and password is too short.
Current settings: 
Auto-type start delay is 1000ms
Auto-type typing delay is 50ms

## Steps to Reproduce (for bugs)

1. Load Reddit (or other) login screen and click username field
2. Switch window to KeepassXC
3. CTRL + V to auto-type
4. Username is properly auto-typed, but password skips the first several (4?) characters

## Context

This issue means the auto-type feature is useless in firefox. 

## Debug Info

KeePassXC - 2.3.3
Revision: 0a155d8

Libraries:
- LIBS

Operating system: 0a155d8
CPU architecture: x86_64
Kernel: 4.15.0-29-generic

Enabled extensions:
- EXTENSIONS

**Comment by droidmonkey** [comment] 2018-07-31 03:02
Duplicate of #2081.

**Closed by droidmonkey** 2018-07-31 03:02 UTC
