### ISSUE TITLE
Importing share file is blank

### ISSUE THREAD

**Issue by sawft99** [keepassxreboot/keepassxc#10229] opened 2024-01-25 15:42 UTC
## Overview
I deleted a synced group that is using keeshare. The group was set to 'synchronized'. When I go to create a group and import the keeshare, it says it was successful but there are no entries. The keeshare file I was using was still the same size and did not get modified while deleting or exporting. If I open it as an independent database it shows up fine. I've also tried using a signed and non signed keeshare file with no change.

## Steps to Reproduce
1. Create a group in an existing database
2. Create a synchronized group (with a password)
3. Make a few entries if needed for examples
4. Delete the group
5. Create a new group and set to 'import' a keeshare file, enter password for it
6. Hit ok and see that there are no entries

## Expected Behavior
After importing the keeshare for the entries to show up. Switching to synchronized also overwrites the share databased to be blank

## Actual Behavior
Import is reported as successful but there are no entries

```
KeePassXC - Version 2.7.6
Revision: dd21def

Qt 5.15.10
Debugging mode is disabled.

Operating system: Windows 11 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.22631

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.19.3

```

Operating System: Windows
Windowing System: 11

**Comment by droidmonkey** [comment] 2024-01-25 19:03
Since you deleted the group (and all the entries under it), the database remembers that and considers any imported entries to be deleted and drops them. This is a known issue with keeshare, see #6477 which is a duplicate of this one.

**Closed as not planned by droidmonkey** 2024-01-25 19:03 UTC
