### ISSUE TITLE
Can I link a database to my system login credentials to be automatically unlocked on start up ?

### ISSUE THREAD

**Issue by Nokia808** [keepassxreboot/keepassxc#3206] opened 2019-06-02 08:37 UTC
Hi. This is a question but I did not find "Question" category to use it for it & for that I used "Feature request".

Dear, in Seahorse, we can link a database for login credential so that when user have to enter password  for it's account so as to launch to it's system at each boot or logout/login this login to account led that database to be unlocked automatically.

To be more clear, I use my 1st user account on my Linux Fedora 30 to login for my OS at each boot. I'm disabling automatic login, so that I must enter my sudo password at each boot to complete the entrance for my OS. So, can I make a database I select to be unlocked just when I enter my sudo password (my login credential) on login to my system ?

I'm using KeypassXC version 2.4.1 from my Fedora official repositories.

Is this possible on KeePassXC or not ? If not, then can you add it, kindly?

Thank you for your hard work to develop this great project & maintain it alive !

**Comment by droidmonkey** [comment] 2019-06-02 12:14
Please take a look at #2726. This functionality will be available in 2.5.0.

**Comment by innerand** [comment] 2019-10-27 21:47
@droidmonkey I'm afraid it doesn't get implemented by #2726 and I can`t find that feature in 2.5.0 

- #2726 would replace the system Keyring with KeePassXC. 

- Whereas the requested feature would be, that KeePassXC queries the password for a database from the system keyring. 

And this would be a really hard missed feature. I've currently something like this in the auto start : `secret-tool lookup 'keepass' 'default' | /usr/bin/keepassxc --pw-stdin ~foo.kdbx &> /dev/null &` and that sucks because it can't handle screen locks or suspend modes.

**Comment by droidmonkey** [comment] 2019-10-27 23:29
You are correct, I originally read the OP's post a different way. I prefer to close this issue and open a new one with your wording.

**Comment by droidmonkey** [comment] 2019-10-27 23:30
Actually this is a duplicate of #1404

**Closed by droidmonkey** 2019-10-27 23:30 UTC
Labels: discussion
