### ISSUE TITLE
Implement sync feature with other password managers: KWallet, Gnome Keyring, etc

### ISSUE THREAD

**Issue by MurzNN** [keepassxreboot/keepassxc#2679] opened 2019-02-04 08:51 UTC
Many systems have build-in password manages, that are deeply integrated into system and apps. For example, KDE have KWallet, that use most of KDE software, so KWallet it can't be replaced by other password manager and users still need to use it.

For solve this problem will be good to implement sync feature in KeePassXC that will sync stored passwords with external storage on every change. 

With this feature users will can use KeePassXC as main storage for all passwords, and continue use systems and apps that can use only build-in password managers.

**Comment by MurzNN** [comment] 2019-02-04 08:52
For KWallet we can add/update/delete passwords via Dbus commands:
```
org.kde.KWallet.readEntryList
org.kde.KWallet.writeEntry
org.kde.KWallet.writePassword
```

**Comment by phoerious** [comment] 2019-02-05 15:36
Duplicate of #1403.

**Closed by phoerious** 2019-02-05 15:36 UTC
Labels: new feature
