### ISSUE TITLE
Passphrase generator: word separator does not replace space

### ISSUE THREAD

**Issue by ZJaume** [keepassxreboot/keepassxc#1803] opened 2018-03-31 16:45 UTC
When setting a word separator in the passphrase generator it does not replace the space separator with that separator. It only appends the new separator.
## Expected Behavior

When a word separator is introduced, it replaces space separator between words.

## Current Behavior

When a word separator is introduced, it is appended to the existing space separator between words.

![screenshot](https://user-images.githubusercontent.com/11339330/38165441-eeea152c-3502-11e8-87f9-326c63ae074d.png)

## Possible Solution

Only insert space separator between words if word separator field is empty.

## Steps to Reproduce (for bugs)

1. Go to passphrase generator
2. Fill the separator field with any character

## Context

For now I am removing space separator manually.

## Debug Info

KeePassXC - 2.3.1
Revision: 2fcaeea

Libraries:
- Qt 5.10.1
- libgcrypt 1.8.2

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 4.15.14-1

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by TheZ3ro** [comment] 2018-03-31 19:52
Seems that in the input field you have ` _` (space underscore).
When you are changing the separator note that in the input field there is already a space (since it's the default separator), so if you want only an underscore you need to delete the field.

I would say it's an expected behavior since we are allowing multi-character separator. Should we limit the separator to 1 char only?

**Comment by ZJaume** [comment] 2018-03-31 20:30
Oh! I'm very sorry! I have been using passphrase generator since months and never noticed the space was there :sweat_smile:. You can close the issue

**Comment by droidmonkey** [comment] 2018-03-31 21:09
This could be fixed by selecting the whole field when you focus on it. Similar to how we should handle password fields.

**Closed** 2018-03-31 21:08 UTC
