### ISSUE TITLE
Drag and Drop stops working from time to time on Mac 2.6.2

### ISSUE THREAD

**Issue by t3easy** [keepassxreboot/keepassxc#5636] opened 2020-10-30 16:08 UTC
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Even after reinstall the App, drag and drop stops working after some time.
The problem comes back.
Related to:
#5620 
#5621

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Reinstall KeepassXC
2. Drag and drop works
3. Work with KeepassXC
4. Close the database
5. Reopen
6. After some time, drag and drop stops working.
7. Reinstall KeepassXC
8. D&d works again

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Drag and drop works continuously

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Drag and drop stops after some time

## Context
[NOTE]: # ( Give us any additional information you may have. )
Dark mode is on
Switching don't does not help

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.2
Revision: e9b9582

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS

**Comment by droidmonkey** [comment] 2020-10-30 16:17
Ugh why only mac?

**Comment by droidmonkey** [comment] 2020-10-31 13:00
I just tested this rather extensively using 2.6.2 on macOS 10.15, could not reproduce drag/drop issues at all. Even when holding ALT to create copies. Everything worked as expected. Unless you can precisely narrow down how this happens we cannot reproduce it.

**Comment by t3easy** [comment] 2020-10-31 17:22
Maybe it's related to my other issue, that is breaks after some crashes.

**Comment by f0x1sland** [comment] 2020-10-31 21:29
I have the same problem :( I don't know how this happens.. Any ideas? It worked at the begin too.

KeePassXC - Version 2.6.2
Revision: e9b9582

Qt 5.15.1
Debugging mode is disabled.

Operating system: macOS 10.15
CPU architecture: x86_64
Kernel: darwin 19.6.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.6

**Comment by Serret** [comment] 2020-11-03 11:48
I have the same issue on macOS. Drag and Drop simply doesn't work. I tried close and reopen KeePassXC but it doesn't solve this issue.

macOS: 10.15.7
KeePassXC: 2.6.2

**Comment by t3easy** [comment] 2020-11-03 12:21
Temporary solution is to reinstall the app once it don't work anymore. Than it works for some time.

**Comment by droidmonkey** [comment] 2020-11-03 12:59
We need a lot more help to narrow down this issue. Does the drag/drop come back after restarting your mac or log off/on? Does it come back ever again without reinstall? Do you receive any error messages or warnings from mac?

**Comment by brad2014** [comment] 2020-11-03 15:46
I see it also.   Entries are not draggable for me.

- Starting and stopping KeePassXC does not fix it. 

KeePassXC - Version 2.6.2
Revision: e9b9582

Qt 5.15.1
Debugging mode is disabled.

Operating system: macOS 10.15
CPU architecture: x86_64
Kernel: darwin 19.6.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.6

**Comment by rennefJ** [comment] 2020-11-03 21:04
I am seeing the same issue. 
I uninstalled and reinstalled via homebrew and that did not fix it for me.
> KeePassXC - Version 2.6.2
>Revision: e9b9582
>Qt 5.15.1
>Diagnosemodus ist deaktiviert.
>Betriebssystem: macOS 10.15
>CPU-Architektur: x86_64
>Kernel: darwin 19.6.0
>Aktivierte Erweiterungen:
>- Auto-Type
>- Browser-Integration
>- SSH-Agent
>- KeeShare (bestätigtes und unbestätigtes Teilen)
>- YubiKey
>- TouchID

>Kryptographische Bibliotheken:
>libgcrypt 1.8.6

**Comment by droidmonkey** [comment] 2020-11-03 21:50
Unless you have substantive information we don't need anymore me toos

**Comment by t3easy** [comment] 2020-11-03 22:33
> We need a lot more help to narrow down this issue. Does the drag/drop come back after restarting your mac or log off/on? Does it come back ever again without reinstall? Do you receive any error messages or warnings from mac?

@droidmonkey No, even if I restart the Mac D&D don't come back. I can't remember it ever came back without reinstall the app by just copy it from the dmg.
If you tell me which logs you could need, I'll try to provide them.

**Comment by droidmonkey** [comment] 2020-11-04 04:08
Can you create a new database and take a video of your experience? I want to know where it is breaking down and that can help.

**Comment by rennefJ** [comment] 2020-11-04 08:41
It was not working with my regular database, so I created a new test database  as suggested. 
And to my surprise D&D now works on the newly created database but also in my regular database where it was not working before. I opened and closed the test database a few times and restarted the App two times and could not get it to "break". I did not reinstall in the process or reboot in between. 
I have a video of me creating the test database that I can share, but since all is working its probably not of much value.

**Comment by droidmonkey** [comment] 2020-11-04 11:55
That is certainly a surprise!

**Comment by Serret** [comment] 2020-11-04 18:27
I'm not sure whether it's relevant or not.
But from yesterday to today, it stopped working again.

#### Usage from yesterday to today:
- Used the same database.
- I locked the mac and it went to sleep, several times.
- No reboots.
- No reinstalls.
----

#### Using the demo database
- I downloaded the demo database.
- Opened the database in a new tab. (without closing the original database)
- Tried dragging an entry.
- Still didn't work.

I tried repeating the steps above after closing the original database and closing the application. But the result was the same.

**Comment by droidmonkey** [comment] 2020-11-04 18:49
Can you answer my questions above?

**Comment by rennefJ** [comment] 2020-11-04 19:37
> When it was broken, were you able to drag entry lines at all? Was the broken part the drag or the drop?
No, no dragging possible at all. When you click and hold, the cursor moves but the entry does not move at all.

After my testing this morning, I deleted the test database and rebooted for work. When I logged back in to my personal account D&D had stopped working again. This time I figured I download the demo database and test with that. I could not open the Demo database for some reason, but after I dismissed the open dialogue for the demo database D&D was working again my still opened personal database!

Keepassxc gets opened automatically when I log-in to my account. Could it be an issue with the state restoration, when the app gets closed on logout and restarted on log-in?

**Comment by Serret** [comment] 2020-11-04 19:38
Not sure if this is the desired upload method, please let me know if you prefer me to upload it elsewhere or if you'd like to see any other behaviour/usage.

(had to zip the .mov file)
[screen recording.zip](https://github.com/keepassxreboot/keepassxc/files/5490117/screen.recording.zip)

**Comment by droidmonkey** [comment] 2020-11-04 22:43
Well this is good news (for me) because that means my fix to the drop code didn't cause this problem. This is most definitely Qt related.

**Comment by yonkoma** [comment] 2020-11-09 14:38
It looks like [this is](https://bugreports.qt.io/browse/QTBUG-86786) probably the corresponding ticket. So it should be fixed in the upcoming 5.15.2 release.

**Comment by droidmonkey** [comment] 2020-11-09 15:18
Good thing they tested their "fix"

**Comment by laetitiaR5962** [comment] 2020-11-16 09:58
I have the same problem. I follow this issue to see the "fix".

**Comment by luisfontes19** [comment] 2020-11-20 17:28
+1. Just stopped working... Closing the database, closing the app doesn't work. 
Reinstall made it work again, thanks for the tip :)

**Comment by elnumnum** [comment] 2020-11-22 14:33
HI

I also have the problem with on my Mac running macOS 10.16 and KeePassXC - Version 2.6.2
I had the problem too when it was running macOS 10.15 

I DONT have the problem on :
- a mac running macOS High Sierra (10.13) and KeePassXC - Version 2.6.2
- a mac running macOS 10.15 and KeePassXC - Version 2.5.4

**Comment by droidmonkey** [comment] 2020-12-12 14:52
This was fixed in Qt 5.15.2 which will be released under KeePassXC 2.6.3

**Closed** 2020-12-12 14:52 UTC
Labels: Qt Bug, platform: macOS
