### ISSUE TITLE
Can't open database on flatpak after version 2.7.8

### ISSUE THREAD

**Issue by shellheim** [keepassxreboot/keepassxc#10676] opened 2024-05-06 15:26 UTC
## Overview
[TIP]:
[NOTE]: When I enter the password to my database it shows up for a fraction of a second and then I am back to the password prompt.

## Steps to Reproduce

1. Download the latest keepassxc as flatpak
2. Try to open a database by entering its password 

## Expected Behavior
The database opens

## Actual Behavior
The database is shown for a split second and then the its locked again. The user is thrown back to the password prompt.

## Context
[NOTE]: Here's a [video](https://github.com/keepassxreboot/keepassxc/assets/116480892/42feca29-e990-4837-8971-f048b8e66274) showcasing the bug.

[NOTE]:
KeePassXC - 2.7.8
Revision: f6757d3

[NOTE]: 
Operating System: Linux
Desktop Env: KDE
Windowing System:Wayland

**Comment by DamienGombaultRecia** [comment] 2024-05-06 15:31
I confirm the same behavior with KeePassXC Flatpak version 2.7.8.
OS : Fedora Kinoite 40 (KDE/Wayland)

**Comment by nopiz** [comment] 2024-05-06 15:33
I can confirm on Fedora 39 (GNOME/Wayland)

**Comment by shellheim** [comment] 2024-05-06 15:36
@DamienGombaultRecia @nopiz I think both of you are also on revision f6757d3?

**Comment by phoerious** [comment] 2024-05-06 15:38
I can indeed reproduce this.

**Comment by DamienGombaultRecia** [comment] 2024-05-06 15:39
Yes, from FlatPak source  : https://github.com/flathub/org.keepassxc.KeePassXC/commit/1a310838607032ef666cb14fbac4f4985d2a8b10

```
sources:
      - type: git
        url: https://github.com/keepassxreboot/keepassxc.git
        tag: 2.7.8
        commit: f6757d35aded625318e34ec745583604c814b7c3
```
```

FlatPak commit :
    Commit: ff056bcc994fd3b384dd6f57eb74cf3f8989fcdc00f9a0dc7bb8081277982a6a
    Parent: b74e3a1fa80097e66f56f09f170ebd53e16f6021713f4930bc4b52140a41f628
   Subject: Bump to 2.7.8 (1a310838)
      Date: 2024-05-06 10:37:43 +0000
   History: 
```

**Comment by phoerious** [comment] 2024-05-06 15:42
It's indeed a Flatpak-specific bug. Doesn't happen with the AppImage or Snap.

**Comment by shellheim** [comment] 2024-05-06 15:44
You can temporarily fix the problem by rolling back to 2.7.7 until the bug is fixed. 

```sh
flatpak update --commit=36cc2d7aa2eb5e377e97b816f16480f5c7deb8a04c5cd2f8f3d4b74a2abd8ab6 org.keepassxc.KeePassXC
```

**Comment by droidmonkey** [comment] 2024-05-06 16:05
Can you screenshot your Application Settings -> Security tab

**Comment by marciorodrigues** [comment] 2024-05-06 16:12
Same problem in Debian, KDE, Xorg.
![image](https://github.com/keepassxreboot/keepassxc/assets/33334190/3f101e3e-3512-4ab5-827a-38e1023a2f4e)

**Comment by phoerious** [comment] 2024-05-06 16:13
I don't know where this comes from, but the default for database inactivity lock seems to be 10 seconds, but with a fresh profile, it's way less than that. When I go to settings and click OK, the database no longer auto-locks instantly, even without changing any settings.

**Comment by marciorodrigues** [comment] 2024-05-06 16:17
> I don't know where this comes from, but the default for database inactivity lock seems to be 10 seconds, but with a fresh profile, it's way less than that. When I go to settings and click OK, the database no longer auto-locks instantly, even without changing any settings.

I disabled the "Lock databases after minimizing the window" option and it worked again.

**Comment by phoerious** [comment] 2024-05-06 16:20
I don't think it's that setting. It works for me with and without that setting. The problem seems to be the auto lock timeout, which is <1s if you haven't saved your keepassxc.ini.

**Comment by shellheim** [comment] 2024-05-06 16:21
> Can you screenshot your Application Settings -> Security tab

@droidmonkey 

![06-21:50:33](https://github.com/keepassxreboot/keepassxc/assets/116480892/affe06c1-814e-4183-835b-282fd55eca62)

**Comment by marciorodrigues** [comment] 2024-05-06 16:45
After I managed to access the vault, I noticed that several options were different from what I normally use. The screen layout was completely different, the theme was different, it was showing the password and hiding the notes and username, the lock time was also different and when I clicked close it was closing instead of minimizing.
I'm going to reset everything and reconfigure it to see if it works.

The username column is hidden, but the option is to show it. It appears normally on the lower screen.
![image](https://github.com/keepassxreboot/keepassxc/assets/33334190/fc5a0335-d269-49e8-9bd3-a770ce342572)

**Comment by CodeShakingSheep** [comment] 2024-05-06 16:48
Same problem on ZorinOS, Flatpak after update to version 2.7.8.

> I don't know where this comes from, but the default for database inactivity lock seems to be 10 seconds, but with a fresh profile, it's way less than that. When I go to settings and click OK, the database no longer auto-locks instantly, even without changing any settings.

Thanks, this worked for me. Afterwards, I could open my database. Indeed, the layout is really different than before.

**Comment by obispobruno** [comment] 2024-05-06 17:05
Same problem.

Fedora 40 Sericea (Sway Atomic)
Using latest flatpak 2.7.8 commit ff056bcc994fd3b384dd6f57eb74cf3f8989fcdc00f9a0dc7bb8081277982a6a

**Comment by droidmonkey** [comment] 2024-05-06 17:07
Thanks, no need for me too. Use the thumbs up on the main post

**Comment by trafuga** [comment] 2024-05-06 17:39
Linux Mint 21.2 Cinnamon using latest flatpak 2.7.8

**Comment by zroug** [comment] 2024-05-06 17:42
With Flatpak and version 2.7.8 my `keepassxc.ini` contains some strange entries like

```ini
ApplicationTheme=true
MinimizeToTray=monochrome-light
TrayIconAppearance=true
```

For comparison, the previous version had

```ini
ApplicationTheme=auto
MinimizeToTray=true
TrayIconAppearance=monochrome-light
```

So maybe the keys are mixed up somehow.

Edit:

The KeeShare key pair that is stored with key `Own` got replaced with `true` too.

```ini
[KeeShare]
Own=true
```
instead of

```ini
[KeeShare]
Own="<?xml version=\"1.0\"?><KeeShare><PrivateKey>...
```

So without a backup this one might be permanently lost if it isn't stored elsewhere. Otherwise most things didn't change except for some smaller things like `HideUsernames`.

**Comment by ps-spark** [comment] 2024-05-06 17:45
> Linux Mint 21.2 Cinnamon using latest flatpak 2.7.8

Same here. After downgrade to previous version, it's working again. It looks like the UI opens for 400ms then it locks again without any error message.

**Comment by droidmonkey** [comment] 2024-05-06 18:45
I reverted the Flatpak release to 2.7.7

**Comment by Vovchikan** [comment] 2024-05-06 18:47
Same on Kubuntu 23.10 with flatpak version

**Comment by phoerious** [comment] 2024-05-06 19:42
> So without a backup this one might be permanently lost if it isn't stored elsewhere. Otherwise most things didn't change except for some smaller things like `HideUsernames`.

The key isn't used for anything.

**Comment by droidmonkey** [comment] 2024-05-07 01:55
Fixed https://github.com/flathub/org.keepassxc.KeePassXC/pull/128

Apologies for the inconvenience with regards to your settings being wiped. This was a failure of a testing on my part.

**Closed as completed by droidmonkey** 2024-05-07 01:55 UTC
Labels: distribution: Flatpak

**Comment by shellheim** [comment] 2024-05-07 06:03
Hope this isn't another xz type bug 👀

**Comment by shellheim** [comment] 2024-05-07 06:10
Okay, so there is another problem now. I can't copy or paste my username/password from an entry in the database.

**Comment by shellheim** [comment] 2024-05-07 06:26
Also, if you have just updated. Go to settings > security and change the clear clipboard from 1 sec to 10 sec or more.

**Comment by phoerious** [comment] 2024-05-07 07:22
I recommend you do `rm ~/.var/app/org.keepassxc.KeePassXC/config/keepassxc/keepassxc.ini` and reconfigure everything from scratch. There are various other switches that have been flipped, such as lock on screen lock etc.

**Comment by shellheim** [comment] 2024-05-07 08:16
Thanks @phoerious that also fixed the small font issue I was having.
