### ISSUE TITLE
[feature request] multiple auto-type sequences per entry

### ISSUE THREAD

**Issue by lcapriotti** [keepassxreboot/keepassxc#739] opened 2017-07-03 15:57 UTC
Each entry supports one auto-type sequence, either default or custom. Ideally each entry should allow multiple auto-type sequences, as to achieve this cloning and modifying entries is needed, with possible misalignment if further changes are needed (pwd for example).

## Expected Behavior
Multiple auto-type sequences should be possible for the same entry.

## Current Behavior
Only one auto-type sequence can me configured per entry.

## Possible Solution
Each auto-type sequence defined for an entry should be selectable via a submenu instead of a single "Perform Auto-Type (Ctrl-V)" menu entry. Standard sequences like auto-type username/ auto-type password/auto-type username&password may be default sequences, with possibility to add custom ones.

## Steps to Reproduce (for bugs)
N/A

## Context
There are sites where you may be asked to provide username and passwords or just username or passwords to perform specific actions, currently there is no easy way to use auto-type to support the latter other than cloning.

## Debug Info
N/A

**Comment by phoerious** [comment] 2017-07-03 16:00
Duplicate of #736.

You can have multiple auto-type sequences per entry.

**Closed by phoerious** 2017-07-03 16:00 UTC
