### ISSUE TITLE
[Search] - Viewing expired passwords

### ISSUE THREAD

**Issue by TheLargeFries** [keepassxreboot/keepassxc#3499] opened 2019-09-02 16:59 UTC
[TIP]:  # ( Provide a general summary of the feature in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Summary
As an end user, I have many folders to organize my password database. I notice when passwords expire, I am not prompted to change the password, nor is there an easy way for me to view ALL passwords in a single list to view the expired password list. I would love to see an option to search for all expired passwords, to easily identify all entries that have expired

## Desired Behavior
Click a single button, to view all expired passwords. 

## Possible Solution
Ideally, placing this on the top menu option bar, and changing colors if there are any expired passwords, to draw the user's attention to it. So if no expired passwords, display a normal icon, if expired passwords exist, color it red, or change icon to something else

For clarity, "top menu option bar":
![image](https://user-images.githubusercontent.com/52138656/64127799-3d093680-cd81-11e9-94b1-1af2e084edb4.png)

## Context
I would like to keep all passwords changing every 6-12 months, and this feature would help remind me to do so.

## Workaround
You can search for "*", and sort by expired as a workaround - so this should likely be considered a low priority feature request, though certainly a "nice to have"!

**Comment by dstrelnikov** [comment] 2019-11-15 16:05
I really like it!

It would be also nice to emphasise somehow the "expired" and "expires soon" entries.

**Comment by droidmonkey** [comment] 2019-11-15 16:40
I missed this one. It is a duplicate of #551

**Closed** 2019-11-15 16:40 UTC
Labels: new feature
