### ISSUE TITLE
Locking the DB after locking the lap / hibernating

### ISSUE THREAD

**Issue by microcreators** [keepassxreboot/keepassxc#384] opened 2017-03-09 09:55 UTC
## Expected Behavior
I use keepassXC pretty often during a day. I'd love to see a feature of automatically locking the DB after I'm done, which in my case usually is simply closing the lid or locking the account. I'm on OSX, but I imagine this would apply to other systems as well.

## Current Behavior
Currently, if the file was open and a laptop went to sleep (automatically, by closing it, by hibernating, etc), the file stays wide open and accessible upon coming back to the system. This is IMO a potential security breach. Especially if a device is stolen and / or an account taken over.

## Possible Solution
Detect a device "going to sleep" and account locking. Lock the file immediately upon detecting it.
Original Keepass does it. 

## Context
Trying to harden security a bit in case of unfortunate event like stealing hardware. Trying not to expose keepass file if I'm unlocking the laptop next to someone and keepassXC was open.

## Your Environment
* KeePassXC version/commit used: 2.1.3
* Qt version (e.g. Qt 5.3): 5.8.0
* Compiler (e.g. Clang++3.6.0): no idea ;)
* Operating System and version: OSX 10.11.6

**Comment by phoerious** [comment] 2017-03-09 10:03
Duplicate of #135.

**Closed by phoerious** 2017-03-09 10:03 UTC
