### ISSUE TITLE
status on KDBX 4 support?

### ISSUE THREAD

**Issue by Diapolo** [keepassxreboot/keepassxc#647] opened 2017-06-15 09:43 UTC
I saw there was a pull some time ago to support the newly introduced KDBX 4 format (see http://keepass.info/help/kb/kdbx_4.html), but I'm wondering what progress is currently made in supporting that? I want to switch from Windows to Ubuntu in the near future, so reading my KeePass database is essential for me.

Thanks,
Dia

**Comment by TheZ3ro** [comment] 2017-06-15 10:09
Duplicate of #148, please use that issue. Also we don't have any ETA on KDBX4 support, it will be available in the 2.3 version.

**Closed by TheZ3ro** 2017-06-15 10:09 UTC
