### ISSUE TITLE
Feature Request - Dark Theme

### ISSUE THREAD

**Issue by Mascall** [keepassxreboot/keepassxc#2338] opened 2018-09-29 21:14 UTC
Hi sorry if this is in the wrong section, first time using GitHub and im sure this may have been asked previously...

I would like to request a Dark Theme option if possible for the Windows version of KeePassXC

Thanks

**Comment by tromlet** [comment] 2018-10-31 16:57
Given that Mac OS X 10.14's magnum opus feature was, in fact, a dark theme... I would second this. It would be nice to see a nice dark theme for all platforms.

**Comment by droidmonkey** [comment] 2018-10-31 17:33
Duplicate of #804. Qt needs to release 10.12 which will support Mojave dark theme...

**Closed by droidmonkey** 2018-10-31 17:33 UTC
