### ISSUE TITLE
searchbar is only visible in fullscreen

### ISSUE THREAD

**Issue by iBilley** [keepassxreboot/keepassxc#3644] opened 2019-10-20 21:51 UTC
running manjaro linux gnome stable branch, keepass commnunity KeePassXC (keepassxc)  2.4.3-1

![Screenshot from 2019-10-21 00-06-15](https://user-images.githubusercontent.com/56536098/67167268-01114b80-f398-11e9-9689-d93f3de50320.png)

and rezised down
![Screenshot from 2019-10-21 00-06-22](https://user-images.githubusercontent.com/56536098/67167273-0f5f6780-f398-11e9-97e9-66e7eab58173.png)

## Expected Behavior
when resizing windows the seachbar should scale below the menu, or get a more prominent place to the left (where most eyeballs are focused )

**Comment by droidmonkey** [comment] 2019-10-20 21:55
Not sure what you are referring to. Please provide a screenshot.

**Comment by iBilley** [comment] 2019-10-20 22:20
updated, hope this makes it clear the search is currently all the way to the right. at least at my system. i think thats the problem, it does not show up when i start or make the window small. seach is the first i use so maximize windows first is a real hassle.

**Comment by droidmonkey** [comment] 2019-10-20 23:11
We don't recommend running with the icon titles if possible.

**Comment by droidmonkey** [comment] 2019-10-20 23:12
Either way this is a duplicate of #505

**Closed by droidmonkey** 2019-10-20 23:12 UTC
Labels: more info needed
