### ISSUE TITLE
Upgrade via PPA in LinuxMint 18.3 64-bit failed (libsodium)

### ISSUE THREAD

**Issue by rodoviario** [keepassxreboot/keepassxc#1555] opened 2018-02-28 11:55 UTC
Tried to update via package manager, but failed with error:
```
Preparando para desempaquetar .../libsodium23_1.0.16-0ppa3~xenial1_amd64.deb ...
Desempaquetando libsodium23:amd64 (1.0.16-0ppa3~xenial1) ...
dpkg: error al procesar el archivo /var/cache/apt/archives/libsodium23_1.0.16-0ppa3~xenial1_amd64.deb (--unpack):
 intentando sobreescribir `/usr/lib/x86_64-linux-gnu/libsodium.so.23.1.0', que está también en el paquete libsodium18:amd64 1.0.16-0ppa1~xenial1
dpkg-deb: error: el subproceso copiado fue terminado por la señal (Tubería rota)
Procesando disparadores para libc-bin (2.23-0ubuntu10) ...
Se encontraron errores al procesar:
 /var/cache/apt/archives/libsodium23_1.0.16-0ppa3~xenial1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

Diggin a little found that libsodium23 (which fails to install) has the same file and version that libsodium18. If I try to uninstall libsodium18, it will remove programs, including (ffmpeg, gstreamer, obs-studio, openshot-qt, transmageddon, vidcutter, wiff, libav-tools, flowblade). I guess they all use another ppa which also includes the library.

Tryed to remove the file and do apt install -f but didn't work (so restored the file by hand)

## Expected Behavior

libsodium18 and libsodium23 should not conflict

## Current Behavior

libsodium18 and libsodium23 have a common library that refuses to install (overwrite)

## Possible Solution

Ideas (sorry, don't know anything about how apt/dpkg works)
* libsodium18 and libsodium23 should avoid overwritting but continue the install
* may be they should be marked as the same thing somewhere
* other option would be to actually overwrite the library and move on

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Debug Info

KeePassXC - VERSION
Revision: REVISION

Libraries:
- LIBS

Operating system: OS
CPU architecture: ARCH
Kernel: KERNEL

Enabled extensions:
- EXTENSIONS

**Comment by phoerious** [comment] 2018-02-28 12:08
Duplicate of #1545

**Closed by phoerious** 2018-02-28 12:08 UTC
