### ISSUE TITLE
Empty space in the username ui input field causing inconsistent look

### ISSUE THREAD

**Issue by tgurr** [keepassxreboot/keepassxc#5635] opened 2020-10-30 13:15 UTC
## Overview

![ksnip_20201030-140657](https://user-images.githubusercontent.com/414984/97708800-a38b0100-1ab9-11eb-958c-13d030139ac9.png)

## Steps to Reproduce
1. Create or edit an entry
2. see a strange space in the username ui input field

## Expected Behavior
See a consistent behaviour across all input fields

## Notes
This seems to be only present in the Linux build, on Windows I do get the strange empty space on every input field, but at least it looks consistent, see

![ksnip_20201030-141311](https://user-images.githubusercontent.com/414984/97709080-109e9680-1aba-11eb-89c1-8b222a45dc01.png)

KeePassXC - Version 2.6.2
Revision: e9b9582
Qt 5.15.1

Operating System: Linux
Desktop Env: KDE
Windowing System: X11

**Comment by phoerious** [comment] 2020-10-30 13:35
Duplicate of #5601.

**Closed by phoerious** 2020-10-30 13:35 UTC
Labels: bug
