### ISSUE TITLE
Display error in Toolbar with 2.6.0

### ISSUE THREAD

**Issue by gyli** [keepassxreboot/keepassxc#4988] opened 2020-07-08 19:52 UTC
## Overview
<img width="804" alt="Screen Shot 2020-07-08 at 3 45 47 PM" src="https://user-images.githubusercontent.com/2060045/86963270-3df1be00-c132-11ea-9e7e-a70e26355b0a.png">

## Steps to Reproduce
1. Settings -> Toolbar button style -> Choose anyone with Text
2. Click arrow icon to display more buttons

## Context
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.0
Revision: 0765954

Qt 5.15.0
Debugging mode is disabled.

Operating system: macOS 10.15
CPU architecture: x86_64
Kernel: darwin 19.5.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.5

[NOTE]:
Operating System: macOS
Windowing System: X11

**Comment by droidmonkey** [comment] 2020-07-08 22:04
This is most definitely a Qt bug

**Comment by phoerious** [comment] 2020-07-09 07:14
This could be due to the toolbar background being transparent so the window background can be seen.

**Comment by timodenissen** [comment] 2020-07-10 07:24
Similar issue on Ubuntu 20.04 using the PPA with KeePassXC v2.6.0.

[https://www.bilder-upload.eu/bild-169c14-1594365815.png.html](url)

**Comment by phoerious** [comment] 2020-07-10 07:32
That's a duplicate of pinned issue #4963

**Comment by droidmonkey** [comment] 2020-08-03 01:57
I cannot reproduce this on Catalina.

**Closed by droidmonkey** 2020-08-03 01:57 UTC
Labels: bug
