### ISSUE TITLE
Changes in Notes lost while adding TOTP

### ISSUE THREAD

**Issue by bluppfisk** [keepassxreboot/keepassxc#9042] opened 2023-01-30 23:54 UTC
## Overview

When editing an entry, if you have anything (unsaved) in Notes while setting up TOTP, the notes field will be cleared when finishing TOTP set-up.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. open an entry with no TOTP set up
2. put something in the notes field, do NOT save
3. from the menu, select Entries > TOTP > Set up TOTP
4. Finish setting up TOTP
5. Despair as the notes field is cleared (I temporarily pasted my TOTP recovery codes in there)

## Expected Behavior

Notes field is not cleared during TOTP set-up

## Actual Behavior
Notes field is irrevokably cleared during TOTP set-up

## Context
n/a

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.4
Revision: 7729648
Distribution: Snap

Qt 5.15.5
Debugging mode is disabled.

Operating system: Ubuntu Core 20
CPU architecture: x86_64
Kernel: linux 6.1.7-060107-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.12.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Gnome
Windowing System: Wayland

**Comment by droidmonkey** [comment] 2023-01-31 00:29
Duplicate of #6838

**Closed as not planned by droidmonkey** 2023-01-31 00:29 UTC
Labels: duplicate
