### ISSUE TITLE
Shutdown blocked on MacOS 10.14

### ISSUE THREAD

**Issue by andreas-p** [keepassxreboot/keepassxc#4057] opened 2019-12-23 18:05 UTC
V2.5.1 is installed on OSX 10.14.6 from the binary bundle, configured to minimize instead of closing the app. Database is opened, window minimized.

When shutting down the machine, the keepassxc window will restore, but nothing more happens until the system claims "Can't shutdown because keepassxc won't terminate, close it manually" after 15s or so.

**Comment by droidmonkey** [comment] 2019-12-23 18:43
Do you have automatically save after every change and/or save on exit enabled?

**Comment by phoerious** [comment] 2019-12-23 19:14
Please do not delete the issue template.

**Comment by droidmonkey** [comment] 2019-12-23 20:50
Could not replicate on MacOS 10.15.

**Comment by weslly** [comment] 2019-12-23 23:27
I can reproduce it on 10.14 when I turn the "minimize instead of exit" setting on. It seems to be overriding the "Quit" menu item when you right click the icon from the Dock instead of using the application menu.

I'm not sure if using the 'cmd-W' key binding to "close database" instead of the default close window behavior has something to do with it. I'll take a look at this.

**Comment by andreas-p** [comment] 2019-12-24 12:26
> Do you have automatically save after every change and/or save on exit enabled?
Autosave is enabled, no unsaved data.

**Comment by andreas-p** [comment] 2019-12-24 12:28
> Could not replicate on MacOS 10.15. Although I did notice that the minimize instead of app exit setting does not work on MacOS.

Seems that KeepassXC works just the opposite on 10.14 vs 10.15: on 10.14, "minimize instead of exit" works (this is essential for me, I hate to re-type the passphrase every time I hit the wrong button) , but prevents shutdown.

**Comment by mbedded** [comment] 2019-12-29 08:19
I have the same issue that the Mac does not shutdown when KeepassXC is not closed by hand (CMD + Q). OS X complains that a program is blocking the shutdown. It does not matter if there are unsaved changes or not. The window state (visible/closed) has no effect either.

- I am using OS X 10.15.2 (Catalina)
- I have activated the setting "Minimize instead of app exit"

**Comment by andreas-p** [comment] 2020-01-17 18:49
Problem remains with 2.5.2. Small difference: when initiating shutdown, the system will almost immediately claim "KeepassXC has interrupted shutdown".

**Comment by wolframroesler** [comment] 2020-04-13 15:21
Probably same as #3944

**Comment by ddobrev** [comment] 2020-04-15 00:43
KeePassXC is otherwise perfect, especially with the feature for 2FA. However, this problem is really annoying and occurs every single day, even with 2.5.4 (I use macOS 10.15.4). Have any of the developers been able to reproduce it?

**Comment by ddobrev** [comment] 2020-04-15 00:44
That is — the issue isn't specific to macOS 10.14.

**Comment by droidmonkey** [comment] 2020-04-15 03:28
Please read the whole issue thread, we describe what the situation is.

**Closed** 2020-09-28 01:44 UTC
Labels: bug, platform: macOS
