### ISSUE TITLE
Hotkey for Opening KeePassXC and focus Search

### ISSUE THREAD

**Issue by solariz** [keepassxreboot/keepassxc#1986] opened 2018-05-22 18:27 UTC
*feature request*

I use Keepass also for Storing Information like Creditcard or Wallet Addresses. It would be very very useful if there could be a hotkey defined in XC to open the Main GUI and place focus in Quick Search box to quickly search and access Information.

Thanks!

**Comment by phoerious** [comment] 2018-05-23 07:57
You can use Ctrl+F to focus the search, which I think should be easy enough.
But perhaps we can do something with the focus after unlocking a database or so.

**Comment by solariz** [comment] 2018-05-23 08:06
What I mean is a global System Hotkey to bring the minimized UI to Front if I am in another app.
Currently the Workflow require me to search the tiny tray Icon, Click it and than use CTRL F to search.
I the Keepass Client there is a global Hotkey like CTRL-ALT-P for opening the Password Manager nomatter in which app you are.

**Comment by phoerious** [comment] 2018-05-23 08:13
This looks like it's mostly a duplicate of #99 then.

**Comment by solariz** [comment] 2018-05-23 08:44
Yes duplicated.

Sorry to hear that it's a WONTFIX because actually a very common use of keepass :(

**Comment by phoerious** [comment] 2018-05-23 09:19
We are thinking about adding some command line flags, which can be bound to global hotkeys in your system settings, to do things like that. But native global hotkeys are really painful to implement cross-platform.

**Closed by phoerious** 2018-05-23 09:19 UTC
Labels: wishlist

**Comment by plissje** [comment] 2018-10-14 06:59
Hey guys,
Is there an update on this? Would love to have this feature as I'm missing this greatly :(

**Comment by waynebloss** [comment] 2018-10-14 20:30
The way it stands now is not terrible though. If you have KeePassXC setup to keep running in the system tray and if you have it set to start only a single instance, when you use your OS to create an application shortcut to just run `keepassxc` - it works pretty well. I just have to hit one extra `Ctrl+F` shortcut to focus on search - no big deal really.

Also, with this setup, if you leave the window with search focused - the next time you bring it up search is already focused.

With something like `xdotool` I can probably implement this feature myself.

**Comment by solariz** [comment] 2019-08-11 10:23
Another year passed, any updates on the Hotkey management?
I really like to move to keepass XC but this WONTFIX is a no go for me :(

So sadly.

**Comment by droidmonkey** [comment] 2019-08-11 13:12
This issue is a duplicate as mentioned above.

**Comment by xmokay** [comment] 2023-05-17 11:21
I reckon the cost to add this handy feature wouldn't be steep. It's a pity that it's not supported.

**Comment by CerebralFreeze** [comment] 2023-08-03 13:49
Use AutoHotkey to create a script for a global hotkey.  The script I use is below.  I use the upper left ` key (since I rarely use this key) to toggle show/hide KeePassXC.  Pretty handy.

† _I also use AutoHotkey to create a lot of other global hotkeys for programs like Microsoft Office and Chrome.  Pretty useful.  You should try it._

```
`:: 
If (WinExist("ahk_exe KeePassXC.exe") && WinActive("ahk_exe KeePassXC.exe"))					
	WinMinimize
Else
{
	Run C:\Program Files\KeePassXC\KeePassXC.exe
	WinActivate, ahk_exe KeePassXC.exe
}
Return
```



> Another year passed, any updates on the Hotkey management? I really like to move to keepass XC but this WONTFIX is a no go for me :(
> 
> So sadly.

**Comment by bee-eater** [comment] 2024-01-11 12:22
Also KeePassXC doesn't seem to have a plugin capability? For KeePass the plugin autotypesearch does a great job:

https://sourceforge.net/projects/autotypesearch/

![image](https://github.com/keepassxreboot/keepassxc/assets/34870259/efc0800c-bc69-4576-a681-60c63099ccaf)

It would be great to have a similar option in KeePassXC!

I was thinking about switching to KeePassXC but I already have too major points why I'm not going to:

1. Global hotkey for fast search
2. You can't use cmdline actions on an opened an unlocked database, right? You always have to provide the password in the arguments --> ??? How are you supposed to use this? Store the PW in the batch files?? For me it looks "unusable"...

For KeePass I just create a batch with the following content:
`%~dp0\..\KeePass\KeePass.exe` -entry-url-open -uuid:<uuid of entry>`

Excecuting it will open the URL of the entry including user and pw information (if database is unlocked and entry exists of course...). Very handy for SAP shorcuts etc...

**Comment by JSchimmelpfennig** [comment] 2024-09-25 14:07
This can be also done with Microsofts PowerToys Keyboard Manager!
![image](https://github.com/user-attachments/assets/1f00c36c-fa3d-4804-bf7c-bf7678b4b486)
![image](https://github.com/user-attachments/assets/581c9068-baa5-4ea5-bdfd-d317913141db)
