### ISSUE TITLE
[Suggestion] Exporting of groups 

### ISSUE THREAD

**Issue by neural-oD** [keepassxreboot/keepassxc#821] opened 2017-07-27 12:12 UTC
Hi 
In Keepass it's possible to export a group. I would suggest we add this feature to keepassxc. It's very helpful especially when trying to share things with others. If I've missed something and it does already do this, please point me in the right direction, cause I couldn't find this feature.

Thanks\

**Comment by neural-oD** [comment] 2017-07-27 12:32
Just checked now. Another implementation of this could be based on what is available now. At the moment, if you have two tabs with different databases, it's possible to move a group between those tabs/databases. What could work is that instead of just moving, if one could implement a context as to either move or copy. This could work quite nicely too I would say.

**Comment by weslly** [comment] 2017-07-27 16:42
Duplicate of #642

**Closed by weslly** 2017-07-27 16:42 UTC
