### ISSUE TITLE
Allow search to be a global search

### ISSUE THREAD

**Issue by felixfoertsch** [keepassxreboot/keepassxc#805] opened 2017-07-21 13:33 UTC
## Expected Behavior

Pressing CMD+F should move the cursor to the search box and search starting from the root node. Typing "Google" should find all occurrences of Google in the whole database.

## Current Behavior

Searching for a term takes into account the currently selected folder and searches only in there.

## Possible Solution

Return to the default KeePassX search behaviour. Or implement a toggle to switch between the two search styles.

## Context

I described the default KeePassX behaviour in "Expected Behaviour" .

The problem with the KeePassXC behaviour can be realised in the following workflow: if you manually look for credentials in a specific folder, this subfolder ist selected. Of course after login in, it stays selected.

If you then go back to KeePassXC after a while and try to *search* for credentials for another services, the previously selected folder is still selected, which results in a wrong search. You have to manually select the root node again to perform the correct search.

## Debug Info

KeePassXC - 2.1.4
Revision: cb283bb95ae559d044415f426f841c27bff383f0

Operating system: macOS
Version: 10.12.6
CPU architecture: x86_x64

Using:
- Qt 5.8.0
- libgcrypt 1.7.6

Extensions:
- KeePassHTTP
- Autotype
- Yubikey

**Comment by phoerious** [comment] 2017-07-21 13:35
This is already possible. Duplicate of #296

**Closed by phoerious** 2017-07-21 13:35 UTC
