### ISSUE TITLE
Open Database on startup is not working if database is synced with third party client

### ISSUE THREAD

**Issue by matecode** [keepassxreboot/keepassxc#1834] opened 2018-04-11 08:37 UTC
I Use KeepassXC 2.3.1 with Ubuntu 16.04 and I sync the database with SynologyDrive Client to my NAS, working regularly on two computers. I use "open last database on startup" option and i autostart keepassxc on system startup

## Expected Behavior

I expect the database to be open on startup, but it is not. If i open the database manually and stop keepassxc and reopen it, it works, so it seems that there is a connection to the sync with the third party client.

## Current Behavior

The database is not open on start of keepassxc

## Steps to Reproduce (for bugs)
1. install keepassxc for autostart on ubuntu 16.04 
2.install sync of databse with third party sync client
3."open database on startup" 
4.use database, shutdown pc
5.use the same setup on other pc
6.databse will not open on autostart of keepassxc

## Debug Info
KeePassXC - Version 2.3.1
Revision: 2fcaeea

Libraries:
- Qt 5.5.1
- libgcrypt 1.8.1

System: Ubuntu 16.04.4 LTS
CPU-Architektur: x86_64
Kernel: linux 4.13.0-38-generic

Libraries:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by droidmonkey** [comment] 2018-04-11 10:49
Does the database not open on both pcs? Also, all we do is look for the file where it last was. If KeePassXC starts BEFORE the drive sync is up and running then it won't be able to find the database to auto open. You probably need to add a delay to the XC startup.

**Comment by nekr0z** [comment] 2019-04-06 04:27
Could it be a duplicate of #430 maybe? I've had the same issue until I first closed keepasscx, from then on it worked as expected. The caveat here being that during PC shutdown keepassxc is closed in a way that prevents writing data about currently opened databases to config.

**Comment by droidmonkey** [comment] 2019-04-06 04:39
I'm actually going to close this since I received no feedback.

**Closed by droidmonkey** 2019-04-06 04:39 UTC
