### ISSUE TITLE
cli: add ability provide password non-interactively

### ISSUE THREAD

**Issue by cyphar** [keepassxreboot/keepassxc#1297] opened 2017-12-16 15:12 UTC
At the moment, `keepassxc-cli` commands require passwords to be input interactively. While you can just pipe into them, the interactive prompt means that parsing the output is more annoying than it really should be.

## Expected Behavior
Ideally we should have a `--password-file` field (which is the same as the `--key-file` field) where the password is sourced from (presumably we would only allow a single line). Users can make this usage secure by using FIFOs or process substitution -- which distinguishes it from the more naive `--password` field (which would expose the user's password through `/proc/*/cmdline`).

## Current Behavior
Currently users must input their password interactively.

## Possible Solution
Add a `--password-file` option to all commands (same as `--key-file`).

## Context
I'm scripting around `keepassxc-cli` in order to be able to use it to fill in my password with my Mutt configuration, but parsing the output with shell is more frustrating than it needs to be. Not to mention that the prompt format has changed, making my scripts quite fragile.

## Debug Info
KeePassXC - Version 2.2.2
Revision: 6d46717

Libraries:
- Qt 5.9.3
- libgcrypt 1.8.1

Operating system: openSUSE Tumbleweed
CPU architecture: x86_64
Kernel: linux 4.14.3-1-default

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

**Comment by cyphar** [comment] 2017-12-18 23:11
This would also be a good opportunity to refactor the existing sub-command code to remove the duplication of the `--key-file` option code (which is currently copied for all subcommands with slightly different handling when opening the database). Personally I think we should have a `DatabaseOpener` class for `cli` which is passed to each subcommand.

**Comment by louib** [comment] 2017-12-19 14:55
@cyphar a good first step for the `key-file` option would be to extract the option as a constant in the `Command` class. The slightly different handling is because of the `extract` command, and IIRC I think there's no way around that.

**Comment by liar666** [comment] 2018-08-22 12:43
Would a solution like the one I presented here, be secure enough?:
https://github.com/keepassxreboot/keepassxc/issues/2184#issuecomment-415017286

**Comment by louib** [comment] 2019-02-16 19:43
@cyphar the `--quiet` option has been added to the CLI already, which should make parsing the output easier. Can you give it a try?

**Comment by tangxinfa** [comment] 2019-04-25 06:50
In the previous version of keepassxc we can noninteractive add a entry by:

    echo -e 'MasterPassword\nEntryPassword\n' | keepassxc-cli add path/of/my/keepass-db-file test_entry -u test_user --url http://example.com -p

But today it not works, the added entry's password is empty.

keepassxc-cli's version is 2.4.1

**Comment by louib** [comment] 2019-04-25 15:21
@tangxinfa could you create a separate issue for that please?

**Comment by louib** [comment] 2019-04-25 21:08
@tangxinfa I was not able to reproduce with the current `develop` branch. Could you open a separate issue for that please?

**Comment by tangxinfa** [comment] 2019-04-26 04:12
@louib upgrade to 2.5.0, it works now, thanks.

**Comment by droidmonkey** [comment] 2019-04-26 11:33
Marking this as fixed in 2.5

**Closed** 2019-04-26 11:33 UTC
Labels: plugin: CLI

**Comment by jirib** [comment] 2020-11-11 12:02
Would it be possible to have a env var for password? Now I work around it this way `keepassx-cli show -p <file> <entry> <<< "${_KEEPASSXC_PASS}"` in `bash`, ie. puttig env var into stdin.
