### ISSUE TITLE
Application 'not responsive' after using browser password generator and closing

### ISSUE THREAD

**Issue by mgrandi** [keepassxreboot/keepassxc#8445] opened 2022-09-06 18:42 UTC
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

Pretty sure this goes here and not for the browser plugin

Anyway, the application no longer responds to clicks (as in it plays the windows 'alert' sound every time you try to interact with it, as if there is a modal window still present and you need to close it) when you use the password generator and close it 

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. go to website with input field
2. right click input field -> keepassxc-browser -> show password generator
3. close password generator
4. try to interact with the main keepassxc application
5. application isn't interact-able, plays windows 'alert' sound every time

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

the main application should be usable after closing the password manager

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

the main application cannot be interacted with and you have to right click the task / tray icon and right click -> quit

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.1
Revision: 5916a8f

[NOTE]: # ( Pick choices based on your environment )
Operating system: Windows 10 Version 2009 (windows 11)
CPU architecture: x86_64
Kernel: winnt 10.0.22622

**Comment by varjolintu** [comment] 2022-09-06 18:49
Duplicate of: https://github.com/keepassxreboot/keepassxc/issues/7952

**Closed as not planned by varjolintu** 2022-09-06 18:49 UTC
Labels: duplicate
