### ISSUE TITLE
Allow for opening multiple entries in multiple tabs or windows

### ISSUE THREAD

**Issue by marco-brandizi** [keepassxreboot/keepassxc#4250] opened 2020-01-27 14:10 UTC
[TIP]:  # ( Provide a general summary of the feature in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Summary
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
It would be good to introduce a multi-tab or multi-window interface, which should allow for opening multiple entries at the same time.

## Desired Behavior
See above.

## Context
Sometimes I have multiple accounts to use to access a service. For instance, first I need to authenticate into my intranet web application and then I've to enter the credentials of two servers I administrate, having to jump from one to another, with timeouts forcing me to type the same passwords more than once.  

Furthermore, this feature would be useful to do copy-paste from one entry to another, which is sometimes needed when you have to update entries about similar services (eg, migrating from one version to another of the same service).

**Comment by droidmonkey** [comment] 2020-01-27 23:03
Does cloning an entry not work in your use case?

Additionally, it sounds like you need to setup appropriate Auto-Type and browser extension integration for your workflow.

Our application is most likely not going to become one that has multiple pop-ups and windows. We already have a tabbed interface when multiple databases are opened.

**Comment by marco-brandizi** [comment] 2020-01-28 01:54
Hi @droidmonkey, thanks. Indeed, cloning could solve the second example. However, I have a number of occasions when seeing multiple entries at the same time would be useful, and I'd like it to work even when I don't use auto-type. One tab per DB isn't the use case I'm interested in.

**Comment by droidmonkey** [comment] 2022-03-21 21:03
Duplicate of #738

**Closed by droidmonkey** 2022-03-21 21:03 UTC
Labels: new feature
