### ISSUE TITLE
Configuration information and application data should be stored seperately

### ISSUE THREAD

**Issue by bearbin** [keepassxreboot/keepassxc#3510] opened 2019-09-05 19:13 UTC
## Summary
[NOTE]: # ( Provide a brief overview of what the new feature is all about )

Currently, there is a single configuration file for KeepassXC which contains both data and configuration. The data (e.g. LastDatabases, LastKeyFile, LastDir, etc) should be separated out into its own file.

## Desired Behavior
[NOTE]: # ( Tell us how the new feature should work, be specific )

Only configuration is stored in the configuration file, so it can be synced between multiple computers (or automatically updated for managed installations).

## Possible Solution
[NOTE]: # ( Not required, but suggest ideas on how to implement the addition or change )

Use a separate file for data.

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )

I want to have my dotfiles synced between computers, and this introduces spurious changes so it is hard to differentiate real ones that need updates.

**Comment by droidmonkey** [comment] 2019-09-05 21:01
Related to #2574 and #2514

**Comment by alerque** [comment] 2019-10-26 16:56
This is an exact duplicate of what I requested back in #2193.

**Closed** 2019-10-26 16:57 UTC
Labels: new feature
