### ISSUE TITLE
Pasting Notes in entry with CTRL + SHIFT + V crashes app

### ISSUE THREAD

**Issue by aferrazlr** [keepassxreboot/keepassxc#3967] opened 2019-12-03 10:51 UTC
KeePassXC crashes (cf. screenshot) when pasting text from Microsoft Teams chat to the Notes field in a New Entry.

![image](https://user-images.githubusercontent.com/154761/70044664-b3087e00-15ba-11ea-93ba-63bf0b3a34c6.png)

**Comment by droidmonkey** [comment] 2019-12-03 13:04
Ctrl+Shift+V should trigger Auto-Type on the entry. I just tried replication and it did just that to me.

**Comment by bf** [comment] 2020-01-03 12:20
The same happens to me on arch linux. KeepasXC version 2.5.1. If you give me debug instructions I can try to provide you with a core dump.

Steps to reproduce: 
1) copy multi-line text from gedit
2) go the "edit" -> "notes" textarea
3) paste text
4) click "apply" button
5) keepassxc crashes after ~1sec

**Comment by droidmonkey** [comment] 2020-01-03 12:38
Run a snapshot build: https://snapshot.keepassxc.org

**Comment by droidmonkey** [comment] 2020-01-05 03:31
Still an issue in 2.5.2?

**Comment by bf** [comment] 2020-01-06 08:10
Seems to be fixed now :)

**Comment by aferrazlr** [comment] 2020-01-06 14:51
Just tried version 2.5.2 and it's still not fixed. 

Keeps crashing:
![image](https://user-images.githubusercontent.com/154761/71825445-cb752800-3093-11ea-83f1-6834a36b91c4.png)

Version 2.5.2:
![image](https://user-images.githubusercontent.com/154761/71825483-e3e54280-3093-11ea-8260-81dc2c14ac55.png)




> KeePassXC - Version 2.5.2
> Revision: 62cda9d
> 
> Qt 5.13.2
> Debugging mode is disabled.
> 
> Operating system: Windows 10 (10.0)
> CPU architecture: x86_64
> Kernel: winnt 10.0.18363
> 
> Enabled extensions:
> - Auto-Type
> - Browser Integration
> - SSH Agent
> - KeeShare (signed and unsigned sharing)
> - YubiKey
> 
> Cryptographic libraries:
>  libgcrypt 1.8.5
>

**Comment by droidmonkey** [comment] 2020-01-06 17:06
Can you cause it to crash by copying from any other application? I don't have teams installed.

**Comment by droidmonkey** [comment] 2020-01-07 23:11
I cannot reproduce this at all. When I press Ctrl+Shift+V while editing notes, KeePassXC performs Auto-Type for the current entry.

**Comment by droidmonkey** [comment] 2020-01-07 23:12
OK, I missed a key point of this issue. The entry must be NEW and totally unedited. No username or password.

**Closed** 2020-01-09 13:21 UTC
Labels: bug, crash :boom:
