### ISSUE TITLE
Minimize on startup setting is broken

### ISSUE THREAD

**Issue by innerand** [keepassxreboot/keepassxc#3081] opened 2019-04-25 20:19 UTC
## Expected Behavior
keepassxc should start minimized when option is selected. 

## Current Behavior
keepassxc doesn't start minimized when option is selected.

## Steps to Reproduce
1. Select Tools/Startup/Minmize Window at application startup
2. Close keepassxc
3. Start keepassxc

## Debug Info
KeePassXC - Version 2.4.1
Revision: 7bafe65

Libraries:
Qt 5.12.3
libgcrypt 1.8.4

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 5.0.9-arch1-1-ARCH

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Possibly duplicate of https://github.com/keepassxreboot/keepassxc/issues/2653, but should emphasize that it isn't just broken on mac.

**Comment by phoerious** [comment] 2019-04-25 22:27
Duplicate of #2481.

**Closed by phoerious** 2019-04-25 22:27 UTC
Labels: bug
