### ISSUE TITLE
.kdbx file icon broken

### ISSUE THREAD

**Issue by 0xShree** [keepassxreboot/keepassxc#9461] opened 2023-05-22 03:51 UTC
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
After an update .kdbx file is displayed with broken icon

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Broken .kdbx file icon

## System info
[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: KDE
Windowing System: X11

KeePassXC - Version 2.7.5
Revision: 9d0537b
Qt 5.15.9
Debugging mode is disabled.

Operating system: Linux 6.3.2-arch1-1
CPU architecture: x86_64
Kernel: linux 6.3.2-arch1-1

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 3.0.0

![image](https://github.com/keepassxreboot/keepassxc/assets/49250702/39ac2704-a7e9-4bc2-b7e1-282b8c145bfe)

**Comment by phoerious** [comment] 2023-05-22 07:51
This is probably a bug in Dolphin. Can anybody reproduce this on other desktop environments?

**Comment by droidmonkey** [comment] 2023-07-16 02:41
Closing this since we only received a couple reports. This is likely an issue with the local system handling svg icons.

**Closed as completed by droidmonkey** 2023-07-16 02:41 UTC
Labels: platform: Linux
