### ISSUE TITLE
Bug: Search now working when window too small

### ISSUE THREAD

**Issue by richardk2016** [keepassxreboot/keepassxc#823] opened 2017-07-27 21:22 UTC
When the window is too narrow, I can't search wich cmd+f. I have more then 1000 entries in my database. So I need search very often during the day. I need the screen for doing my stuff, so I need to keep the kpxc window as small as possible, because it es nearly always visible. I have to expand the windows to nearly one third of the entire screen to be able to search.

## Expected Behavior
cmd+f starts search mode, regardless how narrow the windows of kpxc is.

## Current Behavior
If the window is too narrow, cmd+r simply does nothing.

## Possible Solution
Fix the bug?

## Steps to Reproduce (for bugs)
Read above. If window is too narrow, search is not working.

## Context
Search not working is a showstopper using the program. KeepassX is ugly, but the search works without problem.

## Debug Info

KeePassXC - VERSION 2.2.0

Operating system: Mac OS 10.11.6

**Comment by phoerious** [comment] 2017-07-27 22:16
Duplicate of #505.

**Closed by phoerious** 2017-07-27 22:16 UTC
