### ISSUE TITLE
Search Results Should Not Automatically Clear

### ISSUE THREAD

**Issue by jgindin** [keepassxreboot/keepassxc#3006] opened 2019-04-14 17:18 UTC
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
After I perform a search, the results should remain displayed until *I* perform some action to clear them.

## Current Behavior
After some amount of time, the search results are automatically cleared out.

## Possible Solution
Don't do this. Leave the search results alone. If you really feel like this is somehow beneficial, at least make it a configurable setting.

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. Search for some entry
2. Wait
3. Notice the results get cleared

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )
Having to search *again* for what I was just using is a PITA. Especially when I'm going to need that same result a few times... This happens when sites automatically log you out after a period of time.

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.4.1
Revision: 7bafe65

Qt 5.11.1
Debugging mode is disabled.

Operating system: Ubuntu 18.10
CPU architecture: x86_64
Kernel: linux 4.18.0-17-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.3

**Comment by droidmonkey** [comment] 2019-04-14 19:07
Duplicate of #2953

**Closed by droidmonkey** 2019-04-14 19:07 UTC
Labels: bug
