### ISSUE TITLE
The "Notes" filed/column dose not display cross-references

### ISSUE THREAD

**Issue by grmblfly** [keepassxreboot/keepassxc#11326] opened 2024-10-07 16:09 UTC
## Overview
The "Notes" filed/column dose not display any cross-references -- especially the {REF:N@I:<uuid>} kind.

## Steps to Reproduce
1. Enter cross-reference {REF:N@I:<uuid>} in the Notes field of a new test entry
2. Copy and paste it into the Title field as well

## Expected Behavior
Both fields should show the value of the original <uuid> record.

## Actual Behavior
The Titel field displays the value, and the Notes field displays syntax.

## Context
[[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.9
Revision: 8f6dd13

Qt 5.15.11
Debugging mode is disabled.

Operating system: Windows 11 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.22631

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 3.1.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows

**Comment by droidmonkey** [comment] 2024-10-07 21:23
Duplicate of https://github.com/keepassxreboot/keepassxc/issues/7410

**Closed as not planned by droidmonkey** 2024-10-07 21:23 UTC
