### ISSUE TITLE
QT5 bug causes linking error when building on Windows (NOT a KeePassXC bug)

### ISSUE THREAD

**Issue by shaneknysh** [keepassxreboot/keepassxc#3137] opened 2019-05-11 08:06 UTC
_This is not a bug in KeePassXC but it will affect anyone trying to build KeePassXC on Windows with the broken qt5 install_

Because of [qt5 issue 5253](https://github.com/msys2/MINGW-packages/issues/5253) linking is broken when building in Windows.

## Current Behavior
The error you will get is 

```
CMake Error at D:/msys64/mingw64/lib/cmake/Qt5Gui/Qt5GuiConfig.cmake:15 (message):
  The imported target "Qt5::Gui" references the file

     "C:/building/msys32/mingw64/x86_64-w64-mingw32/lib/libglu32.a"

  but this file does not exist.  Possible reasons include:

  * The file was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and contained

     "D:/msys64/mingw64/lib/cmake/Qt5Gui/Qt5GuiConfigExtras.cmake"

  but not all the files it references.

Call Stack (most recent call first):
  D:/msys64/mingw64/lib/cmake/Qt5Gui/Qt5GuiConfigExtras.cmake:45 (_qt5_Gui_check_file_exists)
  D:/msys64/mingw64/lib/cmake/Qt5Gui/Qt5GuiConfigExtras.cmake:70 (_qt5gui_find_extra_libs)
  D:/msys64/mingw64/lib/cmake/Qt5Gui/Qt5GuiConfig.cmake:212 (include)
  D:/msys64/mingw64/lib/cmake/Qt5/Qt5Config.cmake:28 (find_package)
  CMakeLists.txt:70 (find_package)
```

The "c:/building" folder reference is the issue and seems to be a regression in qt5. 

## Possible Solution

editing the Qt5GuiConfig.cmake file to point to the location of your msys2/mingw installation will correct the problem until qt5 issues a fix.

**Comment by phoerious** [comment] 2019-05-11 08:50
I noticed that a while ago and fixed it by editing out the C:/building part in the Qt find module.

**Comment by droidmonkey** [comment] 2019-05-11 10:48
I believe that is a bug with msys2 packing more so qt5

**Comment by shaneknysh** [comment] 2019-05-11 23:18
I wanted to add it here for documentation for anyone else who experienced the issue building keepassxc. There are a lot of mentions to the issue in searches but few that correctly identify the root cause and workaround available.

**Comment by chuim** [comment] 2019-06-24 05:23
To make it easier for others trying to bypass this problem in the meantime: 

1. Open `C:\msys64\mingw64\lib\cmake\Qt5Gui\Qt5GuiConfigExtras.cmake`
1. Edit the line (70 for my current version of QT5) that contains this:
`_qt5gui_find_extra_libs(OPENGL "C:/building/msys64/mingw64/x86_64-w64-mingw32/lib/libglu32.a;C:/building/msys64/mingw64/x86_64-w64-mingw32/lib/libopengl32.a;C:/building/msys64/mingw64/x86_64-w64-mingw32/lib/libgdi32.a;C:/building/msys64/mingw64/x86_64-w64-mingw32/lib/libuser32.a" "" "")`
1. Replace those paths with the current location of those libs in your system which is, in my case, `C:/msys64/mingw64/x86_64-w64-mingw32/lib/`.

**Comment by ZebulanStanphill** [comment] 2019-06-24 14:56
The issue is now fixed in the latest version of the MSYS2 MINGW-packages.

https://github.com/msys2/MINGW-packages/issues/5253#issuecomment-503984301

**Closed** 2019-06-24 17:19 UTC
Labels: upstream
