### ISSUE TITLE
Drag n Drop fields

### ISSUE THREAD

**Issue by lwolfs** [keepassxreboot/keepassxc#2285] opened 2018-09-12 07:02 UTC
I am new to KeepassXC, been using Keepass since the stoneages. I have searched but didnot find a way to drag and drop fields from KeepassXC to ... something outside KeepassXC (notepad, URL field in browser) using the mouse, not the keyboard.
The native Keepass (at least v2) has this feature and is used a lot by me.

Is this feature not in KeepassXC, or didnt I find it while it is there ?

Thx

**Comment by droidmonkey** [comment] 2018-09-24 13:59
Would this be from the entry view (ie, showing all the entries in the folder)? You would grab, say username, cell and drag it somewhere and it would carry through.

**Comment by lwolfs** [comment] 2018-09-24 14:15
No, this is from the main screen, where one can drag&drop from the table view.

2018-09-24 15:59 GMT+02:00, Jonathan White <notifications@github.com>:
> Would this be from the entry view (ie, showing all the entries in the
> folder)? You would grab, say username, cell and drag it somewhere and it
> would carry through.
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/keepassxreboot/keepassxc/issues/2285#issuecomment-423984407


-- 
Groeten,

Lucien Wolfs

**Comment by droidmonkey** [comment] 2018-09-24 14:35
Yes that is what I am talking about

**Comment by droidmonkey** [comment] 2018-10-06 19:16
Duplicate of #1987

**Closed by droidmonkey** 2018-10-06 19:16 UTC
Labels: accessibility, user interface
