### ISSUE TITLE
Saving DB fails intermittently on windows

### ISSUE THREAD

**Issue by mattvchandler** [keepassxreboot/keepassxc#197] opened 2017-01-25 00:26 UTC
## Current Behavior
Most of the time, attempting to save a database file on windows fails with this message:

    Writing the database failed.
    
    The Process cannot access the file because it is being used by another process.

A copy of the DB file is written at \path\to\db.kdbx.<2 random? letters>\<PID>

Occasionally, the write does go through without an error.

## Steps to Reproduce (for bugs)
I have not yet been able to reproduce the error with a fresh database created with either keepassxc or keepassX. Obviously, I'm not willing to upload one of my real DBs.

## Context
Process Explorer reports no other process has a handle to the .kdbx file.

## Your Environment
* KeePassXC version/commit used: 42c0815cdaa652bcdf25b90a2a4a20b2981a39b2
* Qt version 5.6.2
* Compiler: gcc version 6.3.0 (Rev1, Built by MSYS2 project)
* Operating System and version: Windows 7 SP1

**Comment by droidmonkey** [comment] 2017-01-26 01:25
What is the origin of your original DB that caused this error? Was it created in KeePass or some other program?

The reason why this error is thrown is for three distinct reasons:

1. Cannot open the file for writing
2. Cannot write to the IOStream for some reason
3. Cannot commit the changes to the file AFTER writing to the IOStream

**Comment by mattvchandler** [comment] 2017-01-26 01:26
Originally created in KeepassX 1.x, imported into KeepassX 2.x

**Comment by mattvchandler** [comment] 2017-01-26 01:37
I deleted all entries from the problematic DB and see the same error with the now empty DB. See attached. master pw is 'asdf'
[test.zip](https://github.com/keepassxreboot/keepassxc/files/731367/test.zip)

**Comment by droidmonkey** [comment] 2017-01-26 02:16
No problems for me under Windows 10 64-bit

**Comment by dsbert** [comment] 2017-01-30 18:51
I'm experiencing this same issue. Windows 7 64 bit. This may be due to keepass not playing well with other file watchers. I have my database file in a drop box share. If I move the file outside of that share, I don't see the errors anymore.

**Comment by mattvchandler** [comment] 2017-01-30 18:59
I have my problematic files in Dropbox too.

That seems to be the key. I can reproduce the problem consistently with 
a new database file saved in Dropbox, and the problem stops when Dropbox 
is off or the file is moved outside it.

**Comment by droidmonkey** [comment] 2017-01-30 21:00
Interesting, I store mine in Google Drive (and previously OneDrive) and have not had any issues. I will test with dropbox.

**Comment by phoerious** [comment] 2017-01-30 22:01
I don't have issues with Nextcloud/OwnCloud (i.e., csync), either.

**Comment by CombleG** [comment] 2017-02-27 18:20
Hi,

Just to say that i have the same problem..
Dropbox or GoogleDrive..
I want to use KeePassxc instead off KeePass, but i can because off this bug :(

**Comment by CombleG** [comment] 2017-02-27 18:21
Hi,

Just to say that i have the same problem..
Dropbox or GoogleDrive..
I want to use KeePassxc instead off KeePass, but i can because off this bug :(

**Comment by Dunkh4n** [comment] 2017-02-27 18:23
Hi,

Just to say that i have the same problem..
Dropbox or GoogleDrive..
I want to use KeePassxc instead off KeePass, but i can because off this bug :(

**Comment by dsbert** [comment] 2017-03-30 13:57
This is still a problem in version 2.1.3. However, it seems like it might not be happening quite as often.

**Comment by droidmonkey** [comment] 2017-04-03 03:57
So I came upon this issue with a slow upload to google drive... seems like when these cloud providers are syncing the file they hold a lock on it. This prevents KeePassXC from writing to the file (naturally). There is really nothing we can do about it...

**Comment by dsbert** [comment] 2017-04-03 04:23
How do other programs handle this behavior? How does Keepass 2? Is it
silently failing in the background and just not notifying me? It is trying
to save multiple times before it raises an error? I understand there are
difficult issues when integrating with third-party applications. However, I
feel like there is definitely more that could be done to smooth this out. I
know this is an open source program (and everything that implies), but I
hope this issue isn't just closed as 'not fixable'.

**Comment by droidmonkey** [comment] 2017-04-03 04:26
I found that waiting for the upload to complete worked great. Other than that I am out of ideas... unless we are being too strict when we try to write to a file?

**Comment by netforhack** [comment] 2017-04-09 01:05
The same issue, also wtf is this ?
![image](https://cloud.githubusercontent.com/assets/1379437/24833691/d1c5a002-1cd9-11e7-90ca-dc33b14e0f83.png)

**Comment by netforhack** [comment] 2017-04-11 00:26
@droidmonkey seems that keepass2 works with copy of original db file ".lock", to save it delete original db file and rename .lock to original db file name

**Comment by EmperorSAM** [comment] 2017-05-04 09:07
I have problem too. Win7 64bit. Dropbox sync is enabled - DB no save. Disabled - Normal Save.
KeePassXC 2.1.4

**Comment by tronjs** [comment] 2017-05-05 08:03
I have the same problem

**Comment by phoerious** [comment] 2017-05-14 13:45
I would assume that this is a Windows-only problem due to the fact that Windows is the only OS that grants and requires exclusive file access.

**Comment by JaggedJax** [comment] 2017-07-25 17:53
I get this same issue with the kdbx file sitting in a dropbox folder on Windows 8.1 x64. Even after the file has been synced by Dropbox I cannot save in KeePass XC and it just keeps creating new temporary DB files in the folder every time it tries to save.

**Comment by droidmonkey** [comment] 2017-07-26 00:34
We probably make the wrong checks for writability which result in false negatives

**Comment by felixkopf** [comment] 2017-09-02 16:00
Same issue here.

I figured out, that when I click "Save" or press CTRL+S two times quickly in a row, it works.
The first attempt fails with the error message and a new .kdbx.'something'-File is created in my Dropbox.

**Comment by tooor** [comment] 2017-09-10 18:22
Windows 10 64-bit experiencing 100% reproducible behavior when I do the following:

1. Have Dropbox running
2. Store my DB file in Dropbox folder
3. Try to save DB file. 

Problem is immediately fixed _without_ restarting keypassxc when I close Dropbox, then try to save again. So my temporary solution is just close Dropbox when I can't save the DB, then start Dropbox again to sync my newest version of DB to cloud.

**Comment by jask05** [comment] 2017-09-14 09:22
Hi,

I have the same problema like @tooor. Are there any workaround?

Thanks!

**Comment by rockihack** [comment] 2017-09-16 16:50
Probably a qt bug. QSaveFile uses a temporary file without exclusive lock.

https://bugreports.qt.io/browse/QTBUG-57299

**Comment by snospar** [comment] 2017-09-16 20:05
I can confirm the same issue when using Windows 10 and opening the kdbx file from my NAS (drive mapped using SMB). Bizarely, if I click multiple times on the Save button it will work - I hear the NAS update the file (disk chunters) and when I shut the application it know the file has been saved so doesn't prompt.

I've never had this issue when accessing the same kdbx file from the same NAS when using Linux on the same dual boot machine.

**Comment by andreas-profitlich** [comment] 2017-11-04 22:26
same problem (Windows 10, Dropbox) - this is a blocker guys

**Comment by krizian** [comment] 2017-11-13 12:29
same problem here for three Windows PCs in a private network with NAS Server (1x Windows 7, 2x Windows 10). We can't use KeepassXC till this issue is solved. Agreeing to andreas-profitlich: this is a true blocker!!

**Comment by droidmonkey** [comment] 2017-11-13 13:59
The use case of a shared database among multiple users was not programmed into this app. I consider a file sync service as a multiple user in this context. It is technically not a blocker since there is a workaround (click save till it works). With that said its on my short list to fix.

**Comment by 5paceToast** [comment] 2017-11-13 16:04
@droidmonkey the [FAQ](https://keepassxc.org/docs#faq-cloudsync) gives an impression that using a file sync service (to synchronize the same db accross multiple machines of a single user, as in this issue) isn't just supported, but is recommended.

Maybe it makes sense to modify the FAQ to reflect the original intent in this case?

Furthermore, spamming save seems relatively inconsistent (e.g in my testing I've never managed to get it to sync, even after a full minute of clicking), so I wouldn't really consider it a real workaround (that's not to mention the lock-file per-click that gets created (and therefore synced)).

**Comment by TheZ3ro** [comment] 2017-11-13 16:18
@5paceToast he is referring to KeePassX, originally it wasn't developed with syncing in mind. Now it's a requirement. 

We are wrapping up features such as sync, auto-reload and auto-merge trying to make the sync process easy, transparent and multi-platform. The FAQ are fine

**Comment by 5paceToast** [comment] 2017-11-13 16:27
Ah, ok. Thanks for clearing that up :)

**Comment by krizian** [comment] 2017-11-14 10:03
@TheZ3ro @droidmonkey is the plan to copy features such as sync and auto-merge from Keepass, or would it be possible to create a real db with sync features like e.g. a sql db ? 
In Keepass auto-reload was missing for daily multi-user use.
Thank you in advance! : )

**Comment by droidmonkey** [comment] 2017-11-20 17:04
Will be worked on in conjunction with #1002

**Comment by sdidit** [comment] 2017-12-13 19:56
It seems to me the problem is caused by the temporary file. If Google Drive starts to sync the temporary file before it is renamed, the rename will fail. I'm then left with a temporary file and no database file. The problem happens more often now that Google has updated their sync utility.

**Comment by droidmonkey** [comment] 2017-12-13 21:23
Perhaps the temp file should be created in to directory then moved into the appropriate location afterwards.

**Comment by sdidit** [comment] 2017-12-13 22:33
It's more an issue of Backup and Sync. Other applications that create temporary files have the same problem with Google Drive. There's an option to ignore certain file extensions, but that only applies to the backup function, not the sync function.

**Closed** 2018-01-28 20:19 UTC
Labels: Windows, bug, high priority
