### ISSUE TITLE
Cannot copy password

### ISSUE THREAD

**Issue by yThomasS** [keepassxreboot/keepassxc#3577] opened 2019-09-25 15:35 UTC
## Expected Behavior
Should be possible to first copy the username and then the password

## Current Behavior
After copy and pasting the username the only option that I get in the popup menu is "New Entry"

## Possible Solution
Wait for some time (2min?)

## Steps to Reproduce
1.right click on an entry and copy the username
2.past username on some webpage
3.right click on the same entry (or on any entry) and it is only showing "New Entry"

## Context
Nothing special

## Debug Info
KeePassXC - Version 2.4.3
Revision: 5d6ef0c

Qt 5.12.3
Debugging mode is disabled.

Operating system: macOS Mojave (10.14)
CPU architecture: x86_64
Kernel: darwin 18.7.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.4

**Comment by droidmonkey** [comment] 2019-09-25 18:13
You must make sure KeePassXC has focus first. This is a duplicate of another issue.

**Closed** 2019-09-25 18:13 UTC
Labels: bug

**Comment by yThomasS** [comment] 2019-09-26 06:43
How do I make KeePassXC focus? I clicked on the app, selected something from the menu, but nothing changed.
