### ISSUE TITLE
Command-line options disregarded by GUI application

### ISSUE THREAD

**Issue by a-dma** [keepassxreboot/keepassxc#1636] opened 2018-03-05 13:05 UTC
Currently on Ubuntu 17.10.
According to `keepassxc -h` there's a bunch of options like `--pw-stdin` and `--keyfile` that can be used to start the application. These flags seems to be disregarded and don't change anything.

Furthermore, if the `--pw-stdin` option is specified, the application will not paint its window until a string is typed on the terminal used to launch it followed by return. The string (which I assume is expected to be the password, is echoed on screen).

## Expected Behavior
The application should start and the database should already be unlocked, at least if all you're using is a password and/or a keyfile.

## Current Behavior
The usual initial screen is shown. No field is filled-out. No error is shown if the database file or the keyfile don't exist.

## Possible Solution
Honor the flags advertised by `--help`

## Steps to Reproduce (for bugs)
1. Open a terminal
2. Run `keepassxc --pw-stdin --keyfile key_file Passwords.kdbx`
3. A window opens but is not painted.
4. If a string is sent to the terminal the normal execution resumes, but options are disregarded

## Context
Trying to find a way around having to have a clear-text keyfile sitting on my hard disk.

## Debug Info
```
KeePassXC - Version 2.3.0
Revision: 4c0ed74

Libraries:
- Qt 5.9.1
- libgcrypt 1.7.8

Operating system: Ubuntu 17.10
CPU architecture: x86_64
Kernel: linux 4.13.0-25-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey
```

**Comment by phoerious** [comment] 2018-03-05 13:24
Duplicate of #1600

**Closed by phoerious** 2018-03-05 13:24 UTC
