### ISSUE TITLE
"KeePassXC" can't be opened because Apple cannot check it for malicious software

### ISSUE THREAD

**Issue by themediapot** [keepassxreboot/keepassxc#3692] opened 2019-10-27 22:43 UTC
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
When launching KeePassXC 2.5.0 after upgrading from 2.4.3, I expect KeePassXC to launch as usual.

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
When launching KeePassXC 2.5.0 after upgrading from 2.4.3, I received this error message from MacOS:

> "KeePassXC" can't be opened because Apple cannot check it for malicious software.
> This software needs to be updated.  Contact the developer for more information.
>
> Firefox Developer Edition downloaded this file yesterday at 8:45 pm from github-production-release-asset-2e65be.s3.amazonaws.com.

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. Download [binary bundle](https://github.com/keepassxreboot/keepassxc/releases/download/2.5.0/KeePassXC-2.5.0.dmg) from https://keepassxc.org/download/ 
2. Open bundle, drag KeePassXC into Applications folder
3. Execute bundle
4. Receive error message

OR

1. Brew upgrade keepassxc
2. Run KeePassXC
3. Receive error message

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.5.0
Revision: REVISION

Libraries:
- LIBS

Operating system: MacOS 10.15

Enabled extensions:
- KeePassXC-Browser

**Comment by droidmonkey** [comment] 2019-10-27 23:22
Duplicate of #3685

**Closed by droidmonkey** 2019-10-27 23:22 UTC
Labels: bug
