### ISSUE TITLE
Unable to change directory location to mounted volume

### ISSUE THREAD

**Issue by kevbarroga** [keepassxreboot/keepassxc#547] opened 2017-05-05 00:43 UTC
I keep my .kdbx file stored in a mounted volume not in /home/username directory. I am unable to change the directory location to anything other than /home and the ~/snap/keepassxc directory. Creating a symbolic link does not work...

I am experiencing this issue on Ubuntu 17.04
KeePassXC v2.1.4 *installed via snap package*

**Comment by vsvyatski** [comment] 2017-05-05 09:38
It's not really a bug of KeePassXC. You can experience the same problem with VLC, for instance, or any other Qt based application running on GTK based environment like Unity, Gnome itself, Cinnamon, Maté, etc. A Qt based application shows Qt file dialog which doesn't really let you browse for a file on some drive that is plugged into the system, but not mounted via Nautilus (Nemo, Caja, etc). An example of such drive would be some secondary hard drive with NTFS which is not mounted automatically on startup. Once the drive is mounted via the file manager it should be possible to navigate to the file via the dialog (it's quite inconvenient though).
There is certain solutions for this problem:
1. You can force you drive to be mounted automatically on the system startup. See https://help.ubuntu.com/community/AutomaticallyMountPartitions and https://help.ubuntu.com/community/MountingWindowsPartitions. But again, it will be kinda inconvenient to browse for a file in the Qt dialog.
2. You can install [libqt5libqgtk2 package](http://packages.ubuntu.com/search?keywords=libqt5libqgtk2) which will make Qt applications (including KeePassXC) to use GTK file dialog which allows to mount partitions on the fly (but this will last only until you log out or manually unmount the partition). Unfortunately, it seems like this approach is not working on Zesty yet (it definitely works on Xenial and theretically should on Yakkety).

To the development team: I believe this thing is worth mentioning in known issues.

**Comment by TheZ3ro** [comment] 2017-05-05 09:56
I think this is a duplicate of #400 since you mentioned you are using the snap package.
Follow this comment to plug the removable-media interface on the Snap package https://github.com/keepassxreboot/keepassxc/issues/400#issuecomment-297218549

**Closed** 2017-05-05 09:56 UTC
Labels: duplicate

**Comment by droidmonkey** [comment] 2017-05-05 10:41
Got it!
