### ISSUE TITLE
crash on exit

### ISSUE THREAD

**Issue by Hugo-Leung** [keepassxreboot/keepassxc#9952] opened 2023-10-22 18:52 UTC
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Occasionally, KeepassXC would crash while I am exiting the application. It tends to happen more often if I attempt to shutdown windows before manually exiting KeepassXC. I think this is similar to #7543

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Open database
2. Shutdown windows (without exiting KeePassXC)

I don't know if this is a reliable way of reproducing this error, as it will exit without errors for weeks, but then randomly appear one day and disappear the next day.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
KeepassXC should exit gracefully 

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

![20231021_161630](https://github.com/keepassxreboot/keepassxc/assets/20005167/901b13db-04aa-497a-88b5-17e465c9ea22)

## Context
[NOTE]: # ( Give us any additional information you may have. )
It does not happen all the time.

KeePassXC - Version 2.7.6
Revision: dd21def

Qt 5.15.10
Debugging mode is disabled.

Operating system: Windows 11 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.22621

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.19.3

**Comment by droidmonkey** [comment] 2023-10-22 19:06
Unfortunately it is impossible to fix this without a crash dump, and even then you'd have to run a debug build and reproduce it. Unless we stumble on the reason why this is occurring (doesn't happen to me) this won't be solved. Closing since there is nothing we can do without more info.

**Closed as not planned by droidmonkey** 2023-10-22 19:06 UTC
Labels: platform: Windows, crash :boom:
