### ISSUE TITLE
keepassxc hangs when connecting from keepass-browser plugin

### ISSUE THREAD

**Issue by grimpy** [keepassxreboot/keepassxc#1452] opened 2018-02-03 20:16 UTC
After installing https://github.com/keepassxreboot/keepassxc-browser for firefox.
I pressed the connect button from the addon which should yield me with a popup to approve this connection instead keepassxc hangs (does not respond to any X events cligking in UI) and the browser plugin gives the following message
` Timeout or not connected to KeePassXC `

**Comment by grimpy** [comment] 2018-02-03 20:29
I was suspecting my windows manager (Awesome) so I tried to test it with another windows manager (XFCE) and it seems to work fine from there the popup to authorize firefox appears and once approved it works under Awesome awell. So I tested under I3 aswell and noticed that the popup quickly flashed infront of me and then dissapeared

**Comment by grimpy** [comment] 2018-02-04 09:17
@varjolintu not sure what gave away I'm an Archlinux user but yes I used https://aur.archlinux.org/packages/keepassxc-git for the install.
I've installed the browser plugin via https://addons.mozilla.org/en-US/firefox/addon/keepassxc-browser/?src=userprofile

**Comment by varjolintu** [comment] 2018-02-04 09:31
@grimpy I assumed this is related to another issue (https://github.com/varjolintu/keepassxc/issues/20) where the issue can be reproduced with the AUR package. I hope to find the reason for this soon.

**Comment by prometheanfire** [comment] 2018-02-04 20:02
just reproduced with a git master build on gentoo as well (I use awesome as well).

**Comment by prometheanfire** [comment] 2018-02-04 21:50
@grimpy mind testing the PR linked above?

**Comment by prometheanfire** [comment] 2018-02-04 21:52
nevermind, this bug should be closed now (since it merged)

**Comment by TheZ3ro** [comment] 2018-02-04 22:05
Thanks for the contribution 😉

**Closed** 2018-02-04 22:05 UTC
Labels: browser integration
