### ISSUE TITLE
Unable to login using TouchID after unlocking mac

### ISSUE THREAD

**Issue by rahilsh** [keepassxreboot/keepassxc#6903] opened 2021-09-08 03:27 UTC
![Screenshot 2021-09-08 at 8 48 46 AM](https://user-images.githubusercontent.com/22071745/132441041-68c8514a-aa92-4430-9180-512028db51b6.jpg)

## Overview
When I try to login after unlocking/restart of mac it does not allow to login via TouchID(check screenshot for error). First time I have to login using password and only when I lock DB manually, it allows to login via TouchID, which I felt i never do. Is this specific to MacOS Big Sur or across all MacOS

## Steps to Reproduce
1. Lock Mac while Keepassxc is running in background
2. Unlock Mac
3. Open Keepassxc, press ok without entering password

## Expected Behavior
Prompt for TouchID

## Actual Behavior
No Prompt for TouchID

KeePassXC - Version 2.6.6
Revision: 386b79a

Operating System: macOS Big Sur
Desktop Env: Gnome/KDE/XFCE/Mate/Cinnamon (Not sure)
Windowing System: X11/Wayland (Not sure)

**Comment by droidmonkey** [comment] 2021-09-08 04:28
This is by design. You can't use touchid after you close keepassxc. It is meant for quick unlocking only.

**Comment by rahilsh** [comment] 2021-09-08 05:05
@droidmonkey I didn't quit keepassxc, I just locked mac and unlocked

**Comment by droidmonkey** [comment] 2021-09-08 07:48
Ahh sorry I read it as a logoff/login scenario. I'll investigate but have your set a timeout for your touchid in the application security settings?

**Comment by phoerious** [comment] 2021-09-08 08:00
The unlock key is saved in your system keychain. Is it possible that this keychain is locked after closing the lid?

**Comment by rahilsh** [comment] 2021-09-08 08:07
![Screenshot 2021-09-08 at 1 32 55 PM](https://user-images.githubusercontent.com/22071745/132470547-5ddf6b72-4450-4b89-a732-4b9ff4087196.jpg)

I unchecked this checkbox in security settings and now it is working as expected. I believe this was checked by default. I have 2 suggestions

1. can we keep this option unchecked by default
2. When keepassxc is locked we need to press enter to activate login via touchID, can we somehow avoid this and keepassxc asks touchID directly(except when app starts and password is needed)

PS: We can close this issue as it is not a bug

**Comment by droidmonkey** [comment] 2021-09-08 10:13
Yah touchid has its own improvements issue tracking a bunch of stuff.

**Closed as completed by droidmonkey** 2021-09-08 10:13 UTC
Labels: platform: macOS
