### ISSUE TITLE
Auto-Type disable the layout switching!

### ISSUE THREAD

**Issue by MAPIIIAJI** [keepassxreboot/keepassxc#2246] opened 2018-08-28 06:14 UTC
OS: Ubuntu 18.04
DE: XFCE 4.12
App.: KeePassXC 2.3.1
Language layouts: English, Russian
---
If use Auto-type, stops switching (Alt+Shift) to another layout (after several attempts, did not exactly count and did not get stuck).
Both at home and at work I use the same operating system and DE. Both at home and at work KeePassXC stops switching the layout. This is very annoying, please tell me the solution to this problem. Thanks in advance.

Regards,
Jamshid

**Comment by denisov** [comment] 2018-09-01 05:15
Me too. I am using "caps lock" to switch langiages. I even cannot change hotkey after keepassxc autotype

OS: Mint 19
DE: Mate
App: KeePassXC 2.3.4 
Language layouts: English, Russian

**Comment by Ravshanovich** [comment] 2018-09-20 17:48
If more than one system language is installed, the keyboard shortcuts to change the language will stop working after you type automatically.
If three system languages are installed, the change layout button continues to work after the autorun operation, but the language moves to the next
OS: Mint 19
DE: Cinnamon
App: KeePassXC 2.3.4
Language layouts: English, Russian

**Comment by vladipus** [comment] 2018-10-25 16:33
What's the solution? This actually breaks the system, unlike the original KeePassX, which behaved normally.

**Comment by maximium** [comment] 2018-12-10 11:21
> What's the solution? This actually breaks the system, unlike the original KeePassX, which behaved normally.

KeePassX 2.0.3 breaks it too if use autotype while non english layout active

**Comment by MasterGroosha** [comment] 2019-05-13 20:46
And it's still an issue :(

**Comment by NiklasSenpai** [comment] 2019-05-31 19:15
Not sure if it's the same issue but I'm using two different keyboard layouts (same language tho) and KeepassXC ignores when I switch them. Autotype inserts the wrong characters and my autotype shortcut doesn't update (it's still mapped to the same physical keys even though the character is mapped to a different key on the other layout)

It's annoying because I sometimes have to switch layouts just for autotype and then switch back

**Comment by bagau** [comment] 2019-06-25 05:48
I've read all of duplicates of this issue. But there are no solutions. Did anybody find himself custom solution for this issue?

**Comment by bakemonoru** [comment] 2019-07-03 07:55
confimed for me:
Fedora 30
XFCE 4.12
Keepassxc:
Name         : keepassxc
Version      : 2.4.3
Release      : 1.fc30
Architecture : x86_64
Source       : keepassxc-2.4.3-1.fc30.src.rpm
Repository   : @System
From repo    : updates

Layout switch key: CAPSLOCK
Layout lis: EN, RU

Problem occurs when RU layout is active and i perform autotype.

**Comment by dev-lc** [comment] 2019-09-24 11:10
> confimed for me:
> Fedora 30
> XFCE 4.12
> Keepassxc:
> Name : keepassxc
> Version : 2.4.3
> Release : 1.fc30
> Architecture : x86_64
> Source : keepassxc-2.4.3-1.fc30.src.rpm
> Repository : @System
> From repo : updates
> 
> Layout switch key: CAPSLOCK
> Layout list: EN, RU
> 
> Problem occurs when RU layout is active and i perform autotype.

The same for me. I have three laptops with Fedora 27, 29, 30 (Cinnamon) and Keepassxc.x86_64                                                2.4.3-4.fc29

**Comment by lilalkor** [comment] 2019-10-06 08:14
Still the same issue.
OS: Arch Linux
DE: KDE Plasma 5.16.5
App.: KeePassXC 2.4.3
Language layouts: English, Russian

But it behaves normally on other system with Windows - correctly changes layout for autotype.

**Comment by wijde** [comment] 2019-12-11 11:52
Guys, the problem has not yet been fixed and is very annoying. After some time, I returned to Linux desktop and see that the problem has not been fixed so far.
Version: 2.5.1
Ubuntu19.10 / DE KDE

**Comment by karmicdude** [comment] 2020-01-08 16:14
Another +1 from me too. 
Sometimes, being a little inattentive, I forget to switch the layout before autotype. This is a very annoying problem, you have to close the entire working environment, stop the services, close the development env like ide, dev tools, opened terminal session, etc. that sometimes is just hell.
Archlinux, KeePassXC 2.5.1, DE KDE, Keyboard layouts: both custom for EN and RU

**Comment by phoerious** [comment] 2020-06-01 08:42
Duplicate of #324

**Closed by phoerious** 2020-06-01 08:42 UTC
Labels: bug, plugin: Auto-Type

**Comment by wijde** [comment] 2021-02-09 08:36
I have: MacOS
Processor: M1
Problem: At certain points when working with KeePassXC, keyboard switching stops working. You have to restart the Mac for the switch to work.

**Comment by kvoit** [comment] 2022-01-21 10:30
I don't see at all how this is a duplicate of #324. That issue describes the situation in which the auto-type layout does not match the desktop environments layout and thus produces wrong characters.

THIS issue describes that under certain circumstances, auto-typing breaks the desktop environments possibility to switch layout via hotkeys.

For me, this happens under KUbuntu 21.10's Plasma, when I auto-type under German layout. The characters will be wrong, but also, I cannot switch layout anymore with Ctrl+Shift. I CAN still switch layout by clicking on the systray icon.

Steps to reproduce:
- Start with an English Kubuntu (in my case GB layout)
- Add German as a secondary layout, configure switching shortcut
- Switch to German, and auto-type something. I have not identified any particular character that triggers this, but maybe use an email address as user name and put some special characters in the password.
=> Switching layout with hotkey doesn't work anymore.

As long as I remember to only auto-type only under GB layout, everything works as expected.

This issue has been going on for quite some time and on multiple computers and it really annoying if one switches back and forth between layouts often (e.g. since programming with German layout is horrible, but the English one doesn't have all characters ...)

**Comment by droidmonkey** [comment] 2022-01-21 10:56
Is the same underlying reason and is fixed in upcoming 2.7.0

**Comment by kvoit** [comment] 2022-01-21 11:09
Great to hear, thanks.

**Comment by hinell** [comment] 2022-04-29 17:00
@droidmonkey Whe 2.7.0 is going to be released?
