### ISSUE TITLE
Add commands in the context menu for entries with SSH keys

### ISSUE THREAD

**Issue by Adirelle** [keepassxreboot/keepassxc#4344] opened 2020-02-19 10:48 UTC
Allow to add/remove SSH keys to the agent using the context menu of entries, the same way you can copy username/password/TOTP.

## Summary

There is no quick and easy way to add/remove a SSH key to the SSH agent. To do so, one has to open the entry, click on SSH integration panel and then click on the "Add" or "Remove" key buttons. The idea is to add some context-menu commands to do so.

## Desired Behavior

When right-clicking on a entry which contains a SSH key, the context menu shows a submenu with two commands : "Add key to SSH agent", "Remove key from SSH agent".

## Context

As I have access to production servers, I have recently generated several SSH keys instead of using the same key for all usage, e.g. I use one key to access the corporate git server and another one to connect to production servers. To avoid accidental (or malicious) accesses to the servers, I only add the SSH keys into the agent when I need them. (Actually only the passphrases are stored in the database, the key themselves are stored on the filesystem.)

**Comment by droidmonkey** [comment] 2020-02-19 11:03
Duplicate of #1815

**Closed by droidmonkey** 2020-02-19 11:04 UTC
Labels: new feature
