### ISSUE TITLE
Modify KeePassXC behavior with non-data changes?

### ISSUE THREAD

**Issue by XTChrys** [keepassxreboot/keepassxc#11595] opened 2024-12-25 09:27 UTC
### Have you searched for an existing feature request?

- [x] Yes, I tried searching

### Brief Summary

Hi all and Merry Christmas! Currently KeepassXC when open item group (with non-data changes), after click "X" for close app, a tooltip ask "Save" or Discard" changes. This is annoying. KeePass not request this, you can force save by clicking on the grey icon "Save". Is it possible to add this behavior on KeePassXC? Or add an option to not save the database by default without ask? Thanks for all!

### Example

_**KeePassXC behavior :**_

![Image](https://github.com/user-attachments/assets/3c8de2a2-a9a3-4f2e-8f4d-063d19dcf5b2)

_**KeePass behavior:**_

![Image](https://github.com/user-attachments/assets/4c9c549e-f293-4cbc-8df5-c155f5212993)

**Comment by droidmonkey** [comment] 2024-12-25 12:19
Duplicate of https://github.com/keepassxreboot/keepassxc/issues/9751#issuecomment-1683766203

**Closed as not planned by droidmonkey** 2024-12-25 12:19 UTC
