### ISSUE TITLE
Unlock Database window does not auto-close on macOS 13

### ISSUE THREAD

**Issue by moabits** [keepassxreboot/keepassxc#8783] opened 2022-11-11 08:58 UTC
I unlock my database with the fingerprint sensor on a MacBook Pro M1.
Since updating to macOS _Ventura_, the "Unlock Database" window does no longer auto-close after unlocking.
The buttons get disabled, but the window stays open. I also can not close it manually since the window controls are disabled.

**Comment by varjolintu** [comment] 2022-11-11 09:44
Duplicate of: https://github.com/keepassxreboot/keepassxc/issues/8719

**Closed as not planned by varjolintu** 2022-11-11 09:44 UTC
Labels: duplicate
