### ISSUE TITLE
Set and unset tags from several entries at once

### ISSUE THREAD

**Issue by MrChocolatine** [keepassxreboot/keepassxc#8277] opened 2022-07-17 14:14 UTC
## Summary

I would like to be able to delete tags from several entries at once.

## Examples

I do not have any picture to show some ideas:

1. From the block "Database Tags", or in the preview panel of an entry, to be able to right on any tag and select "Delete this tag from all entries".
2. Menubar > Database Settings > Maintenance > A new view with a list of all the tags used, with possibility to delete them from all entries (and rename the tags eventually?)

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )

I am asking for this feature because, since I upgraded to the [version 2.7.0](https://github.com/keepassxreboot/keepassxc/releases/tag/2.7.0), where the tags functionality has been added, _almost all_ my entries got automatically flagged with tags while I never wanted that.
I am not saying this feature is not useful (I want to use tags) but 1) the tags I have now were not created by me and 2) the set of entries that were modified with tags is not correct.
I do not understand how the creation of these tags was based on.

Thank you.

**Comment by droidmonkey** [comment] 2022-07-17 15:18
We did not add any tags to your entries. You must have used another keepass program that added those tags. This feature is a duplicate of being able to set/unset a tag on multiple entries at once.

**Comment by droidmonkey** [comment] 2022-07-17 15:26
It appears I didn't have an issue tracking this feature, re-opened

**Comment by MrChocolatine** [comment] 2022-07-17 16:01
> You must have used another keepass program that added those tags

That is surprising, but I am pretty sure I did not. Apart from KeePassXC I never had any other passwords manager or any program related to passwords :-\ .

**Comment by MrChocolatine** [comment] 2022-07-17 16:01
Thank you for considering this request 👍  .

**Comment by droidmonkey** [comment] 2022-07-17 17:30
Are you referring to the weak passwords and other saved searches? These are not tags, they are searches.

**Comment by MrChocolatine** [comment] 2022-07-17 19:55
> Are you referring to the weak passwords and other saved searches? These are not tags, they are searches.

I was referring to the tags we can see in the sliding block "Database Tags" in the bottom left corner.
And now you mention it, I just noticed the first 3 entries have a slightly different icon, these must be searches like you said. But I have "normal tags" below.

**Comment by droidmonkey** [comment] 2022-07-17 20:07
A screenshot would be helpful, but either way we do not add tags (and never did prior to 2.7.0) unless you used another program or added them post 2.7.0. Not sure what happened there.

**Comment by andreystepanov** [comment] 2022-08-05 19:49
Add/remove tags on multiple entries would be very useful feature.
Because now it’s impossible to do, and doing it one-by-one is very tedious (with hundreds or thousands of entries).

Especially true for those who migrating from other password managers and doing initial organization/cleanup, like myself.

Potential workflow is:

1. Perform a search using default operators provided by KeePassXC
2. Add/remove tags to/from selected entries

Another way to quickly add tag for multiple items might be just dragging them to one of the tags in the bottom-left corner of the main UI screen. The same way you move entries between groups (folders). But it only applies for adding tags. For removal we probably need different UI.

**Comment by droidmonkey** [comment] 2022-08-05 20:09
Oh I like the drag and drop idea, not entirely intuitive but an option. I was thinking something more akin to the GitHub tagging interface.

**Comment by andreystepanov** [comment] 2022-08-06 16:15
To remove tag from multiple entries we might just do the same drag-and-drop action but with pressed modifier key such as `Alt` / `Shift` / `Control`. Personally i prefer `Alt`.

But if i want to remove multiple tags it still will be an issue though.
Current UI for assigning tags on the entry level is good, but I’m just not sure how or where you can render it inside main window.

There's a few options:

1. **Use search input for tags**
   As an alternative we can just render tags inside search field itself, when UI button to add/remove tags has been clicked (or via keybinding).
   
   The input would be filled will current tags from all selected entries (unique only), and user would be able to add/remove them quickly.
   
![shot-2022-08-06-at-18-50-20-edit--2CzMaCfggtMwf1UfSZgakVljS3k](https://user-images.githubusercontent.com/472885/183257164-408c91a0-14c6-40c1-b8f0-e3092d4638c6.png)

2. **Create custom tab called `Tags` in preview pane**
   Probably much better solution would be to use preview pane for these sorts of actions (in the future probably others would be added here anyway).
   
   New tab called `Tags` would be whole lot cleaner. And later we might even move currently displayed tags for single entry there too.
   
![shot-2022-08-06-at-19-00-53-edit--2CzNrgERZOGdishXTXiBsXJrGXx](https://user-images.githubusercontent.com/472885/183257185-51c0a6f6-855e-4d1d-9e81-56fb770503fe.png)

![shot-2022-08-06-at-19-08-09-edit--2CzOkUhlZgydmDxhLHQTK1IbZ5j](https://user-images.githubusercontent.com/472885/183257183-de6143d9-1bf3-4897-8dda-1083fb20d25e.png)

As a keybinding i'm suggesting to add `Control + t` as default one.

**Comment by rjt** [comment] 2022-08-06 23:51
Adding tags to entries retrieved from search results would be nice.

**Comment by sunknudsen** [comment] 2022-08-16 18:48
Is it currently possible to delete unused tags?

**Comment by droidmonkey** [comment] 2022-08-16 20:32
Tags will not appear if no entry has them

**Comment by sunknudsen** [comment] 2022-08-16 22:00
Thanks for helping out @droidmonkey.

I am using version 2.7.1 and have a tag which when clicked displays “No Results”.

Should I open a separate issue?

**Comment by droidmonkey** [comment] 2022-08-17 00:01
Do you have groups where you have disabled searching? Please open a new issue if so, we probably shouldn't show tags in groups that cannot be searched.

**Comment by sunknudsen** [comment] 2022-08-17 13:21
@droidmonkey

> Do you have groups where you have disabled searching?

No… all groups are set to “Inherit from parent group (Enable)”.

**Comment by droidmonkey** [comment] 2022-08-17 17:32
And you aren't talking about the predefined searches at the top of the tags list, correct?

**Comment by sunknudsen** [comment] 2022-08-17 17:55
@droidmonkey Correct… tag is called “privacyguides”.

**Closed as completed** 2022-09-08 10:46 UTC
Labels: feature: Tags

**Comment by sunknudsen** [comment] 2022-09-08 18:18
@droidmonkey Figured it out after seeing https://github.com/keepassxreboot/keepassxc/pull/8435… item in bin had tag.
