### ISSUE TITLE
Add alternative keys for drag&drop copying items between databases

### ISSUE THREAD

**Issue by CodingSpiderFox** [keepassxreboot/keepassxc#3594] opened 2019-10-01 16:59 UTC
Reproduce:

Open two databases, the first having at least one entry.
Hold left CTRL key and left-click drag the item from the first tab into the second tab. 

Result: the item is MOVED to the second database.

From MS Windows file explorer, I'm used to use left CTRL key as copy shortcut when draging and dropping files in the file explorer.

I saw that the ALT key can be used in KeepassXC to do that when dragging and dropping items between the open databases tabs.

I think it would be more intuitive to let CTRL key trigger this behaviour, too.

**Comment by droidmonkey** [comment] 2019-10-01 17:31
Also, in explorer you can right click drag an item and it will show a context menu to choose the desired action on drop.

**Comment by DJCrashdummy** [comment] 2020-03-29 13:09
isn't this issue already fixed? - at least at the linux built with a MATE-GUI (if this makes a difference) it seems so...

**Comment by droidmonkey** [comment] 2020-03-29 13:40
On Windows this does not work properly and needs to be fixed.

**Comment by droidmonkey** [comment] 2022-03-21 21:03
Duplicate of #7272

**Closed by droidmonkey** 2022-03-21 21:03 UTC
Labels: new feature
