### ISSUE TITLE
KeepassXC not exiting cleanly since 2.5.1 release

### ISSUE THREAD

**Issue by meelten** [keepassxreboot/keepassxc#4308] opened 2020-02-10 00:58 UTC
##  Expected Behavior

KeepassXC should terminate it's process on program exit.

## Current Behavior

About 80% of the times after exiting KeepassXC (either with "X" button or Database->Quit) the keepassxc process will not terminate but hang and only way to get rid of it is using kill command. It all started precisely with 2.5.1 release (never happened before) and is still present in 2.5.3. 

## Steps to Reproduce

1. Open KeepassXC with database and let it run for some time.
2. Close KeepassXC.
3. Check if the app was closed successfully (process was terminated).

## Context

Desktop environment is latest KDE Plasma. I don't use minimize to tray option and don't have any extensions enabled except autotype. I had enabled "save database on exit" but disabling it makes no difference. Making/not making changes to the database does not affect this at all. Also I believe running Keepass in longer sessions makes probability of this bug higher. Usually I have database open for all day and reproducibility is almost 100%. But it seems like with short sessions it usually manages to exit properly.

## Debug Info

KeePassXC - Version 2.5.3
Revision: f8c962b

Qt 5.14.1
Debugging mode is disabled.

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 5.5.2-arch1-1

Enabled extensions:
- Auto-Type

**Comment by droidmonkey** [comment] 2020-02-10 01:48
Duplicate of #4249. I actually reproduced this issue today but could not determine where the failure occurs. Although clearly some change in 2.5.1 started the issue. I wish there was a reliable way to reproduce this for debugging.

**Closed by droidmonkey** 2020-02-10 01:48 UTC
Labels: bug
