### ISSUE TITLE
KeepassXC 2.2.4 crashes on search attempt

### ISSUE THREAD

**Issue by RaSpirit** [keepassxreboot/keepassxc#1399] opened 2018-01-18 16:42 UTC
I just installed updated version from PPA and I'm getting the issue when I try to use search after entering 2-4 symbols the program crashes. Same happens for manually built version. Previous version worked fine (not sure what version it was). Using with database, that was created by KeepassXC earlier.

### KeepassXC version
2.2.4 from [PPA](http://ppa.launchpad.net/phoerious/keepassxc/ubuntu)
For manual building code was downloaded from [release archive](https://github.com/keepassxreboot/keepassxc/releases/download/2.2.4/keepassxc-2.2.4-src.tar.xz)

KeePassXC - Version 2.2.4
Revision: 4723f66

Libraries:
- Qt 5.5.1
- libgcrypt 1.6.5

Operating system: Linux Mint 18.3
CPU architecture: x86_64
Kernel: linux 4.13.0-26-generic

Enabled extensions: None

### Linux distributive 
`Linux Mint 18.3 Sylvia`

## Logs Info
Found this in syslog:

```[177592.922696] keepassxc[8467]: segfault at 55ff00000011 ip 00007f759f7b3ae8 sp 00007ffddc317400 error 4 in libQt5Core.so.5.5.1[7f759f563000+4c5000]```

Related part of `dmesg` output:

```
[176333.234361] psmouse serio1: Touchpad at isa0060/serio1/input0 - driver resynced.
[177151.271575] keepassxc[27674]: segfault at 55d400000011 ip 00007f0d24968ae8 sp 00007ffc05bcf300 error 4 in libQt5Core.so.5.5.1[7f0d24718000+4c5000]
[177199.936630] keepassxc[4487]: segfault at 55b400000011 ip 00007f19b3a7eae8 sp 00007fff6be817f0 error 4 in libQt5Core.so.5.5.1[7f19b382e000+4c5000]
[177221.263570] keepassxc[5130]: segfault at 557a00000011 ip 00007f4d07c0cae8 sp 00007ffeaad32970 error 4 in libQt5Core.so.5.5.1[7f4d079bc000+4c5000]
[177264.529396] psmouse serio1: Touchpad at isa0060/serio1/input0 lost sync at byte 6
[177264.566013] psmouse serio1: Touchpad at isa0060/serio1/input0 - driver resynced.
[177399.647538] psmouse serio1: Touchpad at isa0060/serio1/input0 lost sync at byte 6
[177399.660612] psmouse serio1: Touchpad at isa0060/serio1/input0 - driver resynced.
[177592.922696] keepassxc[8467]: segfault at 55ff00000011 ip 00007f759f7b3ae8 sp 00007ffddc317400 error 4 in libQt5Core.so.5.5.1[7f759f563000+4c5000]
[178080.235638] psmouse serio1: Touchpad at isa0060/serio1/input0 lost sync at byte 6
[178080.250724] psmouse serio1: Touchpad at isa0060/serio1/input0 - driver resynced.
[178083.680552] psmouse serio1: Touchpad at isa0060/serio1/input0 lost sync at byte 6
[178083.716090] psmouse serio1: Touchpad at isa0060/serio1/input0 - driver resynced.
[178340.731004] keepassxc[9217]: segfault at 240000032f ip 00007f1261fadae8 sp 00007ffc0255d930 error 4 in libQt5Core.so.5.5.1[7f1261d5d000+4c5000]
```

**Comment by louib** [comment] 2018-01-18 16:46
Pretty sure this is a duplicate of https://github.com/keepassxreboot/keepassxc/issues/1254

Can you add the complete debug info in the description?
Was it a new database or an imported database?

**Comment by RaSpirit** [comment] 2018-01-18 17:10
Hi @louib 

Thanks for response. Yes it looks like duplicate (sorry that missed it). Just updated description.

**Closed** 2018-01-18 19:36 UTC
Labels: duplicate
