### ISSUE TITLE
Option to prevent save from snapping back to Root

### ISSUE THREAD

**Issue by hysan** [keepassxreboot/keepassxc#297] opened 2017-02-12 05:05 UTC
When saving, the selected group always resets back to the Root group. This can be a minor annoyance when you want to save a newly created entry and then use it right away. Could this behavior be made to be configurable?

**Comment by phoerious** [comment] 2017-02-12 11:40
Please check if you have the latest version of KeePassXC. This issue has been fixed already (#144, #176).

Also please don't delete the issue template next time. It prevents situations like this where we don't know if this is somehow a regression or maybe you using an old version.

**Comment by phoerious** [comment] 2017-02-12 11:43
Actually, the fix is not yet in 2.1.1. It was only merged into develop. I'm therefore closing this as a duplicate of #144.

**Closed by phoerious** 2017-02-12 11:43 UTC

**Comment by hysan** [comment] 2017-02-12 15:11
Thanks. Still new to Github so wasn't sure about how to report things. I'll remember to use the template next time.
