### ISSUE TITLE
Database is not locked when being edited

### ISSUE THREAD

**Issue by Ana06** [keepassxreboot/keepassxc#3362] opened 2019-07-09 19:33 UTC
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Current Behavior
If while you are editing an entry of the database you lock the computer, the database is not locked and instead the following message is shown:

![image](https://user-images.githubusercontent.com/16052290/60916933-01c21e00-a290-11e9-9130-360cd04e5bbe.png)

If you click _Cancel_, the database hasn't been locked and you can still access the database.

## Expected Behavior

I expect that the database is locked when I lock the computer, even if I am editing. It seems a risk.

## Possible Solution
The database is locked even if an element is being edited.

As we don't want to lose the changes of the edited fields, the best option would be that the changes can be recovered after unlocking the database. In other words, the questions about discarding changes should be made after the database is unlocked.

## Debug Info
KeePassXC - Version 2.4.3
Revision: 5d6ef0c

Qt 5.9.7
Debugging mode is disabled.

Operating system: openSUSE Leap 15.1
CPU architecture: x86_64
Kernel: linux 4.12.14-lp151.28.7-default

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.2

**Comment by droidmonkey** [comment] 2019-07-09 20:01
Duplicate of #721

**Closed by droidmonkey** 2019-07-09 20:01 UTC
Labels: bug
