### ISSUE TITLE
Crash when opening DB using hardware key

### ISSUE THREAD

**Issue by shift-crops** [keepassxreboot/keepassxc#4234] opened 2020-01-25 07:44 UTC
When trying to use the hardware key (YubiKey) to unlock the DB, the application crashes if KeePassXC is closed, reopened and touch the YubiKey.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
DB will be unlocked when you touch YubiKey.

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
Application crashes
![crash](https://user-images.githubusercontent.com/5857144/73117938-89534e00-3f90-11ea-990f-20d8c31182be.png)

This message has the following meaning.
```
The instruction at 0x94aaa referenced memory at NULL.
Memory could not be read.
```

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )

1. Enable `Minimise instead of app exit`
    - Tools > Settings > General > Basic Settings > General
2. Attempt to unlock DB using YubiKey.
    - After pressing OK, do not touch the YubiKey
3. Close KeePassXC
    - Press [x] at top right or Alt-F4
4. Launch KeePassXC again.
5. Crash when touching YubiKey

The app is crashing here.
![debug](https://user-images.githubusercontent.com/5857144/73118087-6e81d900-3f92-11ea-976b-44933fd2b3ab.PNG)

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )
Just trying to open the DB.

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.5.3
Revision: f8c962b

Qt 5.13.2
Debugging mode is disabled.

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.18363

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by droidmonkey** [comment] 2020-01-25 12:03
This is most likely the same crash as switching db tabs while unlocking

**Comment by droidmonkey** [comment] 2020-01-25 13:08
Confirmed, this is a duplicate of #4187

**Closed by droidmonkey** 2020-01-25 13:08 UTC
Labels: bug, crash :boom:, plugin: YubiKey
