### ISSUE TITLE
Cannot up app after latest macOS update: Code Signature Invalid

### ISSUE THREAD

**Issue by RoarSlot** [keepassxreboot/keepassxc#4496] opened 2020-03-27 06:45 UTC
Cannot up app after latest macOS update: Code Signature Invalid

rocess:               KeePassXC [724]
Path:                  /Applications/KeePassXC.app/Contents/MacOS/KeePassXC
Identifier:            org.keepassx.keepassxc
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           KeePassXC [724]
User ID:               501

Date/Time:             2020-03-27 07:42:23.623 +0100
OS Version:            Mac OS X 10.15.4 (19E266)
Report Version:        12
Anonymous UUID:        E8ED3D49-85B7-8EDA-438D-69E30B0BE984

Time Awake Since Boot: 39 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (Code Signature Invalid)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace CODESIGNING, Code 0x1

kernel messages:

VM Regions Near 0 (cr2):
--> 
    __TEXT                 000000010cdca000-000000010d15c000 [ 3656K] r-x/r-x SM=COW  

Thread 0 Crashed:
0                                	0x000000010d5f1000 _dyld_start + 0

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x0000000000000000  rcx: 0x0000000000000000  rdx: 0x0000000000000000
  rdi: 0x0000000000000000  rsi: 0x0000000000000000  rbp: 0x0000000000000000  rsp: 0x00007ffee2e35c10
   r8: 0x0000000000000000   r9: 0x0000000000000000  r10: 0x0000000000000000  r11: 0x0000000000000000
  r12: 0x0000000000000000  r13: 0x0000000000000000  r14: 0x0000000000000000  r15: 0x0000000000000000
  rip: 0x000000010d5f1000  rfl: 0x0000000000000200  cr2: 0x0000000000000000
  
Logical CPU:     0
Error Code:      0x00000000
Trap Number:     0

Binary Images:
       0x10cdca000 -        0x10d15bfff + (0) <16AE8CED-0E4C-3291-AE43-913B0D7192FF> 
       0x10d5f0000 -        0x10d681eff + (750.5) <1F893B81-89A5-3502-8510-95B97B9F730D> 

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 135
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=4776K resident=0K(0%) swapped_out_or_unallocated=4776K(100%)
Writable regions: Total=8408K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=8408K(100%)
 
                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
STACK GUARD                       56.0M        1 
Stack                             8192K        1 
__DATA                             360K        4 
__DATA_CONST                        20K        1 
__LINKEDIT                         536K        2 
__TEXT                            4240K        2 
shared memory                        8K        2 
===========                     =======  ======= 
TOTAL                             69.0M       13

**Comment by wesmi** [comment] 2020-03-27 07:41
I have this exact problem to a T.  Additional info from my setup that might help:

KeePassXC only fails to start for me on my MacBook 12" Retina (2017).  I had this same problem when running the beta builds of MacOS Catalina (10.15.4) and continues into the release today.  (I did a full reinstall from MacOS Recovery to make sure no stray beta builds were present.)

However, KeePassXC *starts successfully* on my Mac Mini (2018), on which I also run beta builds of Catalina.

Running "sudo spctl --master-disable" doesn't allow KeePassXC to start.  On both systems, I installed from Homebrew though I did remove the Homebrew install on my laptop and reinstall using the direct download from the KeePassXC site with no change.

**Comment by twjacobsen** [comment] 2020-03-27 07:57
I just updated to latest version of MacOS last night, and I'm getting the exact same issue. Installed view Homebrew, 2015 Macbook Pro. Pretty critical to not be able to access passwords

**Comment by phoerious** [comment] 2020-03-27 08:49
Duplicate of #4398.

**Comment by bassqualle** [comment] 2020-03-27 08:49
Same problem: after the most recent upgrade of MacOS keePassXC is no longer starting up.

Workaround: Re-installing the app from DMG-image fixed the problem.

**Closed by phoerious** 2020-03-27 08:49 UTC
Labels: bug
