### ISSUE TITLE
Add high resolution toolbar icons (windows)

### ISSUE THREAD

**Issue by jsoref** [keepassxreboot/keepassxc#783] opened 2017-07-16 19:50 UTC
This is a dell laptop w/ resolution 3200x1800 (recommended) and font size 250% (recommended).
I'm not particularly used to using high resolution laptops....

Most applications (e.g. Chrome, Notepad, WinSCP) look fine with these settings.

## Expected Behavior

Buttons should be reasonably sized in proportion to the UI font.

## Current Behavior
![image](https://user-images.githubusercontent.com/2119212/28250726-b5a42144-6a3d-11e7-8073-cb2b59eb59d3.png)
![image](https://user-images.githubusercontent.com/2119212/28250737-03d0df6a-6a3e-11e7-8338-f595445a67d5.png)

## Possible Solution

Add additional resolutions for art and code w/ Qt.

See http://doc.qt.io/qt-5/highdpi.html for information

## Steps to Reproduce (for bugs)
1. Have a High DPI laptop or bump your font scaling up in display preferences

## Context
The toolbar buttons are nearly invisible

## Debug Info
KeePassXC - Version 2.2.0
Revision: caa49a8ef3ee28ed478192389b21d61107b3b8e0

Libraries:
- Qt 5.9.0
- libgcrypt 1.7.7

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.15063

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

**Comment by phoerious** [comment] 2017-07-16 19:53
Duplicate of #548

**Closed by phoerious** 2017-07-16 19:53 UTC
