### ISSUE TITLE
Add support to automatically open additional databases when opening a database (KeeAutoExec plugin)

### ISSUE THREAD

**Issue by scic** [keepassxreboot/keepassxc#529] opened 2017-04-26 09:30 UTC
I would like the functionality of the **[KeeAutoExec](http://keepass.info/plugins.html#keeautoexec) plugin** for Keepass to be available in keepassxc:

When I open a "master" database keepassxc opens multiple other databases automatically. The information to open these databases (path, password) is stored in the "master" database.

It would be best if the same configuration that the KeeAutoExec plugin uses is also used for keepassxc. So that the configuration in the database is compatible.

**Comment by TheZ3ro** [comment] 2017-04-26 09:56
Duplicate of #477, use that Issue instead of opening a new one. Closing

**Closed by TheZ3ro** 2017-04-26 09:56 UTC
