### ISSUE TITLE
KeePassXC-Browser, Firefox Add-On - message "Timeout or not connected to KeePassXC"

### ISSUE THREAD

**Issue by royracer** [keepassxreboot/keepassxc#2077] opened 2018-06-28 00:15 UTC
## Expected Behavior

KeePassXC-Browser add-on connects from Firefox

## Current Behavior
KeePassXC-Browser, Firefox Add-On - "Timeout or not connected to KeePassXC". Reload button does not seem to do anything.

Firefox is my primary browser. I think keepassxc-proxy is not running (from Firefox). For testing purposes, I checked Google Chrome (KeePassXC Browser Integration tab) and added the Chrome extension. Works fine in Chrome and keepassxc-proxy is running (after Chrome is opened but not from Firefox).

Results from pgrep -la keepassxc:
```
2789 keepassxc
3664 keepassxc-proxy chrome-extension://oboonakemofpalcgghocfoadofidjkkk/
```
The keepassxc-proxy process that runs is only after opening Google Chrome. It seems keepassxc-proxy is not running from Firefox.

Contents of ~/.mozilla/native-messaging-hosts/org.keepassxc.keepassxc-browser.json:
```
{
    "allowed_extensions": [
        "keepassxc-browser@keepassxc.org"
    ],
    "description": "KeePassXC integration with native messaging support",
    "name": "org.keepassxc.keepassxc_browser",
    "path": "/home/roy/Programs/AppImage/keepassxc/KeePassXC-2.3.3-x86_64.AppImage",
    "type": "stdio"
}
```

Contents of ~/.config/google-chrome/NativeMessagingHosts/org.keepassxc.keepassxc-browser.json:
```
{
    "allowed_origins": [
        "chrome-extension://iopaggbpplllidnfmcghoonnokmjoicf/",
        "chrome-extension://oboonakemofpalcgghocfoadofidjkkk/"
    ],
    "description": "KeePassXC integration with native messaging support",
    "name": "org.keepassxc.keepassxc_browser",
    "path": "/home/roy/Programs/AppImage/keepassxc/KeePassXC-2.3.3-x86_64.AppImage",
    "type": "stdio"
}
```
Paths are the same and match expected values from Troubleshooting Guide. Both json files (Firefox and Chrome) have the same rw-rw-r-- permissions for the same user.

I turned on debugging in Firefox but it is not logging anything to console.

Both Chrome and Firefox are checked under KeePassXC/Browser Integration tab.

Other steps taken:

- I have NoScript add-on in Firefox. I have disabled temporarily in case that was interfering.
- Closed Firefox bunch of times, rebooted OS.
- Have checked Troubleshooting Guides
- Looked through GitHub issues and tried things found there

Other possible items of interest:
- Previously had the snap package installed and was using the "legacy browser integration".
- Uninstalled snap package
- Removed the older http-connector add-on/extension from Firefox and Chrome
- Removed the "legacy" browser connection entries in the KeePassXC database
- Installed AppImage version in order to use new browser integration.
- "Legacy Browser Integration" is unchecked after install
- Don't know if there is "something left over" that did not get reset or deleted, either from the prior KeePassXC snap install or the older browser add-on/extension

## Possible Solution

I have not been able to manually run keepassxc-proxy as suggested in the Troubleshooting Guide. I checked 'varjolintu's repo and other sources and wasn't able to do it. I don't think it can be done with the AppImage KeePassXC version but maybe I am mistaken.

Don't know if it is a permissions issue with Firefox?

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Debug Info

KeePassXC - Version 2.3.3
Revision: 0a155d8
Distribution: AppImage

Libraries:
- Qt 5.9.4
- libgcrypt 1.8.1

Operating system: Ubuntu 16.04.4 LTS
CPU architecture: x86_64
Kernel: linux 4.4.0-128-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

Firefox Version 60.0.2 (64-bit)
Chrome Version 67.0.3396.99 (Official Build) (64-bit)
KeePassXC-Browser Version 1.1.7 (both Chrome and Firefox)

**Comment by varjolintu** [comment] 2018-06-28 06:39
Here's a related PR that should've fixed the issue months ago: https://github.com/keepassxreboot/keepassxc/pull/1530.

I'll do some testing with the AppImage.

**Comment by varjolintu** [comment] 2018-06-28 07:03
I quickly tested this with my Arch system and I couldn't reproduce the issue. I downloaded the official AppImage, enabled the browser integration (and enabled the automatic update of native messaging scripts from the Advaced tab). Then everything worked. Even tried to close KeePassXC and reopened the AppImage again. Then reloaded the extension from the popup and everything was working.

Have you tried to make a new temporary profile to Firefox via about:profiles, and see if it has the same issue with newly installed extension?

**Comment by royracer** [comment] 2018-06-28 17:36
I checked "Update native messaging manifest files at startup". I removed FF add-on and re-installed while also closing/opening KeePassXC a few times.

I created a new Firefox profile for testing. Same issue.

I deleted the AppImage file, downloaded a new copy. Same issue.

I created a new temporary db (wasn't sure if the db file had some of the settings besides pwd info).

I found it interesting that the old KeePassXC settings were retained even after deleting the AppImage file and re-downloading. I thought the settings would reset to default. Could there be an issue with data being stored/retained instead of starting clean?

Perhaps (if I am told where to look/what to do) I can make sure all appropriate "legacy" files and dependent libraries are deleted (except kdbx file) and can re-install AppImage and library dependencies "fresh"?

I can also go back to the old http-connector. That was working fine for me (with snap package). I only wanted to move to keepassxc-browser because of the deprecation message and know the [snap package issue was open](https://github.com/keepassxreboot/keepassxc/issues/1598).

Thanks to the community for your continued development of this very useful program.

**Comment by varjolintu** [comment] 2018-06-29 04:54
@royracer One thing you can try of course is to test another user or a frest install in a VM. But it takes time, so in the meantime I could try to do the same: download an older AppImage with a fresh Ubuntu VM, then the latest one and see if it reproduces the issue.

**Comment by varjolintu** [comment] 2018-06-29 05:47
@royracer Just tested this with a fresh Xubuntu install. First I downloaded AppImage for 2.2.4 and made a database. Then switched to AppImage 2.3.3 and enabled browser integration. Everything works fine.

Can you try if there's any difference if you delete the `~/.config/keepassxc/keepassxc.ini` before starting KeePassXC again?

**Comment by royracer** [comment] 2018-06-29 19:10
I deleted the keepassxc.ini file then started KeePassXC. Same issue. Chrome connects. Firefox does not (ie same issue).

I did notice some possibly odd behavior after deleting the config file. Some settings were reset, notably "_Settings/Security/Lock databases when session is locked or lid is closed_" and "_Settings/Browser Integration/Enable KeePassXC browser integration_".

However, the checkboxes under "_Settings/Browser Integration/Advanced_" for "_Google Chrome_" and "_Firefox_" did not get reset and stayed checked.

I can try the VM install sometime over the weekend. I suspect it will work fine as you already tested. Perhaps it is specific to my environment (or having the snap first then changing to AppImage) or others could be experiencing same issue.

Also, I would be happy to test both launching the proxy by starting the AppImage with positional proxy parameter or checking CHROME_WRAPPER or MOZ_LAUNCHED_CHILD environment variables, if I can be pointed in the right direction.

**Comment by droidmonkey** [comment] 2019-02-01 23:16
@royracer still an issue?

**Comment by ruifortes** [comment] 2019-02-17 10:35
On Ubuntu 18.10 I can't connect using Chromium and Firefox only connects it I already have KeePassXC opened.
Firefox can start KeePassXC if I disable "Use a proxy application between KeePassXC and browser extension", not in Chromium

**Comment by droidmonkey** [comment] 2019-02-17 17:04
@ruifortes what version of KeePassXC are you using. There is a known bug in 2.3.1 that causes this issue.

**Comment by ruifortes** [comment] 2019-02-19 01:38
Hi...I have:
KeePassXC 2.3.4
Firefox 65.0
Ubuntu 18.10
GNOME 3.30.1

**Comment by varjolintu** [comment] 2019-02-19 06:01
@ruifortes That's how the extension works. KeePassXC needs to be open for the connection. Are you using snap versions of both?

**Comment by ruifortes** [comment] 2019-02-20 19:19
ah..ok, thought there would be some kind of service version you could run.
I was annoying to have the app constantly open but I found that you can make keepass minimize (or close) to the system tray.
Thanks

**Comment by royracer** [comment] 2019-02-25 03:50
> @royracer still an issue?

Still an issue.

Just upgraded KeePassXC to version 2.3.4 (via AppImage).

KeePassXC-Browser integration works with Chrome but not with Firefox.

Able to use the legacy KeePassHttp-Connector integration for Firefox

**Comment by droidmonkey** [comment] 2019-02-25 04:15
Is your Firefox the snap version?

**Comment by varjolintu** [comment] 2019-02-25 06:42
@royracer Check the JSON file inside `~/.mozilla/native-messaging-hosts` and make sure it points to the right binary (keepassxc-proxy).

**Comment by royracer** [comment] 2019-02-25 07:50
Where would the keepassxc-proxy binary be?

The current path in the Firefox JSON file is:
    "path": "/home/roy/Programs/AppImage/keepassxc/KeePassXC-2.3.4-x86_64.AppImage",

What should the correct path be?

Note, the Chrome json file has the same path as above and is working.

I also don't need to use the AppImage at all. Legacy Http-Connector still works with Firefox.

Also, I can try the Ubuntu distribution or snap image. It was awhile ago, but if I remember correctly, I only switched to AppImage because an older version of KeePassXC said to upgrade as the older browser integration was being deprecated.

**Comment by phoerious** [comment] 2019-02-25 08:06
For the AppImage, that is correct (assuming that is the correct path to your AppImage). All executables are packaged within the AppImage and selected depending on the caller's environment.

**Comment by krya-kryak** [comment] 2019-03-21 09:05
I've first stumbled upon this bug request before actually connecting firefox with freshly installed keepassxc (2.4.0 snap in my case) and had just the same symptoms.

@royracer, I can't help but notice that you have `~/.mozilla/native-messaging-hosts/org.keepassxc.keepassxc-browser.json` as a path for your firefox config bit. This didn't work for me either, but after that I actually read the snap integration script I've changed the file name to `~/.mozilla/native-messaging-hosts/org.keepassxc.keepassxc_browser.json` (note the underscore) and everything worked like a charm. Where did that filename with a dash come from?

**Comment by droidmonkey** [comment] 2019-03-21 10:43
Oh snap did I typo?

**Comment by royracer** [comment] 2019-03-21 12:56
I think it was a typo. It is the file with underscore at:
~/.mozilla/native-messaging-hosts/org.keepassxc.keepassxc_browser.json

Contents are:
```
{
    "allowed_extensions": [
        "keepassxc-browser@keepassxc.org"
    ],
    "description": "KeePassXC integration with native messaging support",
    "name": "org.keepassxc.keepassxc_browser",
    "path": "/home/roy/Programs/AppImage/keepassxc/KeePassXC-2.3.4-x86_64.AppImage",
    "type": "stdio"
}
```
As far as I am concerned, if this is not a known bug and not an issue for anyone else, it can be closed. Maybe it is just something with my local setup.

I am using the legacy KeePassHttp-Connector with Firefox just fine. At some point, I can uninstall the AppImage and try either the Snap or PPA versions.

**Comment by droidmonkey** [comment] 2019-03-21 17:24
OK, I just checked. Both the KeePassXC application and my Snap utility script write the correct filename "org.keepassxc.keepassxc_browser.json" with the underscore. I am closing this issue since it is not valid.

**Closed by droidmonkey** 2019-03-21 17:24 UTC
Labels: plugin: Browser integration
