### ISSUE TITLE
ChaCha20 is too restrictive about IV size (Database lockout)

### ISSUE THREAD

**Issue by ghost** [keepassxreboot/keepassxc#7590] opened 2022-03-22 17:40 UTC
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Cannot unlock database

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Try unlocking database with password
2. Error: `Fehler beim Öffnen der Datenbank: SymmetricCipher::init: Ungültige IV-Größe von  of 16 für ChaCha20.`

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Unlocking did function with version 2.6.6

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Error: `Fehler beim Öffnen der Datenbank: SymmetricCipher::init: Ungültige IV-Größe von  of 16 für ChaCha20.`

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.0
Revision: d7a9ef4

Qt 5.15.3
Diagnosemodus ist deaktiviert.

Betriebssystem: Windows 10 Version 2009
CPU-Architektur: x86_64
Kernel: winnt 10.0.19044

Aktivierte Erweiterungen:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare
- YubiKey
- Schnelle Entsperrung

Kryptographische Bibliotheken:
- Botan 2.18.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10 Pr0

**Comment by phoerious** [comment] 2022-03-22 21:22
@droidmonkey Sounds like something broke here with Botan. But might also be an issue with the database, since we have tests for Cha-Cha-encrypted databases.

**Comment by phoerious** [comment] 2022-03-22 21:28
Probably an issue with the database, because I cannot reproduce this at all. Try opening the database with the old 2.6.6 version. If that works, save it as AES and then again as ChaCha20.

**Comment by ghost** [comment] 2022-03-23 10:00
@phoerious 
1. As you suggested, I opened the db with the 2.6.6-version: no problem (as before)
2. Then I saved as AES, opened it with the 2.7.0-version: no problem
3. Opened the AES-Version with 2.6.6-version, saved it as ChaCha20. Tried opening the ChaCha20 with 2.7.0-version: again `Fehler beim Öffnen der Datenbank: SymmetricCipher::init: Ungültige IV-Größe von of 16 für ChaCha20`
4. I tried solving by exporting the AES from the 2.6.6-version as csv. Created a new db with the 2.7.0-version and ChaCha20 and imported the csv. But no luck: again `Fehler beim Öffnen der Datenbank: SymmetricCipher::init: Ungültige IV-Größe von of 16 für ChaCha20`

At last I solved it for me, by creating a new db with the 2.7.0-version using AES and importing the csv.

IMO the ChaCha20 in the 2.7.0-version seems somehow broken.

Edit: I was able to reproduce this issue with 2 other db's as well.

**Comment by droidmonkey** [comment] 2022-03-23 10:43
It is a bug because ChaCha20 supports a min and a max IV size. Just stick to AES for now or 2.6.6. Don't use your csv imported database you lose a lot of information.

**Comment by tagform** [comment] 2022-03-30 08:20
I still cannot unlog my database with keypassxc 2.7.0

Error:
Fehler beim Öffnen der Datenbank: XML Fehler:
Vorzeitiges Ende des Dokuments.
Zeile 15573, Spalte 17

Any solutions so far?

I am just a "stupid user" ...

**Comment by droidmonkey** [comment] 2022-03-30 10:20
You need to downgrade to 2.6.6 for now

**Comment by tagform** [comment] 2022-03-30 10:26
thanks! where is v.2.6.6 available?

**Comment by droidmonkey** [comment] 2022-03-30 10:32
https://github.com/keepassxreboot/keepassxc/releases/tag/2.6.6

**Comment by tagform** [comment] 2022-03-30 10:45
thanks a lot!

**Comment by tagform** [comment] 2022-03-30 10:49
2.6.6 same problem
??

Fehler beim Öffnen der Datenbank: XML Fehler:
Vorzeitiges Ende des Dokuments.
Zeile 15573, Spalte 17

**Comment by phoerious** [comment] 2022-03-30 11:00
That's a different error. You file seems to be corrupt.

**Comment by tagform** [comment] 2022-03-30 11:06
corrupt = broken? what can i do?

**Comment by phoerious** [comment] 2022-03-30 11:07
Do you have a backup?

**Comment by tagform** [comment] 2022-03-30 11:08
no

**Comment by phoerious** [comment] 2022-03-30 11:11
Well, then you are out of luck, I'm afraid. Always have backups of your database. You can try to recover the what's left in the database with the CLI:
```
keepassxc-cli export database.kdbx
```

**Comment by droidmonkey** [comment] 2022-03-30 11:40
OK, I looked into this, we are actually asking Botan if the IV size is correct and Botan is coming back saying it is not. So we aren't doing anything restrictive on our end.

https://github.com/randombit/botan/blob/eb766403edf977837999d6ed31523493c62d6259/src/lib/stream/chacha/chacha.cpp#L296-L299

```
bool ChaCha::valid_iv_length(size_t iv_len) const
   {
   return (iv_len == 0 || iv_len == 8 || iv_len == 12 || iv_len == 24);
   }
```

@randombit I tried looking this up but came up empty, are 16 byte nonces unsupported for ChaCha?

**Comment by randombit** [comment] 2022-03-30 12:53
@droidmonkey 16 byte nonce for ChaCha is not something I have seen before.

8 byte nonce is original ChaCha
12 byte nonce is used in the IETF variant of ChaCha20Poly1305
24 byte nonce is XChaCha
0 nonce is our shorthand for "all zero nonce"

And TBH I don't know how a 16 byte ChaCha nonce would work. ChaCha has only limited space for the nonce and 16 bytes exceeds it. That said apparently libgcrypt does accept this, so I suppose we can reverse engineer what it is doing. I'll look into this asap.

If libgcrypt is doing what I bet it is doing (abusing the stream position word to hold the extra 4 bytes) you will be able to emulate the behavior using `StreamCipher::seek`.

Update: [that was it](https://github.com/gpg/libgcrypt/blob/master/cipher/chacha20.c#L391-L397)

I suppose for convenience it's fine to implement that in the library, it's non-standard for sure but basically harmless. However that isn't helping you in the near term. Until then what you would need to do is (untested but 99% sure):

If given a 16 byte nonce for ChaCha, use the last 12 bytes as the nonce. Take the first 4 bytes, convert it to an integer using little-endian convention, and call `StreamCipher::seek` on `n*64`.

**Comment by droidmonkey** [comment] 2022-03-30 13:58
I recommend NOT making a change to the library. I'll implement the workaround on our end so people can open their 16-byte nonce databases and then we'll upconvert them to 24 byte nonces. Do you know if libgcrypt support 24 byte nonce?

**Comment by randombit** [comment] 2022-03-30 14:11
> Do you know if libgcrypt support 24 byte nonce?

AFAICT from a quick look at their code, it does not.

**Comment by tagform** [comment] 2022-03-30 16:06
> Well, then you are out of luck, I'm afraid. Always have backups of your database. You can try to recover the what's left in the database with the CLI:
> 
> ```
> keepassxc-cli export database.kdbx
> ```

I could repair the database with keepass2. luckily, no data lost.

**Comment by randombit** [comment] 2022-03-30 18:57
FYI - it turns out this is also how [OpenSSL](https://www.openssl.org/docs/man1.1.1/man3/EVP_chacha20_poly1305.html) does ChaCha nonces, so I will be adding 128 bit support upstream as well.

**Comment by phoerious** [comment] 2022-03-30 19:24
Which nonce size does KeePass2 use?

**Comment by droidmonkey** [comment] 2022-03-31 11:53
KeePass2 uses IV of 12 bytes. It cannot open a database with IV size 24.

**Comment by tagform** [comment] 2022-03-31 11:58
just one more information for you developers. I could repair my corrupt database with keepass2 but it turned out that after a few logins with keepassxc v.2.7 the failure (corrupt database) appeared again. i switched back to v.2.6.6 . everything works fine.

**Comment by droidmonkey** [comment] 2022-03-31 11:59
Are you using ChaCha20 encryption algorithm?

**Comment by tagform** [comment] 2022-03-31 12:00
> Are you using ChaCha20 encryption algorithm?

i am just a "stupid user". no clue of programing, i am afraid.

**Comment by droidmonkey** [comment] 2022-03-31 12:02
You are on the wrong discussion issue then

**Comment by droidmonkey** [comment] 2022-03-31 21:58
OK so here is the deal, 2.6.6 creates a database using ChaCha20 with an IV of size 12. Therefore, this database must have been created by some other program. At this time, I am not going to build in any work arounds for IV size 16 and I am closing this issue as a result. KeePassXC 2.7.0 creates ChaCha20 databases with IV size 12 and so does KeePass2.

To work around the invalid use of IV size 16 you need to convert your database to AES on another program and then back to ChaCha20 using KeePassXC.

**Closed as completed by droidmonkey** 2022-03-31 21:58 UTC
