### ISSUE TITLE
KeePassXC crashes on start up after Mac OS upgrade to 10.14.6 (18G4032)

### ISSUE THREAD

**Issue by sk8404** [keepassxreboot/keepassxc#4487] opened 2020-03-25 15:26 UTC
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
[NOTE]: # Programm opens

## Current Behavior
[NOTE]: # OS message/dialog: KeePassXC quit unexpectedly ..... Ignore/Report...

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1.
2.
3.

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION
Revision: REVISION

Libraries:
- LIBS

Operating system: OS
CPU architecture: ARCH
Kernel: KERNEL

Enabled extensions:
- EXTENSIONS

**Comment by fpavageau** [comment] 2020-03-25 15:33
#4486 was created for the same problem 5 minutes before this issue.

**Comment by varjolintu** [comment] 2020-03-25 15:35
Duplicate of https://github.com/keepassxreboot/keepassxc/issues/4398.

**Closed by varjolintu** 2020-03-25 15:35 UTC
Labels: duplicate
