### ISSUE TITLE
KeepassXC freezing and crashing when I search for a node

### ISSUE THREAD

**Issue by Flambi** [keepassxreboot/keepassxc#9429] opened 2023-05-16 12:59 UTC
## Overview
I have an issue with KeepassXC.

On Windows I can get into the database, but when I try to open an entry it will starts eating memory approx 2GB. CPU is fine there is no high concumption, but it hangs. I can't do much just crash after 20 sec.

On Linux it is doing the same but eating 1 core CPU 100% and memory usage is normal. Of course it is crashing as well after 20 sec when I try to open an entry.

I tested each version from Official site since 2.7.1. I tested on various OS in VM.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Unlock database with KeePassXC on Windows or Linux
2. Search for a specific entry (only for a specific node is killing it).

## Expected Behavior
It should not crash

## Actual Behavior
On Windows it starts eating memory (2GB) on Linux 1 CPU core goes to 100 %

## Context
Database is not corrupt because it works on Windows with KeePass and Keepassium on iOS with the same database.
Tried to delete the specific node which caused the crash. But still crashing.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.1 - 2.7.5 Appimage or install from repository
Revision: 7729648

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows/Linux
Desktop Env: Pantheon/Gnome/Mate/Cinnamon
Windowing System: X11/Wayland

**Comment by droidmonkey** [comment] 2023-05-16 14:06
How big is your database file and how many entries do you have?

**Comment by Flambi** [comment] 2023-05-16 15:19
It is 107 MB with 765 entries. I store there files as well, but none of them are larger than 3 MB.
I made no changes on the database, just upgraded KeePassXC. Previously it worked fine. Now if I downgrade it, still does not work either

**Comment by droidmonkey** [comment] 2023-05-16 15:52
I don't think this is a keepassxc problem. Please try using the flatpak distribution.

**Comment by Flambi** [comment] 2023-05-16 20:22
I tried the flatpak distribution on fresh install and gave me the same issue. I tried another database as well gave me the same result

**Comment by droidmonkey** [comment] 2023-05-16 21:44
Does it happen on a brand new database?

**Comment by Flambi** [comment] 2023-05-17 07:29
Yes, it does.
I tried to export everything to CSV and import. This will only brings the data witout attachments and favicons. I have the same experiences

**Comment by droidmonkey** [comment] 2023-05-17 09:46
Do you have a bunch of entries with references? If you don't know what that is then the answer is likely no.

**Comment by Flambi** [comment] 2023-05-17 10:13
Yes I use links inside the nodes, which leads to another nodes. I created them in KeePass

**Comment by droidmonkey** [comment] 2023-05-17 10:35
Ok, I am wondering if you have a circular reference and for whatever reason our check for that condition is not working now.

**Comment by Flambi** [comment] 2023-05-17 10:38
I'll check them, but are they working in KeePassXC as well?

**Comment by Flambi** [comment] 2023-05-17 11:09
Okay, this was the solution. If there are references which makes loop then it will just get into that loop. Delete loop reference and will work without any issue

Thank you!

**Comment by droidmonkey** [comment] 2023-05-17 11:12
That's a major bug that needs fixing though, reopening. Glad you could confirm it.

**Comment by Flambi** [comment] 2023-05-17 12:14
Okay, I have a backup from the original one, I can live without the links. Let me know, and I can help you test it.

**Comment by bf** [comment] 2024-04-22 08:58
Have same issue. Keepass on linux gnome wayland. Cursor is still blinking but rest of UI is frozen. Window can be resized, but no clicks are accepted. Click on "x" button does not close window. Need to `killall keepassxc` in order to restart it.

**Comment by bf** [comment] 2024-04-29 08:36
BTW I can reproduce it when I sign up for a website and generate a password for the new account. KeepasXC will show the "password generator" popup. Then I sign up for the website and press "store as 'new'". Then I go back to KeepassXC and press "X" on the password generator modal dialog. Then whole KeepasXC UI is frozen and needs to be killed with `killall keepassxc`.

**Comment by droidmonkey** [comment] 2024-04-29 10:21
That is a different issue

**Comment by bf** [comment] 2024-04-29 10:24
> That is a different issue

Both result in UI freeze, just wanted to share so someone can finally fix this issue. I don't understand what kind of code creates GTK UI freezes and I don't experience these kind of crashes in any of the other software I'm using in a gnome/gtk environment.

**Comment by droidmonkey** [comment] 2024-04-29 11:49
@bf I merged the fix to the password generator X-button freeze into the upcoming 2.7.8 release, we forgot to include it in the 2.7.7 release.

**Comment by Rebs77** [comment] 2024-05-28 09:21
Hi! Having the same problem... KeepassXc was wortking perfectly but since this monday it freezes and start "eating" memory when I try to unblock de database. 
How can I verify if the problem is the circular reference that has been refered above?
I have tried with my database and also with a new database e the problem is the same. I suppose it was some update that its creating the problem. 
My operating system is Windows 10 Entreprise LTSC.
![KeepassXC_freez](https://github.com/keepassxreboot/keepassxc/assets/171020450/06b50475-1f8a-4dfc-86d7-20b59137a477)

**Comment by droidmonkey** [comment] 2024-05-28 09:51
Did you make any entry references? Did you change your database encryption settings?

**Comment by Rebs77** [comment] 2024-05-28 10:01
Hi, I have the database but i didn't make any changes to the default settings.
My operating system is Windows 10 Entreprise LTSC. - Build 1809.

**Comment by droidmonkey** [comment] 2024-05-28 10:10
Recommend reinstalling the visual studio runtime: https://aka.ms/vs/17/release/vc_redist.x64.exe

**Comment by Rebs77** [comment] 2024-05-28 10:40
> _Recommend reinstalling the visual studio runtime: https://aka.ms/vs/17/release/vc_redist.x64.exe_

I did that, it didn't work. 
I also uninstalled KeepassXc, cleared the files in AppData, installed it again and the problem remained..

**Comment by Rebs77** [comment] 2024-05-31 10:13
Sorry, Any olther opinions or eventual solutions?

**Comment by droidmonkey** [comment] 2024-05-31 11:46
Impossible to tell without reproduction

**Comment by Rebs77** [comment] 2024-05-31 11:53
Ok, thank's anyway... i'll try to upgrade to win11, ou make some updates to the win10 version and then see if the problem remains or get fixed...

**Comment by droidmonkey** [comment] 2024-06-16 12:33
I can't replicate this issue. If you can give me precise steps to repeat the recursion that caused it I will reopen.

**Closed as completed by droidmonkey** 2024-06-16 12:33 UTC
Labels: not reproducible, crash :boom:
