### ISSUE TITLE
Feature: xkcd password generation

### ISSUE THREAD

**Issue by alanfranz** [keepassxreboot/keepassxc#263] opened 2017-02-07 10:50 UTC
Hello,
this is a feature I'd really like: xkcd-style password generation.

https://xkcd.com/936/

There're many implementations of xkcd-style password generators, and I'm currently using them, then pasting the pw in keepassx.

If the feature is interesting and would probably be merged, I could contribute a PR myself.

**Comment by TheZ3ro** [comment] 2017-02-07 11:10
Duplicate of #21

**Closed** 2017-02-07 12:01 UTC
Labels: duplicate
