### ISSUE TITLE
Try other (still locked) database on auto-type not found

### ISSUE THREAD

**Issue by wilriker** [keepassxreboot/keepassxc#4777] opened 2020-05-25 10:59 UTC
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
It would be helpful to either
a) be able to select the database to be unlocked by first auto-type invocation or
b) if no entry was found in the just unlocked databases and other locked databases remain to let the user unlock them as well.

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
I usually have two databases in my KeepassXC instance. After start-up both are locked and when I first use auto-type it will ask me to unlock one of them (I have not yet found a pattern which one that is). Most of the times of course this is the wrong one and it will not find the required entry (I unlock it anyway since I usually need both databases sooner or later).

**Comment by droidmonkey** [comment] 2020-05-25 11:30
Duplicate of #2322

**Closed by droidmonkey** 2020-05-25 11:30 UTC
Labels: new feature
