### ISSUE TITLE
Please separate "state" from "configuration" in config files

### ISSUE THREAD

**Issue by tunbridgep** [keepassxreboot/keepassxc#4286] opened 2020-02-04 02:40 UTC
So, currently keepassxc saves it's settings in keepassxc.ini. This is fine. But it also stores things like the last-opened file history in the same file.

This is potentially "bad practice" (despite being standard on Windows) because it makes any sort of configuration management tedious and annoying. If I want keepassxc to work the same way on multiple PCs, and want to sync the config file (say, through github), I run into a problem where the config file is polluted with unnecessary changes. Even if I were to ignore these, it still runs into the problem of having one PC where, for example, the recent database list points to invalid files.

This is also a potential slight privacy risk (although it's very minor) as it has the potential to reveal the location of someone's database files if they share their configuration.

Would it be possible to split the config into two files, one for permanent, database-agnostic settings (such as program behaviour - minimize on copy etc) and one for "history" (recently opened documents etc).

Many programs on Linux already do this (~/.bash_history, for example).

**Comment by droidmonkey** [comment] 2020-02-04 03:05
Duplicate of #2193

**Closed by droidmonkey** 2020-02-04 03:05 UTC
Labels: new feature
