### ISSUE TITLE
KeePassXC inhibits Plasma logout

### ISSUE THREAD

**Issue by stikonas** [keepassxreboot/keepassxc#1190] opened 2017-11-17 14:08 UTC
## Expected Behavior
System logs out.

## Current Behavior
If I try to shutdown my Plasma desktop without entring KeePassXC passphrase, log out is inhibited.
I can see notification:
keepassxc prevented log out.

This does not happen if KeePassXC is unlocked.

## Steps to Reproduce (for bugs)
1. Try KeePassXC on Plasma.
2. Log our from your desktop. First attempt fails.

## Debug Info

KeePassXC - 2.2.1

Operating system: GNU/Linux
CPU architecture: x86_64
Kernel: 4.12.12-gentoo

**Comment by phoerious** [comment] 2017-11-17 14:10
Duplicate of #856

**Closed by phoerious** 2017-11-17 14:10 UTC
