### ISSUE TITLE
Pull window to current workspace when it's raised for unlocking

### ISSUE THREAD

**Issue by ronso0** [keepassxreboot/keepassxc#10037] opened 2023-11-19 14:44 UTC
## Summary
Pull window to current workspace when it's raised for unlocking (xfce4 desktop).

## Examples
I use browser windows on multiple workspaces. KeepassXC is usually launched on workspace1.
If I click the KeepassXc icon in an edit field in a browser in another workspace, xfce switches to workspace1 and raises KeepassXC.
If feasible, it would be very convenient if KeepassXC was pulled to that my current workspace.
If not, I'd be happy if someone could propose a workaround for xfce4, or at least some dirty hack using `wmctrl` or alike.

**Comment by droidmonkey** [comment] 2023-11-19 15:48
Duplicate of #1858

**Closed as not planned by droidmonkey** 2023-11-19 15:48 UTC
Labels: duplicate
