### ISSUE TITLE
Setting MinimizeOnStartup=true won't allow the main window to ever show on MacOS

### ISSUE THREAD

**Issue by ChristopherSchultz** [keepassxreboot/keepassxc#2280] opened 2018-09-10 22:07 UTC
Title is summary. Details below.

## Expected Behavior
When launching KeePassXC, its main window is visible.

## Current Behavior
When launching KeePassXC, its main window is not visible.

## Steps to Reproduce (for bugs)
1. Launch KeePassXC under MacOS High Sierra (not sure if the specific version is important)
2. Close the main window by clicking the red "X" button in the window's titlebar in the upper-left hand corner of the window
3. Main window disappears

Actually... no windows are showing. Launching KeePassXC from the dock or the command-line causes the main window to show briefly, then disappear. Clicking the dock icon does nothing. Right-clicking the dock-icon gives no options for any windows. Clicking "Show All Windows" gives the message "No available windows". Clicking on the application menu and selecting "About KeePassXC" does nothing. SHIFT-Click on the dock to launch in "safe mode" (which must be supported by the application) doesn't do anything.

Interestingly... using the global hotkey for auto-type _works_! So the database is indeed open and I can interact with it... I just can't see it, find entries, add/edit/remove entries, etc.

## Debug Info
KeePassXC - 2.3.4

**Comment by ChristopherSchultz** [comment] 2018-09-10 22:11
Looks like this is a mis-implementation of the "minimize on startup" feature.

Changing:

`MinimizeOnStartup=true` to `MinimizeOnStartup=false` in my `.../Application Support/keepassxc/keepassxc.ini` file restored the window.

**Comment by ChristopherSchultz** [comment] 2018-09-10 22:14
This may be related to issue #1727

**Comment by droidmonkey** [comment] 2018-09-11 02:12
@weslly can you confirm?

**Comment by weslly** [comment] 2018-09-11 03:10
I can reproduce #1727, but not this issue.

>Close the main window by clicking the red "X" button in the window's titlebar in the upper-left hand corner of the window

Currently this button quits the application instead of closing the window, unlike the regular OSX behavior, but this would be another bug.

**Comment by ChristopherSchultz** [comment] 2018-09-11 16:11
I did end up upgrading from 2.3.3 to 2.3.4 in an effort to see if any issue I was seeing had been resolved in the later version. I can confirm that X button closes the app which is only slightly unexpected given Mac application semantics.

It was setting the "minimize on startup" that caused a problem for me. I will try to get better steps-to-reproduce now that I know what the "fix" was (and thus reverse-engineered the root problem... it had nothing to do with closing the main window).

**Comment by ChristopherSchultz** [comment] 2018-09-11 16:16
Yes, this reproduces the issue for me in 2.3.4:

1. Launch KeePassXC (or leave it open if it's already open)
2. Go to app preferences (KeePassX -> Preferences, or CMD-,)
3. Under "General -> Basic Settings", check the "Minimize window at application startup" setting
4. Quit KeePassXC
5. Launch KeePassXC

Result: application window shows, then disappears. I haven't found a way to bring it back.

Expected: application window starts minimized (it's okay to show, then minimize), but can be brought back up by clicking on the dock icon

The only way I was able to get the application window to come back was to hand-edit the keepassxc.ini file and change `MinimizeOnStartup=true` to `MinimizeOnStartup=false` and re-launch the application.

**Comment by ChristopherSchultz** [comment] 2018-09-11 23:50
Not that I know of. This is a 3-week-old laptop so I haven't had a lot of time to break it, yet :)

**Comment by droidmonkey** [comment] 2018-09-15 15:58
![](https://github.trello.services/images/mini-trello-icon.png) [#2280 - MacOS minimizeonstartup](https://trello.com/c/lID8Y1Wt/4-2280-macos-minimizeonstartup)

**Comment by ChristopherSchultz** [comment] 2018-10-09 16:50
@martijnjanssen The auto-type issue is documented elsewhere several times: #2326, #1982, #1216, #947

**Comment by pawel-tomkiel** [comment] 2019-03-27 14:18
I can confirm that this bug still persists in 2.4.0. Fortunately @ChristopherSchultz [workaround](https://github.com/keepassxreboot/keepassxc/issues/2280#issuecomment-420078563) still works 😉

**Comment by droidmonkey** [comment] 2019-03-28 01:33
I disagree, I cannot replicate this issue at all. As a matter of fact, for me minimize on startup doesn't work at all on MacOS.

**Comment by pawel-tomkiel** [comment] 2019-03-28 07:28
I stumbled upon this right after update to 2.4.0 (MacOS Mojave 10.14.4, installed via `brew cask`). Same behaviour as described. I had in config:
```
MinimizeOnStartup=true
```

and changing to `false` resolved the issue.

**Comment by ChristopherSchultz** [comment] 2019-05-23 14:14
Begging your pardon, but I can reproduce this every time using KeePassXC 2.4.1 and I'd like to reopen this bug report.

Steps to reproduce:
0. MacOS 10.14.4, KeePassXC 2.4.1 installed from vanilla DMG bundle
1. Edit keepassxc.ini, set `MinimizeOnStartup=true`
2. Launch KeePassXC (I used 5-finger-pinch, type "kee", press RETURN)

Result: KeePass main window is not possible to view. Clicking the icon in the dock causes KeePassCX application to gain focus; menubar is visible when the application is active, but the main window is always hidden.

I have a single display (MacBook Pro internal) and no funny window management in play. Four-finger-upward-swipe to show all windows does not show KeePassXC's main window anywhere. My dock happens to be on the right side of the screen and not the bottom. Everything else is pretty standard MacOS.

Version/debug info:
KeePassXC - Version 2.4.1
Revision: 7bafe65

Qt 5.12.2
Debugging mode is disabled.

Operating system: macOS Mojave (10.14)
CPU architecture: x86_64
Kernel: darwin 18.5.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.4

**Comment by droidmonkey** [comment] 2019-05-23 16:00
I'll take a look

**Comment by hmueller01** [comment] 2020-01-30 09:26
I had this issue with v2.5.3 too. I reported in a duplicate issue #4266 (sorry!). In my case it happened because I set the dock behavior of KeePassXC to show on all desktops (right click on the dock icon, options, show on all desktops). If I switch back to "without", window to unlock database shows up but does not minimize after unlock (this happens only if I set `MinimizeAfterUnlock=true` which I do not like).

With "show on all desktops" I can use autotype (unlock screen appears, selection what to paste), but I am unable to open the main window (as reported here).

**Comment by droidmonkey** [comment] 2020-02-02 13:15
Thank you for the tip, that might be the differentiating factor.

**Comment by ChristopherSchultz** [comment] 2020-02-03 17:42
Yes, that might be it. I definitely have mine set to "appear on all desktops" as well, and probabyl have had that since initial installation.

**Comment by droidmonkey** [comment] 2020-02-03 17:53
How is that set? I tried doing this on my Mac mini and couldn't figure it out. Screenshot or guide would be appreciated.

**Comment by hmueller01** [comment] 2020-02-03 18:54
Right click or long click on the dock icon. Then choose options, show on all desktops.

**Comment by droidmonkey** [comment] 2020-06-06 22:12
Fixed in 2.6

**Closed** 2020-06-06 22:12 UTC
Labels: bug, platform: macOS
