### ISSUE TITLE
data loss when adding subgroups from 2 PC to the shared file

### ISSUE THREAD

**Issue by sena73** [keepassxreboot/keepassxc#7896] opened 2022-04-14 12:09 UTC
Steps to reproduce:

1. Put password file on samba shared folder.

2. 2 users open the file, choose a group and start adding 10 subgroups to
that group simultaneously, also adding 1 password entry in each subgroup

From time to time users are asked to merge the file - that is expected.

But at the end I get 3 added subgroups lost!

Reproduced with keepassxc 2.6.2 (Debian 11 package) and 2.7.1 appimage.

I also performed same test with keepass2 (Debian 11 package) - works without problem.

**Comment by droidmonkey** [comment] 2022-04-14 13:39
Do you have auto saves enabled?

**Comment by sena73** [comment] 2022-04-14 14:18
> Do you have auto saves enabled?

If that is automatic saving after adding group/entry, then yes. Saving was happening automatically, I do not need to click on "save" button.

**Comment by GigabyteProductions** [comment] 2023-12-29 22:07
We are experimenting with a shared password database on Google Drive. Our KeePassXC 2.7.6 instances are automatically re-loading the database as expected, but entries in groups/subgroups get moved into the root group, and all groups are lost. Is the behavior that I am describing caused by the same bug?

**Comment by droidmonkey** [comment] 2023-12-29 23:12
Are you using KeeShare? If so, that is this "bug" (it's actually designed behavior but appears as a bug): #3045

Could also be related to #4671

As for this issue, I'm closing it as there has been no input from the OP in 2 years.

**Closed as not planned by droidmonkey** 2023-12-29 23:12 UTC

**Comment by GigabyteProductions** [comment] 2023-12-29 23:19
Nope, just two of us opening a whole database file from the Google Drive, but at the same time

**Comment by droidmonkey** [comment] 2023-12-30 00:40
What you describe is generally... not possible. Make sure you are opening the same database file and Google drive is actually syncing your file.

**Comment by sena73** [comment] 2024-01-02 13:00
> Are you using KeeShare? If so, that is this "bug" (it's actually designed behavior but appears as a bug): #3045
> 
> Could also be related to #4671
> 
> As for this issue, I'm closing it as there has been no input from the OP in 2 years.

I will check with the latest keypassxc. But I will expect the issue to be closed after some actual fixing happens, not just because OP does not report it again and again...

**Comment by sena73** [comment] 2024-08-13 10:03
I checked with 2.7.9 - the bug is still present. Please fix it or at least warn users about the possible data loss!

And no, I am not using KeeShare. I am using "merging" feature.
