### ISSUE TITLE
Update from KeePassXC 2.4.3 to 2.5.0: Issues with browser integration

### ISSUE THREAD

**Issue by danielkr123** [keepassxreboot/keepassxc#3740] opened 2019-10-31 08:04 UTC
Hello,

yesterday I updated KeePassXC from 2.4.3 to 2.5.0 on a Windows and MacOS notebook. After the update the browser plugin (Firefox on the MacOS machine; Chrome on the Windows machine) does not seem to be able to match the URL to the correct password/username any more. Instead it shows a (long) list of all passwords ever used in that browser when clicking on one of the credentials text boxes on the website (see attached picture from GitHub login).

Best regards,
Daniel

![GitHub Login with KeePassXC browser plugin](https://user-images.githubusercontent.com/22988970/67929324-58e05b80-fbbd-11e9-94e6-90e0dc81972e.png)

**Comment by varjolintu** [comment] 2019-10-31 09:23
This sounds very strange. Do you happen to have an entry with an invalid URL? Extra characters etc? Are you able to debug the extension itself?

**Comment by danielkr123** [comment] 2019-10-31 09:58
No - it's the same with all websites

**Comment by droidmonkey** [comment] 2019-10-31 10:29
This is a duplicate of the three other issues that all were a result of having asterisks or semicolons in the url field for the entry.

**Comment by danielkr123** [comment] 2019-10-31 13:28
Thanks! I can confirm that entries with RegEx URL patterns were the issue. Once I removed them it workes well. RegEx expressions which I removed were the following:

1. https://.*google.com --> changed to https://google.com since it will now automatically match all subdomains
2. https://www.google.com|https://www.google.de --> No idea yet how I can add different URLs

**Comment by droidmonkey** [comment] 2019-10-31 13:42
Go to the browser integration tab when editing an entry to add multiple URLs. This is a KeePassXC 2.5.0 feature

**Closed by droidmonkey** 2019-10-31 13:42 UTC
Labels: plugin: Browser integration
