### ISSUE TITLE
Cannot move entries or groups on macOS

### ISSUE THREAD

**Issue by klartext79** [keepassxreboot/keepassxc#5728] opened 2020-11-21 06:57 UTC
## Overview
Yesterday when i installed KeepassXC for the VERY FIRST time, on a clean macOS Big Sur installation everything worked fine. Dragging and dropping was possible without an issue.
Today after i enabled Chrome extension and saved the very first password by that extenion, dragging and dropping is not possible anymore. Neither groups nor entries.

Whenever i start a dragging process, the console logs the following lines (and only these)
```
Invalidating assertion 218-108-618 (target:[app<application.org.keepassxc.keepassxc.1640368.1640375(501)>:1239]) from originator [daemon<com.apple.coreservices.launchservicesd>:108]
Invalidating assertion 218-134-619 (target:[app<application.org.keepassxc.keepassxc.1640368.1640375(501)>:1239]) from originator [daemon<com.apple.WindowServer(88)>:134]
Calculated state for app<application.org.keepassxc.keepassxc.1640368.1640375(501)>: running-active (role: UserInteractiveNonFocal)
[app<application.org.keepassxc.keepassxc.1640368.1640375(501)>:1239] Ignoring jetsam update because this process is not memory-managed
[app<application.org.keepassxc.keepassxc.1640368.1640375(501)>:1239] Ignoring suspend because this process is not lifecycle managed
[app<application.org.keepassxc.keepassxc.1640368.1640375(501)>:1239] Set darwin role to: UserInteractiveNonFocal
[app<application.org.keepassxc.keepassxc.1640368.1640375(501)>:1239] Ignoring GPU update because this process is not GPU managed
[app<application.org.keepassxc.keepassxc.1640368.1640375(501)>:1239] Skipping AppNap state - not lifecycle managed
```

## Context
Restarting application - no effect, same behaviour.
Restarting machine - no effect, same behaviour.
Deleting the .ini file and restarting the application - **Works again**

This is the ini content before deleting it
```
[General]
UseTouchID=(removed)

[Browser]
CustomProxyLocation=
Enabled=true

[GUI]
TrayIconAppearance=monochrome-dark

[KeeShare]
Active="<?xml version=\"1.0\"?>\n<KeeShare xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\">\n  <Active/>\n</KeeShare>\n"
Foreign="<?xml version=\"1.0\"?>\n<KeeShare xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\">\n  <Foreign/>\n</KeeShare>\n"
Own="<?xml version=\"1.0\"?>\n<KeeShare xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\">\n  <PrivateKey/>\n  <PublicKey/>\n</KeeShare>\n"
QuietSuccess=true
```

This is the ini content after restart and deletion (where it works again) - without any changes by the user

```
[General]
ConfigVersion=1
UpdateCheckMessageShown=true
UseTouchID=(removed)

[PasswordGenerator]
AdditionalChars=
ExcludedChars=
Logograms=true
```

[NOTE]:
KeePassXC - Version 2.6.2
Revision: e9b9582

Qt 5.15.1
Debugging mode is disabled.

Operating system: macOS 10.16
CPU architecture: x86_64
Kernel: darwin 20.1.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.6

**Comment by phoerious** [comment] 2020-11-21 08:43
Duplicate of pinned issue.

**Closed by phoerious** 2020-11-21 08:43 UTC
Labels: bug

**Comment by klartext79** [comment] 2020-11-23 07:44
Would be good to let others in your pinned topic know that deletion of .ini file could fix it without re-installing.

**Comment by droidmonkey** [comment] 2020-11-23 11:17
It doesn't. This is a qt bug, it is coincidental that anything works at this point.
