### ISSUE TITLE
CSV export missing Custom Attributes

### ISSUE THREAD

**Issue by grizzler0031** [keepassxreboot/keepassxc#2094] opened 2018-07-05 15:24 UTC
## Expected Behavior

When exporting a database with entries that have custom attributes, I would expect these to show up in the csv file.

## Current Behavior

The custom attributes appear to be missing.

## Steps to Reproduce (for bugs)

1. add one or more custom attributes to an entry
2. export the database to a csv file

## Context

not relevant

## Debug Info

[filled in rather than pasted because of localization...]
KeePassXC 2.3.1
Revision 2fcaeea 

Libraries:
- Qt 5.10.1
- libgcrypt 1.8.3

Operating system: Debian Testing (Buster)
CPU architecture: x86_64
Kernel: linux 4.16.0-2-amd64

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by TheZ3ro** [comment] 2018-07-05 15:48
Duplicate of #854

**Closed by TheZ3ro** 2018-07-05 15:48 UTC

**Comment by grizzler0031** [comment] 2018-07-05 16:41
It's a good thing searching for 'custom attributes' or 'extra attributes' showed #854...
Oh wait. It didn't. Because it's called 'additional attributes' there. Oh well, I guess that's what you get when translations suck...
I mean, after seeing 'switch on' translated as 'schakelen aan' I should have been prepared for that.

Sorry about this little rant. I hate checking things first and then finding I've wasted time anyway.

**Comment by TheZ3ro** [comment] 2018-07-05 18:31
No problem, I can feel the struggle since English isn't my native language either :)

About the issue, Custom Attributes are dynamic fields in the database and CSV doesn't support such fields. An alternative can be adding a column to the CSV called "extra" with a json representation of Custom/Extra Attributes, but it's way better to export the database as XML (that natively supports dynamic fields)

**Comment by grizzler0031** [comment] 2018-07-05 19:41
Yes, one single field with something like json was what I was expecting. But keepassxc-cli's XML extract is actually what I need. I seem to have overlooked that functionality when I checked the available documentation...
