### ISSUE TITLE
New or updated password incomplete when it contains an ampersand

### ISSUE THREAD

**Issue by jurgenhaas** [keepassxreboot/keepassxc#4709] opened 2020-05-07 09:25 UTC
## Overview

When using a browser extension (in my case latest Firefox on Ubuntu) and either creating a new password or updating an existing one for a website, the extension prompts me if I wanted to add a new or update an existing record in my KeePass database. I confirm that and feel happy.

Problem being, if the password contained an ampersand (&), that would then truncate the password at that position and only store the characters preceding that character's position. I assume that's because the request is some sort of http request and that could easily get that wrong.

## Expected Behavior

The stored password should be complete and it should probably be base64 encoded during the request from the browser extension over to the KeePass application.

## Context

KeePassXC - Version 2.5.4
Revision: dcca5aa

Operating System: Ubuntu 18.04 LTS
Desktop Env: Gnome

**Comment by droidmonkey** [comment] 2020-05-07 10:47
All communication between the extension and keepassxc is encrypted

**Comment by varjolintu** [comment] 2020-05-07 10:58
Could not reproduce the issue.

**Comment by jurgenhaas** [comment] 2020-05-28 15:05
Oh wow, this is crazy. I was listening to Security now with Steve Gibson and Leo Lapport from Twit this morning and Steve reported about a new feature of FF 78 which will show a warning when a password field with the maxlength attribute will cut a pasted password from a password manager which would otherwise remain unnoticed.

When listening I though, hmm, wonder if that's related to the issue I had reported here a few weeks ago. And indeed, went back to that form on https://developer.climacell.co/sign-up and indeed, they use maxlength=20 for the password field. Then I went to KeePass and checked the password history for that record and guess what, the & sign was character number 21. So, it's been the webform cutting the generated password, not the password manager as I originally thought.

So funny - and stupid by the web developer that they really do that. Though I should report back here so you can remove the bug tag and maybe spread the word about it if helpful.

**Comment by droidmonkey** [comment] 2020-05-28 15:36
Wow good find! I am closing this issue then.

@varjolintu perhaps we can issue a similar notification to the user if a maxlength is added to a password field (for non-Firefox users). I have been bitten by this myself in the past with a bank (of all places).

**Closed by droidmonkey** 2020-05-28 15:36 UTC
Labels: bug, plugin: Browser integration

**Comment by varjolintu** [comment] 2020-05-28 17:16
@droidmonkey I'll give it a try.
