### ISSUE TITLE
A way to edit list of attributes in the upper part

### ISSUE THREAD

**Issue by swamp-fish** [keepassxreboot/keepassxc#397] opened 2017-03-15 11:02 UTC
Add/remove visibility(including cutom ones) and rearrange attributes in the header that currently only has Title, Username and Url

## Possible Solution

![screenshot_20170315_124903](https://cloud.githubusercontent.com/assets/9247853/23945129/0377c180-097e-11e7-9330-0f69e83778a6.png)
For example, 
1) Right Click on the Title
2) Edit
3) A new window will open that will have all shown attributes listed in Vertical way and nearby the list of ALL attributes including custom ones that you can place in there.
4) To place attributes there could simple arrows LEFT and RIGHT to place entries from one list to another, and UP and DOWN to rearrange them

## Context

More visibility to things actually used. Frankly i don't think there should be a difference between custom and non custom properties, you can have those standart options simply available as default. This could result in additions to the code that won't rely on just built-ins. For example this https://github.com/keepassxreboot/keepassxc/pull/146 useful addition only takes into account built-in properties and thus not expandable(or atleast it looks like it from GUI screenshots in there)

**Comment by phoerious** [comment] 2017-03-15 12:02
I would prefer a right click menu with a list of check options to toggle visibility and drag and drop for reordering columns.
I wouldn't list custom attributes, since they are not available in every entry and there can also be infinitely many, possibly making the list very long.  But a single column "Advanced attributes" would be possible.

**Comment by swamp-fish** [comment] 2017-03-22 08:57
The way you described it could really result in long unusable list. The way i described it you'll have everything managable. It would be nice even to have a filter for each section. Maybe i described everything bad. My proposal is to get similar to Smplayer way of changing elements in toolbars but with filter on top of each list.

**Comment by phoerious** [comment] 2017-03-22 11:05
I know what you mean, but we only have a very limited number of options. I would like to do it the way most file explorers do it for their columns.

**Comment by droidmonkey** [comment] 2017-05-07 03:49
Duplicate of #17

**Closed by droidmonkey** 2017-05-07 03:49 UTC
Labels: new feature, user interface
