### ISSUE TITLE
Firefox: no logins found

### ISSUE THREAD

**Issue by jwshepherd** [keepassxreboot/keepassxc#5077] opened 2020-07-14 13:48 UTC
After upgrading to version 2.6.0 i have started having more and more issues with previously working websites getting the no logins found.

Firefox version: 78.0.2(32-bit)
only other extension installed was nighteye

go to a regular website ( gmail)
click keepass icon on username field
error: no login found displays
copy url to google, works fine

I can see the websites in the password list window, but am Unsure why it cannot see the domains or url even if it matches 100%

deleted and created new keys in firefox to no avail.

KeePassXC - Version 2.6.0
Revision: 0765954

Qt 5.15.0
Debugging mode is disabled.

Operating system: Windows 10 Version 1909
CPU architecture: x86_64
Kernel: winnt 10.0.18363

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5

Operating System: Windows 10 1909

**Comment by varjolintu** [comment] 2020-07-14 14:58
What kind of URL's are you using in your entries? Can you give an example with a certain site?

**Comment by jwshepherd** [comment] 2020-07-15 02:30
https://verified.capitalone.com/sic-ui/
https://www.atmosenergy.com/
https://www.autotask.net/

fairly normal sites.

**Comment by varjolintu** [comment] 2020-07-15 04:55
@jwshepherd I had no problems with Autotask or Capital One sites. The reason Atmos Energy site is not properly identified is that the password field has an `autocomplete` attribute with value `new-password` which is ignored because, well, it is identified as a new password field. You can still fill the credentials manually using the context menu though.

**Comment by V4n1X** [comment] 2020-07-15 06:44
Can confirm this on MS Edge too. No logins found on sites, that are found before. Mostly internal sites (VMWare vCenter, IcingaWeb2, etc...)

Extension and KeePassXC both on 2.6.0

**Comment by varjolintu** [comment] 2020-07-15 07:16
@V4n1X Edge version is not the latest yet. Microsoft validation takes 2-5 days. Those errors should be fixed. You can confirm this by using another browser with 1.6.6.

Everyone who has these issues, please confirm if KeePassXC 2.5.4 still works so we can rule out if the problem is in the extension or KeePassXC itself.

**Closed** 2020-08-03 01:21 UTC
Labels: bug, plugin: Browser integration

**Comment by tomberggit** [comment] 2023-07-30 18:36
Hi, I am working with KeePassXC 2.7.5, Windows 10, Firefox 115.0.3, 64 bit.
Regardless of the website, Keepass returns the message "No logins found" (in German: "Keine Anwendungen gefunden").
In parallel I tried it with Linux Mint: Same error. Switching to English language: Also error.

**Comment by robsonsobral** [comment] 2023-10-06 12:47
This bug is back!

Running KeePassXC 2.7.6 and KeePassXC-Browser 1.8.8.1

**Comment by HyperHypa** [comment] 2023-11-15 18:40
Currently on KeePassXC-Browser 1.8.9 and the error is showing again even with the setting turned off. It only happens on Google for some reason.

**Comment by varjolintu** [comment] 2023-11-15 18:41
@HyperHypa What setting?

**Comment by HyperHypa** [comment] 2023-11-15 18:43
Oh my bad, after changing the URL https://google.com to https://accounts.google.com, it's working again.

**Comment by JohnLGalt** [comment] 2023-11-15 19:26
Leave the URL in the main section as `https://google.com`

Then, go to the `Browser Integration` tab and add `https://accounts.google.com` as an additional URL.

My google accounts have it set this way and it works.
