### ISSUE TITLE
Password Quality Column

### ISSUE THREAD

**Issue by Johnex** [keepassxreboot/keepassxc#2556] opened 2018-12-18 23:29 UTC
Hi!
I would love to see a list option to show the quality of the password in bits, like the QualityColumn plugin does for Keepass 2.

**Comment by kneitinger** [comment] 2018-12-19 00:09
Hi!  Thanks for the feature request, this appears to be a duplicate of #551 and [this comment which has an interesting suggestion to represent it more minimally with red, yellow, or green dots](https://github.com/keepassxreboot/keepassxc/issues/1091#issuecomment-338442407).

**Comment by Johnex** [comment] 2018-12-19 01:03
I see yeah. I will keep this one open though since #551 was created in 2017 but still not completed 😃

**Comment by droidmonkey** [comment] 2018-12-19 02:08
Keeping two issues open doesn't help. #551 is in our backlog, it'll get done.

**Closed by droidmonkey** 2018-12-19 02:08 UTC
