### ISSUE TITLE
Dependency conflict on Ubuntu 16.04

### ISSUE THREAD

**Issue by sindrom91** [keepassxreboot/keepassxc#1567] opened 2018-02-28 21:53 UTC
Unable to update to the new version because apt is failing to install libsodium23.

## Current Behavior
Installation fails with the following error message:
`trying to overwrite '/usr/lib/x86_64-linux-gnu/libsodium.so.23.1.0', which is also in package libsodium18:amd64 1.0.16-0ppa1~xenial1`

## Steps to Reproduce (for bugs)
1. Make sure to have libsodium18 installed on Ubuntu 16.04
2. Try to install or update KeePassXC

## Debug Info
KeePassXC - 2.3.0-0ppa1~xenial1

Operating system: Ubuntu 16.04
CPU architecture: x86_64
Kernel: 4.4.0-116-generic

**Comment by TheZ3ro** [comment] 2018-02-28 22:12
Duplicate of #1545

**Closed by TheZ3ro** 2018-02-28 22:12 UTC
