### ISSUE TITLE
Database locks when screen saver is activated although the session is not locked

### ISSUE THREAD

**Issue by alexander-koerschgen** [keepassxreboot/keepassxc#8563] opened 2022-10-10 11:37 UTC
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

With the setting "Lock databases when session is locked or lid is closed" activated, my database is already locked when the screen saver is activated although this does not cause the session to be locked on my system.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Enable setting "Lock databases when session is locked or lid is closed".
2. Ensure that activating the screen saver does not cause the session to lock.
3. Wait for the screen saver to activate.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Nothing because the session is not locked.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
The database is locked.

## Context
[NOTE]: # ( Give us any additional information you may have. )
I have configured my system in such a way that the session is not locked when the screen saver is activated. The session is only locked when I manually lock it or when the system enters suspend/hibernate. I would like KeePassXC to automatically lock the database in exactly these situations. I would not like to have KeepassXC lock the database when only the screen saver is activated. The setting "Lock databases when session is locked or lid is closed" should work in this fashion according to its wording.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.2
Revision: e9b9582

Qt 5.15.2
Debugging mode is disabled.

Operating system: Debian GNU/Linux 11 (bullseye)
CPU architecture: x86_64
Kernel: linux 5.10.0-18-amd64

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.8

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Cinnamon
Windowing System: X11? I found this: `$ echo $XDG_SESSION_TYPE` -> `x11`

**Comment by gmejzej** [comment] 2023-05-23 19:20
Hopefully fixing this bug is prioritized. This is super inconvenient to have to constantly be typing strong password just cause the screen blanked to save energy.

**Comment by sergeolkhovik** [comment] 2023-07-07 10:50
Agree! My env - laptop with Ubuntu 23.04, but I modified ~/.local/share/applications/keepassxc.deskto file and added '-platform xcb' extra option in order to have autotype working.

**Comment by realpixelcode** [comment] 2024-09-07 10:55
Not sure whether this is the same issue, but probably at least very similar: I find it very inconvenient that the DB is locked as soon as the screen begins fading out. Like, the option to turn off the screen after, say, 5 minutes does not turn the monitor instantly black after 5 minutes but instead slowly darkens it within a couple of seconds.

***Expected behaviour***:

1. The screen time-out of 5 minutes is reached.
2. The screen slowly begins to fade out.
3. After a couple seconds, the screen is completely black.
4. KeePassXC locks the database.

***Actual behaviour***:

1. The screen time-out of 5 minutes is reached.
2. KeePassXC locks the database.
3. The screen slowly begins to fade out.
4. After a couple seconds, the screen is completely black.

This behaviour is annoying because the screen fade-out can be interrupted by wiggling the mouse, but for the KeePassXC database it's already too late. It's basically locked immediately after 5 minutes without prior notice.

**Comment by droidmonkey** [comment] 2024-09-07 11:01
Take that up with the implementors of the screen fade. They send out the notice that everything was turned off when the fade starts.

**Comment by droidmonkey** [comment] 2024-09-07 11:10
This is actually a duplicate of https://github.com/keepassxreboot/keepassxc/issues/4708

**Closed as not planned by droidmonkey** 2024-09-07 11:10 UTC
Labels: duplicate
