### ISSUE TITLE
Import new single entries into current database from text or csv files (not a bulk import into a new DB)

### ISSUE THREAD

**Issue by MountainX** [keepassxreboot/keepassxc#4116] opened 2020-01-07 04:49 UTC
## Summary
Say I have credentials for one site temporarily saved as text (CSV or plain text). I would like to move that credential info into my currently open KeePassXC database. Of course, I could re-type the info or copy-paste it. But it would be very convenient to import it with one click.

This is not the same as bulk importing many records into a new database. This is for one or a few records that should be added to the existing database.

## Desired Behavior
There is a standard file format for plain text. Assume I have a file with credentials in that format. I go to the KeePass menu Database > Import > One Entry (to current DB) and it opens a file chooser dialog. When I select the file, it is imported to the currently active / open DB.

## Possible Solution

The text file to import could contain fields like this:

[Group:]	Shopping
[Title:]	World's Best 3D Printer Website
[Shared by:]	fred
[URL:]		https://3d-printers.com
[Accnt email:]	bob99@gmail.com
[Username:]	bob9999
[Password:]	chair-spot-belong-heavy-FIGHT-TRIANGLE-HOLE-tools
[Expires:]
[Notes:]
This is a great site.
The prices are excellent
[Created:]	2020_01_06_22_28_05

Any fields not used by KeePassXC could be put into notes. 
If the file format is not recognized, just dump all the info into notes.
If Group is present in the imported file, the new entry is put in that group. Otherwise, it is put into a group named "Imported Items"

Upon successful important, a confirmation message can be displayed (and would include the Group where the item was saved). A warning could be added stating, "If these credentials were not passed to your securely, please change the password or take other necessary precautions."

Future options might include the ability to drag and drop a suitable text file onto the KeePassXC window. Or to open a dialog that let's you paste text from the clipboard, and then the parsing and import proceed. However, for my needs, the simplest solution like a file open dialog would work well.

## Context

It would be ideal if people could always share passwords without going through the step of ever writing them down or putting them temporarily into an unencrypted file format. However, in real life, login credentials are often shared in a variety of ways in which they temporarily go through plain text. For any password that is shared with me, I move it into KeePassXC. I find myself doing this often enough that I would like to automate it as described above.

Here's another example. Say I create a new VPS (virtual private server). Many providers send the server info in an email. My habit is to immediately move all that into KeePassXC. Then I need to set up the server and secure it, which often means changing login info of the KeePassXC entry. But I feel it is much better to first make an entry in KeePassXC and then update it as required. So I want to get the info from the plain text (or email) into KeePassXC as easily as possible. A one-click import would be faster than copy-pasting each field one by one.

I would personally use this feature every day.

Of course, the single entry import could be made to recognize other file formats. Heck, I guess it could eventually be made smart enough to scan any email text and pick out the login credentials. But at this time I don't need that as much as I just need a simple version that does what I mentioned above.

(If the feature is implemented like I have described above, I would be happy to make a contribution to help support the work, assuming that's appropriate.)

**Comment by MountainX** [comment] 2020-01-07 04:55
I would be equally happy if this was only available in keepassxc-cli intially (if that makes implementation easier).

**Comment by droidmonkey** [comment] 2020-01-07 05:04
Duplicate of #1832

**Closed** 2020-01-07 05:04 UTC
Labels: new feature

**Comment by droidmonkey** [comment] 2020-01-07 05:07
We won't implement an arbitrary plain text file import. CSV is plenty robust enough. For single entries it is far easier to just create a new entry and copy/paste the relevant data.
