### ISSUE TITLE
No screen recoding permissions in macOS 10.14?

### ISSUE THREAD

**Issue by microcreators** [keepassxreboot/keepassxc#4581] opened 2020-04-11 14:10 UTC
2.5.4 is asking to have Accessibility Features enabled as well as Screen recording permissions, to enable auto-type. I can grant the former, but not the latter. There's no Screen Recording category in macOS 10.14.6

## Expected Behavior
I can add KeePassXC to Screen Recording priv section. Or KeePassXC can start auto-typing w.o this permission.

## Current Behavior
System Preferences will pop-up. 

## Possible Solution
Maybe this is something with my 10.14.6 installation / config, since I can't see a way to get that category added. Or this is specific to 10.15.x

## Steps to Reproduce
Try to auto-type ;)
Me trying to find that category... [on imgur](https://imgur.com/a/RpxJxHi)

Operating system: macOS 10.14.6

**Comment by phoerious** [comment] 2020-04-11 15:08
Please read the pinned issues.

Duplicate of #4573.

**Closed by phoerious** 2020-04-11 15:08 UTC
Labels: bug

**Comment by phoerious** [comment] 2020-04-11 15:11
Actually, the permission is new in Catalina, you are still on Mojave. Please try the steps outlined in the linked issue report anyway and see if you it resolves your problem.
