### ISSUE TITLE
add --yubikey <slot:serial> option to keepassxc desktop tool, just like --keyfile and with the keepass-cli open system

### ISSUE THREAD

**Issue by tuxcrafter** [keepassxreboot/keepassxc#11419] opened 2024-10-29 20:34 UTC
## Summary
When starting starting keepassxc with database and keyfile option when configured to use yubikey it will give an opening error and empty password error because it does not know to use a yubikey. When not providing any option to keepassxc it does remember the last database and does not give the error. My usecase is however to tell keepassxc what databases to use on startup with the unlock options as arguments.

## Examples
keepassxc keepass01.kdbx --keyfile keepass01.key --yubikey 1:18653578  keepass02.kdbx --keyfile keepass02.key --yubikey 2:18653578

I am willing to provide a 100 euro bounty

**Comment by droidmonkey** [comment] 2024-10-29 20:53
Duplicate of https://github.com/keepassxreboot/keepassxc/issues/6018

**Closed as completed by droidmonkey** 2024-10-29 20:53 UTC
Labels: duplicate
