### ISSUE TITLE
Using keepassxc-cli with keyfile only works when also having password

### ISSUE THREAD

**Issue by eigan** [keepassxreboot/keepassxc#1885] opened 2018-04-29 10:16 UTC
## Steps to Reproduce
1. Create a keyfile with following content: tester1234 _(have tested with this content, and my regular key created with `ssh-keygen`)_
2. Open keepassxc and create a new database with only "Key file" checked, and specify the keyfile created.
3. Save database
4. Run `keepassxc-cli ls -k <path-to-keyfile> <path-to-database>`
5. You are now prompted for password, just press enter.

## Expected Behavior
After "Steps to reproduce", the output should be: `[empty]`

## Current Behavior
```
 ~ keepassxc-cli ls -k <path-to-keyfile> <path-to-database>
Insert password to unlock <path-to-database>: 
Error while parsing the database: Wrong key or database file is corrupt.
```

## Debug Info

KeePassXC - 2.3.1
Revision: 2fcaeea

Libraries:
- Qt 5.10.1
- libgcrypt 1.8.2

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 4.16.5-1-ARCH

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by louib** [comment] 2018-04-29 23:39
Duplicate of https://github.com/keepassxreboot/keepassxc/issues/1873

**Closed by louib** 2018-04-29 23:39 UTC
