### ISSUE TITLE
When "show TOTP" is active Locking session doesn't Lock DB on MacOS

### ISSUE THREAD

**Issue by tjarkoGrossmann0815** [keepassxreboot/keepassxc#2407] opened 2018-10-22 06:54 UTC
## Expected Behavior
When locking session with active "Lock database when session is locked or lid is closed" and an open "Show TOTP" popup. The DB should be locked.

## Current Behavior
The DB remains open with the TOTP field visible.

## Steps to Reproduce (for bugs)
1. activate "Lock database when session is locked or lid is closed" on MacOs
2. click "Show TOTP" of entry with TOTP
3. lock and Reopen Session

## Debug Info
KeePassXC - Version 2.3.4
Revision: 6fe821c

Libraries:
- Qt 5.9.3
- libgcrypt 1.8.2

Operating system: macOS High Sierra (10.13)
CPU architecture: x86_64
Kernel: darwin 17.7.0

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by tjarkoGrossmann0815** [comment] 2018-10-22 06:59
The same behavior can be observed when opening the "about keepassxc" popup

**Comment by weslly** [comment] 2018-10-22 10:33
Duplicate of #721

**Closed by weslly** 2018-10-22 10:33 UTC
