### ISSUE TITLE
PW - Change Log to help conflict resolution during multi device sync

### ISSUE THREAD

**Issue by KevinFleischer** [keepassxreboot/keepassxc#3154] opened 2019-05-17 14:05 UTC
## Summary
When syncing the PW container over cloud services like dropbox (or private clouds) I could happen that a sync conflict appears. In those situations it would be helpful to find out what the last changes to the container on each device was. Currently I don't see a way to find the last changed/added passwords (over ALL groups). I have to go through them one by one.

## Desired Behavior
Finding out what entries had been changed / added last.

## Possible Solution
A new menu entry under "entries" called "last changes".
It will show a table of the last n changed entries in the form:
date | pw-group | entry title | changed attribute

The "changed attribute" is optional for better usability. The other columns would be sufficient to enable the desired usecase.

## Context
I use a synology NAS for syncing my container between my Kubuntu Laptop and my Android Phone. I had the situation that changes occured between the sync windows. I was not sure if/for how long the container had not been synchronized. So this feature request was born.

**Comment by droidmonkey** [comment] 2019-05-25 20:45
Duplicate of #1152

**Closed by droidmonkey** 2019-05-25 20:45 UTC
Labels: new feature
