### ISSUE TITLE
UI frozen after password generator is used via browser plugin

### ISSUE THREAD

**Issue by dreua** [keepassxreboot/keepassxc#7952] opened 2022-04-25 14:05 UTC
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
After using the password generator through browser plugin, the main window is frozen. Ctrl + q is the only function that I've found still working.

For me this is reproducible every time, I'm curious to hear whether it's reproducible for others as well (and under which circumstances)!

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Setup the Browser plugin in Firefox, have KeepassXC open and a DB unlocked.
2. In any text field (e.g. search field here on Github) press Alt+Shift+G.
3. Close the Password Generator with the X icon. (Not reproducible when using "Close" button.)
4. Go back to KeepassXC and try to search for an entry or do anything else.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
KeepassXC main window should continue to be usable after the password generator is closed.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
KeepassXC main window is frozen.

## Context
[NOTE]: # ( Give us any additional information you may have. )
I think the browser-accessible password generator changed with a recent update, which might have introduced this bug.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.1
Revision: 5916a8f

Qt 5.15.2
Debugging mode is disabled.

Operating system: Fedora Linux 35 (Workstation Edition)
CPU architecture: x86_64
Kernel: linux 5.16.20-200.fc35.x86_64

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.18.2

KeePassXC-Browser Version: 1.7.12
Mozilla Firefox 99.0.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux (Fedora 35)
Desktop Env: Gnome
Windowing System: X11

**Comment by droidmonkey** [comment] 2022-04-25 15:16
This is the key step:

Close the Password Generator with the X icon. (Not reproducible when using "Close" button.)

**Comment by varjolintu** [comment] 2022-04-25 18:37
Interesting. After calling the Password Generator again and closing it via <kbd>Esc</kbd> or Close button, KeePassXC is responsive again. The `closeEvent` is emitting `closed()` before accepting the event, so everything should be fine.

**Comment by Wapp92** [comment] 2022-05-01 11:37
I have the exact same issue, i have disable password generator in the keepass browser plugin setting for now. Firefox user.

**Comment by droidmonkey** [comment] 2022-05-01 12:35
Wonder if it's similar to this https://github.com/keepassxreboot/keepassxc/discussions/7986

**Comment by Tidone** [comment] 2022-10-31 15:37
Hi,
I found that changing the window modality in [the respective source file](https://github.com/keepassxreboot/keepassxc/blob/develop/src/gui/PasswordGeneratorWidget.cpp#L130) from `Qt::ApplicationModal` to `Qt::WindowModal` fixes the problem.

A few quick tests showed that everthying should still work fine with this fix, but I'm not a QT GUI developer, so I don't know if this change breaks anything under the hood.
It would be best if one of the developers takes a look at this.

**Comment by droidmonkey** [comment] 2022-10-31 16:11
Does WindowModal allow the dialog to be shown if the MainWindow is hidden (minimized and/or in tray)?

**Comment by Tidone** [comment] 2022-10-31 17:58
Yes, the dialog is still shown if the main window is minimized or in tray.
The modality shouldn't matter here because you call `raise()` and `activateWindow()` in `BrowserService::showPasswordGenerator()` anyway.


Also, this only masks the underlying issue without fixing it.
Still, I couldn't find any obvious difference between pressing X and pressing the button, so this change can be implemented until the underlying issue is found.
Another "fix" might be to change the window layout to disable/hide the X altogether, but that would be suboptimal from a UX point of view.

**Comment by droidmonkey** [comment] 2022-10-31 19:20
This may be a qt bug in which application modal dialogs don't fire off the closed signal when the x is used.

**Comment by Tidone** [comment] 2022-10-31 19:33
Nevermind, I found the issue:
Right now `PasswordGeneratorWidget::closeEvent` emits the `closed()` signal immediately, which causes the PasswordGeneratorWidget object to be destroyed immediately. That also means that the UI framework will abort its cleanup routines because it references an invalid, destroyed object.

To fix this you have to replace the `emit closed();` in [PasswordGeneratorWidget::closeEvent](https://github.com/keepassxreboot/keepassxc/blob/develop/src/gui/PasswordGeneratorWidget.cpp#L123) with `QTimer::singleShot(0, this, [=] {emit closed();});`.
You also have to replace `event->accept()` with `event->ignore();` in the next line.

That way the signal is emitted after the UI framework has finished handling the user input.

Edit: This is not a QT bug; The closed signal is actually emitted when the X is pressed.

**Comment by droidmonkey** [comment] 2022-10-31 21:01
Can you submit a pull request?

**Comment by droidmonkey** [comment] 2022-10-31 21:05
That isn't a fix that is an anti pattern. We likely need to just delete the closeEvent function and listen for the closed signal on the generation side. Orrrr use a custom signal for a canceled operation.

**Comment by Tidone** [comment] 2022-11-01 11:11
Unfortunately it seems a QWidget doesn't provide an event to signal that the window is closed.
I tried to listen to the QObject::destroyed signal (from [this post](https://stackoverflow.com/a/7944336)), but that causes a crash when the scoped pointer in `BrowserService` is reset.

I don't know that much about Qt GUI programming and don't have the time to dig deeper into the code, so someone else will have to take over from here if you don't want to implement the singleShot approach.

**Comment by droidmonkey** [comment] 2022-11-01 11:37
It's OK we got it from here

**Comment by ghost** [comment] 2023-05-28 12:34
Hey, just chiming in to wake this thread up. I get this one pretty often, a minor annoyance in an otherwise wonderful software :) Thanks!

**Closed as completed** 2023-11-23 03:49 UTC
Labels: high priority :rotating_light:, feature: Browser
