### ISSUE TITLE
Locking is incorrect on linux.

### ISSUE THREAD

**Issue by t4777sd** [keepassxreboot/keepassxc#572] opened 2017-05-12 17:39 UTC
It seems that a lock file is created and if this file exists, then keepass will not allow the editing of the database. The problem is that this file is not removed 100% of the time. For example, if the computer gets suddnely restarted while keepass is open.

It would be a lot better to use a real file locking mechanism using FLOCK. That way, anytime the process crashes the lock is released. As it is now, this file must manually be deleted which for non-technical users will probably confuse them and basically make the software unusable for them (as they will have no idea how to work-around the bug).

Or, alternatively, the user should be prompted with the ability to open the database in write-mode regardless of the existence of the lock-file.

**Comment by TheZ3ro** [comment] 2017-05-12 20:20
What version of KeePassXC are you using? Next time don't delete the Issue template.
Anyway this is already implemented. If you open a kdbx and a lock file is found, this dialog will appear
![istantanea_2017-05-12_22-19-06](https://cloud.githubusercontent.com/assets/686894/26015405/256533c0-3761-11e7-8cfb-7d1552e76f49.png)
Note: Si stands for Yes

**Comment by phoerious** [comment] 2017-05-14 13:36
Stale lock files are automatically removed next time you launch KeePassXC.

**Comment by droidmonkey** [comment] 2017-11-20 17:02
Will be corrected through (and duplicate of) #1002

**Closed** 2017-11-20 17:02 UTC
