### ISSUE TITLE
Program crashes when left open with a locked DB [Windows / keepassxc 2.6.1]

### ISSUE THREAD

**Issue by styu99** [keepassxreboot/keepassxc#5348] opened 2020-08-27 16:15 UTC
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
The program crashes when its left open, but the database remains unlocked. The error message given is:
```
The instruction at 0X00000000003D8E8E referenced memory at
0x000000000000012. The memory could not be read.
```
![chrome_2020-08-27_11-01-57](https://user-images.githubusercontent.com/8606886/91467372-18da1b80-e856-11ea-9f1e-ef6543a43ff0.png)

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Leave the program open on windows, but without unlocking the DB.

## Expected Behavior
The program to continue running without any issues.

## Actual Behavior
It crashes as shown in the overview.

## Context
KeePassXC - Version 2.6.1
Revision: 9a35bba

Qt 5.15.0
Debugging mode is disabled.

Operating system: Windows 10 Version 1903
CPU architecture: x86_64
Kernel: winnt 10.0.18362

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows

**Comment by NodokaMurmevent** [comment] 2020-09-02 07:52
same problem for me : 
![unknown-kee](https://user-images.githubusercontent.com/16167605/91954284-20d00a80-ecf1-11ea-8c34-7020c2de145c.png)

Operating system: Windows 10 Version 2004
CPU architecture: x86_64

**Comment by dnlmlr** [comment] 2020-12-13 16:50
I also have the same issue. This is sporadically happening pretty much since I can remember, but I actually never wrote a report.
The issue only occours on Windows 10 for me and not on the linux version.

I noticed that in #4514 as well as in this issue, the YubiKey extension was enabled, which I am also using. Might be worth knowing.

**Comment by droidmonkey** [comment] 2020-12-13 17:51
Is your database also in a locked state?

**Comment by dnlmlr** [comment] 2020-12-13 18:15
Yes I am 99% sure that it is always crashing when in locked state. 

Since I had this issue for quite some time it doesn't really make sense to specify a Windows version here, but it is happening for over a year, maybe even two years. Right now I'm on Windows 10 build 19042.572

I am currently using KeepassXC version 2.6.1, but as stated above, the issue was happening with the older versions as well.

Since it happens so sporadically I don't have an error message either, but I can share it the next time it happens. Although I suspect it might actually be the same memory address as in the other images since I remember it to be the same on different crashes

**Comment by droidmonkey** [comment] 2020-12-13 18:22
No need for an error message, its not useful anyway. Can you update to 2.6.2? I fixed a crash with capslock in that version.

**Comment by dnlmlr** [comment] 2020-12-13 18:38
Thanks for the responses.

I just updated to 2.6.2 and I will keep it locked for a while and check if the crash happens again.

If it crashes at any time, I'll update you. So if it doesn't crash in the next 1-2 week it probably didn't happen again. I'll still try to confirm that it's not crashing after a week or two anyways. (I will set up a reminder for 1 week).

**Comment by droidmonkey** [comment] 2020-12-13 18:49
Great thanks!

**Comment by styu99** [comment] 2020-12-13 23:00
Just wanted to give an update and say that I haven't really noticed any crashing as of late, perhaps the new versions fixed it? I'll keep you updated.

**Comment by dnlmlr** [comment] 2020-12-16 07:59
I also have not experienced any crashes over the last 3 days. This looks extremely promising as I would have expeced serveral crashes in this time, since I left it unlocked on purpose to provoke the bug. 

If anything changes and I get the crash again I'll be sure to let you know, but for now it looks like it is fixed with 2.6.2 👍

**Comment by dnlmlr** [comment] 2021-01-28 12:59
It is now over a month later and I have not yet experienced a single crash. This suggests that the issue is fixed. 👌

I think this can be closed if there are no other objections.

**Comment by phoerious** [comment] 2021-01-28 13:36
Thanks for letting us know.

**Closed by phoerious** 2021-01-28 13:36 UTC
Labels: bug
