### ISSUE TITLE
Unable to drag-and-drop entries between groups

### ISSUE THREAD

**Issue by rickvanderzwet** [keepassxreboot/keepassxc#4184] opened 2020-01-14 15:15 UTC
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
When selecting a entry and and dragging it with the left mouse-button down to a new folder, I expect the entry to be moved to the new location.

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
Entry is not moved to new location, just remains at old location

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
![Screencast from 14-01-20 16:09:42](https://user-images.githubusercontent.com/186766/72356168-11ac3600-36e9-11ea-84e5-e9972b3d74dd.gif)

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )

## Debug Info

```
[rick@krypton ~]$ keepassxc --debug-info
QSocketNotifier: Can only be used with threads started with QThread
KeePassXC - Version 2.5.2
Revision: 62cda9d

Qt 5.13.2
Debugging mode is disabled.

Operating system: Fedora 31 (Workstation Edition)
CPU architecture: x86_64
Kernel: linux 5.3.16-300.fc31.x86_64

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.5
```

Libraries:
```
[rick@krypton ~]$ ldd /usr/bin/keepassxc
	linux-vdso.so.1 (0x00007ffe1cace000)
	libQt5Svg.so.5 => /lib64/libQt5Svg.so.5 (0x00007f82480b2000)
	libqrencode.so.4 => /lib64/libqrencode.so.4 (0x00007f82480a2000)
	libQt5Concurrent.so.5 => /lib64/libQt5Concurrent.so.5 (0x00007f8248099000)
	libsodium.so.23 => /lib64/libsodium.so.23 (0x00007f824803f000)
	libykpers-1.so.1 => /lib64/libykpers-1.so.1 (0x00007f824802b000)
	libargon2.so.1 => /lib64/libargon2.so.1 (0x00007f8248021000)
	libz.so.1 => /lib64/libz.so.1 (0x00007f8248005000)
	libQt5Network.so.5 => /lib64/libQt5Network.so.5 (0x00007f8247e43000)
	libQt5Widgets.so.5 => /lib64/libQt5Widgets.so.5 (0x00007f8247799000)
	libQt5Gui.so.5 => /lib64/libQt5Gui.so.5 (0x00007f824725a000)
	libgcrypt.so.20 => /lib64/libgcrypt.so.20 (0x00007f824713c000)
	libquazip5.so.1 => /lib64/libquazip5.so.1 (0x00007f8247107000)
	libQt5DBus.so.5 => /lib64/libQt5DBus.so.5 (0x00007f8247069000)
	libQt5Core.so.5 => /lib64/libQt5Core.so.5 (0x00007f8246b35000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f824693b000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f82467f5000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f824662c000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f824660a000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f82465ee000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f8248613000)
	libyubikey.so.0 => /lib64/libyubikey.so.0 (0x00007f82465e9000)
	libusb-1.0.so.0 => /lib64/libusb-1.0.so.0 (0x00007f82465cd000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f82465c6000)
	libssl.so.1.1 => /lib64/libssl.so.1.1 (0x00007f8246530000)
	libcrypto.so.1.1 => /lib64/libcrypto.so.1.1 (0x00007f8246250000)
	libGL.so.1 => /lib64/libGL.so.1 (0x00007f82461ba000)
	libpng16.so.16 => /lib64/libpng16.so.16 (0x00007f8246184000)
	libharfbuzz.so.0 => /lib64/libharfbuzz.so.0 (0x00007f824608c000)
	libgpg-error.so.0 => /lib64/libgpg-error.so.0 (0x00007f8246069000)
	libdbus-1.so.3 => /lib64/libdbus-1.so.3 (0x00007f8246013000)
	libsystemd.so.0 => /lib64/libsystemd.so.0 (0x00007f8245f5e000)
	libicui18n.so.63 => /lib64/libicui18n.so.63 (0x00007f8245c7b000)
	libicuuc.so.63 => /lib64/libicuuc.so.63 (0x00007f8245aa8000)
	libpcre2-16.so.0 => /lib64/libpcre2-16.so.0 (0x00007f8245a24000)
	libglib-2.0.so.0 => /lib64/libglib-2.0.so.0 (0x00007f82458fc000)
	libudev.so.1 => /lib64/libudev.so.1 (0x00007f82458ce000)
	libGLX.so.0 => /lib64/libGLX.so.0 (0x00007f8245898000)
	libX11.so.6 => /lib64/libX11.so.6 (0x00007f8245752000)
	libXext.so.6 => /lib64/libXext.so.6 (0x00007f824573d000)
	libGLdispatch.so.0 => /lib64/libGLdispatch.so.0 (0x00007f8245680000)
	libfreetype.so.6 => /lib64/libfreetype.so.6 (0x00007f82455bf000)
	libgraphite2.so.3 => /lib64/libgraphite2.so.3 (0x00007f824559a000)
	librt.so.1 => /lib64/librt.so.1 (0x00007f824558d000)
	liblzma.so.5 => /lib64/liblzma.so.5 (0x00007f8245564000)
	liblz4.so.1 => /lib64/liblz4.so.1 (0x00007f8245543000)
	libicudata.so.63 => /lib64/libicudata.so.63 (0x00007f8243b52000)
	libpcre.so.1 => /lib64/libpcre.so.1 (0x00007f8243ade000)
	libxcb.so.1 => /lib64/libxcb.so.1 (0x00007f8243ab1000)
	libbz2.so.1 => /lib64/libbz2.so.1 (0x00007f8243a9d000)
	libXau.so.6 => /lib64/libXau.so.6 (0x00007f8243a97000)
```

```
[rick@krypton ~]$ uname -a
Linux krypton 5.3.16-300.fc31.x86_64 #1 SMP Fri Dec 13 17:59:04 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
[rick@krypton ~]$ lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	Fedora
Description:	Fedora release 31 (Thirty One)
Release:	31
Codename:	ThirtyOne
```

Enabled extensions:
- NONE

**Comment by porjo** [comment] 2020-01-16 05:04
Duplicate of #3930 ?

**Comment by rickvanderzwet** [comment] 2020-01-16 09:48
> Duplicate of #3930 ?

You are right it's a duplicate. The suggested work-around at https://github.com/keepassxreboot/keepassxc/issues/3930#issuecomment-568012940  `keepassxc -platform xcb` does work.

I am puzzled how-ever why the issue is closed though, since the underlying issue itself it not fixed (yet), merely identified. I know it has a limited set of users effected ([using QT natively on wayland](https://gitlab.gnome.org/GNOME/mutter/issues/965#note_667401)), how-ever it would be great if it some got listed as known-issue and/or provide UI alternatives like for example (cut/copy & paste style) shortcuts on the menu.

**Comment by droidmonkey** [comment] 2020-01-16 13:22
We tend to not keep issues open that are not within our control. That issue is well documented as far as workaround and uplink to the source bug report. It does need to be retitled to be more searchable.

For what its worth this isn't even a Qt bug, it's a bug in Gnome wayland since they yanked support for v1 of a protocol.

**Comment by droidmonkey** [comment] 2020-01-16 13:27
I also want to take this moment to make a point... when you create issues you have the opportunity to immediately browse existing open/closed issues that are related to the title you choose. I just replicated your process and found #3930 popped up immediately...

![image](https://user-images.githubusercontent.com/2809491/72528850-04eb2780-383a-11ea-83b8-fcf4f965ce34.png)

**Closed by droidmonkey** 2020-01-16 13:27 UTC
Labels: bug

**Comment by rickvanderzwet** [comment] 2020-01-16 15:36
> I also want to take this moment to make a point... when you create issues you have the opportunity to immediately browse existing open/closed issues that are related to the title you choose. I just replicated your process and found #3930 popped up immediately...

Fair point, I made the wrong assumption about the fact the bug is present and no open issue was present to represent it. 

Never considered the possibility: 
> We tend to not keep issues open that are not within our control.

Lesson learned :-)
