### ISSUE TITLE
System-wide hotkey to show KeepassXC window

### ISSUE THREAD

**Issue by boolbag** [keepassxreboot/keepassxc#10237] opened 2024-01-28 09:23 UTC
## Summary
Under Tools/Options/Integration, Keepass has a box to define a system-wide shortcut to show the Keepass window.
This is very useful when global autotype doesn't work, for instance.
This shortcut works whether Keepass has a window in the tray or in the taskbar.
It would be lovely to have the same feature in KeepassXC

## Examples
![Clipboard Image](https://github.com/keepassxreboot/keepassxc/assets/7551671/ff1f5dd5-7460-48aa-af9d-40ee919c7b7b)

## Context
Quickly switch to KeepassXC, which happens multiple times a day.

## Workaround
This workaround using autohotkey works, but could be improved, as it relaunches KeepassXC when it's in the system tray.

```
; Ctrl + Alt + K: switch to KeepassXC
^!K::                            ; Ctrl + Alt + K
if WinExist("ahk_exe KeePassXC.exe") {
   WinActivate  ; Uses the last found window.  
   }
else {
   Run, C:\Program Files\KeePassXC\KeePassXC.exe
}
Return
```

**Comment by droidmonkey** [comment] 2024-01-28 11:19
Duplicate of #99

**Closed as not planned by droidmonkey** 2024-01-28 11:19 UTC
