### ISSUE TITLE
Search bar is unavailable in a small window (<750px)

### ISSUE THREAD

**Issue by shurph** [keepassxreboot/keepassxc#2198] opened 2018-08-13 15:58 UTC
The search bar hides when a window size is less than 750px. This behavior causes the issue that you can't use search at all on such small window (hidden search bar can't being focused so you can't type text into it).

BTW, I realize that min window size is 750px for application. But I also believe that this min size was chosen by mistake :-) Because it's too big min size.

## Expected Behavior
Search bar is available in a small window (550-650px).
![keepassxc-searchbar-proposal](https://user-images.githubusercontent.com/2353345/44043143-c8c52c6e-9f2a-11e8-9148-dc1ab0c13558.png)

## Current Behavior
![keepassxc-searchbar-issue](https://user-images.githubusercontent.com/2353345/44043061-958abff8-9f2a-11e8-9028-a066eec68f38.png)

## Context
I prefer to have small window for keepass, my window manager allows me to resize a window how I want.
But without a search bar I can't use app normally.

## Debug Info
KeePassXC - Version 2.3.3

Revision: 0a155d8

**Comment by droidmonkey** [comment] 2018-08-14 01:35
This is a duplicate of #505

**Closed** 2019-07-10 03:11 UTC
Labels: bug, duplicate, user interface
