### ISSUE TITLE
Heavy bug on create and edit DBs

### ISSUE THREAD

**Issue by Kahru** [keepassxreboot/keepassxc#4133] opened 2020-01-08 09:01 UTC
Hello,

if i create a new db with keepasxc the systems hangs after create. If then i reopen this database i can create one entry and can save this.  If i make then a new entry, the the software overwrite my first entry and all data are data lost.

if i import a database created with windows keepass2 2.43 then this database works without errors.

System KUbuntu 18.10
KeypassXC 2.4.x and 2.5.2

**Comment by phoerious** [comment] 2020-01-08 10:18
Do you happen to have a Ryzen CPU?

**Comment by Kahru** [comment] 2020-01-08 10:56
Hello, yes it is a Ryzen 5 2600

**Comment by droidmonkey** [comment] 2020-01-08 11:04
You need to update your firmware immediately.

**Comment by Kahru** [comment] 2020-01-08 11:08
What did you mean? Bios?

**Comment by droidmonkey** [comment] 2020-01-08 12:34
Yes

**Comment by phoerious** [comment] 2020-01-08 12:39
Duplicate of #3415.

**Closed by phoerious** 2020-01-08 12:39 UTC

**Comment by Kahru** [comment] 2020-01-08 14:00
Hello, after bios update a part of the problem seems to disappear. I can create now more then one key. But on create a new database keepass hangs equally as before. I must shut down the software and reopen the new created empty database. Then i can make new entrys.

**Comment by droidmonkey** [comment] 2020-01-09 03:12
Sorry but have never experienced that problem before and you are the first to report it. Not sure what to do about it, could be something on your end unfortunately.

**Comment by Kahru** [comment] 2020-01-10 06:39
Thank you for your answer. 

Tis morning i had tested it again. I open the software. All is empty, no other databases are open in tabs. Then i create a new database. The name dialog and the save dialog are working perfect. After save i can see the new kbdx file on my file system. But then keepassxc hangs. I see no root group on the left side. If i now close keepassxc and reopen my new kbdx-file. Then i see the root group and all seems to be work. I can live with this error ... its only or your information.

For your background: We are a webdesign company and used over years keypass2 on windows. We have many kbdx-files here. Now we changed our systems to Kubuntu 18.10. KeePassXC has the version 2.5.2.

**Comment by droidmonkey** [comment] 2020-01-10 11:15
Can you run a develop snapshot on your system, perhaps it can drop a core dump for us. Https://snapshot.keepassxc.org

**Comment by bear30** [comment] 2020-01-10 12:46
Ok, i tested now the snapshop from 08-01-2020 00:58. This version doesn't have this create problem. It works perfect!

**Comment by droidmonkey** [comment] 2020-01-10 14:03
Interesting! I assume you tested the AppImage. That would point to a problem with a library on your system.

**Comment by bear30** [comment] 2020-01-10 14:55
Yes it was the image from 08-01-2020

![Screenshot_20200110_155327](https://user-images.githubusercontent.com/5871470/72162077-92092900-33c1-11ea-8fb4-0a75e4f59505.png)
