### ISSUE TITLE
PPA not available for Ubuntu 21.04 (Hirsute)

### ISSUE THREAD

**Issue by errotu** [keepassxreboot/keepassxc#6460] opened 2021-04-28 13:52 UTC
Currently, the [official KeePassXC PPA](https://launchpad.net/~phoerious/+archive/ubuntu/keepassxc) is not yet available for Ubuntu 21.04 (Hirsute).

Thanks for all your efforts and your great work!

**Comment by phoerious** [comment] 2021-04-29 13:50
Duplicate of https://github.com/keepassxreboot/keepassxc-packaging/issues/16

**Closed by phoerious** 2021-04-29 13:50 UTC
Labels: distribution, platform: Linux
