### ISSUE TITLE
Crash at startup on Mac OS 10.11.6

### ISSUE THREAD

**Issue by moesphemie** [keepassxreboot/keepassxc#74] opened 2016-11-03 10:58 UTC
I've followed all instructions and got through the install process according to the wiki-page. Everything went well without any problems. When i try to open the App from /Applications by double clicking on the icon, an general-app-looking icon jumps on the dock, vanishes and then a window pops out telling me "KeePassXC closes unexpectedly"
## Expected Behavior

The App to start

## Current Behavior

Mac Error Dialog pops up

## Error report
[Gist crash report](https://gist.github.com/moesphemie/3ed0236c6ff118d241ac0b179e23df13)

## Your Environment

* KeePassXR version/commit used: 
* Qt version (e.g. Qt 5.3): 5.7.0
* Compiler (e.g. Clang++3.6.0): clang-703.0.31
* Operating System and version: Mac OS 10.11.6

**Comment by TheZ3ro** [comment] 2016-11-03 12:04
Seems a duplicate of https://github.com/keepassxreboot/keepassxc/issues/60
Can you try starting `/Applications/KeePassXC.app/Contents/MacOS/KeePassXC` manually from a Terminal and report the error?

**Comment by moesphemie** [comment] 2016-11-03 12:12
Ah i see, it seems to be the same problem.

I also get the same error:

> This application failed to start because it could not find or load the Qt platform plugin "cocoa"
in "".

> Reinstalling the application may fix this problem.
> Abort trap: 6

Excecuting this workaround:

https://github.com/keepassxreboot/keepassxc/issues/60#issuecomment-256112837

also didn't do the job for me

**Comment by TheZ3ro** [comment] 2016-11-03 12:32
Sincerely i don't know why the workaround doesn't work.

- @rockihack the shell workaround needs macdeployqt or can also work with DeployQt4 ?

**Comment by moesphemie** [comment] 2016-11-03 13:01
Maybe because of this?

> Won't work with Qt 5.1.0

[macdeploymentqt repo](https://github.com/MaximAlien/macdeployqt)

**Comment by rockihack** [comment] 2016-11-03 13:41
You need to use macdeployqt + workaround.

**Comment by TheZ3ro** [comment] 2016-11-03 14:12
Ok thanks @rockihack for your constant help

@moesphemie Unfortunately you need to wait for a fix or manually patch with this changes (don't care about build.sh file) https://github.com/rockihack/keepassx/commit/c85b45a8724bec999372d93617947b518941764a

**Comment by moesphemie** [comment] 2016-11-03 14:43
Alright, i'll give it a try:

src/autotype/mac/CMakeLists.txt

is for me 

src/autotype/CMakeLists.txt

is this the file i've to modify? The code here is this:

    if(UNIX AND NOT APPLE)
      find_package(X11)
      find_package(Qt5X11Extras 5.2)
      if(PRINT_SUMMARY)
        add_feature_info(libXi X11_Xi_FOUND "The X11 Xi Protocol library is required for auto-type")
        add_feature_info(libXtst X11_XTest_FOUND "The X11 XTEST Protocol library is required for auto-type")
        add_feature_info(Qt5X11Extras Qt5X11Extras_FOUND "The Qt5X11Extras library is required for auto-type")
      endif()

      if(X11_FOUND AND X11_Xi_FOUND AND X11_XTest_FOUND AND Qt5X11Extras_FOUND)
        add_subdirectory(xcb)
      endif()
    endif()

    if(WITH_TESTS)
      # autotype non supported on Windows right now
      if(UNIX)
        add_subdirectory(test)
      endif()
    endif()

**Comment by rockihack** [comment] 2016-11-03 14:47
You can ignore `src/autotype/mac/CMakeLists.txt` it belongs to mac autotype.
Merge `src/CMakeLists.txt` and update `QT_BINARY_DIR` if you didn't install qt5 with homebrew.

**Comment by moesphemie** [comment] 2016-11-03 15:01
Now i get this

    objc[9335]: Class RunLoopModeTracker is implemented in both /usr/local/Cellar/qt5/5.7.0/lib/QtCore.framework/Versions/5/QtCore and /Applications/KeePassXC.app/Contents/Frameworks/QtCore.framework/Versions/5/QtCore. One of the two will be used. Which one is undefined.
    objc[9335]: Class NotificationReceiver is implemented in both /Applications/KeePassXC.app/Contents/Frameworks/QtWidgets.framework/Versions/5/QtWidgets and /usr/local/Cellar/qt5/5.7.0/lib/QtWidgets.framework/Versions/5/QtWidgets. One of the two will be used. Which one is undefined.
    QCoreApplication::arguments: Please instantiate the QApplication object first
    QCommandLineParser: argument list cannot be empty, it should contain at least the executable name

**Comment by rockihack** [comment] 2016-11-03 16:31
This is the exact error that happens **without** the workaround.
Make sure that the script has write permissions or execute with `sudo`.

```
#!/bin/bash

# Canonical path to qt5 directory
QT5_DIR="/usr/local/Cellar/qt5/5.7.0"

# Change qt5 framework ids
for framework in $(find "$QT5_DIR/lib" -regex ".*/\(Qt[a-zA-Z]*\)\.framework/Versions/5/\1"); do
    echo "$framework"
    install_name_tool -id "$framework" "$framework"
done
```

**Comment by moesphemie** [comment] 2016-11-03 16:49
Sweet! It's working now – Thanks a lot you two guys!!
I had to delete the build-folder and the keepass-app and rebuild everything to get it work.

**Closed** 2016-11-04 01:26 UTC
