### ISSUE TITLE
2.4.0, with the browser extension: multiple problems

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [keepassxreboot/keepassxc#2821] opened 2019-03-20 23:51 UTC
(What follows is insufficiently detailed to comprise a proper bug report. Yet, I found no forum for KeePassXC and no other means of contacting the team except via IRC, and, at present, I do not have time for IRC. I have, however, searched the open issues and found none that match anything below. Still, some of the problems that I report may owe somehow to my particular setup.)

- When the KeePassXC application is not running, and I run a browser (Firefox) that I have integrated with KeePassXC, and press the keyboard combination that I have assigned to and via the browser extension, I see a rather cryptic error message - which unfortunately I find it hard to capture (since my Windows screenshot tool has no delay function).

- When KeePassXC *is* running, but my database is not unlocked, and I press the key combination that I have assigned to the extension, a prompt to open my database appears - but it opens behind other windows.

- After I had unlocked the database, pressing the key combination did nothing, and clicking the browser extension's icon displayed an error and displayed a 'reconnect' button. After clicking that button, I received a message saying: 'Error: no logins found'.

- Also, I am confused, even after reading the FAQ, about the relationship between the keyboard shortcut assigned in KeePassXC and the shortcuts assignable in the browser extension.

&nbsp&nbsp;&nbsp;&nbsp;KeePassXC works well for me on Linux. On Windows, at least with version 2.4.0, I have to try to deal with all the above. (My Linux version of KeePassXC is an earlier version, because, after the website announced 2.4 for Linux, the announcement disappeared and I have found no way, as of yet, of obtaining 2.4 for Linux.) On Windows, I am returning, now, to KeePass (as against KeePassXC).

**KeePassXC - Version 2.4.0
Revision: c51752d

Libraries:
- Qt 5.12.1
- libgcrypt 1.8.4

Operating system: Windows 8.1 (6.3)
CPU architecture: x86_64
Kernel: winnt 6.3.9600

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey**

**Comment by varjolintu** [comment] 2019-03-21 05:27
>     * When the KeePassXC application is not running, and I run a browser (Firefox) that I have integrated with KeePassXC, and press the keyboard combination that I have assigned to and via the browser extension, I see a rather cryptic error message - which unfortunately I find it hard to capture (since my Windows screenshot tool has no delay function).

KeePassXC must be running so the extension can connect to it. It doesn't reconnect automatically yet. There's a few issues with the pull request we must first solve. If KeePassXC was started later than your browser, for now you have to reconnect to it using the extension popup icon and use the Reload button.

>     * When KeePassXC _is_ running, but my database is not unlocked, and I press the key combination that I have assigned to the extension, a prompt to open my database appears - but it opens behind other windows.

This is not a bug. In Windows this is not simply possible. See [this](https://docs.microsoft.com/en-us/windows/desktop/api/winuser/nf-winuser-setforegroundwindow). A quote: "An application cannot force a window to the foreground while the user is working with another window. Instead, Windows flashes the taskbar button of the window to notify the user. "

>     * After I had unlocked the database, pressing the key combination did nothing, and clicking the browser extension's icon displayed an error and displayed a 'reconnect' button. After clicking that button, I received a message saying: 'Error: no logins found'.

Does your credential URL match the page URL? The schemes must be also matched if you haven't disabled the setting for matching them. An entry with `http://site.com` will not match with `https://site.com`. However, `site.com` will work with both.

>     * Also, I am confused, even after reading the FAQ, about the relationship between the keyboard shortcut assigned in KeePassXC and the shortcuts assignable in the browser extension.

Please wait for the official documentation to arrive. You can modify the shortcuts manually from both browsers.

**Comment by sherghan** [comment] 2019-03-21 09:20
> message saying: 'Error: no logins found'.

On MacOS once I change something in KeePassXC entry, I need to close and reopen Firefox to get this change to propagate to KeePassWC-Browser. Untill then the entry is not usable at all and this message appears in FF.

Maybe this will help.

P.S.
Exemplary change I frequently do is edition of `KeePassXC-Browser Settings` in the _Advanced_ tab of entry edit view.

**Comment by varjolintu** [comment] 2019-03-21 09:24
@sherghan Reloading a page or switching a ta b should be enough, because the credentials are retrieved again.

**Comment by sherghan** [comment] 2019-03-22 07:42
@varjolintu 
Reloading page helps if database was unlocked.
In my case (described above) nothing helps, but to close and reopen whole FF. :-(

I haven't noted that earlier, I have the following FF extensions installed:
NoScript, NokeAnything, Sylish

**Comment by varjolintu** [comment] 2019-03-22 09:53
I'm quite sure this is related to https://github.com/keepassxreboot/keepassxc-browser/pull/358, and will be hopefully fixed soon when the new version is released.

**Comment by droidmonkey** [comment] 2019-04-06 04:54
Closing as there doesn't seem to be an active issue here.

**Closed by droidmonkey** 2019-04-06 04:54 UTC
Labels: bug, plugin: Browser integration
