### ISSUE TITLE
Can't download favicon from DuckDuckGo use proxychains4 with sock5

### ISSUE THREAD

**Issue by jamesmccoy0405** [keepassxreboot/keepassxc#4851] opened 2020-06-12 17:24 UTC
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
The CCP uses GFW to make people unable to use DuckDuckGo.
And the proxychains4 (https://github.com/rofl0r/proxychains-ng) can get throught GFW.
But new version KeePassXC can't use proxychains4 with sock5.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Double click KeePassXC's AppImage and open database;
2. Enable use DuckDuckGo service to download website icons from settings>security privacy;
3. Edit entry>icon>download favicon show “Unable to fetch favicon.”;
4. Close KeePassXC;
5. Enter proxychains4 ./KeePassXC-2.6.0-beta1-x86_64.AppImage  from Terminal;
6. Open database;
7. Edit entry>icon>download favicon show “Unable to fetch favicon.” and Terminal show "qt.network.ssl: QSslSocket::connectToHostEncrypted: TLS initialization failed".

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Can download favicon from DuckDuckGo like old version KeePassXC's AppImage

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
1. Can't link DuckDuckGo service;
2. Unable to fetch favicon;
3. qt.network.ssl: QSslSocket::connectToHostEncrypted: TLS initialization failed.

## Context
[NOTE]: # ( Give us any additional information you may have. )
proxychains4: https://github.com/rofl0r/proxychains-ng

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.0-beta1
Build Type: PreRelease
Revision: e5b0219
Distribution: AppImage
Qt 5.14.2
Debugging mode is disabled.
Operating system: Ubuntu 20.04 LTS
CPU architecture: x86_64
Kernel: linux 5.4.0-37-generic
Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration
Cryptographic libraries:
 libgcrypt 1.8.1

and

KeePassXC - Version 2.5.4
Revision: dcca5aa
Distribution: AppImage
Qt 5.12.7
Debugging mode is disabled.
Operating system: Ubuntu 20.04 LTS
CPU architecture: x86_64
Kernel: linux 5.4.0-37-generic
Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration
Cryptographic libraries:
 libgcrypt 1.8.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: Ubuntu 20.04 LTS
Desktop Env: Gnome 3.36.2
Windowing System: X11

**Comment by droidmonkey** [comment] 2020-06-12 20:36
@phoerious is this an appimage problem or a Qt problem? Either way its not a KeePassXC proper problem.

**Comment by jamesmccoy0405** [comment] 2020-06-13 00:33
In versions 2.4.3 and earlier, Terminal shows:
[proxychains] Strict chain  ...  127.0.0.1:10808  ...  icons.duckduckgo.com:443  ...  OK
qt.network.ssl: QSslSocket: cannot call unresolved function SSLv23_client_method
qt.network.ssl: QSslSocket: cannot call unresolved function SSL_CTX_new
qt.network.ssl: QSslSocket: cannot call unresolved function SSL_library_init
qt.network.ssl: QSslSocket: cannot call unresolved function ERR_get_error
qt.network.ssl: QSslSocket: cannot call unresolved function ERR_get_error

I can't find the version where favicon can be downloaded last year.
I will try change proxychains4 setting to deal with it and find the old KeePassXC version which I can download favicon successful. 

version information:
KeePassXC - Version 2.4.3
Revision: 5d6ef0c
Distribution: AppImage
Qt 5.10.1
Debugging mode is disabled.
Operating system: Ubuntu 20.04 LTS
CPU architecture: x86_64
Kernel: linux 5.4.0-37-generic
Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey
Cryptographic libraries:
 libgcrypt 1.8.1

**Comment by jamesmccoy0405** [comment] 2020-06-13 00:34
Sorry to touch the close button.

**Comment by jamesmccoy0405** [comment] 2020-06-13 06:06
this version is ok, install from  sudo apt install keepassxc 
start with proxychains4 keepassxc
Terminal show:
[proxychains] Strict chain  ...  127.0.0.1:10808  ...  icons.duckduckgo.com:443  ...  OK

KeePassXC - Version 2.4.3
Revision: 5d6ef0c
Qt 5.12.8
Debugging mode is disabled.
Operating system: Ubuntu 20.04 LTS
CPU architecture: x86_64
Kernel: linux 5.4.0-37-generic
Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey
Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by jamesmccoy0405** [comment] 2020-06-13 06:32
test KeePassXC version with AppImage
All failed with Unable to fetch favicon
1. KeePassXC-2.6.0-beta1-x86_64.AppImage
2. KeePassXC-2.5.4-x86_64.AppImage
3. KeePassXC-2.5.3-x86_64.AppImage
4. KeePassXC-2.5.2-x86_64.AppImage
5. KeePassXC-2.5.1-x86_64.AppImage
6. KeePassXC-2.5.0-x86_64.AppImage
7. KeePassXC-2.4.3-x86_64.AppImage
8. KeePassXC-2.4.2-x86_64.AppImage
9. KeePassXC-2.4.1-x86_64.AppImage
10. KeePassXC-2.4.0-x86_64.AppImage

2.5.0 to 2.6.0 beta1
qt.network.ssl: QSslSocket::connectToHostEncrypted: TLS initialization failed.

2.4.0 to 2.4.3
[proxychains] Strict chain ... 127.0.0.1:10808 ... icons.duckduckgo.com:443 ... OK
qt.network.ssl: QSslSocket: cannot call unresolved function SSLv23_client_method
qt.network.ssl: QSslSocket: cannot call unresolved function SSL_CTX_new
qt.network.ssl: QSslSocket: cannot call unresolved function SSL_library_init
qt.network.ssl: QSslSocket: cannot call unresolved function ERR_get_error
qt.network.ssl: QSslSocket: cannot call unresolved function ERR_get_error

**Comment by jamesmccoy0405** [comment] 2020-06-13 06:47
Snap verison is ok, but  browsers installed as snaps are currently not supported.
KeePassXC - Version 2.5.4
Revision: dcca5aa
Distribution: Snap
Qt 5.9.5
Debugging mode is disabled.
Operating system: Ubuntu Core 18
CPU architecture: x86_64
Kernel: linux 5.4.0-37-generic
Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration
Cryptographic libraries:
 libgcrypt 1.8.1

propsReply "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.283\" (uid=1000 pid=21121 comm=\"/snap/keepassxc/784/usr/bin/keepassxc -style fusio\" label=\"snap.keepassxc.keepassxc (enforce)\") interface=\"org.freedesktop.DBus.Properties\" member=\"GetAll\" error name=\"(unset)\" requested_reply=\"0\" destination=\"org.freedesktop.NetworkManager\" (uid=0 pid=1442 comm=\"/usr/sbin/NetworkManager --no-daemon \" label=\"unconfined\")"
nmReply "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.283\" (uid=1000 pid=21121 comm=\"/snap/keepassxc/784/usr/bin/keepassxc -style fusio\" label=\"snap.keepassxc.keepassxc (enforce)\") interface=\"org.freedesktop.NetworkManager\" member=\"GetDevices\" error name=\"(unset)\" requested_reply=\"0\" destination=\"org.freedesktop.NetworkManager\" (uid=0 pid=1442 comm=\"/usr/sbin/NetworkManager --no-daemon \" label=\"unconfined\")"
"Object path cannot be empty"
QObject::startTimer: Timers cannot have negative intervals

**Comment by droidmonkey** [comment] 2020-06-13 13:42
This is a duplicate of #4219

**Closed by droidmonkey** 2020-06-13 13:42 UTC
Labels: bug

**Comment by phoerious** [comment] 2020-06-13 13:56
It's an OpenSSL and AppImage problem we can't really solve.

**Comment by jamesmccoy0405** [comment] 2020-06-13 14:02
Ok, thx.
