### ISSUE TITLE
When opening KXC from browser focus is on window but writing is in website

### ISSUE THREAD

**Issue by sotypischandy** [keepassxreboot/keepassxc#5469] opened 2020-09-25 07:12 UTC
## Overview
Whenever I want to enter my credentials into a website and open the database through the icon in the browser, KXC pops up. If I start writing I write my password into the website instead of opening my database. 

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. KXC is open and browser plugin for firefox is installed
2. Lock Windows and log back in
3. On a website with login credentials press onto the icon for KXC 
4. KXC pops up in front
5. If you start writing now, you wenter your password into the website

## Expected Behavior
I expect the window that comes on top to automatically have my text cursor in it instead of it being in the windows(browser) behind

## Actual Behavior
The actual text cursor is still in the window AND it looks like you can write in KXC now, but if you start writing it goes into the username field

## Context
I think it is kind of dangerous since I just entererd my master password into a website because I thought that KXC grabbed the text cursor. 

KXC version 2.6.1 (updated froim 2.6.0 just now to see if its gone)
Windows 10 as an OS

## Some personal remarks
Thank you all for this great project! It's my first time reporting a bug, so if I forgot something, I'm sorry.
Best,
Andy

**Comment by varjolintu** [comment] 2020-09-25 13:59
Duplicate of https://github.com/keepassxreboot/keepassxc/issues/5390.

**Closed by varjolintu** 2020-09-25 13:59 UTC
Labels: bug
