### ISSUE TITLE
Error on Mac | Build was successful

### ISSUE THREAD

**Issue by ezeeyahoo** [keepassxreboot/keepassxc#95] opened 2016-11-13 04:54 UTC
$ cmake .. -DCMAKE_OSX_ARCHITECTURES="x86_64"
-- Performing Test WERROR_C_AVAILABLE
-- Performing Test WERROR_C_AVAILABLE - Success
-- Performing Test WERROR_CXX_AVAILABLE
-- Performing Test WERROR_CXX_AVAILABLE - Success
-- Found Gcrypt: /usr/local/lib/libgcrypt.dylib (Required is at least version "1.6.0")
-- Found LibMicroHTTPD: /usr/local/lib/libmicrohttpd.dylib
-- Found ZLIB: /usr/lib/libz.dylib (found version "1.2.8")
-- Performing Test ZLIB_SUPPORTS_GZIP
-- Performing Test ZLIB_SUPPORTS_GZIP - Success
-- Performing Test HAVE_PR_SET_DUMPABLE
-- Performing Test HAVE_PR_SET_DUMPABLE - **Failed**
-- Performing Test HAVE_RLIMIT_CORE
-- Performing Test HAVE_RLIMIT_CORE - Success
-- Performing Test HAVE_PT_DENY_ATTACH
-- Performing Test HAVE_PT_DENY_ATTACH - Success
-- /tmp/keepassxc/share/translations/keepassx_cs.ts;/tmp/keepassxc/share/translations/keepassx_da.ts;/tmp/keepassxc/share/translations/keepassx_de.ts;/tmp/keepassxc/share/translations/keepassx_el.ts;/tmp/keepassxc/share/translations/keepassx_en_plurals.ts;/tmp/keepassxc/share/translations/keepassx_es.ts;/tmp/keepassxc/share/translations/keepassx_fr.ts;/tmp/keepassxc/share/translations/keepassx_id.ts;/tmp/keepassxc/share/translations/keepassx_it.ts;/tmp/keepassxc/share/translations/keepassx_ja.ts;/tmp/keepassxc/share/translations/keepassx_ko.ts;/tmp/keepassxc/share/translations/keepassx_lt.ts;/tmp/keepassxc/share/translations/keepassx_nl_NL.ts;/tmp/keepassxc/share/translations/keepassx_pl.ts;/tmp/keepassxc/share/translations/keepassx_pt_BR.ts;/tmp/keepassxc/share/translations/keepassx_pt_PT.ts;/tmp/keepassxc/share/translations/keepassx_ru.ts;/tmp/keepassxc/share/translations/keepassx_sl_SI.ts;/tmp/keepassxc/share/translations/keepassx_sv.ts;/tmp/keepassxc/share/translations/keepassx_uk.ts;/tmp/keepassxc/share/translations/keepassx_zh_CN.ts;/tmp/keepassxc/share/translations/keepassx_zh_TW.ts
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/keepassxc/build

$ make package
went fine as well
**===============================================**
but while running the app, it gives issue
$ /Applications/KeePassXC.app/Contents/MacOS/KeePassXC ; exit;
objc[7803]: Class RunLoopModeTracker is implemented in both /usr/local/Cellar/qt5/5.7.0/lib/QtCore.framework/Versions/5/QtCore (0x103465df0) and /Applications/KeePassXC.app/Contents/Frameworks/QtCore.framework/Versions/5/QtCore (0x102e95df0). One of the two will be used. Which one is undefined.
objc[7803]: Class NotificationReceiver is implemented in both /Applications/KeePassXC.app/Contents/Frameworks/QtWidgets.framework/Versions/5/QtWidgets (0x1020eb650) and /usr/local/Cellar/qt5/5.7.0/lib/QtWidgets.framework/Versions/5/QtWidgets (0x106433650). One of the two will be used. Which one is undefined.
QCoreApplication::arguments: Please instantiate the QApplication object first
QCommandLineParser: argument list cannot be empty, it should contain at least the executable name

logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
Deleting expired sessions...none found.

[Process completed]

**Comment by TheZ3ro** [comment] 2016-11-13 09:52
You need to follow this step to fix the Qt5 environment [wiki/Building-Environment-on-MacOS#fix-the-qt5-environment](https://github.com/keepassxreboot/keepassxc/wiki/Building-Environment-on-MacOS#fix-the-qt5-environment)

Duplicate of https://github.com/keepassxreboot/keepassxc/issues/74#issuecomment-258168184

**Comment by droidmonkey** [comment] 2016-11-13 12:14
Any idea why people's Qt install is messed up on Mac?

**Comment by TheZ3ro** [comment] 2016-11-13 12:39
By using macdeployqt and Qt5, the fix in the wiki is required in order to avoid the above bug

**Closed** 2016-11-13 14:49 UTC
Labels: duplicate

**Comment by ezeeyahoo** [comment] 2017-01-07 20:18
Issue reproduced after qt5 upgraded..fixed path but script didn't work it seems..

**Comment by TheZ3ro** [comment] 2017-01-07 20:27
Can you please report the output of [this](https://github.com/keepassxreboot/keepassxc/wiki/Building-Environment-on-MacOS#fix-the-qt5-environment) script? Thanks

**Comment by ezeeyahoo** [comment] 2017-01-07 20:33
`/usr/local/Cellar/qt5/5.7.1_1//lib/QtBluetooth.framework/Versions/5/QtBluetooth
/usr/local/Cellar/qt5/5.7.1_1//lib/QtCharts.framework/Versions/5/QtCharts
/usr/local/Cellar/qt5/5.7.1_1//lib/QtCLucene.framework/Versions/5/QtCLucene
/usr/local/Cellar/qt5/5.7.1_1//lib/QtConcurrent.framework/Versions/5/QtConcurrent
/usr/local/Cellar/qt5/5.7.1_1//lib/QtCore.framework/Versions/5/QtCore
/usr/local/Cellar/qt5/5.7.1_1//lib/QtDataVisualization.framework/Versions/5/QtDataVisualization
/usr/local/Cellar/qt5/5.7.1_1//lib/QtDesigner.framework/Versions/5/QtDesigner
/usr/local/Cellar/qt5/5.7.1_1//lib/QtDesignerComponents.framework/Versions/5/QtDesignerComponents
/usr/local/Cellar/qt5/5.7.1_1//lib/QtGamepad.framework/Versions/5/QtGamepad
/usr/local/Cellar/qt5/5.7.1_1//lib/QtGui.framework/Versions/5/QtGui
/usr/local/Cellar/qt5/5.7.1_1//lib/QtHelp.framework/Versions/5/QtHelp
/usr/local/Cellar/qt5/5.7.1_1//lib/QtLocation.framework/Versions/5/QtLocation
/usr/local/Cellar/qt5/5.7.1_1//lib/QtMacExtras.framework/Versions/5/QtMacExtras
/usr/local/Cellar/qt5/5.7.1_1//lib/QtMultimedia.framework/Versions/5/QtMultimedia
/usr/local/Cellar/qt5/5.7.1_1//lib/QtMultimediaWidgets.framework/Versions/5/QtMultimediaWidgets
/usr/local/Cellar/qt5/5.7.1_1//lib/QtNetwork.framework/Versions/5/QtNetwork
/usr/local/Cellar/qt5/5.7.1_1//lib/QtNfc.framework/Versions/5/QtNfc
/usr/local/Cellar/qt5/5.7.1_1//lib/QtOpenGL.framework/Versions/5/QtOpenGL
/usr/local/Cellar/qt5/5.7.1_1//lib/QtPositioning.framework/Versions/5/QtPositioning
/usr/local/Cellar/qt5/5.7.1_1//lib/QtPrintSupport.framework/Versions/5/QtPrintSupport
/usr/local/Cellar/qt5/5.7.1_1//lib/QtPurchasing.framework/Versions/5/QtPurchasing
/usr/local/Cellar/qt5/5.7.1_1//lib/QtQml.framework/Versions/5/QtQml
/usr/local/Cellar/qt5/5.7.1_1//lib/QtQuick.framework/Versions/5/QtQuick
/usr/local/Cellar/qt5/5.7.1_1//lib/QtQuickParticles.framework/Versions/5/QtQuickParticles
/usr/local/Cellar/qt5/5.7.1_1//lib/QtQuickTest.framework/Versions/5/QtQuickTest
/usr/local/Cellar/qt5/5.7.1_1//lib/QtQuickWidgets.framework/Versions/5/QtQuickWidgets
/usr/local/Cellar/qt5/5.7.1_1//lib/QtScript.framework/Versions/5/QtScript
/usr/local/Cellar/qt5/5.7.1_1//lib/QtScriptTools.framework/Versions/5/QtScriptTools
/usr/local/Cellar/qt5/5.7.1_1//lib/QtScxml.framework/Versions/5/QtScxml
/usr/local/Cellar/qt5/5.7.1_1//lib/QtSensors.framework/Versions/5/QtSensors
/usr/local/Cellar/qt5/5.7.1_1//lib/QtSerialBus.framework/Versions/5/QtSerialBus
/usr/local/Cellar/qt5/5.7.1_1//lib/QtSerialPort.framework/Versions/5/QtSerialPort
/usr/local/Cellar/qt5/5.7.1_1//lib/QtSql.framework/Versions/5/QtSql
/usr/local/Cellar/qt5/5.7.1_1//lib/QtSvg.framework/Versions/5/QtSvg
/usr/local/Cellar/qt5/5.7.1_1//lib/QtTest.framework/Versions/5/QtTest
/usr/local/Cellar/qt5/5.7.1_1//lib/QtWebChannel.framework/Versions/5/QtWebChannel
/usr/local/Cellar/qt5/5.7.1_1//lib/QtWebEngine.framework/Versions/5/QtWebEngine
/usr/local/Cellar/qt5/5.7.1_1//lib/QtWebEngineCore.framework/Versions/5/QtWebEngineCore
/usr/local/Cellar/qt5/5.7.1_1//lib/QtWebEngineWidgets.framework/Versions/5/QtWebEngineWidgets
/usr/local/Cellar/qt5/5.7.1_1//lib/QtWebSockets.framework/Versions/5/QtWebSockets
/usr/local/Cellar/qt5/5.7.1_1//lib/QtWebView.framework/Versions/5/QtWebView
/usr/local/Cellar/qt5/5.7.1_1//lib/QtWidgets.framework/Versions/5/QtWidgets
/usr/local/Cellar/qt5/5.7.1_1//lib/QtXml.framework/Versions/5/QtXml
/usr/local/Cellar/qt5/5.7.1_1//lib/QtXmlPatterns.framework/Versions/5/QtXmlPatterns`

**Comment by TheZ3ro** [comment] 2017-01-07 21:01
Try deleting the trailing `/` in your `QT5_DIR` variable.
Then run the script again, compile KeePassXC and execute.

**Comment by ezeeyahoo** [comment] 2017-01-10 15:56
worked..Thanks..extra / can be problematic sometimes specially with RE..hmm..

**Comment by TheZ3ro** [comment] 2017-01-10 21:45
I will specify that in the wiki :+1:
