### ISSUE TITLE
Error while reading the database: Not a KeePass database.

### ISSUE THREAD

**Issue by cryptobasher** [keepassxreboot/keepassxc#7531] opened 2022-03-13 12:25 UTC
Today I faced an issue with one of my databases, it has become 2.3Gb in size and password is incorrect all the time, it says "Error while reading the database: Not a KeePass database." 

how come? My other database opens just fine and it's only 9kb in size. I think this some kind of a bug.

I'm running the latest Kali OS

**Comment by droidmonkey** [comment] 2022-03-13 12:42
Did you attach a humongous file to one of your entries? When it says "its not a keepass database" that means it doesn't even have the magic numbers at the start of the file... and it most definitely is not a keepass database (anymore).

**Comment by checksummaster** [comment] 2022-03-14 16:47
I have same error recently.
My keepass database is just 49k and I can open it with keepass or keepassDX (on android) but not keepassxc (same error, not a keepass database).

Normally my database is on a google drive but also a local copy can't be opened.

I don't know what is exactly the magi number but my database begin int hex with 03D9A29A

**Comment by droidmonkey** [comment] 2022-03-14 16:51
Try resyncing the file. There was clearly a copy error that occurred.

**Comment by checksummaster** [comment] 2022-03-14 17:11
Thank for the answer, maybe it was that.
After opening it with keepass (local copy and google drive copy), it seems that keepassxc works again.
Maybe keepass do something because the timestamp of the database file change.
I suspect keepassdx to write something wrong and keepass make a correction to the file (or just changing timestamp force a resyncing in keepassxc??).

I try to reproduce but I can't since I open all my copies with KeePass (I should keep a backup).

If I reproduce, I will keep a copy to check what is the change.

**Comment by droidmonkey** [comment] 2022-03-14 19:08
Closing this, OP has not come back with more info and this is almost always a write failure.

**Closed as completed** 2022-03-14 19:07 UTC
Labels: more info needed

**Comment by nullx5** [comment] 2023-12-16 00:05
### Error reading database: Not a KeePass database.
```
Ubuntu 22.04.3 LTS
KeePassXC 2.6.6
```

I got this same error, my keePassxc database was working perfectly, but I wanted to open it and unfortunately I ran into this error, apparently the database was corrupted somehow, my only solution was that I had a backup copy. I have no idea how it could have been corrupted.

Doing a little research on the signatures [file header/signature](https://www.garykessler.net/library/file_sigs.html) [keepass.info](https://keepass.info/help/base/repair.html)

`file db.kdbx`

db.kdbx: Microsoft PowerPoint 2007+

`xxd db.kdbx`

504b 0304 0a00 0000 0000 874e e240 0000

---

`file backup-db.kdbx`

backup-db.kdbx: Keepass password database 2.x KDBX

`xxd backup-db.kdbx`

03d9 a29a 67fb 4bb5 0000 0400 0210 0000

KeePass has quite a few features to prevent database file corruption (transacted database writing, device buffer flushing, ...). However, data corruption can still be caused by other programs, system or broken storage devices.

KeePass, of course, can't do anything when data becomes corrupted.

If the database header (first bytes) is corrupt, `bad luck`: the repair functionality will not be able to restore it (because the header contains the information required to decrypt the database).

> The recommendation is to regularly make backup copies of your databases.

**Comment by prolifick1** [comment] 2024-06-10 04:53
I ran into this issue also, if you have the Drive app, the context menu has an option "Manage Versions". I was able to see a list of recent version files and restore the one saved earlier today. The most recent version of my db was mysteriously borked and I couldn't make it worke by copying it locally or resynching.
