### ISSUE TITLE
MacOS authentication store password in keychain

### ISSUE THREAD

**Issue by markster101** [keepassxreboot/keepassxc#4314] opened 2020-02-11 04:17 UTC
[TIP]:  # ( Provide a general summary of the feature in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Summary
Since MacOS can store application passwords in a keychain, it would be great the keepassXC application have this capability. This way a user does not need to enter the password every time to open the keepass database.

## Desired Behavior
The application could display a simple prompt asking a user to save the password to a keychain.
Once it is saved in macos keychain, Keepassxc can use it next time user opens the application.

## Possible Solution
[NOTE]: # ( Not required, but suggest ideas on how to implement the addition or change )

## Context
With many passwords we have to remember it saves the user time and effort to remember another password. We already have to know desktop user password and root/admin password to the keychain app. Having this feature would greatly improve security and offer the user to choose if they want to save the db password in the keychain.

**Comment by phoerious** [comment] 2020-02-11 06:54
Ideally, your database master password is much stronger than your desktop password (or at least its unlikely that your desktop password is as strong). I also don't know what KDF Apple uses for transforming your password. So this would definitely be convenience at the cost of security.

**Comment by varjolintu** [comment] 2020-02-11 17:01
AFAIK the Keychain Access is open by default (at least for me when I'm logged in). This would cause the database automatically to unlock for a normal user if the password has been saved in keychain.

Correct me if I'm wrong.

**Comment by markster101** [comment] 2020-02-11 17:22
That is exactly right. Many Mac apps use keychain, for example chrome or safari storing certificates and passwords.

**Comment by droidmonkey** [comment] 2020-02-11 17:36
The keychain is used currently to enable touchid quick login, albeit to a very limited extent.

**Comment by droidmonkey** [comment] 2020-03-30 13:28
Duplicate of #2619

**Closed by droidmonkey** 2020-03-30 13:28 UTC
Labels: new feature, platform: macOS
