### ISSUE TITLE
keepassxc 2.7.3. crashes on MacOS if a database is opened

### ISSUE THREAD

**Issue by bones78** [keepassxreboot/keepassxc#8663] opened 2022-10-26 04:21 UTC
After updating to 2.7.3 the database crashes if i open it (the programm ist directly closed). If I go back to 2.7.1 everything works fine.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. update zu 2.7.3
2. open database
3. progamm crashes

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
no crash

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.3
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS

**Comment by oetjen** [comment] 2022-10-26 05:13
Duplicate of #8639

**Comment by AlmightyBeaver** [comment] 2022-10-26 05:49
Workaround for now:
Disabling the Touch-ID setting in the Security Preferences.

**Closed as not planned** 2022-10-26 07:23 UTC
Labels: duplicate
