### ISSUE TITLE
AutoType: possibility to match parent windows of modal dialogue

### ISSUE THREAD

**Issue by schmittlauch** [keepassxreboot/keepassxc#1376] opened 2018-01-12 13:29 UTC
## Context

The problem I want to tackle is the one described in cloutierjo/titleUrl#1:

There's currently no possibility to change the "Basic Authentication" modal dialogue's window titles in Firefox due to extension restrictions. So it would be quite useful to be able to match the window titles of the dialogue's parent window instead/ as well.

This may also be relevant & useful for other applications as modal popups with very generic window titles are a common thing in many applications.

## Current Behavior
- it's not possible to differentiate between different website's *Authentication required* modal dialogues

## Possible Solution
- match the parent window's title too, either additionally or only that title

## Steps to Reproduce (for bugs)

1. Go to a website requiring HTTP basic auth with Firefox >= 57 + a KeePass helper/ title URL addon of your choice
2. Observe the website URL to only be part of the dialogue's body text but the window title being the same for all websites

## Debug Info

KeePassXC - Version 2.2.4
Revision: 4723f66

Libraries:
- Qt 5.10.0
- libgcrypt 1.8.2

Operating system: openSUSE Tumbleweed
CPU architecture: x86_64
Kernel: linux 4.14.12-1-default

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

**Comment by droidmonkey** [comment] 2019-07-10 02:40
Duplicate of #412

**Closed by droidmonkey** 2019-07-10 02:40 UTC
Labels: wishlist
