### ISSUE TITLE
Add an 'e-mail' field in entries' menu

### ISSUE THREAD

**Issue by WPFilmmaker** [keepassxreboot/keepassxc#1193] opened 2017-11-18 12:11 UTC
As per title I think that having an 'e-mail' menu space would be useful. Many times emails and username are different and while in the entry menu there is a field for username, there is not one for e-mail. I think it would be useful and if it is not too difficult to implement I would like to see it in Keepassxc. What do you think?

**Comment by TheZ3ro** [comment] 2017-11-18 12:32
You can add an additional field called "email" without any problem

**Comment by droidmonkey** [comment] 2017-11-18 12:50
I think he means as a first class entry field right below username. This would break compatibility with keepass.

**Comment by WPFilmmaker** [comment] 2017-11-18 17:23
@droidmonkey Thats what I meant. and since it would break compatibility with keepass I also can imagine why it hasn't/won't be implemented.

**Comment by droidmonkey** [comment] 2017-11-18 18:24
I actually had a great idea on how to implement this and also make showing arbitrary attributes on the first page.

**Comment by TheZ3ro** [comment] 2017-11-18 18:59
So it's a duplicate of #863

**Comment by WPFilmmaker** [comment] 2017-11-18 19:05
I just gave a look at #863 and it looks like a great idea! Hope to see it implemented :)

**Comment by droidmonkey** [comment] 2017-11-19 12:07
Yup! Marking as duplicate in favor of the other.

**Closed** 2017-11-19 12:07 UTC
