### ISSUE TITLE
Hang Crash when DeepL Desktop app is open.

### ISSUE THREAD

**Issue by SenpaiSharp** [keepassxreboot/keepassxc#10581] opened 2024-04-12 01:47 UTC
Having [DeepL desktop app](https://www.deepl.com/en/app/) for Windows open with a database open is causing KeepassXC to hang upon doing pretty much anything, such as clicking on an entry. This is true with the latest version of KeepassXC, 2.7.7 and at least as far back as 2.7.6., the first version I ever used. I'm using the Windows 64x version of KeepassXC on Windows 10.

**Comment by droidmonkey** [comment] 2024-04-12 02:19
Cannot replicate at all. DeepL doesn't appear to be an intrusive application, not sure how it would interfere or interact with other application at all. 

You can try adding KeePassXC to the block list:

![image](https://github.com/keepassxreboot/keepassxc/assets/2809491/47e92ef9-21c4-4259-8b5c-30b021d3128f)

**Comment by SenpaiSharp** [comment] 2024-04-12 05:23
I've had stranger conflicts in the past but usually they're reproducible for others.

Adding KeePassXC to the block list did no good. I don't believe it's a matter of DeepL's shortcuts because just the acts of mouse clicks causes the hang. It's not the end of the world but I would like to know if anyone manages to reproduce.

**Comment by droidmonkey** [comment] 2024-04-14 14:04
I am closing since this cannot be reproduced. If anyone else can reproduce please post here.

**Closed as completed by droidmonkey** 2024-04-14 14:04 UTC
Labels: not reproducible, platform: Windows

**Comment by byteboon** [comment] 2024-07-18 16:54
Having similar issues with DeepL and another application that I maintain. It appears DeepL makes use of UIAutomation to intrusively interact with other applications, and possibly not doing it correctly, which may also be the issue here.  Just some drive-by information while I look for my own solutions.

**Comment by AKAK2020** [comment] 2024-10-28 09:54
Unfortunately, the problem has not been solved. KeepassXC no longer responds when Deepl is started. The Keepass task goes to not responding. Unfortunately, an entry in the block list does not help. The entry in the json file does not solve the problem. Has anyone found a solution to this problem?

**Comment by bnitsche** [comment] 2024-10-28 22:47
Another similar issue ... since some weeks my mouse and other input devices did hang and only responded shortly after ~ 2 seconds in an infinite loop. This happened periodically. Sometimes directly after restarting the machine, sometime after several minutes .. and sometimes not .. except when I put the focus on the task manager .. 

After long investigation in hardware and software issues, I stopped Deepl and mouse input was back again .. AND .. as soon as I uninstalled DeepL desktop, there was no problems any more at all ... now reading the other messages, looks like deepl deeply integrates into the system .... to deep ... but it's called deepl .. so I do not wonder any more ;)
