### ISSUE TITLE
KeepassXC starts in German on English system

### ISSUE THREAD

**Issue by bllngr** [keepassxreboot/keepassxc#3030] opened 2019-04-18 11:54 UTC
## Expected Behavior
When the language is set to "System Default", KeepassXC uses the current user's system language.

## Current Behavior
~~Starting with 2.4.1,~~ German is used on my English system. Windows Display Language is set to English, Region is set to the US. The only German setting is the Regional Format, which is set to German (Germany). 

## Steps to Reproduce
1. Make sure KPXC's language is set to "System Default"
2. Change Windows' Display Language is to English, Region to the US.  Select "German (Germany)" for the Regional format.
3. ~~Start KPXC 4.2. Note that it starts in English.~~
4. Start KPXC 4.2.1. Note that it starts in German.

Note: I can also reproduce the behaviour with 2.4.0 and 2.3.4. Seems like something changed on my system at the same as updating to 2.4.1. But nevertheless, KPXC starts with an incorrect language.

## Debug Info
KeePassXC - Version 2.4.1
Revision: 7bafe65

Qt 5.12.2
Debugging mode is disabled.

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.17763

Enabled extensions:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.4

**Comment by droidmonkey** [comment] 2019-04-18 12:19
I would consider this a bug if you had ALL English settings. Either way this would be an issue with Qt, not us. We tell Qt to make the choice.

**Comment by bllngr** [comment] 2019-04-18 14:39
> I would consider this a bug if you had ALL English settings.

I disagree. The setting is called "Language" with the value "System default". So I'd expect the language to be the same as my system (and any other applications for that matter). Why would I want an application to use a different language then my system just because I'm using a different date format?

> Either way this would be an issue with Qt, not us. We tell Qt to make the choice.

That may be true, but it's an issue with your software nevertheless. Other Qt applications that are set to "system language" behave correctly (e.g. Qt Creator).

**Comment by droidmonkey** [comment] 2019-04-18 16:49
Ok looks like this is a known issue on windows, there is a different call to make that returns the UI language.

**Comment by phoerious** [comment] 2019-04-18 17:23
Duplicate of #1924.

**Comment by droidmonkey** [comment] 2019-04-18 17:31
That other one is closed

**Comment by phoerious** [comment] 2019-04-18 17:43
The reporter closed it himself. The issue itself wasn't fixed or decided bit to by us.

**Closed** 2019-05-07 17:00 UTC
Labels: duplicate
