### ISSUE TITLE
Ability to assign a database for browser integration

### ISSUE THREAD

**Issue by HanabishiRecca** [keepassxreboot/keepassxc#10550] opened 2024-04-05 12:14 UTC
## Summary

Currently browser integration simply uses a database which tab is selected in the UI window. And I don't see any way to assign one particular database to be used for browser intergation.

## Examples

Something like with the Secret Service Integration, where you can actually choose which database to expose.

## Context

Current behavior is inconvinient if you have multiple databases, as it requires you to switch back and forth.

**Comment by droidmonkey** [comment] 2024-04-05 13:11
Duplicate of #5238

**Closed as not planned by droidmonkey** 2024-04-05 13:11 UTC
Labels: duplicate, feature: Browser
