### ISSUE TITLE
Yubikey fails to be detected on Ubuntu 16.04

### ISSUE THREAD

**Issue by rwky** [keepassxreboot/keepassxc#883] opened 2017-08-19 13:39 UTC
## Expected Behavior

When creating a new database and ticking "Challenge Response" yubi keys should be detected.

## Current Behavior

No yubi key is detected (I've tried a Neo and 4)

## Steps to Reproduce (for bugs)
1. Install keepassxc 2.2.0 on Ubuntu 16.04 64 bit
2. Go to create a new database
3. Tick challenge response
4. Insert yubi key and click refresh

## Context

This works fine on OS X so I know it's not the keys, I've tried two different keys using both the AppImage and Snap package.

## Debug Info
KeePassXC - Version 2.2.0
Libraries:
- Qt 5.9.0
- libgcrypt 1.6.1

Operating system: Ubuntu 16.04.3 LTS
CPU architecture: x86_64
Kernel: linux 4.4.0-92-generic

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

**Comment by phoerious** [comment] 2017-08-19 13:48
Duplicate of #693

**Closed by phoerious** 2017-08-19 13:48 UTC
