### ISSUE TITLE
[Feature Request] Hide in the dock under mac os

### ISSUE THREAD

**Issue by MZLAKg2aGGFs8yi** [keepassxreboot/keepassxc#2154] opened 2018-07-26 03:16 UTC
Currently the program is still in the dock after it is hidden, which is a waste because it can be accessed  from the small icon in the system tray. An option to hide it from the Mac dock would be useful.

**Comment by droidmonkey** [comment] 2018-07-26 16:32
This is too vague. Please add more information or it will be closed.

**Comment by phoerious** [comment] 2018-07-29 13:49
I think the problem mentioned here is that there is no Mac-style "hidden window" mode where the program is running in the background without an icon in the dock. This is a duplicate of #1334

**Closed by phoerious** 2018-07-29 13:49 UTC
Labels: more info needed, platform: macOS, user interface
