### ISSUE TITLE
[feature request] Allow type selection for autotype with multiple entries

### ISSUE THREAD

**Issue by rieje** [keepassxreboot/keepassxc#853] opened 2017-08-07 15:39 UTC
A feature request--allow type selection for autotype with multiple entries. Currently, there seems to something similar--when you type, keepassxc begins matching what you type to "Group" (the first column in the list of entries). Instead, it would make more sense to match what you type to "Username," which is more intuitive and practical.

EDIT: Actually, I'm not sure how the type selection works at all.

**Comment by TheZ3ro** [comment] 2017-08-12 08:38
Can you provide more information about this? Thanks

**Comment by rieje** [comment] 2017-08-18 14:07
@TheZ3ro For example, go to www.github.com and in the username field, trigger Auto-Type. A KeepassXC popup window will show up containing all my github accounts which I currently select with up/down arrow keys*. Instead of using arrow keys, it would be nicer to begin typing the username and KeepassXC incrementally searches for that username, selecting the first match closest to what you've typed so far. So I would trigger Auto-Type, type in `rie`, and the entry with `rieje` would be selected, then I just hit enter to confirm the selection. 

What needs to be done currently is to use the down up/down arrow key to navigate the desired entry--this is problematic for the following reason:

Imagine a long list of entries--you need to spam up/down arrow key or use your mouse to select the appropriate entry (neither are ideal especially when your workflow is vim-like where you generally want to keep your fingers in home row) and entirely keyboard driven. Even for a short list this is an issue, although I found you could cycle through the list via `r` hotkey (which doesn't really solve the issue).
--------------------------------------------------------------------
* As a side note, even if there's only one entry, this popup window still shows up requiring you to select it--I feel this should be an option and the default is to automatically select it if it's the only entry such that triggering Auto-Type will automatically autotype the one and only entry. It's kind of redundant to make the user select the entry if it's the only one available.

**Comment by emkae** [comment] 2017-08-24 07:36
> ** As a side note, even if there's only one entry, this popup window still shows up requiring you to select it--I feel this should be an option and the default is to automatically select it if it's the only entry such that triggering Auto-Type will automatically autotype the one and only entry. It's kind of redundant to make the user select the entry if it's the only one available.

This is so annoying to me :+1:

**Comment by phoerious** [comment] 2017-08-24 07:43
I don't really understand what you mean. Auto-Type by user name doesn't make sense. My username is the same for most websites and also not part of the window title. KeepassXC matches entries based on their title which needs to be a substring of the browser window title (or a custom substring you define).

Showing of the selection window for only a single entry is a precaution and you can turn it off already.

**Comment by emkae** [comment] 2017-08-24 11:29
Auto Type is clearly not working when there is only one search result and I haven't selected the search result explicitly (via tab or mouse-click). CTRL+C or CTRL+B works though.

You can see it here: https://youtu.be/fBq3DDjUSXI

**Comment by phoerious** [comment] 2017-08-24 11:54
Well, that's because you are still focusing the search field. Ctrl+V is expected to paste your clipboard contents to the search field in that case.
You can always configure a global Auto-Type shortcut, though. That way you don't have to search and select entries manually.

**Comment by emkae** [comment] 2017-08-24 12:13
> Ctrl+V is expected to paste your clipboard contents to the search field in that case.
That makes sense. I did not paste anything in the search field once and I cannot imagine pasting anything there in the future (it's not like it's Google), so it occured to me that this might be a bug. Thanks for the clarification :+1:

**Comment by droidmonkey** [comment] 2017-08-24 16:23
I think he's asking for a search feature within the auto type selection dialog.

**Comment by phoerious** [comment] 2017-08-24 16:35
That feature has been discussed elsewhere.

**Comment by rieje** [comment] 2017-08-24 21:47
Could you link the duplicate issue? I haven't found what I'm suggesting, although there are many suggestions to improve dealing with multiple entries.

Also, maybe there's a misunderstanding but I definitely feel it does make sense to allow navigating to an entry by typing incrementally. When I Auto-Type for a website I have multiple accounts for (typically anonymous accounts), I want to be able to type the first few characters of the username and have the entry I'm typing for incrementally match and auto-select it. This beats having to visually parse the list to find the account you're looking for and then navigating the list via arrow keys or using the mouse to select it. Incremental searching is more natural because you accomplish the task by doing the same thing every time--type the first few characters of what username you want and hit Enter. The way it is now requires more user attention (find the entry you're interested in, navigate to it, and select it). 

I'm a keyboard-driven user and what I'm suggesting would make KeepassXC way more fluid. I don't see any downsides.

**Comment by TheZ3ro** [comment] 2017-08-28 10:26
So this is a duplicate of #429 (and #788)

**Closed** 2017-08-28 10:26 UTC
Labels: duplicate
