### ISSUE TITLE
2.7.9 does not load database from CLI anymore - Linux

### ISSUE THREAD

**Issue by djlalle** [keepassxreboot/keepassxc#10955] opened 2024-06-22 18:17 UTC
## Overview
new version does not load anymore the database from linux CLI

## Steps to Reproduce
keepassxc --keyfile /home/.../keyfile /home/.../database.kdbx
the same behavior if I use a password instead of the keyfile

## Expected Behavior
downgraded to keepassxc-2.7.8-3
working fine, it opens the database from CLI

## Actual Behavior
just start, without opening the database

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.9
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Sway
Windowing System: Wayland

**Comment by droidmonkey** [comment] 2024-06-22 18:37
We didn't touch that code. Can you describe how you have keepassxc installed and what happens when you issue the command?

**Comment by djlalle** [comment] 2024-06-22 18:44
thanks a lot for your answer :)
Arch linux, I had installed keepassxc with pacman
and upgraded
I start keepassxc from the Swaywm config file
but I had to downgrade, since 2.7.9 start with no database

**Comment by djlalle** [comment] 2024-06-23 16:27
I can confirm that keepassxc **2.7.9-1** using this command from the terminal:
**keepassxc --keyfile /home/.../keyfile /home/.../database.kdbx**
start wit no database
keepassxc-**2.7.8-3** with the same exact command, instead starts with the database requested

**Comment by droidmonkey** [comment] 2024-06-23 16:47
What Linux distro are you using? Arch? Mint?

**Comment by djlalle** [comment] 2024-06-23 21:44
Arch

**Comment by TomKTW** [comment] 2024-06-25 07:54
I'm suspecting that I'm getting a same issue here on KeePassXC 2.7.9 when launching the app from KDE Plasma (Wayland) launcher on Arch with one of my recently opened databases.

It should look like this (with note that others have empty list):
![image](https://github.com/keepassxreboot/keepassxc/assets/11387678/a207e438-1a0f-4e25-bc1b-058bbb86ffa3)

This issue has occured recently after updating the package for KeePassXC that seems to be updated on Arch repository to 2.7.9-1 about 5 days ago (previous release seems to be 2.7.8-3).

It seems that KeePassXC does actually open the database properly. However, the side bar and bottom info bar are gone and root folder is the default folder that's opened when the database is open. I'm assuming this is the actual issue that was reported.

I've tried to make a screencast to replicate this issue on its initial state:
[Screencast_20240625_090855.webm](https://github.com/keepassxreboot/keepassxc/assets/11387678/c143b066-40da-42a3-8594-53427b8f0f61)

On initial start, when you open the database, everything is collapsed and root folder is open. I'm assuming that everyone in here has nothing in their root folder and instead, they're using sub folders. This way, their database is acutally loaded,  but they are in an empty  folder and they can't navigate around.

A workaround for this is simply going to left or bottom side of window and try to resize those bars bar back, which I've done in the screencast for the sidebar, and that state remained even after restarting the application.

Another workaround is to close the database again (without closing the application) and re-open it. This will temporarily restore the layout until the application is closed and reopened again, which will cause it to go back to "broken" state again.

After resizing both bars, it should go back to original state, as shown here:
![image](https://github.com/keepassxreboot/keepassxc/assets/11387678/ba95d8c8-b4e1-45bd-871d-5a544392ad73) 

If this is valid even for others, I'm assuming that KeePassXC 2.7.9 has somehow broken state of default folder, side bar and bottom bar on initial start where the first database is opened.

**Comment by droidmonkey** [comment] 2024-06-25 10:05
Related change: https://github.com/keepassxreboot/keepassxc/pull/10641

**Comment by mlavi** [comment] 2024-07-07 21:18
@TomKTW described my situation exactly and workaround, using KeePassXC 2.7.9 AppImage on Linux Mint 21.3. I start KeePassXC with keepass-cli to open a database, which starts window minimized per configuration. Thanks, looking forward to a patch.

**Comment by droidmonkey** [comment] 2024-07-07 22:34
This is a duplicate of #11013

**Closed as completed by droidmonkey** 2024-07-07 22:34 UTC
Labels: duplicate, more info needed, platform: Linux
