### ISSUE TITLE
Issue with memory, can't keep keeypassxc open.

### ISSUE THREAD

**Issue by jhk217626** [keepassxreboot/keepassxc#1808] opened 2018-04-01 18:37 UTC
## Expected Behavior
KeepassXC should lock itself and wait again to be unlocked.

## Current Behavior
Get this error message "The instruction at 0x0000000066767002 referenced memory at 0x000000000000000000C. The memory could not be written. Click on OK to terminate the program."

## Steps to Reproduce (for bugs)

1. Unlock KeepassXC
2. Wait for it to lock up
3. Experience the error when it tries to lock
4.

## Context
I've replicated this on 2 separate computers. Downgrading the version seems to help.

## Debug Info
KeePassXC - Version 2.3.1
Revision: 2fcaeea

Libraries:
- Qt 5.10.1
- libgcrypt 1.8.2

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.16299

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by thomasaiman** [comment] 2018-04-04 16:42
I'm getting the same error. 

Windows 10, x86_64, v10.0.16299. 

This is with only auto-type enabled (no browser integration, no ssh agent, no yubikey).
The title of the error box is "Auto-Type - KeePassXC: Windows - Application Error".

**Comment by phoerious** [comment] 2018-04-04 16:44
Duplicate of #1561

**Closed by phoerious** 2018-04-04 16:44 UTC
Labels: bug, platform: Windows
