### ISSUE TITLE
Some icons are deleted after saving and reopening

### ISSUE THREAD

**Issue by wj94k8wdv3** [keepassxreboot/keepassxc#4805] opened 2020-06-01 14:47 UTC
## Overview
Some icons are deleted after saving and reopening

![Снимок экрана 2020-06-01 в 17 35 41](https://user-images.githubusercontent.com/48610613/83419871-795fe500-a42e-11ea-8740-5902ca077c66.png)

After opening:

![Снимок экрана 2020-06-01 в 17 34 57](https://user-images.githubusercontent.com/48610613/83419896-8250b680-a42e-11ea-80d6-62bfbcde3f5d.png)

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1.  I Download icon related to the record
2. I close the application the database is saved to the cloud iCloud (option "Secure save" - Disabled)
3. I launch the application and open the database (The icons that were previously added disappeared, but this is not on all entries, but only on some)

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.5.4
Revision: dcca5aa

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS Catalina 10.15.5 (19F96)

**Comment by hifi** [comment] 2020-06-01 15:08
Does this happen only with certain downloaded icons and is it 100% reproducible or is it random?

If it's related to an icon you downloaded and it is never saved, could you provide a direct link to the failing icon?

**Comment by wj94k8wdv3** [comment] 2020-06-01 15:27
> Does this happen only with certain downloaded icons and is it 100% reproducible or is it random?
> 
> If it's related to an icon you downloaded and it is never saved, could you provide a direct link to the failing icon?

This is not an accidental event, it happens with the same record, and I noticed that this applies only to some records that operate over the https protocol. In normal mode, the icons for these entries are not loaded, they can only be loaded when duckduckgo mode is turned on, but after they are downloaded and re-entered into the database, they disappear, here is the list of resources with problems: https://www.emipm.com https : //codekitapp.com https://www.shiftbright.com https://rucaptcha.com https://sketch.cloud

Р.S. Sorry for my bad English

**Comment by phoerious** [comment] 2020-06-01 16:40
Duplicate of #4341.

**Closed by phoerious** 2020-06-01 16:40 UTC
Labels: bug
