### ISSUE TITLE
Compilation failed.

### ISSUE THREAD

**Issue by Achaean** [keepassxreboot/keepassxc#3676] opened 2019-10-27 00:54 UTC
Hi! :-)

I'm on a Debian oldstable based distro, where I have successfully compiled the previous stable release (2.4.3), so I tried to compile the latest one (2.5), but I failed!
I received the message "error: ‘YubiKey’ has not been declared", although I don't need it and I disabled support for it.

Anyway! I'm attaching the cmake and make logs.
[LOGS.zip](https://github.com/keepassxreboot/keepassxc/files/3775422/LOGS.zip)

**Comment by droidmonkey** [comment] 2019-10-27 03:55
Can you please just post the failure portion?

**Comment by phoerious** [comment] 2019-10-27 11:25
Duplicate of #3684

**Closed by phoerious** 2019-10-27 11:25 UTC
Labels: bug

**Comment by Achaean** [comment] 2019-10-27 13:06
Just for the record, at my own compilation YUBIKEY=OFF.
-- Disabled features:
.
.
.
* YubiKey
