### ISSUE TITLE
Crash after start (after macOS update)

### ISSUE THREAD

**Issue by msc1978** [keepassxreboot/keepassxc#4480] opened 2020-03-25 09:33 UTC
Hi i just upgraded macOS to Catalina 10.15.4 (with 10.15.3 it still works/worked)

now at the start of keepassXC i get:
System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (Code Signature Invalid)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace CODESIGNING, Code 0x1

tried binary and homebrew installs, but the issues remain the same for all
any suggestion to fix this?

**Comment by InabaByakko** [comment] 2020-03-25 09:44
I also encountered a same issue on macOS Mojave 10.14.6 after installed security update 2020-002 10.14.6 (https://support.apple.com/kb/HT201222) .

Crash report log is on below.

```
Process:               KeePassXC [453]
Path:                  /Applications/KeePassXC.app/Contents/MacOS/KeePassXC
Identifier:            org.keepassx.keepassxc
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           KeePassXC [453]
User ID:               501

Date/Time:             2020-03-25 18:25:41.432 +0900
OS Version:            Mac OS X 10.14.6 (18G4032)
Report Version:        12
Bridge OS Version:     4.4 (17P4263)
Anonymous UUID:        0D172B12-63D2-D31E-358D-4784CC2AED28


Time Awake Since Boot: 69 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (Code Signature Invalid)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace CODESIGNING, Code 0x1

kernel messages:

VM Regions Near 0 (cr2):
--> 
    __TEXT                 000000010aaab000-000000010ae3d000 [ 3656K] r-x/r-x SM=COW  

Thread 0 Crashed:
0                                 	0x0000000113acb000 _dyld_start + 0

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x0000000000000000  rcx: 0x0000000000000000  rdx: 0x0000000000000000
  rdi: 0x0000000000000000  rsi: 0x0000000000000000  rbp: 0x0000000000000000  rsp: 0x00007ffee5154bb8
   r8: 0x0000000000000000   r9: 0x0000000000000000  r10: 0x0000000000000000  r11: 0x0000000000000000
  r12: 0x0000000000000000  r13: 0x0000000000000000  r14: 0x0000000000000000  r15: 0x0000000000000000
  rip: 0x0000000113acb000  rfl: 0x0000000000000200  cr2: 0x0000000000000000
  
Logical CPU:     0
Error Code:      0x00000000
Trap Number:     0


Binary Images:
       0x10aaab000 -        0x10ae3cfff + (0) <16AE8CED-0E4C-3291-AE43-913B0D7192FF> 
       0x113aca000 -        0x113b3470f + (655.1.1) <C192CA31-D059-3770-9882-D864FEFA0C96> 

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 146
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=4552K resident=0K(0%) swapped_out_or_unallocated=4552K(100%)
Writable regions: Total=8404K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=8404K(100%)
 
                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
STACK GUARD                       56.0M        1 
Stack                             8192K        1 
__DATA                             372K        4 
__LINKEDIT                         468K        2 
__TEXT                            4084K        2 
shared memory                        8K        2 
===========                     =======  ======= 
TOTAL                             68.8M       12 

Model: MacBookPro15,2, BootROM 1037.100.359.0.0 (iBridge: 17.16.14263.0.0,0), 4 processors, Intel Core i7, 2.8 GHz, 16 GB, SMC 
Graphics: kHW_IntelIrisGraphics655Item, Intel Iris Plus Graphics 655, spdisplays_builtin
Memory Module: BANK 0/ChannelA-DIMM0, 8 GB, LPDDR3, 2133 MHz, SK Hynix, -
Memory Module: BANK 2/ChannelB-DIMM0, 8 GB, LPDDR3, 2133 MHz, SK Hynix, -
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x7BF), wl0: Oct 23 2019 08:32:36 version 9.137.11.0.32.6.36 FWID 01-671ec60c
Bluetooth: Version 6.0.14d6, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB 3.1 Bus
USB Device: iBridge Bus
USB Device: Touch Bar Backlight
USB Device: Touch Bar Display
USB Device: Apple Internal Keyboard / Trackpad
USB Device: Headset
USB Device: Ambient Light Sensor
USB Device: FaceTime HD Camera (Built-in)
USB Device: Apple T2 Controller
Thunderbolt Bus: MacBook Pro, Apple Inc., 41.2
Thunderbolt Bus: MacBook Pro, Apple Inc., 41.2
```

**Comment by phoerious** [comment] 2020-03-25 09:49
Duplicate of #4398.

**Closed by phoerious** 2020-03-25 09:49 UTC
