### ISSUE TITLE
Global application shortcut

### ISSUE THREAD

**Issue by schiorean** [keepassxreboot/keepassxc#423] opened 2017-03-22 12:12 UTC
Hello,

What would be nice to have is a global app shortcut that simply opens the application main window. Very nice to have if one is working a lot with the application instead of opening it from sys tray using mouse.

P.S. Apologizing if feature requests should be added somewhere else.

**Comment by TheZ3ro** [comment] 2017-03-22 16:05
This is a duplicate of #99

**Closed** 2017-03-22 16:06 UTC
Labels: duplicate
