### ISSUE TITLE
macOS - option to hide dock icon

### ISSUE THREAD

**Issue by woj-tek** [keepassxreboot/keepassxc#1334] opened 2017-12-28 16:44 UTC
Currently it's possible to show tray icon (the one next to clock) but dock icon still remains. It would be great to be able to hide dock icon and let KeePassXC run "in the background" (only with tray icon)

## Expected Behavior
Select "Show system tray icon", add another option "Hide dock icon" to the group of this options

## Current Behavior
We have two icons now if we enabled mentioned option. The dock icon could be shown when the window is visible though.

## Context

This could limit the clutter in the dock. Long running application are better situated in the tray instead of dock/taskbar.

## Debug Info
KeePassXC - Version 2.2.4
Revision: 4723f66

Libraries:
- Qt 5.9.1
- libgcrypt 1.8.1

Operating system: macOS High Sierra (10.13)
CPU architecture: x86_64
Kernel: darwin 17.3.0

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

**Comment by woj-tek** [comment] 2017-12-30 18:57
I'm not sure about `macOS` - in windows you can have similar behaviour - only show application in tray without taskbar item. I'm fairly sure that in Linux this works in similar fashion.

**Comment by bannmann** [comment] 2018-01-20 11:58
One example of a widely-used app that does this is Google Drive.

**Comment by woj-tek** [comment] 2018-01-23 14:03
Quite a lot of apps do this - yet another example would be DrobBox.

**Comment by beck** [comment] 2018-05-11 21:54
This ticket is especially important for keeping browser integration without adding noise to alt-tab.

**Comment by MZLAKg2aGGFs8yi** [comment] 2018-07-29 17:40
Another Example is Onedrive. This is important for someone who want to keep their dock clean, like me.

**Comment by GM-Alex** [comment] 2018-08-29 22:02
@phoerious Why was this issue closed? Is this feature available?

**Comment by droidmonkey** [comment] 2018-08-30 12:41
First off, the examples given are NOT applications, they are services. The little popup you see when you click the icon is just a modal window, not an app window. That is why its not visible in the task bar.

Second, you can minimize KeePassXC to tray and keep it there while still using AutoType and Browser integration. I do not think it is even possible to hide from the taskbar from our application.

**Comment by woj-tek** [comment] 2018-08-30 16:30
First of - if you use KeePassXC mostly (only) as a service to keep passwords for browsers then... it's a service (I kinda stopped using KeePassXC because was annoyed by the dock icon and quite frequent, unintentional switching to it when changing apps)

Secondly - you may be able to minimize to try under different OSs, but as you stated - you are not a macOS user and the whole point of this ticket is that - it's not possible to minimise app to try currently (there is a workaround with PlistInfo modification, but it's very brittle and doesn't work well).

I tried tinkering with it myself, but unfortunately it went over my head.

**Comment by droidmonkey** [comment] 2018-08-30 17:27
Would this work for you: http://ghosttile.kernelpanic.im

This code snippet might help implement the desired behavior. When the app is supposed to be minimized to tray (like in windows), we should hide the dock icon.

https://gist.github.com/TomLiu/7837127

**Comment by phoerious** [comment] 2018-08-30 17:37
We should implement normal macOS behaviour which is to only close the window, but keep the app running when the window close button is pressed. We kind of have that already, but it requires explicit configuration.

**Comment by woj-tek** [comment] 2018-08-30 18:35
@droidmonkey - I'll try those patches

@phoerious - currently close window button closes the window (and it works correctly) - macOS has little bit different notion of application/windows: you can have running application without any window (not minimised - window widget/document completely destroyed), AFAIR it contradicts windows/linux where if you run the app you have the document and (in majority of the times) if you close last document you close the application altogether.

**Comment by phoerious** [comment] 2018-08-30 18:47
You can enable the tray icon and then the option to hide the window instead of closing everything.

**Comment by praveendhawan** [comment] 2019-02-11 05:19
Are there any updates on this?

**Comment by droidmonkey** [comment] 2019-02-11 12:11
Not this in particular, but we did fix interaction with the app during browser extension use. The window will properly re-hide itself and stay out of alt+tab.

**Comment by woj-tek** [comment] 2019-02-11 15:12
@praveendhawan I played a bit with it without much luck (lack of c/qt experience I guess).

@droidmonkey I appreciate all the work to improve compatibility with macos, unfortunately this is unrelated to this particular issue :-)

**Comment by peacetype** [comment] 2019-02-16 01:12
I'm interested in the inverse of this behavior... I'd like to see the system tray icon gone but the dock icon remain. Do you think others might be interested in this as a separate feature request?

**Comment by droidmonkey** [comment] 2019-02-16 01:45
You can just disable the tray icon in settings.

**Comment by peacetype** [comment] 2019-02-16 03:18
@droidmonkey Unfortunately, disabling that option also disables the 3 sub-options that are dependant on it. 

I like how you can close the KeePassXC window to hide it and the app keeps running and can be made visible again by clicking the dock icon. I just wish that feature did not require adding another icon to my already-cluttered system tray. I know other apps like iTunes and Photoshop have this behavior without adding an icon to the system tray.

**Comment by droidmonkey** [comment] 2019-02-16 04:32
I'll play around with this on our test Mac to see if there is an easy solution. Those three sub options are mainly for windows and Linux envs.

**Comment by peacetype** [comment] 2019-02-16 04:53
@droidmonkey Sweet! If I knew more about C++ and Mac development I might even try messing with it myself but its way over my head. I'm just getting started with self-teaching programming and learning iOS development.

This app is amazing btw. I've missed Keepass ever since I switched over from Windows. Never could find a good Mac version. This cross-platform approach is terrific!

**Comment by TCB13** [comment] 2019-03-10 18:21
+1 on this feature!

**Comment by TCB13** [comment] 2019-03-10 18:29
I was reading the comments above and usually in macOS to hide a running App from the Dock you need to add the following to `Info.plist`:
`````
<key>LSUIElement</key>
<string>1</string>
`````
Can't it be done programmatically in Qt?

**Comment by woj-tek** [comment] 2019-03-12 22:45
@TCB13 - I played with it a bit and while it hides icon from the dock it messes up the interaction with KeePass - in the end I had to force-close it because I wasn't able to restore the window. Maybe recent changes to improve compatibility would help with the situation.

However, adding it to `Info.plist` would make it non-optional, which may be a problem for some.

**Comment by TCB13** [comment] 2019-03-12 22:46
@woj-tek you just need to add it to the menu on top, and you can always get it back.

**Comment by TCB13** [comment] 2019-03-12 22:48
![image](https://user-images.githubusercontent.com/6315832/54241453-e1b86300-4518-11e9-88e5-8d6914046b5f.png)

Works just fine for me.

**Comment by woj-tek** [comment] 2019-03-12 22:48
Have you tried it? Because as I said - I was playing with it a bit and while at the beginning it was working ok I had to revert it because it broke later on...

**Comment by TCB13** [comment] 2019-03-12 22:48
@woj-tek I've been using it for a week or so, no trouble at all. :)

**Comment by TCB13** [comment] 2019-03-12 22:50
@woj-tek have a look at my current settings:

![image](https://user-images.githubusercontent.com/6315832/54241547-30fe9380-4519-11e9-98a4-7217681ea243.png)

**Comment by TCB13** [comment] 2019-03-12 22:53
> However, adding it to `Info.plist` would make it non-optional, which may be a problem for some.

I wasn't asking for it to be permanent. We could have a default like:
`````
<key>LSUIElement</key>
<string>0</string>
`````
Then, if user turn on "hide window to system tray when minimized" it could change it to:
`````
<key>LSUIElement</key>
<string>1</string>
`````
This way it would be optional and consistent with the current Windows experience.

**Comment by woj-tek** [comment] 2019-03-12 22:56
OK, I know what was my issue - I also store some passwords for other applications that don't provide interaction with KeePassXC and with `LSUIElement` the application in "shown state" doesn't show up in alt-tab so if you want to get some secret to other app ypu have to toggle KeePassXC, copy it and then if you want to go back to KeePassXC you have to click twice on toggle in the menu.

**Comment by TCB13** [comment] 2019-03-12 22:59
@woj-tek interesting, I don't have that use case indeed. Anyway, what do you think about toggling `LSUIElement` on `Hide window to system tray when minimized`?

**Comment by woj-tek** [comment] 2019-03-12 23:09
I'm not sure that this option should be toggled altogether. IMHO there should be a better way to handle it via Qt.

**Comment by TCB13** [comment] 2019-03-12 23:14
Hmm... but toggling `LSUIElement` is something native to the Apple platform that works reliably and is used by many apps. A Qt solution would fall more into a slight hack.

Some examples:
- Dropbox:
![image](https://user-images.githubusercontent.com/6315832/54242390-4e812c80-451c-11e9-9bbf-e32b68c4e601.png)

- Viscosity VPN:
![image](https://user-images.githubusercontent.com/6315832/54242407-648eed00-451c-11e9-9cbf-bf1593de8786.png)

- Dropzone 3:
![image](https://user-images.githubusercontent.com/6315832/54242463-999b3f80-451c-11e9-9951-dd9782c59a3e.png)

Anyway, thank you for you feedback. Keep up the great work!

**Comment by woj-tek** [comment] 2019-03-13 00:38
In that case that may be a viable option - hopefully developers would consider it :-)

**Comment by xvrxq52Dm6Pu** [comment] 2019-03-13 00:41
LSUIElement also remove it from command+tab selection. A perfect behavior should be like onedrive. You can open Onedrive settings and still see it in command+tab, while it is indeed minimized to system tray.

**Comment by TCB13** [comment] 2019-03-13 09:27
@xvrxq52Dm6Pu and... that kind of “perfect behaviors” is exactly why Microsoft for Mac all full of UI glitches, crashes and others problems - instead of going with native solutions for common problems (that work reliable and in an expected way) they hack stuff around.

**Comment by marothe** [comment] 2019-05-29 12:52
I tried the workaround - and it worked: there is no dock-symbol but only a tray icon. But, now I cannot use auto-type any longer, only if I delete the two lines of code from the Info.plist.
Is there really no real workaround? And why are the developers not implementing this easy feature?

**Comment by konrad-a** [comment] 2019-06-19 16:19
I have the same usability issue - is there a way to hide the dock icon and have the auto-type working?

**Comment by TCB13** [comment] 2019-06-19 16:39
@marothe @konrad-a I don't use auto-type so I can't comment on it.

**Comment by marothe** [comment] 2019-06-19 16:44
@konrad-a I got used to the symbol in the dock...hope I can get rid of it in the future.

**Comment by janprzy** [comment] 2020-02-02 11:06
> What I've tried is toggling the `LSUIElement` from Terminal (essentially the same operation with altering `Info.plist` manually), and then re-signing the application to avoid crashing on startup:
> 
> ```
> defaults write /Applications/KeePassXC.app/Contents/Info LSUIElement 1
> sudo codesign -f -s - /Applications/KeePassXC.app
> ```
> 
> Works for me for the time being.

I can confirm that this works for me too. Maybe making it the default should be considered.

I see no point in having a dock icon when accessing passwords through a browser extension. Especially when the menu bar icon is enabled, the dock icon just provides pointless redundancy. Maybe only hide it when the menu bar icon is enabled?

**Comment by konrad-a** [comment] 2020-05-26 11:12
I reinstalled by MacOs and ended up googling this issue again.
Yes, the workaround works, but could it be included in one of future releases?
`defaults write /Applications/KeePassXC.app/Contents/Info LSUIElement 1
sudo codesign -f -s - /Applications/KeePassXC.app`

**Comment by droidmonkey** [comment] 2020-05-26 15:55
@phoerious is this something we can add to 2.6?

**Comment by phoerious** [comment] 2020-05-26 17:28
I thought that's already possible when the tray is enabled?

**Comment by phoerious** [comment] 2020-05-26 18:12
I stand corrected. The dock icon is still showing, even when pressing the close button. Lemme see if I can fix that.

**Comment by phoerious** [comment] 2020-05-26 20:00
Changing the plist file is not something you want or can do at runtime, especially not with a signed app. There are other system APIs to achieve the same effect. I proposed a fix, which should resolve this issue and overall improve the tray icon experience.

**Closed** 2020-05-27 08:55 UTC
Labels: new feature, platform: macOS
