### ISSUE TITLE
Suggested Feature : Auto start with system boot

### ISSUE THREAD

**Issue by Y0Mamma** [keepassxreboot/keepassxc#2084] opened 2018-07-01 22:17 UTC
It would be nice if I could have Keepassxc start minimized to the system tray when I turn my computer on.

Operating system: Linux Mint 19
CPU architecture: 64 bit
Kernel: 4.15.0-23

**Comment by droidmonkey** [comment] 2018-07-02 00:41
Duplicate of #1218

**Closed by droidmonkey** 2018-07-02 00:41 UTC
