### ISSUE TITLE
KeepassXC can't open DB on 1/3 of my macbooks

### ISSUE THREAD

**Issue by julian-saunders** [keepassxreboot/keepassxc#8412] opened 2022-08-26 10:32 UTC
## Overview
I am using KeepassXC on multiple macbook pros, but for some reason I am unable to open the same DB on 1/3 of them.
I'm also accessing the same DB from Keepass2Android.

## Steps to Reproduce

Macbook pro 2017 at version 12.4 - Access DB fine with KeepassXC
Macbook pro 2017 at version 12.5.1 - Can't open DB with KeepassXC, but the DB can be opened with StrongBox
Macbook pro 2021 at version 12.5.1 - Access DB fine with KeepassXC

The DB was being accessed over DropBox, but I also tried accessing the DB locally.  Still the same issue.

I created a new DB on the troublesome macbook, and I'm unable to open this DB across the other macbooks and receive the same error.

I receive the following error message: 

"Error while reading the database: Invalid credentials were provided. Please try again.
If the error reoccurs, your database file may be corrupt. (HMAC mismatch)"

[NOTE]: 
KeePassXC - 2.7.1
Revision: 5916a8f

**Comment by droidmonkey** [comment] 2022-08-26 13:19
Your one MacBook that cannot open or save a proper database may have faulty RAM.

**Comment by julian-saunders** [comment] 2022-08-26 14:27
> Your one MacBook that cannot open or save a proper database may have faulty RAM.

I have run Apple Diagnostics, and it passed without issue.

I would expect to see other applications, including the OS, with issues if there was a memory problem.

It can open and close a DB that it created, but not a DB that was created on my other devices.

**Comment by phoerious** [comment] 2022-08-29 12:21
Make sure you don't accidentally load a key file if you don't have one. Your problem sounds a lot like that.

**Comment by Lanzhou-J** [comment] 2022-09-11 12:57
I received the same error message and later discovered that I used the wrong password. 
Hope it helps.

**Comment by droidmonkey** [comment] 2022-09-11 13:01
Since this is not possible to reproduce and it is quite possible user error or something out of our control... going to close this one.

**Closed as completed by droidmonkey** 2022-09-11 13:01 UTC
Labels: more info needed, platform: macOS

**Comment by julian-saunders** [comment] 2022-09-16 07:40
> Since this is not possible to reproduce and it is quite possible user error or something out of our control... going to close this one.

Understood.  
 
I still have the same issue with just one macbook, and interestingly I'm able to use another password manager such as StrongBox, on the macbook in which KeePassXC can't open the db, on the same db file and I can open it successfully. Therefore it seems to be a problem with KeePassXC on said macbook. 

I have removed KeePassXC, and installed again, but this doesn't fix the issue. Perhaps there is a way to fully remove it?

**Comment by droidmonkey** [comment] 2022-09-16 10:36
The only rements of the program left after removing it would be the configuration ini files which would not impact database decryption, but you never know.... they are located in the application support hidden folders in your user profile.
