### ISSUE TITLE
Make password policy local to an entry

### ISSUE THREAD

**Issue by ceving** [keepassxreboot/keepassxc#5178] opened 2020-07-27 06:51 UTC
## Summary
Most services have different password policies. It would be nice to be able to store the password policy in an entry. By this it would be possible to create directly a sufficient password during a password change.

## Examples
This parameters of the password policy should not be global but local to the entry.
![2020-07-27 08_47_29-KeePassXC](https://user-images.githubusercontent.com/795748/88511955-0b770a80-cfe6-11ea-89b0-549b5b0de6c6.png)

## Context
Whenever I do a password change, I have to enter the new password policy.

**Comment by droidmonkey** [comment] 2020-07-27 14:19
Duplicate of #2628

**Closed** 2020-07-27 14:19 UTC
Labels: new feature
