### ISSUE TITLE
Add Cut/Copy/Paste to transfer entries from one DB to the other

### ISSUE THREAD

**Issue by ghost** [keepassxreboot/keepassxc#7106] opened 2021-11-04 08:00 UTC
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
To transfer entries from one DB to the other, functions like Cut/Copy/Paste on single and preferably multiple DB entries would be needed.

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
I want to create a DB which is about to contain several entries from a "master" DB and meant to be given away to employees. The only way to this at the moment is to export the whole master DB, delete the entries not needed and import it again as a different DB. That's pretty time-consuming and not a good way to go.

**Comment by droidmonkey** [comment] 2021-11-04 10:16
You could also:
- drag and drop the entries you want to copy to the new database, hold CTRL when dragging to copy instead of move
- copy the actual master kdbx file, open the copy and delete entries not needed. Also recommend resetting the database uuid under database settings -> browser integration
- don't do any of this and just make a couple targeted databases and drop them in a read only network share so employees can open them directly. This has the side benefit of being able to reset passwords without redistribution.

**Comment by droidmonkey** [comment] 2021-11-04 10:21
This is a duplicate of #172 #2074

**Closed as completed by droidmonkey** 2021-11-04 10:21 UTC
Labels: duplicate
