### ISSUE TITLE
Keepassxc 2.4.0 doesn't respect set keyboard language

### ISSUE THREAD

**Issue by vanous** [keepassxreboot/keepassxc#2827] opened 2019-03-21 17:27 UTC
## Expected Behavior
When logging in i expect "Z" to be where i set it via DE (gnome-shell) keyboard settings.

## Current Behavior
When i type "Z", i get "Y". This was not happening in 2.3.x

## Versions:

Keepassxc 2.4.0 , AppImage

vanous@debthinkpad:$ uname -a
Linux debthinkpad 5.0.0-trunk-amd64 #1 SMP Debian 5.0.1-1~exp1 (2019-03-12) x86_64 GNU/Linux

vanous@debthinkpad:$ cat /etc/debian_version 
buster/sid

Gnome 3.30.2

thank you

**Comment by phoerious** [comment] 2019-03-26 13:26
Duplicate of #428

**Closed by phoerious** 2019-03-26 13:26 UTC
Labels: bug, distribution: AppImage

**Comment by vanous** [comment] 2019-03-27 10:17
This is not a duplicate, i can enter accented characters just fine. The issue might be in gnome-shell, however (not sure yet), as it might be that the language settings might not be available right after gnome-shell start...

**Comment by phoerious** [comment] 2019-03-27 10:19
It's not about accented characters, it's about your keyboard layout being mixed up. Z and Y being switched points to you having a QWERTZ keyboard, but KeePassXC assuming a QWERTY keyboard.

**Comment by vanous** [comment] 2019-03-27 13:15
Yes. But after restarting KPXC, all is correct and the keyboard layout is detected correctly, i can input all data correctly.

**Comment by phoerious** [comment] 2019-03-27 13:16
It's still the same bug or a variation of it.

**Comment by ibqn** [comment] 2019-10-14 16:55
This is very annoying bug, I do not see why it is closed, I have two keyboard layouts 'en' and 'de' and if I switch the language on ubuntu 18.04 keepassxc enters characters from the other primary layout...

**Comment by droidmonkey** [comment] 2019-10-14 18:02
It's closed because its a duplicate of another, open, issue.
