### ISSUE TITLE
unable to copy user and password

### ISSUE THREAD

**Issue by JAPPR** [keepassxreboot/keepassxc#4081] opened 2020-01-03 10:13 UTC
Hi all.
I have a very irritating issue with Keepassxc.
When I select an entry to copy user and password many times on right click I get an option for a new CTRL N, and I am not able to copy user / pass.
This is erratic but very frequent.
Any help on this problem?
![3B1DCA81-7FAB-44ED-9DC9-261625DA726C_4_5005_c](https://user-images.githubusercontent.com/19793253/71717947-a70a1900-2e11-11ea-8c07-30585991b73d.jpeg)

I am on a iMac Pro, Catalina and using a Logitech wireless Mouse. I have no problems with other apps

**Comment by droidmonkey** [comment] 2020-01-03 12:35
You need to click the title bar of the application first. There is a bug on Qt macOS that the application does not receive focus when you right click it.

**Comment by droidmonkey** [comment] 2020-01-03 14:12
Duplicate of #3412

**Closed by droidmonkey** 2020-01-03 14:12 UTC
