### ISSUE TITLE
Feature Request: Show statistics about the database

### ISSUE THREAD

**Issue by bryceml** [keepassxreboot/keepassxc#1283] opened 2017-12-14 18:04 UTC
I think it would be cool if there was something in a menu you could click to show statistics about the database, like:

Total passwords
Total Unique passwords
Average length of password use between changes
Total / Unique usernames
Average / Min / Max password lengths and complexities
Oldest Password

I think it would be useful.

**Comment by TheZ3ro** [comment] 2017-12-14 22:04
Duplicate of #551, please use that Issue, I'm closing this one

**Closed by TheZ3ro** 2017-12-14 22:04 UTC
