### ISSUE TITLE
autotype feature uses the wrong keyboard layout

### ISSUE THREAD

**Issue by yennor** [keepassxreboot/keepassxc#688] opened 2017-06-27 07:52 UTC
I already filled that bug against keepassx. But since it still exists in keepassxc 2.2.0 I fill it here again.
I've got more than one keyboard layout installed on my system since I'm not always using the same keyboard, and also depending on the language I write in, I've got to change the layout. When using the autotype feature, it mostly uses the wrong keyboard layout. 
That means the autotype feature writes y instead of z and vice-versa. also some special keys like "$+\#*" are mapped wrongly.
Like that the whole autotype feature is relatively useless to me. I always need to open keypassxc, copy the password to clipboard and paste it at the right place manually.

I'm using Debian Stretch with KDE 5.

**Comment by phoerious** [comment] 2017-06-27 08:50
Duplicate of #324

**Closed by phoerious** 2017-06-27 08:50 UTC
