### ISSUE TITLE
Keepassxc does not print special characters when auto-typing

### ISSUE THREAD

**Issue by glospoto** [keepassxreboot/keepassxc#4661] opened 2020-04-25 21:43 UTC
Hi there,
I'm experiencing a boring behavior when auto-typing passwords. In particular, I observed this problem when the password contains some special character like "-" or "_". The problem showed up with version 2.5.4. With previous versions everything worked fine. I'm runninng it on Arch Linux.
Thanks for your support.

**Comment by droidmonkey** [comment] 2020-04-25 22:21
Are you using a different keyboard layout?

**Comment by glospoto** [comment] 2020-04-26 16:36
Hi,
what do you mean by " using different keyboard layout"? I'm currently using the italian keyboard layout and the character is not printed at all. I'm not talking about character substitutions.
Thanks!

**Comment by droidmonkey** [comment] 2020-04-26 16:50
There is nothing special about the characters you mentioned, but if they don't map correctly on the Italian keyboard then they won't print. We already know about this situation and there is not much we can do about it.

**Comment by glospoto** [comment] 2020-04-26 17:23
I know there is nothing special about those characters. I meat they are neither letters nor numbers. By the way, I do not think it is matter of mapping. Suppose a password is "-123" when keepassxc types it, the resulting password is "123", namely, without character "-". I even try with password "1-23" and it results in "123" after keepassxc auto-typing. I do not know why, but that character is skipped for some reason, regardless its position in the password itself. If you need more information, please let me know.
Thanks!

**Comment by droidmonkey** [comment] 2020-04-26 17:46
This is a duplicate of #324

**Closed by droidmonkey** 2020-04-26 17:46 UTC
Labels: duplicate, more info needed
