### ISSUE TITLE
Can't connect to agent after switching to the snap package (2.4.2)

### ISSUE THREAD

**Issue by fgianneschi** [keepassxreboot/keepassxc#3251] opened 2019-06-10 11:53 UTC
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
Trying to get the ssh-agent integration to work again, after switching to the snap package.

## Current Behavior
When I open the database, or I try to add/remove a ssh key to the agent, it says that it can't connect to the agent.

## Possible Solution
Switch to OpenSSH agent? Seems complicate.

## Steps to Reproduce
1. Enable SSH Agent support
2. Open the database
3. Try to add key to agent

## Context
In order to get the latest version of KeepassXC on my Ubuntu 18.04.02 LTS, today I've switched my installation from 2.3.4 (managed by apt-get), which I removed, to the new 2.4.2 managed by snap.
I was able to get the ssh-agent integration to work correctly under the 2.3.4, but now it doesn't work anymore. Can't connect to agent.
At first, it was simply a problem of file system permissions, since the new installation can't access the contents of my .ssh directory, but then I copied my keys also under the snap/keepassxc/current directory and I fixed it. However it was only the first part of the problem, because the application still can't connect.
Looks like my new installation can't talk with the agent, which remained the same as before (gnome-keyring 3.28.0.2).
The ssh-add -l command reports no entries, unless I add them by command line. But even after that, Keepass isn't able to remove them.
I've read all the #1800 and #2248 threads, where similar problems are reported, but without success.

## Debug Info
KeePassXC - Version 2.4.2
Revision: b5bc1aa
Distribution: Snap

Qt 5.9.5
Debugging mode is disabled.

Operating system: Ubuntu Core 18
CPU architecture: x86_64
Kernel: linux 4.15.0-50-generic

Enabled extensions:
- Auto-Type
- Integrazione con i browser
- Agente SSH
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.1

**Comment by droidmonkey** [comment] 2019-06-10 13:55
Duplicate of #1951

**Closed by droidmonkey** 2019-06-10 13:55 UTC
Labels: bug

**Comment by fgianneschi** [comment] 2019-06-11 10:58
> Duplicate of #1951

Tried that but it doesn't work.
It's not a matter of finding the ssh key, this was a first issue that I already solved (and the proof is that KeepassXC is able to show the public key).

**Comment by droidmonkey** [comment] 2019-06-11 11:38
The snap app cannot talk to ssh-agent because of sandboxing. This has nothing to do with reading the key file.

**Comment by fgianneschi** [comment] 2019-06-11 13:03
Ok, I'll try the AppImage first and then wait for the Launchpad fix you mentioned in #3203.
Thanks

**Comment by EBoisseauSierra** [comment] 2019-06-19 11:34
Using @hifi 's solution detailed in #1951  (see [this comment](https://github.com/keepassxreboot/keepassxc/issues/1951#issuecomment-474688638)) enables you to keep using snap, while being able to add SSH keys to keepass:

```
sudo snap install --devmode keepassxc
```
