### ISSUE TITLE
No Bépo keyboard support (french dvorak), problem with autotype

### ISSUE THREAD

**Issue by bipox** [keepassxreboot/keepassxc#414] opened 2017-03-19 16:15 UTC
It will enter login information wrong, for example what should be "bépo" will become qwer (on a qwerty configuration).
I understand this is not a priority, and I'm no developer, but if I can help in any way with this I'd be happy to.

**Comment by TheZ3ro** [comment] 2017-03-19 16:48
I think it's a duplicate of #324

**Comment by bipox** [comment] 2017-03-19 17:10
Yes, probably. However phoerious is able to make it work when restarting the program, as I can't make it work, be it starting manually after boot, or closing and relaunching it.

**Closed** 2019-07-10 01:40 UTC
