### ISSUE TITLE
KeePassXC appimage immediately returns error upon update check

### ISSUE THREAD

**Issue by grande-mephistopheles** [keepassxreboot/keepassxc#5422] opened 2020-09-12 10:11 UTC
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
When checking for updates from the Help menu, KeePassXC does not show if the current version is outdated or up-to-date. Instead it shows an error while retrieving update information.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Open KeePassXC appimage
2. Click on "Help" menu from the toolbar
3. Click "Check for Updates"

## Expected Behaviour
[NOTE]: # ( Tell us what you expected to happen )
The application should tell the user if the current version is outdated or not.

## Actual Behaviour
[NOTE]: # ( Tell us what actually happens )
Shows "Update Error" message which is not helpful to user in any way

## Context
[NOTE]: # ( Give us any additional information you may have. )
__Screenshot__
![btwd-err](https://user-images.githubusercontent.com/58479925/92993200-4e7e3600-f4df-11ea-8173-3c08cea181a8.jpg)

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.1
Revision: 9a35bba
Distribution: AppImage

Qt 5.14.2
Debugging mode is disabled.

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.1

[NOTE]: # ( Pick choices based on your environment )

Operating system: Linux Mint 20
CPU architecture: x86_64
Kernel: linux 5.4.0-47-generic
Desktop Environment: Cinnamon
Windowing System: X11

**Comment by droidmonkey** [comment] 2020-09-12 11:32
Duplicate of #4965

**Closed** 2020-09-12 11:33 UTC
Labels: bug
