### ISSUE TITLE
vertical bar(?) while editing database after updating to newest KeepassXC

### ISSUE THREAD

**Issue by lukixx3** [keepassxreboot/keepassxc#5364] opened 2020-09-01 05:24 UTC
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

I've just updated to newest KeepassXC and after editing entry I have a strange vertical line.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. open database
2. edit entry, add a note (i've added URL to my notes as I keep one entry as a simple list of websites in notes)
3. when focused on keepassxc click on the right side of taskbar (where tray icons are, I personally clicked ShareX icon)
4. before this vertical bar appears, there is a part of outline of title marked green, after clicking tray icon it changes to this vertical bar

happens every single time I am editing any entry, currently after just doubleclicking an entry the vertical bar is always visible without even touching tray icons

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.1
Revision: 9a35bba

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10

![image](https://user-images.githubusercontent.com/5240146/91797895-fc5a2c80-ec23-11ea-9df2-8ef9a3ece7a7.png)
![image](https://user-images.githubusercontent.com/5240146/91797905-0419d100-ec24-11ea-870c-2ad3d4789881.png)

**Comment by phoerious** [comment] 2020-09-01 07:42
Duplicate of #5300.

**Closed by phoerious** 2020-09-01 07:42 UTC
Labels: bug
