### ISSUE TITLE
macOS: Export CSV file dialog closes immediately

### ISSUE THREAD

**Issue by vraravam** [keepassxreboot/keepassxc#4888] opened 2020-06-20 15:56 UTC
## Overview
Trying to export as CSV for an encrypted backup of my primary data

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Open a kdbx db
2. Go to "Database" > "Export" > "CSV file"
3. It prompts for "Allow Keepassxc to access files on your filesystem"
4. Click ok
5. The download dialog appears for a split second - and then disappears

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
At step 5 above, I would have expected it to allow me to enter a choice of the target filename as per my choice - and when clicking "ok", it should have exported all entries into a CSV.

## Actual Behavior
The download dialog appears for a split second - and then disappears. There's no file in the exported directory location.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.0-beta1
Build Type: PreRelease
Revision: e5b0219

Qt 5.14.1
Debugging mode is disabled.

Operating system: macOS 10.15
CPU architecture: x86_64
Kernel: darwin 19.5.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.5

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS Catalina
Desktop Env: 
Windowing System:

**Comment by droidmonkey** [comment] 2020-06-20 18:21
There is a bug in Qt on macOS that causes file dialogs to disappear (crash/hang).

**Comment by treewolf** [comment] 2020-08-27 09:24
This also happens here.
macos catalina
10.15.6 beta

KeePassXC - Version 2.6.1
Revision: 9a35bba

Qt 5.15.0
Debugging mode is disabled.

**Comment by droidmonkey** [comment] 2020-09-28 01:41
Duplicate of #5295

**Closed by droidmonkey** 2020-09-28 01:41 UTC
Labels: bug, platform: macOS
