### ISSUE TITLE
Constantly increased CPU usage when DB is unlocked

### ISSUE THREAD

**Issue by Bonikt** [keepassxreboot/keepassxc#3809] opened 2019-11-06 15:12 UTC
## Expected Behavior
Normal CPU usage, being able to auto-type.

## Current Behavior
It's the second day that I use the new version of KeePass, and today it began to behave unusually. CPU usage is about 23% for no reason (at the same time, other processes behave normally). The autotype is significantly slowed down, typing 5 symbols with ~3 second pauses. Even minimizing  /maximizing the window is delayed for a few seconds. 

## Possible Solution
Check what is going on in the background, maybe you introduced some kind of process memory protection?

## Steps to Reproduce
1. Open KeePassXC.
2. Unlock the database with a password.
3. Here it begins. 

## Context
The size of my database is 374 MB. The previous version of KeePassXC worked perfectly with this database. Before installation (portable, zip), I checked the integrity of the zip file. Kaspersky Endpoint Security for Windows 11.1.1.126 (latest version) is installed with the latest databases. 

## Debug Info
KeePassXC - Version 2.5.0
Revision: 1ab8a9f

Qt 5.13.1
Debugging mode is disabled.

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.18362

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5

![Screen 1 - Locked](https://user-images.githubusercontent.com/39348559/68310384-f73e5680-00c0-11ea-9763-b49c872a0db7.png)
![Screen 2 - Unlocked](https://user-images.githubusercontent.com/39348559/68310393-fd343780-00c0-11ea-8b89-b34de9bb68e2.png)
![Screen 3 - System Info](https://user-images.githubusercontent.com/39348559/68310401-00c7be80-00c1-11ea-8f5e-3f3885be280b.png)

**Comment by droidmonkey** [comment] 2019-11-06 15:35
This is a duplicate of the hashing issue. Already fixed in 2.5.1 to be deployed this week.

**Closed** 2019-11-06 15:35 UTC
Labels: bug
