### ISSUE TITLE
Kubuntu won't shutdown or logoff when mainwindow Keepassxc is open locked or not

### ISSUE THREAD

**Issue by Shorty365** [keepassxreboot/keepassxc#1357] opened 2018-01-06 16:37 UTC
When shutting down Kubuntu 16.04 the process hangs is Keepassxc is still open on the desktop. It dos not matter is the database is locked or not. When Keepassxc is minimized shutting down goes as exptected. 

## Expected Behavior
Kubuntu should close all running programs and than perform a normal shut down.

## Current Behavior
If Keepassxc is open on the desktop sutting down results in a black screen with only a mouse cursor. Pressing shortly the Power-button brings a Power/Logoff screen where the shutdown can be activated. Shutting down than completes.

## Steps to Reproduce (for bugs)
Start Keepassxc in Kubuntu 16.04. Keep program running on Desktop and perfom a shut down from the K-menu.

## Debug Info

KeePassXC - VERSION 2.2.4
Revision: REVISION

Libraries:
- LIBS

Operating system: Kubuntu 16.04
CPU architecture: AMD64
Kernel: 4.10.0-42

Enabled extensions:
- EXTENSIONS

**Comment by phoerious** [comment] 2018-01-06 19:29
Duplicate of #856.

**Closed by phoerious** 2018-01-06 19:29 UTC
