### ISSUE TITLE
improve right-click entry menu usability

### ISSUE THREAD

**Issue by mfc** [keepassxreboot/keepassxc#2942] opened 2019-04-04 13:32 UTC
porting this bug report over from [KeePassX](https://dev.keepassx.org/issues/445) since it still exists in KeePassXC v2.4.0 and i cannot find existing issue for it. 

# Expected Behavior

When right-clicking on an entry in KeePassXC v2.4.0, the user expects the first choices to pertain to the entry one is right-clicking.

# Current Behavior

Instead, the first option is "Add new entry", which has no relationship with the entry selected.

# Possible Solution

From a usability and user expectations perspective, what should happen is that first, operations pertaining to the entry in question should be listed. Second, meta-operations related to the entry listed. Finally (if deemed necessary), operations totally unrelated to the entry selected should be listed. So for example:

* operations related to the entry in question
  * Copy username
  * Copy password
  * Copy attribute to clipboard
  * Open URL

* meta-operations related to the entry in question
  * Edit entry
  * Clone entry
  * Delete entry
  * Perform Auto-Type
  * TOTP

* unrelated operations
  * Add new entry

**Comment by droidmonkey** [comment] 2019-04-04 13:50
This is a duplicate of a recently reported issue.

**Closed** 2019-04-04 13:52 UTC
Labels: duplicate
