### ISSUE TITLE
Autotyping into noVNC results in a keyboard layout mismatch (QWERTY vs QWERTZ)

### ISSUE THREAD

**Issue by Braintelligence** [keepassxreboot/keepassxc#4799] opened 2020-06-01 08:35 UTC
## Overview
When autotyping into a noVNC browser window (for example when using Proxmox VE) every y/Y is converted into z/Z and vice-versa. This doesn't happen with KeePass 2.x.

## Steps to Reproduce
1. Open a noVNC window in a browser (in my case Opera) to a VM running in Proxmox VE. In my case Ubuntu Server 20.04 with `XKBLAYOUT="de", XKBVARIANT="nodeadkeys"` (thus QWERTZ).
2. Run KeepassXC (in my case on Windows 10 with QWERTZ) and Auto-Type the password into the noVNC window.
3. You will see y/Y and z/Z replaced with each other.

## Expected Behavior
I expect this to work as it works on Keepass 2.X: Not switching symbols. Since it works with Keepass 2.X it has to be an issue with KeepassXC.

## Actual Behavior
y/Y and z/Z are being replaced with each other in an autotyped sequence.

DEBUG info:
KeePassXC - Version 2.5.4
Revision: c023bf9

Qt 5.14.2
Diagnosemodus ist deaktiviert.

Betriebssystem: Windows 10 Version 1909
CPU-Architektur: x86_64
Kernel: winnt 10.0.18363

Aktivierte Erweiterungen:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare (bestätigtes und unbestätigtes Teilen)
- YubiKey

Kryptographische Bibliotheken:
 libgcrypt 1.8.5

Operating System (Host): Windows 10
Operating System (VM in noVNC): Ubuntu Server 20.04

If you need any more info I'll happily provide it. If this issue is a duplicate please point me to the original issue; I couldn't find anything that exactly depicts this behaviour.

EDIT: My current workaround is copying the password into a custom field and switching the y/Y and z/Z there btw.

**Comment by phoerious** [comment] 2020-06-01 08:50
Duplicate of #324

**Comment by Braintelligence** [comment] 2020-06-01 08:51
Thanks for pointing me to the corresponding issue 👍

**Comment by Braintelligence** [comment] 2020-06-01 08:55
@phoerious Wait, I'm not convinced this is the same issue.

Just to be sure:

When I use KeepassXC on my Windows Host and autotype into an editor or some password form I get the expected string.

When I use KeepassXC on my Windows Host and autotype into the noVNC window the y/Y and z/Z are replaced.

Is this REALLY the same issue? The issue you've linked does seem to have the problem running within the same environment.

**Comment by phoerious** [comment] 2020-06-01 12:32
Actually, it's probably more related to #1833, but perhaps also its own issue. I'll reopen for now, but I don't think this is going to be fixed any time soon.

**Comment by Braintelligence** [comment] 2020-06-01 12:41
Thanks; I can wait. The workaround works for now and hopefully helps other people when looking for it here. I even think I saw someone talk about VNC somewhere on here.

**Comment by smorks** [comment] 2022-03-24 03:04
i'm having a similar issue with auto-type and noVNC, i tested with the latest KeePassXC version (2.7.0) on Windows 10/11.

basically, any password with special characters auto-typed into noVNC results in the password being typed as if shift wasn't pressed.

for example, if my password is "passw@rd*", i would send "passw2rd8".

when i use the auto-type feature in KeePass, it works as expected, so i don't believe it's a noVNC issue? however auto-typing in KeePassXC into other apps works as expected. it's pretty strange.

**Comment by droidmonkey** [comment] 2022-03-24 03:16
You can now use the special virtual keyboard mode when autotyping into virtual or remote guests. When in the selection dialog press Ctrl+4 or select the virtual keyboard from the right click menu.

**Closed by droidmonkey** 2022-03-24 03:16 UTC
Labels: duplicate

**Comment by smorks** [comment] 2022-03-24 03:25
thank you, that works great!
