### ISSUE TITLE
Open terminal for ssh:// urls (continued)

### ISSUE THREAD

**Issue by JakobPP** [keepassxreboot/keepassxc#3488] opened 2019-08-30 19:44 UTC
I can see this bug has been around before and possibly fixed/not fixed? https://github.com/keepassxreboot/keepassxc/issues/2427

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
double click on url with ssh://{username}@ip:22 should open terminal automatically.

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
ssh:// url - not working when double click on url field or when use cmd shortcut in front as well. The URL field has been tested and is working with "normal" HTTP URL.

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )

    1.add to url eg. ssh://127.0.0.1:22
    2.Save
    3.try to Url open, double click on URL

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.4.3
Revision: 5d6ef0c

Qt 5.9.5
Debugging mode is disabled.

Operating system: Ubuntu 18.04.3 LTS
CPU architecture: x86_64
Kernel: linux 4.15.0-58-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.1

**Comment by droidmonkey** [comment] 2019-08-31 00:12
This works in 2.4.3. You have to setup your OS to handle ssh:// schemas to launch the terminal. I just tested on Windows 10 and it worked.

**Comment by intonet** [comment] 2019-09-10 07:55
Hi. 
I tested this and works for:
ssh://myname@10.0.0.1:22

but not works when I use {username} variable
ssh://{username}@10.0.0.1:22

( in preview at Botton pane {username} in URL is replaced ok.) 
Can you look at this again ?

**Comment by droidmonkey** [comment] 2019-09-10 11:47
Ahhh interesting

**Comment by strasharo** [comment] 2019-09-19 19:48
Same here, on the URL preview in the grid I see the placeholder being replaced by the user, but when I run it it ends up as %7BUSERNAME%7D in the command line.

**Comment by jzielke84** [comment] 2019-10-22 10:38
Confirmed, this shuld be fixed asap since it's a basic functionality that's broken

**Comment by droidmonkey** [comment] 2019-10-26 17:39
This was fixed in c5a93ca and will be in 2.5.0

**Closed by droidmonkey** 2019-10-26 17:39 UTC
Labels: bug
