### ISSUE TITLE
Feature Request: Custom Columns

### ISSUE THREAD

**Issue by Gibletron** [keepassxreboot/keepassxc#2461] opened 2018-11-07 07:45 UTC
We are currently able to add custom attributes to KeepassXC items.
I would like to be able to show these in the main window.
Or for instance show an extra column for TOTP code/availability
I have made a very rough mockup of what I'm thinking of below:

![image](https://user-images.githubusercontent.com/17140683/48117199-c1298500-e268-11e8-9d22-3bc046b85ed9.png)

![image](https://user-images.githubusercontent.com/17140683/48117288-0057d600-e269-11e8-9f71-e66b47888c9c.png) ![image](https://user-images.githubusercontent.com/17140683/48117374-4d3bac80-e269-11e8-8d99-70c611969876.png)

**Comment by droidmonkey** [comment] 2018-11-07 13:11
TOTP column is implemented in the upcoming 2.4.0 release (#2284). We will not be implementing custom attribute columns as it grows very messy very fast. Each entry would have to be searched with their attributes enumerated OR a free-form text box where you type in the entry attribute name. Either way it does not lend itself to a good user experience.

**Comment by Gibletron** [comment] 2018-11-07 17:29
All in all there are only a few fields that I regularly use and in my opinion would be good to add to the main window, OTP and E-Mail are the first to come to mind.
Since OTP is already implemented my current question would be if an extra field for E-Mail would be possible to add.

I think the problem with it would be that a lot of usernames currently are an e-mail address.
As such duplicate information could get messy..
One solution would be to just let the user choose globally (username or username & Email in the interface)
Other option would be a checkbox per added entry with the same choice.

**Comment by thedoginthewok** [comment] 2018-11-16 10:36
This feature is available in the normal Keepass and I've used it without any problems when I was on Windows. This feature is extremely useful in certain use cases.

![keepass_win](https://user-images.githubusercontent.com/6908247/48615983-a060de00-e992-11e8-9340-ac0e08127674.png)

In my case, I have to add the custom fields anyway, to be able to use them in the URL. On Windows I was using Keepass as a sort of "poor man's single sign on" tool. 
I don't want to add the information that I already have in the custom fields to the title or notes, as that would mean duplicating it. 

Alternatively it would be great to be able to reference other fields in the Notes or Title section:

![grafik](https://user-images.githubusercontent.com/6908247/48616336-97bcd780-e993-11e8-851b-7c5ed0b5589a.png)


I know the custom fields are resolved to their values in the URL, but I haven't yet updated the URLs to the macOS version of the tool I'm using to log on. The updated URL will be much longer, and the fields will not be visible like they are now. 

If resolving in Title or Notes is not possible, a custom column for all custom fields would be great too.

**Comment by droidmonkey** [comment] 2019-07-10 02:09
Duplicate of #1493

**Closed by droidmonkey** 2019-07-10 02:09 UTC
