### ISSUE TITLE
Add option to hide window on close for macOS

### ISSUE THREAD

**Issue by mrroman** [keepassxreboot/keepassxc#498] opened 2017-04-13 13:04 UTC
Hide window on close is a common workflow for macOS apps. Users close the window, but the application is working in the background with opened document. If you want to go back, you just click app icon in the dock.

## Expected Behavior
When user presses window Close button, the window is hidden (not minimized). 

## Current Behavior
When use presses window Close button, it closes the application.

## Possible Solution
Add option in the preferences to enable described behaviour. I think we can use QWindow::hide() method.

## Context
This will implement common macOS app workflow.

## Your Environment
* KeePassXC 2.1.4
* Qt version (e.g. Qt 5.3): 
* Compiler (e.g. Clang++3.6.0): 
* Operating System and version: macOS Sierra

**Comment by ibrokemypie** [comment] 2017-05-08 01:25
Very annoying closing the window and then no longer being able to use browser extension

**Comment by TheZ3ro** [comment] 2017-05-08 15:31
I'm not a MacOS expert, but in the codebase I see this line:

```
bool MainWindow::isTrayIconEnabled() const
{
#ifdef Q_OS_MAC
    // systray not useful on OS X
    return false;
#else
```

The *MinimizeOnClose* option is enabled only if `isTrayIconEnabled()` returns true, on MacOS this returns always false and the comment says that systray is not usefull on MacOS.

Does MacOS has systray? If an application hides itself the icon is still shown?

**Comment by ibrokemypie** [comment] 2017-05-08 22:25
https://github.com/keepassxreboot/keepassxc/issues/438

**Comment by mrroman** [comment] 2017-05-09 06:35
@TheZ3ro 

MacOS system tray looks more or less like Ubuntu systray.

When you hide application window, it still works in the background and is available in the dock. You can show app window just by clicking app icon in the dock. A new instance won't be started. Dock also inspired Ubuntu Unity and Gnome 3 Shell :).

**Comment by TheZ3ro** [comment] 2017-05-09 09:03
This is a duplicate of #438 anyway can you guys test this branch? https://github.com/keepassxreboot/keepassxc/tree/feature/macos-minimize-onclose
I've made a hotfix for a Minimize to Dock on Close.

I've preferred the dock because adding a trayicon with the only option to Toggle Window is pretty useless. Let me know what you think and if it works!

**Comment by mrroman** [comment] 2017-05-09 10:17
It doesn't work :(. But I know why :).

1. You have to enable GUI/MinimizeOnClose option for MacOS. It is not visible in configuration panel. 
2. To make it work as I described, you have to modify hideWindow() like this:

```cpp
void MainWindow::hideWindow()
{
#ifndef Q_OS_MAC
    setWindowState(windowState() | Qt::WindowMinimized);
#endif
    QTimer::singleShot(0, this, SLOT(hide()));
...
```

**Closed** 2017-05-19 16:51 UTC
Labels: new feature
