### ISSUE TITLE
Secret Service integration broken

### ISSUE THREAD

**Issue by moridius** [keepassxreboot/keepassxc#10396] opened 2024-03-12 10:45 UTC
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
I cannot get passwords via the Secret Service integration anymore.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Unlock the database.
2. Use secret-tool to request a password.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Getting the password.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
KeePassXC popup asks me to unlock the database (although it's already unlocked). If I give the correct master password the popup vanishes and nothing happens. After some time secret-tool reports a timeout.

## Context
[NOTE]: # ( Give us any additional information you may have. )
This worked fine before the update (probably with version 2.7.6 although I don't know).

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.7
Revision: 68e2dd8

Qt 5.15.11
Debugging mode is disabled.

Operating system: Void Linux
CPU architecture: x86_64
Kernel: linux 6.6.21_1

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.19.3

[NOTE]: # ( Pick choices based on your environment )
Operating System: Void Linux
Desktop Env: i3  window manager
Windowing System: X11

**Comment by droidmonkey** [comment] 2024-03-12 11:16
I think you might have two keepassxc's running at the same time? We only fixed a small crash bug with Secret Service integration that doesn't impact credential retrieval. Do a reboot and try again.

**Comment by tomfun** [comment] 2024-03-13 09:01
I have the same problem on
 Linux Mint XFCE
 Linux sqdl-l 5.15.0-100-generic #110-Ubuntu SMP Wed Feb 7 13:27:48 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

> you might have two keepassxc's running at the same time?

No. 

![image](https://github.com/keepassxreboot/keepassxc/assets/5002775/fd9c7d73-b6df-4d28-b5df-486f9e6fd094)

some times it shows error:

![image](https://github.com/keepassxreboot/keepassxc/assets/5002775/30df09ef-e858-4d6a-b13a-afcfd536347b)
![image](https://github.com/keepassxreboot/keepassxc/assets/5002775/deb949fa-5fcd-4ee9-a7ee-890b01e1bab9)

**Comment by Taijian** [comment] 2024-03-15 13:31
I have the same issue - it took me a while to figure this one out, but here's what's happening.

Secret Service support is configurable via the 'Database settings' menu dialogue. 
For some reason, after the update to 2.7.7, this setting keeps reverting to 'Do not unlock this database' after some time elapses. I then have to go back to this setting, re-select the  Group(s) I want to expose to the Secret Service Agent, confirm and then it works again... for a while.
Then it breaks again and I have to re-enable it again, etc...



![Bildschirmfoto vom 2024-03-15 14-28-44](https://github.com/keepassxreboot/keepassxc/assets/18460640/3423a623-8ee0-4a2f-8b53-20e6a0071394)

**Comment by Taijian** [comment] 2024-03-15 14:11
Investigating further, it seems that the permission revert happens whenever a changed shared database - via the KeyShare functionality - is merged back into the 'main' database, then the Secret Service permission setting gets reverted. So possibly related to #9371

**Comment by droidmonkey** [comment] 2024-03-15 17:19
Yes this is a duplicate of that issue. No changes to FdoSecrets was made in 2.7.7 that would relate to this behavior.

**Closed as not planned by droidmonkey** 2024-03-15 17:19 UTC
Labels: duplicate, feature: Secret Service
