### ISSUE TITLE
CLI Tests fail on systems with non-default (en-US) locale

### ISSUE THREAD

**Issue by libklein** [keepassxreboot/keepassxc#8525] opened 2022-10-01 10:50 UTC
## Overview
TestShow CLITest fails on systems with non-default (en-US) locales.

## Steps to Reproduce
1. Change your locale / add `QLocale::setDefault(QLocale("de-DE"));` to https://github.com/keepassxreboot/keepassxc/blob/develop/tests/TestCli.cpp#L76.
2. Run testcli.
3. testShow fails.

Operating System:Linux
Desktop Env: -
Windowing System: X11

**Comment by michaelk83** [comment] 2022-10-01 11:14
Duplicate of #7747 , I think. Should be fixed by #7780.

**Comment by droidmonkey** [comment] 2022-10-01 12:01
Correct

**Closed as not planned by droidmonkey** 2022-10-01 12:01 UTC
Labels: duplicate
