### ISSUE TITLE
Filling in the form fields separately

### ISSUE THREAD

**Issue by icaid** [keepassxreboot/keepassxc#3342] opened 2019-06-30 09:23 UTC
[TIP]:  # ( Provide a general summary of the feature in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Summary
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
It would be very handy to use the possibility to fill fields in form by pulling login or password separately.

## Desired Behavior
[NOTE]: # ( Tell us how the new feature should work, be specific )
1. Highlight a database entry.
2. Click on any part of entry (login, password or something else) and not releasing left mouse button pull chosen part to field of form.
3. Form field must be filled only chosen part of entry (only login or only password, etc) but not whole string of database entry as it is now.
## Possible Solution
[NOTE]: # ( Not required, but suggest ideas on how to implement the addition or change )

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
It is handy to have a possibility to choose which informatin to use for filling form.

**Comment by droidmonkey** [comment] 2019-06-30 16:13
Duplicate of #2724

**Closed by droidmonkey** 2019-06-30 16:13 UTC
Labels: new feature
