### ISSUE TITLE
MinimizeToTray=true and --pw-stdin Don't open a window, then hide it

### ISSUE THREAD

**Issue by MorsMortium** [keepassxreboot/keepassxc#9020] opened 2023-01-21 11:22 UTC
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
The title says it all. One addition is that this will show the password length too, but that's not my concern, only that it pops up on startup

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Set MinimizeToTray=true from GUI or the config file
2. Start with --pw-stdin

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
There will be no window, only the tray icon with the opened db.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
The window pops up for half a second, with the password already in the field, and the "enter pressed" state, grayed out, then it disappears to the tray.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.4
Revision: 63b2394

Qt 5.15.7
Debugging mode is disabled.

Operating system: Manjaro Linux
CPU architecture: x86_64
Kernel: linux 6.0.15-1-MANJARO

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.19.3

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: KDE
Windowing System: X11

**Comment by MorsMortium** [comment] 2023-07-29 17:43
This seems to have been fixed since. But I'm not sure if it was something with KDE Plasma, or the fix is, so I hope a developer can confirm that it was fixed.

**Comment by droidmonkey** [comment] 2023-07-29 20:03
We didn't explicitly fix it so it likely wasn't broken on our end. Closing if you cannot reproduce.

**Closed as completed by droidmonkey** 2023-07-29 20:03 UTC
