### ISSUE TITLE
Unlock database command/shortcut

### ISSUE THREAD

**Issue by piegamesde** [keepassxreboot/keepassxc#2644] opened 2019-01-24 13:27 UTC
## Desired Behavior
I'd like to be able to unlock KeepassXC using a global shortcut and/or the command line. KeepassXC is always running in background with the correct database opened, but locked.  

## Possible Solutions
- Provide a command option that connects to the running application and asks to unlock it
- Add a setting for a global unlock shortcut, like the autotype option does, but without the autotype.

**Comment by droidmonkey** [comment] 2019-01-24 18:52
This is a duplicate of #99. In 2.4.0, If you use the global Auto-Type shortcut then the database unlock dialog properly shows as well.

**Closed by droidmonkey** 2019-01-24 18:52 UTC
Labels: new feature

**Comment by piegamesde** [comment] 2019-01-25 09:10
@droidmonkey I disagree, this is a different issue. I explicitly don't want to autotype, I just want to unlock the database via shortcut.

**Comment by droidmonkey** [comment] 2019-01-25 12:22
I was just using the Auto-Type window as an example. The linked issue is a global shortcut to raise/lower the window from the system tray.

**Comment by piegamesde** [comment] 2019-01-28 12:18
I don't really understand how to set it up without autotype. Also, I do not have a system tray; the window is always open in the background.

My current workaround to focus the window from the command line is `xdotool windowactivate $(xdotool search --onlyvisible --class keepassxc)`.

**Comment by droidmonkey** [comment] 2019-01-28 14:15
If you have it always open in the background why doesn't ALT+TAB or desktop window switch work just as well? The main reason for a keyboard shortcut to bring a window to the front is because the window is not part of those options. I don't know what desktop env you are using but most linux envs allow you to program arbitrary keyboard shortcuts to execute programs such as your xdotool trick.
