### ISSUE TITLE
High Network Traffic

### ISSUE THREAD

**Issue by szeberli** [keepassxreboot/keepassxc#3755] opened 2019-11-01 14:24 UTC
KeePassXC 2.5.0
## Current Behavior
High Network Traffic 5Mbit/s down

## Steps to Reproduce
If the KeepassXC DB is set up on a SMB share, it has high network traffic of about 5Mbit/s down

Operating system: Win10
CPU architecture: i7 64bit

**Comment by phoerious** [comment] 2019-11-01 14:30
Duplicate of #3699.

**Closed by phoerious** 2019-11-01 14:30 UTC
Labels: duplicate
