### ISSUE TITLE
Secrete service client triggers unlock of the wrong database

### ISSUE THREAD

**Issue by guidot** [keepassxreboot/keepassxc#10797] opened 2024-05-23 08:09 UTC
## Overview
The last database that has the focus before shutdown will be presented for unlock (triggered by a client request) upon next start, no matter if it is the one with a secret service group configured or not. The dialog does not offer to select the correct one.

## Steps to Reproduce
1. Have two databases: db A with a secrete service group and db B without.
2. With only db A unlocked start a program that uses secrete service (in my case the Nextcloud Desktop client).
3. Client happily uses db A.
4. Reboot or relogin.
5. Client triggers unlock dialog for db A. Nice.
6. Now open db B and give it the focus.
7. Reboot or relogin.

## Expected Behavior
KeePassXC selects db A in the unlock dialog.
If it doesn't know which db to select let the user chose one.

## Actual Behavior
KeePassXC selects db B in the unlock dialog.
No way to select a different db.

## Context
KeePassXC - Version 2.7.8
Revision: f6757d3

Qt 5.15.13
Diagnosemodus ist deaktiviert.

Betriebssystem: openSUSE Tumbleweed
CPU-Architektur: x86_64
Kernel: linux 6.8.9-1-default

Aktivierte Erweiterungen:
- Auto-Type
- Browser-Integration
- Passkeys
- SSH-Agent
- KeeShare
- YubiKey
- Secret-Service-Integration

Kryptographische Bibliotheken:
- Botan 2.19.3

Operating System: Linux
Desktop Env: KDE
Windowing System: X11

**Comment by droidmonkey** [comment] 2024-05-23 11:01
duplicate of #9225

**Closed as completed by droidmonkey** 2024-05-23 11:01 UTC
