### ISSUE TITLE
keepassxc does not open attachments in pdf with adobe acrobat dc

### ISSUE THREAD

**Issue by daniele74b** [keepassxreboot/keepassxc#5839] opened 2020-12-16 08:08 UTC
hi, I installed keepassxc version 2.6.2 on windows 10, I have a problem with opening the attached files in pdf, in practice as soon as I click on the attachment when opening adobe acrobat dc it reports me an error that it cannot open the file, and it says exactly "error while opening the document. this file is already open or used by another application" i could not find anything on the net for this problem, not if it is really a bug .... if possible could someone give me some information thank you in advance.
I am attaching a screenshot of the error
![acrobat](https://user-images.githubusercontent.com/75983945/102321568-27238300-3f7e-11eb-91b3-8af9ff45a5b1.JPG)

**Comment by phoerious** [comment] 2020-12-16 19:08
Duplicate of #2400.

**Closed by phoerious** 2020-12-16 19:08 UTC
Labels: bug

**Comment by luisfl** [comment] 2026-03-03 14:48
keepassxc still not recognizing PDF files added as attachments: keepassxc-2.7.11-3.fc42.x86_64, Fedora 42 fully updated.

**Comment by droidmonkey** [comment] 2026-03-03 20:52
We decided not to support pdf capability due to increased dependencies
