### ISSUE TITLE
Ctrl+Backspace doesn't delete selection in text fields

### ISSUE THREAD

**Issue by beastr45** [keepassxreboot/keepassxc#11091] opened 2024-07-21 23:21 UTC
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

for some reason whenever pressing control + backspace after entering the wrong password in order to unlock a database the highlighted text isnt deleted and the cursor goes to the beggining of the password box instead.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1.  enter the wrong password when trying to unlock a database
2.  the password box should be highlighted, expecting the user to press backspace 
3.  press control backspace instead out of muscle memory, the highlighted text will not delete.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

the text should delete whether control backspace or backspace is pressed.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

the password gets messed up because it gets entered in twice.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows/Linux/macOS
Desktop Env: Gnome/KDE/XFCE/Mate/Cinnamon
Windowing System: X11/Wayland

**Comment by droidmonkey** [comment] 2024-07-21 23:30
Windows, Mac or Linux? Although I doubt we will do anything about this since this behavior is controlled by Qt, not us.

**Comment by beastr45** [comment] 2024-07-22 02:28
> Windows, Mac or Linux? Although I doubt we will do anything about this since this behavior is controlled by Qt, not us.

Shure! My current user setup is with using a linux machine. Is the described issue not reproducible on windows?

**Comment by droidmonkey** [comment] 2024-07-22 02:38
I can reproduce it on Windows, hadn't tried before since I was away from my computer. Interestingly this doesn't seem to impact another Qt application I am using. Although it is consistent behavior in every text field, not just the main password unlock.

**Comment by droidmonkey** [comment] 2024-07-22 03:22
OK, I traced this in the debugger and it is indeed a Qt bug, seems to be fixed in Qt 6 which we are going to eventually. The bug is that the cursor is moved to the start of the line BEFORE the delete action happens. This causes the text to become deselected and nothing gets deleted.

```
else if (event == QKeySequence::DeleteStartOfWord) {
    if (!isReadOnly()) {
        cursorWordBackward(true);  // <--- Bug happens here, this should come AFTER the del() call
        if (hasSelectedText())
            del();
    }
```

**Closed as completed by droidmonkey** 2024-07-22 03:22 UTC
Labels: user interface, Qt
