### ISSUE TITLE
Double clicking a database no longer opens the password/keyfile prompt window

### ISSUE THREAD

**Issue by TheChiefMeat** [keepassxreboot/keepassxc#1579] opened 2018-03-01 10:34 UTC
## Expected Behavior
KeePassXC used to show the password/keyfile input boxes when you double clicked any database file. in 2.3.0, that is no longer the case.

## Steps to Reproduce (for bugs)
1. Install 2.2.4
2. Untick 'Remember last database, Remember last key file and security dongles', 'Load previous databases on startup'
3. Double click any database file.
4. Rerun the above three steps with version 2.3.0.

## Debug Info
KeePassXC - Version 2.3.0
Revision: 4c0ed74

Libraries:
- Qt 5.10.1
- libgcrypt 1.8.2

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.16299

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- YubiKey

**Comment by phoerious** [comment] 2018-03-01 10:36
Duplicate of #1533

**Closed by phoerious** 2018-03-01 10:36 UTC
