### ISSUE TITLE
Support for field references between entries

### ISSUE THREAD

**Issue by kwiniarski** [keepassxreboot/keepassxc#560] opened 2017-05-10 13:38 UTC
## Expected Behavior
Original KeePass has a feature to copy an entry with references in user/password fields. In KeePassXC those references are not recognized. When I copy user name or password from copied entry (with references) I should get referenced user name or password.

## Current Behavior
Currently KeePassXC don't recognize reference tokens (ex. `{REF:U@I:F7C70D1E65A8CD49BCDB549AC759D748}`) and when an entry is matched to the domain, reference token is suggested/returned for both user and password.

## Possible Solution
If entry is matched, then application should check if user or password matches reference token pattern. If so, it should look for refereed entry and read data from it. References are described on http://keepass.info/help/base/fieldrefs.html

## Steps to Reproduce (for bugs)
1. Create database with original KeePass
2. Create an entry in it
3. Create copy of the entry with references
4. Open database in KeePassXC and try to use copied entry

## Context
Original KeePass has a feature to copy an entry with references in user/password fields, which is very convenient for example if you have in the company several applications which are authorized using credentials from LDAP or other central system. Generally if you change this password then you have change X entries in KeePass. With references this is still one entry to change.

## Your Environment

* KeePassXC version/commit used: 2.1.4/cb283bb95ae559d044415f426f841c27bff383f0
* Qt version (e.g. Qt 5.3): 5.5.1
* Compiler (e.g. Clang++3.6.0): 
* Operating System and version: Ubuntu 16.04

**Comment by TheZ3ro** [comment] 2017-05-10 13:50
This is a duplicate of #75 and it has been fixed in #370. This feature will be available in the next 2.2 version of KeePassXC

**Closed by TheZ3ro** 2017-05-10 13:50 UTC

**Comment by lanox** [comment] 2017-05-25 23:33
@TheZ3ro when will 2.2 be released ?

**Comment by TheZ3ro** [comment] 2017-05-26 08:35
@lanox we don't have a fixed date, but I think it will be soon
