### ISSUE TITLE
Frequent freezes with webdav hosted database (network-related)

### ISSUE THREAD

**Issue by theCalcaholic** [keepassxreboot/keepassxc#3788] opened 2019-11-04 12:14 UTC
## Expected Behavior
At least as long as KeepassXC is neither saving nor loading the database, the application runs smoothly, whether or not the database is hosted locally or remotely (e.g. via webdav/sftp/...).

## Current Behavior
KeepassXC freezes frequently when used with slow web shares, even when not manually interacted with.

## Possible Solution
A possible cause could be regular checks on the database file (e.g. whether or not it has been changed remotely), that are implemented blockingly. A solution would be to always rely on asynchronous I/O (would also be nice for the application to not freeze when saving the db).

## Steps to Reproduce
1. Host your password database on some kind of (particularly slow) remote storage (or while limiting connectivity)
2. Activate General -> Automatically reload the database when modified externally in KeepassXC settings
3. Wait

## Context
I'm hosting my password database via webdav while working from a sometimes unreliant company network. The reason why I'm not using KeeShare for synchronization is, that the latter is not supported by my android client (keepass2android).

## Debug Info
KeePassXC - Version 2.5.0
Revision: 1ab8a9f

Qt 5.9.5
Debugging mode is disabled.

Operating system: Ubuntu 18.04.3 LTS
CPU architecture: x86_64
Kernel: linux 4.15.0-66-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.1

**Comment by phoerious** [comment] 2019-11-04 12:21
Duplicate of #3699.

**Closed by phoerious** 2019-11-04 12:21 UTC
Labels: bug
