### ISSUE TITLE
Sort by

### ISSUE THREAD

**Issue by JosefVohnout** [keepassxreboot/keepassxc#671] opened 2017-06-26 14:48 UTC
Hi, Is possible to add a ability to sort entries by "Creation Time" and "Last Modification Time" like in KeePass2?

**Comment by TheZ3ro** [comment] 2017-06-26 16:16
Duplicate of #17

**Comment by phoerious** [comment] 2017-06-26 16:17
Not exactly. I believe the other one is about the grid, this one is about groups.

**Closed by TheZ3ro** 2017-06-26 16:16 UTC
Labels: wishlist
