### ISSUE TITLE
Crash on closing changed entry

### ISSUE THREAD

**Issue by ei-ke** [keepassxreboot/keepassxc#4058] opened 2019-12-24 15:57 UTC
## Expected Behavior
Saving the entry without crashing?

## Current Behavior
I'm just changing many passwords (christmas cleaning...) and started adding favicons and using the browser extension. Now the worst case happened: Segfault from time to time and I'm not sure what is causing it.

## Steps to Reproduce
First I noticed it when grabbing the favicon. So I started to "apply" changes first after changing the password of an entry, then grabbing the favicon and then clicking "OK".
It sometimes failed on the grabbing.
Last tries showed it mostly happens when pressing "OK", also after not changing the favicon at all.

**EDIT** Got it: I just disabled the browser extension. Changed an entry, applied, pressed OK -> crash. Opened the DB, changed an entry, pressed OK -> still alive. Changed the same entry, applied, pressed OK -> died.

## Context
After having this issue I build 2.5.1 with `cmake -DWITH_XC_ALL=ON -DCMAKE_BUILD_TYPE=Debug` and run it with gdb which gives me the following informations:

```
Thread 1 "keepassxc" received signal SIGSEGV, Segmentation fault.
0x000055555563f33c in QScopedPointer<Entry, QScopedPointerDeleter<Entry> >::isNull (this=0x100) at /usr/include/qt/QtCore/qscopedpointer.h:150
150	        return !d;

#0  0x000055555563f33c in QScopedPointer<Entry, QScopedPointerDeleter<Entry> >::isNull() const (this=0x100) at /usr/include/qt/QtCore/qscopedpointer.h:150
#1  0x000055555563ac83 in Entry::beginUpdate() (this=0x0) at /home/eike/github/keepassxc/src/core/Entry.cpp:803
#2  0x00005555556e2979 in EditEntryWidget::commitEntry() (this=0x555556374400) at /home/eike/github/keepassxc/src/gui/entry/EditEntryWidget.cpp:1063
#3  0x00005555556e2ab0 in EditEntryWidget::acceptEntry() (this=0x555556374400) at /home/eike/github/keepassxc/src/gui/entry/EditEntryWidget.cpp:1087
#4  0x000055555562265e in EditEntryWidget::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) (_o=0x555556374400, _c=QMetaObject::InvokeMetaMethod, _id=2, _a=0x7fffffffcf60)
    at /home/eike/github/keepassxc/build/src/keepassx_core_autogen/6E6TVKAI7O/moc_EditEntryWidget.cpp:254
#5  0x00007ffff69f2ac1 in QMetaObject::activate(QObject*, int, int, void**) () at /usr/lib/libQt5Core.so.5
#6  0x000055555561c2eb in EditWidget::accepted() (this=0x555556374400) at /home/eike/github/keepassxc/build/src/keepassx_core_autogen/DMHXEJ42XS/moc_EditWidget.cpp:190
#7  0x000055555561bf90 in EditWidget::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) (_o=0x555556374400, _c=QMetaObject::InvokeMetaMethod, _id=1, _a=0x7fffffffd0c0)
    at /home/eike/github/keepassxc/build/src/keepassx_core_autogen/DMHXEJ42XS/moc_EditWidget.cpp:106
#8  0x00007ffff69f2ac1 in QMetaObject::activate(QObject*, int, int, void**) () at /usr/lib/libQt5Core.so.5
#9  0x00007ffff770f809 in  () at /usr/lib/libQt5Widgets.so.5
#10 0x00007ffff69f2ac1 in QMetaObject::activate(QObject*, int, int, void**) () at /usr/lib/libQt5Core.so.5
#11 0x00007ffff7666de3 in QAbstractButton::clicked(bool) () at /usr/lib/libQt5Widgets.so.5
#12 0x00007ffff766700c in  () at /usr/lib/libQt5Widgets.so.5
#13 0x00007ffff7668412 in  () at /usr/lib/libQt5Widgets.so.5
#14 0x00007ffff76685d6 in QAbstractButton::mouseReleaseEvent(QMouseEvent*) () at /usr/lib/libQt5Widgets.so.5
#15 0x00007ffff75b1096 in QWidget::event(QEvent*) () at /usr/lib/libQt5Widgets.so.5
#16 0x00007ffff756d4e5 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#17 0x00007ffff7576f8a in QApplication::notify(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#18 0x00007ffff69c6d12 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/libQt5Core.so.5
#19 0x00007ffff757612b in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) () at /usr/lib/libQt5Widgets.so.5
#20 0x00007ffff75cd371 in  () at /usr/lib/libQt5Widgets.so.5
#21 0x00007ffff75d0414 in  () at /usr/lib/libQt5Widgets.so.5
#22 0x00007ffff756d4e5 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#23 0x00007ffff7576e11 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#24 0x00007ffff69c6d12 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/libQt5Core.so.5
#25 0x00007ffff6f4fda4 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () at /usr/lib/libQt5Gui.so.5
#26 0x00007ffff6f5164b in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () at /usr/lib/libQt5Gui.so.5
#27 0x00007ffff6f2bb0c in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Gui.so.5
#28 0x00007ffff2fdc0ec in  () at /usr/lib/libQt5XcbQpa.so.5
#29 0x00007ffff54b639e in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#30 0x00007ffff54b81b1 in  () at /usr/lib/libglib-2.0.so.0
#31 0x00007ffff54b81f1 in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#32 0x00007ffff6a1eb13 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#33 0x00007ffff69c583c in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#34 0x00007ffff69cd676 in QCoreApplication::exec() () at /usr/lib/libQt5Core.so.5
#35 0x00005555555c0b7e in main(int, char**) (argc=1, argv=0x7fffffffe358) at /home/eike/github/keepassxc/src/main.cpp:156


```

Please let me know how I can help you to further isolate this error so it can be fixed.

## Debug Info
KeePassXC - Version 2.5.1
Revision: 0fd8836

Qt 5.13.2
Debugging mode is enabled.

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 5.4.6-arch1-1

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.5

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: 5.4.6-arch1-1

**Comment by phoerious** [comment] 2019-12-24 16:09
Duplicate of #3933.

**Closed by phoerious** 2019-12-24 16:09 UTC
Labels: duplicate
