### ISSUE TITLE
Keepass XC Systray Greyed-Out but Not Closing on Quit

### ISSUE THREAD

**Issue by XyjpcpXNF6UGaQ** [keepassxreboot/keepassxc#4143] opened 2020-01-09 15:27 UTC
The problem is one of Keepass XC remaining greyed-out, but not exiting from the systray, in Windows 7 x64 after selecting Quit through right-click context selection, even if the user logs out and back in again or if the computer is put into Sleep mode.

This should not happen, is happening in 2.5.2, and was not happening prior to 2.5.1. The problem does not happen all the time, but I have been unable to determine a pattern to this.

KeePassXC - Version 2.5.2
Revision: 62cda9d

Qt 5.13.2
Debugging mode is disabled.

Operating system: Windows 7 SP 1 (6.1)
CPU architecture: x86_64
Kernel: winnt 6.1.7601

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by droidmonkey** [comment] 2020-01-09 16:01
Duplicate of #4079

**Closed by droidmonkey** 2020-01-09 16:01 UTC
Labels: bug
