### ISSUE TITLE
Docs: Trouble using KeePassXC with Dropbox

### ISSUE THREAD

**Issue by richb-hanover** [keepassxreboot/keepassxc#1217] opened 2017-11-23 14:13 UTC
I'm having trouble using KeePassXC. The [FAQ](https://keepassxc.org/docs#faq-cloudsync) leads me to believe that I can simply place the database in a Dropbox folder and it will work fine.

> **Q: Why is there no cloud synchronization feature built into KeePassXC?**
> A: Cloud synchronization with Dropbox, Google Drive, OneDrive, Nextcloud etc. can be easily accomplished by simply storing your KeePassXC database inside your shared cloud folder and letting your desktop synchronization client do the rest. We prefer this approach, because it is simple, not tied to a specific cloud provider and keeps the complexity of our code low. 

## Expected Behavior

From the above description, I was hopeful that everything would "just work". Specifically, I was hoping I could open the same database (stored on Dropbox) with KeePassXC on two computers, and they would take turns reading/updating the database.

## Current Behavior

There are several symptoms of failure to work well with a database on a shared folder:

1. When opening the database from the second computer, I am given a choice of Open/Open read-only/Cancel.

2. Adding an entry and clicking Save gives a message, "Writing to the database failed. The process cannot access the file because it is being used by another process."

3. My Dropbox folder has many files named "my-database-file.kdbx.X#####" as well as "my-database-file.kdbx.lock"

## Possible Solution

My suspicion is that it's not possible to have two computers with concurrent read/write access to the file. Since referring to passwords is the common operation, and updating the passwords is relatively uncommon, I wonder if this could documented as a work-around:

1. Set up both KeePassXC instances to disconnect from the database after a couple minutes
2. Open the database on the first computer
3. Attempt to open the database on the second computer. If it's still being used by the first computer, open the database read-only.
4. Wait, or talk to the other person if you need to add/update a password.

## Steps to Reproduce (for bugs)

1. See above.
2.
3.
4.

## Debug Info

KeePassXC - 2.2.2 - Win10
Revision: REVISION

Libraries:
- LIBS

Operating system: Win10
CPU architecture: 32-bit & 64-bit 
Kernel: KERNEL

Enabled extensions:
- EXTENSIONS

**Comment by droidmonkey** [comment] 2017-11-23 16:04
This is a known issue due to the way Dropbox locks files when syncing. For whatever reason I never experience this issue with Google Drive Sync or OneDrive. Duplicate of #604 and #197.

**Closed by droidmonkey** 2017-11-23 16:04 UTC

**Comment by onomori** [comment] 2017-11-23 16:14
I've been encountering this while trying to setup KeepassXC with dropbox earlier. The issue regarding the file being used by another process is caused by Dropbox still "using the file". You have to pause syncing when you're saving. It should free it up and enable you to save the db. 

You can get around the "my-database-file.kdbx.lock" being synced by doing this: https://superuser.com/questions/469776/how-to-exclude-files-not-folders-from-dropbox-sync

Basically, you 
1. pause dropbox syncing 
2. close keepassxc. the .lock file should disappear
3. make a folder called "my-database-file.kdbx.lock". 
4. Then in Dropbox client (I'm assuming you have the windows 1 installed) go to preferences > sync > selective sync, uncheck that folder (my-database-file.kdbx.lock) to disable it from syncing. 
5. You can then delete the folder and once you turn syncing on again and the file comes up, it should have the Dropbox minus icon meaning it's excluded from the sync.

Not sure how to deal with the randomly-lettered extensions. I'm not sure where they're coming from either.

**Comment by richb-hanover** [comment] 2017-11-23 17:28
> This is a known issue due to the way Dropbox locks files when syncing. For whatever reason I never experience this issue with Google Drive Sync or OneDrive. Duplicate of #604 and #197.

Thanks for this speedy response. 

1. Would it make sense to remove "Dropbox" from the list in the FAQ? (It was first in the list of cloud sync apps, and that made me wonder what I was doing wrong.)
2. Is the procedure described in *Possible Solution* (in the OP) a good workaround?

Thanks again.

**Comment by phoerious** [comment] 2017-11-23 17:53
Dropbox has always worked fine for me, although I was primarily using it on Linux, while Windows was mostly read-only. So this is only a problem on Windows.
