### ISSUE TITLE
#accounttypeconcept – Add Multiple URLs to a Set of Entrees by defining Urls for Tags 

### ISSUE THREAD

**Issue by b3nks** [keepassxreboot/keepassxc#11087] opened 2024-07-20 11:42 UTC
## Summary
Some Websites use multiple URLs for their login. Adding the additional URLs to each and every Account Entree for all the accounts you store in the Browser Integration Field Additional URLs, to make it appear in the browser with KeePassXC-Browser, is not convenient e.g. if the url changes. Introducing an Account Type Concept would be helpful.

## Example
Say you have 40 MS Accounts managed in KeepassXC.  MS adds another URL to login. You have to click every KeepassXC Entree to add the url with lots of clicks to make it work in your Browser.

## Proposal
Introduce a possibilility to add URLs recognized by KeePassXC-Browser, to multiple Entrees but not individually.
This could be done via tags, that can define and hold the URLs for multiple Entrees at one convenient spot.
A tag "microsoft" could hold:

- https://login.microsoftonline.com/
- https://admin.microsoft.com/
- https://login.microsoft.com/
- ...

## Context
KeePassXC-Browser Version 1.9.1.1

Debian 12.5 bookworm
Kernel 6.1.0-21-amd64 auf x86_64
Desktop: GNOME GNOME Shell 43.9
Windowing System: x11

**Comment by droidmonkey** [comment] 2024-07-20 12:24
Duplicate of #1314

**Closed as not planned by droidmonkey** 2024-07-20 12:24 UTC
Labels: duplicate

**Comment by b3nks** [comment] 2024-07-23 13:17
Hi @droidmonkey - Thanks for having a look at my suggestion. It was not thought as a multi edit as suggested in #1314 but as setting the URLs once for a Tag not for each entree.
