### ISSUE TITLE
KeePassXC becomes randomly unresponsive on Windows 11

### ISSUE THREAD

**Issue by sunstep** [keepassxreboot/keepassxc#8685] opened 2022-10-27 21:05 UTC
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

I can't really say much about this issue, I have no idea how it happens, but this has bothered me multiple times. I have ignored it all the times until this time when I decided to record it and report it here. In short, the program just becomes randomly unresponsive and I have no clue how it happens.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Keep KeePassXC running for a long period (4 hours?)
2. Try to use KeePass and find out it's being unresponsive again.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
KeePass is supposed to be responding to my clicks. 

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
It's not responding to my clicks. Refer to this video that I recorded: *Removed by the original thread poster for privacy reasons*

## Context
[NOTE]: # ( Give us any additional information you may have. )
There is nothing that I can add, except for that I am sorry for not being able to tell much about the issue, I just wanted to report it. You may close the issue report if it's not meeting the guidelines.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.3
Revision: d8483d3
Operating system: Windows 10 Version 2009 (It's actually Windows 11, but it's reporting Windows 10)

[NOTE]: # ( Pick choices based on your environment )
ACTUAL Operating System: Windows 11

**Comment by droidmonkey** [comment] 2022-10-27 21:11
It's not unresponsive, there is a modal dialog that must be closed to interact with the main application. Do you have multiple monitors? You may have a browser access dialog popped up on your other monitor you need to close. 

BTW an unresponsive application will have a gray overlay and have the spinning wheel mouse icon. That is done by windows itself to indicate the gui is not responding to input. That is not the case in your video.

**Comment by sunstep** [comment] 2022-10-27 22:58
I have only one monitor. 

"You may have a browser access dialog popped up on your other monitor you need to close."

I will keep an eye on it if it happens again.

**Comment by achernyakevich-sc** [comment] 2022-10-28 16:34
@droidmonkey There is another case I reproduced Windows 10 and 11 (fingerprints DB unlocking activated).

Sporadically when KeepassXC-browser web-extension (Firefox or Edge) call reload of locked KeepassXC it show popup window but after pressing there Unlock fingerprint confirmation dialog is not called, KeepassXC window can be closed but KeepassXC stop to work. If KeepassXC closed by Ctrl+Q it remove KeepassXC window but process stay running and prevent working of newly run instance.

**Comment by sunstep** [comment] 2022-10-29 13:40
It just happened again, I checked all my browser tabs and I did not find anything from KeePass in my browser. In fact, it even wasn't connected to KeePass in the first place for some reason. I had to reload it for it to connect to KeePass again.

**Comment by Tidone** [comment] 2022-10-29 16:59
Hi, I don't know if this is the same issue, but I can reproduce the unresponsive window with these steps:
1. Initial setup: Close all browser windows, unlock the database and close the keepass window again
2. Open a browser and go to google, or any other website with a textbox
3. Right-click on the textbox, go to KeepassXC-Browser -> Show Password Generator
4. Close the Password generator by clicking on **X**
    - Do not close it with the **Close** button!
5. Open KeepassXC, which is now unresponsive

This only happens if you close the password generator with the X. If you click on the Close button KeepassXC keeps working normally.

Also, by "unresponsive" I mean that the KeepassXC window is displayed normally but if you click on anything it won't react, and Windows plays the error-sound as if there were a modal dialog in focus waiting for user-input.

**Comment by michaelk83** [comment] 2022-10-29 17:44
@Tidone see #7952, probably not the same as OP.

@sunstep Did you check for hidden modal dialogs *outside* of the browser? Possibly hidden behind some other window for whatever reason. Try minimizing and unminimizing KeePassXC, or moving windows around to see what's behind them.

**Comment by sunstep** [comment] 2022-10-29 18:25
I'm quite certain that it is impossible for me to minimize Keepass when it's in the unresponsive state (see video). But the next time it happens, I'll try to close as many programs and see if I can find anything.

**Comment by michaelk83** [comment] 2022-10-29 18:43
Maybe try right-clicking the taskbar entry for KeePassXC, and see if you have a minimize option there.

**Comment by sunstep** [comment] 2022-10-30 16:33
I don't see a minimize option when right-clicking the taskbar icon.

**Comment by droidmonkey** [comment] 2022-10-30 16:58
Can you use a snapshot build from https://snapshot.keepassxc.org and when it does freeze go to task manager and create a dump: 
![image](https://user-images.githubusercontent.com/2809491/198891251-cd0ec7c5-3ac4-4076-92b1-66692b3ceb1f.png)

We recommend doing this with a dummy database, you can email a link to the file to team@keepassxc.org.

**Comment by sunstep** [comment] 2022-10-30 17:35
Alright, I have installed it, I will update this thread if I send an email with the dump file.

**Comment by sunstep** [comment] 2022-11-13 19:14
I have my suspicions that this bug does not seem to happen on KeePassXC 2.8.0 snapshot. I have the latest regular version installed and the latest snapshot version. When I keep the regular version running, the bug happens, I think I managed to make it happen twice already on the regular version, while having both versions installed. But I can't seem to get the bug on the snapshot version. Even with long computer sessions. I don't want to confirm anything yet, but perhaps it is fixed in 2.8.0?

**Comment by droidmonkey** [comment] 2022-11-13 19:20
There are no appreciable code differences between the two

**Comment by fralorenz** [comment] 2022-11-21 08:35
Hi, I also get this issue quite often (2.7.4, Win 10, 2 screens). When I try to right-click into the dialog I can see the clicks register on totally different screen locations (the context menue apears somewhere to the upper left). I tried setting the Windows text scaling to 100% and it seems to have fixed the issue, even after I set it back to my usual 125%.

**Comment by redtreetop** [comment] 2022-11-21 14:21
I also have this issue, same as above
2 displays scaled at 125%
when minimized and then bring back, i can not click on any menu items/menus unless i move mouse pointer to a totally different position. it seems to be something to do with scaling i believe
version 2.7.4

**Comment by droidmonkey** [comment] 2022-11-21 14:34
Likely related to the qt bug affecting macos as well, sumilar problems with window rendering.

**Comment by JohnLGalt** [comment] 2022-11-21 17:14
> It's not unresponsive, there is a modal dialog that must be closed to interact with the main application. Do you have multiple monitors? You may have a browser access dialog popped up on your other monitor you need to close.
> 
> BTW an unresponsive application will have a gray overlay and have the spinning wheel mouse icon. That is done by windows itself to indicate the gui is not responding to input. That is not the case in your video.

Interesting, I've noticed this as well for a while now, in that I cannot click on the window in any dialog / test entry field anywhere, it is fully unresponsive - **until I click the title bar of KPXC.** The main reason I have not reported it is that I am typically running the latest snapshot, from a folder that I extract the .ZIP version of the latest snapshot, at any given moment. 

Would clicking on the title bar allow KPXC to negate the need to close said modal dialog? If so, then this could be a real possibility - otherwise, I think something else is getting in the way, and I have tons of TSR software at any given moment, so tracing it down would be tedious, and thus I've not reported it. But it does happen on the snapshot edition for me, though I've just realized that I have the stable also installed on my system as well (not portable but actual install), so I'm uninstalling it to confirm if this issue continues or not.

I'm 99% sure it is the snapshot because of the warning that shows across the top reminding me that I'm using a developmental snapshot, but I do tend to hide that on every restart of the app, so I'll be more vigilant.

If it is a QT bug, though - sigh. Wouldn't surprise me that Windows 11 22H2 is breaking QT in some way....

**Comment by droidmonkey** [comment] 2022-11-21 18:10
I have not experienced this behavior ever so unfortunately cannot offer any fixes or ideas

**Comment by JohnLGalt** [comment] 2022-11-22 15:00
I'll keep trying to actively test for it to see if I can get a definite methodology to recreate it then. I honestly thought it was either the Microsoft PowerToys for Win11, or some other background app, but now that someone else has also mentioned it, I'll explore more.

**Comment by achernyakevich-sc** [comment] 2022-11-22 15:53
As I wrote earlier/above I have experienced similar freezing for Windows X. Mainly when KeepassXC Browser try to force reopening KeepassXC DB through activation of fingerprints checking. Problem appeared starting KeepassXC 2.7.3.

What is similar with latest comments in this issue - I have two displays, one is 150% scaled and other one is 200% scaled. Maybe problem is really somehow related to positioning of some modal window out of visible area...

**Comment by sunstep** [comment] 2022-11-27 15:52
I honestly have no clue how to reproduce this, it doesn't seem to happen on 2.8.0 snapshot. Very weird. I'm considering switching from windows to Linux, so I probably can't keep going after this problem.

**Comment by m4ksio** [comment] 2022-12-04 04:27
I have similar problem but cannot really find a reliable way to trigger it.

However, what seems to help is when I lock the database from the browser extension. DB locks and the KeePass window is responsible again.

Interestingly, recently I had this problem happen while I had unsaved edits and locking the database "revived" the window and showed dialogue about unsaved changes.

**Comment by redtreetop** [comment] 2022-12-04 17:28
here is a screen shot showing my issue if the same as others?

after a time being minimised and then maximising the window you can see the text and box work no longer fills the window
and you can no longer click on anything

this is showing on display1 - which is a dell 4k monitor scaled to 125%
for ref - display2 - dell 2k monitor - scale 100%

![image](https://user-images.githubusercontent.com/67707128/205505832-b510572d-048f-4b05-8492-3bde7b7d529a.png)

**Comment by droidmonkey** [comment] 2022-12-04 17:45
That seems to be an entirely different issue and likely caused by switching display scaling when you unplug and plug a monitor. This would be a qt bug though, not Keepassxc.

**Comment by redtreetop** [comment] 2022-12-05 10:45
just to add...

no display swapping (or unplugging) its a two monitor setup.
monitors never sleep
KeePassXC simply minimised then maximised say 10+ mins later and above pic is result
KeePassXC always on same display

**Comment by sunstep** [comment] 2022-12-10 00:21
I think I figured it out. I am pretty certain that the issue is caused by the save changes pop up. Furthermore, I recently reinstalled my OS and since then the pop-up actually shows itself. Now the only mystery left is why does this pop up show in the first place? I did not make any changes to my account database. Not from my browser, not from my phone or any other devices. It's pretty odd.

When I click yes to save. It gives me another pop-up:

Title: Disable safe saves?

KeePassXC has failed to save the database multiple times. This is likely caused by file sync services holding a lock on the safe file. Disable safe saves and try again?   

I am pretty sure Syncthing has something to do with this since I use it, however I, once again, did not make any changes from any devices. Why would Syncthing randomly do this? And could the second pop-up have something to do with this issue. I quickly checked the folder with the database in it, I did not find any Syncthing conflict files or whatsoever. 

Another possibility is that the second pop-up appeared because I did not have my YubiKey inserted when I clicked yes to save. I wanted to insert it after clicking yes, and then the second pop-up appeared, but that does not answer why it asks to save my database in the first place.

I think this could have something to do with the fact that I sometimes remove my YubiKey from my PC, but I am not certain.

**Comment by achernyakevich-sc** [comment] 2022-12-10 09:22
It looks like hypotheses that problem caused by changes saving routine has foundation. I just got confirmation of it. In my case when window hang up and tree and table were gray I have found that toolbar is not. So I clicked Save button. I got red alert that KeepassXC can't save because saving is in progress.

I'm not sure that I described my case in all details. I will recheck next time when it will hang up. But it really caused feeling that KeepassXC hanged up and I can't do anything with it. So at the end I killed it in the Task Manager and started new copy.

**Comment by droidmonkey** [comment] 2022-12-10 13:25
@achernyakevich-sc make sure you are running 2.7.4. That is a different problem I fixed already: https://github.com/keepassxreboot/keepassxc/pull/8606

**Comment by achernyakevich-sc** [comment] 2022-12-11 11:25
> @achernyakevich-sc make sure you are running 2.7.4. That is a different problem I fixed already: #8606

@droidmonkey I use exactly 2.7.4.

**Comment by JohnLGalt** [comment] 2022-12-11 20:04
> > It's not unresponsive, there is a modal dialog that must be closed to interact with the main application. Do you have multiple monitors? You may have a browser access dialog popped up on your other monitor you need to close.
> > BTW an unresponsive application will have a gray overlay and have the spinning wheel mouse icon. That is done by windows itself to indicate the gui is not responding to input. That is not the case in your video.
> 
> Interesting, I've noticed this as well for a while now, in that I cannot click on the window in any dialog / test entry field anywhere, it is fully unresponsive - **until I click the title bar of KPXC.** The main reason I have not reported it is that I am typically running the latest snapshot, from a folder that I extract the .ZIP version of the latest snapshot, at any given moment.
> 
> Would clicking on the title bar allow KPXC to negate the need to close said modal dialog? If so, then this could be a real possibility - otherwise, I think something else is getting in the way, and I have tons of TSR software at any given moment, so tracing it down would be tedious, and thus I've not reported it. But it does happen on the snapshot edition for me, though I've just realized that I have the stable also installed on my system as well (not portable but actual install), so I'm uninstalling it to confirm if this issue continues or not.
> 
> I'm 99% sure it is the snapshot because of the warning that shows across the top reminding me that I'm using a developmental snapshot, but I do tend to hide that on every restart of the app, so I'll be more vigilant.
> 
> If it is a QT bug, though - sigh. Wouldn't surprise me that Windows 11 22H2 is breaking QT in some way....

For me, uninstalling the stable release and only running snapshot seems to have cleared the issue on my end, so it seems I was invariably running stable edition and had not realized it. And perhaps that was the actual problem, as the stable release was installed on my system, and the snapshot I use via portable directory,  and it may very well have been causing idiosyncrasies that I was not aware of.

@droidmonkey Could having both installs be a way to simulate this possible issue with saves going crazy, in that stable tries to save while snapshot is open (possibly in the background / hidden)?

**Comment by droidmonkey** [comment] 2022-12-11 22:08
I test with multiple instances (debug, stable, portable) running at the same time all pointing to the same file. It's how I developed the file change detection behavior.

**Comment by racic** [comment] 2023-01-04 17:52
I encountered exact same issue in version 2.7.4. The main window behaves as if there is a modal window above it and denies clicks. But there's no modal window to be seen. I work exclusively on a exteral monitor, the built-in laptop one is disabled.

**Comment by sunstep** [comment] 2023-01-04 19:50
For me, it does not happen anymore since I clean reinstalled my OS. Chances are that the issue is not with KeePassXC, but that something else in the OS causes it. I have no clue what causes it. 

> Can you use a snapshot build from https://snapshot.keepassxc.org and when it does freeze go to task manager and create a dump: ![image](https://user-images.githubusercontent.com/2809491/198891251-cd0ec7c5-3ac4-4076-92b1-66692b3ceb1f.png)
> 
> We recommend doing this with a dummy database, you can email a link to the file to [team@keepassxc.org](mailto:team@keepassxc.org).

If anyone could do what this quote says, it would help them understand the issue better.

**Comment by JohnLGalt** [comment] 2023-01-05 15:18
I recently reinstalled as well, and it has happened exactly once since then.

For me, though, it's not as if an overlay is blocking the main window, as I *can* interact with certain elements withing the main screen, but some elements refuse to accept any mouse input - until I grab the title bar and move the window slightly. Then all functionality is restored.

**Comment by MitchellBauer** [comment] 2023-01-30 21:09
Not sure if this helps, but I'm having the unresponsive issue in two scenarios. First if the display gets locked, or turned off. Second is if the computer goes to sleep. I've noticed that Windows 10 and 11 can be a little bit buggy with saved states if the computer wakes up from a sleep. Example browsers may not function correctly, or some applications that require internet no longer can see the internet (Steam). I get around this by always shutting down, which brings up another bug that I've seen in windows where I know I hit shutdown button, but the computer actually just goes to sleep. Note, hibernation is turned off. I now resort to command line shutdowns. Keepass, and every other program always functions correctly upon boot up.

I've seen this saved state issue throughout the organization that I manage as well.

One possible solution, is under the Keepass Settings - General - User Interface (At the bottom), "checking the minimize instead of app exit", "show a system tray icon", "hide window to system tray when minimized"

The only software that I have seen fail from taskbar minimization is Corsair's iCue software. Changing how Windows handles KeePass in the background and restores the Window might get us through this rough patch in restoration state reliability.

**Comment by webstarspro** [comment] 2023-02-02 11:22
> here is a screen shot showing my issue if the same as others?
> 
> after a time being minimised and then maximising the window you can see the text and box work no longer fills the window and you can no longer click on anything
> 
> this is showing on display1 - which is a dell 4k monitor scaled to 125% for ref - display2 - dell 2k monitor - scale 100%
> 
> ![image](https://user-images.githubusercontent.com/67707128/205505832-b510572d-048f-4b05-8492-3bde7b7d529a.png)

I've been experiencing the same problem for months.
After a few hours keepassXC inactivity the app is frozen.
It's not possible to take a screenshot of keepassxc.
Its possible to click in the search field but you can't search anything.

![1675180652494](https://user-images.githubusercontent.com/57489251/216311167-3ff51a76-2a77-4d94-8d3e-c73cb808d184.jpg)

If I click on the border of the app and try to strech it.....a piece of the keepassxc  is visually duplicated.

**Comment by MitchellBauer** [comment] 2023-02-06 22:43
Might have fixed it for myself. Previous taskbar minimization settings didn't do anything. Looks like the problem was due to the DPI scaling in windows. 3440 x 1440 display, 100% is just too small, always operated at 125%. 

Find your qt.conf file in KeepassXC. Open it up and add line WindowsArguments = dpiawareness=1.

In my case I have darkmode enabled. So my qt.confg looks like the following. Supposedly, all you have to do is add your argument at the end with a space.

[Platforms]
WindowsArguments = darkmode=1 dpiawareness=1

As a side note, the unresponsivness would always happen after a display shut off or computer going to sleep.

**Comment by droidmonkey** [comment] 2023-02-06 23:31
That's interesting, we can add that to the default distro

**Comment by webstarspro** [comment] 2023-02-08 13:46
> Might have fixed it for myself. Previous taskbar minimization settings didn't do anything. Looks like the problem was due to the DPI scaling in windows. 3440 x 1440 display, 100% is just too small, always operated at 125%.
> 
> Find your qt.conf file in KeepassXC. Open it up and add line WindowsArguments = dpiawareness=1.
> 
> In my case I have darkmode enabled. So my qt.confg looks like the following. Supposedly, all you have to do is add your argument at the end with a space.
> 
> [Platforms] WindowsArguments = darkmode=1 dpiawareness=1
> 
> As a side note, the unresponsivness would always happen after a display shut off or computer going to sleep.

I did this in my qt.conf file:
[Platforms]
WindowsArguments = darkmode=1 dpiawareness=1


but it doesn't help.
After some time the app look like this again:

![1675863638567](https://user-images.githubusercontent.com/57489251/217547430-12ab312b-489c-4d69-8753-d4db2babb610.jpg)

**Comment by Terramoto** [comment] 2023-02-08 16:02
Been following this issue for a while because i had the same issue. I no longer seem to have this issue, not sure if it's because i have it set to lock the database after a couple minutes of inactivity. So maybe the lock database resets something that prevents it from locking, does anyone have this issue without the browser extension?

**Comment by droidmonkey** [comment] 2023-05-02 20:25
I am closing this since I can never reproduce the behavior. There are other issues describing similar behavior (KeePassXC is stuck in background without notification tray icon). Without being able to reproduce it there is nothing I can do to solve it unfortunately.

**Closed as completed by droidmonkey** 2023-05-02 20:25 UTC
Labels: not reproducible, platform: Windows

**Comment by achernyakevich-sc** [comment] 2023-05-22 14:34
I could reproduce it for KeepassXC 2.7.4 (portable) on Windows 10 + Firefox + KeepassXC-browser Firefox Add-On.

Last week I had upgraded KeepassXC to 2.7.5 (portable) and for 7 days have not reproduced this issue. Probably it is gone as a side effect of other fixes. I will let know if I still will reproduce the same issue for 2.7.5.

**Comment by 4e576rt8uh9ij9okp** [comment] 2023-12-06 18:24
> It's not unresponsive, there is a modal dialog that must be closed to interact with the main application. Do you have multiple monitors? You may have a browser access dialog popped up on your other monitor you need to close.
> 
> BTW an unresponsive application will have a gray overlay and have the spinning wheel mouse icon. That is done by windows itself to indicate the gui is not responding to input. That is not the case in your video.

I want to mention this too, indeed there was the Password Generator open, I closed it with an X i assume or I didn't close at all.
Meaning it either MUST be closed with the close button or it didn't show when ALT+TAB or hovering over the task tab.

I wish this would be fixed.

**Comment by basselworkforce** [comment] 2024-02-05 19:14
As a quick workaround: re-open the password generator dialog from your browser and then click on Close this time instead of X

**Comment by dgnuff** [comment] 2024-02-25 04:01
I know this is closed, but I'm getting it 100% of the time with a fresh install of both the operating system and the latest KeePassXC on a Windows 11 system.  KeePass hangs right at startup, with no icon in the notification area, but there is an entry for it in the taskbar.  However hovering over that entry shows just a blue rectangle as the hover preview, and no window appears if I click.

Using Sysinternals Process Explorer to try and bring the window to front has no effect either.  I'm fairly certain it's stuck waiting for input, because Process Eexplorer shows it using almost no CPU time at all.

The one useful thing I can add is that I then downloaded the latest snapshot as of 2024-2-25 02:00 UTC ( 2024-2-24, 18:00H -08:00), downloaded the PDB file as well, and cloned the github repo.

With that lot, I was able to attach Visual Studio to the hung process, and create a full dump file.  That can be downloaded from https://scruffy.org just go there and look for KeePassXC.dmp.

This does look to be a QT bug.  The main thread has made a call into `msgBox.exec();` at line 129 of MessageBox.cpp, and not returned.  Judging by the look of the assembly listing, that's a call into one of the QT dlls, and is therefore not debuggable with what I have.

**Comment by droidmonkey** [comment] 2024-02-25 04:15
@dgnuff sounds like you are accessing the computer remotely and running into screenshot security: https://keepassxc.org/docs/KeePassXC_UserGuide#_screenshot_security

**Comment by dgnuff** [comment] 2024-02-25 06:53
@droidmonkey  Yes - that would be it.  I'd forgotten that I'm accessing that system via a VNC connection.  I'll add "--allow-screencapture" to the shortcut that launches it.  That should do the trick.

Thanks so much for the help.

**Comment by achernyakevich-sc** [comment] 2024-03-14 20:13
For version 2.7.6 I could more or less stable reproduce unresponsiveness by the following scenario:

* Environment: Windows 10 + KeepassXC 2.7.6 portable, Firefox + KeepassXC-browser.
* Scenario:
  * Navigate in any web application form for updating password.
  * In the browser press Alt+Shift+G that call popping up of KeepassXC's Generate Password window.
  * Regenerate password several times in the windows (Refresh button or Ctrl+R shortcut).
  * Copy generated password and close KeepassXC's Generate Password window.
  * Fill new password and save it for the account.
  * Login in web application using new password.
  * When KeepassXC-browser propose to add/save new account/password - press add/update button to save it.
  * KeepassXC updated but application become unresponsive (though window could be moved to foreground or closed by context menu of tray icon).

I use KeepassXC 2.7.7 for about 5 days, added few new accounts using the described scenario and could not reproduce the problem. Probably the problem is gone in the version 2.7.7.
