### ISSUE TITLE
With autotype, the @ sign is changed to " sometimes

### ISSUE THREAD

**Issue by sxe** [keepassxreboot/keepassxc#2880] opened 2019-03-26 08:19 UTC
## Expected Behavior
When I am on a website, I have a username / password combination for, I expect that the auto type feature puts these correctly into the username and password fields. 

## Current Behavior
Sometimes and I am not sure when exactly this happens keepassxc converts the @ sign to a "  in my username and password when invoking auto type by pressing ctrl+shift+a. I tested it in firefox and a text editor to make sure it's not firefoxes fault.

Example: myemail@test.com will will look like this: myemail"test.com 

I can fix this by restarting keepassxc (so far this worked 100% of the time in like 6 cases) 

## Context
I have keepassxc in my autostart list. It gets started when I boot my PC.  This might have something to do with it, cause so far I never noticed this when starting it manually.

## Debug Info
KeePassXC - Version 2.4.0
Revision: c51752d

Libraries:
- Qt 5.12.2
- libgcrypt 1.8.4

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 5.0.4-arch1-1-ARCH

Enabled extensions:
- Auto-Type
- Browser Integration

## OS
I am running KDE, see the rest under Debug Info

Cheers

**Comment by droidmonkey** [comment] 2019-03-26 11:57
Do you switch keyboard layouts, perhaps from one language to another, while KPXC is running?

**Comment by sxe** [comment] 2019-03-26 13:15
HI @droidmonkey no I don't. At least not manually.
The workflow is like this: System boot > KPXC is up and running > I enter my DB password > Starting Firefox > auto type
And that's when the problem occurs.

**Comment by droidmonkey** [comment] 2019-03-26 13:29
Sometime similar to this has been reported before, but I cannot find the issue right now.

**Comment by phoerious** [comment] 2019-03-26 13:31
Found it. Duplicate of #324.

**Closed by phoerious** 2019-03-26 13:31 UTC
Labels: bug

**Comment by sxe** [comment] 2019-03-26 15:14
ok great, I coudn't find am already existing bug report. Sorry for that.

Do you need any further information?
If not I will keep it at that. The other ticket seems to have a lot of information already.

Cheers

**Comment by phoerious** [comment] 2019-03-26 15:18
If you have it, sure. You can see that the issue is pretty old and we get occasional reports of it. So we know that there is an issue, but none of us was ever able to reproduce it. We believe it's a Qt bug or some general configuration or Xorg issue.

**Comment by sxe** [comment] 2019-03-26 15:49
Well, I don't have anything at hand. I just thought you might need some more debug infos or something. 

The second to last comment from @jtrh in the other thread has a reproducible description on how you can get the bug. I have my system lang set to en_US but numbers and time to de_DE.

> LANG=en_US.UTF-8
> LC_CTYPE="en_US.UTF-8"
> LC_NUMERIC=de_DE.UTF-8
> LC_TIME=de_DE.UTF-8
> LC_COLLATE="en_US.UTF-8"
> LC_MONETARY="en_US.UTF-8"
> LC_MESSAGES="en_US.UTF-8"
> LC_PAPER="en_US.UTF-8"
> LC_NAME="en_US.UTF-8"
> LC_ADDRESS="en_US.UTF-8"
> LC_TELEPHONE="en_US.UTF-8"
> LC_MEASUREMENT="en_US.UTF-8"
> LC_IDENTIFICATION="en_US.UTF-8"
> LC_ALL=

Looks like KPXC is not using the correct language? That's all I have for now. 

Cheers
