### ISSUE TITLE
Search within Notes field

### ISSUE THREAD

**Issue by remcokalf** [keepassxreboot/keepassxc#6998] opened 2021-09-29 09:47 UTC
## Summary
It would be very helpful to be able to search _within_ the Notes field of an entry.

## Context
I use the Notes field a lot to store secure notes and passwords that are related and I need together. 
For example all passwords of a client, related to a project.
These notes can become quite large. Searching within the Notes field, or within the whole entry would speed up finding what you are looking for a lot.

**Comment by droidmonkey** [comment] 2021-09-29 10:10
Duplicate of #4864. I will say based on this and the previous issue, you are using the application wrong such that all the useful features are inaccessible to you. You should have a group for each client and maybe each project. Within that group create all the entries needed each with their own login information. Then you can use Auto-Type and browser extension to automatically retrieve and inject the credentials when needed. You are using the application like an encrypted notepad which is not leveraging the special features we have to make your life easier.

**Closed as completed by droidmonkey** 2021-09-29 10:10 UTC
Labels: duplicate

**Comment by remcokalf** [comment] 2021-09-29 10:50
Seriously? "You are using the application wrong"? 
I find KeepassXC very useful, exactly how I use it. You can't dictate which features a user uses and finds useful. 

"You are using the application like an encrypted notepad"
For me it's a mix between what you describe and what I describe above. And yes partly I use it exactly like that, an encrypted notepad. And that is making my life a lot easier.

**Comment by droidmonkey** [comment] 2021-09-29 11:05
You do as you please. Just letting you know how to leverage our other useful features...

**Comment by remcokalf** [comment] 2021-09-29 11:40
I appreciate that. And I will look into it and see what I am missing out on. But some of those key features don't work for me like browser extension, which does not work in Safari. I reacted to your remark about how I _should_ use the app. Users might use an application not as you intended, for their own good reasons. 

I chose KeepassXC years ago specifically for the encrypted Notes feature, not for the rest. For me, and I suspect other users too - encrypted notes are a lifesaver in everyday life, and that I can use them together with separate user/pw entries. There is much more to keep safe than single user/pw entries. I might have consecutive passwords for some projects together with notes for each of them, I'd rather copy 4 times and paste consecutively with a smart paste app than having to click open a group and each entry separately which is very cumbersome. Also, navigating by search is much faster than looking through entries if you have hundreds or more. Being able to search again when having only looked at (not edited) an entry would speed things up even more. And searching within notes too. I get that this is not your intended use or you use it differently. Anyway, this was my attempt to make something I have been using everyday for years better. Good luck.

**Comment by droidmonkey** [comment] 2021-09-29 12:53
You should check out Auto-Type, copy pasting credentials is generally not a good idea. https://keepassxc.org/docs/KeePassXC_UserGuide.html#_auto_type

**Comment by remcokalf** [comment] 2021-09-29 14:01
Will check it out. Thanks

**Comment by unknown-address** [comment] 2021-09-29 19:23
@droidmonkey 
just out of curiosity, what would you recommend to use: `Auto-Type` or `KeePassXC browser extension`? Are there any pros/cons ?

**Comment by phoerious** [comment] 2021-09-29 20:27
Browser for anything that lives inside your browser, Auto-Type for things outside your browser.

**Comment by tredondo** [comment] 2021-10-07 20:09
I think we got into the "you're using it wrong" argument due to the wrong example.

I've given what I think are better examples in [the issue this one duplicates](https://github.com/keepassxreboot/keepassxc/issues/4864#issuecomment-938118252) (though I feel this issue is much better phrased).

**Comment by Dees7** [comment] 2026-06-22 17:59
I have waited a lot ) and now made a fork and added  search bar for notes, because I use love KepassXC and use it to keep secure notes too and I really need search. I have some very big notes.

Also (very annoy me):
- fixed home/end in one-line QLineEdit 
- fixed del in tag

@droidmonkey why don't you want add this feature? look like it needed many meapole.
I don't know C and done it with claude. I didn't test all but macos. It is cause I don't make PR. 
It looks good and useful. Please consider adding this feature. 

https://github.com/Dees7/keepassxc/commits/fix/macos-lineedit-home-end-tags-del-add-search-notes

<img width="1286" height="915" alt="Image" src="https://github.com/user-attachments/assets/0b7e3f4e-6e05-4cdf-af91-852bfd3019a0" />
