### ISSUE TITLE
Syncthing: simultaneous edits to entry - changes overwritten instead of being merged

### ISSUE THREAD

**Issue by Jasha10** [keepassxreboot/keepassxc#10225] opened 2024-01-23 18:07 UTC
Using a file syncing service (syncthing), changes on computerA can be overwritten
by changes on computerB rather than being merged. Specifically, if computerB starts
editing a given entry before computerA saves changes to the database, computerB
may clobber computerA's changes.

## To Reproduce

At a high level, the bug can be reproduced like this:
1. Open Entry1 for editing on computerB
2. Edit Entry1 on computerA & save. Changes synced via syncthing (or dropbox, etc).
3. Finish editing Entry1 on computerB & save. This overwrites the change made on computerA.

Here is a step-by-step:
- On computerA:
    - open keepassxc:
    - create new database: `test_db.kdbx`, saved to a folder synced with syncthing
    - Add new entry:
        - title: "Entry1"
        - Notes: "123"
    - Click OK to save the new entry
- On computerB:
    - wait for syncthing to synchronize `test_db.kdbx`
    - open `test_db.kdbx`, verify that Entry1 is as expected.
    - open Entry1 for editing. Leave Entry1 open and return to computerA
- On computerA:
    - open Entry1 for editing.
    - add "456" to Notes. Full text of Notes now reads "123\n456"
    - Click OK to save the changes to Entry1
- On computerB:
    - wait until syncthing updates `test_db.kdbx` with the updates from computerA
    - Entry1 is still open for editing; Notes reads "123".
    - add "789" to Notes. Full text of Notes now reads "123\n789"
    - Click OK to close Entry1.
- On computerA:
    - once syncthing updates, observe that notes reads "123\n789" and the data "456" is lost.

## Why is this a problem?

This can lead to loss of data. In the example above, the string "456" from computerA is lost.
In real life, I lost some sensitive recovery codes that I'd saved in Notes. Thankfully I was able to regenerate them.

## Workarounds / Best Practices

Do not leave entries open for editing for long periods of time. Only edit entries on one computer at a time.

## How Might This Problem be Solved?

My naive expectation is that keepassxc would do one of the following when I try to save changes to Entry1 on computerB:
- Detect that the database has changed; give an error that the database is conflicted & prevent overwriting the database.
- Detect that the database has changed; back up the changed version of the database to `test_db.kdbx.bak` before overwriting

### Debug Info

KeePassXC - Version 2.7.6
Debugging mode is disabled.
Operating system: Ubuntu 22.04.3 LTS
CPU architecture: x86_64
Kernel: linux 6.5.0-14-generic
Cryptographic libraries:
- Botan 2.19.3

**Comment by droidmonkey** [comment] 2024-01-23 18:36
Duplicate of #8545

**Closed as not planned by droidmonkey** 2024-01-23 18:36 UTC
