### ISSUE TITLE
Auto-Type option no longer present in context menu

### ISSUE THREAD

**Issue by banaanihillo** [keepassxreboot/keepassxc#7566] opened 2022-03-22 09:26 UTC
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
After the update to the 2.7.0 version, the Auto-Type option disappeared from the context menu (the menu that appears when clicking the Menu key while a specific entry is in focus, or "Right Click"). The "Entries" section in the top menu bar does not have that option either. I confirmed via "Edit Entry" that all my entries have the default Auto-Type options: "Enable Auto-Type for this entry" is ticked, and the radio input is set as "Inherit default Auto-Type sequence from the group" (I have not changed those settings myself).

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Update to 2.7.0 (automatically)
2. Move focus to an entry
3. Open up the context menu via the Menu key, or perhaps a mouse right-click

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
The "Auto-Type" option to be present.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
The "Auto-Type" option is not present.

## Context
[NOTE]: # ( Give us any additional information you may have. )
The context menu includes the following items:
- Copy Username
- Copy Password
- Copy Attribute (with "Title" available, and "URL" and "Notes" greyed out)
- TOTP (with "Copy TOTP", "Show TOTP" and "Show QR Code" greyed out, and "Set up TOTP" available)
- Edit Entry
- Clone Entry
- Delete Entry
- New Entry
- Open URL (greyed out)
- Download Favicon (greyed out)

The "Preview Panel" does have an Autotype tab for all entries, and it includes the "Default Sequence" {USERNAME}{TAB}{PASSWORD}{ENTER}. I have not changed this sequence myself for any entry.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.0
Revision: d7a9ef4
Distribution: Snap

Qt 5.15.3
Debugging mode is disabled.

Operating system: Ubuntu Core 20
CPU architecture: x86_64
Kernel: linux 5.14.0-1027-oem

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.12.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux (Ubuntu 20.04 LTS)
Desktop Env: Gnome
Windowing System: X11

**Comment by phoerious** [comment] 2022-03-22 09:43
Duplicate of #7567.

**Closed as completed by phoerious** 2022-03-22 09:43 UTC
Labels: duplicate
