### ISSUE TITLE
URL Resolution not working

### ISSUE THREAD

**Issue by marcelmu** [keepassxreboot/keepassxc#5382] opened 2020-09-04 07:29 UTC
## Overview
After upgrading to 2.6.1 (Windows 64 Bit) resolving entries by the URL is not working anymore. This affects auto-fill as well as the browser integration.

## Steps to Reproduce
1. Upgrade to 2.6.1
2. Use autofill or browser plugin

## Expected Behavior
Entry should be found

## Actual Behavior
When filling in data manually, browser plugin suggest creating a new entry, even though an entry exists.
After Downgrading to 2.6.0 everything works again as expected.

## Context
KeePassXC - 2.6.1
Operating System: Windows 7 64 Bit

**Comment by varjolintu** [comment] 2020-09-04 07:38
Duplicate of https://github.com/keepassxreboot/keepassxc/issues/5299.

**Closed by varjolintu** 2020-09-04 07:38 UTC
Labels: bug

**Comment by marcelmu** [comment] 2020-09-04 08:37
Oh god damnit. How could I miss that?! I'm sorry for the duplicate.
