### ISSUE TITLE
KeePassXC Crashes Upon opening a QuickBooks file

### ISSUE THREAD

**Issue by Linkinwater** [keepassxreboot/keepassxc#8175] opened 2022-06-20 19:41 UTC
## Description
Whenever I open a QuickBooks (QB) file, the KeePassXC window disappears (closes/crashes) with no message or error pop-up.

## Steps to Reproduce
1. Open KeePassXC and unlock the database
2. Copy and paste the password into the QB password box OR use auto-type (same behavior either way)

## Expected Behavior
KeePassXC to remain open and unlocked.

## Actual Behavior
When the QB file loads, the KeePassXC window will disappear.
Reproducibility: 100%

## Context
I usually use QuickBooks Desktop Pro Plus 2022, but I get the same behavior with QuickBooks Premier 2021.
I have tested this on a different system (also running Windows 10) and get the same behavior.
I did not have this issue with the previous version of KeePassXC (2.7.0).
If I manually type the password into QB, ignoring KeePassXC altogether, it does not crash it.

## Debug Info
KeePassXC - Version 2.7.1
Revision: 5916a8f

Qt 5.15.3
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.19044

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.18.1

**Comment by droidmonkey** [comment] 2022-06-20 19:54
We didn't do anything with clipboard code between versions. Try reinstalling keepassxc. Something else is up here.

**Comment by Linkinwater** [comment] 2022-06-20 23:11
I tried reinstalling, but it didn't change anything. It's possible that a QB update that came out at the same time might also be to blame. I'll try testing a few more things and post if I find anything.

**Comment by droidmonkey** [comment] 2022-06-21 00:42
See if any other app on your computer causes this problem with keepassxc. We have had reports of clipboard copying causing a crash but never a crash caused by another app that you (or Auto-Type) are interacting with. Do you have an aggressive antivirus?

**Comment by droidmonkey** [comment] 2022-06-30 11:04
Closing unless a crash dump or further isolation can be determined.

**Closed as not planned by droidmonkey** 2022-06-30 11:04 UTC
Labels: more info needed, platform: Windows, crash :boom:

**Comment by RockyMtnDingo** [comment] 2022-07-11 17:10
Hi, this is happening consistently to me too. How can I generate the proper crash dump for you?

**Comment by droidmonkey** [comment] 2022-07-11 17:28
If you can better describe the circumstances that lead to a crash that would be helpful.

**Comment by RockyMtnDingo** [comment] 2022-07-11 17:34
I'll have usually chrome and keepassXC open, then when I open up Quickbooks, then actually open the company file, keepassXC and chrome half time time will crash. I just updated quickbooks again this morning and it is no longer consistent. Now it seems intermittent.

**Comment by droidmonkey** [comment] 2022-07-11 17:43
I'm not sure how quick books can crash other apps that have nothing to do with it....

Seems like a "common" issue that faults QuickBooks and / or Windows itself:

https://www.reddit.com/r/sysadmin/comments/vlvjsz/has_anyone_else_seen_quickbooks_causing_memory

https://quickbooks.intuit.com/learn-support/en-us/other-questions/google-chrome-browsers-crash-when-quickbooks-desktop-pro-plus/00/890853

**Comment by Linkinwater** [comment] 2022-07-11 23:49
Weird. I use Chrome and have never had problems with QB crashing it.
But I can confirm that a massive QB update came out right about the exact same time that I updated KeePass, so it's very likely they messed something up with that. I've had lots of issues before with QB not playing nice with other software, so I'm not at all hesitant to let them take the blame for this one, too.
I tested with QB Premier 2021, and had no crashing issues. It must just be the 2022 version.

**Comment by RockyMtnDingo** [comment] 2022-07-12 14:31
Yep. That reddit post is exactly what's going on. /user/HeroesBaneAdmin seems like he knows what he's talking about, but I completely reinstalled windows on a device that I have run thorough hardware tests on and it was still happening. Quickbooks support has been absolutely useless. Do you agree with him that you think it's actually chrome and not quickbooks? or do I have to run thru the sysinternals stuff to have an idea?

**Comment by droidmonkey** [comment] 2022-07-12 19:16
There is no way this is on Chrome or KeePassXC or any other application besides Quick Books. Someone proposed that there was broad memory corruption happening and memory sensitive apps (like us) might be more impacted than others. Chrome like enables memory protections as well which makes it more susceptible to corruption errors. At the end of the day, this is clearly being invoked by Quick Books.
