### ISSUE TITLE
[Feature Request] Associate multiple URLs with a single user/password combo

### ISSUE THREAD

**Issue by boconnell** [keepassxreboot/keepassxc#274] opened 2017-02-09 04:23 UTC
## Expected Behavior
In the original Keepass (2), one can create a new entry, with a different title/url, and create basically a soft-link (reference) to another entry's username and password. This would help facilitate Passifox's ability to find the user/pass for a given website without having to manage two entries that will always be shared. I understand this is really an expected behavior with Passifox, but passifox is happy to point out that this can be done in the original Keepass.

## Current Behavior
You can duplicate an entry, but can't have it reference the original automatically.

**Comment by TheZ3ro** [comment] 2017-02-09 07:39
Duplicate of #75

**Comment by droidmonkey** [comment] 2017-02-09 17:48
I disagree that this is a duplicate. This is related to the http plugin, not autotype. My opinion is that http should search attributes for additional urls. That is the more elegant solution than duplicating entries.

**Comment by droidmonkey** [comment] 2017-02-09 17:48
I disagree that this is a duplicate. This is related to the http plugin, not autotype. My opinion is that http should search attributes for additional urls. That is the more elegant solution than duplicating entries.

**Comment by Throne3d** [comment] 2017-02-09 18:55
The only solution I've found in KeePass itself is to duplicate an entry, use references, and change the URL – I searched for it at some point and that was a solution. I'm not sure if that's the only one.

I agree that it would be more elegant to have it search additional attributes, but I think it could be handled by the other issue too.

**Comment by TheZ3ro** [comment] 2017-02-09 19:29
@droidmonkey  #75 is not Autotype but HTTP specific. 
Citing from that issue (the autotype is wrong. The user meant autofill from ChromeIPass)

> Expected Behavior
> On Amazon.ca, I should be able to autotype/fill from ChromeIPass the records from amazon.com, as the u/p combo is stored as {REF:U@I:AMAZON.COM_UUID} and {REF:P@I:AMAZON.COM_UUID}
> 
> Context
> Amazon.com and Amazon.ca both use the same credentials, but as they are using different URLs, they are seen as different sites to Keepass/KeepassX and ChromeIPass. Keepass on Windows manages this by allowing you to create 2+ separate entries, one containing the real values, the other containing a reference via UUID to the first one (http://keepass.info/help/base/fieldrefs.html).

Citing from this Issue
> Current Behavior
> You can duplicate an entry, but can't have it reference the original automatically.

--- 

Both Issue are related to reference between entry. That is useful also beside HTTP or Autotype.
Here KeePass docs http://keepass.info/help/base/fieldrefs.html
Also, by inserting URLs in custom attribute the download favicon will need to be extended to custom attributes too?

**Comment by phoerious** [comment] 2017-02-09 19:51
For autotype, there is no reason at all to have multiple entries, because you can have multiple autotype conditions per entry. KeePassHTTP is the only reason why you would want something like that, but also only because you can't add multiple URLs to an entry.

**Comment by TheZ3ro** [comment] 2017-02-09 20:25
Not really. I can use reference if I have multiple users on the same website so I can set 1 URL and reference it, or having 1 entry with your common username and reference that, or reference same CustomAttribute, and much more.

IMHO it's a duplicate

**Comment by droidmonkey** [comment] 2017-02-09 20:49
The reference syntax and usability is questionable to me. So very cumbersome to overcome the simple case of multiple urls. I will investigate the use of an attribute to help overcome this.

**Comment by TheZ3ro** [comment] 2017-02-09 21:58
Sadly reference needs to be implemented for KeePassHTTP URLs or for other things. Finding an alternative to what is written in KeePass specifications seems useless to me.

Since you can't have multiple URL for entry you need to use custom attribute (and place an `S:` before it when using it) or inserting in URL a list of url separated with `|` or `;` but will break lot of things on KeePass side.

**Comment by droidmonkey** [comment] 2017-02-09 22:04
How about a compromise? We can close this issue, but #75 should be implemented with a GUI change. We add a button to the entry edit widget: "Reference Entry..." which opens a picker dialog to choose the other entry to reference. This will auto-fill the username and password fields with the crazy ```S:``` syntax using the picked reference.

**Comment by TheZ3ro** [comment] 2017-02-09 22:24
Totally agree with that, more user friendly.

PS: We should also consider a similar approach for Autotype sequences ;)

**Closed** 2017-02-12 15:24 UTC
Labels: discussion, new feature, plugin interface

**Comment by ccoenen** [comment] 2021-07-03 09:59
If someone came here via a search engine, trying to find out how this works, please look at https://github.com/keepassxreboot/keepassxc/pull/3558 which was the feature added in KeePassXC 2.5.0.
