### ISSUE TITLE
Failure to re-add key to SSH Agent after upgrade to 2.6.0 on MacOS

### ISSUE THREAD

**Issue by DG0lden** [keepassxreboot/keepassxc#5016] opened 2020-07-10 16:01 UTC
## Overview
The keys aren't added to the agent after second (and next) database unlock.

Key configuration is the following
<img width="384" alt="зображення" src="https://user-images.githubusercontent.com/2138893/87173758-8518b400-c2d6-11ea-8dc3-599b9991dd40.png">

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Start KeepassXC
2. Unlock the database (key is being added to the agent here)
3. Lock the database (or wait for lock timeout). Do no close KeepassXC
4. Unlock the database again. Key is not added to the agent.
5. Manual try to add the key in this state leads to the error message:
<img width="354" alt="зображення" src="https://user-images.githubusercontent.com/2138893/87174264-34ee2180-c2d7-11ea-91bc-84a67cc83150.png">

## Expected Behavior
Key shall be added to the agent each time I unlock the databse

## Actual Behavior
When KeepassXC starts, after the first database unlock the key is added to the agent properly.
But after next database unlock key is not added anymore.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.0
Revision: 0765954

Qt 5.15.0
Debugging mode is disabled.

Operating system: macOS Mojave (10.14)
CPU architecture: x86_64
Kernel: darwin 18.7.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.5

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS Mojave 10.14.6

**Comment by hifi** [comment] 2020-07-11 04:17
This is odd. I cannot reproduce this on Linux and there shouldn't be anything platform specific about this.

Are you only opening and closing a single database? This "ownerhip conflict" should only be triggered if you are opening two or more databases with the *same* key in them.

**Comment by danubekas** [comment] 2020-07-13 10:52
I have a similar issue on Linux. 
Adding/ Removing Keys manually works fine untl the Database is locked. When I unlock the Database again, I cannot add previously used keys to ssh-agent (removing still works).
After restarting KeepassXC everything works again until DB is locked.

KeePassXC - Version 2.6.0
Revision: 0765954
Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 5.7.7-arch1-1

**Comment by droidmonkey** [comment] 2020-07-13 10:58
Sounds like you don't have "remove key on database unlock" checked for those keys.

**Comment by danubekas** [comment] 2020-07-13 11:05
When I remove key on database lock, I still cannot add the key again without restart.

**Comment by droidmonkey** [comment] 2020-07-13 11:29
Got it

**Comment by Felixoid** [comment] 2020-07-17 06:41
2.6.0, arch-linux here as well. After 2.6.0 keys could be added to the agent only after program restart. Roll-back to 2.5.4 fixes the issue.

Is there any additional information that would be useful here?

**Closed** 2020-07-18 14:02 UTC
Labels: bug, platform: macOS, plugin: SSH agent
