### ISSUE TITLE
KeePassHTTP requests access to items with empty URL

### ISSUE THREAD

**Issue by ligyxy** [keepassxreboot/keepassxc#1080] opened 2017-10-16 18:37 UTC
## Current Behavior
On some web pages, it pops up the KeePassXC HTTP Confirm Access window asking access to several items, even if I have never saved item for that website/URL. I noticed that those items it requests are all with empty URL field. So I am guessing something goes wrong with the URL match when performing auto-fill with keepasshttp. I have tried checking and unchecking "Match URL Schemas" in the Browser Integration, but it is not changed.

One web page I have tried is  , I am not sure if there's any requirement on the web page to trigger this.

## Possible Solution
Not match records with empty URL

## Steps to Reproduce (for bugs)
1. Add record with empty URL;
2. One example page I have https://www.crowdflower.com/ , with keepasshttp enabled, it will pop up the request window for granting access.

## Debug Info
KeePassXC - 2.1.1

Operating system: OS X 10.13
CPU architecture: x86_64

Enabled extensions:
- KeePassHTTP
- Auto-Type

**Comment by TheZ3ro** [comment] 2017-10-16 19:13
Duplicate of #1017 

Will be fixed in the new version soon :)

**Closed by TheZ3ro** 2017-10-16 19:13 UTC
