### ISSUE TITLE
Auto-type fails and its keyboard shortcut cannot be set, if more than one instance of KeePassXC has ended up runng. (Windows.)

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [keepassxreboot/keepassxc#6394] opened 2021-04-10 15:57 UTC
## Overview
Somehow multiple instances of KeePassXC ended up running. I did not realise that that was so - until I investigated various problems that the multiplicity turned out to cause.

## Steps to Reproduce
I _think_ the following.
1.  Run KeePassXC
2.  Run it _again_. (But, how? I find that when I have one instance running, another will not run. Yet, somehow, I ended up, earlier, with _three_ instances; and indeed I think I've encountered this problem at least once before.)
3. Try to use autotype.
4. Try to set the autotype key.

## Expected Behavior

The user should be prevented - more thoroughly than she is already - from running multiple instances of KeePassXC. Or else the problems that I list below should be forestalled in some other fashion.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

1) Pressing the autotype hotkey did nothing.
2) Trying to set that hotkey, within KeePassXC, showed the relevant box - the one that one selects before pressing the key combination - with a red outline.
3) The same box showed 'ctrl + alt' when I pressed ctrl + alt + k. That is, the 'k' was omitted. I imagine the cause is that another instance of KeePassXC was intercepting the key-combination.

## Context

KeePassXC - Version 2.6.4
Revision: 34a78f0

Qt 5.15.2
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.19042

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
- libgcrypt 1.9.1-unknown

Operating System: Windows 10

**Comment by droidmonkey** [comment] 2021-04-10 16:05
We won't do anything about the hotkey problems since that is not solvable without maintaining multiple config files for each instance. Try to replicate how you started multiple instances. This could conceivably happen if you rapid fire started keepassxc.exe three times before any single one of them established the single instance pipe.

**Comment by LinuxOnTheDesktop** [comment] 2021-04-10 16:23
> Try to replicate how you started multiple instances.

I'm not managing so far. I have KeePassXC set to run on login, and it does so (and so far as I can tell the PC is not set to autorun more than one instance). Here are methods that I used to try to generate multiple instances. All of them failed to do that.

1) Unloading KeePassXC, running it, and then immediately afterwards repeatedly pressing tmy KeePassXC hotkey.
2) Running KeePassXC - when it is not running already - by double-clicking its executable, and then repeating the step immediately afterwards.
3) Running KeePassXC and then telling a windows terminal to execute the path to the executable.

If the problem re-occurs then I will try to recall how it arose.

**Comment by droidmonkey** [comment] 2021-04-12 00:59
Gonna close this unless you can reproduce the event.

**Closed by droidmonkey** 2021-04-12 00:59 UTC
Labels: bug

**Comment by LinuxOnTheDesktop** [comment] 2021-04-12 02:36
I have a tool that can prevent duplicate processes. I have decided to use that tool (the program Process Lasso) to workaround the problem. Hence I will not be able to duplicate the problem (though I did try previously to do so). I note that a workaround does imply a bug. I invite anyone else who encounters the bug to petition to get this report re-opened.

**Comment by LinuxOnTheDesktop** [comment] 2021-04-20 01:15
The problem recurs even when a utility (the aforementioned Process Lasso) is set to allow only a single instance of KeePassXC.

The circumstance in which the problem manifests itself is this joint one: I use the autotype hotkey and the database is locked (though the problem does occur in every such joint circumstance).

Those things together suggest that what is happening is this. _The hotkey is launching a new instance of KeePassXC when what the hotkey should be doing is reactivating an existing instance._ But I could be wrong.

**Comment by droidmonkey** [comment] 2021-04-20 01:26
The hotkey is registered by the running instance and responds to it being pressed. A new instance is absolutely not started.
