### ISSUE TITLE
Suddenly unable to use ico images

### ISSUE THREAD

**Issue by ItTakesTwo** [keepassxreboot/keepassxc#1195] opened 2017-11-19 09:30 UTC
Totally random my Keepassxc cannot work with .ico images anymore. Neither download nor use as custom icon.

## Expected Behavior
I put the URL to the website into the URL field, go to the icon tab, press "Download favicon" and the icon is automatically downloaded and saved.
Alternatively I download the icon myself, go to the symbol tab, activate the custom icon tab, press "Add custom icon", choose the ico file and save it.

## Current Behavior
After I press "Download favicon" I get the error message "Unable to fetch favicon." shown in a red box above the icons. If I choose the icon manually I have to set the filetype filter to all files to even see the ico file and after choosing the ico file I get in the same red box the error message "Can't read icon". 

## Steps to Reproduce (for bugs)
1. Put URL to website in URL field
2. Go to icon tab
3. Press "Download favicon"

## Context
I cannot download icons comfortably anymore and went back to the times of Keepass2 where I have to find and download the favicon myself to have it in my database.

## Debug Info
KeePassXC - Version 2.2.2
Revision: 6d46717

Libraries:
- Qt 5.9.2
- libgcrypt 1.8.1

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.15063

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

**Comment by droidmonkey** [comment] 2017-11-19 12:06
The whole icon downloading scheme will change once i can merge the qhttpengine/curl pr.

**Comment by nursoda** [comment] 2017-11-20 12:01
OK, but that has nothing to do with the .ico FileType itself, right? .ico (aka "Windows Icon" format) is not even part of the "image filetype mask" in the selection dialog, so it seems .ico support was (purposely?) removed. Please re-add it.

Workaround: Convert .ico to .png manually. But that's unnecessary steps ...

**Comment by phoerious** [comment] 2017-11-20 17:30
We did not change anything related to ICO files. Perhaps Qt removed support for it.

**Comment by ItTakesTwo** [comment] 2017-11-27 10:12
It's working on my Debian Jessie machine by the way.

**Comment by chessgriffin** [comment] 2017-12-01 13:05
Same here - select an entry > "view/edit entry" > Icon > Use custom icon > Download favicon results in a red "Unable to fetch favicon" error message.  This is Keepassxc 2.2.2 on Windows 10.  Thanks.

**Comment by droidmonkey** [comment] 2017-12-01 13:12
I'll look into this weekend

**Comment by chessgriffin** [comment] 2017-12-01 13:19
Thanks - and to clarify, on Windows 10 I can add a custom icon that I downloaded manually and it displays fine.  I can also open my db in Keepass 2.37 on Windows 10 and use a plugin to download icons and they display  fine in Keepassxc.  It just seems to be the downloading part that is broken on Windows 10 -- but it works perfectly on Mac OS High Sierra.  Thanks again for looking into it and thanks for your work on Keepassxc - I use it all the time on multiple platforms and it's fantastic.

**Comment by droidmonkey** [comment] 2017-12-01 14:36
I believe this is all fixed with the move to curl for the download process. Can you provide a site that does not work for you and I'll run it through the debugger for both versions.

**Comment by chessgriffin** [comment] 2017-12-01 14:44
Sure, here are a few at random:

http://americanexpress.com
https://dropbox.com
https://paypal.com

Thanks!

**Comment by nursoda** [comment] 2017-12-01 21:49
> I believe this is all fixed with the move to curl for the download process.
How can that be as .ico is missing in the list of selectable LOCAL files?

**Comment by droidmonkey** [comment] 2017-12-01 22:03
You all are talking about two completely different issues...

**Comment by nursoda** [comment] 2017-12-02 09:09
True, it's two issues (download .ico, select/use local .ico), but both are described in the bug. Shall the bug be splitted?

**Comment by droidmonkey** [comment] 2017-12-02 22:30
For both of you @chessgriffin and @nursoda, which platform are you using KeePassXC on? I have no issues with *.ico showing up in my file selection dialog or downloading ico's from the internet. KeePassXC relies on Qt to tell it which image formats it can read, if you are on Linux and you don't have the qico.so file installed, Qt will not know how to handle ico files. This explains why neither website icons nor file chooser icons are accessible. This is not a KeePassXC issue.

**Comment by chessgriffin** [comment] 2017-12-02 23:48
Please see my two posts and I set it all out.  Icon downloading does not work on Windows 10 like other posters but works for me on Mac.  In all cases viewing and selecting custom icons manually works fine.

**Comment by nursoda** [comment] 2017-12-03 11:40
I encountered the issue on Windows (10 Pro 64bit).

**Comment by ralther** [comment] 2018-01-19 23:10
Using KeePassXC v2.2.4 (Windows 10, Linux)
I'm encountering the same issue on Windows 10.  I'm unable to download ICO type favicons.  I receive the error "Unable to fetch favicon."

If I download the favicon manually and try to "Add custom icon", *.ico does not show up in the Images filter.  If I select "All files", and select it, I get the error "Can't read icon".

I also run this on Linux using the same version of KeePassXC, and it downloads and reads .ico files fine.  It's ironic that it's only failing on Windows.

**Comment by droidmonkey** [comment] 2018-02-24 18:45
Is this still an issue with 2.3.0-beta1? I could not reproduce this at all.

**Comment by nursoda** [comment] 2018-02-25 00:03
With beta1 I can SELECT but not LOAD an .ico Icon:

- The preselected file type filter "Images" still doesn't include .ico in the list of allowed extensions.
- If I select "All files" and select a valid .ico, it says "Cannot read Icon" (back-translated from german error message).

Additionaly, I can no longer use a SMB share, the file selection dialog is limited to local drives.

**Comment by TheZ3ro** [comment] 2018-02-25 00:30
@nursoda can you also report your Debug info form the about window?

**Comment by nursoda** [comment] 2018-02-25 00:35
Of beta1? I had it uninstalled already, but yes. Installing beta1 again ...

KeePassXC - Version 2.3.0-beta1
Build-Typ: PreRelease
Revision: 69283e8

Bibliotheken:
- Qt 5.10.1
- libgcrypt 1.8.2

Betriebssystem: Windows 10 (10.0)
CPU-Architektur: x86_64
Kernel: winnt 10.0.16299

Aktivierte Erweiterungen:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by N3pp** [comment] 2018-02-25 18:48
I too still get "Unable to fetch favicon." error with or without the "use Google as fallback" option. And when I try to add custom icon, ".ico" doesn't show up in the extension list and both changing the filter to "All files" then selecting the icon (.ico) and changing the extension of the file (to bmp/png etc.) leads to the "Can't read icon" error.

KeePassXC - Version 2.3.0-beta1
Build Type: PreRelease
Revision: 69283e8

Libraries:
- Qt 5.10.1
- libgcrypt 1.8.2

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.16299

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by phoerious** [comment] 2018-02-25 19:01
Google should always return a standard icon if the website has none, so the "unable to download favicon" should only occur when KeePassXC can't access the Internet.
I also can't reproduce the ICO issue and can't find anything via Google.

**Comment by nursoda** [comment] 2018-02-25 21:08
Did you try to reproduce ON WINDOWS 10 64bit? It has been confirmed that it's a non-issue on Linux. I'm using all default settings, no development environment (e.g. Qt not installed apart from what's contained in the package. In case there might be interferences: There are other programs installed that also use Qt components, such as Kleopatra (GPG4win).

I suggest you create a debug version to explore the cause of the LOCAL .ico not readable issue. I think that the DOWNLOAD issue disappears once the LOCAL issue is solved. I can offer that you see for yourself on my machine using Teamviewer but I won't let you install dev tools on it.

**Comment by phoerious** [comment] 2018-02-25 21:19
Yes, I tried it on Windows, 64bit. I can open ICO files just fine and they are also included in the file filter.

**Comment by droidmonkey** [comment] 2018-02-25 22:00
I suspect the root cause of this issue is something is missing or disabled on the affected machines that is preventing the deployed qt in KeePassXC from loading the ico plugin.

**Comment by ralther** [comment] 2018-02-26 16:37
I'm guessing that the ICO plugin for Qt (libqico) is not included in the installer (I don't see it on my Windows machine).  On my Linux machine, this plugin is installed by default.

If I remove libqico.so from my Linux system, I experience the same behavior as I do on Windows 10: ICO files don't show up in the Images filter, and I'm unable to download the icon (however, if I allow Google fallback, it works - on both Linux and Windows).

I'm guessing you have this plugin installed at the system level or in your development environment, so it works for you.  Downloading from Google works because they deliver a PNG image rather than the actual ICO from the website.

**Comment by droidmonkey** [comment] 2018-02-26 22:45
@phoerious we need to include this dll in the same manner we include the windows platform dll, I suspect.

**Comment by phoerious** [comment] 2018-02-27 13:19
Fixed in #1534 and #1537

**Closed by phoerious** 2018-02-27 13:19 UTC
Labels: Windows, bug, distribution

**Comment by ralther** [comment] 2018-02-27 15:44
Just a suggestion - you may want to include that plugin for all platforms, not just Windows.  I know the plugin is likely installed on Linux, but it may not always be.  e.g. KDE/Plasma desktops will almost certainly have it installed, but not necessarily GNOME or other DEs.  It is a dependency and it's likely better to include it than not.

**Comment by phoerious** [comment] 2018-02-27 17:24
The AppImage does ship all available imageformat plugins.

**Comment by nursoda** [comment] 2018-02-27 17:33
Please notify us here once a new beta build is ready to test.

**Comment by phoerious** [comment] 2018-02-27 18:48
There will be no more beta builds. We will release a stable version today/tonight.

**Comment by droidmonkey** [comment] 2018-02-27 23:43
Apologies for doubting your report. There is no logical reason why qt was actively seeking out our msys installs. Crazy stuff indeed!

**Comment by nursoda** [comment] 2018-02-28 08:19
Release 2.3.0 works like a charm with local .ico files. Thanks.
