### ISSUE TITLE
Agent connection failed

### ISSUE THREAD

**Issue by Kusoneko** [keepassxreboot/keepassxc#4460] opened 2020-03-23 05:55 UTC
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

This is sort of a continuation of #3683, I have since switch from bash to zsh and from the hacky method used to start the ssh-agent in there to the systemd method mentioned [here](https://wiki.archlinux.org/index.php/SSH_keys#Start_ssh-agent_with_systemd_user).

I'm gonna assume this is gonna be something for @hifi ?

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Successful connection to the ssh-agent.

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
![keepass-ssh-failed](https://user-images.githubusercontent.com/7924656/77285482-75ce1600-6ca7-11ea-81d2-e51277a9a26e.png)

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. Launch keepassxc through the KDE Plasma 5 Application Launcher
2. Enter passphrase to open the database
3. Observe as the above happens immediately

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )
Unable to use keepassxc as a ssh-agent despite the following:
![keepass-ssh-stuff](https://user-images.githubusercontent.com/7924656/77285611-c80f3700-6ca7-11ea-9c02-5dd86711ae52.png)
![keepass-ssh-systemd](https://user-images.githubusercontent.com/7924656/77285620-cc3b5480-6ca7-11ea-95ac-57e7472e3186.png)
The only case it appears to work properly is if I launch keepassxc from the terminal, which isn't quite what is wanted here, it should correctly connect to the ssh-agent regardless since it's now properly started.

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.5.3
Revision: f8c962b

Qt 5.14.1
Debugging mode is disabled.

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 5.5.11-1-ck-sandybridge

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by hifi** [comment] 2020-03-23 08:17
Regardless how you start the agent, the environment variable `SSH_AUTH_SOCK` needs to be visible to KeePassXC for it to properly pick it up. If systemd launches the process "on the side" and the env variable is not exported during KDE start in the process chain it won't come up in any application started from within - except a terminal that may re-export the env variable manually with a shell startup script.

The *proper* method to start ssh-agent is to do it within X session startup before starting a DE/WM session and exporting the env variable so that it is picked up by the environment.

Because it is hard for people to configure this if it hasn't been done by the distribution the right way we added an override that is available in nightly and will be in 2.6.0 within the agent settings. Because your socket path is static you can override it in the settings and it should work.

This is definitely not a bug within KeePassXC.

**Closed by hifi** 2020-03-23 08:17 UTC
Labels: not a bug
