### ISSUE TITLE
Password Containing "&" show URL Encoded in Preview Panel - 2.7.3

### ISSUE THREAD

**Issue by pixeldoc2000** [keepassxreboot/keepassxc#8654] opened 2022-10-25 11:35 UTC
## Overview
Preview Panel shows Password URL Encoded if it includes special Characters like &.
Looks like it only happens with &, other Characters are not encoded AFAIK.

## Steps to Reproduce
1. Create Entry with Password including & Character
2. Select Entry
3. Preview Password in Preview Panel

## Expected Behavior
Passwort Preview should be displayed as is ;-)

## Actual Behavior
Example Password: `Pass123&123`
Password Preview: `Pass123&amp;123`
![grafik](https://user-images.githubusercontent.com/376715/197763220-5de6dd86-d2b0-4a19-b188-c790f9d66928.png)

![grafik](https://user-images.githubusercontent.com/376715/197762816-65d1cc63-2d14-474e-a0a9-3c959b33e706.png)

## Context
KeePassXC - Version 2.7.3
Revision: d8483d3
Operating System: Windows 10

**Comment by pixeldoc2000** [comment] 2022-10-25 11:37
Maybe related to #8636 ?

**Comment by phoerious** [comment] 2022-10-25 11:41
No, but it's a duplicate of #8627, which has been fixed in #8633.

**Closed as not planned by phoerious** 2022-10-25 11:41 UTC
