### ISSUE TITLE
ssh-agent: keytype sk-ecdsa-sha2-nistp256@openssh.com not yet supported

### ISSUE THREAD

**Issue by Gulaschcowboy** [keepassxreboot/keepassxc#4741] opened 2020-05-14 13:55 UTC
The new openssh keytype sk-ecdsa-sha2-nistp256@openssh.com is not yet supported in keepassxc. Would be nice to have this supported as well.

Thx!

**Comment by hifi** [comment] 2020-05-14 17:01
Duplicate of #4334.

**Closed by hifi** 2020-05-14 17:01 UTC
Labels: duplicate, new feature, plugin: SSH agent
