### ISSUE TITLE
Cant add ssh key "Agent connection failed"

### ISSUE THREAD

**Issue by ToKaTpoHb** [keepassxreboot/keepassxc#1746] opened 2018-03-17 15:11 UTC
## Expected Behavior

I'm trying to add a key from KeepassXC

## Current Behavior
![image](https://user-images.githubusercontent.com/11059471/37556911-6b5e0540-2a05-11e8-93a2-ee6513fd3fd1.png)

## Steps to Reproduce (for bugs)

1. Generate sample key with `ssh-keygen -t rsa -b 4096`
2. Add new entry.
3. Add key as attachment.
4. Press "Add to agent" button.
5. Error happens.

## Debug Info
```
$ echo $SSH_AUTH_SOCK
/run/user/1000/keyring/ssh
```

KeePassXC - Version 2.3.1
Revision: 2fcaeea
Distribution: Snap

Libraries:
- Qt 5.7.1
- libgcrypt 1.7.6-beta

Operating system: Ubuntu Core 16
CPU architecture: x86_64
Kernel: linux 4.13.0-37-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by hifi** [comment] 2018-03-17 16:18
Does ssh-add work from command line after this happens? Also we don't really recommend GNOME Keyring as it has multiple issues with ssh keys.

**Comment by ToKaTpoHb** [comment] 2018-03-17 16:21
@hifi yes
```
$ ssh-add -L
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDEGda0YWYwdRrfjMTz42pNmSohb1UcSo7bkWDY0OfEbIGLP0RZ6hBvM56WP3JpuFb+DRl5XWJeolw/FMSgrFw7uWv0gUthDeKeHYC7iKNx1SOWor3AY9twvpL99o1rVtWfzFxKst90bPZ+KyBf+s7iWscbrSAH1jjA ......
```

**Comment by hifi** [comment] 2018-03-17 16:22
Does this also happen with the PPA version of KeePassXC or only with the snap one?

**Comment by ToKaTpoHb** [comment] 2018-03-17 16:23
I dont know, let me test.

**Comment by ToKaTpoHb** [comment] 2018-03-17 16:42
If you need more detailed explanation or comments please ping me.

**Comment by hifi** [comment] 2018-03-18 05:05
This is a problem with GNOME Keyring and I haven't been able to reproduce it locally to see what's going wrong. If you just want things to work I suggest turning off the SSH Agent feature from GNOME Keyring and enabling the real OpenSSH `ssh-agent`.

**Comment by hifi** [comment] 2018-03-18 05:06
Closing as duplicate of #1632, please add any insight into the older issue.

**Closed by hifi** 2018-03-18 05:06 UTC
Labels: plugin: SSH agent

**Comment by asvc** [comment] 2020-03-28 00:00
Just a note, observed this today on Windows build,
```
KeePassXC - Version 2.5.3
Revision: f8c962b

Qt 5.13.2
Debugging mode is disabled.

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.18363
```
Pageant:
```
Pageant

Release 0.72

Build platform: 32-bit x86 Windows
Compiler: clang 7.0.0 (tags/RELEASE_700/final), emulating Visual Studio 2013 (12.0), _MSC_VER=1800
Embedded HTML Help file: yes
Source commit: 75cd6c8b2703137e574223d90d2f3ead9ca34acc
```
Restarting both has resolved the issue.
