### ISSUE TITLE
Warning about database changed missing while editing entry

### ISSUE THREAD

**Issue by itsenaf** [keepassxreboot/keepassxc#10461] opened 2024-03-18 10:27 UTC
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

We are using databases with multiple users.
Following feature prevents us from overwriting other user changes:

![image](https://github.com/keepassxreboot/keepassxc/assets/32543904/aad05bb6-eef9-409c-a0a3-b56bbc53a036)

Unfortunately, this warning doesn't appear when you are active in "edit entry" window.
For example after click on "Add entry" or double click on entry to view its content.
In this case, mentioned warning seems to be invisible in background.
When you close edit window, the warning will not appear afterwards. You get no notification about recent change.
You will probably overwrite the other users changes when saving.

This seems to be a bug.
The warning should also appear in front of "edit entry" window.
In settings window it works like expected.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
0. Disable feature "automatically reload the database when modified externally."
1. Add new entry and leave it open.
2. Make change to database on other computer.
3. Do not receive warning about change.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Warning about external change should also appear while editing entry, or afterwards.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
No warning appears.

## Context
[NOTE]: # ( Give us any additional information you may have. )
I guess its no issue since v2.7.7. We just fall into this case for the first time now.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.7
Revision: 68e2dd8

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows

**Comment by droidmonkey** [comment] 2024-03-18 11:14
Duplicate of #8545

**Closed as not planned by droidmonkey** 2024-03-18 11:14 UTC
Labels: duplicate
