### ISSUE TITLE
Ctrl + F from entry list  stops working when search window vanishes because insufficient  toolbar space

### ISSUE THREAD

**Issue by PatriciaJH** [keepassxreboot/keepassxc#4262] opened 2020-01-29 14:44 UTC
## Expected Behavior
I switch to KeepassXC from an application that's requesting a password by using a keystroke combo, the focus is already in the entry list window where I left it, I type Ctrl-F, I enter or paste the name of the thing I want, I hit Ctrl-C for the password (or Ctrl-B for username occasionally) I keystroke-switch back to where I was  and no mouse is ever involved.

This is how it worked until this [most recent upgrade] whoops, no it happened because I switched settings to "text under icons," and the search window vanished because there wasn't enough space on the toolbar on my laptop screen. 

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
I switch to Keepass and Ctrl + F does nothing.  I discover that there is a little >> on the right-hand edge which, with a mouse click, opens a search window.  If-and-only-if this window is open, Ctrl + F performs a search.  As soon as I switch focus to an entry, the search window vanishes.  In order to perform another search, I have to re-open the window.
NOTE that a naive user wouldn't suspect this window even exists, and would not be able to find the thing.

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )
Ctrl-F should automatically open the search window, and there should be some kind of search icon on the toolbar if the search window is closed due to lack of space. 
Truncate toolbar text rather than crowding a key element off the window. 

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1.
2.
3.

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION
Revision: REVISION

Libraries:
- LIBS

Operating system: OS
CPU architecture: ARCH
Kernel: KERNEL

Enabled extensions:
- EXTENSIONS

**Comment by droidmonkey** [comment] 2020-01-29 22:41
Duplicate of #505

**Closed by droidmonkey** 2020-01-29 22:41 UTC
Labels: bug
