### ISSUE TITLE
[Feature Request] Export password attributes

### ISSUE THREAD

**Issue by apiraino** [keepassxreboot/keepassxc#2620] opened 2019-01-19 20:02 UTC
Unless I'm missing something, as of KeepassXC 2.3.4 the export to .CSV function does not include the OTP attributes from the "Advanced" properties.

It would nice to be able to export them, too, to have a full export of the database.

btw Password attributes are not accessible either from the KeepassXC client, so one cannot script a manual export.

Thanks!

**Comment by droidmonkey** [comment] 2019-01-20 04:46
Duplicate of #2094 and #1437

**Closed by droidmonkey** 2019-01-20 04:47 UTC
