### ISSUE TITLE
DB does not get locked when there is an active "browser confirm access" window

### ISSUE THREAD

**Issue by Troyciv** [keepassxreboot/keepassxc#2046] opened 2018-06-12 09:45 UTC
## Expected Behavior

When having "lock databases when session is locked or lid is closed" activated in the settings the db should get locked when I close my lid. 

## Current Behavior

DB does not get locked when there is an active window called "browser confirm access", used for the browser plugin.

## Steps to Reproduce (for bugs)

1. install keepass 2.3.3.
2. install keepassxc-browser for firefox
3. open password db in keepassxc
4. visit a website where your db has the login for and also has the url stored
5. keepassxc will pop up a window for browser access confirmation
6. close the lid
7. open lid
8. db is still open

## Debug Info

KeePassXC - 2.3.3
Revision: 0a155d8

Libraries:
- Qt 5.9.1
- libgcrypt 1.7.8

Operating system: ubuntu 17.10
CPU architecture: x86_64
Kernel: 4.13.0-43-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by TheZ3ro** [comment] 2018-06-14 20:00
Duplicate of #721 that applies to every type of Dialog

**Closed by TheZ3ro** 2018-06-14 20:00 UTC
Labels: bug, plugin: Browser integration
