### ISSUE TITLE
Spaces in additional attribute not working for autotype

### ISSUE THREAD

**Issue by grenzor** [keepassxreboot/keepassxc#1546] opened 2018-02-28 06:02 UTC
## Expected Behavior

In 2.2.4 I had an additional attribute with a space in it like `SOME NAME` and it worked when using it for autotype sequence using something like `{S:SOME NAME}`.

## Current Behavior

In 2.3.0 Autotype sequences with attributes like `{S:SOME NAME}` containing spaces gives the error `The Syntax of your Auto-type statement is incorrect` (whereas `{S:SOMENAME}` gives no error). Not sure if this is new behavior in 2.3.0 (using KDBX4) but just something I wanted to ask about in case it's a bug.

Operating system: Windows

**Comment by googlebleh** [comment] 2018-02-28 06:34
I'm getting the same error message for an additional attribute with an underscore in the name.

My equivalent case has the attribute `SOME_NAME`, and auto-type says the syntax `{S:SOME_NAME}` is incorrect. Changing it to `SOMENAME` and, respectively, `{S:SOMENAME}` works as expected.

OS: Ubuntu 17.10, amd64

**Comment by TheZ3ro** [comment] 2018-02-28 13:53
Thanks for the report, I can reproduce this.

I will fix it in the next minor 2.3.1 version

**Comment by brwolfgang** [comment] 2018-03-05 12:28
Adding some more info: Autotype also fails if the additional attribute has an accent such as í, ó, ú, â, ã, etc.
Just pointing that it is a regression since it worked fine until last version.

**Comment by TheZ3ro** [comment] 2018-03-05 14:04
Check out `release/2.3.1` branch, should be fixed now

**Comment by phoerious** [comment] 2018-03-06 21:30
Fixed in #1626

**Closed by phoerious** 2018-03-06 21:30 UTC
Labels: bug, plugin: Auto-Type
