### ISSUE TITLE
Allow closing window, but keeping the application running without tray icon

### ISSUE THREAD

**Issue by lumnn** [keepassxreboot/keepassxc#1175] opened 2017-11-09 09:23 UTC
Recent Gnome version (3.26) don't use tray at all. Which makes it more uncomfortable to use application. To have quick access to database you have to keep window open at all times.
Options "Show a system tray icon" and both sub-options doesn't change any behaviour.

I believe it would be very useful for Gnome users, and maybe others to allow closing application window, but keep running in background. Next time when users start app from launcher it should be able to quickly show the window.

## Expected Behavior
New option in settings like: "Hide application window, but keep running in background on app exit". This must check and force "Start only a single instance of KeePassXC".
Database > Quit should work exactly same as in tray mode, so user is able to close app entirely.

**Comment by droidmonkey** [comment] 2017-11-09 12:05
Based on my read, gnome expects you to either be a foreground or background app. If you are background you use notification apis to send messages to the user in a consistent way. If you are foreground you live in the "task bar" on the left when open.

So, based on this gnome thinks it is an antipattern to show a tray icon for an app that is merely minimized and it is also an antipattern to just hide the app completely when minimized.

I tend to agree with the latter regardless of gnome or not. Im going tp say this won't likely be implemented.

**Comment by phoerious** [comment] 2017-11-17 10:38
I know that KDE devs have been arguing for a while against using tray icons as well. But their incentive was that you shouldn't hide a window, but minimize it and let the task bar handle it.

**Comment by chrpinedo** [comment] 2018-04-09 07:06
Some input about this issue from GNOME: https://wiki.gnome.org/Initiatives/StatusIconMigration/Guidelines

**Comment by droidmonkey** [comment] 2018-07-14 21:03
Duplicate of #795

**Closed by droidmonkey** 2018-07-14 21:03 UTC
