### ISSUE TITLE
Keybord layout for password

### ISSUE THREAD

**Issue by plegrand1** [keepassxreboot/keepassxc#3605] opened 2019-10-06 09:38 UTC
Hello,
i'm using Keepassxc AppImage 2.4.3 on debian SID with gnome-shell.
When keepassxc is launched from autostart (/home/pascal/.config/autostart/keepassxc.desktop)
[Desktop Entry]
Name=KeePassXC
Exec=env QT_AUTO_SCREEN_SCALE_FACTOR=0 /home/pascal/Documents/KeePassXC/KeePassXC.AppImage %U
Terminal=false
Type=Application
Icon=/home/pascal/Documents/KeePassXC/keepassxc.png
StartupNotify=true

The keyboard layout is QWERTY then my password is always wrong.
I have to quit keepassxc and launch it again then it works fine (AZERTY).
Could you help me to find the problem ?

**Comment by droidmonkey** [comment] 2019-10-06 11:02
Its probably launching before your keyboard layout is setup

**Comment by plegrand1** [comment] 2019-10-06 13:07
thanks for your answer, but i cant see how i could change this.
When you say : "Not using the current keyboard layout (ie detect it after launch) is a known issue.".
You speak about a keepassxc issue ?
Thanks again

**Comment by droidmonkey** [comment] 2019-10-06 13:11
Instructions for delaying start: https://askubuntu.com/questions/28685/how-can-i-delay-a-specific-program-on-startup

Yes this is a KeePassXC issue. AutoType "remembers" the keyboard that was active when KeePassXC launches. It does not look for the _current_ active keyboard after launch.

**Comment by plegrand1** [comment] 2019-10-07 07:33
The strange thing is that on an other computer (same config),  i have not this problem.

**Comment by plegrand1** [comment] 2019-10-07 08:04
As you said : 

> AutoType "remembers" the keyboard that was active when KeePassXC launches. It does not look for the current active keyboard after launch.

Just for information my problem is about unlock database and not autotype

**Comment by plegrand1** [comment] 2019-10-07 08:25
Yes i understand, as i said before it happen on my home computer but no problem on my job computer

**Comment by irgendsontyp** [comment] 2019-11-02 17:20
Is this somehow related to https://github.com/keepassxreboot/keepassxc/issues/2122?

**Comment by phoerious** [comment] 2020-06-01 08:43
Duplicate of #324

**Closed by phoerious** 2020-06-01 08:43 UTC
Labels: bug
