### ISSUE TITLE
Unable to Type in Any Text Entry Field

### ISSUE THREAD

**Issue by arctic289spice** [keepassxreboot/keepassxc#7959] opened 2022-04-26 05:32 UTC
## Overview
I can't type anywhere in KeePassXC.  New entries, old entries, the search bar; I'm not able to enter text anywhere.  I can copy and paste (by left clicking, not with Ctrl+C/V), but I can't enter information in any text field with my keyboard.  I'm still able to unlock my DB by typing my password in, but this is currently the only location in KeePassXC 2.7.1 where I can enter text with my keyboard.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1.  Unlock DB (still able to type in the password field) 
2. Select 'Add a new entry' or attempt to use search bar.
3. Attempt to enter text with keyboard.
4. No new text is displayed/recorded

## Expected Behavior
Text entry is accomplished with the physical keyboard in all text fields.

## Actual Behavior
Unable to enter text with my keyboard anywhere (expect the master password)

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.1
Revision: 5916a8f

Qt 5.15.2
Debugging mode is disabled.

Operating system: Fedora Linux 35 (Workstation Edition)
CPU architecture: x86_64
Kernel: linux 5.17.4-200.fc35.x86_64

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.18.2

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Gnome
Windowing System: Wayland

**Comment by droidmonkey** [comment] 2022-04-26 11:20
Duplicate of https://github.com/keepassxreboot/keepassxc/issues/5608

**Comment by Altonss** [comment] 2022-04-26 22:45
I have the same issue!

**Comment by LarsGehrken** [comment] 2022-04-27 14:52
Have the Same issue with the same Environment

**Comment by droidmonkey** [comment] 2022-04-27 15:08
@Germano0 we have a fresh set of problems with FC35. We saw this previously with FC33.

**Comment by Germano0** [comment] 2022-04-27 15:33
Hi there, I am almost sure about what triggered this problem.
I disabled [the patch](https://src.fedoraproject.org/rpms/keepassxc/blob/rawhide/f/xcb.patch) for handling Qt problems on Wayland because I have been told by Jan Grulich that a specific Qt patch had been merged into Qt 5 that Fedora ships. [Details here](https://src.fedoraproject.org/rpms/keepassxc/blob/rawhide/f/keepassxc.spec#_17)

But despite that you seem to be experiencing troubles. So I am going to build a new KeepassXC release with [the patch](https://src.fedoraproject.org/rpms/keepassxc/blob/rawhide/f/xcb.patch) resumed.

@arctic289spice @Altonss @LarsGehrken are you willing to test the new package release I will produce as soon as possible? I will send a new message here as soon I will build it.
Thank you

**Comment by arctic289spice** [comment] 2022-04-27 17:56
@Germano0, I can't test at the moment, but as a quick workaround I unchecked the 'Automatically launch KeePassXC at system startup' option in basic settings after reviewing [#5608](https://github.com/keepassxreboot/keepassxc/issues/5608), and everything seems to be working now.  I've closed KPXC and restarted a few times and the fix seems to be holding.

![KPXC Screenshot](https://user-images.githubusercontent.com/90937545/165589000-34153ee7-149e-4dae-b593-8dc269fef8ef.png)

**Comment by LarsGehrken** [comment] 2022-04-27 19:39
@Germano0 I will test it asap, when you give me a hint when the release is available

**Comment by Germano0** [comment] 2022-04-29 17:24
@arctic289spice @Altonss @LarsGehrken 

1. are all of you using Wayland and GNOME?
2. can you please test [this build](https://koji.fedoraproject.org/koji/buildinfo?buildID=1958096) if you use Fedora 36, [this build](https://koji.fedoraproject.org/koji/buildinfo?buildID=1958098) if you use Fedora 35, [this build](https://koji.fedoraproject.org/koji/buildinfo?buildID=1958097) if you use Fedora 34

Thank you

**Comment by LarsGehrken** [comment] 2022-04-30 12:01
Yes I am using Wayland and Gnome.
I will test it later today on fedora 35.

**Comment by LarsGehrken** [comment] 2022-05-01 08:40
When trying to directly to your new RPM on Fedora 35 I get this:

Error: Transaction test error:
  file /usr/share/keepassxc/docs/KeePassXC_GettingStarted.html from install of keepassxc-2.7.1-3.fc35.i686 conflicts with file from package keepassxc-2.7.1-2.fc35.x86_64
  file /usr/share/keepassxc/docs/KeePassXC_KeyboardShortcuts.html from install of keepassxc-2.7.1-3.fc35.i686 conflicts with file from package keepassxc-2.7.1-2.fc35.x86_64
  file /usr/share/keepassxc/docs/KeePassXC_UserGuide.html from install of keepassxc-2.7.1-3.fc35.i686 conflicts with file from package keepassxc-2.7.1-2.fc35.x86_64

I will try a clean new install.

**Comment by LarsGehrken** [comment] 2022-05-01 08:54
@Germano0 After a clean new Install with your new Package for Fedora35 it now works! 
Even with "Automatic start" activated.
Thanks!

**Closed as completed** 2022-05-01 10:09 UTC
Labels: downstream, platform: Linux - Wayland

**Comment by Germano0** [comment] 2022-05-01 17:29
Waiting for feedback from the other 2 users

**Comment by droidmonkey** [comment] 2022-05-01 18:41
Yes closing because confirmed it wasn't on us 😄

**Comment by Germano0** [comment] 2022-05-05 09:41
@arctic289spice @Altonss any news?

**Comment by lua-vr** [comment] 2022-05-07 03:32
@Germano0 I was not participating in this thread but had the very same environment and problem, I can confirm your new build for Fedora 35 works! Thank you

**Comment by arctic289spice** [comment] 2022-05-07 04:32
> @arctic289spice @Altonss any news?

Yes! Apologies for the delay.  Works for me now as well.

**Comment by Germano0** [comment] 2022-10-11 08:17
You are mixing 32 bit and 64 bit packages
