### ISSUE TITLE
"Segmentation fault" after two or more clicks in the gui

### ISSUE THREAD

**Issue by marvinwankersteen** [keepassxreboot/keepassxc#2195] opened 2018-08-10 16:12 UTC
## Expected Behavior
KeePassXC should stay open

## Current Behavior
After two or more clicks through the folders, KeePassXC gets closed with error "Speicherzugriffsfehler" (Segmentation fault).

## Possible Solution
I don't know.

## Context
I have a second PC (Laptop) with exactly the same OS. The debug info is the same like below.

## Debug Info
```
KeePassXC - Version 2.3.3
Revision: 0a155d8

Bibliotheken:
- Qt 5.5.1
- libgcrypt 1.8.1

Betriebssystem: Linux Mint 18.3
CPU-Architektur: x86_64
Kernel: linux 4.13.0-45-generic

Aktivierte Erweiterungen:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey
```

## Dependency libraries
```
$ for i in $(apt-cache show keepassxc | grep Depends | sed -e 's/Depends: //g' -e 's/, /\n/g' -e 's/ | /\n/g' | awk '{print $1}'); do dpkg -l | grep "$i:"; done | awk '{print $2"\t\t"$3}' | grep -v i386 | sort
libargon2-0:amd64       20171227-2+really20161029-0ppa1~xenial1
libc6:amd64             2.23-0ubuntu10
libgcrypt20-18:amd64    1.8.1-0ppa2~xenial1
libqt5core5a:amd64      5.5.1+dfsg-16ubuntu7.5
libqt5dbus5:amd64       5.5.1+dfsg-16ubuntu7.5
libqt5gui5:amd64        5.5.1+dfsg-16ubuntu7.5
libqt5network5:amd64    5.5.1+dfsg-16ubuntu7.5
libqt5widgets5:amd64    5.5.1+dfsg-16ubuntu7.5
libqt5x11extras5:amd64  5.5.1-3build1
libsodium23:amd64       1.0.16-0ppa3~xenial1
libstdc++6:amd64        5.4.0-6ubuntu1~16.04.10
libx11-6:amd64          2:1.6.3-1ubuntu2
libxi6:amd64            2:1.7.6-1
libxtst6:amd64          2:1.2.2-1
libykpers-1-1:amd64     1.17.2-1
zlib1g:amd64            1:1.2.8.dfsg-2ubuntu4.1
```

On my laptop, KeepassXC work's without any issues. I already tried to delete any entries/fields with {}, but that doesn't help.
All dependency libraries of KeepassXC are on both PCs exactly the same.

How can I better debug this error?

**Comment by phoerious** [comment] 2018-08-10 16:25
Duplicate of #1254. Unfortunately there is nothing we can do about it. Use the AppImage if it keeps happening.

**Closed by phoerious** 2018-08-10 16:25 UTC

**Comment by marvinwankersteen** [comment] 2018-08-10 18:04
Thanks for the fast reply. The AppImage works without problems.
