### ISSUE TITLE
Mac File Open Search does not find kdbx

### ISSUE THREAD

**Issue by metbril** [keepassxreboot/keepassxc#553] opened 2017-05-08 20:20 UTC
## Expected Behavior

Searching for (database) files is working, files are found.

## Current Behavior

When I try to open a file from the File Open menu a dialog opens. When I search for the term 'kdbx' (without the quotes) it does not find anything. When I search from a Finder window for 'kdbx' it finds my files. 

So it looks like the file search function in the application is not working properly.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* KeePassXC version/commit used: (can be found under Help -> About)
* Qt version (e.g. Qt 5.3): 
* Compiler (e.g. Clang++3.6.0): 
* Operating System and version: 

macOS 10.12.4 / KeepassXC 2.1.4

**Comment by weslly** [comment] 2017-05-18 04:12
I just tested on macOS Sierra and cannot reproduce this issue. 

Does the search work if you try to find `kdbx` files from other apps' open file dialog?

**Comment by weslly** [comment] 2017-06-08 02:11
Closing for now

**Comment by metbril** [comment] 2017-06-08 05:36
When I search directly from Finder I get to see search results. From the file open dialog I don't. I will try again and add some screenshots.

**Comment by weslly** [comment] 2017-06-08 13:02
@metbril Can you try it from the TextEdit.app open file dialog?

**Comment by metbril** [comment] 2017-06-08 18:40
Search: name contains 'kdbx'

## Finder

Search window from Finder.app. Files found.

![finder](https://user-images.githubusercontent.com/559346/26944854-31b20912-4c8a-11e7-8958-352c3ecf374f.png)

## TextEdit

File > Open dialog from TextEdit.app. Files showing.

![textedit](https://user-images.githubusercontent.com/559346/26944865-398eb950-4c8a-11e7-827e-995b3dd54b83.png)

## KeePassXC 2.1.4

File > Open dialog. Files **NOT** found. Please note I am using macOS in Dutch system language. Perhaps this is relevant.

![keepassxc](https://user-images.githubusercontent.com/559346/26944880-4413d6f8-4c8a-11e7-8e74-b2b5e999d246.png)

**Comment by weslly** [comment] 2017-06-08 18:42
Thanks for the screenshots, I'll reopen and test with another language.

**Comment by weslly** [comment] 2017-06-08 21:39
I changed the system language to dutch but still can't reproduce this:

![screen shot 2017-06-08 at 18 35 54](https://user-images.githubusercontent.com/107672/26951903-73d710f0-4c79-11e7-9271-33b27074b9bc.png)

**Comment by weslly** [comment] 2017-06-08 21:40
@metbril Can you test if it works after changing the system language to english?

**Comment by metbril** [comment] 2017-06-09 08:10
I have switch language from "system default"  (which will become Dutch) to "English". No files found, either. See screenshot. One thing I noticed is, that regardless of the Keepass UI language that is set, the dialog is always in English (compare below screenshot with that of my earlier comment).

![keepassxc-english](https://user-images.githubusercontent.com/559346/26966743-aa0ed590-4cfb-11e7-8de1-29d56f8d7442.png)

**Comment by weslly** [comment] 2017-06-29 02:42
@metbril Can you check if it works with v2.2.0?

**Comment by metbril** [comment] 2017-08-24 19:54
I have tried with 2.2.0 (locale nl-NL) and Mac OS X 10.12.6

It looks like it's working. When I choose File Open en search for kdbx I get to see al my files. :)

**Closed** 2017-08-24 19:54 UTC
Labels: macOS, not reproducible
