### ISSUE TITLE
Right click behavior on macOS

### ISSUE THREAD

**Issue by gyli** [keepassxreboot/keepassxc#3898] opened 2019-11-18 22:26 UTC
## Expected Behavior
Highlight an entry, right click on a blank area in the list, the options it pops up should be "New entry".

## Current Behavior
Currently the menu it pops up is options of selected items.

## Possible Solution
If one or more items are selected, I have to left-click on a blank area to de-select them, in order to pop up "New entry" menu.

## Steps to Reproduce
1. Highlight an entry
2. Right click on a non-highlighted area in the list
3. It will show the options of the selected item(s), while it should probably show "New entry" instead.

## Context
I found that my usual way to create a new entry does not work, since in current version, I have to make sure there is no entry highlighted, before creating a new entry through right click. Note that when switching to a group, the first entry is the default entry and it's pre-highlighted. So if you want to create a new entry under a group (without using the toolbar), you need to - choose the group, left-click on a blank area to de-select the default one, right-click on a blank area to pop up "New entry" option. 

I am not sure if it's a bug, but I think the previous and better behavior is right-click on blank area always calls "New entry" option. Only when right-click on highlighted items calls the menu for those items, like Copy username, Copy password, etc.

I know there is a similar ticket, https://github.com/keepassxreboot/keepassxc/issues/3839, but I don't think these are same issue. This one is more like a designing improvement.

## Debug Info
KeePassXC - Version 2.5.1
Revision: 0fd8836

Qt 5.13.1
Debugging mode is disabled.

Operating system: macOS Mojave (10.14)
CPU architecture: x86_64
Kernel: darwin 18.7.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by droidmonkey** [comment] 2019-11-19 00:38
Duplicate issue.

**Comment by droidmonkey** [comment] 2019-11-19 02:19
The problem is with Qt not deselecting the chosen row on right click in blank space. This bug also causes the issue seen in the related issue.

**Comment by droidmonkey** [comment] 2019-11-23 15:04
This is a duplicate of #3839. The same underlying issue in the Qt framework causes both.

**Closed by droidmonkey** 2019-11-23 15:04 UTC
Labels: bug
