### ISSUE TITLE
get segfault with --pw-stdin and MinimizeToTray=true

### ISSUE THREAD

**Issue by StefanIGit** [keepassxreboot/keepassxc#3943] opened 2019-11-28 08:50 UTC
Since 2.5.1 I get a segfault when I use the --pw-stdin and the MinimzeToTray=true option.
I use this script to auto unlock the db on login
`
secret-tool lookup keepass Database |keepassxc --pw-stdin /home/stefan/Documents/Database.kdbx
`

**Debug Info:**
KeePassXC - Version 2.5.1
Revision: 0fd8836

Qt 5.9.5
Debugging mode is disabled.

Operating system: Linux Mint 19.1
CPU architecture: x86_64
Kernel: linux 4.15.0-70-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.1

**keepassxc.ini**

[General]
AutoReloadOnChange=true
AutoSaveAfterEveryChange=true
AutoSaveOnExit=true
AutoTypeDelay=25
AutoTypeEntryTitleMatch=true
AutoTypeEntryURLMatch=true
AutoTypeStartDelay=500
BackupBeforeSave=true
DropToBackgroundOnCopy=false
FaviconDownloadTimeout=10
GlobalAutoTypeKey=0
GlobalAutoTypeModifiers=0
HideWindowOnCopy=false
IgnoreGroupExpansion=true
LastActiveDatabase=/home/stefan/Documents/Database.kdbx
LastChallengeResponse=@Variant(\0\0\0\x1c\0\0\0\0)
LastDatabases=/home/stefan/Documents/Database.kdbx
LastDir=/home/stefan/Desktop
LastKeyFiles=@Variant(\0\0\0\x1c\0\0\0\0)
LastOpenedDatabases=/home/stefan/Documents/Database.kdbx
MinimizeAfterUnlock=false
MinimizeOnCopy=true
MinimizeOnOpenUrl=false
OpenPreviousDatabasesOnStartup=true
RememberLastDatabases=true
RememberLastKeyFiles=true
SSHAgent=false
SingleInstance=true
UpdateCheckMessageShown=true
UseAtomicSaves=true
UseGroupIconOnEntryCreation=true

[Browser]
AllowExpiredCredentials=false
AlwaysAllowAccess=false
AlwaysAllowUpdate=false
BestMatchOnly=false
CustomProxyLocation=
Enabled=true
HttpAuthPermission=false
MatchUrlScheme=true
NoMigrationPrompt=false
SearchInAllDatabases=false
ShowNotification=true
SortByUsername=false
SupportBrowserProxy=true
SupportKphFields=true
UnlockDatabase=true
UpdateBinaryPath=true
UseCustomProxy=false

[FdoSecrets]
Enabled=false
NoConfirmDeleteItem=false
ShowNotification=true

[GUI]
CheckForUpdates=false
CheckForUpdatesIncludeBetas=false
CheckForUpdatesNextCheck=1575535015
DarkTrayIcon=true
HidePasswords=true
HidePreviewPanel=false
HideToolbar=false
HideUsernames=false
Language=system
ListViewState=@ByteArray(\0\0\0\xff\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\x1\x1\0\0\0\0\0\0\0\0\0\0\0\r\x1\0\0\0\0\x1\0\0\0\0\0\0\0\x64\0\0\x6\n\0\0\0\r\x1\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x64\0\0\0\x18\0\0\0\x81\0\0\0\0\0\0\0\r\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\x1l\0\0\0\x1\0\0\0\0\0\0\0\x64\0\0\0\x1\0\0\0\0\0\0\0\x64\0\0\0\x1\0\0\0\0\0\0\x1\x2\0\0\0\x1\0\0\0\0\0\0\0\x64\0\0\0\x1\0\0\0\0\0\0\0\x64\0\0\0\x1\0\0\0\0\0\0\0\x64\0\0\0\x1\0\0\0\0\0\0\0\x64\0\0\0\x1\0\0\0\0\0\0\0\x64\0\0\0\x1\0\0\0\0\0\0\0\x18\0\0\0\x1\0\0\0\x2\0\0\0\x64\0\0\0\x1\0\0\0\0\0\0\0\x64\0\0\0\x1\0\0\0\0\0\0\x3\xe8\x1\0\0\0\x64)
MainWindowGeometry=@ByteArray(\x1\xd9\xd0\xcb\0\x2\0\0\0\0\t\xa6\0\0\0\xd8\0\0\f\xc5\0\0\x3N\0\0\t\xa6\0\0\0\xf7\0\0\f\xc5\0\0\x3N\0\0\0\0\0\0\0\0\a\x80)
MainWindowState=@ByteArray(\0\0\0\xff\0\0\0\0\xfd\0\0\0\0\0\0\x3 \0\0\x2\x19\0\0\0\x4\0\0\0\x4\0\0\0\b\0\0\0\b\xfc\0\0\0\x1\0\0\0\x2\0\0\0\x1\0\0\0\xe\0t\0o\0o\0l\0\x42\0\x61\0r\x1\0\0\0\0\xff\xff\xff\xff\0\0\0\0\0\0\0\0)
MinimizeOnClose=false
MinimizeOnStartup=true
MinimizeToTray=true
MonospaceNotes=false
MovableToolbar=false
PreviewSplitterState=649, 264
SearchViewState=@ByteArray(\0\0\0\xff\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x4\xc8\0\0\0\r\x1\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x64\0\0\0\x18\0\0\0\x81\0\0\0\0\0\0\0\r\0\0\0\x64\0\0\0\x1\0\0\0\0\0\0\0\x64\0\0\0\x1\0\0\0\0\0\0\0\x64\0\0\0\x1\0\0\0\0\0\0\0\x64\0\0\0\x1\0\0\0\0\0\0\0\x64\0\0\0\x1\0\0\0\0\0\0\0\x64\0\0\0\x1\0\0\0\0\0\0\0\x64\0\0\0\x1\0\0\0\0\0\0\0\x64\0\0\0\x1\0\0\0\0\0\0\0\x64\0\0\0\x1\0\0\0\0\0\0\0\x64\0\0\0\x1\0\0\0\0\0\0\0\x18\0\0\0\x1\0\0\0\x2\0\0\0\x64\0\0\0\x1\0\0\0\0\0\0\0\x64\0\0\0\x1\0\0\0\0\0\0\x3\xe8\x1\0\0\0\x64)
ShowTrayIcon=true
SplitterState=284, 1612
ToolButtonStyle=0

[KeeShare]
QuietSuccess=true
Settings.active="<?xml version=\"1.0\"?>\n<KeeShare xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\">\n  <Active/>\n</KeeShare>\n"
Settings.foreign="<?xml version=\"1.0\"?>\n<KeeShare xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\">\n  <Foreign/>\n</KeeShare>\n"
Settings.own="<?xml version=\"1.0\"?>\n<KeeShare xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\">\n  <PrivateKey/>\n  <PublicKey/>\n</KeeShare>\n"

[security]
HidePasswordPreviewPanel=true
IconDownloadFallback=false
autotypeask=true
clearclipboard=true
clearclipboardtimeout=20
clearsearch=true
clearsearchtimeout=5
hidenotes=false
lockdatabaseidle=false
lockdatabaseidlesec=240
lockdatabaseminimize=false
lockdatabasescreenlock=false
passwordemptynodots=true
passwordscleartext=false
passwordsrepeat=true
relockautotype=false
resettouchid=false
resettouchidscreenlock=true
resettouchidtimeout=30

**Comment by droidmonkey** [comment] 2019-11-29 18:40
This is most likely a duplicate of #3887

**Comment by droidmonkey** [comment] 2019-12-29 14:02
I cannot replicate this at all.

**Closed by droidmonkey** 2019-12-29 14:02 UTC
Labels: bug, in triage
