### ISSUE TITLE
KeepassXC as system keyring on Linux

### ISSUE THREAD

**Issue by jleclanche** [keepassxreboot/keepassxc#1109] opened 2017-10-22 19:21 UTC
This is a bit of a long shot but I've been thinking about the lack of system keyring on [LXQt](http://lxqt.org) and it hit me that, with some work, there's no reason why KeepassXC couldn't *be* the system keyring.

On linux: What is a system keyring? GNOME Keyring and KWallet are system keyrings. For standardization purposes, they both implement the [Secret Service API](https://specifications.freedesktop.org/secret-service/), which is a DBus based API.

The meat of it:
- The secret service handles secure storage of secrets at rest
- The service is able to [open sessions over DBus](https://specifications.freedesktop.org/secret-service/ch06.html)
- In sessions, clients are able to [securely ask and receive secrets](https://specifications.freedesktop.org/secret-service/ch07.html)
- The service [may require items to be unlocked before being accessed](https://specifications.freedesktop.org/secret-service/ch08.html).

If KeepassXC wanted to implement this, most of the work would be in adapting it to the DBus API, as its model is already essentially fully implemented. It would also probably be worth keeping separate to the KeepassXC core (some kind of plugin? Enable on demand?).
Another hard bit to answer for would be: How do items map to the ones advertised by the system keyring? Maybe they don't, maybe there's a special database (or table in an existing database) for the system stuff.

Thoughts? I don't know if I would have time to work on it myself, but I figured I would at least throw the idea out there to see how it's received.

**Comment by phoerious** [comment] 2017-10-22 19:22
This is a duplicate of #440

**Closed by phoerious** 2017-10-22 19:22 UTC

**Comment by jleclanche** [comment] 2017-10-22 19:24
@phoerious It is not. #440 proposes adding support for fetching keys from the system keyring (a secret-service client). In this issue, I am proposing for KeepassXC to *be* the secret service.

**Comment by phoerious** [comment] 2017-10-22 19:26
#440 suggests both.

**Comment by jleclanche** [comment] 2017-10-22 19:27
Alright, I'll move discussion there.
