### ISSUE TITLE
Browser: option to only look at parent domains when matching

### ISSUE THREAD

**Issue by tails618** [keepassxreboot/keepassxc#6916] opened 2021-09-14 23:13 UTC
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
The browser extension already has an option to only save domains, not URLs. This feature would allow it to only read URLs for existing logins as well.

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
I recently moved over from Bitwarden and my library of hundreds of logins now has exact URLs, rather than domains - this is a problem when I want to login to a website like onedrive.live.com but my login is set to login.live.com. Having it be an option to read only the root domain would eliminate this issue.

**Comment by droidmonkey** [comment] 2021-09-15 01:45
Onedrive.live.com and login.live.com are two different domains. They share a parent domain, but ultimately they are different. We could possibly provide an option to only look at the parent domain, but that won't be the default behavior. We do strict domain and subdomain matching for security and scoping reasons.

**Comment by tails618** [comment] 2021-09-15 01:48
Just for my own curiosity, what security benefits does not just looking at the parent domain add?

**Comment by droidmonkey** [comment] 2021-09-15 04:49
A domain is just a name for an ip address. It is quite possible to have completely different sites, one legit and one nefarious, under the same parent domain name.

**Comment by droidmonkey** [comment] 2023-08-19 19:53
@varjolintu this could be added as a feature flag on the browser settings page for the entry.

**Comment by varjolintu** [comment] 2023-08-20 05:03
@droidmonkey Sure. Gotta remember this is related to the annoying top-level-domain issue where Qt lacks a proper function for it.

**Comment by droidmonkey** [comment] 2024-08-18 18:16
Duplicate of #6519

**Closed as not planned by droidmonkey** 2024-08-18 18:16 UTC
Labels: duplicate, feature: Browser
