### ISSUE TITLE
Crash when deleting entries "for good", when selected via a search

### ISSUE THREAD

**Issue by bipox** [keepassxreboot/keepassxc#383] opened 2017-03-08 07:31 UTC
keepassxc 2.1.2

## Steps to Reproduce (for bugs)
1. delete entry
2. search for deleted entry using the search function
3. delete "for good"
4. app crash

Delete from the recycle bin folder directly works fine

## Your Environment
* Qt version: 5.8.0
* Operating System and version: Manjaro Linux x64

**Comment by TheZ3ro** [comment] 2017-03-08 09:47
Possible duplicate of #369

**Comment by bipox** [comment] 2017-03-08 10:16
You're right. Sorry 'bout that.

Great app btw.

**Comment by TheZ3ro** [comment] 2017-03-08 10:57
Thanks :) Closing this

**Closed by TheZ3ro** 2017-03-08 10:57 UTC
