### ISSUE TITLE
Crash on unlocking Windows 10

### ISSUE THREAD

**Issue by dmnk** [keepassxreboot/keepassxc#1862] opened 2018-04-19 07:39 UTC
Start and unlock keepassxc

Lock windows session (e.g. with [win]+[L]).
Unlock (secure sign-in enabled, so to get the password input field [strg]+[alt]+[del] has to be pressed).

Error messsage pops up (above login screen):
Unhandled exception at 0x0000000066767002 (Qt5Core.dll) in KeePassXC.exe: 0xC0000005: Access violation writing location 0x000000000000000C.

## Expected Behavior
keepassxc shouldn't die

## Current Behavior
i guess it's trying to identify the password field?

## Possible Solution
haven't got the debug symbols right now, but look into what happens at the mentioned address.

## Steps to Reproduce (for bugs)
see introduction

## Context
see introduction

## Debug Info
KeePassXC - Version 2.3.1
Revision: 2fcaeea

Bibliotheken:
- Qt 5.10.1
- libgcrypt 1.8.2

Betriebssystem: Windows 10 (10.0)
CPU-Architektur: x86_64
Kernel: winnt 10.0.16299

Aktivierte Erweiterungen:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP) <- but deactivated
- SSH Agent
- YubiKey

Libraries:
- LIBS

Operating system: OS
CPU architecture: ARCH
Kernel: KERNEL

Enabled extensions:
- EXTENSIONS

**Comment by OlivierMary** [comment] 2018-05-04 19:15
Hi,

duplicate of #1561 ?

**Comment by phoerious** [comment] 2018-05-07 06:43
Yes, it's a duplicate.

**Closed by phoerious** 2018-05-07 06:43 UTC
Labels: bug, platform: Windows
