### ISSUE TITLE
New Entry Option - Notes

### ISSUE THREAD

**Issue by ghost** [keepassxreboot/keepassxc#7001] opened 2021-09-30 10:11 UTC
## Summary
Entry with only Notes 

## Context
Other Password Managers such as Bitwarden, 1Password and Dashlane, etc. provide an called notes which is just an Entry with Notes Box with No Username, Password and TOTP Field.

When Importing or Exporting (and using it in Another Password Manager), Those Notes are converted as an Entry in KeePass Database like a Password entry - Notes is in Notes Field, But Username and Passwords are just some extra thing. This also acts vice versa in other Password Managers too. 

I think that this should be a Must as it differentiates Passwords from Notes and Easy for Productivity.

I think that this can be implemented as it is just a new Template with the Removal of 2 Fields.

**Comment by droidmonkey** [comment] 2021-09-30 12:29
Duplicate of #863

**Closed as completed by droidmonkey** 2021-09-30 12:29 UTC
Labels: duplicate
