### ISSUE TITLE
[Suggestion] Ability to make the preview area smaller than currently possible

### ISSUE THREAD

**Issue by hart0** [keepassxreboot/keepassxc#5252] opened 2020-08-10 19:11 UTC
## Summary
I have my KeePassXC (2.6.0) set up in compact mode so the icons are smaller than they normally would be. With the size of my KeePassXC window, the preview area still takes up 50% of the view at a minimum (unless I disable it by dragging it down all the way). I don't have notes in most of my entries, but when I do I usually double click the entry to view them since they are often larger amounts than what can be displayed in the preview. So in my case, most of what the preview area shows is either already displayed in the main entry view (Username, URL, optionally Password/Small amount of notes) for each entry or is empty space (when there are no notes).

I suggest the ability to be able to further decrease the size of the preview section, maybe so you can drag it down where the [area below the green line is hidden](https://i.imgur.com/fVvCCUp.png).

## Examples
[Video](https://gfycat.com/angrycookedkodiakbear) showing the preview area size compared to the whole window, and trying to make it smaller

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
This would improve usability by allowing me to see significantly more entries at a time in the entries view, hiding what is usually empty or unneeded space in the preview tab without completely hiding it by dragging it down all the way. I would prefer having it be smaller as opposed to hiding it entirely which is currently possible.

**Comment by droidmonkey** [comment] 2020-08-10 20:00
Duplicate of #4989

**Closed by droidmonkey** 2020-08-10 20:00 UTC
Labels: new feature
