### ISSUE TITLE
[Linux] tray icon not showing / infinite loop leads to crash

### ISSUE THREAD

**Issue by glubsy** [keepassxreboot/keepassxc#683] opened 2017-06-26 22:17 UTC
The system tray icon is missing. I'm running i3 window manager on Antergos / Arch Linux. 

When I enable the feature in the "settings", I get an error message in stdout in an infinite loop, which causes keepassxc to hang until I kill it.:
`QSystemTrayIcon::setVisible: No Icon set`

Using the 2.2.0 Appimage works fine and shows the icon in tray and doesn't produce this error. 

Seems to be a missing dependency? 

## Expected Behavior
Tray icon should show up in i3 tray and not crash. 

## Current Behavior
Tray icon doesn't show up in i3 tray and crashes with error message.

If I set the tray icon "on" in the Appimage, it will be written to some config file somewhere and when starting the "installed" keepassxc it will get stuck in the loop (obviously) at startup. Have to reset the setting in the Appimage or edit the config file. ;)

## Possible Solution
Might be how the source code handle the theme as show [here](https://classicforum.manjaro.org/index.php?topic=23137.0) (which is working fine by the way)?

## Your Environment
* KeePassXC version/commit used: 2.2.0 Revision: caa49a8ef3ee28ed478192389b21d61107b3b8e0
* Qt version (e.g. Qt 5.3): Qt 5.9.0
* Operating System and version: Antergos Linux x86_64 kernel 4.9.33-1-lts

Here are some potentially relevant variables from my the keepassxc env:
```
$ sudo cat /proc/$(pidof keepassxc)/environ | xargs --null --max-args=1 --
DESKTOP_SESSION=i3 (with debug log)
QT_QPA_PLATFORMTHEME=kde
GTK_MODULES=canberra-gtk-module
PATH=/home/user/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
```

I have KDE Plasma 5 installed, along with Xfce 4. I use qt5ct to configure themes usually (and the theme works great in keepassxc).
I'm also using the Numix icon set but it seems to be working fine

Looking at the environment from the Appimage, I might be missing some dependency perhaps? 
The package for Arch only list these as dependencies:
`Depends On      : hicolor-icon-theme  libxtst  qt5-x11extras`
Since it works with the bundled libs in the Appimage, should I report to the package maintainer instead?

**Comment by phoerious** [comment] 2017-06-26 22:23
Could you try unsetting XDG_DATA_DIRS in a terminal and run it again?

**Comment by glubsy** [comment] 2017-06-26 22:37
XDG_DATA_DIRS not existing, still happening. 
Tried fiddling with the bundled libs in the Appimage trying to LD_PRELOAD them but it doesn't seem to work (or I'm doing it wrong).

**Comment by phoerious** [comment] 2017-06-26 22:39
I'm not sure what the problem is, but I suspect some unfortunate interaction between how the package was built and how it is used on your system. I doubt it's something we can fix upstream.

**Comment by glubsy** [comment] 2017-06-26 22:41
I have changed this variable: 
QT_QPA_PLATFORMTHEME=kde
to this
QT_QPA_PLATFORMTHEME=qt5ct

The theme changed, and the icon displays fine. So it's something to do with the icon missing from the theme that's applied somehow? Not ideal...

**Comment by phoerious** [comment] 2017-06-26 22:43
I doubt it's the icon missing (it's not in the theme anyway). I suppose it's rather some interaction bug with the platform theme engine.

**Comment by glubsy** [comment] 2017-06-26 22:59
Thanks anyway. I've always had trouble with theming Qt programs the right way. 

This is with the QT_QPA_PLATFORMTHEME unset or set to "qt5ct": 
![](http://i.imgur.com/1kIxrzd.png)

This is with the QT_QPA_PLATFORMTHEME=kde
![](http://i.imgur.com/HaxoxjG.png)

Too bad the icon tray makes it crash.

**Comment by phoerious** [comment] 2017-06-26 23:10
Okay, so your theme does have a custom icon. Can you try using a different icon theme?

**Comment by glubsy** [comment] 2017-06-26 23:17
I've just tried messing around between the KDE Plasma settings (via `systemsettings5`) and qt5ct (changing my theme to "Breeze" now) and now it works. I'm not using the dark theme I was using anymore, but it's not crashing at least. 

Haven't changed the icon theme though, it's still Numix.

I was using QtCurve before (I think, it's so messy can't really tell):
![](http://i.imgur.com/X9rkAJL.png)

Changed to this and it works: 
![](http://i.imgur.com/S1uo7RT.png)
![](http://i.imgur.com/RlEJcWM.png)

**Comment by phoerious** [comment] 2017-06-26 23:21
So probably a platform bug due to theming inconsistencies. Can I close this then?

**Comment by glubsy** [comment] 2017-06-26 23:22
Thanks for your time. Love this project very much (been using Keepass with mono up until recently, I think I'll use keepassxc from now on). :)

**Closed** 2017-06-26 23:22 UTC

**Comment by glubsy** [comment] 2017-06-26 23:28
Oh by the way, I think I found what was causing the problem: 

in `systemsettings5` -> Colors, I was using a color scheme (Wonton Soup). Applying any one of those color scheme seem to crash. Could be a KDE bug then... not sure.

![](http://i.imgur.com/DW72gU1.png)

`export QT_QPA_PLATFORMTHEME="kde" ; keepassxc` -> will crash.

**Comment by phoerious** [comment] 2017-06-26 23:29
If it's related the the color scheme it is most likely a KDE bug.

**Comment by glubsy** [comment] 2017-06-26 23:35
On second thought, I think it's a bug caused by the interactions between qt5ct and the messy KDE theming. Some things must be overlapping somewhere. 
I think I'll blame KDE. :P

**Comment by phoerious** [comment] 2017-06-26 23:36
You should consider filing a report at bugs.kde.org.
