### ISSUE TITLE
MacOS GUI completely broken / unusable

### ISSUE THREAD

**Issue by thrdroom** [keepassxreboot/keepassxc#745] opened 2017-07-04 09:37 UTC
I wanted to switch from KeepassX to KeepassXC in my company. Sadly the whole GUI is broken on all our macs which makes the programm unusable here :(

## Expected Behavior

Programm should be running smooth like the original KeepassX

## Current Behavior

When opening the programm the whole GUI gets messed up and none of the functions and buttons are useable. Opening kdbx files renders nothing. Documented on video with two macs, see below.

## Steps to Reproduce (for bugs)

Watch the Bug-Video of Mac1
[![Watch the Bug-Video of Mac1](https://raw.github.com/GabLeRoux/WebMole/master/ressources/WebMole_Youtube_Video.png)](http://sendvid.com/wzmmybeg)

Watch the Bug-Video of Mac2
[![Watch the Bug-Video of Mac2](https://raw.github.com/GabLeRoux/WebMole/master/ressources/WebMole_Youtube_Video.png)](http://sendvid.com/qm17qfgq)

## Debug Info

The debuginfos are equal for all of our macs

KeePassXC - Version 2.2.0
Revision: caa49a8ef3ee28ed478192389b21d61107b3b8e0

Libraries:
- Qt 5.9.0
- libgcrypt 1.7.7

Operating system: OS X Mavericks (10.9)
CPU architecture: x86_64
Kernel: darwin 13.4.0

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

**Comment by phoerious** [comment] 2017-07-04 10:03
Can anybody else reproduce this with OS X 10.9 or older?

**Comment by thrdroom** [comment] 2017-07-04 11:50
I haven't tried to build it myself - too many dependencies for a workstation here. (no xcode, brew etc...)

**Comment by phoerious** [comment] 2017-07-04 13:20
Would be great if you could find a Maverick machine on which you could try building KeePassXC. This is most likely some library issue. Our binaries were built on 10.12.

**Comment by gretraholisi** [comment] 2017-07-04 13:55
GUI behaves ok on El Capitan with the pre-built app.

**Comment by thrdroom** [comment] 2017-07-12 12:18
No chances of getting an build-environment working properly!
I’ve set up a mavericks environment.

Installed brew and tried to install all the dependencies, and from there on the problems began.
"brew install qt5“ failed cause there was no qt5 for mavericks 10.9.5 in the brew repo.

So i downloaded an installer for qt5 from them homepage and installed it by hand.
Same problem with libgcrypt…build would fail with libgcrypt from brew and with the default from mavericks.

As stated in a blogpost about building keepassx (lost the link) I’ve commented out the libgcrypt-check.
After fiddling around for a while with custom-paths for the qt5 install and libgcrypt the cmake went successfully.

But when i tried to run "make -j8 package“ it fails with build errors.
**After 3 hours wasted without the ability to get a proper build i quit!**

This is too much hassle and too much time for simply just getting a simple peace of software running as alternative to **keepassx which btw runs fine ootb on mavericks and even older.**
Can someone else please get this done in an mavericks environment?

And could the team of the app please get an release working with at least mavericks?
A lot of companies i know stay with mavericks for stability and other reasons.

Thanks

**Comment by phoerious** [comment] 2017-07-12 12:25
You don't need to resort to old KeePassX blog posts to build KeePassXC. We have a comprehensive and up-to-date guide in our wiki: https://github.com/keepassxreboot/keepassxc/wiki/Building-KeePassXC# macOS (make sure you also follow the build environment setup instructions).

You want to know the reason why we do not provide Mavericks builds? Well, we simply can't. None of us has Mavericks at home and there are no publicly available virtual machine images available.

**Comment by thrdroom** [comment] 2017-07-13 06:49
Thanks for the clarification.
But i did exactly that. I followed this two guides:

[https://github.com/keepassxreboot/keepassxc/wiki/Set-up-Build-Environment-on-OS-X](https://github.com/keepassxreboot/keepassxc/wiki/Set-up-Build-Environment-on-OS-X)
[https://github.com/keepassxreboot/keepassxc/wiki/Building-KeePassXC](https://github.com/keepassxreboot/keepassxc/wiki/Building-KeePassXC)

Following this two guides i wasn’t able to start „cmake“ cause it was neccesary to comment out some lines from the „CMakeLists.txt“ file which are related to the zlib check. This was documented in some blogpost (about building KeepassX) i found googling about the error with zlib.

Well i think the problem with the Mavericks builds can then be easily solved as i can provide you with a virtual machine image ;)
Is a virtual box image file fine or which format would you need?

**Comment by phoerious** [comment] 2017-07-13 07:58
Virtual Box is fine.

**Comment by thrdroom** [comment] 2017-07-13 12:29
Ok i got it. Here it is: [https://www.hidrive.strato.com/lnk/L4OPOvdn](https://www.hidrive.strato.com/lnk/L4OPOvdn) If you need something more like the install-medium let me know

**Comment by thrdroom** [comment] 2017-07-14 12:45
I forgot to tell you the login credentials for the VM.

**username:** vmuser
**password:** password

**Comment by weslly** [comment] 2017-07-15 02:41
KeepassXC v2.2.0 is built with Qt 5.9, which requires at least OSX 10.10, so you would need to build it from sources using Qt 5.8 to support Mavericks.

https://doc.qt.io/qt-5/supported-platforms-and-configurations.html

Related: #768

**Comment by thrdroom** [comment] 2017-07-15 16:25
I see...
Can you then please start to build the future releases of Keepassxc with Qt 5.8 instead?

Thanks

**Comment by weslly** [comment] 2017-07-16 15:21
Well, technically it is not impossible, but IMHO that wouldn't make sense to downgrade it now since eventually we would need to upgrade it again after a couple of versions due to new code being added that make use of new Qt features. 

That would also potentially break the build environment of everyone using 5.9 to compile KeepassXC and maybe even some distro packages that already require 5.9, since sometimes there's something that works on 5.8 but not on 5.9 (eg. #528). Even [homebrew already uses 5.9 as its default Qt version](https://github.com/Homebrew/homebrew-core/pull/14109
) and doesn't even have 5.8 available (strangely enough, it has 5.5 and 5.7), so it would confuse people trying to compile KeepassXC on their macs and require them to download the 5.8 package from Qt website instead.

Also, I noticed Qt 5.9 feels a lot more stable on newer macOS versions than 5.8, so I'm not sure it would be worth to make the app more prone to random crashes in exchange of supporting an old version of macOS that would have to become unsupported again soon.

@keepassxreboot/core-developers what do you guys think?

**Comment by phoerious** [comment] 2017-07-16 17:29
We actually don't use any Qt 5.9 features. The minimum supported version is still Qt 5.2. However, those old versions have countless bugs (including crashes) which are fixed in newer versions. Qt 5.9 is also a new LTS release.

> (strangely enough, it has 5.5 and 5.7)
Qt 5.6 is the previous LTS release, so it would make sense to have that. Not sure why they have 5.5 and 5.7, though.

**Comment by thrdroom** [comment] 2017-07-21 14:31
What is the direction this conversation is going? Do we have any consent about what Qt version to use? Anyone problems with going the 5.6 way?

**Comment by phoerious** [comment] 2017-07-21 14:50
I'm not quite sure what direction to go. Downgrading Qt is not a permanent fix and may create other issues. I don't know how common Mavericks still is, but officially, it has already reached its end of life. So how long do we build with old Qt versions to support old EOL OS X versions?

I feel like creating a guide how to build for legacy OS X would be a better solution.

**Comment by thrdroom** [comment] 2017-07-21 15:15
Maybe you could orient on the other apps for keepass-databases like OG KeepassX and Keeweb. Both run fine on at least mavericks or even older versions of macOS.

**Comment by phoerious** [comment] 2017-07-21 15:17
That's not really a good measure. KeepassX uses Qt 4 and hasn't seen a new release in a very long time. KeeWeb is a web application and will never suffer these issues as long as Webkit runs on the platform.

**Comment by droidmonkey** [comment] 2017-07-22 03:29
This is akin to asking for Windows xp support... Just saying

**Comment by thrdroom** [comment] 2017-07-24 08:16
Not even CLOSE @droidmonkey Windows XP and macOS Mavericks is ain't the same ballpark, it ain't the same league, it ain't even the same god damn sport! XP was released 2001, mavericks was end of 2013. You are comparing apples and oranges for just having a polarizing statement. Asking for mavericks support is maybe comparable to asking for windows 8 support, which is not a big deal – I think! If you don’t wanna support it ok fine, then left out users with a pretty good OS that’s just 4 years old – but don’t come up with arguments like that. This is something which frustrates m. Almost every software I use is still compatible with mavericks and still gets updates - but only yours wont. Every new update after mavericks is a privacy, performance and battery nightmare and it gets worse and worse with every update – kinda like windows 10. So i hope you reconsider your thoughts on mavericks-support cause its not even a big deal for you in perspective of development – but it is for users who simply just need a small simple app without the need of having a building environment and the knowledge of handling building errors.

**Comment by gagarine** [comment] 2017-08-13 14:30
"This is too much hassle and too much time for simply just getting a simple peace of software running as alternative to keepassx which btw runs fine ootb on mavericks and even older." 
exactly.
So if you can't upgrade to a recent macOS you can use keepassx. Using older version of library can have unattended consequences.

**Comment by BenjaminDeuter** [comment] 2017-08-14 12:19
> Asking for mavericks support is maybe comparable to asking for windows 8 support

[Wikipedia](https://en.wikipedia.org/wiki/OS_X_Mavericks) lists OS X Mavericks support status as "Unsupported as of September 2016, iTunes ended in August 2017", citing the [Apple Security Updates page](https://support.apple.com/en-us/HT201222).

By contrast, Extended Support for Windows 8 (with the Windows 8.1 upgrade) is to be expected until 2023-01-10 [according to Microsoft](https://support.microsoft.com/en-us/help/13853/windows-lifecycle-fact-sheet).

In my humble opinion, it is not the fault of the KeePassXC Developers that Apple decides to drop support for some of their operating system releases much sooner than Microsoft does.

**Comment by thrdroom** [comment] 2017-09-20 07:54
@BenjaminDeuter Of course it is the fault of the KeePassXC developers to drop support for older os-versions (which wouldnt be a big hassle for them) only because apple says "yeah lets throw out new versions of our OS ever half/full year which renders good working hardware useless". And also force user to adopt their behavior of crippling down MacOS with every "new feature" they implement.

No sorry i simply totally disagree. People who are working seriously and want to avoid some cloud-BS like the creative-cloud from adobe or some other creepy privacy invasion-"features" need to stay away from everything that comes after mavericks. (BTW i hope this changes in future but im not really sanguine about it.)

E.g. our design-appartement HAS to stay on mavericks for the fact of still beeing able to use Adobe CS6 Master Collection. Besides all of this, i want to throw in the fact that EVERY software we use (and we use a lot of tools) are still getting updates for mavericks, Only KeePassXC thinks the short release-cicles of apple are a "good thing" to adopt and they should just leave out users with still pretty good OS-versions.

So thats it for me, i dont want to waste anymore of my time cause i really think that all of you just dont get what i want to tell you. As long as this software (and their developers) is excluding people with my kind of thinking and concerns it is dead to me. kthxbye

**Comment by TheZ3ro** [comment] 2017-09-20 10:17
We are not excluding anybody. This project is open source, we are not payed by anybody for doing this, we are not a company and we offer free support on almost every single issue. 

Asking (requiring) developers to build a custom version for a specific platform and with specific requirements it's not a thing. We ship binaries compiled with the latest version of Qt to keep our user updated, if that's not supported on your platform you can download the source code and build it yourself.
This is the spirit of open-source, freedom over the code.

If you want a custom solution, simply pay for it. I will build your Maverick binary personally.
But since we are doing it for free as an hobby, we decide what it's the best for most of our users.
(And you still can modify/build/distribute KeePassXC binaries yourself.)

> As long as this software (and their developers) is excluding people with my kind of thinking and concerns it is dead to me.

You are disrespecting our work and Us as individuals.

**Closed by TheZ3ro** 2017-09-20 10:17 UTC
