### ISSUE TITLE
Mac: KPXC 2.5.3 - crashing right after start

### ISSUE THREAD

**Issue by WeirdCircumstances** [keepassxreboot/keepassxc#4481] opened 2020-03-25 10:16 UTC
Right after upgrade to the newest version via homebrew, program keeps crashing and is unable to open. My solution for now is switching back to older release.

System here: MacOS Catalina 10.15.4, KeepassXC 2.5.3 - updated couple minutes ago via brew upgrade. More infos below.

Problem report:
```
Process:               KeePassXC [7625]
Path:                  /Applications/KeePassXC.app/Contents/MacOS/KeePassXC
Identifier:            org.keepassx.keepassxc
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           KeePassXC [7625]
User ID:               501

Date/Time:             2020-03-25 11:04:13.811 +0100
OS Version:            Mac OS X 10.15.4 (19E266)
Report Version:        12
Anonymous UUID:        E37F32D9-66E1-8759-94B7-943598DCB11A

Sleep/Wake UUID:       5C53A00A-2579-4C19-8F59-46ABB0068FC4

Time Awake Since Boot: 3500 seconds
Time Since Wake:       2500 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (Code Signature Invalid)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace CODESIGNING, Code 0x1

kernel messages:

VM Regions Near 0 (cr2):
--> 
    __TEXT                 0000000107620000-00000001079b2000 [ 3656K] r-x/r-x SM=COW  

Thread 0 Crashed:
0   ???                           	0x0000000111167000 _dyld_start + 0

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x0000000000000000  rcx: 0x0000000000000000  rdx: 0x0000000000000000
  rdi: 0x0000000000000000  rsi: 0x0000000000000000  rbp: 0x0000000000000000  rsp: 0x00007ffee85dfc10
   r8: 0x0000000000000000   r9: 0x0000000000000000  r10: 0x0000000000000000  r11: 0x0000000000000000
  r12: 0x0000000000000000  r13: 0x0000000000000000  r14: 0x0000000000000000  r15: 0x0000000000000000
  rip: 0x0000000111167000  rfl: 0x0000000000000200  cr2: 0x0000000000000000
  
Logical CPU:     0
Error Code:      0x00000000
Trap Number:     0


Binary Images:
       0x107620000 -        0x1079b1fff +??? (0) <16AE8CED-0E4C-3291-AE43-913B0D7192FF> (null)
       0x111166000 -        0x1111f7eff +??? (750.5) <1F893B81-89A5-3502-8510-95B97B9F730D> (null)

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 2923
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=4776K resident=0K(0%) swapped_out_or_unallocated=4776K(100%)
Writable regions: Total=8408K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=8408K(100%)
 
                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
STACK GUARD                       56.0M        1 
Stack                             8192K        1 
__DATA                             360K        4 
__DATA_CONST                        20K        1 
__LINKEDIT                         536K        2 
__TEXT                            4240K        2 
shared memory                        8K        2 
===========                     =======  ======= 
TOTAL                             69.0M       13 

Model: MacBookPro12,1, BootROM 190.0.0.0.0, 2 processors, Dual-Core Intel Core i5, 2,7 GHz, 8 GB, SMC 2.28f7
Graphics: kHW_IntelIris6100Item, Intel Iris Graphics 6100, spdisplays_builtin
Memory Module: BANK 0/DIMM0, 4 GB, DDR3, 1867 MHz, 0x02FE, 0x4544464132333241324D412D4A442D460000
Memory Module: BANK 1/DIMM0, 4 GB, DDR3, 1867 MHz, 0x02FE, 0x4544464132333241324D412D4A442D460000
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x133), Broadcom BCM43xx 1.0 (7.77.111.1 AirPortDriverBrcmNIC-1600.4)
Bluetooth: Version 7.0.4f6, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB 3.0 Bus
USB Device: Bluetooth USB Host Controller
Thunderbolt Bus: MacBook Pro, Apple Inc., 27.1
```

When there is more info needed on this behavior, please let me know (and how to get those infos ;)

Thanks for reading :)

**Comment by phoerious** [comment] 2020-03-25 10:18
Duplicate of #4398.

**Closed by phoerious** 2020-03-25 10:18 UTC
Labels: bug
