### ISSUE TITLE
Indentation of the "user name" text field

### ISSUE THREAD

**Issue by trockenasche** [keepassxreboot/keepassxc#5339] opened 2020-08-25 20:29 UTC
## Overview
The indentation of the "user name" text field is different from all other text fields.
The username is indented further to the left under the light and dark theme.
Under the Classic Theme it is exactly the other way round.
![grafik](https://user-images.githubusercontent.com/2905450/91224117-e8916080-e721-11ea-911c-f54a76ee6eeb.png)
![grafik](https://user-images.githubusercontent.com/2905450/91224130-ecbd7e00-e721-11ea-9461-f54876f3ead2.png)

## Steps to Reproduce
Just open any entry.

## Expected Behavior
All text fields should appear in one line.

## Actual Behavior
The text fields aren't in one line.

[NOTE]:
KeePassXC - Version 2.6.1
Revision: 9a35bba

[NOTE]: #
Operating System: Windows **and** Linux
Desktop Env: Gnome
Windowing System: X11

**Comment by phoerious** [comment] 2020-08-25 20:34
That's an interesting variant of this bug which I haven't seen yet.

**Comment by droidmonkey** [comment] 2020-08-25 20:47
Literal duplicate of #5321

**Closed by droidmonkey** 2020-08-25 20:47 UTC
Labels: bug
