### ISSUE TITLE
Colour key - Numbers, Letters and Special Character numbers

### ISSUE THREAD

**Issue by hzeeer** [keepassxreboot/keepassxc#5750] opened 2020-11-26 10:00 UTC
## Summary
This would be a simple colour code to help differentiate number an letters for people that struggle.
I would also suggest different settings/configuration for those that have difficulty with colour blindness.

## Examples
Letter to be normal Black
Numbers to be Green text 
Special Characters to be Red to make them stand out!

## Context
I have difficulty seeing he difference between certain numbers and letters e.g. 1 and L. 
My friend is colour blind to options to customise the colours would be helpful for him.

**Comment by phoerious** [comment] 2020-11-26 10:03
Duplicate of #4099.

**Closed by phoerious** 2020-11-26 10:03 UTC
Labels: new feature
