### ISSUE TITLE
Add option for building CLI-tool only

### ISSUE THREAD

**Issue by wallisers** [keepassxreboot/keepassxc#4631] opened 2020-04-20 09:31 UTC
## Summary
Add an option for building only the CLI-tool (`keepassxc-cli`) without the GUI elements.

## Context
This would be great for using KeePassXC in a minimalist setup: Preventing the need for bloaty GUI libraries, while still being able to benefit from the great browser integration.

**Comment by phoerious** [comment] 2020-04-20 09:56
Pretty much a duplicate of #1714.

**Closed by phoerious** 2020-04-20 09:56 UTC
Labels: new feature
