### ISSUE TITLE
Chrome addon - Injected stylesheet affects web page content

### ISSUE THREAD

**Issue by Mooninaut** [keepassxreboot/keepassxc#3582] opened 2019-09-26 17:57 UTC
## Expected Behavior
The KeePassX Chrome extension does not affect the rendering of page content, other than form fields

## Current Behavior
The injected stylesheet has the following section:

.separator {
    height: 100% !important;
    border-left: 1px solid rgb(204, 204, 204);
    margin: 10px !important;
}

This affects web page content that uses the CSS class "separator".

## Possible Solution
Use an application-specific CSS class name, such as "keepassxc-extension-separator" that would not likely appear in any web page.

## Steps to Reproduce
In Chrome, with the KeePassXCBrowser extension enabled https://chrome.google.com/webstore/detail/keepassxc-browser/oboonakemofpalcgghocfoadofidjkkk visit https://codepen.io/mooninaut/pen/GRKLmrG

## Context
This affects the web application I test as part of my job, which means I have to disable the Chrome extension.

## Debug Info
Chrome extension version: 1.5.0, released today (September 26, 2019)

KeePassXC - Version 2.4.3
Revision: 5d6ef0c

Qt 5.12.3
Debugging mode is disabled.

Operating system: macOS Mojave (10.14)
CPU architecture: x86_64
Kernel: darwin 18.7.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.4

**Comment by droidmonkey** [comment] 2019-09-26 19:44
Duplicate of an issue over on the extension board.

**Closed by droidmonkey** 2019-09-26 19:44 UTC
Labels: bug
