### ISSUE TITLE
After upgrade to 2.7.3 on Linux, cannot connect to browser

### ISSUE THREAD

**Issue by jcernohorsky** [keepassxreboot/keepassxc#8634] opened 2022-10-24 11:27 UTC
After upgrade from `2.7.1 1ppa1~jammy1 to 2.7.3-1ppa1~jammy1` from PPA, internet browsers cannot connect to database. From plugin debug I had "Unknown Error".
Firefox extension plugin: 1.8.3
Firefox version: 102.4.0 esr
After downgrade to 2.7.1 everything is working again.

**Comment by droidmonkey** [comment] 2022-10-24 11:34
Make sure you run through the browser troubleshooting guide

**Comment by jcernohorsky** [comment] 2022-10-24 11:59
> 

Yep, I do :).
~/.mozilla/native-messaging-hosts is OK
Check the native messaging script file path and extension ID's is OK
keepassxc-proxy is running
And under "Debug the extension itself" I got "unknown error"

Thank you.

**Comment by Schnoop** [comment] 2022-10-24 12:22
I've the same problem. Updated yesterday from `2.7.1 1ppa1~jammy1 to 2.7.3-1ppa1~jammy1` via PPA. 
Chrome Extension: 1.8.3
Chrome Version: 106.0.5249.119

The icons in the input fields went from "Keepass file locked" to "Keepass file is open". But it is not showing any credentials.

The error messages from the browser plugin are varied:

>  Cannot send activated_tab message: Could not establish connection. Receiving end does not exist

> Nonce compare failed

Regards

**Comment by droidmonkey** [comment] 2022-10-24 12:28
Can you replicate this behavior with the appimage?

**Comment by git-noise** [comment] 2022-10-24 12:31
Hello,
I had the same issue, but while trying to debug using the recommended command: ```sudo strace -f -p $(pgrep firefox) 2>&1 | grep keepass```, it suddenly worked.
I am using the firefox snap and saw some apparmor logs DENY too, no clue if its related.

**Comment by Schnoop** [comment] 2022-10-24 12:40
@droidmonkey yes, i can replicate the problem with the latest appimage.
Add just to make sure: The problem is not there if i use the appimage version 2.7.1

**Comment by phoerious** [comment] 2022-10-24 13:00
Is your Firefox installed as a Snap?

**Comment by Schnoop** [comment] 2022-10-24 13:04
Don't know if you referring to me or not. In my case it is Google Chrome not Firefox. No Snap.

**Comment by danielb42** [comment] 2022-10-24 13:05
My Firefox is not installed via Snap: 106.0.1+build1-0ubuntu0.22.04.1\~mt1 from mozilla-ppa.
I'm experiencing this issue only randomly: Since upgrading to 2.7.3-1ppa1\~jammy1, I sometimes need to click "Reconnect" in the browser widget/popup when using new tabs.

**Comment by jcernohorsky** [comment] 2022-10-24 13:07
> Is your Firefox installed as a Snap?

Hi @phoerious , my Firefox is from Firefox PPA. No snap.

**Comment by sajonCC** [comment] 2022-10-24 13:08
I can confirm this bug.
Firefox 106.0.1 installed from ppa
KeepassXC 2.7.3 installed from ppa
KeepassXC Firefox Add-on 1.8.3

result of `sudo strace -f -p $(pgrep firefox) 2>&1 | grep keepass`

`[pid 38462] openat(AT_FDCWD, "/home/sajon/.mozilla/native-messaging-hosts/org.keepassxc.keepassxc_browser.json", O_RDONLY <unfinished ...>
[pid 37720] newfstatat(AT_FDCWD, "/usr/bin/keepassxc-proxy",  <unfinished ...>
[pid 37720] newfstatat(AT_FDCWD, "/usr/bin/keepassxc-proxy",  <unfinished ...>
[pid 37720] newfstatat(AT_FDCWD, "/usr/bin/keepassxc-proxy",  <unfinished ...>
[pid 37720] newfstatat(AT_FDCWD, "/usr/bin/keepassxc-proxy",  <unfinished ...>
[pid 38509] execve("/usr/bin/keepassxc-proxy", ["/usr/bin/keepassxc-proxy", "/home/sajon/.mozilla/native-mess"..., "keepassxc-browser@keepassxc.org"], 0x7f45cb92c900 /* 77 vars */ <unfinished ...>`

keepassxc-proxy is runing.

I've followed troubleshooting guide but no luck to resolve the problem. I will try to downgrade to 2.7.1 and provide you with info.

**Comment by droidmonkey** [comment] 2022-10-24 13:40
This might be related to moving the proxy socket to a subdirectory. Specifically if the proxy version isn't updated but keepassxc is then comms will fail.  Restarting browser or computer should cause the new proxy to be loaded. 

https://github.com/keepassxreboot/keepassxc/pull/8030

**Comment by Schnoop** [comment] 2022-10-24 13:54
@droidmonkey i'm sorry to tell you that a reboot does not fix the problem for me.

**Comment by phoerious** [comment] 2022-10-24 13:59
Make sure you have "Update native messaging manifests at startup" enabled in the advanced browser integration settings in KeePassXC and then restart KeePassXC.

**Comment by Schnoop** [comment] 2022-10-24 14:06
Done that. Nothing changed.

**Comment by dsoares** [comment] 2022-10-24 15:13
After upgrade from keepassxc 2.7.2 to 2.7.3, (snap package), the browser integration stopped working.  I've already:
- read the browser troubleshooting guide multiple times
- checked the `~/.config/google-chrome/NativeMessagingHosts/org.keepassxc.keepassxc_browser.json` file.
- reinstalled with --devmode 
I use google-chrome from the Ubuntu 22.04 repository.
I downgraded to snap package version 2.7.2 and it works again. Something is broken with 2.7.3.

**Comment by ghost** [comment] 2022-10-24 15:39
I can confirm this - using Brave on Linux, upgrading KeePassXC to 2.7.3 immediately broke browser integration. Downloading the 2.7.1 AppImage, then stopping 2.7.3 and running the AppImage, immediately fixed the problem without a reboot.

**Comment by phoerious** [comment] 2022-10-24 15:40
I cannot reproduce this with Chrome and 2.7.3 from the PPA.

**Comment by sajonCC** [comment] 2022-10-24 15:54
I've try with official ppa for ubuntu (ver. 2.6.6), offical ppa for KeePassXC (ver. 2.7.3) and AppImage ver 2.7.3). Nothing is working :( Can some one provide me with the link to version 2.7.1 (AppImage, ppa..)

Thanks

**Comment by jcernohorsky** [comment] 2022-10-24 16:21
> I've try with official ppa for ubuntu (ver. 2.6.6), offical ppa for KeePassXC (ver. 2.7.3) and AppImage ver 2.7.3). Nothing is working :( Can some one provide me with the link to version 2.7.1 (AppImage, ppa..)
> 
> Thanks

http://ppa.launchpad.net/phoerious/keepassxc/ubuntu/pool/main/k/keepassxc/ ... and choose 2.7.1 for your distrib.

**Comment by sajonCC** [comment] 2022-10-24 17:16
Thanks, I've try 2.7.1 and it's not working for me :(
Strange think, when I start firefox and keepassxc I can not find keepassxc-proxy running. Why this is not started automatically? 

When I start keepassxc-proxy manually, I can see this in the konsole:
`[pid  6174] <... sendmmsg resumed>[{msg_hdr={msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="q\311\1 \0\1\0\0\0\0\0\1\tkeepassxc\3org\0\0\1\0\1\0"..., iov_len=42}], msg_iovlen=1, msg_controllen=0, msg_flags=0}, msg_len=42}, {msg_hdr={msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="X\317\1 \0\1\0\0\0\0\0\1\tkeepassxc\3org\0\0\34\0\1\0"..., iov_len=42}], msg_iovlen=1, msg_controllen=0, msg_flags=0}, msg_len=42}], 2, MSG_NOSIGNAL) = 2
[pid  6174] recvfrom(87, "X\317\201\200\0\1\0\1\0\0\0\1\tkeepassxc\3org\0\0\34\0\1\300"..., 2048, 0, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("127.0.0.53")}, [28 => 16]) = 70
[pid  6174] recvfrom(87, "q\311\201\200\0\1\0\1\0\0\0\1\tkeepassxc\3org\0\0\1\0\1\300"..., 65536, 0, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("127.0.0.53")}, [28 => 16]) = 58
[pid  6114] openat(AT_FDCWD, "/home/sajon/.mozilla/native-messaging-hosts/org.keepassxc.keepassxc_browser.json", O_RDONLY <unfinished ...>
[pid  5580] newfstatat(AT_FDCWD, "/usr/bin/keepassxc-proxy",  <unfinished ...>
[pid  5580] newfstatat(AT_FDCWD, "/usr/bin/keepassxc-proxy",  <unfinished ...>
[pid  5580] newfstatat(AT_FDCWD, "/usr/bin/keepassxc-proxy",  <unfinished ...>
[pid  5580] newfstatat(AT_FDCWD, "/usr/bin/keepassxc-proxy",  <unfinished ...>
[pid  6203] execve("/usr/bin/keepassxc-proxy", ["/usr/bin/keepassxc-proxy", "/home/sajon/.mozilla/native-mess"..., "keepassxc-browser@keepassxc.org"], 0x7f1cc0eb3d00 /* 78 vars */ <unfinished ...>
`
and still is not working.

Message in the browser pop-up is "Key exchange was not successful"

What am I doing wrong?

**Comment by phoerious** [comment] 2022-10-24 17:51
You cannot start the proxy yourself, this is done by the browser when you click "Retry" or "Reconnect".

**Comment by sajonCC** [comment] 2022-10-24 18:00
Ok, clear. Do you see anything unusual in strace output?

**Comment by mdonz** [comment] 2022-10-24 18:14
FWIW, I am using the latest PPA versions of Firefox and Chromium on Ubuntu 22.04 (no snaps in use) and the upgrade for Keepassxc from 2.7.1 to 2.7.3 yesterday broke functionality as described by various users. Computer restart did not help.
Uninstall of 2.7.3 and download and install of 2.7.1 restored functionality here.
Happy to try to help with testing but do not know where to look for that.

**Comment by varjolintu** [comment] 2022-10-24 19:12
Reboot shouldn't be needed if `keepassxc-proxy` is killed, or the browser is restarted (which terminates the proxy).

**Comment by linkp** [comment] 2022-10-24 20:52
On openSUSE  Leap 15.4 with Brave Browser 1.44.112, KeepassXC-Browser extension 1.8.3 and a precipitating upgrade to KeepassXC 2.7.3, I resolved the problem by removing and reconnecting the database in the browser extension settings.

Update: I spoke too soon. It worked one time, but has returned to no longer retrieving credentials.

**Comment by mdonz** [comment] 2022-10-24 22:56
> Reboot shouldn't be needed if `keepassxc-proxy` is killed, or the browser is restarted (which terminates the proxy).
I restarted the browser(s) first which did not solve the issue (not knowing how the keepass-proxy process works). As a next step in trying, I restarted completely. Still no joy at the time hence downgrade was the only option that I figured out would get me back to work yesterday.

**Comment by Romich777** [comment] 2022-10-25 08:26
FF Mint - same error

**Comment by varjolintu** [comment] 2022-10-25 09:37
Tested this briefly with a pretty fresh Xubuntu install which didn't have KeePassXC installed at all. Everything works normally.

Did these steps:
1. Uninstalled the Snap Firefox and replaced it with `ppa:mozillateam/ppa`'s Firefox.
2. Downloaded an AppImage for 2.7.3 from `keepassxc.org`.
3. Opened KeePassXC, enabled Browser Integration and made a new test database.
4. Connected the extension do database, everything worked.

I also checked if `XDG_RUNTIME_DIR` was enabled. It was, pointing to `/run/user/1000`. The new socket location is now `/run/user/1000/app/org.keepassxc.KeePassXC/org.keepassxc.KeePassXC.BrowserServer` and the socket exists after KeePassXC start.

And I also saw there's a symbolic link from `/run/user/1000/org.keepassxc.KeePassXC.BrowserServer -> /run/user/1000/app/org.keepassxc.KeePassXC//org.keepassxc.KeePassXC.BrowserServer`.

**Comment by kipusoep** [comment] 2022-10-25 09:59
I'm on Windows and got redirected to this issue from #8648
I tried reinstalling version 2.7.1, but still the credentials are not entered in the username/password fields (Edge).
The KeepassXC icon in the username text input remains grey and clicking it doesn't do anything.
Error in the logs:
`KeePassXC-Browser - Error: Credential list is empty`

**Comment by varjolintu** [comment] 2022-10-25 10:01
@kipusoep On what page?

**Comment by kipusoep** [comment] 2022-10-25 10:15
~~Unfortunately every single page that used to work yesterday :-)~~

Never mind, rebooted my machine and connected the browser plugin again, now it works.

**Comment by varjolintu** [comment] 2022-10-25 10:21
> ~Unfortunately every single page that used to work yesterday :-)~
> 
> Never mind, rebooted my machine and connected the browser plugin again, now it works.

Probably the proxy wasn't upgraded itself while it was still running.

**Comment by varjolintu** [comment] 2022-10-25 12:41
The error happens if 2.7.1 is upgraded to 2.7.3 while the browser is running. The proxy needs to be killed before a new connection must be made, so these steps work if the browser is not open:

Workaround:
1. Close the browser and KeePassXC 2.7.1.
2. Update the KeePassXC to 2.7.3 (using AppImage etc.)
3. Delete the old proxy socket from `XDG_RUNTIME_DIR` (for me it's `/run/user/1000/org.keepassxc.KeePassXC.BrowserServer`)
4. Start KeePassXC 2.7.3
5. Start the browser

Reason for this bug is that the old socket file exists in the `XDG_RUNTIME_DIR` and it's not overridden by the new symbolic link which is needed. The socket should point to the one under `app/org.keepassxc.KeePassXC/org.keepassxc.KeePassXC.BrowserServer`.

The proper fix for this is to check if the original file is not a symbolic link, and delete it if that's true, before trying to make a new link.

**Comment by michaelk83** [comment] 2022-10-25 13:06
> The proper fix for this is to check if the original file is not a symbolic link, and delete it if that's true, before trying to make a new link.

Untested, but this should work for a manual fix:
```
cd $XDG_RUNTIME_DIR
ln -sf app/org.keepassxc.KeePassXC/org.keepassxc.KeePassXC.BrowserServer org.keepassxc.KeePassXC.BrowserServer
```
(adjust as needed; the `-f` forces replacement of the existing file)

edit: Or just deleting it should be fine, if it's recreated when the proxy is restarted. But on most modern Linux, `XDG_RUNTIME_DIR` [should be completely deleted during logout](https://unix.stackexchange.com/q/476963/455274), so it's puzzling that some of the users here report that a reboot doesn't fix the issue (@Schnoop, @mdonz).

**Comment by droidmonkey** [comment] 2022-10-25 13:24
Shouldn't need sudo, this is user land

**Comment by danielb42** [comment] 2022-10-25 13:35
I created the link as above (as user) with firefox und keepassxc stopped, but keepassxc-proxy keeps crashing occasionally on new tabs.

**Comment by gwert** [comment] 2022-10-25 13:38
I'm running KeePassXC-Browser 1.8.3 on Firefox 106.0.1 and KeePassXC 2.7.3 on Linux Mint 20.3.  Deleting `$XDG_RUNTIME_DIR/org.keepassxc.KeePassXC.BrowserServer` and rebooting solved the problem for me.  However, based on the timestamps, it did appear that everything in `$XDG_RUNTIME_DIR` had already been recreated when I attempted other solutions and rebooted just before trying to delete `org.keepassxc.KeePassXC.BrowserServer`.  It also appeared to be a symbolic link pointing to the same location it's pointing to now, so I'm not sure what deleting it did to resolve the issue.  Maybe a file system permissions issue?  Hopefully, the solution is durable and doesn't return the next time I reboot or re-open Firefox or KeePassXC...

UPDATE: This solution appears to work for a short period (10 minutes, give or take?), but then it loses the connection to the database.  It then takes several attempts to reconnect to the database, works for a little bit, then disconnects again.

**Comment by michaelk83** [comment] 2022-10-25 13:48
> Shouldn't need sudo, this is user land

Edited.

**Comment by gbe0** [comment] 2022-10-25 15:54
> > I've try with official ppa for ubuntu (ver. 2.6.6), offical ppa for KeePassXC (ver. 2.7.3) and AppImage ver 2.7.3). Nothing is working :( Can some one provide me with the link to version 2.7.1 (AppImage, ppa..)
> > Thanks
>
> http://ppa.launchpad.net/phoerious/keepassxc/ubuntu/pool/main/k/keepassxc/ ... and choose 2.7.1 for your distrib.

Jammy doesn't show there anymore, how ever you can get the 2.7.1 package for it from the PPA archive:

<https://launchpad.net/~phoerious/+archive/ubuntu/keepassxc/+files/keepassxc_2.7.1-1ppa1~jammy1_amd64.deb>

**Comment by phoerious** [comment] 2022-10-25 16:00
See https://github.com/keepassxreboot/keepassxc/issues/8634#issuecomment-1290490385
No need to downgrade if you apply this fix.

**Comment by gbe0** [comment] 2022-10-25 16:20
> See [#8634 (comment)](https://github.com/keepassxreboot/keepassxc/issues/8634#issuecomment-1290490385) No need to downgrade if you apply this fix.

The fix does not work for me; I get the original behavior still.

Ubuntu Jammy
Firefox 107.0b4 (installed from the firefox-next PPA)
KeePassXC from PPA

Initially, the database shows as connected and it may work for some sites before giving the "Cannot connect to KeePassXC. Check that browser integration is enabled in KeePassXC settings." message. I can immediately reproduce the issue by accessing any website using basic HTTP authentication.

**Comment by linkp** [comment] 2022-10-25 16:21
@phoerious The "fix" in the referenced comment does not fix it on my system. (See my previous comment https://github.com/keepassxreboot/keepassxc/issues/8634#issuecomment-1289603339 for OS system and RPM package details.)

After the 2.7.3 upgrade, clicking the auto-fill icons no longer enters any credentials. I can manually trigger auto-fill by using the contextual menu *Request Global Auto-Type* option from the *KeePassXC-Browser* menu.

**Comment by danielb42** [comment] 2022-10-25 16:37
> The fix does not work for me; I get the original behavior still.
> 
> Ubuntu Jammy Firefox 107.0b4 (installed from the firefox-next PPA) KeePassXC from PPA
> 
> Initially, the database shows as connected and it may work for some sites before giving the "Cannot connect to KeePassXC. Check that browser integration is enabled in KeePassXC settings." message. I can immediately reproduce the issue by accessing any website using basic HTTP authentication.

Same here. keepassxc-proxy process is gone by then.

**Comment by varjolintu** [comment] 2022-10-25 16:51
@gbe0 Firefox-Next is the beta release? We don't officially support those. Is `keepassxc-proxy` vanishing for you too?

@danielb42 Is there any logs or indication that the proxy crashes? It should only disappear if the browser does something to it.

**Comment by danielb42** [comment] 2022-10-25 16:54
@varjolintu Nothing at all. No logs, no errors. I tried starting it manually to see stderr maybe, but firefox doesn't seem to use this one.

Debugging the browser addon just prints the usual messages of "Could not connect to.." to the dev console when the proxy has died.

**Comment by Mattchooness222** [comment] 2022-10-25 18:58
I'm getting this exact issue with Firefox 106.0.1 on Windows 10 21H2. I went through the whole troubleshooting document and nothing was able to help. I rolled back to 2.7.1 and all is well again.

**Comment by mdonz** [comment] 2022-10-25 19:47
Could it be that some of us here with reported issues are using the browser add-ons but also the Thunderbird add-on "keepassmail-xc" and this might be part of the mixed results? Meaning before the workaround (manually remove the contents of $XDG_RUNTIME_DIR or creating the symbolic link) they should also close Thunderbird? Just a thought.

**Comment by ghost** [comment] 2022-10-25 20:14
> Could it be that some of us here with reported issues are using the browser add-ons but also the Thunderbird add-on "keepassmail-xc" and this might be part of the mixed results? Meaning before the workaround (manually remove the contents of $XDG_RUNTIME_DIR or creating the symbolic link) they should also close Thunderbird?

I don't have Thunderbird at all - in fact I don't have Firefox either, only a fork, which is rarely running (and which I haven't used since attempting the 2.7.3 upgrade).

**Comment by danielb42** [comment] 2022-10-26 07:19
Not using keepassmail-xc either. However I can also confirm that using the 2.7.1 AppImage, the issue of the dying proxy process disappears.

**Comment by deadly667** [comment] 2022-10-26 08:42
After update to 2.7.3 (Chrome browser and KeePassXC was closed) it created  symlinks like:

`/run/user/1000/org.keepassxc.KeePassXC.BrowserServer -> /run/user/1000/app/org.keepassxc.KeePassXC//org.keepassxc.KeePassXC.BrowserServer=
`

After fixing symlinks for me everything works. 

Ubuntu 20.04
KeePaasXC 2.7.3

**Comment by MarioMan632** [comment] 2022-10-26 08:47
Looks the issue is effecting multiple OSes and Browsers as it occurs for me on Edge (used for work) on Windows 10 Pro 21H2. 
When I get home will see if this occurs on Edge (for Work from home) on my MacBook Pro. 

Hopefully there is a fix for this soon on Windows..

**Comment by varjolintu** [comment] 2022-10-26 08:53
@MarioMan632 It's a different issue on Windows. It's already fixed, so downgrading to 2.7.1 in the meanwhile is the only workaround for now.

**Comment by Booteille** [comment] 2022-10-26 15:59
> After update to 2.7.3 (Chrome browser and KeePassXC was closed) it created symlinks like:
> 
> `/run/user/1000/org.keepassxc.KeePassXC.BrowserServer -> /run/user/1000/app/org.keepassxc.KeePassXC//org.keepassxc.KeePassXC.BrowserServer= `
> 
> After fixing symlinks for me everything works.
> 
> Ubuntu 20.04 KeePaasXC 2.7.3

I can confirm fixing the symlink fixed this issue on Pop_OS! 22.04 and KeePassXC  2.7.3.

**Comment by ghost** [comment] 2022-10-26 16:49
> I can confirm fixing the symlink fixed this issue on Pop_OS! 22.04 and KeePassXC 2.7.3.

Also on Pop_OS! 22.04, normal logins were fine after manually rebuilding the symlink but when I went to comment here, KeePassXC would only populate user/pass but would not populate TOTP. Going back to the 2.7.1 AppImage restored functionality, so while this feels like a red herring, it clearly didn't work and responded to revert, so it becomes a "later" problem.

**Comment by RainyCityCoder** [comment] 2022-10-26 18:39
Had issues with the snap version 2.7.3, and got it working with 2.6.6. Steps (as best I can remember): 
1) uninstall KeePassXC
2) restart
3) install KeePassXC 2.6.6 (`sudo snap install keepassxc --candidate`)
4) enable browser integration
5) run "KeePassXC-Browser Helper Script" under the " Snap Package" heading on this page: https://keepassxc.org/download/#linux
6) restart browser
7) connect extension to database
8) test

**Comment by varjolintu** [comment] 2022-10-26 19:00
@RainyCityCoder Why 2.6.6 if there's 2.7.1?

**Comment by RainyCityCoder** [comment] 2022-10-26 20:42
@varjolintu On snapcraft.io there's 2.7.3 of course, 2.7.2, which is listed as beta, and 2.6.6 listed as candidate. As I found out; 2.6.6 is what's available for Debian. Since I couldn't quickly figure out how to revert to 2.7.1, I tried 2.6.6. Since it worked, I'm happy. A quick scan of the keepassxc blog tells me that for my use, I'm unlikely to miss anything introduced by later versions, but if I do at a later date, I can always try to find 2.7.1.

**Comment by ShosGithub** [comment] 2022-10-27 09:52
Same issue on Windows 11 with Edge 106.0.1370.52 after upgrade to 2.7.3
Have Proxy Software installed.
Sometimes it shows credentials, sometimes not.

**Comment by styjdt** [comment] 2022-10-27 13:59
Also here for Win10 Edge 106.0.1370.52 after upgrade to 2.7.3.
No flaky behaviour, consistently the credentials are not shown/inserted. Same for TOTP.
The KeePassXC "button" is green, showing that connection is good and there and password is available, but clicking it does not change anything...

**Comment by droidmonkey** [comment] 2022-10-27 17:20
We don't need any more "me toos", thank you for all the reports!

**Closed as completed** 2022-10-28 11:30 UTC
Labels: platform: Linux, feature: Browser
