### ISSUE TITLE
Icontray primary click options are useless and should be deleted

### ISSUE THREAD

**Issue by apfelchips** [keepassxreboot/keepassxc#2255] opened 2018-08-31 19:23 UTC
When primary clicking the KeepassXC icon in the Icontray you get two options: Toggle window and Close KeepassXC this is annoying since primary clicking indicates the user wants to open the KeepassXC main window and not have to choose what to do with a secondary click.

## Expected Behavior
A primary click should always open/un-minimize the KeepassXC main window.

## Current Behavior
A primary click open a rather useless/annoying dropdown menu.
![screenshot](https://user-images.githubusercontent.com/6919384/44931632-defed900-ad51-11e8-944f-9390e074200e.png)

## Possible Solution
The menu should only appear on a secondary click (aka. left click) by the user and may be expanded with additional options.

## Steps to Reproduce
1. enable minimize to tray icon in settings
2. minimize to tray
3. click the KeepassXC tray icon

## Context
Little things like these make a big difference in the users reception/enjoyment of the app.

## Debug Info
KeePassXC - 2.3.4

Operating system: ALL
CPU architecture: ALL
Kernel: ALL

**Comment by droidmonkey** [comment] 2018-08-31 19:51
Duplicate of #2130, this is not our fault.

**Closed by droidmonkey** 2018-08-31 19:51 UTC
