### ISSUE TITLE
KeePassXC prevents KDE Plasma from logging out

### ISSUE THREAD

**Issue by PlqnK** [keepassxreboot/keepassxc#2857] opened 2019-03-24 12:21 UTC
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
KDE Plasma logs me out.

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
If I try to log out, shut down or reboot my computer, Plasma will display a popup saying that the log out/shut down/reboot of Plasma was cancelled by `/usr/bin/keepassxc`.

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )
I've tried the following:
- Enabling and disabling autosave
- Enabling and disabling safe save
- Trying to log out/shut down/reboot when the DB is locked and unlocked

But none of it worked.

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. Use KDE Plasma with KeePassXC launched
2. Try to log out from Plasma "Start Menu"
3. See the popup by `Plasma Workspace` saying `Logout canceled by '/usr/bin/keepassxc'`

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )
I'm running an up to date Arch Linux install:
- KDE Plasma 5.15.3
- KDE Frameworks 5.56.0

I'v had this bug before (a long time ago) but it was eventually corrected, it just "came back" with version 2.4.0.

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.4.0
Revision: c51752d

Libraries:
- Qt 5.12.2
- libgcrypt 1.8.4

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 5.0.3-arch1-1-ARCH

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey

**Comment by PlqnK** [comment] 2019-03-24 12:24
My be related to #1190 and #856

**Comment by droidmonkey** [comment] 2019-03-24 12:59
Do you have the system tray icon enabled and minimize to system tray instead of exiting? If so, please try disabling those one at a time to see if the issue goes away. I want to isolate this on a known "broken" example.

**Comment by PlqnK** [comment] 2019-03-24 13:05
I have both enabled indeed! And the culprit is "Minimize instead of app exit", if I disable it no more problem!

**Comment by droidmonkey** [comment] 2019-03-24 13:59
Ok, as I suspected. Unfortunately the real fix to this is platform-dependent. Each platform sends a pre-shutdown notification that we have to identify uniquely from a user close action. This occurs in the OSEventFilter class. I implemented it for Windows, but need to dive into Xcb docs to figure it out for Linux.

**Comment by vip9** [comment] 2019-03-24 17:01
[https://github.com/keepassxreboot/keepassxc/issues/2692#issuecomment-475974699](https://github.com/keepassxreboot/keepassxc/issues/2692#issuecomment-475974699)

**Comment by droidmonkey** [comment] 2019-03-24 17:15
This is actually a duplicate of #2692

**Closed** 2019-03-24 17:15 UTC
Labels: bug, duplicate, platform: Linux
