### ISSUE TITLE
Status on database getting modified after groups are expanded/collapsed?

### ISSUE THREAD

**Issue by firepainting** [keepassxreboot/keepassxc#9814] opened 2023-08-31 15:02 UTC
References: #446 #535 #4103 

Pardon me if I'm not following this, but whenever I expand/collapse a group, the database still gets modified. From previous Issues I would surmise that it should have been resolved by now.

Is there a way to disable that? Or is that decided upon already to just be that way?

I'm not a fan of auto-saving databases and wholeheartedly believe that expanding/collapsing stuff should not be save-worthy, as discussed in the above Issues also.

## Expected Behavior
Database does not get modified after simply expanding/collapsing groups.

## Actual Behavior
Database gets modified after expanding/collapsing groups.

```
KeePassXC - Version 2.7.6
Revision: dd21def
Distribution: AppImage and PPA

Qt 5.15.2 for AppImage; Qt 5.15.3 for PPA
Debugging mode is disabled.

Operating system: Linux Mint 21.2
CPU architecture: x86_64
Kernel: linux 5.15.0-82-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.19.1
```

Operating System: Linux Mint 21.2
Desktop Env: Cinnamon
Windowing System: X11

Thank you!

**Comment by varjolintu** [comment] 2023-08-31 15:13
Duplicate of: https://github.com/keepassxreboot/keepassxc/issues/9751

**Closed as not planned by varjolintu** 2023-08-31 15:13 UTC

**Comment by firepainting** [comment] 2023-08-31 16:19
Thanks.

>keepassxreboot locked and limited conversation to collaborators 2 weeks ago

I wish they didn't lock it. I think allowing for users' input and feedback is for the better. But that's just me of course.

I fully agree with @xboxones1

>I do not suffer from loss of memory and I do not need to remember whether I made changes or not. Here the problem is not only in Yubikey, such behavior is simply not acceptable when the base is saved simply after navigation on the panel. I want to decide for myself when to keep changes, and when not. This should be a disabling option, not be permanent.

Everyone knows that KeePass2 does not behave like this and #446 has been a while...

Anyway from the looks of it, this is an unwanted effect (as phoerious said). I hope it gets fixed soon!

Thank you!

**Comment by firepainting** [comment] 2023-08-31 16:35
Just a note to self.

From #9751:

>This is now broken, before version 2.7.6 it worked as it should - @xboxones1 

I started using KeePassXC 2.7.5 just two days before the 2.7.6 update (2023-08-16) and thought this was not the case before. (@xboxones1 I hope you can confirm this.)

Something must keep screwing this up all these years (6 years!).
