### ISSUE TITLE
16x16 icon size is too small on higher resolution displays

### ISSUE THREAD

**Issue by starksm64** [keepassxreboot/keepassxc#636] opened 2017-06-11 20:44 UTC
Related to the existing request to improve the application icons: https://github.com/keepassxreboot/keepassxc/issues/475
either the default icon size should be 32x32, or there should be a preference option to set the displayed icon size.

## Expected Behavior
It is very difficult to view the default icons, or add custom icons that can easily be understood what they are. I would like to either see the default icon size be 32x32 or have the ability to choose an icon display size from among a set of 16x16, 32x32, 48x48, 64x64.

## Current Behavior
The current icon sizes are 16x16 and are simply very difficult to see clearly on displays like a 27" iMac.

## Possible Solution
Currently the Metadata, Group and Entry classes have an icon scaling method that would need to be changed. Right now there is a test between a default and custom icon. Perhaps the Metadata class can be updated to simply handle the scaling/choice of the icon regardless of whether it was a default or custom icon.

## Context
I have been moving my text based password store over to KeyPassXC and have found it difficult to create/assign meaningful icons to both groups and entries due to the low resolution that is supported.

## Your Environment
KeePassXC - Version 2.1.4
Revision: 79ba3a28e6df941e906af3b6dc66fd9f28dbd4c0

Libraries:
- Qt 5.8.0
- libgcrypt 1.7.6

Operating system: OS X El Capitan (10.11)
CPU architecture: x86_64
Kernel: darwin 15.6.0

Enabled extensions:
- Auto-Type

**Comment by weslly** [comment] 2017-06-11 20:48
Duplicate of #548.

**Closed by weslly** 2017-06-11 20:48 UTC
