### ISSUE TITLE
Select SSH Agent Private Key Attachment in Keepass-XC CLI

### ISSUE THREAD

**Issue by kuolemaaa** [keepassxreboot/keepassxc#11222] opened 2024-09-01 15:24 UTC
## Summary
Using the GUI I can set a Private Key from the Attachments of the entry in the "SSH Agent" section, that attachment will be loaded on the ssh-agent running on the host. It seems that there is not way to do that programmatically in CLI.

## Examples
Due to the nature of the thing ( ssh-agent, attachments, entry) I really don't know a proper command to assign to this function.

This is just my proposal:

`keepassxc-cli attachment-ls <database> <entry> ` to list entry's attachment, maybe filenames only (seems missing)

`keepassxc-cli ssh-agent <database> <entry> ` to print actual private key status

`keepassxc-cli ssh-agent <database> <entry> -a <attachment-name>` to set that attch. as private key for entity

`keepassxc-cli ssh-agent <database> <entry> -f <externalFilePath>` to set an external file, like the GUI

`keepassxc-cli ssh-agent <database> <entry> --add` to add the pk to the agent

`keepassxc-cli ssh-agent <database> <entry> --rm` to remove it from the agent

## Context
I use keepassxc as my ssh-agent manager but manage this kind of things on a remote machine, sometimes without any graphical help is frustrating. I know I can use other solutions like funtoo's keychain or GPG ssh agent but Keepassxc is my first love. It just lacks CLI capabilities for power users.

**Comment by droidmonkey** [comment] 2024-09-01 16:16
Duplicate of https://github.com/keepassxreboot/keepassxc/issues/6339

**Closed as not planned by droidmonkey** 2024-09-01 16:16 UTC
Labels: duplicate, feature: CLI, feature: SSH agent
