### ISSUE TITLE
Mac Preferences

### ISSUE THREAD

**Issue by metbril** [keepassxreboot/keepassxc#555] opened 2017-05-08 20:29 UTC
## Expected Behavior

- Preferences menu option is in  Applications menu ('KeepassXC')
- Shortcut key for preferences is <CMD>+, (mac default) or at least any other key

## Current Behavior

- Preferences menu item is in Tools menu.
- No shortcut key for Preferences

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

macOS 10.12.4 / KeepassXC 2.1.4

* KeePassXC version/commit used: (can be found under Help -> About)
* Qt version (e.g. Qt 5.3): 
* Compiler (e.g. Clang++3.6.0): 
* Operating System and version:

**Comment by weslly** [comment] 2017-05-08 20:57
Duplicate of #481.

**Comment by TheZ3ro** [comment] 2017-05-08 21:09
Can I close this?

**Comment by weslly** [comment] 2017-05-08 21:10
@TheZ3ro yes, was fixed in #483

**Closed** 2017-05-08 21:11 UTC
Labels: duplicate

**Comment by metbril** [comment] 2017-05-09 03:20
The issue is closed but my request for a keyboard shortcut had not been adressed elsewhere. Could we reopen the issue and dedicate it to a shortcut?

**Comment by weslly** [comment] 2017-05-09 03:22
@metbril it was fixed already on the develop branch.
