### ISSUE TITLE
Safari browser integration

### ISSUE THREAD

**Issue by specter78** [keepassxreboot/keepassxc#5298] opened 2020-08-20 13:52 UTC
Integrate keepassxc in safari. 

Now that safari is supporting web extension api, this should (hopefully) make it easier.

**Comment by varjolintu** [comment] 2020-08-20 15:20
Duplicate of: https://github.com/keepassxreboot/keepassxc-browser/issues/294

**Closed by varjolintu** 2020-08-20 15:20 UTC
Labels: new feature
