### ISSUE TITLE
2.5.1 - Browser Confirm Access ignores subdomain specificity

### ISSUE THREAD

**Issue by jm-duke** [keepassxreboot/keepassxc#3848] opened 2019-11-12 09:59 UTC
I tested this behavior with the KeePassXC-Browser Addon for Firefox and Chrome. Downgrading KeepassXC from 2.5.1 to 2.5.0 fixed the issue, so it seems to be related to the latest version of KeepassXC and not to the browser addon.

## Expected Behavior
When browsing to a site, the "KeePassXC-Browser Confirm Access" pop-up requests password access to the credentials stored for this specific site or does not pop-up at all for sites, for which I already granted password access.

## Current Behavior
The pop-up requests access to multiple, unrelated sites.

Also, on sites that were already known and that never showed the pop-up after I ticked "Remember this decision", the pop-up requests access to other sites now.

## Steps to Reproduce
1. Upgrade KeepassXC to 2.5.1
2. Browse to a site, which requests passwords stored in KeepassXC

## Context
Tested on two different Windows desktops, one using Firefox + KeepassXC Browser, the other using Chrome + KeepassXC Browser

## Debug Info
KeePassXC - Version 2.5.1
Revision: 0fd8836

Qt 5.13.1
Debugging mode is disabled.

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.18362

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by droidmonkey** [comment] 2019-11-12 10:44
We specifically fixed this issue in 2.5.1. What do the URL's look like for the sites that are erroneously sent?

**Comment by ThinkChaos** [comment] 2019-11-12 11:14
Since 2.5.1, it KeepassXC sends all the sibling sub-domains: if I browse to `a.x.x`, KeepassXC asks me if I also want to provide the browser access to credentials for `b.x.x`, `c.x.x`, etc.
In my settings, I have checked "Return only best-matching credentials".

**Comment by varjolintu** [comment] 2019-11-12 11:31
I'll check the behaviour if there's something we've missed. Thanks for reporting it.

**Comment by droidmonkey** [comment] 2019-11-12 11:44
Probably start with a new test case and see where things go sideways

**Comment by varjolintu** [comment] 2019-11-12 12:09
@droidmonkey Already did it. I have the fix ready. Sadly this didn't make to 2.5.1.

**Comment by varjolintu** [comment] 2019-11-12 20:50
The fix has been submitted. Feel free to test it.

**Comment by luchaos** [comment] 2019-11-13 07:41
For what it's worth - the previous version already an issue with one entry that had a space at the end of the url field. Now it asks for access to seemingly random domains.
Notably when working locally on `.test` domains - it will ask for other `.test` domains in the database.
Glad you have it on high priority :) Thank you for your fantastic work!

**Comment by varjolintu** [comment] 2019-11-13 07:43
@luchaos Please test the PR if you can! I'd appreciate it if any extra bugs are found.

**Comment by jm-duke** [comment] 2019-11-13 07:54
I'd be happy to test as well, but the PR is not available for download yet, is it?

**Comment by varjolintu** [comment] 2019-11-13 07:56
@jm-duke You'll have to compile the sources yourself using https://github.com/varjolintu/keepassxc/archive/fix/browser_subdomain_matching.zip or https://github.com/varjolintu/keepassxc/tree/fix/browser_subdomain_matching via git.

**Comment by chc-pr** [comment] 2019-11-13 08:02
> 
> 
> @jm-duke You'll have to compile the sources yourself using https://github.com/varjolintu/keepassxc/archive/fix/browser_subdomain_matching.zip or https://github.com/varjolintu/keepassxc/tree/fix/browser_subdomain_matching via git.

I know this is a stupid Q, but I have never compiled from source a github windows file. Reading the compiling for windows instructions appears to be using a linux environment Linux to compile (from a quick scan). Have I got that right? I don't really want to mess about with my Windows env as it is really overdue for a HW upgrade and adding yet more stuff into it will probably kill it from lack of storage space.

Sorry to ask such a newbe Q. Thanks

**Comment by varjolintu** [comment] 2019-11-13 08:08
@chc-pr That's right. You can install everything needed via MSYS2. It's pretty simple actually. If you use git with it, everything is downloaded to the same MSYS2 root path. It's easy to clean/uninstall.

**Comment by chc-pr** [comment] 2019-11-13 08:18
Thx. I'll do that ASAP, prob later today or early tomorrow (I feel I should allow a bit of time to do it without being pressured by other things) - but if you can build a Windows test package I can implement that pretty much immediately and report back. Thank you for the offer.

**Comment by jm-duke** [comment] 2019-11-13 08:24
+1 I probably won't find the time to build stuff today, but I would definitely be able to test a build

**Comment by Morl99** [comment] 2019-11-13 17:06
I am also affected wildly by this, because most of my entries end on db.de (our internal company dns). It leads to receiving 30ish matches on each page, KeepassXC became unusable in 2.5.1 for this. 

I will try to build the patched version on my mac and let you know if this works for me. Thanks for the quick fix, I appreciate that!

**Comment by droidmonkey** [comment] 2019-11-13 17:19
Apologies for this snafu, I blame myself for not testing this case prior to merging. The code did not look like it changed to cause this, crazy stuff.

**Comment by Morl99** [comment] 2019-11-13 17:21
Ok I can confirm, that the above PR fixes this issue for me. I made a couple of tests opening various URLs in the browser. They all behaved correctly. 
It would be great if this PR could lead to a new release quickly!

And kudos for the instructions on how to build the software. As an outsider to the project, this made it really easy for me!

**Comment by varjolintu** [comment] 2019-11-13 17:36
The matching has been broken a long time, since the KeePassHTTP support. Tried to fix it for 2.5.1 but the subdomain matching was a miss. This time it really should work correctly. Thanks everyone for the patience. It's frustrating when something breaks.

**Comment by Morl99** [comment] 2019-11-13 20:06
Looking at the test cases, I get the feeling that there this problem is not actually verified by unit tests yet, is that correct? I am actually not 100% sure if I understand them correctly, I am used reading BDD test cases, so this code is a little hard on my eyes.

**Comment by varjolintu** [comment] 2019-11-14 09:26
@Morl99 The test happens here: https://github.com/keepassxreboot/keepassxc/blob/2a5feeb4fdd6da5ed278c7125ad879978891657b/tests/TestBrowser.cpp#L295

First, it's tested against various GitHub URL's, but the test only searches matches for `https://github.com/`, and there's only one entry URL with a match.

Second, it's tested against a common `www` subdomain. In that case it returns all entry URL's with that subdomain, plus an entry with `https://github.com` because it accepts all subdomains.

Third, there's a list of entry URL's to be tested against `https://accounts.example.com`. As you can see, the matches for that URL are `https://accounts.example.com`, `https://accounts.example.com/path` and `https://example.com/`. All other entries with different subdomains are ignored.

I hope this clarifies the test cases used here.

**Comment by droidmonkey** [comment] 2019-11-14 13:30
Shouldn't https://example.com NOT match in the last test case mentioned? This would be because the URL in the entry is less specific then the one provided.

**Comment by varjolintu** [comment] 2019-11-14 13:54
@droidmonkey Previously that has been working as a wildcard for all subdomains. Do we want to change that behaviour? This means you cannot use any "general" URL's in the entry anymore, until we have implemented a support for wildcards.

**Comment by droidmonkey** [comment] 2019-11-14 14:49
I'm sorry you are absolutely correct. Please ignore me.

**Comment by Morl99** [comment] 2019-11-14 20:35
Thank you @varjolintu, I had found the test class, but was unsure of the test cases. Your explanation made it clear, thanks. I am convinced and think this should be shipped as soon as possible.

**Comment by patrick7** [comment] 2019-11-18 07:15
When will this be fixed? Or is there a workaround?
It's difficult / annoying to work with this bug.

**Comment by varjolintu** [comment] 2019-11-18 07:41
@patrick7 It's already fixed. Just have to wait for it to be merged. Then a snapshot build can be used while waiting for a new release.

**Comment by iokiwi** [comment] 2019-11-20 00:44
Will this fix similar subdomain specificity issues when retrieving icons?

For example, if a website at a subdomain has a different icon to the website of the parent domain, only the icon of the parent domain is used.

https://ecorp.com
https://product.ecorp.com

Just need a yes or no - if not I will raise a separate issue

**Comment by thePanz** [comment] 2019-12-04 12:33
@varjolintu any ETA for v2.5.2?
Or any way to get a pre-build package?

**Comment by chc-pr** [comment] 2019-12-04 12:45
> @varjolintu any ETA for v2.5.2?
> Or any way to get a pre-build package?

+1

This bug is REALLY REALLY seriously annoying ...

**Comment by patrick7** [comment] 2019-12-04 12:48
+1 to the previous 2 comments.

**Comment by varjolintu** [comment] 2019-12-04 12:51
You can test a snapshot build from: https://snapshot.keepassxc.org/

**Comment by MaxXor** [comment] 2019-12-04 13:12
@thePanz I agree, this bug does heavily impact the usability of the keepassxc browser extension and an update would be very important.

**Comment by tohn** [comment] 2019-12-04 13:31
Apparently it's not yet merged in the latest snapshot :(

**Comment by varjolintu** [comment] 2019-12-04 13:34
You can also downgrade to 2.5.0 until there's an update.

**Comment by thePanz** [comment] 2019-12-04 14:04
@varjolintu Downgrading to `2.5.0` fixed the issue.
I tested the `latest` AppImage but the bug is still present.

**Comment by chc-pr** [comment] 2019-12-04 15:06
Can someone tell me where I can find 2.5.0? I can't see it anywhere and a search of github hasn't actually resulted in my finding it ... but I am sure it must be here somewhere ..

Thx

**Comment by thePanz** [comment] 2019-12-04 15:18
@chc-pr : https://github.com/keepassxreboot/keepassxc/releases/tag/2.5.0

**Comment by Morl99** [comment] 2019-12-11 12:43
> Apparently it's not yet merged in the latest snapshot :(

I don't think that this is true, the fix for this is already merged in the 2.5.2 branch, it is just not released yet. See https://github.com/keepassxreboot/keepassxc/pull/3854

**Closed** 2019-12-27 23:15 UTC
Labels: bug, high priority :rotating_light:, plugin: Browser integration

**Comment by patrick7** [comment] 2019-12-27 23:29
When will the fixed v2.5.2 be released?
It is getting more and more annoying every day

**Comment by droidmonkey** [comment] 2019-12-27 23:33
We are wrapping it up right now.

**Comment by patrick7** [comment] 2020-01-03 19:54
Any news?

**Comment by varjolintu** [comment] 2020-01-03 19:55
@patrick7 The info I have, the release could be already tomorrow.

**Comment by patrick7** [comment] 2020-01-03 19:56
"already".

**Comment by droidmonkey** [comment] 2020-01-03 23:08
We are releasing tomorrow.

**Comment by Django987** [comment] 2020-04-09 04:56
I am still having the issue in version 2.5.3 now, although both options checked. Also tried it with only "best matching"-option.
Specific URLs look like this:
- https://devtools.com/jenkins
- https://devtools.de/builda

I get for both URLs each both credential entries

![image](https://user-images.githubusercontent.com/29111781/78859161-d9d63580-7a2e-11ea-8e27-2a24685441ca.png)

**Comment by varjolintu** [comment] 2020-04-09 05:36
@Django987 I'll check it out.

**Comment by ilpssun** [comment] 2022-03-17 19:07
I came here using KeepassXC 2.6.6 because this behavior is still annoying me.  I have several "services" installed like https://mydomain.com/owncloud and https://mydomain.com/webmail etc.  KeepassXC always suggests all passwords for https://mydomain.com/ even though I set "Match URL scheme" and "Return only best-matching credentials".  Is this still open or am I missing something?

**Comment by varjolintu** [comment] 2022-03-17 19:30
@ilpssun Currently we do matching based on the (sub)domain. There's not yet an option for an exact match.
