### ISSUE TITLE
Tab icons turn black after focus (dark theme)

### ISSUE THREAD

**Issue by quinncomendant** [keepassxreboot/keepassxc#5322] opened 2020-08-23 00:10 UTC
## Overview
The icons in the tabs (left bar) turn black when focus is in the tab area (only on the dark theme).

## Steps to Reproduce
1. Use dark theme.
2. Open `Preferences…`
3. Click on any tab.
4. The icons will all be dark except the currently selected tab.

## Expected Behavior
Icons should always be white when using dark mode.

## Actual Behavior
Icons turn black.

## Context
This occurs both when editing an entry and in the program settings. I first noticed this in v2.6.0, but waited to see if it would be fixed in the 2.6.1 release, but it wasn't, the problem is still there. Here's a screenshot and screencast:

![Screen Shot 2020-08-22 at 18 51 45](https://user-images.githubusercontent.com/6884276/90967856-baeeb200-e4aa-11ea-8a61-5bcce4f070e0.png)

![hidden-icons](https://user-images.githubusercontent.com/6884276/90967876-ebcee700-e4aa-11ea-81b8-6426362f2eec.gif)

## Versions
KeePassXC - Version 2.6.1
Revision: 9a35bba

Qt 5.15.0
Debugging mode is disabled.

Operating system: macOS Mojave (10.14)
CPU architecture: x86_64
Kernel: darwin 18.7.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by danielkoch** [comment] 2020-08-26 12:00
I think thins bug "only" appears in Mac OS 10.13 and 10.14.

**Comment by droidmonkey** [comment] 2020-09-29 02:04
Duplicate of other issues with macos and the new theme, same causr

**Closed** 2020-09-29 02:04 UTC
Labels: duplicate
