### ISSUE TITLE
Flatpak version doesn't respect theme on ubuntu 18.04

### ISSUE THREAD

**Issue by tiotrom** [keepassxreboot/keepassxc#2098] opened 2018-07-07 13:41 UTC
Ubuntu 18.04 flatpak (2.3.3) version of KeePassXC and GNOME Shell 3.28.1. KeePassXC does not respect theme design. 

![screenshot-20180707154139-1920x1080](https://user-images.githubusercontent.com/34804533/42411455-788110ec-81fc-11e8-8e83-0397150f6d5e.png)

**Comment by droidmonkey** [comment] 2018-07-07 13:57
We do not control the flatpak at this time.

**Comment by tiotrom** [comment] 2018-07-07 14:07
It is the same with snap or installed via the Software Center. None respect the theme.

**Comment by phoerious** [comment] 2018-07-07 14:32
That's a limitation of Snap. We cannot do anything about it.

**Comment by tiotrom** [comment] 2018-07-07 14:56
But even if I install via ubuntu-bionic-universe the 2.3.1+dfsg.1-1 version, it doesn't respect theme. Or the appimage. Also would be a great idea to at least add a feature of changing themes inside the app. Like provide a dark theme too.

**Comment by droidmonkey** [comment] 2018-07-07 21:09
This is more likely a qt issue, you need to make sure you are setting the QT_QPA_PLATFORMTHEME env var properly. I think 18.04 does not properly set it or Qt does not respect its default setting.

**Comment by Novite5** [comment] 2018-07-08 07:33
KeepassXC 2.3.3 in Arch with Gnome 3.28.2 has the same problem.

**Comment by Podesta** [comment] 2018-09-17 14:19
Duplicate of #1931

**Comment by droidmonkey** [comment] 2018-09-17 16:26
No it's not, this issue concerns flatpaks.

**Comment by Podesta** [comment] 2018-09-17 17:37
I believe his real issue, as he pointed out in his other 2 comments, was that none of the current releases of keepasxc respect the theme on Ubuntu 18.04 and flavors. It probably makes sense to keep this one open too, to track the issue specifically to the flatpak, as there may also have a problem specific to it.

**Comment by droidmonkey** [comment] 2018-09-17 17:42
True that, good point

**Comment by droidmonkey** [comment] 2018-09-21 01:51
There must have been a trigger that caused it to stop working. Either an environment variable or new software package. Did you install anything between those reboots or change any system settings?

**Comment by Podesta** [comment] 2018-09-21 02:13
@tiotrom I made a post on the other thread I linked. If you want to try on Ubuntu again, and are willing to go with either the ppa or the repo install.

**Comment by droidmonkey** [comment] 2019-02-24 21:59
Closing this as it should be reported under https://github.com/flathub/org.keepassxc.KeePassXC

**Closed by droidmonkey** 2019-02-24 21:59 UTC
