### ISSUE TITLE
Couldn't match password after databases unlocked

### ISSUE THREAD

**Issue by EugeniyPetrov** [keepassxreboot/keepassxc#1635] opened 2018-03-05 11:57 UTC
Hello,
KeePassXC is unable to match passwords if Global Auto-Type was hit, but the database is locked.
To reproduce the bug:
1. Lock the database
2. Go to any webpage, put cursor to form and hit global auto-type hotkey.
3. KeePassXC requests the password to unlock, fill in.
4. KeePassXC says "Couldn't find an entry that matches the window title: passwords - KeePassXC"

The bug was described in issue #1176, there is a comment that this is possibly because of auto-type accidentally hit the on KeePassXC window, but bug appears always.

KeePassXC - 2.3.0
Operating system: MacOS High Siera 10.13.3

**Comment by TheZ3ro** [comment] 2018-03-05 14:15
Duplicate of #1216

**Closed by TheZ3ro** 2018-03-05 14:15 UTC
