### ISSUE TITLE
Search in all opened databases doesn't work with auto opened databases

### ISSUE THREAD

**Issue by WhitespaceQ** [keepassxreboot/keepassxc#9166] opened 2023-02-25 12:10 UTC
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
On Opera 95.0.4635.46 with Chromium 109.0.5414.120, the browser integration fails to find any matching credential in a database that isn't the main database.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Create two database, A and B
2. Set a rule so that database B is opened whenever A is opened
3. Enable browser integration for Chromium and check "Search in all opened databases"
4. Open Opera, open a page with log-in page and click KeepaasXC logo
5. No Browser Access Request is prompted unless the user manually open the KeepassXC instance and switch to the B database tab

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
When the KeepassXC logo is clicked, a browser access request prompt should be opened just like in Chrome and Firefox.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
No browser access request prompt unless I manually switch to the database that contains the credentials for the site.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.4
Revision: 63b2394

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 11 22H2 22621.1265

**Comment by varjolintu** [comment] 2023-02-26 08:37
Is there any difference if you use Auto-Open or not? One bug related to that was just fixed for the extension recently.

**Comment by chris246** [comment] 2023-07-22 13:20
Same problem here with the Firefox integration.

I open both databases manually with individual pass phrases.

**Comment by droidmonkey** [comment] 2023-07-22 15:40
This has nothing to do with the browser or the browser extension.

**Comment by droidmonkey** [comment] 2024-08-18 16:16
Duplicate of #7269

**Closed as not planned by droidmonkey** 2024-08-18 16:16 UTC
Labels: duplicate, feature: Browser
