### ISSUE TITLE
Yubikey remains "open" after use preventing other applications to use it

### ISSUE THREAD

**Issue by diffusae** [keepassxreboot/keepassxc#1215] opened 2017-11-23 00:22 UTC
If you are using a Yubikey with KeePassXC, the Yubico OTP in Slot 1 isn't available.

## Expected Behavior

Normally you also can use OTP generation from slot 1, when you press a button.

## Current Behavior

Slot 1 isn't functional.

## Possible Solution

As a workaround it helps to unplugged the Yubikey.

## Steps to Reproduce (for bugs)

1. Use Yubikey
2. Press the button 

## Context

With the Keepass extension it was possible to use both functionalities.

## Debug Info

KeePassXC - Version 2.2.2
Revision: 6d46717

Libraries:
- Qt 5.5.1
- libgcrypt 1.7.6

Operating system: Ubuntu 16.04.3 LTS
CPU architecture: x86_64
Kernel: linux 4.4.0-101-generic

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

**Comment by phoerious** [comment] 2017-11-23 00:25
KeePassXC doesn't release the YubiKey properly after using it. This is a known issue and requires a bit of refactoring.

**Comment by diffusae** [comment] 2017-11-23 00:36
Yes, this was also my thoughts about this issue. Didn't have found it in the list.

**Comment by sainaen** [comment] 2017-11-25 12:59
Here is a related (but slightly different) issue about YubiKey being locked into CR mode too early on the unlock screen: #698. It's closed, but wasn't fixed.

**Comment by phoerious** [comment] 2017-11-25 15:18
It's the same problem.

**Comment by diffusae** [comment] 2018-03-01 20:31
Yes, that's the same problem. and it isn't fixed in KeePassXC - Version 2.3.0

**Comment by phoerious** [comment] 2018-03-01 21:33
The issue has not been fixed, so yes, it's still there.

**Comment by diffusae** [comment] 2018-03-01 21:49
Yes, I see. No problem, I get used to it. Sometimes it's irritating.

**Comment by jongj** [comment] 2018-09-12 12:09
It took me a while to figure out the root cause of my YubiKey to lock up and find this issue. I have a YubiKey nano so not so easy to unplug to unlock. Issuing: 

	$ ykinfo  -a 

also unlocks the  YubiKey without having to remove it.

**Comment by wingsuit** [comment] 2019-02-08 10:07
For me the issue comes from opening KeepassXC when the yubikey is already plugged in. 

If I open the database and then plug the yubikey in it does not seem to lock it up. One difference I've noticed is that when opening the app with the key plugged in the challenge response light moves which doesn't happen if the key isn't plugged in.

Is it possible to build this app with the yubikey functionality removed since I am only using static passwords?

**Comment by droidmonkey** [comment] 2019-02-08 15:33
Yes you can build it without -DWITH_XC_ALL and specify the options you want. Specifically -DWITH_XC_YUBIKEY=OFF

**Comment by wingsuit** [comment] 2019-02-09 15:32
Perfect thanks. Are there any options I should specify since I'm not using -DWITH_XC_ALL?

**Comment by wingsuit** [comment] 2019-02-09 15:33
Perfect thanks

**Comment by droidmonkey** [comment] 2019-02-09 15:33
You can see them all in the INSTALL.md file. Depends on what you use really.

**Comment by Frederick888** [comment] 2019-04-18 11:01
Hmm... I always start KeePassXC by providing password via stdin and I didn't notice this issue before. Have there been any changes made recently so that KeePassXC always detects YubiKey even if it's not used and no related panels, e.g. database configuration, are opened?

**Comment by droidmonkey** [comment] 2019-04-18 12:25
We did correct some yubikey issues in 2.4

**Comment by Frederick888** [comment] 2019-04-19 10:05
@droidmonkey The problem is that `DatabaseOpenWidget::showEvent` calls `DatabaseOpenWidget::pollYubikey` even when a password is already given via stdin... It doen't seem to be a newly introduced problem tho, guess I just overlooked it somehow. And apart from polling YubiKeys unnecessarily when opening a database, it also does the polling when KeePassXC is closed as it goes through the Lock DB -> Show DatabaseOpenWidget routine regardless.

As @phoerious mentioned, this issue needs some refactoring to be fixed neatly. I managed to put a quick hack together so that at least YubiKey polling is not triggered if the correct password and/or keyfile is already given. I can make a PR if you guys want although it's obviously an ugly fix.

```diff
diff --git a/src/gui/DatabaseOpenWidget.cpp b/src/gui/DatabaseOpenWidget.cpp
index ced72485..aa6afc2d 100644
--- a/src/gui/DatabaseOpenWidget.cpp
+++ b/src/gui/DatabaseOpenWidget.cpp
@@ -109,10 +109,12 @@ void DatabaseOpenWidget::showEvent(QShowEvent* event)
         connect(YubiKey::instance(), SIGNAL(detectComplete()), SLOT(yubikeyDetectComplete()), Qt::QueuedConnection);
         connect(YubiKey::instance(), SIGNAL(notFound()), SLOT(noYubikeyFound()), Qt::QueuedConnection);
         // clang-format on
 
-        pollYubikey();
-        m_yubiKeyBeingPolled = true;
+        if (!m_credentialsGiven) {
+            pollYubikey();
+            m_yubiKeyBeingPolled = true;
+        }
     }
 #endif
 }
 
@@ -152,8 +154,13 @@ void DatabaseOpenWidget::load(const QString& filename)
 
     m_ui->editPassword->setFocus();
 }
 
+void DatabaseOpenWidget::setCredentialsGiven(bool credentialsGiven)
+{
+    m_credentialsGiven = credentialsGiven;
+}
+
 void DatabaseOpenWidget::clearForms()
 {
     m_ui->editPassword->setText("");
     m_ui->comboKeyFile->clear();
@@ -193,8 +200,11 @@ void DatabaseOpenWidget::openDatabase()
     QApplication::setOverrideCursor(QCursor(Qt::WaitCursor));
     bool ok = m_db->open(m_filename, masterKey, &error, false);
     QApplication::restoreOverrideCursor();
     if (!ok) {
+        m_credentialsGiven = false;
+        pollYubikey();
+        m_yubiKeyBeingPolled = true;
         m_ui->messageWidget->showMessage(error, MessageWidget::MessageType::Error);
         return;
     }
 
@@ -307,9 +317,9 @@ QSharedPointer<CompositeKey> DatabaseOpenWidget::databaseKey()
     if (config()->get("RememberLastKeyFiles").toBool()) {
         config()->set("LastChallengeResponse", lastChallengeResponse);
     }
 
-    if (m_ui->checkChallengeResponse->isChecked()) {
+    if (!m_credentialsGiven && m_ui->checkChallengeResponse->isChecked()) {
         int selectionIndex = m_ui->comboChallengeResponse->currentIndex();
         int comboPayload = m_ui->comboChallengeResponse->itemData(selectionIndex).toInt();
 
         // read blocking mode from LSB and slot index number from second LSB
diff --git a/src/gui/DatabaseOpenWidget.h b/src/gui/DatabaseOpenWidget.h
index 72f07cfa..c7a238ce 100644
--- a/src/gui/DatabaseOpenWidget.h
+++ b/src/gui/DatabaseOpenWidget.h
@@ -39,8 +39,9 @@ class DatabaseOpenWidget : public DialogyWidget
 public:
     explicit DatabaseOpenWidget(QWidget* parent = nullptr);
     ~DatabaseOpenWidget();
     void load(const QString& filename);
+    void setCredentialsGiven(bool credentialsGiven);
     void clearForms();
     void enterKey(const QString& pw, const QString& keyFile);
     QSharedPointer<Database> database();
 
@@ -73,8 +74,9 @@ protected:
     QSharedPointer<Database> m_db;
     QString m_filename;
 
 private:
+    bool m_credentialsGiven = false;
     bool m_yubiKeyBeingPolled = false;
     Q_DISABLE_COPY(DatabaseOpenWidget)
 };
 
diff --git a/src/gui/DatabaseTabWidget.cpp b/src/gui/DatabaseTabWidget.cpp
index 313bfabb..10071205 100644
--- a/src/gui/DatabaseTabWidget.cpp
+++ b/src/gui/DatabaseTabWidget.cpp
@@ -168,8 +168,9 @@ void DatabaseTabWidget::addDatabaseTab(const QString& filePath,
         }
     }
 
     auto* dbWidget = new DatabaseWidget(QSharedPointer<Database>::create(filePath), this);
+    dbWidget->setCredentialsGiven(!(password.isEmpty() && keyfile.isEmpty()));
     addDatabaseTab(dbWidget, inBackground);
     dbWidget->performUnlockDatabase(password, keyfile);
     updateLastDatabases(filePath);
 }
diff --git a/src/gui/DatabaseWidget.cpp b/src/gui/DatabaseWidget.cpp
index 8cfc4081..d1e45c80 100644
--- a/src/gui/DatabaseWidget.cpp
+++ b/src/gui/DatabaseWidget.cpp
@@ -1008,8 +1008,9 @@ void DatabaseWidget::switchToOpenDatabase()
 void DatabaseWidget::switchToOpenDatabase(const QString& filePath)
 {
     updateFilePath(filePath);
     m_databaseOpenWidget->load(filePath);
+    m_databaseOpenWidget->setCredentialsGiven(m_credentialsGiven);
     setCurrentWidget(m_databaseOpenWidget);
 }
 
 void DatabaseWidget::switchToOpenDatabase(const QString& filePath, const QString& password, const QString& keyFile)
@@ -1480,8 +1481,13 @@ bool DatabaseWidget::currentEntryHasTotp()
     }
     return currentEntry->hasTotp();
 }
 
+void DatabaseWidget::setCredentialsGiven(bool credentialsGiven)
+{
+    m_credentialsGiven = credentialsGiven;
+}
+
 bool DatabaseWidget::currentEntryHasNotes()
 {
     Entry* currentEntry = m_entryView->currentEntry();
     Q_ASSERT(currentEntry);
diff --git a/src/gui/DatabaseWidget.h b/src/gui/DatabaseWidget.h
index fb9cf817..14e208e6 100644
--- a/src/gui/DatabaseWidget.h
+++ b/src/gui/DatabaseWidget.h
@@ -106,8 +106,9 @@ public:
     bool currentEntryHasPassword();
     bool currentEntryHasUrl();
     bool currentEntryHasNotes();
     bool currentEntryHasTotp();
+    void setCredentialsGiven(bool credentialsGiven);
 
     void blockAutoReload(bool block = true);
 
     QByteArray entryViewState() const;
@@ -262,7 +263,9 @@ private:
 
     // Autoreload
     QPointer<DelayingFileWatcher> m_fileWatcher;
     bool m_blockAutoSave;
+
+    bool m_credentialsGiven = false;
 };
 
 #endif // KEEPASSX_DATABASEWIDGET_H
```

**Comment by psychotrome** [comment] 2019-05-27 04:25
Hi, found this issue report only after posting on another related one (3054).

Using 2.4.1 and just wanted to comment that this issue doesn't happen, at least for me as long as the key is plugged in continuously from cold boot. As long as it's not unplugged at all even between sleep/wake it'll work fine and KeePassXC won't lock it up.

**Comment by droidmonkey** [comment] 2019-05-29 15:14
I think we should just not auto-poll the Yubikey. I find it annoying when I am testing with a Yubikey plugged in as well. Here is my proposal:

1. Only poll when the "Refresh" button has been pressed, unless
2. The database has previously used a Yubikey to unlock and "Save Keyfiles" is enabled

**Closed** 2020-05-15 00:19 UTC
Labels: bug, plugin: YubiKey
