### ISSUE TITLE
Many dialog boxes have black background and are unreadable

### ISSUE THREAD

**Issue by idontusenumbers** [keepassxreboot/keepassxc#5022] opened 2020-07-10 22:36 UTC
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
About:
![image](https://user-images.githubusercontent.com/1175031/87208182-7250b000-c2d3-11ea-9712-05225aba4c15.png)

Browser access request:
![image](https://user-images.githubusercontent.com/1175031/87208257-afb53d80-c2d3-11ea-9fb1-713b65116826.png)

Delete entry:
![image](https://user-images.githubusercontent.com/1175031/87208287-cfe4fc80-c2d3-11ea-8c27-246adf981c3b.png)

KeePassXC - Version 2.6.0
Revision: 0765954

Qt 5.15.0
Debugging mode is disabled.

Operating system: macOS High Sierra (10.13)
CPU architecture: x86_64
Kernel: darwin 17.7.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by droidmonkey** [comment] 2020-08-03 02:22
You seem to have unique theming problems, unfortunately this is not the case for anyone else as far as I am aware.

**Comment by idontusenumbers** [comment] 2020-08-03 05:22
Is this closed because it's fixed?

**Comment by droidmonkey** [comment] 2020-08-03 10:12
I can't fix something that isn't broken. I think these problems are unique to you

**Comment by idontusenumbers** [comment] 2020-08-03 16:06
They are also unique to keepassxc =)

I tried searching my computer for all other apps that use QtGui.framework. I couldn't reproduce it in any of the other apps: DB Browser for SQLite, Fritzing, SVGCleaner, Wireshark, unetbootin, or Snap Camera.

I'd be happy to provide any logs or preferences.

**Comment by droidmonkey** [comment] 2020-08-03 16:56
That doesn't necessarily mean much, Qt varies wildly with version differences. But without a way to reproduce what you are seeing, it is impossible to fix. Question, are you running keepassxc in Light theme with macOS in dark theme?

**Comment by idontusenumbers** [comment] 2020-08-03 17:02
This bug manifests with the light theme only; the system theme is what I normally use and it doesn't manifest this bug. It seems to me like a default was changed to something meant for the dark theme, or a new variable was introduced for themes but not set for the light theme so it brings in a default or 0.

**Comment by droidmonkey** [comment] 2020-08-03 18:06
What theme is your macOS desktop set to?

**Comment by idontusenumbers** [comment] 2020-08-03 18:09
![image](https://user-images.githubusercontent.com/1175031/89213370-99c13280-d58a-11ea-81f6-597c13933103.png)

**Comment by droidmonkey** [comment] 2020-08-03 19:33
Oh forgot high Sierra does not have a dark mode

**Comment by idontusenumbers** [comment] 2020-08-03 20:05
The native API does have a way to check if the 'dark menu bar and dock' mode is active; although that doesn't sound like something keepassxc should respond to.

**Comment by droidmonkey** [comment] 2020-08-03 22:08
Hmm we are modifying the behavior of the window palette to allow cocoa to draw the background. We choose Qt::Transparent which might be rendering as black on high sierra.

**Comment by droidmonkey** [comment] 2020-09-28 01:42
Duplicate of #5347

**Closed by droidmonkey** 2020-09-28 01:42 UTC
Labels: bug, platform: macOS, theme
