### ISSUE TITLE
Database specific lock-timeouts

### ISSUE THREAD

**Issue by chron-isch** [keepassxreboot/keepassxc#3980] opened 2019-12-05 15:36 UTC
I originally posted this here https://github.com/keepassxreboot/keepassxc/issues/635 but thought it deserved it's own issue and didn't want to highjack the orignal topic.

With the introduction of freedesktop.secrets.service support it's has more or less become necessary to keep at least one database constantly open (or evolution, networkmanager and a lot of other applications will complain about missing password after a while).

Obviously I don't like having ALL my passwords(like crypto keys, work passwords, and so on) exposed/unlocked constantly, so I would like to split it up into multiple databases with diffrent lock-timeouts or in case of the freedesktop.secrets.service database no lock-timeout at all and just lock it when the session is locked or the lid is closed.

Would that even be possible?

**Comment by droidmonkey** [comment] 2019-12-05 15:50
This is a duplicate of #2224

**Closed** 2019-12-05 15:58 UTC
Labels: new feature

**Comment by chron-isch** [comment] 2019-12-05 16:00
Sorry about that, didn't pop up when I was searching for existing issues.

**Comment by droidmonkey** [comment] 2019-12-05 16:52
Its ok, that one is coming in 2.6.0. I like the idea a lot.
