### ISSUE TITLE
import of csv file crashes

### ISSUE THREAD

**Issue by docmorbius** [keepassxreboot/keepassxc#4034] opened 2019-12-17 16:21 UTC
Attempting to import a CSV file crashed every time. First I tried CSV files created by other programs. I tried shorter and shorter files until I got down to one entry. Then I tried a CSV File exported by keepassxc itself.  It still crashed.  I then used an older version of keepassxc (2.3.4) and it worked. The resulting .kdbx file was then readable by the newer version of keepasxc (2.5.1)
## Expected Behavior
I expected version 2.5.1 to be able to import a CSV File without crashing.

## Current Behavior
It appears that 2.5.1 crashes importing any CSV file.

## Debug Info
KeePassXC - Version 2.5.1
Revision: 0fd8836

Qt 5.13.1
Debugging mode is disabled.

Operating system: macOS Mojave (10.14)
CPU architecture: x86_64
Kernel: darwin 18.7.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by phoerious** [comment] 2019-12-17 17:34
Duplicate of #3849.

**Closed by phoerious** 2019-12-17 17:34 UTC
Labels: bug
