### ISSUE TITLE
Font size in Notes is too small

### ISSUE THREAD

**Issue by sazun** [keepassxreboot/keepassxc#10769] opened 2024-05-16 16:02 UTC
After updating to 2.7.8 from 2.7.4 in MacOS the font size in entries notes has reduced and it is almost unreadable.

**Comment by droidmonkey** [comment] 2024-05-16 17:25
Duplicate of #10740, and a fix is already in preparation. For now, you can disable using monospace font for notes in the application settings.

**Closed as completed** 2024-05-16 17:25 UTC
