### ISSUE TITLE
KeepassXC database is requesting save when no save options are set and only AutoType actions undertaken.

### ISSUE THREAD

**Issue by Entreprenerdz** [keepassxreboot/keepassxc#8138] opened 2022-06-11 08:00 UTC
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Using KPXC for normal read-only retrieval and AutoType of credentials sometimes thinks a change has been made, causing annoying save requests.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Browse to a web page where you need to log.  Activate the AutoType key sequence.
2. KeepassXC is presented with Unlock Database.  Press Enter and submit fingerprint for Touch ID integration.
3. Press button on Yubikey to unlock the database.  KPXC plays the AutoType sequence, gaining access to the website.
4. After a period of time, the KeypassXC dock icon starts bouncing.  Switching to the app, you are presented with a "{DATABASE NAME} was modified.  Save Changes?"

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Expect that when timer runs out, database should lock without needing Yubikey to be touched as it should not be re-saving the database.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
User is presented with "Don't Save", "Cancel"(Don't lock), and Save requiring Yubikey to be touched.

## Context
[NOTE]: # ( Give us any additional information you may have. )
I am lost on how to resolve this issue, or how to properly search for a resolution.  I only notice it when it's not working properly, which I would say is 80% of the time.  My specifics are:  Yubikey with HMAC_SHA1 Challenge Response for access.  M1 Macbook running Big Sur.  No browser extension, all AutoType. 1 main database with Yubikey and three others really accessed, never AutoOpened, but I do use the Open with link feature, which is not often, nor is there any correlation as most usage is just the main db with Yubikey.

I have two KeeShares set up, pretty much the entire Main db to share with my other Macbook and one of the 3 other dbs, very small and just contains critical logins to access on my phone which cannot utilize the Yubikey to unlock.

It's gotten to the point that when the bouncing icon starts I just flip over to that screen, it stops, then go back to what I was doing because it happens so much.  So KPXC sits with the popup described above open, waiting for input.

I've tried disabling the KeeShares with no luck.  I believe that I read somewhere that the Yubikey needs to reencrypt the database every time it saves but there should be no reason for it to save, and there are times when it doesn't ask to save so I am quite certain it's some issue.

I've scoured the settings to see if I can find some check box that I've missed but I'm quite certain I have them all set properly as follows:  RIght.  No screen shots... so all 6 checkboxes in teh General Side bar option of Settings, Basic Settings Tab, File Management section are unchecked, so there should be no saving at all.

I'm hoping someone has experienced this or can offer some new ways to attempt to troubleshoot this issue.

[NOTE]: # ( Paste debug info from Help → About KeePassXC - Version 2.7.1
Revision: 5916a8f

Qt 5.15.2
Debugging mode is disabled.

Operating system: macOS 11.6
CPU architecture: arm64
Kernel: darwin 20.6.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.19.1
 )
KeePassXC - VERSION
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS
Windowing System: 

Thank you in advance for your time and effort.

**Comment by droidmonkey** [comment] 2022-06-11 10:27
My first thought is that non data changes are needing to be saved, those are group expand/collapse state, sort order (natural) of the entry list. Is that setting disabled in the application settings?

**Comment by Entreprenerdz** [comment] 2022-06-13 12:59
Yes.  All 5 checkboxes under File Managment are unchecked.

never expand/collapse, sort, or much else other than Search.  But the main sequence is AutoType keypress, unlock TouchID, touch Yubikey, KPXC auto-types credentials.  Then leave it.

Any suggestions on preferred steps to methodically disable features and find the culprit?  I think I've done them all, except new database, that is.

**Comment by droidmonkey** [comment] 2022-06-13 13:03
Keeshare would be my only other guess, make sure they are all turned off

**Comment by Entreprenerdz** [comment] 2022-06-13 13:10
Ya... I was thinking that.  I had them Inactive but I think maybe application wide in settings might be the better route.

A question about that, since I'm here.  I was using Syncthing to keep  my dbs in sync previously, but upon reading about keeshare and what not, it seemed to me that using syncthing has a chance of overwriting a db and potentially losing data, while keeshare is 'merged' which at most would add extra history or full on records.  Is my thinking correct?

Thanks for your time on this question and my issue above.

**Comment by droidmonkey** [comment] 2022-06-13 20:19
The database handling and merge is basically the same between keeshare and normal databases.

**Comment by droidmonkey** [comment] 2023-02-22 02:57
Closing this as it is a duplicate of other keeshare issues.

**Closed as completed by droidmonkey** 2023-02-22 02:57 UTC
