### ISSUE TITLE
Incorrect system tray icon if database file and password are provided via CLI

### ISSUE THREAD

**Issue by Frederick888** [keepassxreboot/keepassxc#2867] opened 2019-03-25 03:57 UTC
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
The icon which does _not_ have a lock is shown in system tray.

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
The icon with a lock is shown.

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. Disable `Load previous databases on startup` in settings
0. Launch KeepassXC via CLI, e.g. `printf '%s' "$password" | keepassxc --pw-stdin /path/to/database.kdbx`

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.4.0
Revision: c51752d

Libraries:
- Qt 5.12.2
- libgcrypt 1.8.4

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 5.0.4-arch1-1-ARCH

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey

**Comment by droidmonkey** [comment] 2019-03-25 12:46
Duplicate of #2828

**Closed by droidmonkey** 2019-03-25 12:46 UTC
Labels: bug
