### ISSUE TITLE
QR-Code for easy credential transfer

### ISSUE THREAD

**Issue by 2tata** [keepassxreboot/keepassxc#10540] opened 2024-04-03 11:38 UTC
## Summary
It would be a nice feature to generate a QR code from the password and the username.

## Examples
There could be entries in the context menu like: "show Password QR-Code"  and  "show Username QR-Code"
And additional when open the keepassxc entry to small buttons for user and pass QR-code. 

## Context
This makes it easy for transferring credentials to phones and tables.

**Comment by phoerious** [comment] 2024-04-03 11:40
Duplicate of #675.
I agree this would be useful, but it's also not without certain risks.

**Closed as completed by phoerious** 2024-04-03 11:40 UTC
Labels: duplicate
