### ISSUE TITLE
Add views for tags / tag-cloud

### ISSUE THREAD

**Issue by OLLI-S** [keepassxreboot/keepassxc#4519] opened 2020-03-29 21:30 UTC
## Summary
Add an easy way to see all entries having a specific tag.

## Details
In the issue **Add Tag Feature** (#508) the "tags" feature from KeePass is requested.
I used tags in KeePass but viewing all entries of a specific tag requires multiple mouse clicks in KeePass.
So please make this feature (viewing all entries with a specific tag) easy accessible.

It would be cool when I can access all entries with a specific tag with one click.
**One way** would be if users can define tags they want to see in the groups.
These views are not folders containing entries, these views just display entries of a specific tag.

Here an example of the two tags "TOTP" and "Favorites":
![image](https://user-images.githubusercontent.com/8037790/77859677-1de56100-720b-11ea-8e4e-c52bdbe3ada1.png)

**An other way** would be to add a tag-cloud that lists all tags used in the database,
As there can be many tags in the database that are not so important (users don't want to see these tags in the tag cloud) I suggest to implement the first way where users can define what tags they want to see.

## Why this is important
For many entries I have to copy the TOTP out of KeePassXC, because they are not automatically filled in the website or because I want to log into an application.
This forces me to search for the entry in KeePassXC and then to copy the TOTP code.
So here I would add the view for the tag "TOTP".

In KeePassXC I often search for the same entries, so it would be cool to define these entries as "Favorite" entries (using the tag "Favorite" and to define also a view for this tag).
So I can access all favorite entries with one mouse click.

**Comment by JosiahCarberry** [comment] 2020-05-12 13:33
I'm not sure how to vote for feature requests. This feature is surely one that I would like, as I have a lot of tags in my kdbx file. They help a lot in the selection of credentials.

**Comment by OLLI-S** [comment] 2020-05-12 18:27
You can donate money for this feature here:
https://www.bountysource.com/issues/90922761-add-views-for-tags-tag-cloud

**Comment by droidmonkey** [comment] 2020-05-12 19:33
@JosiahCarberry 
![image](https://user-images.githubusercontent.com/2809491/81737343-f5858f00-9465-11ea-8289-03a39a6342df.png)

**Comment by droidmonkey** [comment] 2021-10-02 21:25
This is a duplicate of #508 and already being implemented by #6487

**Closed by droidmonkey** 2021-10-02 21:25 UTC
Labels: new feature
