### ISSUE TITLE
KeePassXC would like to control this computer

### ISSUE THREAD

**Issue by yThomasS** [keepassxreboot/keepassxc#3731] opened 2019-10-30 10:05 UTC
## Expected Behavior
After the first question about control this computer, which I deny the program should not ask again.
BTW: why does the program wants to do that in the first place????

## Current Behavior
For every start it is asking again.

## Possible Solution
Click "Deny" on every startup

## Steps to Reproduce
1. Start application 
2. See the question window
![Screen Shot 2019-10-30 at 10 58 23](https://user-images.githubusercontent.com/37152106/67848470-0a6f8600-fb05-11e9-866e-75f4a94cbbd7.png)

## Context
It is annoying and sounds for me like a malicious software.

## Debug Info
KeePassXC - Version 2.5.0
Revision: 1ab8a9f

Qt 5.13.1
Debugging mode is disabled.

Operating system: macOS Mojave (10.14)
CPU architecture: x86_64
Kernel: darwin 18.7.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by phoerious** [comment] 2019-10-30 10:45
This is needed for Auto-Type and not a bug.

Duplicate of #3689.

**Closed by phoerious** 2019-10-30 10:45 UTC
Labels: bug

**Comment by yThomasS** [comment] 2019-10-30 10:56
If this is required for some features then it should be mentioned somewhere. 
And I still think it is a bug if it asked me this on EVERY start.

**Comment by droidmonkey** [comment] 2019-10-30 11:03
We already have this tracked for correction in another issue.

**Comment by yThomasS** [comment] 2019-10-30 11:07
And if it is required for auto-type (not sure what that is) can it not be disabled by default and if you want to switch it on in preferences you will see the note "requires you to enable `Control this computer` in Security & Privacy"

**Comment by neunzehnachtneun** [comment] 2019-11-11 11:26
But why is this needed in 2.50? In 2.4.3 auto-type is working very well without granting access to keepassxc.

**Comment by phoerious** [comment] 2019-11-11 11:30
It's a change in Catalina.

**Comment by neunzehnachtneun** [comment] 2019-11-11 11:55
But even it's a change in Catalina, why does it also affect Sierra?

**Comment by neunzehnachtneun** [comment] 2019-11-25 09:49
@phoerious @droidmonkey Any comment?

**Comment by phoerious** [comment] 2019-11-25 10:10
KeePassXC does not run in confined mode, so there is nothing KeePassXC couldn't do anyway on older macOS versions.

**Comment by zrml** [comment] 2022-11-18 08:05
same issue with v2.7.4 -- this should be at least documented somewhere. FWIW I could not find it. Thanks KPXC team!
