### ISSUE TITLE
Copy shortcut is broken and actually copies password despite what is selected

### ISSUE THREAD

**Issue by chbndrhnns** [keepassxreboot/keepassxc#1894] opened 2018-05-02 17:03 UTC
Copy shortcut is broken and actually copies password despite what is selected

## Expected Behavior
The selected text is copied.

## Current Behavior
The default copy action is carried out (copy password)

## Possible Solution
Right click selection, choose copy

## Steps to Reproduce (for bugs)
1. Select an attribute of a database entry
2. hit CMD+C to copy it
3. Paste in a text editor

## Context
Exposing  passwords when I did not want it

## Debug Info
KeePassXC - Version 2.3.1
Revision: 2fcaeea

Bibliotheken:
- Qt 5.9.3
- libgcrypt 1.8.2

Betriebssystem: macOS High Sierra (10.13)
CPU-Architektur: x86_64
Kernel: darwin 17.5.0

Aktivierte Erweiterungen:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by droidmonkey** [comment] 2018-05-02 17:50
Duplicate of #1653

**Closed by droidmonkey** 2018-05-02 17:50 UTC
